### PR TITLE
Include Array and String generic methods

### PR DESCRIPTION
**Pull request by SebastianSimon**
> What was wrong/why is this fix needed? (quick summary only)

Array and String generic methods were a set of deprecated JavaScript features which are now obsolete, but they’re missing from the list of deprecated and obsolete features.

> Issue number (if there is an associated issue)

None.

> Anything else that could help us review it

Sources:

* [Firefox 53 release notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/53#javascript)
* [Firefox 68 release notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/68#javascript)
* [Firefox 71 release notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/71#javascript)
* [Archive.org: MDN docs for String generic methods](https://web.archive.org/web/20170629115020/https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#String_generic_methods)
* [Archive.org: MDN docs for Array generic methods](https://web.archive.org/web/20160403085740/https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Array_generic_methods)

### CODE REVIEW

**Comment by teoli2003** [comment]
We should fix the link at https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/53#javascript at the same time.

**Comment by sideshowbarker** [comment]
> We should fix the link at [developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/53#javascript](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/53#javascript) at the same time.
> 
> (Fix = remove the link)

Pushed a change to remove that

**Comment by sideshowbarker** [comment]
@SebastianSimon Should I hold off on merging this til @Rumyra has approved it?

**Review by sideshowbarker — APPROVED** [review]

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
This seems straightforward, so I’m going ahead with merging it. If further refinements are needed, they could be done in a follow-up PR.

**Pull request merged**
