### PR TITLE
Update BCD info, part 5

### PR DESCRIPTION
**Pull request by OnkarRuikar**
Adding to #19185 

The PR updates BCD info in WebAPI docs.

Note: It's easy to review the changes. Open the preview URLs hosted by the PR companion, in new tabs, and look at the BCD tables at the bottom of the pages.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by random-vincent** [comment]
@OnkarRuikar 
Hi, Ruikar! 
I would like to confirm the accuracy of that `securitypolicyviolation_event` was deprecated.
I can still look up this event in the [standard](https://w3c.github.io/webappsec-csp/#reporting) now.
Where is this news that `securitypolicyviolation_event` was deprecated coming from?

Thank you!

**Comment by teoli2003** [comment]
We reflected what is indicated in mdn/browser-compat-data. This may be wrong there (if so, we'll need to fix it at both places).

MDN (content) is moving to merely reflect the data stored at mdn/browser-compat-data.

**Comment by OnkarRuikar** [comment]
> Where is this news that `securitypolicyviolation_event` was deprecated coming from?

The event is associated with 3 interfaces: https://github.com/mdn/browser-compat-data/search?q=securitypolicyviolation_event

They marked it `deprecated` under `Element` interface here: https://github.com/mdn/browser-compat-data/pull/12333
But it's still alive on global scope e.g. https://github.com/mdn/browser-compat-data/blob/bcd97a7a61d9b63c5caa4b15cbac26c18be51f65/api/Document.json#L6531

If you wish to change any compatibility data then raise an issue here: https://github.com/mdn/browser-compat-data/issues

**Comment by teoli2003** [comment]
@hamishwillee Was the use of the deprecated flag an oversight (bad cut & paste)?

**Comment by hamishwillee** [comment]
@teoli2003 @OnkarRuikar It is hard to be absolutely certain given the time that has gone by, but I would say yes - this was an error. I certainly do not recall any specific information that it should be deprecated, and if the specs do not provide indication of this, then revert.

**Pull request merged**
