### PR TITLE
Add new tail-call WASM features

### PR DESCRIPTION
**Pull request by pepelsbey**
### Description

- Adds two new tail-call versions of the call function: `return_call` and `return_call_indirect`.
- Mentions two sources of information on the WASM tail call functions.

### Motivation

To support enabled tail calls in Firefox 121.

### Related issues and pull requests

- https://github.com/mdn/content/issues/30333
- https://github.com/mdn/interactive-examples/pull/2693 — potential demo for the `return_call`

### CODE REVIEW

**Comment by pepelsbey** [comment]
@eqrion could you please have a look?

**Comment by yurydelendik** [comment]
The specification also adds `return_call_ref` instruction. This instruction added to complement `call_ref`, and was part of the function references / GC specification as well (which are landed before tail calls). See https://github.com/WebAssembly/function-references/blob/main/proposals/function-references/Overview.md

**Comment by pepelsbey** [comment]
@yurydelendik the question is the browser support, we don’t document spec-only features, only the ones that are implemented in browsers. Do you know anything about it?

**Comment by yurydelendik** [comment]
> @yurydelendik the question is the browser support, we don’t document spec-only features, only the ones that are implemented in browsers. Do you know anything about it?

Firefox implements function references and GC proposal in version 120, and tail calls proposal in 121. (Chrome implemented them in other order)

**Comment by yurydelendik** [comment]
See also https://webassembly.org/roadmap/

**Comment by pepelsbey** [comment]
> Firefox implements function references and GC proposal in version 120, and tail calls proposal in 121

Yes! That’s the reason we’re updating the docs. But is it just `return_call` and `return_call_indirect` or `return_call_ref` is also implemented in Chrome and Firefox? I don’t see V8 mentioning it [in the blog post](https://v8.dev/blog/wasm-tail-call).

**Comment by yurydelendik** [comment]
> I don’t see V8 mentioning it [in the blog post](https://v8.dev/blog/wasm-tail-call).

The V8 implemented it with Wasm GC proposal since they released tail calls long ago -- the `return_call_ref` is part of both proposals (GC and tail calls).

**Comment by yurydelendik** [comment]
> If so, I’ll file another issue to document `return_call_ref` on the same page.

That's fine. This detail is not really important since it was discussed internally in the meetings. `return_call_ref` can be document with any proposals.

**Review by bsmth — APPROVED** [review]
Thank you!

**Pull request merged**
