### PR TITLE
How to transitions

### PR DESCRIPTION
**Pull request by rachelandrew**
An example for the CSS Learn section of using transitions.

### CODE REVIEW

**Review by chrisdavidmills — COMMENTED** [review]
Hi @rachelandrew !

This is looking really good. I've got a few comments and suggestions, some of which relate to this article in particular, and some of which relate to handling subjects like translations in general. Most of this is kind of take it or leave it really, discussion points.

1. I'd expect a button to transition a bit quicker than 2 seconds; maybe have the default value as 1 second?
2. I'd also expect a button to change style when clicked to show a  response. I know that bit isn't the pointof this tutorial, but maybe include something simple anyway, so it is a more complete solution that someone can use?
3. In the same vein as comment 2, maybe also add a `cursor:pointer` property to provide more of a visual hint that this can be clicked?
4. In general, I think it's very well written. I do wonder if it should be titled something more generic like "How to fade an element on hover" so that it is clearer that this doesn't just apply to buttons, even if that is the most common use case?
5. More generically, how were you thinking of breaking up these hover/transition type topics into howto articles? What would the other titles be like? "How to move an element across the screen on hover"? "How to fade an element out on click"? etc? Or would it help to have more generic articles to begin with, like "How to animate an element" to explain the basics, and then more on to more specifics in followups?
6. I think realistically, the best approach would be to have two different sets of articles that work together — the howtos, like you are currently explaoring, and a related animation cookbook that explores the subject in a more. The howtos each give an explanation and a copy and pasteable solution for a specific common question, like you are doing, and then the cookbook explains each piece of the puzzle in more depth and takes a more bolt-on type approach, e.g. first we have the basics, now let's choose a thing to animate, now let's choose a type of animation, now let's add a delay, now let's choose a timing function, etc., with lots of possible combinations to get the result you actually want. What do you think?

**Comment by rachelandrew** [comment]
@chrisdavidmills I'm a bit confused because this wasn't anything to do with an "animation cookbook", this is just another one of those CSS how tos I was doing to replace the questions that no-one asks. So I hadn't thought about any of the things above, it's a standalone like the others.

**Comment by rachelandrew** [comment]
Document is linked from the issue: https://github.com/mdn/content/issues/1080

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills I'm a bit confused because this wasn't anything to do with an "animation cookbook", this is just another one of those CSS how tos I was doing to replace the questions that no-one asks. So I hadn't thought about any of the things above, it's a standalone like the others.

My apologies; I'm getting a bit ahead of myself here. I think we have talked about cookbooks before, but obviously quite a bit less than I thought we had. How about you ignore points 5 and 6 for now, and we'll revisit those later on, when you are finished with the howto updates?

**Comment by rachelandrew** [comment]
@chrisdavidmills I think at one point you mentioned an animation one would be nice to have, but it would need some planning. I can do that, but that isn't my aim with these. The idea with these was to try and show a single concept clearly and link people into the docs to read more.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills I think at one point you mentioned an animation one would be nice to have, but it would need some planning. I can do that, but that isn't my aim with these. The idea with these was to try and show a single concept clearly and link people into the docs to read more.

Makes sense, thanks.

**Comment by rachelandrew** [comment]
@chrisdavidmills sorry to be picky but point 4 seems at odds with 2 and 3. Either this should be generic OR it should be about a button and have button features. I'd probably rather make it generic as I would rather these explained a single thing simply than try to demonstrate multiple things at one.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills sorry to be picky but point 4 seems at odds with 2 and 3. Either this should be generic OR it should be about a button and have button features. I'd probably rather make it generic as I would rather these explained a single thing simply than try to demonstrate multiple things at one.

I see the point of what you are saying here. If it were more generic, then there would be no point in having specific styles for a button.

I like the idea of making it generic so it is suitable for more situations, but I also worry that people are more likely to do specific searches for exactly what their problem is, not more generic searches. So having thought about it a bit more, I think I'd rather it be specifically about a button.

What do you think?

Then 2 and 3 would still apply. I think we should still just explain the one thing we are demonstrating here, rather than trying to explain everything that appears in the article.

**Comment by rachelandrew** [comment]
@chrisdavidmills realised this one had been abandoned, sorry about that! I've just fixed it up as requested.

**Pull request merged**
