### PR TITLE
fix typo: tte -> the

### PR DESCRIPTION
**Pull request by Haroenv**

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
LGTM, thanks @Haroenv !

**Review by rachelandrew — APPROVED** [review]
thanks!

**Comment by Haroenv** [comment]
Thanks for keeping MDN such a nice place @chrisdavidmills and @rachelandrew !

**Comment by chrisdavidmills** [comment]
And thank you for your contribution, @Haroenv ; we really appreciate it.

**Pull request merged**
