### PR TITLE
NodeList: Fix method name

### PR DESCRIPTION
**Pull request by ansgarprause**
#### Metadata

- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by teoli2003** [comment]
Thanks for the PR. But we don't add _prototype_ in the API section. Thanks again.

**Comment by ansgarprause** [comment]
@teoli2003 Thanks, I should have realized.
I was misled by the fact that the next sentence says `Array.prototype.forEach()` but I guess that makes sense in this particular case.

**Comment by teoli2003** [comment]
No worry, yes we add them in the JavaScript area.

**Comment by ansgarprause** [comment]
I see. 👍

**Pull request closed without merging**
