### PR TITLE
remove hidden bcd paragraph of web/svg and web/http

### PR DESCRIPTION
**Pull request by peterbe**
Part of #2228

### CODE REVIEW

**Comment by peterbe** [comment]
@teoli2003 I used https://gist.github.com/peterbe/d8f34b3d058a7647f03b65e7e98c50cc to do these. 
Would you mind reviewing this and then see if you can run that Python script on a bunch of other trees? (see line 50 for how to pick the sub-trees)

**Comment by peterbe** [comment]
Due to [a bug in the PR Review Companion](https://github.com/mdn/yari/issues/3902) unfortunately no preview URLs posted. I'm going to try to fix this today.

**Comment by teoli2003** [comment]
Changes here LGTM (I like you removed the extra empty line, my sed scripts didn't). I will use your python scripts on more trees.

**Comment by peterbe** [comment]
Let's let @mirunacurtean take care of the formal review plus merge.

**Review by mirunacurtean — APPROVED** [review]
Checked all files and only the hidden BCD paragraph was removed along with some extra empty lines so this should go ahead with no issues.

**Pull request merged**
