### PR TITLE
Fix inconsistencies in "HTML attribute: step" doc

### PR DESCRIPTION
**Pull request by nwhittaker**
### Description

Fixes a typo in the **min impact on step** section where the default `step` value is said to be `0` instead of `1`.

### Motivation

Otherwise the doc is inconsistent with what it claims the default `step` value to be.

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
Hi @nwhittaker, and thanks for your contribution to MDN!

Your change is correct, but I also wondered if you fancied correcting the example description, starting with the following line:

> Then define an input with a minimum value of 7.2, omitting the step attribute, wherein it defaults to 1.

This is an incorrect description of the code below, as `step` is not omitted; it is set to `2`. And the min value set is `1.2`, not `7.2`.

Also, the text starting `Valid values include...` is not accurate — it says number values with decimals are invalid, which is nonsense. If you try the live example, `1.2`, etc. do not show as invalid. If you try a value like `a`, the red border is immediately shown.

Let me know what you think.

**Comment by nwhittaker** [comment]
@chrisdavidmills, happy to roll in other changes.

---
>>Then define an input with a minimum value of 7.2, omitting the step attribute, wherein it defaults to 1.
>
>This is an incorrect description of the code below, as `step` is not omitted; it is set to `2`. And the min value set is `1.2`, not `7.2`.

I think this is a straightforward enough change.

---
>Also, the text starting `Valid values include...` is not accurate — it says number values with decimals are invalid, which is nonsense. If you try the live example, `1.2`, etc. do not show as invalid. If you try a value like `a`, the red border is immediately shown.

The author does say _even_ numbers with a `.2` decimal are invalid which _is_ accurate given the constraints: `Integers and even numbers followed by .2 are not valid.` However, I'd agree it's still confusing since those aren't the only decimal numbers that are invalid (e.g. `1.3`, `2.1`, etc…). May be easier to describe the values that are valid instead of the ones that are invalid?

I also don't get what is meant by, `As we included an invalid value, supporting browsers will show the value as invalid.` I'm guessing the input's `value` was initially set with an invalid number at one point? Any reason to keep this sentence?

I'll take a stab at rewording some of this, but interested in any feedback you may have regarding specific wording you'd like to see.

**Review by chrisdavidmills — APPROVED** [review]
@nwhittaker your changes look great, thanks!

I've also made a commit to the branch to do a bit of text cleaning and restructuring in other places; after reviewing your changes I kept noticing other things, and couldn't leave it alone ;-)

I'll leave it like this for now, so that you can chime in if there is anything else you'd like to update, and the system can regenerate the preview link so I can test it and make sure my changes work.

**Review by nwhittaker — COMMENTED** [review]
>I'll leave it like this for now, so that you can chime in if there is anything else you'd like to update…

@chrisdavidmills, all looks good to me -- thanks for the help!

**Comment by chrisdavidmills** [comment]
> > I'll leave it like this for now, so that you can chime in if there is anything else you'd like to update…
> 
> @chrisdavidmills, all looks good to me -- thanks for the help!

Perfect, thanks again @nwhittaker!

**Pull request merged**
