### PR TITLE
Add Performance section to JS Set doc, + fix flaw

### LINKED ISSUE #4712: Content suggestion: Can we add Internal data structure used by set?
## What is the new suggestion?
Internal data structure used by set.

## Why is it important or useful?
Useful to know what would be the tradeoffs when a programmer uses an inbuilt set in the code. What are the time complexity and space complexity of the data structure?
How many pages are likely to be needed? 1 paragraphs on the set page.
How much time do you think this work should take? A few hours? 
Will the work enable learners or professionals to achieve their goals better? yes
Does it address critical needs in the web industry? Don't know (I need comments on this)
Is the work an operational necessity, i.e. is not having it a security risk? No security risk
Does the content help make the web more ethical? No
 -->

## Other supporting information

<!-- include any other useful supporting information, such as spec URL,
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

### PR DESCRIPTION
**Pull request by sideshowbarker**
Fixes https://github.com/mdn/content/issues/4712

### CODE REVIEW

**Comment by namit-piriya** [comment]
Are there any known data structures that we can list in the docs for the popular engines like  v8, spider monkey and chakra?
For example, if v8 uses a binary search tree for implementation of set Object (only my assumption) we could list that. 
if that's a possibility I couldn't find it. Even though v8 is open source.
Or could you point me to that?

**Comment by sideshowbarker** [comment]
> Are there any known data structures that we can list in the docs for the popular engines like v8, spider monkey and chakra?
> For example, if v8 uses a binary search tree for implementation of set Object (only my assumption) we could list that.

I think it’s very much out of scope for us to try to document anything in MDN about specific low-level internal implementation details/design of particular JavaScript engine implementations.

For one thing, the details/design of a particular JavaScript engine can change (they all in fact have changed significantly over time), and so even if we documented some current specific implementation detail about a particular engine, there is always a possibility that engine could change later, and then what we had documented in MDN about it would become out of date.

The scope of what we attempt here should be limited in the way that @Andrew-Cottrell described at https://github.com/mdn/content/issues/4712#issuecomment-842116939:

> The [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) page could reflect that requirement using simple language that doesn't assume the reader is familiar with the terms ["hash table"](https://en.wikipedia.org/wiki/Hash_table) or ["sublinear"](https://en.wikipedia.org/wiki/Time_complexity#Sub-linear_time).

…and that can be achieved by @Andrew-Cottrell’s suggested in https://github.com/mdn/content/issues/4712#issuecomment-842116939:

> **Performance:** the [`has`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has) method checks if a value is in a `Set` object using an approach that is, on average, quicker than testing most of the elements that have previously been added to the `Set` object. In particular, it is, on average, faster than the [`Array.prototype.includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) method when an `Array` object has a `length` equal to a `Set` object's `size`.

That’s the level of detail that’s appropriate for MDN. Trying to provide more information than that about specific implementation details that particular engines currently have would not be appropriate for MDN.

**Review by wbamberg — CHANGES_REQUESTED** [review]
I like the content of this, but I think it should not be the first H2 in the page. It should be an H3 in "Description", after the "Value equality" H3.

**Comment by sideshowbarker** [comment]
> I like the content of this, but I think it should not be the first H2 in the page. It should be an H3 in "Description", after the "Value equality" H3.

Yup, makes sense — made it so

**Review by wbamberg — APPROVED** [review]
👍 looks great, thanks for the updates!

**Comment by namit-piriya** [comment]
> I think it’s very much out of scope for us to try to document anything in MDN about specific low-level internal implementation details/design of particular JavaScript engine implementations.

makes sense, after all, there are 3 engines and they will change the details from time to time.
And again we will have to change the documentation else it will be containing old information.

**Pull request merged**
