### PR TITLE
Remove the overuse of 'basic computer literacy' as a prerequisite.

### PR DESCRIPTION
**Pull request by dtKinger**
### Description

This PR aims to remove what is, in my opinion, the overuse of "Basic computer literacy" as a prerequisite for topics. I feel that this tag can be used in high-level topics when no harder prerequisites are listed, but that that should be the extent of its use. 

### Motivation

My goal is to make the docs more accurate and inclusive, and more quickly scanned by a reader to determine that they are fit to digest the content. 

While diving into the express docs, I noticed that "Basic computer literacy" was listed as a prerequisite... It felt superfluous at best and slightly arrogant at worst. That led me to look how pervasively the phrase was used throughout MDN docs and I feel that 89/91 instances could probably be removed.

### Additional details

Thanks for reading and reviewing my PR. I'd be happy to discuss my rationale more deeply if this is a contentious topic.

### Related issues and pull requests

~~I'm not sure. I haven't scanned the issues list, nor did I open one for this.~~
After taking a closer look, I don't believe there are any open issues related to this.

### CODE REVIEW

**Comment by dtKinger** [comment]
I should also mention, the two files containing 'basic computer literacy' that I left unchanged are:
- https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/first_steps/website_security/index.md
- https://github.com/mdn/content/blob/main/files/en-us/learn/front-end_web_developer/index.md

**Review by chrisdavidmills — APPROVED** [review]
Hi there @dtKinger! Thanks a lot for the careful consideration you've given this section of MDN, and for the thoughtful changes. Speaking as the original author of many of these articles (and editor of many others), I think we included the basic computer literacy prereq as a kind of catch-all to make sure that we don't get complete beginners to computing attempting these tutorials and being disappointed. I recall teaching a face-to-face JS basics session once where a bunch of folks turned up and were really annoyed that they didn't understand any of it — turned out they barely knew how to use a mouse, so it was totally the wrong level for them.

However, this isn't normal. I have looked through all the updated page previews, and think your changes make total sense. It feels weird to include that prereq everywhere, when many of the articles are so far above that level. And it adds a lot of noise, making it somewhat harder to decipher the level of the articles.

Approved and merging. Thanks again!

**Comment by dtKinger** [comment]
@chrisdavidmills wow, thanks for a quick but thoughtful review and merge! I appreciate you considering my input. And for the fun anecdote 😅.

This was my first time contributing to an open-source project and TBH I expected backlash and someone saying "this is what we've always done, let's not break it in case it's helping someone". But the way you phrase the problem is precisely how I feel:
>  It feels weird to include that prereq everywhere, when many of the articles are so far above that level. And it adds a lot of noise, making it somewhat harder to decipher the level of the articles.

I've consumed so much of MDN web docs while studying this past year, so a big thank you for your personal contributions to the knowledge base!

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills wow, thanks for a quick but thoughtful review and merge! I appreciate you considering my input. And for the fun anecdote 😅.

You are totally welcome @dtKinger! It isn't usually quite that quick, but you caught me at a New Year's Day lull ;-)
 
> This was my first time contributing to an open-source project and TBH I expected backlash and someone saying "this is what we've always done, let's not break it in case it's helping someone". But the way you phrase the problem is precisely how I feel:

I like to think we are a bit more welcoming than that on MDN. If we do get any complaints, we can always consider reverting it later, but I'm confident this is a good change. If you ever want to make a change in future but you're unsure about it, feel free to open an issue on the repo and we can discuss it. If it is inside the MDN learning area especially, feel free to at-mention me on the issue so I get pinged.
 
> I've consumed so much of MDN web docs while studying this past year, so a big thank you for your personal contributions to the knowledge base!

I love learning and teaching web. It's what I do ;-)

**Pull request merged**
