### PR TITLE
A kitchensink page

### PR DESCRIPTION
**Pull request by peterbe**
Part of #7

I'll share more about how I built this later. 

Can you please review the macros used and think of some that aren't used? @schalkneethling @escattone

### CODE REVIEW

**Review by alshamiri5 — APPROVED** [review]

**Comment by peterbe** [comment]
@schalkneethling The worse thing is that one can't include more than one `<div id="Quick_Links">` so there's no way to include all the various sidebars. One option for that would be to make one kitchensink page for every sidebar macro :(
Can you think of any other type of element that you have to keep an eye on when working on Fiori? 
My goal here is that you (apart from the lack of various sidebars) just need to open this one page to check that your document SCSS fixes all the things possible.

**Comment by schalkneethling** [comment]
> The worse thing is that one can't include more than one `<div id="Quick_Links">` so there's no way to include all the various sidebars. One option for that would be to make one kitchensink page for every sidebar macro

That is what Storybook is for 😄  We can create different variations by providing different input to the `RenderSidebar` component.

**Comment by peterbe** [comment]
> > The worse thing is that one can't include more than one `<div id="Quick_Links">` so there's no way to include all the various sidebars. One option for that would be to make one kitchensink page for every sidebar macro
> 
> That is what Storybook is for 😄 We can create different variations by providing different input to the `RenderSidebar` component.

Yes and no. You can only do components in Storybook. I.e. TS code things in the `src/`. 
There are a bunch of HTML things that only appear in the content either has hardcoded HTML or as KS macros.

**Review by schalkneethling — APPROVED** [review]
r+

**Pull request merged**
