### PR TITLE
Warn about finding undefined in array

### PR DESCRIPTION
**Pull request by omrimeshulami**

### CODE REVIEW

**Comment by schalkneethling** [comment]
Welcome to the community, @omrimeshulami 🦖 - To help the reviewer understand why the warning is added, please update the description of this pull request and include your reason(s) for suggesting the update. Thanks!

**Review by Josh-Cena — COMMENTED** [review]
I get the point of the warning, but (1) please move it to the "Return value" section (2) please add the same text to `findLast`.

**Review by Woodpile37 — COMMENTED** [review]
[Update index.md]

**Review by Woodpile37 — COMMENTED** [review]
update

**Comment by Josh-Cena** [comment]
Hi @omrimeshulami I'm going to close this PR. While I get your intention, I can't think of any tangible case where one would fall into this pitfall. This would be better suited with an example, and I'll gladly re-open if you could comment below with a real-world case where one would be tripped up by this behavior.

**Pull request closed without merging**
