### PR TITLE
Synchronize with BCD v5.5.6

### PR DESCRIPTION
**Pull request by OnkarRuikar**
[BCD release v5.5.6](https://github.com/mdn/browser-compat-data/releases/tag/v5.5.6)

/cc @queengooborg @sideshowbarker

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by dipikabh** [comment]
Hi @OnkarRuikar, I am surprised to see the [update to the `css/ray` file here](https://github.com/mdn/content/pull/31694/files#diff-a14f4053897871ad7fca251e6f17d2a661e44dc27fc2e06bdbbf3f95857f8a30), especially because the same changes were merged [via #31514](https://github.com/mdn/content/pull/31514/files#diff-a14f4053897871ad7fca251e6f17d2a661e44dc27fc2e06bdbbf3f95857f8a30) on Jan 10, just a couple of days before #31694, merged Jan 13.

Could it be because some automated BCD process did not pick up the latest content files?

cc @teoli2003

**Comment by OnkarRuikar** [comment]
> Could it be because some automated BCD process did not pick up the latest content files?

This is because content PR got merged before BCD PR went live. 
- On 10th BCDv5.5.5 went live
- On 11th your PRs go merged, then the bot synced BCDv5.5.5 with content at midnight reverting content changes.
- On 12th BCDv5.5.6 went live with the BCD PR.
- On 13th at midnight the bot synced v5.5.6 auto correcting the status.

The issue was your content change got merged(11th) before BCD PR went live in v5.5.6(12th).

**Comment by dipikabh** [comment]
Thanks for the breakdown of events, @OnkarRuikar.

> On 11th your PRs go merged, then the bot synced BCDv5.5.5 with content at midnight reverting content changes.
> On 13th at midnight the bot synced v5.5.6 auto correcting the status.

Ideally the bot should not have reverted the content updates. But if that's going to be the case, maybe we (especially those of us who update content for Firefox releases and assess an overall standing of the feature across browsers) should stop making the changes in `mdn/content` that are going to get sync'ed with a BCD release anyway (changes involving the banner macros and status field in front matter). I'll let the team know.

**Pull request merged**
