### PR TITLE
chore(ci): Re-enable Prettier check on pull requests

### PR DESCRIPTION
**Pull request by queengooborg**
Now that #28228 has landed, which introduces a review bot for Prettier formatting, I think we're ready to re-enable Prettier formatting checks.  This PR does just that.

### CODE REVIEW

**Comment by OnkarRuikar** [comment]
The Prettier is being [run already in reviewdog.yml](https://github.com/mdn/content/blob/2b649ca83589bf827d99db5d450c0c65a9de7a24/.github/workflows/reviewdog.yml#L39). Why do we want to run Prettier twice? Why do we want to report the issues twice?

**Comment by yin1999** [comment]
> The Prettier is being [run already in reviewdog.yml](https://github.com/mdn/content/blob/2b649ca83589bf827d99db5d450c0c65a9de7a24/.github/workflows/reviewdog.yml#L39). Why do we want to run Prettier twice? Why do we want to report the issues twice?

I chatted with @queengooborg about the following idea yesterday:

Maybe we could merge this with reviewdog into _one_ workflow, as GitHub support [`failure` with conditions](https://docs.github.com/en/actions/learn-github-actions/expressions#example-of-failure-with-conditions). So we could only run reviewdog to post seggestions when the style check is failed. And the failed ci could still let the maintainer know there is something need to be done before merging the PR.

**Comment by OnkarRuikar** [comment]
> I chatted with @queengooborg about the following idea yesterday:
> 
> Maybe we could merge this with reviewdog into _one_ workflow, as GitHub support [`failure` with conditions](https://docs.github.com/en/actions/learn-github-actions/expressions#example-of-failure-with-conditions). So we could only run reviewdog to post seggestions when the style check is failed. And the failed ci could still let the maintainer know there is something need to be done before merging the PR.

We don't have to do the linting twice even in same wokflow. :nerd_face:\
Why not straight up do the `--fix` step? It gives us fixes as well as failure logs. Could you look at my PR that includes all the linters with reviewdog: https://github.com/mdn/content/pull/28240

**Comment by queengooborg** [comment]
Closing as it has been superseded.

**Pull request closed without merging**
