### PR TITLE
Fixed svg file

### LINKED ISSUE #6340: Issue with "Video and audio content": (typo)
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content

#### What information was incorrect, unhelpful, or incomplete?
image

#### Specific section or headline?
Contents of a media file

#### What did you expect to see?
English words

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/video_and_audio_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/video_and_audio_content/index.html
* Last commit: https://github.com/mdn/content/commit/bb51655f7c0823e364fecb9a6c5ee0e5d04ca28f
* Document last modified: 2021-06-03T15:52:42.000Z

</details>

### PR DESCRIPTION
**Pull request by NegiAkash890**
> What was wrong/why is this fix needed? (quick summary only)

Minor correction to svg file

> Issue number (if there is an associated issue)

Fixes #6340

### CODE REVIEW

**Review by wbamberg — CHANGES_REQUESTED** [review]
Thanks @NegiAkash890 ! This does fix the letter spacing in "and so forth", but the image seems to have shrunk and the text is quite hard to read:

***********
Screen Shot 2021-06-25 at 10 42 11 AM

***********

...compared with the original:

************
Screen Shot 2021-06-25 at 10 42 27 AM

************

**Comment by NegiAkash890** [comment]
Ok I fix this soon!

**Comment by sideshowbarker** [comment]
@NegiAkash890 This one seems to be waiting on you

**Comment by NegiAkash890** [comment]
> @NegiAkash890 This one seems to be waiting on you

@sideshowbarker , Thanks for the reminder. I tried editing the original svg file on online svg editors. But it seems that svg in fine.

Screenshot :  
image

But when same svg file is opened in the browser the behavior is different (underlined portion)  :

Screenshot :

image

**Comment by sideshowbarker** [comment]
@NegiAkash890 The image shown in https://user-images.githubusercontent.com/55234838/126427544-9ae7cb50-12e9-4513-9896-e077cc4e522f.png mostly looks fine — except it still has extra space in the “Aud io Tracks” box.

What I’d suggest is that you fix that “Aud io Tracks” space problem, and then just export the whole thing to PNG — and crop it if needed so that it doesn’t have a bunch of extra whitespace around it (which I think is what was causing the problem that @wbamberg commented on).

The original SVG source of this image really just seems to be a big mess. It’s more trouble to work with than it’s worth. And I can see no good reason why we need to keep maintaining this diagram as an SVG image at all. So I think it would be easier at this point to convert it to PNG — with the text-spacing problems fixed. Or else just completely re-create it from scratch. (Even re-creating it from scratch would seem like less work than trying to keep working with the current SVG source.)

**Comment by wbamberg** [comment]
Yeah, I agree with the plan of making this a PNG, and the page looks good now: https://pr6346.content.dev.mdn.mozit.cloud/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content#using_multiple_source_formats_to_improve_compatibility . Thanks!

But you're getting a CI error because Yari wants you to compress the file:

```
/home/runner/work/content/content/files/en-us/learn/html/multimedia_and_embedding/video_and_audio_content/containersandtracks.png is 85.6KB can be compressed to 33.6KB (61%)
Consider running again with '--save-compression' and run again to automatically save the newly compressed file.
HINT! Type the following command:

	yarn filecheck "files/en-us/learn/html/multimedia_and_embedding/video_and_audio_content/containersandtracks.png" --save-compression
```

**Review by wbamberg — APPROVED** [review]
👍 thanks @NegiAkash890 for your work on this!

**Comment by sideshowbarker** [comment]
@NegiAkash890 Nice work 👍

**Pull request merged**
