### PR TITLE
Learn - remove tag attribute form front matter, part 2

### PR DESCRIPTION
**Pull request by OnkarRuikar**

### CODE REVIEW

**Review by hamishwillee — APPROVED** [review]
Looks great! Thank you.

**Comment by teoli2003** [comment]
For bookkeeping purposes: mdn/mdn#262

**Comment by dunkhi** [comment]
Why is there a comma after the type attribute but not after the other attribute names for the input control?

`input#name.form-control(type='text', placeholder='Fantasy, Poetry, etc' name='name' `

**Comment by teoli2003** [comment]
On which of the 168 files this PR updated?

**Comment by OnkarRuikar** [comment]
> Why is there a comma after the type attribute but not after the other attribute names for the input control?
> 
> `input#name.form-control(type='text', placeholder='Fantasy, Poetry, etc' name='name' `

Comma is optional in attributes in PUG. I think the missing comma has to do with the Prettier setting: https://prettier.github.io/plugin-pug/guide/pug-specific-options.html#as-needed

***

@teoli2003  This is not related to the PR. I believe it related to https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form#view.

**Pull request merged**
