### PR TITLE
typo: Double words with Vale

### PR DESCRIPTION
**Pull request by nschonni**
Took a pass over with https://github.com/errata-ai/vale.
Not all of the doubles are wrong (but sometimes might be awkward english for others to understand). Here is the remaining ones
```
% vale .

 files/en-us/games/examples/index.html
 58:72  error  'Nom' is repeated!  Vale.Repetition 


 files/en-us/games/techniques/control_mechanisms/other/index.html
 9:5      error  'Makey' is repeated!  Vale.Repetition 
 165:22   error  'MaKey' is repeated!  Vale.Repetition 
 173:151  error  'MaKey' is repeated!  Vale.Repetition 


 files/en-us/glossary/flex/index.html
 10:161  error  'to' is repeated!  Vale.Repetition 


 files/en-us/learn/css/css_layout/grids/index.html
 618:39  error  'Grid' is repeated!  Vale.Repetition 


 files/en-us/learn/css/styling_text/typesetting_a_homepage/index.html
 68:86  error  'too' is repeated!  Vale.Repetition 


 files/en-us/learn/html/index.html
 37:284  error  'much' is repeated!  Vale.Repetition 


 files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/index.html
 150:209  error  'global' is repeated!  Vale.Repetition 


 files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_stores/index.html
 16:408  error  'global' is repeated!  Vale.Repetition 


 files/en-us/mdn/structures/page_types/api_landing_page_template/index.html
 121:16  error  'blah' is repeated!  Vale.Repetition 


 files/en-us/mdn/structures/page_types/api_reference_page_template/index.html
 123:16  error  'blah' is repeated!  Vale.Repetition 


 files/en-us/mozilla/developer_guide/build_instructions/incremental_builds_with_filesystem_watching/index.html
 26:40  error  'build' is repeated!  Vale.Repetition 


 files/en-us/mozilla/developer_guide/eclipse/eclipse_cdt/index.html
 263:629  error  'that' is repeated!  Vale.Repetition 


 files/en-us/mozilla/developer_guide/eclipse/eclipse_cdt/manual_setup/index.html
 234:629  error  'that' is repeated!  Vale.Repetition 


 files/en-us/mozilla/developer_guide/requesting_feedback_and_ui-review_for_desktop_firefox_front-end_changes/index.html
 13:461  error  'to' is repeated!  Vale.Repetition 


 files/en-us/mozilla/developer_guide/build_instructions/vc6_build_instructions/index.html
 2195:59  error  'long' is repeated!  Vale.Repetition 


 files/en-us/mozilla/firefox/releases/3.5/index.html
 213:180  error  'to' is repeated!  Vale.Repetition 


 files/en-us/tools/debugger-api/debugger/index.html
 88:1  error  'frame' is repeated!  Vale.Repetition 


 files/en-us/web/api/localfilesystemsync/index.html
 49:156  error  'long' is repeated!  Vale.Repetition 


 files/en-us/web/api/localfilesystem/index.html
 72:143  error  'long' is repeated!  Vale.Repetition 


 files/en-us/web/api/microdata_dom_api/index.html
 133:31  error  'index' is repeated!  Vale.Repetition 


 files/en-us/web/api/web_audio_api/using_web_audio_api/index.html
 199:138  error  'that' is repeated!  Vale.Repetition 


 files/en-us/web/api/web_storage_api/using_the_web_storage_api/index.html
 51:133  error  'that' is repeated!  Vale.Repetition 


 files/en-us/web/api/webxr_device_api/geometry/index.html
 168:105  error  'to' is repeated!  Vale.Repetition 


 files/en-us/web/css/css_flexible_box_layout/relationship_of_flexbox_to_other_layout_methods/index.html
 115:100  error  'that' is repeated!  Vale.Repetition 


 files/en-us/web/guide/events/event_handlers/index.html
 34:3  error  'event' is repeated!  Vale.Repetition 


 files/en-us/web/html/element/input/index.html
 479:171  error  'that' is repeated!  Vale.Repetition 


 files/en-us/web/javascript/reference/functions/arguments/callee/index.html
 76:366  error  'much' is repeated!  Vale.Repetition 


 files/en-us/web/javascript/reference/global_objects/intl/locale/numberingsystem/index.html
 192:12  error  'Tham' is repeated!  Vale.Repetition 


 files/en-us/web/media/formats/webrtc_codecs/index.html
 30:144  error  'at' is repeated!  Vale.Repetition 


 files/en-us/web/svg/namespaces_crash_course/index.html
 64:278  error  'that' is repeated!  Vale.Repetition 
 68:123  error  'that' is repeated!  Vale.Repetition 

✖ 33 errors, 0 warnings and 0 suggestions in 11170 files.
```

### CODE REVIEW

**Comment by peterbe** [comment]
That. Is amazing. I'm so glad you were able to do this (I work on the platform, not the content). 
Just wanted to say THANK YOU and I'm also intrigued by this `vale` which I've never seen before. 
Perhaps that something we should (optionally) integrate into the platform so that when you preview your changes to the text, it can pop up a little dialog to the side of the suggestions that `vale` can find.

**Comment by nschonni** [comment]
It's got a bunch of stuff in it, but I mostly just use it for the "duplicates" check 😄 
You might want to go poking around their project, but I don't think one of the variants is a "as a Service" version directly, but maybe they'd be interested in it

**Comment by escattone** [comment]
Thanks @nschonni, this is really cool! This repository is still not active yet, but will be soon (Dec.14th)!

**Comment by nschonni** [comment]
@escattone no worries, let me know if it needs a rebase after you go live or to be split  up into smaller pieces at that point

**Comment by peterbe** [comment]
@nschonni Can you merge in (and resolve) the latest `main` and push and we should be ready to merge. CC @chrisdavidmills

**Comment by nschonni** [comment]
@peterbe rebased and ran a last quick run for a few new ones

**Review by sideshowbarker — APPROVED** [review]

**Comment by chrisdavidmills** [comment]
Merge conflict resolved.

**Review by chrisdavidmills — APPROVED** [review]
OK, so the double word fixes look good to me.

Before I merge this, @peterbe can you check this for me? I just want to make sure that I've not messed anything up by fixing the merge conflict...

**Comment by sideshowbarker** [comment]
> Merge conflict resolved.

The GitHub UI here still thinks there are conflicts; it’s showing, *This branch cannot be rebased due to conflicts* …

**Comment by chrisdavidmills** [comment]
> The GitHub UI here still thinks there are conflicts; it’s showing, This branch cannot be rebased due to conflicts …

Ah daammnit, I'm a fool. More things have been merged since I wrote this, so of course!

**Comment by chrisdavidmills** [comment]
OK, I've fixed the new conflicts, and will get it merged.

**Comment by hamishwillee** [comment]
This is cool. I wonder of parts of it could be run in a github action?

**Comment by nschonni** [comment]
It could, but there are some of those "valid" (because English...) double words. I've never dug into see if there is any easy way to in-line disable false positives.

PS: there are a few baked style configs https://github.com/errata-ai/styles#available-styles

**Pull request merged**
