### PR TITLE
CSS to Markdown

### PR DESCRIPTION
**Pull request by wbamberg**
This draft PR converts all CSS docs (https://developer.mozilla.org/en-US/docs/Web/CSS and everything under it) to Markdown.

## Conversion

The conversion report is at https://gist.github.com/wbamberg/90c2da5ffc28daf5b2ef5a39165884e3 . I converted it using a version of h2m which has https://github.com/mdn/yari/pull/4444, which means it understands SVG syntax highlighting.

The main thing here as usual is tables. I count 57 unconverted tables out of (I think) 175 tables in the CSS docs. This is actually a much better ratio than the JS docs, in which I think around half were unconvertible. See for example https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units for some simple tables that got converted.

Apart from these, unconverted elements were:

* `<kbd>` elements, which we had agreed to keep as HTML
* `id` attributes for the four tools pages. These pages use `EmbedLiveSample` in a very unconventional way, to implement essentially complete web apps. Since these don't have headings, we can't use heading IDs for the live sample. And since they are not really "content" it doesn't seem very important to convert them. The pages concerned are:
    * https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Border-image_generator, 
    * https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Colors/Color_picker_tool
    * https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator
    * https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Border-radius_generator
* a `dir="rtl"` attribute which seemed like it would be worth keeping, in the example at https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing#internationalization_concerns. But maybe this should be made into a live sample? Anyway, it's a tiny thing.

## Testing

I've not looked at every page but I have looked at quite a lot of them. I have found a few issues.

* sometimes, `<dl>` elements are getting mangled in conversion. I filed a bug about this: https://github.com/mdn/yari/issues/4445. It would be good to have this fixed, but the in-content fix is very simple and I think there are very few pages affected. So I would be OK to work around these in content for now. Affected pages (that I have found) are:
    * https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape#shape_functions
    * https://developer.mozilla.org/en-US/docs/Web/CSS/url()#values
    * https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style#descriptors

* the tools pages listed above are broken, I think because the encoding of characters like `<` in the live sample is confusing the converter. Ideally these pages would be part of the core Yari platform and not content pages at all. A less good option that's still better than what we have now would be to make them GitHub pages and include them using `EmbedGHLiveSample`. In the meantime I would be happy to keep these as HTML - they're not exactly editable anyway, so we don't really lose anything that way.

* the code elements in https://developer.mozilla.org/en-US/docs/Web/CSS/background-position#regarding_percentages are not being wrapped, and that's breaking the page layout. I haven't tried to figure out what's happening there yet.

### CODE REVIEW

**Comment by wbamberg** [comment]
I've checked all the pages in CSS where a `<dd>` contains a `<pre>` block, and there are four:

* https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape#shape_functions
* https://developer.mozilla.org/en-US/docs/Web/CSS/url()#values
* https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style#descriptors
* https://developer.mozilla.org/en-US/docs/Web/css/@font-face#descriptors

...they all have the same `<dl>`-mangling problem observed in https://github.com/mdn/yari/issues/4445. Since we already knew about three of them, this makes it look quite likely that only these four pages are affected, so we could fix this in content.

**Comment by teoli2003** [comment]
I checked about 100 reference pages, and they all look good.

**Comment by wbamberg** [comment]
I just regenerated the Markdown from a new Yari that contains the fix for https://github.com/mdn/yari/issues/4445, which seems to work perfectly. Thanks @fiji-flo !

I pushed one more change which fixes the formatting problem in https://developer.mozilla.org/en-US/docs/Web/CSS/background-position#regarding_percentages.

I still need to update the tools pages to refer to GitHub pages, and will do that in this PR once https://github.com/mdn/css-examples/pull/45 is merged. But I think this is ready for review. I've checked a few hundred pages and they look all right.

If a reviewer wants to check a specific subset of pages, perhaps they could indicate which pages they're intending to look at, like "the Grid module pages" or the "Font module pages" or something like that.

Each module can be defined as one of the following pages, and all the pages it links to:

https://developer.mozilla.org/en-US/docs/Web/CSS/css_animations
https://developer.mozilla.org/en-US/docs/Web/CSS/css_backgrounds_and_borders
https://developer.mozilla.org/en-US/docs/Web/CSS/css_basic_user_interface
https://developer.mozilla.org/en-US/docs/Web/CSS/css_box_alignment
https://developer.mozilla.org/en-US/docs/Web/CSS/css_box_model
https://developer.mozilla.org/en-US/docs/Web/CSS/css_charsets
https://developer.mozilla.org/en-US/docs/Web/CSS/css_color
https://developer.mozilla.org/en-US/docs/Web/CSS/css_columns
https://developer.mozilla.org/en-US/docs/Web/CSS/css_conditional_rules
https://developer.mozilla.org/en-US/docs/Web/CSS/css_counter_styles
https://developer.mozilla.org/en-US/docs/Web/CSS/css_device_adaptation
https://developer.mozilla.org/en-US/docs/Web/CSS/css_display
https://developer.mozilla.org/en-US/docs/Web/CSS/css_flexible_box_layout
https://developer.mozilla.org/en-US/docs/Web/CSS/css_fonts
https://developer.mozilla.org/en-US/docs/Web/CSS/css_fragmentation
https://developer.mozilla.org/en-US/docs/Web/CSS/css_functions
https://developer.mozilla.org/en-US/docs/Web/CSS/css_generated_content
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout
https://developer.mozilla.org/en-US/docs/Web/CSS/css_images
https://developer.mozilla.org/en-US/docs/Web/CSS/css_lists_and_counters
https://developer.mozilla.org/en-US/docs/Web/CSS/css_logical_properties
https://developer.mozilla.org/en-US/docs/Web/CSS/css_masking
https://developer.mozilla.org/en-US/docs/Web/CSS/css_miscellaneous
https://developer.mozilla.org/en-US/docs/Web/CSS/css_motion_path
https://developer.mozilla.org/en-US/docs/Web/CSS/css_namespaces
https://developer.mozilla.org/en-US/docs/Web/CSS/css_overflow
https://developer.mozilla.org/en-US/docs/Web/CSS/css_pages
https://developer.mozilla.org/en-US/docs/Web/CSS/css_positioning
https://developer.mozilla.org/en-US/docs/Web/CSS/css_ruby
https://developer.mozilla.org/en-US/docs/Web/CSS/css_scroll_snap_points
https://developer.mozilla.org/en-US/docs/Web/CSS/css_scrollbars
https://developer.mozilla.org/en-US/docs/Web/CSS/css_shapes
https://developer.mozilla.org/en-US/docs/Web/CSS/css_table
https://developer.mozilla.org/en-US/docs/Web/CSS/css_text
https://developer.mozilla.org/en-US/docs/Web/CSS/css_text_decoration
https://developer.mozilla.org/en-US/docs/Web/CSS/css_transforms
https://developer.mozilla.org/en-US/docs/Web/CSS/css_transitions
https://developer.mozilla.org/en-US/docs/Web/CSS/css_variables
https://developer.mozilla.org/en-US/docs/Web/CSS/css_writing_modes

But also I'm not too concerned about people overlapping, I think we will get good enough coverage either way.

Also, @fiji-flo , I'd love your confirmation that the commits here are right to preserve history. It seems like the converter makes this easy by staging the renames, so I just have to do something like:

```
commit
add
commit
```

**Comment by sideshowbarker** [comment]
Incidental comment: For sources that we still have in HTML (not yet it Markdown), it seems like it’s time we stop manually updating the IDs of headings to be a “lower case with underscores for spaces and special characters” match for the text content of the headings — and stop asking contributors to do that. Among other reasons, all the work that goes into changing those IDs is just ultimately wasted, because those IDs don’t get carried over in the Markdown conversion anyway. Right?

So I would think that at this point, when any PR touches the text content of heading, we should rather just be deleting the ID attribute and value from the HTML source — and somewhere document that as being what we’re doing from now own.

To be doing otherwise at this point seems like a waste of everybody’s time. Or is there something I’m missing?

I mention that here in part because I’m right now randomly (in an automated way) going through all the markdown output in this PR, and there’s one non-problem I’ve run into that seems potentially confusing for contributors:

We have cases of articles with multiple Example sections that each of _HTML_, _CSS_, and _JavaScript_ subheadings — that is, multiple subheadings with the exact same text, e.g, _HTML_ text content.

I can imagine a contributor wondering if they might need to add some text to those headings to ensure the headings will get unique IDs in HTML output.

So because Yari deals with that problem by automatically appends `_2`, `_3`, etc., suffixes to the IDs in the HTML output, to ensure every heading gets a unique ID, we might want to document somewhere for contributors, *“Don’t worry about trying to make the text content of headings unique — the system will automatically generate unique IDs for headings, regardless.”*

**Comment by sideshowbarker** [comment]
Conversion to `files/en-us/web/css/css_background_and_borders/border-image_generator/index.md` seems to have partially failed — there’s some unconverted HTML; the beginning looks like this:

```markdown
---
title: Border-image generator
slug: Web/CSS/CSS_Background_and_Borders/Border-image_generator
tags:
  - CSS
  - Tools
---
This tool can be used to generate CSS3 {{cssxref("border-image")}} values.

<div id="Border_Image_Generator"><pre class="brush: html hidden">    &#x3C;div id="container">

&#x3C;div id="gallery">
            &#x3C;div id="image-gallery">
                &#x3C;img class="image" src="border-image-1.png" data-stateID="border1"/>
                &#x3C;img class="image" src="border-image-2.png" data-stateID="border2"/>
                &#x3C;img class="image" src="border-image-3.png" data-stateID="border3"/>
                &#x3C;img class="image" src="border-image-4.png" data-stateID="border4"/>
                &#x3C;img class="image" src="border-image-5.png" data-stateID="border5"/>
                &#x3C;img class="image" src="border-image-6.svg" data-stateID="border6"/>
            &#x3C;/div>
        &#x3C;/div>
```

I’m not sure why form looking at the https://github.com/mdn/content/blob/main/files/en-us/web/css/css_background_and_borders/border-image_generator/index.html source:

```html
---
title: Border-image generator
slug: Web/CSS/CSS_Background_and_Borders/Border-image_generator
tags:
  - CSS
  - Tools
---
<p>This tool can be used to generate CSS3 {{cssxref("border-image")}} values.</p>

<div id="Border_Image_Generator">
<pre class="brush: html hidden">    &lt;div id="container"&gt;
```
Maybe because of the space after `<pre class="brush: html hidden">`? Or maybe the `hidden` attribute?

**Comment by sideshowbarker** [comment]
> @sideshowbarker This is in the process of being moved to another repo: see [mdn/css-examples#45](https://github.com/mdn/css-examples/pull/45)

ah OK thanks

**Comment by sideshowbarker** [comment]
`files/en-us/web/css/scrollbar-color/index.md` has an unconverted table (not sure if that’s considered a non-problem, or it’s already listed as a known issue somewhere…)

**Comment by sideshowbarker** [comment]
`files/en-us/web/css/font-weight/index.md` has an unconverted table. It’s a 3-column table but looks simple enough that it could be done as a markdown table.

**Comment by sideshowbarker** [comment]
`files/en-us/web/css/angle/index.md` has unconverted tables. The tables have images in them. I guess it’s not a conversion failure?

The tables are anyway simple enough that they don’t actually even need to be tables. But anyway, fixing those is outside the scope of this PR, I guess.

**Comment by sideshowbarker** [comment]
`files/en-us/web/css/background-repeat/index.md` has some unconverted tables which look simple enough that they could be done as markdown tables.

**Comment by sideshowbarker** [comment]
I checked a sample of files at random, selected by doing this:

```
git show  --name-only 196beba8235d39d5fdd3c603c6edf7164c410b8b | grep "index\.md" | shuf -n1
```

For each one I checked, I opened the source and looked through it manually, and also looked at the rendered HTML output.

I’m not sure how many files I checked, but on the order of dozens.

I found no outright conversion failures other than the single one I mentioned in https://github.com/mdn/content/pull/7779#issuecomment-897428529

Otherwise the only other significant thing I noticed were the case of unconverted tables I mentioned in my previous comments.

For each file I checked, I also ran it through markdownlint https://github.com/DavidAnson/markdownlint (using https://github.com/igorshubovych/markdownlint-cli), which seems to me like a pretty useful tool.

I pushed a change to this branch with fixes for some problems that markdownlint found. I guess the most-significant problems were cases of missing alt text for images — which isn’t of course a problem with the conversion, but instead just due the images having no alt text to begin with.

Another thing that markdownlint catches and can fix automatically is unnecessary extra spaces after list-item numbers. So the change a pushed includes some of those.

And one more thing it catches is trailing punctuation in heading text. So fixes for the cases of those I came across are also included.

Just for kicks I ran the following:

```
git show  --name-only 196beba8235d39d5fdd3c603c6edf7164c410b8b | grep "index\.md" \
  | xargs markdownlint 2>&1 | cut -d ":" -f1 | sort | uniq | wc -l
```

…and it spit out `169` — as in, there are 169 files that markdown reported issues for. That seems pretty good — only 169 out of 950, so 18%. And quite a number of those are basically false positives.

**Review by sideshowbarker — APPROVED** [review]

**Comment by wbamberg** [comment]
Thanks for the review, @sideshowbarker ! Very much appreciated :).

About https://github.com/mdn/content/pull/7779#issuecomment-897428529 - this is noted in https://github.com/mdn/content/pull/7779#issue-707015880 as "the tools pages listed above are broken", and that will be fixed in this PR now https://github.com/mdn/css-examples/pull/45 is merged.

About the tables: there's nothing unexpected here. For specifics, it looks like:

* the table at https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#meaning_of_relative_weights isn't converted because it has a header column
* the tables at https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat#values aren't being converted because they don't have a header at all

I'm a little unsure about some of the formatting errors markdown-lint reports. We ran Prettier on these files after conversion, so I wonder how many of them are basically Prettier and markdown-lint having different opinions? But it's OK. We really should have Prettier running on CI so we can maintain a consistent format, and that can be a separate thing.

**Comment by fiji-flo** [comment]
@wbamberg looks good history wise as long as we don't squash.

**Review by hamishwillee — APPROVED** [review]
I did a sample check too - saw nothing new. I think we've done due diligence on this.

**Comment by wbamberg** [comment]
Thanks Hamish! I just force-pushed again to pick up a couple of PRs that got merged since this was opened, and also to fix the "tools" pages now they are living in the css-examples repo (https://github.com/mdn/css-examples/pull/45).

This means I've destroyed @sideshowbarker 's commit to this PR, which I'm sorry about but as discussed it seemed like the simplest option.

**Comment by hamishwillee** [comment]
> This means I've destroyed @sideshowbarker 's commit to this PR, which I'm sorry about but as discussed it seemed like the simplest option.

That does suck a bit. Does this still remove the irritating things like extra spaces after numbered bullets?

**Comment by wbamberg** [comment]
> > This means I've destroyed @sideshowbarker 's commit to this PR, which I'm sorry about but as discussed it seemed like the simplest option.
> 
> That does suck a bit. Does this still remove the irritating things like extra spaces after numbered bullets?

No, this is just the output of the converter (which also runs it through Prettier). But I'd rather handle these changes in a follow up.

**Pull request merged**
