### PR TITLE
.

### PR DESCRIPTION
**Pull request by ghost**
#648

> Document checking completed. No errors or warnings to show.

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
Have you tested this patch locally? http://localhost:5000/en-US/docs/Web/JavaScript/Closures You’re aware that doesn’t actually work? That URL shows this:

> Error: From URL /en-US/docs/undefined no folder on disk could be found. Tried to find a folder called en-us/undefined

And Yari logs the following error to this console:

> The slug of files/en-us/web/javascript/closures/index.html doesn't match the folder is located in.

So it’s hard to understand why you raised this PR. We can’t merge this, right? Not without major changes to Yari to teach it about this split format, with the metadata in a separate file.

**Comment by sideshowbarker** [comment]
I’m gonna go ahead and close this per https://github.com/mdn/content/pull/748#pullrequestreview-559754544. Rather than a PR for this, It seems more appropriate to add this to #648 as a concrete proposal.

**Comment by mattiapontonio** [comment]
I haven't tested it locally.

Exactly, the pileline says you can't merge ...

**Comment by mattiapontonio** [comment]
@peterbe can You please review for the Yari side?

**Comment by mattiapontonio** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link

**Comment by mattiapontonio** [comment]
@sideshowbarker can You reopen in draft?

**Comment by sideshowbarker** [comment]
> @sideshowbarker can You reopen in draft?

Can you please be clear about why? If we reopen it in draft, then what happens next?

What is your response to the comments at https://github.com/mdn/content/pull/748#pullrequestreview-559754544 and https://github.com/mdn/content/pull/748#issuecomment-752305510?

Given that we would not be able to merge this pull request without major changes to Yari to teach it about this split format — which so far hasn’t really even been discussed — what’s the purpose of this pull request? Doesn’t it seem premature to have a pull request for this?

**Comment by mattiapontonio** [comment]
No I don't think it's premature. It's just another form of discussing things with the added advantage that actions start and you see the code so it's even better. The issue remains open and the thing goes on I then have to reopen a PR, on what? Personally I find it convenient to do a draft PR, you could also open them empty if you want, creating an empty ES lint configuration file with a comment that says "so guys, let's decide this configuration once and for all 🤹?" 🤷🏻‍♂️

**Comment by mattiapontonio** [comment]
It is not said (and I do not know it) that there is also an action friendly way to make the change but I can not know if not here.
There is always the risk that I work a lot locally and then I get here and ❌

**Comment by mattiapontonio** [comment]
Incidentally, it is not my intention to raise issues on the validator on the contrary I would like to use it later for other modifications.

-  I open the GitHub edit `textarea` 📝
-  I make the change
-  I select everything (ctrl + A on Windows Desktop)
-  Copy (ctrl+C) 🖨️ and paste 📋
- is valid ✔️

So at least I'm calm about that.

**Comment by mattiapontonio** [comment]
I was thinking that the least distracting solution here getting a little inspiration from npm is that the change is merged and Yari continues to use the old version but only for this file 🤷🏻‍♂️
But I have no idea how to do it, I know what can be done with the packages / repository and that instead the http APIs have the version sometimes in the URL.

**Comment by mattiapontonio** [comment]
Can I have the privilege of requesting review to anyone I want?
Or at least @hamishwillee ?
I can?

**Comment by mattiapontonio** [comment]
Thanks for the support.
These rules seem reasonable to me but very difficult to make programmatic.

### Pseudo code of how I imagine Yari's logic.

- try import or fetch the html
- try parse html
- try find link in dom
- try fetch yalm
- try parse yalm
 - get the data
 - patch the html 🥇
- catch error parse yalm ❌
- catch error fetch yalm ❌
- catch error find link in dom ❌
- catch error parse html ❌
 - old logic here 🥈
- catch error import or fetch the html ❌

**Comment by mattiapontonio** [comment]
Alternatively to be defined:

- html has an id
- yalm has 1 id
- there is a relationship map

This decreases the indented try catches, each one has its own flow but it doesn't convince me because I don't imagine it well yet.

**Comment by peterbe** [comment]
See https://github.com/mdn/content/issues/648#issuecomment-753948845

**Pull request closed without merging**
