### PR TITLE
Add missing prefixed space to first word in notecard

### LINKED ISSUE #1844: Notecard missing macro usage
Wondering if the second notecard was supposed to be styled with the macro `{{Note('stuff')}}` on [What is a URL?](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL). I'm asking because the first notecard is utilizing the macro which adds the little notecard icon.

First notecard (uses macro)
Screen Shot 2021-01-27 at 10 25 10 PM

Second notecard (doesn't use macro)
Screen Shot 2021-01-27 at 10 25 15 PM

### PR DESCRIPTION
**Pull request by tannerdolby**
Fixes #1844 

Adds missing prefix space to first word "There" for notecard on [What is a URL?](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL). This fixes the "squished" look.
Before:
Screen Shot 2021-01-27 at 10 20 23 PM

After:
Screen Shot 2021-01-27 at 10 20 13 PM

### CODE REVIEW

**Review by chrisdavidmills — COMMENTED** [review]
This won't be a problem with the "New note syntax", as explained in the related issue ;-)

Can you change it to the new note syntax instead, to try it out?

**Comment by tannerdolby** [comment]
@chrisdavidmills Yeah, I will change it to the new note syntax explained in the related issue :-)

**Comment by chrisdavidmills** [comment]
cheers!

**Comment by tannerdolby** [comment]
@chrisdavidmills I updated the notecard syntax for the first note on this page, there is a second note without the updated form:

```html
<div class="note">
<p><strong>Note:</strong> When specifying URLs to ...</p>
</div>
```

Want me to fix this note to use the updated notecard syntax? ie add an `<h4>` tag, add the `notecard` class and get rid of the `<strong>` tag?

**Comment by hamishwillee** [comment]
@tannerdolby Re https://github.com/mdn/content/pull/1843#issuecomment-769256356 - "yes, please fix all notes to the correct syntax"

**Review by chrisdavidmills — APPROVED** [review]
Great stuff; thanks @tannerdolby

**Comment by tannerdolby** [comment]
Your welcome @chrisdavidmills !

**Pull request merged**
