### PR TITLE
fix(pr-check_redirect): correct the path filter

### PR DESCRIPTION
**Pull request by yin1999**
### Description

correct the path filter

### CODE REVIEW

**Review by hamishwillee — APPROVED** [review]
@OnkarRuikar This looks right to me, given the new file exists and the old  one does not. But since you touched the file perhaps you could confirm. Approving but not merging.

**Comment by OnkarRuikar** [comment]
> @OnkarRuikar This looks right to me, given the new file exists and the old one does not. But since you touched the file perhaps you could confirm. Approving but not merging.

Looks good to me. The workflow "Check Redirects / check-redirects" has run for the commit so the change works.

**Comment by hamishwillee** [comment]
There is one check fail  - do we need to worry about that?

**Comment by yin1999** [comment]
> There is one check fail - do we need to worry about that?

The "System file changes" workflow would always fail. This is used to note us that the current PR has modified files related to the infrastructure of the current repo.

**Comment by OnkarRuikar** [comment]
> There is one check fail - do we need to worry about that?

No need to worry about "System file changes / block" check. It's a deliberate failure (`exit 1`) to avoid accidental or auto merges on system file changes.

**Comment by hamishwillee** [comment]
Thanks! I'm brave enough to merge then :-)

**Pull request merged**
