### PR TITLE
chore(markdownlint) : enable MD045 Images should have alt text

### PR DESCRIPTION
**Pull request by nschonni**
Related to #19334.
Now that the markdownlint rule is only running on files in the PR, this should be safe to turn on to start encouraging people to fix them when they edit these files or add new documents.

Currently there are ~185~ 123 hits (as of 2022-10-24)
```
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:406 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:408 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:493 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:497 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:505 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:711 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.md:603 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.md:667 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.md:729 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.md:797 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.md:29 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/contextualidentities/index.md:17 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/devtools/panels/elementspanel/createsidebarpane/index.md:26 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/devtools/panels/extensionsidebarpane/index.md:21 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/find/find/index.md:97 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/find/find/index.md:99 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/find/find/index.md:228 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/menus/index.md:44 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/menus/index.md:50 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/menus/index.md:54 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/menus/index.md:60 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/notifications/index.md:21 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/pageaction/index.md:20 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/pkcs11/index.md:31 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/pkcs11/index.md:33 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/proxy/register/index.md:21 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/proxy/unregister/index.md:20 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/userscripts/working_with_userscripts/index.md:46 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/userscripts/working_with_userscripts/index.md:107 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/webnavigation/index.md:24 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/webrequest/index.md:22 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/browser_actions/index.md:12 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/extending_the_developer_tools/index.md:124 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/native_messaging/index.md:22 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/user_interface/browser_action/index.md:11 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/user_interface/context_menu_items/index.md:18 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/user_interface/page_actions/index.md:15 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/user_interface/popups/index.md:15 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/user_interface/sidebars/index.md:16 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/what_are_webextensions/index.md:17 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/what_are_webextensions/index.md:23 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/what_are_webextensions/index.md:29 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/what_are_webextensions/index.md:35 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/what_are_webextensions/index.md:45 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/your_second_webextension/index.md:30 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/firefox/releases/3.5/icc_color_correction_in_firefox/index.md:16 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvasrenderingcontext2d/clip/index.md:26 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvasrenderingcontext2d/createlineargradient/index.md:22 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvasrenderingcontext2d/rotate/index.md:26 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvasrenderingcontext2d/translate/index.md:30 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/channel_messaging_api/using_channel_messaging/index.md:41 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/channelmergernode/index.md:18 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/channelsplitternode/index.md:21 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/index.md:169 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/index.md:244 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/index.md:268 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/table/index.md:43 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/table/index.md:58 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/timeend/index.md:55 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/timelog/index.md:77 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/document_object_model/whitespace/index.md:270 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/clientwidth/index.md:34 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/getboundingclientrect/index.md:54 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/mouseenter_event/index.md:101 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/mouseenter_event/index.md:106 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/mouseleave_event/index.md:97 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/mouseleave_event/index.md:103 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/scrollheight/index.md:20 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/htmlelement/offsetheight/index.md:40 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/htmlelement/offsetleft/index.md:40 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/htmlelement/offsetwidth/index.md:38 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/navigator/registerprotocolhandler/web-based_protocol_handlers/index.md:41 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/notifications_api/index.md:33 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/presentation_api/index.md:18 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/service_worker_api/using_service_workers/index.md:43 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/service_worker_api/using_service_workers/index.md:106 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/service_worker_api/using_service_workers/index.md:159 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/stereopannernode/index.md:21 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/streams_api/concepts/index.md:26 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/streams_api/concepts/index.md:48 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/textdecoder/index.md:48 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/web_audio_api/basic_concepts_behind_web_audio_api/index.md:390 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/web_audio_api/basic_concepts_behind_web_audio_api/index.md:394 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/web_storage_api/using_the_web_storage_api/index.md:104 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/web_storage_api/using_the_web_storage_api/index.md:108 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/webgl_api/matrix_math_for_the_web/index.md:276 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/webvr_api/using_the_webvr_api/index.md:42 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/webvr_api/using_the_webvr_api/index.md:238 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/webxr_device_api/fundamentals/index.md:52 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/window/personalbar/index.md:27 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/window/statusbar/index.md:54 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/xrwebgllayer/getnativeframebufferscalefactor/index.md:102 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/xrwebgllayer/getnativeframebufferscalefactor/index.md:148 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/guide/css/getting_started/challenge_solutions/index.md:243 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/guide/mobile/separate_sites/index.md:25 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/compression/index.md:39 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/compression/index.md:45 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/compression/index.md:55 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/compression/index.md:59 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/connection_management_in_http_1.x/index.md:79 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/content_negotiation/index.md:21 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/content_negotiation/index.md:34 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/content_negotiation/index.md:107 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/cors/index.md:27 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/cors/index.md:109 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/cors/index.md:172 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/cors/index.md:305 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/media/formats/video_codecs/index.md:416 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/privacy/firefox_tracking_protection/index.md:33 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/privacy/firefox_tracking_protection/index.md:37 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/progressive_web_apps/add_to_home_screen/index.md:58 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/progressive_web_apps/add_to_home_screen/index.md:208 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/progressive_web_apps/add_to_home_screen/index.md:212 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/fills_and_strokes/index.md:34 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/fills_and_strokes/index.md:57 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/fills_and_strokes/index.md:77 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/paths/index.md:38 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/paths/index.md:73 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/paths/index.md:161 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/paths/index.md:199 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/paths/index.md:266 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/patterns/index.md:82 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/positions/index.md:23 MD045/no-alt-text Images should have alternate text (alt text)
```

/cc @estelle

### CODE REVIEW

**Comment by nschonni** [comment]
The `Markdownlint (All files)` is expected to fail, since this is touching the config file, but that job doesn't run on normal PRs

**Comment by teoli2003** [comment]
I really want @estelle to review this; we have to wait a bit here.

If the linter only lint modified files, this should be doable, but my gut feelings tell me: "Fix them all, first", which, at the current speed, should be this Quarter!

**Review by caugner — CHANGES_REQUESTED** [review]
Change LGTM, but to save time and ensure the quality of the alt texts, I would also suggest just fixing them altogether in one go first.

**Comment by teoli2003** [comment]
Fixing alt text is ongoing. Already half of them were fixed in August. Let's wait until this is done before to merge this.

**Review by teoli2003 — DISMISSED** [review]
We need to reconsider this when all _alt_ texts are fixed. I already have a few thoughts here.

Until now, we only detect automatically fixable MD errors in the Markdownlint workflow, with `.markdownlint.json` as its config file. These flaws are automatically fixed by another workflow, which is good: they are informative, get fixed, and don't get in the way.

This MD error, MD045, is different. It can't be automatically fixed, so we want it to be fixed before the PR lands.

I'm wondering if we shouldn't create a second Markdownlint workflow with MD045 (and maybe more rules in the future), not creating warnings that can be ignored, but errors that should block the PR. This second Markdownlint workflow would have a different `.markdownlint.json` config file. In the case of MD045, it would prevent the merge of a PR that would add an image without _alt_.

**Review by Timmy11223 — COMMENTED** [review]
Help I'm the owner of this acc but everything is saying I need administrative approval.....ZZZ help

**Comment by nschonni** [comment]
I think this is probably good to wait for the cleanup, but I had another idea. An extra config that extends from the base could be used just to run on the PR Files Markdownlint job. Then any PR that touches these files or introduced a new one would be failed, but the global running would remain green

**Comment by bsmth** [comment]
@nschonni, can you drop a comment here with steps to run markdownlint with this rule enabled? It would be interesting to be able to check the status of this now as there have been quite a few fixes landing for this.

**Comment by nschonni** [comment]
You can remove the line in the markdownlint config, then run `yarn lint:md` to see the issues.
You can also see the current ones in the failing CI job on this PR after you merged the main branch recently (~160)

**Comment by bsmth** [comment]
> the current ones in the failing CI job on this PR

Of course, thanks 👍🏻

**Review by estelle — APPROVED** [review]

**Comment by nschonni** [comment]
Getting pretty close! Only 30 remain

**Comment by estelle** [comment]
There are no `![]` left in the `en-us` codebase.

**Review by bsmth — APPROVED** [review]
Well done, all 👍🏻

**Review by Elchi3 — APPROVED** [review]

**Review by caugner — APPROVED** [review]

**Comment by bsmth** [comment]
> alt text are fixed, lets merge this to not regress this achievement

🎉

**Pull request merged**
