### PR TITLE
Remove masonry-auto-flow and redirect to grid-auto-flow

### PR DESCRIPTION
**Pull request by caugner**
### Description

Remove Web/CSS/masonry-auto-flow page and redirect to Web/CSS/grid-auto-flow.

### Motivation

`css.properties.masonry-auto-flow` was removed in https://github.com/mdn/browser-compat-data/pull/24009.

### Related issues and pull requests

See: https://github.com/mdn/browser-compat-data/pull/24009

### CODE REVIEW

**Comment by Josh-Cena** [comment]
If an API isn't tracked in BCD, that usually means it fails the documentation criteria too—should we just remove the documentation altogether, as is usually done?

**Comment by Josh-Cena** [comment]
@caugner Are you coming back to this soon?

**Comment by bsmth** [comment]
Claas is on PTO until next week, but I think deletions with redirects to `grid-auto-flow` is what we want.

**Comment by caugner** [comment]
Thanks @bsmth for following up on this. As discussed, let's go ahead and delete the `masonry-auto-flow` page, redirecting to `grid-auto-flow`.

Let's consider if the `grid-auto-flow` page could mention `masonry-auto-flow` though, just like `position-area` mentions `inset-area`.

**Comment by Josh-Cena** [comment]
@bsmth perhaps you could commit to this branch to add a note?

**Review by bsmth — APPROVED** [review]
Adding a +1, @caugner do you want to check this?

**Comment by caugner** [comment]
> Adding a +1, @caugner do you want to check this?

LGTM, thanks!

**Pull request merged**
