### PR TITLE
Improve map function example

### PR DESCRIPTION
**Pull request by alirezaghey**
### Motivation
The code snippet was wrong, as it accessed elements in an array that were not available.

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Hi, have you tried the example? Setting the end of the array is automatically equivalent to using `push`, so I'll prefer to not change existing code.

**Comment by alirezaghey** [comment]
Hi @Josh-Cena
I did know about that. Thanks for pointing that out.
But I still think it would have educational benefits if we did change the current snippet to a more known style.
My reasoning is that people reading this page are usually no js experts like me, and using this IMHO less known style will draw their attention to some degree away from the subject of functions.

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
I am okay with changing the examples, but I suggest doing it the other way. Instead of initializing with an empty array, we should use `Array(a.length)` instead. This better aligns with the implementation of array's `map`.

**Comment by alirezaghey** [comment]
Made the requested changes in a second commit to the branch.

Sorry if it took too long or if there are mistakes. I don't have access to my laptop.

**Review by Josh-Cena — COMMENTED** [review]
Thanks! There's another occurrence directly below. Could you quickly update that as well?

**Review by Josh-Cena — APPROVED** [review]
Looks great, thanks! And congratulations on your first contribution here—welcome aboard!

**Pull request merged**
