### PR TITLE
fix(art-gallery-example): wait for images to be loaded

### LINKED ISSUE #30782: Canvas Tutorial, Images aren't always loaded before drawing to the canvas
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images

### What specific section or headline is this issue about?

"Example: Framing and Image" and "Art Gallery Example"

### What information was incorrect, unhelpful, or incomplete?

The images aren't checked to see if they're loaded before drawing to the canvas(es). This means that sometimes only a few images draw, sometimes none of the images in the examples draw. The first time I loaded the page, the art gallery example didn't draw the pictures or frames. This issue also happens if you click 'play' to open the examples in the Playground.

image

image

### What did you expect to see?

The pictures drawing properly to the canvas.

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

I'm not sure if there is a better way to do this but, you could add an event listener to the window checking that it's been loaded before calling the draw() function?

window.addEventListener("load", (event) => {
  draw();
});

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvas_api/tutorial/using_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/using_images/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

### PR DESCRIPTION
**Pull request by caugner**
### Description

Draw images only when they're all loaded.

### Motivation

The images aren't always loaded yet when they are drawn on the canvas.

### Related issues and pull requests

Fixes https://github.com/mdn/content/issues/30782.

### CODE REVIEW

**Comment by bsmth** [comment]
@caugner can you check https://github.com/mdn/content/pull/32802/commits/3d8a8bf7a9ab597f101c774079d9bb235b58646b to let me know if it looks okay?

**Comment by caugner** [comment]
> @caugner can you check [3d8a8bf](https://github.com/mdn/content/commit/3d8a8bf7a9ab597f101c774079d9bb235b58646b) to let me know if it looks okay?

@bsmth Thank you for taking over, looking good to me on the preview! 🙌

**Review by bsmth — APPROVED** [review]
I'm leaving a +1 for @caugner's changes. Would be good to have a quick look from someone else, but I think we're good to go in general!

**Comment by bsmth** [comment]
I'm going to merge because I mostly updated prose so let's get it in!

**Pull request merged**
