### PR TITLE
Remove JXON references

### LINKED ISSUE #21620: JXON instead of JSON
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/How_to_create_a_DOM_tree

### What specific section or headline is this issue about?

About "See Also" section

### What information was incorrect, unhelpful, or incomplete?

There is a list of what you can see also and there is a spelling mistake: JXON instead of JSON

### What did you expect to see?

[JSON](https://developer.mozilla.org/en-US/docs/JSON)

### Do you have any supporting links, references, or citations?

[JXON](https://developer.mozilla.org/en-US/docs/JXON)

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document_object_model/how_to_create_a_dom_tree`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/How_to_create_a_DOM_tree
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document_object_model/how_to_create_a_dom_tree/index.md
* Last commit: https://github.com/mdn/content/commit/1511e914c6b1ce6f88056bfefd48a6aa585cebce
* Document last modified: 2022-09-09T05:10:34.000Z

</details>

### PR DESCRIPTION
**Pull request by wbamberg**
The references to "JXON" in https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/How_to_create_a_DOM_tree are confusing to people, who think it is a typo for "JSON" (https://github.com/mdn/content/pull/21585, https://github.com/mdn/content/pull/23644).

<strike>Apart from that, this page is really out of date. I had thought we could replace it by adding a bit of stuff on updating the DOM to  https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction. But now I look, we already have something on that here (e.g. https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction#adding_a_child_element), so this PR does the lazy thing and just deletes this old page.</strike>

Fixes #21620

I've changed this PR to have a more delicate approach, in which we just make https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/How_to_create_a_DOM_tree a bit less obsolete and remove all references to JXON, except for one in the old Firefox release notes.

The reason is that there are a couple of other places where we refer to "creating an in-memory document", like https://developer.mozilla.org/en-US/docs/Web/Guide/Parsing_and_serializing_XML#serializing_dom_trees_to_strings, and in itself this doesn't seem like a ridiculous thing to be documenting.

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Is this a fix for https://github.com/mdn/content/issues/21620?

**Comment by Josh-Cena** [comment]
To properly fix it, I suggest also deleting the reference of JXON in `files/en-us/web/guide/ajax/index.md` and `files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md`, `files/en-us/web/xpath/index.md` (as a tag).

**Comment by teoli2003** [comment]
I agree with @Josh-Cena, though I don't have any strong feelings about doing it in this PR or in a follow-up. Your call, @wbamberg.

**Comment by estelle** [comment]
The JXON issue has come up before. I would be happy to see this page go.

**Review by teoli2003 — APPROVED** [review]
Approving this, so that @wbamberg can merge this if he doesn't want to follow-up here.

**Pull request merged**
