### PR TITLE
Fix title WebAssembly language reference

### PR DESCRIPTION
**Pull request by hamishwillee**
#21451 links to the page called "WebAssembly instructions", but that's incomplete. 

This is a reference for all the instructions you might see in WASM - at least the text version. 
- I changed name to WASM language reference, but I'd be happy with "WASM instruction reference"?
- Having as a DL was broken - you either need to provide info for all or none of these. I have turned into a list with none. Very happy to expand out again, but if so, need to know what is intended for the "Reference instructions" section?

@MendyBerger Any opinions on this?

### CODE REVIEW

**Comment by bsmth** [comment]
I'm also interested in another opinion, but I think instructions might be better, like your other suggestion:

* "WASM instruction reference" or
* "WASM instructions reference" 

the link at https://developer.mozilla.org/en-US/docs/WebAssembly#api_reference would then have to be updated.

>I have turned into a list with no (descriptions)

that makes sense for now.

**Comment by hamishwillee** [comment]
@bsmth Fair enough. This renames both place to WebAssembly instruction reference. I'm open to other opinions too, but I'm confident that this is better unless we get feedback on the intent for undocumented links. 
Can you approve this and if no one has commented by Friday/Monday we'll merge this.

**Review by bsmth — APPROVED** [review]
Thanks, Hamish 👍

**Comment by teoli2003** [comment]
(Sorry, I merge without reading @hamishwillee last comment. Hope it is not a problem)

**Comment by MendyBerger** [comment]
FWIW I support this change

**Comment by hamishwillee** [comment]
All good thanks guys.

**Pull request merged**
