### PR TITLE
Remove long gone WebExtensions features

### PR DESCRIPTION
**Pull request by Elchi3**
### Description

We consider features irrelevant once they are removed from all browsers for more than two years. This is the case with a few WebExtensions features that this PR proposes to remove from the docs.

### Motivation

Cleaning up data and docs, so that readers don't have to read stuff that is not interesting anymore and distracts from other relevant and current information on the page.

### Additional details

None.

### Related issues and pull requests

BCD companion PR: https://github.com/mdn/browser-compat-data/pull/21305

### CODE REVIEW

**Review by rebloor — CHANGES_REQUESTED** [review]
@Elchi3 I think we need some further changes:

- the two deleted images are used to illustrate `tab_background_text` and `frame`, so should be renamed rather than deleted (see lines 382 and 760)
-` headerURL` is mentioned in lines, 145 to 151. Perhaps change the text to "Optional in desktop Firefox 60 onwards. Required in Firefox for Android."
- note referring to `textcolor` on lines 482 to 485
- remove `accentcolor` and `textcolor` from the alias section (from line 1252). We would appear now to only have one alias, for `bookmark_text`/`toolbar_text`

**Comment by Elchi3** [comment]
Thanks @rebloor! Will update this PR. Local preview doesn't really work unfortunately due to https://github.com/mdn/yari/issues/4654

**Comment by zfox23** [comment]
@Elchi3 poking you regarding updating this PR :) Thank you for your help.

**Comment by Elchi3** [comment]
@rebloor Thank you so much! 
http://localhost:5042/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/ works and 
http://localhost:300/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/ does not!

I've made the requested changes. Please take another look.

**Review by rebloor — APPROVED** [review]

**Comment by rebloor** [comment]
@Elchi3, Sorry for the delay in reviewing your update. Everything looks good, and I've merged. Thanks for your help.

**Pull request merged**
