### PR TITLE
fix wrong link

### PR DESCRIPTION
**Pull request by T34-active**
### Related issues and pull requests

https://github.com/mdn/translated-content/pull/19688

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by teoli2003** [comment]
Thank you!

**Comment by T34-active** [comment]
> Thank you!

@teoli2003 I'm sorry, but there are changes to be made to the document.  Can you withdraw your pull request?

**Comment by teoli2003** [comment]
Not sure to understand. I merged _your_ PR… Do you want me to revert it so you make additional changes?

**Comment by T34-active** [comment]
> Not sure to understand. I merged _your_ PR… Do you want me to revert it so you make additional changes?不太明白，我合并了你的公关... 你想让我恢复它，让你做更多的改变吗？

yes plz cancel this PR

**Comment by T34-active** [comment]
> I've created a revert PR, but it would be quicker for you to do a follow-up PR that I can approve.

Thank you

**Pull request merged**
