### PR TITLE
Added pt-BR translation

### PR DESCRIPTION
**Pull request by halcance**
### Description

pt-BR translation

### Related issues and pull requests

Relates to https://github.com/mdn/translated-content/issues/8749#issue-1383308373

### CODE REVIEW

**Comment by cw118** [comment]
Gently poking @mdn/yari-content-pt-br for a review here :)

**Review by josielrocha — APPROVED** [review]
LGTM ;)

**Review by wbamberg — COMMENTED** [review]
Thank you @halcance  and @josielrocha for the review!

Is it intended that items here should be in alphabetical order, for the benefit of maintainers?

(I checked some of the other files and it looks a bit random tbh, but having an ordering seems like a good idea.)

**Comment by halcance** [comment]
Yeah I noticed that, an alphabetical order should be great and I thought to follow it but I got the ch-ZN file and the author put at the bottom, so I did.

**Comment by halcance** [comment]
Updated to alphabetical order.

**Review by wbamberg — APPROVED** [review]
👍 thank you @halcance , looks great!

**Pull request merged**
