### PR TITLE
Update “Compiling an Existing C Module to WebAssembly” example

### PR DESCRIPTION
**Pull request by ashikmeerankutty**
Added encode, free_result, get_result_pointer, get_result_size, destroy_buffer to `api` object.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Hi @ashikmeerankutty ! Can you give me a bit more information about why you've made this change?

I've not looked at any WebAssembly for a while, so am a bit rusty ;-)

**Comment by ashikmeerankutty** [comment]
Hi @chrisdavidmills . I was following this content for getting started with wasm.  It was super helpful. The issue here was we were calling some methods from the api object, specifically `encode, free_result, get_result_pointer, get_result_size, destroy_buffer` at

https://github.com/mdn/content/blob/4a1ddbf4dfcd2d0a899ac4a131bc7ba6ddc097d1/files/en-us/webassembly/existing_c_to_wasm/index.html#L147-L152

But in the tutorial the definition for these methods are not shown. So it will be confusing for beginners to start with. So I added them to the api object.

**Comment by chrisdavidmills** [comment]
Thanks for the explanation @ashikmeerankutty !

I still want to try to find someone else to review this. @jpmedley , do you know much about webassembly, or do you have folks at Google who would help us review this?

**Comment by sideshowbarker** [comment]
We are still in need of a WASM domain expert to review this.

**Review by yurydelendik — APPROVED** [review]
The PR fixes the example: adds fields missing in previous declaration of the `api`, but they are used in a snippet below.

Just to note there are two `const api = {` fragments now. Is there a complete/live example for this article?

**Comment by sideshowbarker** [comment]
@ashikmeerankutty This PR seems to be waiting on your response to https://github.com/mdn/content/pull/2338#pullrequestreview-671281528

**Comment by ashikmeerankutty** [comment]
@sideshowbarker Missed the comment. @yurydelendik  https://developer.mozilla.org/en-US/docs/WebAssembly/existing_C_to_wasm This is the docs for the same.

**Comment by sideshowbarker** [comment]
@ashikmeerankutty I believe what @yurydelendik is asking about is the fact that:

1. This patch in this PR adds the sentence *“Now add the new functions to the api object. The updated api object will be:* and then a code block that shows a `const api` assignment; but
2. The code in the example at this point is code that’s built on code previously introduced in the article.
3. In the http://localhost:5000/en-US/docs/WebAssembly/existing_C_to_wasm#get_an_image_from_javascript_into_wasm section, there is already an assignment to `const api`.

So I guess the question is, should the code in the patch in this PR instead be re-written/moved to *replace* that existing `const api` assignment? Or what?

**Comment by ashikmeerankutty** [comment]
> So I guess the question is, should the code in the patch in this PR instead be re-written/moved to _replace_ that existing `const api` assignment? Or what?

Yes, It can be moved, I placed it below because I thought it may confuse the user. But initializing multiple `api` object also seems to be confusing. So I will add these functions to the above initialization of `api` object. Is that fine?

**Comment by sideshowbarker** [comment]
> > So I guess the question is, should the code in the patch in this PR instead be re-written/moved to _replace_ that existing `const api` assignment? Or what?
> 
> @sideshowbarker Yes, It can be moved, I placed it below because I thought it may confuse the user. But initializing multiple `api` object also seems to be confusing. So I will add these functions to the above initialization of `api` object. Is that fine?

Yup — think that should be fine 👍

**Comment by ashikmeerankutty** [comment]
@sideshowbarker  Cool, Made the change, Can you please review this.

**Comment by sideshowbarker** [comment]
@yurydelendik If you can re-review this, that’d be great. A preview of the rendered version including the change is at https://pr2338.content.dev.mdn.mozit.cloud/en-US/docs/WebAssembly/existing_C_to_wasm

**Review by yurydelendik — APPROVED** [review]

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Thanks much @yurydelendik, and thanks much @ashikmeerankutty for the patch, and congrats on landing your first docs change here — welcome aboard 🎉

**Pull request merged**
