### PR TITLE
Replace {{CSSxRef}} with HTML links

### PR DESCRIPTION
**Pull request by ramiy**
This PR deletes `{{CSSxRef}}` macros and replaces them with regular HTML links.

Why? See https://github.com/mdn/sprints/issues/3885#issuecomment-736326140

@chrisdavidmills Please review and merge.

It took me 6 hours to search & replace over 1,000 files, and I'm not done yet. I still have over 900 files to fix.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@chrisdavidmills While I'm all for reducing macros to a much smaller set, I would reconsider automatic cross references like this one. The thing is that they are just SO useful for both end users and for maintainers. By using a reference you can guarantee styling, you can move references around without breaking anything, and your users don't need to know much about docs structure - ie it is easy. 

What I would do is reduce the ref to a single common item and add a scope - ie not a specific one for the different types of cross reference, but something smart enough to work it out if scope not specified. Of course if you do this @ramiy will hate me :-0

**Comment by ramiy** [comment]
@hamishwillee read this post - https://hacks.mozilla.org/2020/12/welcome-yari-mdn-web-docs-has-a-new-platform/

> Gradually removing the old-style KumaScript macros that remain in MDN content, removing, rendering, or replacing them as appropriate. For example, link macros can just be rendered out, as standard HTML links will work fine, whereas all the sidebar macros we have should be replaced by a proper sidebar system built into the actual platform.

This is part of the roadmap. The migration from legacy KumaScript macros. Otherwise, I wouldn't spend hours to fix thousand of files.

**Comment by hamishwillee** [comment]
@ramiy I understand this ^^^ (and I read the link before I posted). I'm not saying you're not doing the right thing.

What I'm saying is that not every decision made is necessary a good one - automated cross linking to api reference has benefits.

**Comment by chrisdavidmills** [comment]
Thanks for this @ramiy . I'd wait on making any more fixes so that we can coordinate this with the development team, and make sure we are in agreement on how we are moving forward with this. I don't think your work here will be wasted, but I'm not going to merge this until we've got a clear focus and direction on this.

@hamishwillee the trouble is that our xref macros aren't particularly smart. You've still got to know the directory structure to a certain degree, they are an extra complication that we'd need to account for in our move to markdown, and now we are in GitHub their main benefit is no longer as important. I.e., you can now do mass search and replace easily, so if for example the whole CSS directory moved, we could just update the links in one fell swoop anyway.

And we can easily do post processing to make sure that all links that link to a CSS property page, or a JS property or method page, are wrapped in code tags.

**Comment by bershanskiy** [comment]
@ramiy 
> It took me 6 hours to search & replace over 1,000 files, and I'm not done yet. I still have over 900 files to fix.

Please don't do any more of manual labor. It's much better to render macros using scripts: it's less error-prone and way more efficient. If you need help, I'd be glad to answer your questions.

**Comment by peterbe** [comment]
Yes, we want to move away from KS macros, but it's not that simple. There are still some heavy KS macros we don't have an "answer" for at the moment. For example, certain sidebar macros can't simply be replaced because the ordering and grouping is very content-specific and there exists no current solution for describing that in another way. 

If we're ever going to be able to go Markdown, we need to get used to doing things a simpler way. You can still use KS macros in Markdown but if you stick to the basics you'll, for example, be able to use the "Preview" flap in GitHub's UI or the built-in Markdown previewer and linter you might have in the IDE. 

But what I'm not pleased with is that we have to type every absolute URL. I.e. if you type `<a href="/en-US/docs/Web/CSS/width">` your HTML becomes "broken" once we decide to rename the parent tree from "Web" to "webdev", for example. 

What we do for images is that you have to always use a relative path. 
```html
<!--  this is a FLAW -->
<img src="/en-US/docs/Foo/bar/screenshot.png">

<!-- this is OK -->
<img src="picture.png">
<img src="../sibling/other-picture.png">
```

And note with images, the HTML is actually rewritten before it's published. In the example above with the images, it actually becomes ``. 

Another advantage with the `CSSxRef` macro is that it becomes a bit easier to translate content. A translator won't need to fiddle with the attributes within the HTML if they can just type:

```html
<p>Lär dig mer om hur man kan sätta ett {{cssxref('background-color')}}</p>
```

And with a macro here, we could technically guess our best way for a translated content. E.g. you can dynamically check "Does there exist a `background-color` page in the current locale? No? Ok, let's fall back to en-US and log that this page is currently missing."

**Comment by peterbe** [comment]
Besides, I speculate it'd be easier to translate if it's pure HTML (or pure Markdown) with various third-party translation toolings. E.g.
```html
<p>Lär dig mer om hur man kan sätta ett <a href="background-color"><code>background-color</code></a></p>
```
...is nothing weird. Just plain HTML and no need to fiddle with the value of the `href` attribute.

**Comment by ramiy** [comment]
Guys, I agree with all you written here. I know the macros have advantages. But compare to HTML they have many disadvantages. For example, you can't add `title`, `aria` , `class`, `style` or any other attribute to the link. With HTML it's very easy. With macros you can't control the URL, with HTML it is part of the tag. And the most important, new contributors know HTML, they don't know macros.

Remember the main task - to deprecate KumaScripts. And as @chrisdavidmills mentioned, those macros are not particularly smart (see the [source here](https://github.com/mdn/kumascript/blob/master/macros/cssxref.ejs)).

If you ask me, it would be easier to create our own macros from HTML than from KumaScripts macros.

**Comment by sideshowbarker** [comment]
It’s been more than month and we don’t have agreement about merging this, so now closing it without prejudice — meaning that, anybody who feels strongly about this otherwise should feel free to reopen it.

**Pull request closed without merging**
