### PR TITLE
Elaborate on text

### PR DESCRIPTION
**Pull request by estelle**
Example wasn't clear due to fonts in new design.
Addresses https://github.com/mdn/content/issues/14716
Added text to clarify example=
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [X] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by wbamberg** [comment]
Do you think it would also help to use a blockquote here?

Screen Shot 2022-04-05 at 10 11 13 AM

**Comment by wbamberg** [comment]
oops, I was too slow for @teoli2003 :)

**Comment by teoli2003** [comment]
Blockquote would be nice too.

(Sorry, I always ask myself on small edition: "Is it better than the original" and not "Is it the best we can do")

**Pull request merged**
