### PR TITLE
Nschonni empty definitions

### PR DESCRIPTION
**Pull request by chrisdavidmills**
This is my attempt to fix the merge conflict over in https://github.com/mdn/content/pull/209

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by chrisdavidmills** [comment]
Hrm, there seems to have been lots of reviewers from many different teams requested on this one. Really all it needs is one reviewer to approve the general sweeping changes.

**Comment by chrisdavidmills** [comment]
@sideshowbarker approved, so let's merge.

@escattone I think we need to have a think about how the review teams feature is working here, and also talk about best practices for merge conflict fixing, which is what I've done all morning so far ;-)

**Comment by sideshowbarker** [comment]
> Hrm, there seems to have been lots of reviewers from many different teams requested on this one. Really all it needs is one reviewer to approve the general sweeping changes.
> @escattone I think we need to have a think about how the review teams feature is working here,

I think this is one of the limitations of using the `CODEOWNERS` mechanism to manage review approvals; specifically, if a change touches files from a lot of subtrees that have separate owners, the system will require approval from at least one designated code owner for each file that the PR touches. And that’s true regardless of whether you specify the code owners individually by name in the `CODEOWNERS` file, or specify teams.

So in cases like this one, the normal practical way to get the PR merged is for one of the people with admin perms to override the approval requirement to merge the change.

I don’t know what third-party off-the-shelf alternatives to using `CODEOWNERS` might be available. But I know that in part to get around this limitation, for https://github.com/web-platform-tests/wpt/ the infra team ended up rolling their own solution, which is a https://github.com/web-platform-tests/wpt-pr-bot. I don’t think that is as yet portable for use in other repos, but if we end up getting too frustrated with how the `CODEOWNERS`-based mechanism is working for us, then that WPT tool might turn out to be an alternative worth investigating.

**Comment by escattone** [comment]
@chrisdavidmills Regarding the `CODEOWNERS` mechanism, I think @sideshowbarker 's comment above is right on. For these PR's that span multiple "domains" and therefore pull-in lots of `CODEOWNERS` reviewers, we'll have to rely on someone with Admin perms for now.

Yes, we should talk about how best to help contributors with fixing merge conflicts. Perhaps we can refer contributors to [this reference](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/addressing-merge-conflicts)?

**Pull request merged**
