### PR TITLE
CSS Data Types: Capitalize page title

### PR DESCRIPTION
**Pull request by ramiy**
### Description

Use capitalize text in page title.

### Motivation

Similar to other pages.

### CODE REVIEW

**Comment by ramiy** [comment]
@bsmth Please review.

**Review by bsmth — APPROVED** [review]
tnx @ramiy 👍🏻

**Comment by Josh-Cena** [comment]
@ramiy @bsmth I don't think this is in line with our style guide: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#titles

If this needs to be fixed, we should change other titles to sentence case, not change this one to title case. Would be cool if you can redo this PR.

**Comment by bsmth** [comment]
Thanks for the hints. I'm going to revert for now. FYI @ramiy the guidelines state

> Correct: "A new method for creating JavaScript rollovers"
> Incorrect: "A New Method for Creating JavaScript Rollovers"

so other pages need to be fixed to match the guidelines.

**Pull request merged**
