### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by RobertRodes**
In "Individual date and component values," last paragraph: changed "May 31th" to "May 31st."

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:

**Comment by RobertRodes** [comment]
Outstanding. Thank you! I'll have to add this to my resume haha

**Comment by RobertRodes** [comment]
Question. I see "7 of 9 checks passed" in the merged commit comment above. I've also received two emails " Run failed: PR review companion - main (8538f00)" (the second one says attempt 2). Is there a correlation? Also, did I not have to hit the buttons that said "Create Pull Request" on them, and would that perhaps have something to do with these error messages?

**Comment by teoli2003** [comment]
No, given the changes were self-contained (th -> st), I merged this before the tests were completed. I usually don't do this, but I was in a hurry right at that moment.

**Comment by RobertRodes** [comment]
Oh, that makes sense. Hard to see any sort of test going wrong with that one. Thank you!

**Pull request merged**
