### PR TITLE
Convert Example to Live Sample and remove typewriter simulation demo

### LINKED ISSUE #9044: Issue with "setInterval()": (Typewriter simulation demo results 404)
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/setInterval

#### What information was incorrect, unhelpful, or incomplete?

View this demo in action under the Typewriter simulation resolves to 404 Page Not Found.

#### Specific section or headline?

Yes, https://developer.mozilla.org/en-US/docs/Web/API/setInterval#example_3_typewriter_simulation

#### What did you expect to see?

Demo page for the Typewriter simulation.

#### Did you test this? If so, how?

Yes, by visiting the demo page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/setinterval`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/setInterval
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/setinterval/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

### PR DESCRIPTION
**Pull request by AnilSeervi**
- Fixes #9044
---
- Remove TypeWriter Example
- Convert alternating colors example to live sample
- update id link by reducing a space

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thanks for this PR! But I think the right thing to do here (if we want to keep this example at all, which I'm not sure about) would be to make this into a live sample, as we did for https://github.com/mdn/content/pull/8667 .

**Comment by AnilSeervi** [comment]
> Thanks for this PR! But I think the right thing to do here (if we want to keep this example at all, which I'm not sure about) would be to make this into a live sample, as we did for https://github.com/mdn/content/pull/8667 .

Yes. I too thought about converting it into a live sample. But then the example would start right away when the page loads and it'd be over by the time some users get to it. I know that there are controls to trigger the actions. But,
I'm not sure if the example should be kept or be removed ¯\_(ツ)_/¯

**Comment by wbamberg** [comment]
> > Thanks for this PR! But I think the right thing to do here (if we want to keep this example at all, which I'm not sure about) would be to make this into a live sample, as we did for #8667 .
> 
> Yes. I too thought about converting it into a live sample. But then the example would start right away when the page loads and it'd be over by the time some users get to it. I know that there are controls to trigger the actions.

That's a good point. Yes, it would need some kind of "start/reset" buttons.

> But, I'm not sure if the example should be kept or be removed ¯_(ツ)_/¯

Looking at this page as a whole, I think it ought to have at least one live sample. At the moment it has none but has two examples that could be converted to live samples, "Alternating two colors", and "Typewriter simulation". I think the issue I have with the typewriter one is that it's quite long and has a lot of complexity in it that's not relevant to the `setInterval` API, and this makes it hard to use as an example of the API. And I don't see that the typewriter one demonstrates a different enough usage of `setInterval` to merit another example.

So, I think the best thing for this page:
* delete the typewriter example
* convert "Alternating two colors" into a live sample (but giving a start/stop button so it's not doing it all the time).

Also for "Alternating two colors" it might also be worth changing it to set a class attribute on the element, and having some separate CSS, like:

```css
.stop {
  color: red;
}

.go {
  color: green;
}
```

...rather than setting the CSS inline with the `style` (since inline CSS is not good practice).

What do you think?

**Comment by wbamberg** [comment]
(also, this is completely irrelevant but typewriter simulations should build in some randomized delay before each "keypress". They look much more realistic that way :)

**Comment by AnilSeervi** [comment]
Agree with you @wbamberg.
The typewriter example can be removed and put into a external link where one can visit to, if they need a complex example to understand the API better.

The conversion to live sample of the simple example would add to the understanding of the API right away.👍

> Looking at this page as a whole, I think it ought to have at least one live sample.

**Comment by wbamberg** [comment]
I've assigned you the issue, hope that's OK :).

> The typewriter example can be removed and put into a external link

I think it can just be removed, without an external link. Otherwise one day it will rot and someone will file this bug again :).

**Comment by AnilSeervi** [comment]
> I've assigned you the issue, hope that's OK :).
> 
Yea sure no problem.

> > The typewriter example can be removed and put into a external link
> 
> I think it can just be removed, without an external link. Otherwise one day it will rot and someone will file this bug again :).
> 
Will remove it:)

**Comment by AnilSeervi** [comment]
Looking good, aint't it. @wbamberg

**Review by wbamberg — APPROVED** [review]
Yes, this looks great :).

**Pull request merged**
