### PR TITLE
NodeFilter.SHOW_ALL has wrong value (follow-up)

### PR DESCRIPTION
**Pull request by jackdeguest**
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [X] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by sideshowbarker** [comment]
Can you please combine this and the other ones into a single PR?

**Comment by jackdeguest** [comment]
> Can you please combine this and the other ones into a single PR?

Sorry no. I am using the web interface to do so, and I don't want to fork the whole thing on the command line.

**Comment by sideshowbarker** [comment]
> Sorry no. I am using the web interface to do so, and I don't want to fork the whole thing on the command line.

OK, I’ll merge the others into this one in a minute

**Comment by jackdeguest** [comment]
> > Sorry no. I am using the web interface to do so, and I don't want to fork the whole thing on the command line.
> 
> OK, I’ll merge the others into this one in a minute

Thanks, I appreciate it. If it is possible to do via the web, please point me to some docs.

**Comment by sideshowbarker** [comment]
Superseded by https://github.com/mdn/content/pull/11657

**Comment by sideshowbarker** [comment]
> Thanks, I appreciate it. If it is possible to do via the web, please point me to some docs.

I don’t have much experience using the web UI to edit files — but if you’ve looked yourself and found there’s no way to edit multiple files in one PR using the web UI, then I suspect there just really isn’t such a way.

**Pull request closed without merging**
