### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by absurdprofit**
- Changed "These sequenced" to "These sequences".
- Changes "it is complete" to "they are complete".

#### Summary

Fixed typos.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ✅] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by nxtexe** [comment]
Also the youtube video linked on the page has an error saying "This video is private".

**Review by teoli2003 — APPROVED** [review]
👍 Good catch!

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:

**Comment by nxtexe** [comment]
Glad to be apart of something great mate.

**Pull request merged**
