### PR TITLE
Fix #27666 Inconsistent use of window.requestAnimationFrame v requestAnimationFrame

### LINKED ISSUE #27666: Unnecessary / Inconsistent use of window.
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_animations

### What specific section or headline is this issue about?

First two code examples

### What information was incorrect, unhelpful, or incomplete?

The calls to 
`window.requestAnimationFrame(draw);`

in the first sample and
`window.requestAnimationFrame(clock);`

in the second sample inconsistently use the `window` reference when using DOM API's

### What did you expect to see?

I expected not to see the reference to window
`requestAnimationFrame(draw);`
and
`requestAnimationFrame(clock);`
in the second sample

### Do you have any supporting links, references, or citations?

The last sample is consistent with the implied use of `window`. 

It shows consistent reference via implied `window` as follows `requestAnimationFrame(anim)`

As do all samples showing implied window reference for `document ` rather than `window.document`

### Do you have anything more you want to share?

Maybe a second issue? The first sample uses `Date` to get a time to used to animate content rather than use the time parameter (not defined in the sample) passed to the `requestAnimationFrame` callback.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvas_api/tutorial/basic_animations`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_animations
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/basic_animations/index.md
* Last commit: https://github.com/mdn/content/commit/db59cf229e24aae0fb316a838080490818b66ac6
* Document last modified: 2023-02-20T09:57:49.000Z

</details>

### PR DESCRIPTION
**Pull request by skyclouds2001**
### Related issues and pull requests

#27666

note that this may not a fix to #27666, as the issue creator suggest that use `requestAnimationFrame` instead of `window.requestAnimationFrame`, but in my view below, it is better to use `window.requestAnimationFrame`, reasons are below

and @blindman67 did not give further response anymore

### CODE REVIEW

**Comment by blindman67** [comment]
@skyclouds2001 No not fixed.

`window` is the default `this` and its use in the examples is redundant. IE `window.requestAnimationFrame` is the same reference as `requestAnimationFrame`

In the example code the use of `window` is inconsistent (across all examples). It is used with `window.requestAnimationFrame` but not with `window.document.createElement` or `new window.Date()` and many more window properties used in the examples.

**Comment by skyclouds2001** [comment]
> @skyclouds2001 No not fixed.
> 
> `window` is the default `this` and its use in the examples is redundant. IE `window.requestAnimationFrame` is the same reference as `requestAnimationFrame`
> 
> In the example code the use of `window` is inconsistent (across all examples). It is used with `window.requestAnimationFrame` but not with `window.document.createElement` or `new window.Date()` and many more window properties used in the examples.

Well, I understand what you mean now completely

And my opinion is that, whether we use `window.xx` or `xx` might can be judged by following reasons:

* whether the variable is in Web API standard or in ECMAScript standard
* whether the variable is defined as a property on `Window` interface or just simply expose to global scope (in main context it is the `window`)
* whether the variable is a well-known symbol
* wether other developers may confuse it as a custom variable

For example:

* prefer using `document` instead of `window.document`, since `document` property is well-known enough and develpors wouldn't confuse it as a custom variable
* prefer using `Date` instead of `window.Date`, since `Date` is *exposed* to global scope not *defined* on `Window` interface and `Date` is a ECMAScript standard, not a Web API standard
* prefer using `window.print()` instead of `print()`, since `print` is a commonly used symbol and may be comfused by

Here I prefer to use `window.requestAnimationFrame()` better

**Comment by skyclouds2001** [comment]
see also https://github.com/mdn/content/issues/10573#issuecomment-1816017198 and https://github.com/mdn/content/pull/30329#discussion_r1396975842

**Comment by skyclouds2001** [comment]
@blindman67 would you offer your idea on whether using `window.requestAnimationFrame` or `requestAnimationFrame` is better

**Comment by teoli2003** [comment]
Prefixing `requestAnimationFrame()` with `window` prevent to directly copy-paste the snippet into a worker code. Using `self` or nothing doesn't have this problem (and they still work on the Window global scope).

I have no strong feelings about these two solutions (`self` or nothing), though we should uniformize–for sure on a given page, likely everywhere– and I don't see a benefit of `self.`. 

cc/ @wbamberg @elchi3 that may have some extra insight here.

**Pull request closed without merging**
