### PR TITLE
Add example for base64 parameter issue #2186

### PR DESCRIPTION
**Pull request by keithxemi**
I thought I did this, trying again.

### CODE REVIEW

**Comment by Rumyra** [comment]
This is an excellent example - I think it could also go on the main URLSearchParams page under the 'Gotchas' heading https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#gotchas

Would you be able to add this @keithxemi ? If its easier for you I can commit this PR and you open a new one for the main page, or you can amend this PR. Either way let me know :)

**Comment by keithxemi** [comment]
I'll go ahead and add to the gotchas too, thanks.

**Comment by Rumyra** [comment]
Hi @keithxemi just following up to see how you're getting on with the gotchas bit... let me know thanks!

**Comment by keithxemi** [comment]
Gothchas now has my examples. I had originally thought they belonged here
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get and I
think I did a pull for that too. Perhaps one place for them is sufficient,
as a word to the wise.

**Comment by Rumyra** [comment]
Brill thanks so much @keithxemi 🎉

I agree let's keep them on the main page 👍

**Pull request closed without merging**
