### PR TITLE
Adds platform and label properties for screenshots member

### LINKED ISSUE #11100: Issue with "screenshots": missing "label" member
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots

#### What information was incorrect, unhelpful, or incomplete?

This page should include information about the `label` member.

https://w3c.github.io/manifest-app-info/#label-member

#### Specific section or headline?

Examples

#### What did you expect to see?

an example with the `label` member specified

#### Did you test this? If so, how?

No?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/manifest/screenshots`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/manifest/screenshots/index.md
* Last commit: https://github.com/mdn/content/commit/4c03c6709411f09bd0350b1f5d4bdcbf0525ef3d
* Document last modified: 2021-10-11T10:39:03.000Z

</details>

### PR DESCRIPTION
**Pull request by AnilSeervi**
#### Summary

Adds `platform` and `label` properties for `screenshots` member.
#### Motivation

Open-source
#### Supporting details

https://w3c.github.io/manifest-app-info/#dfn-screenshots-object
#### Related issues

Fixes #11100 
#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by Rumyra** [comment]
Hi @AnilSeervi this looks great, thank you!

For the `platform` key, could we add what values are possible - like here on the dir page https://developer.mozilla.org/en-US/docs/Web/Manifest/dir, there's a bit starting

> The dir member can be set to one of the following values:

**Comment by AnilSeervi** [comment]
> For the `platform` key, could we add what values are possible - like here on the dir page https://developer.mozilla.org/en-US/docs/Web/Manifest/dir

There's about a list of 15 possible values for the `platform` member : as listed [here](https://w3c.github.io/manifest-app-info/#platform-member).

Does that mean we should list all the values or just the _general-purpose_ values(`narrow` & `wide`) ?

**Comment by Rumyra** [comment]
I would be explicit and list them all - you could group them as per the spec. So _general purpose_ first with n explanation. Then as the os & distribution ones are pretty self explanatory add them in a sentence underneath.

**Review by AnilSeervi — COMMENTED** [review]
Does this look ok? @Rumyra

**Comment by Rumyra** [comment]
Thanks so much @AnilSeervi - this is brill 👍

**Review by Rumyra — APPROVED** [review]

**Pull request merged**
