### PR TITLE
fix: font-descriptor

### PR DESCRIPTION
**Pull request by HomyeeKing**
according to https://w3c.github.io/csswg-drafts/css-font-loading/#dictdef-fontfacedescriptors

### CODE REVIEW

**Comment by HomyeeKing** [comment]
btw, need to  change the `variationSettings ` ---> `variant `?

**Review by hamishwillee — APPROVED** [review]
Thanks very much @HomyeeKing - good catch!

**Comment by HomyeeKing** [comment]
@hamishwillee  btw, need to change  `variationSettings`---> `variant` or just add `variant` prop in `font-descriptor`?
since `variationSettings` is experimental for now

**Comment by hamishwillee** [comment]
Hi @HomyeeKing 

I don't understand what you mean by "btw, need to change variationSettings---> variant or just add variant prop in font-descriptor? since variationSettings is experimental for now"

I think you are suggesting that the descriptor [variationSettings](https://developer.mozilla.org/en-US/docs/Web/API/FontFace/FontFace#variationsettings) in the FontFace constructor should be renamed to `variant`, but I don't understand the logic of why?

Note, the values just match the spec: https://w3c.github.io/csswg-drafts/css-font-loading/#font-face-constructor

You can add a new PR if you want to make it more clear what the problem is?

**Pull request merged**
