### PR TITLE
text revisions to JS .toLocaleTimeString() doc

### PR DESCRIPTION
**Pull request by timohaver**
1. syntax corrections in the **Syntax** section
2. removed **Checking for support for locales and options arguments** section that was predicated on lack of browser support
3. grammar and punctuation corrections
4. other text revisions for clarity and readability

MDN URL
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString

### CODE REVIEW

**Review by Elchi3 — CHANGES_REQUESTED** [review]
Thanks for your PR!

> locales -> locale

Can you elaborate on this change? It is plural because you can use multiple locales for this parameter as an array. I don't think the change is correct.

**Comment by timohaver** [comment]
Thank you for your review.

I did not know that the locales parameter could be a string or an array. Regardless, the singular form seems more appropriate (to me). It's not obvious to me why the plural form (locales) would be more correct. 

1. The name of the method uses the singular form.

2. All of the MDN examples use a string. Only one example uses more than a single locale and this is to illustrate how to include a fallback. (Perhaps using a single locale is the more common use case?)

2.1 All of the other Google page one search results that provide examples also use a string for this parameter, likewise suggesting that this is the more typical use case.

3. Although my limited searching did not yield an example using an array of locales, does that kind of use not return a string for each locale? While I am necessarily speculating, it seems likely that the return value maintains a one-to-one relationship with a locale value. If I am correct about this, then the return value is based on a locale in the array, rather than on multiple locales in the array. It would be confusing (IMO) to suggest a return value is somehow based on locales if it is actually based on just one locale in the array. 

Does this rationale sense to you?

**Comment by Elchi3** [comment]
Thanks for elaborating!

> I did not know that the locales parameter could be a string or an array. Regardless, the singular form seems more appropriate (to me). It's not obvious to me why the plural form (locales) would be more correct.

Just using one `locale` is probably more common, but what should guides us here is the specification which formally defines these things. It uses the term `locales`: https://tc39.es/ecma402/#sup-date.prototype.tolocaletimestring. I think the docs should use that as well then.

> All of the MDN examples use a string. Only one example uses more than a single locale and this is to illustrate how to include a fallback. (Perhaps using a single locale is the more common use case?)

This seems to me like the real issue here. I think the "Parameters" section and the examples could be more clear on why it is `locales`. It currently just refers to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#parameters which explains the `locales` and `options` parameter in much more details. Please note that `locales` and `options` is actually a concept that appears in many methods of the JS Intl API. I guess this was a matter of not wanting to repeat all this information across multiple pages. However, as you point out in this PR, it seems like that isn't ideal.

**Comment by sideshowbarker** [comment]
@Elchi3, @timohaver from glancing through the comment history, it’s not clear what this PR is waiting on?

**Comment by Elchi3** [comment]
Thanks for the nudge @sideshowbarker. 
It looks like locales -> locale changes have been reverted. Thanks @timohaver! 

So, as far as I can see the only change needed now is to resolve the merge conflict. The correction to the syntax in here is actually wrong. I've simplified syntaxes in a different PR already to avoid the confusing brackets altogether.

**Comment by wbamberg** [comment]
@Elchi3 , I just resolved the merge conflict.

**Review by Elchi3 — APPROVED** [review]
Thanks Will!

**Pull request merged**
