### PR TITLE
Update index.md with new CSS grid Creator (tool) link

### PR DESCRIPTION
**Pull request by Weedshaker**
https://weedshaker.github.io/cssGridLayout/ is a Drag and Drop CSS grid Creator with live preview in HTML with inline style and HTML with CSS.

### Description

This tool shall not only guide people to quickly assemble a CSS grid by drag and drop but also help them to learn the html/css output with live updates.

The PR changes are: Adding a link to the CSS grid Creator at index.md of the CSS Grid Layout page.

### Motivation

To give readers a quick understanding on how to create, change and modify a CSS grid by simple drag and drop modifications. The motivation is to make CSS grid more wide spread and help people to use it.

### Additional details

[](https://github.com/Weedshaker/cssGridLayout)

image

### CODE REVIEW

**Comment by dipikabh** [comment]
Hello @Weedshaker! Welcome to the MDN Web Docs project, and thank you for your pull request.

Unfortunately, we cannot accept this external link. Please see our [external link policy](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#external_links). 

Thank you for your contribution but we’ll be closing this PR. We appreciate your understanding.

**Comment by Weedshaker** [comment]
Dear @dipikabh ,

Thank you for looking at this Pull Request. 

**1. Did you actually have a look at CSS Grid Creator: https://weedshaker.github.io/cssGridLayout/ ?
2. Regarding the external link policy, which exact rules are not fulfilled with my PR?
3. What is the actual reason?**

I hope you could answer the above questions, so I can adjust the CSS Grid Creator to fulfill the external link policy of MDN.

Furthermore the CSS Grid Creator has been very helpful with learning CSS grid as much as https://cssgridgarden.com/ , which is an external Link on the same page just above to where I wanted to place the link. Additionally, Grid Garden is from Codepip, which violates the external link policy "Appearance of endorsement, especially for commercial products or services", since they have an offer for a pro subscription. But don't get me wrong and take down Grid Garden, since we all love it. I simply wanted to make a comparison but I understand that the CSS Grid Creator is not yet as beautiful as Grid Garden still you should measure against the same standards...

In that spirit let's have a look at the MDN external link policy. Bullet point by bullet point:

Good external links: Good external links take readers to resources that are relevant, durable, and widely trusted. You should prefer adding links to external content that is:

- Broken or outdated links
   **-> The link is not broken and placed on github, so as reliable as the mdn documentation hosted on github.**
- Appearance of endorsement, especially for commercial products or services
   **-> There is nothing commercial related with CSS Grid Creator, it is Open Source under GPL-3.0 license**
- Attempt to use MDN Web Docs to distribute spam
   **-> It took a long time to program the CSS Grid Creator, it is very helpful with learning and creating a CSS grid, in this regard far off to be spam**

- **Good external links**: Good external links take readers to resources that are relevant, durable, and widely trusted. You should prefer adding links to external content that is:

  - Unique or indispensable (e.g., an IETF RFC)
   **-> So far I didn't find any CSS Grid drag and drop application, so it should be unique. If it is indispensable that is up to the user.**
  - Necessary for attribution, citation, or acknowledgement (e.g., as part of a Creative Commons attribution)
   **-> Done, only dependency is interact.js**
  - More likely to be maintained for the topic than incorporating such content on MDN Web Docs itself (e.g., a vendor's release notes)
   **-> You are very welcome to incorporate the CSS Grid Creator directly on MDN**
  - Open source or community-driven, like MDN Web Docs itself
   **-> YES 100%**

- **Poor external links**: Poor external links lack relevance, maintainability, accessibility, or otherwise put up barriers to readers. Avoid adding links to external content that is:

  - Generic or non-specific (e.g., a vendor's home page, instead of the related documentation)
   **-> It is very specific to CSS Grid**
  - Ephemeral or unmaintained (e.g., a one-time announcement)
   **-> It is maintained as well as open for anyone to contribute on CSS Grid Creator**
  - Self-linking or self-promotional (e.g., the author's own work off of MDN Web Docs)
   **-> It is not self-promotional but it has a link to the github repo, so that other people can participate.**
  - Paywalled (e.g., an expensive course beyond the reach of hobbyists, students, or readers living in lower-income countries)
   **-> It's all free.**
  - Inaccessible (e.g., a video without captions)
   **-> It is as accessible as it gets with drag and drop**

- **Links that are self-promotional or spam**: While a personal blog post, conference talk, or GitHub repository has value, linking to your own resources can create the appearance of a conflict of interest. Think twice before linking to resources that you have a business or personal connection with.
   **-> It is difficult to disconnect the CSS Grid Creator from my github account but as mentioned above, it would be fine for me to incorporate it directly in the MDN Docs and move the repo to somewhere without any link to me, but I think that is a stretch and as mentioned this is a valuable source for learning CSS Grid**

In the light of the above, I hope that you (@dipikabh) could reconsider this PR and if not may bounce it off on an other reviewer. It really took a long time to create the Grid Creator and I did in the spirit of Grid Garden to teach this awesome technology.

Again, thank you!

**Comment by bsmth** [comment]
Hi @Weedshaker, thanks a lot for your submission and comments. We appreciate that you have put a lot of work into this project. As @dipikabh has mentioned, this addition does not conform to our editorial policy; we do not accept external links by authors to their own tools/projects and will not be reopening this PR based on this policy. 

Thanks for your understanding :)

**Comment by katywings** [comment]
Hey @bsmth
I am not the author of the mentioned css grid project. But it seems to be a useful learning resource, therefore i am wondering: would you accept the PR, if I made it?

**Pull request closed without merging**
