### PR TITLE
Change the docs of fetch API

### PR DESCRIPTION
**Pull request by Abhishek01039**

### CODE REVIEW

**Review by avivmu — COMMENTED** [review]
Why 3 commits for this change? Please [fixup](https://www.google.com/search?q=git+fixup&oq=git+fixup+&aqs=chrome..69i57j0l7.3999j0j7&sourceid=chrome&ie=UTF-8) so there will be one commit

**Comment by Abhishek01039** [comment]
I have messed up something here.
so I have created a new PR.

**Comment by avivmu** [comment]
No need to create a new PR. Just take a look at how to [fixup](https://www.google.com/search?q=git+fixup&oq=git+fixup+&aqs=chrome..69i57j0l7.3999j0j7&sourceid=chrome&ie=UTF-8) commits. If you need help we'll be happy to assist.

**Comment by Abhishek01039** [comment]
sorry I have created 
should I close that? 
@avivmu

**Comment by avivmu** [comment]
No, but for next time you can update an existing PR.

**Pull request closed without merging**
