### PR TITLE
fix: remove duplicate Non-standard_header

### PR DESCRIPTION
**Pull request by skyclouds2001**
### Description

fix: remove duplicate Non-standard_header

### Motivation

small fix

### Additional details

None

### CODE REVIEW

**Comment by wbamberg** [comment]
The duplicate was added in https://github.com/mdn/content/pull/24666 - @OnkarRuikar , do you think this is a bug in your sync script? https://github.com/mdn/content/pull/24666/files#diff-8cd2d43d38b515affd9269216176d7f91bc59614b9adb23ecce4e349fb100d41R8 looks like it introduces a duplicate, too.

**Review by wbamberg — APPROVED** [review]
👍 thank you for the fix, @skyclouds2001 !

**Comment by OnkarRuikar** [comment]
> The duplicate was added in #24666 - @OnkarRuikar , do you think this is a bug in your sync script? https://github.com/mdn/content/pull/24666/files#diff-8cd2d43d38b515affd9269216176d7f91bc59614b9adb23ecce4e349fb100d41R8 looks like it introduces a duplicate, too.

It is because it didn’t find the `{{non-standard}}` header on the first non-blank line after front-matter. The script assumes that all the headers are defined on the same line after front-matter. Almost all the files define headers this way.\
Looking for the headers in document content is complex as there are many ways and places it can be put. Many weird cases have been handled in 11k+ files before the script became stable.

If we decide on fix header section syntax then not only it’ll be easy to retrieve them but also easy to edit/add by the script.\
Also, custom markdown linter rule/ front-matter validator will be able to validate them. 🤔

**Comment by skyclouds2001** [comment]
it seems that #26609 added many duplicate {{non-standard}} in many other files, too

**Comment by OnkarRuikar** [comment]
> it seems that #26609 

#26609 is not the fault of the script

>  added many duplicate {{non-standard}} in many other files, too

Not really, I found only two https://github.com/mdn/content/pull/26614 .\
Considering what happenned in #26609, for missed banners we need to check individual cases.

**Pull request merged**
