### PR TITLE
Add Spring as Java server framework

### PR DESCRIPTION
**Pull request by TurekBot**
This PR is in regard to the Sending and retrieving form data article, section "Other languages and frameworks" https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data#other_languages_and_frameworks

It seems to make sense to include a framework for Java since it's [one of the most used](https://insights.stackoverflow.com/survey/2021#technology-most-popular-technologies#:~:text=Java) languages in the world currently and is often taught in schools. 

Spring has a [quick-start tutorial](https://spring.io/guides/gs/handling-form-submission/) specifically about handling form submission which seems like a really good fit.

Let me know if there's anything you'd like changed!

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

Not an issue, just an improvement.

> What was wrong/why is this fix needed? (quick summary only)

My addition includes a server-side framework for Java because it's a very popular language.

> Anything else that could help us review it

Nope!

### CODE REVIEW

**Comment by teoli2003** [comment]
I think we should remove all external links from this list. It is very subjective and unmaintainable. We can add a sentence about the existence of dozens of solutions besides the one with guides on MDN.

What do you think @Rumyra, @wbamberg

**Comment by wbamberg** [comment]
You mean, keep the links to Django and Express (since we are already endorsing these to the (much greater) extent of writing guides to them) and remove the others, just replacing them with a general statement that lots of alternatives exist? I think that's a good idea.

**Comment by teoli2003** [comment]
Yes, that is what I meant.

**Comment by hamishwillee** [comment]
I don't particularly agree that these links are a problem  (given the frameworks are all popular and long lived, and so are their links). I guess it does reduce ongoing maintenance due to the fact we'll always be missing someone's favourite framework.

**Comment by Rumyra** [comment]
In the contexts of this page, I think adding one Java framework is ok. I do think however this should not be an extensive list moving forward. One example of all the top server side language frameworks gives the learner an overview into what to expect if they carry on learning in this area.

The discussion on external links can be done outside of this PR (I think this will need some very clear guidelines).

I'll merge this and then start making some notes on what we expect from external links :)

**Review by Rumyra — APPROVED** [review]

**Pull request merged**
