### PR TITLE
Add a more detailed explanation of boolean in glossary

### LINKED ISSUE #24085: Boolean definition in HTML
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Boolean

### What specific section or headline is this issue about?

_No response_

### What information was incorrect, unhelpful, or incomplete?

Setting open, open="", open="false", or even open="😛" means open is set. That is the definition of boolean attributes in HTML. See https://codepen.io/estelle/pen/NWBEzoY and the second paragraph in https://developer.mozilla.org/en-US/docs/Glossary/Enumerated

We should amend the https://developer.mozilla.org/en-US/docs/Glossary/Boolean to add the HTML equivalent of what is on https://developer.mozilla.org/en-US/docs/Glossary/Enumerated

### What did you expect to see?

An explanation of what boolean means in HTML

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/boolean`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Boolean
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/boolean/index.md
* Last commit: https://github.com/mdn/content/commit/9d53a300e0baae28dcad8c60080fa0152dd2b023
* Document last modified: 2023-01-13T15:50:18.000Z

</details>

### PR DESCRIPTION
**Pull request by HCY123902**
### Description

Added documentation for the definition of boolean in HTML and linked the boolean definitions in ARIA and JavaScript to the corresponding sections.

### Related issues and pull requests

Fixes #24085

### CODE REVIEW

**Comment by HCY123902** [comment]
@hamishwillee Hello, can you kindly take a look at this pull request? Many thanks

**Comment by hamishwillee** [comment]
Hi @HCY123902 

We try and keep the glossary entries "short and sweet". If additional information is useful (and this appears to be) it should be linked in the See also section (you can provide a brief sentence after the link explaining what is covered at the end point).

I'm therefore closing this.

**Comment by HCY123902** [comment]
> Hi @HCY123902
> 
> We try and keep the glossary entries "short and sweet". If additional information is useful (and this appears to be) it should be linked in the See also section (you can provide a brief sentence after the link explaining what is covered at the end point).
> 
> I'm therefore closing this.

Thanks for the suggestion. Should I open a new pull request to do what you suggested, since this issue is still relevant

**Comment by Josh-Cena** [comment]
This PR is fixing an issue, so yes @HCY123902 you may go ahead and try to shorten it a bit while still meeting the criteria of fixing the issue.

**Comment by HCY123902** [comment]
> This PR is fixing an issue, so yes @HCY123902 you may go ahead and try to shorten it a bit while still meeting the criteria of fixing the issue.
> 
> @hamishwillee Frankly https://developer.mozilla.org/en-US/docs/Glossary/Enumerated is quite long anyway, and due to the nature of how the HTML reference is structured, it would be hard in the short term to shorten the glossary entry much. I'm okay as long as the Boolean and Enumerated pages follow the same style.

I have revised it to make the description more concise. Can you help to take a look again? Many thanks

**Comment by hamishwillee** [comment]
@Josh-Cena Unsetting myself as a reviewer. Feel free to approve if you think this is a useful pattern. Someone obviously did, but it was not me :-)

FWIW If it were up to me, and I thought having aria and html information was useful, I'd probably write separate glossaries and let yari do the disambiguation for me.

**Comment by Josh-Cena** [comment]
> I'd probably write separate glossaries

That would be a nice pattern as well, like https://developer.mozilla.org/en-US/docs/Glossary/Property ?

**Comment by teoli2003** [comment]
I think @hamishwillee is right, and we should have several glossary entries: Boolean, Boolean (JavaScript), Boolean (ARIA), and Boolean (HTML). It will be clearer without adding clutter to the primary entry.

**Comment by hamishwillee** [comment]
Yes. Another example is https://developer.mozilla.org/en-US/docs/Glossary/Signature - there are several sub topics. I don't remember the magic that makes it all work, but I'm sure if you copy the pattern you'll find out :-)

**Comment by teoli2003** [comment]
There is a macro `{{GlossaryDisambiguation}}` (or similar).

**Comment by HCY123902** [comment]
Thanks for the suggestion. I have made the changes accordingly

**Comment by HCY123902** [comment]
@Josh-Cena @teoli2003 Can anyone help to take a look again? Many thanks

**Review by hamishwillee — APPROVED** [review]
This looks excellent.

There is a bug in the rendering of `{{GlossaryDisambiguation}}` but I'll post an issue for that in Yari.

**Pull request merged**
