### PR TITLE
Add spec URLs for the web/http subtree

### PR DESCRIPTION
**Pull request by sideshowbarker**
Part of https://github.com/mdn/content/issues/13126

### CODE REVIEW

**Comment by sideshowbarker** [comment]
A number of these files already had a `browser-compat` key — which makes it unnecessary for them to also have a `spec-urls` key. So in those cases, the automation just replaced the manual specifications table with a `{{Specifications}}` macro — and did not also add a `spec-urls` key — so that the Specifications table in the output is generated from the BCD data.

**Comment by sideshowbarker** [comment]
This is now just blocked on https://github.com/mdn/yari/pull/5314

**Comment by sideshowbarker** [comment]
This is now blocked on both https://github.com/mdn/yari/pull/5314 and https://github.com/mdn/yari/pull/5329

**Review by teoli2003 — APPROVED** [review]
This looks amazing!

**Pull request merged**
