### PR TITLE
Downgrade requestPostAnimationFrame rule to a suggestion

### PR DESCRIPTION
**Pull request by kenrussell**
Users attempting to put requestPostAnimationFrame into production
using polyfills are running into performance problems. Turn this best
practice into a suggestion and add a cautionary note about it.

> What was wrong/why is this fix needed? (quick summary only)

Users are encountering performance problems on some browsers when using this best practice.

> MDN URL of main page changed

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices

> Issue number (if there is an associated issue)

None

> Anything else that could help us review it

### CODE REVIEW

**Review by kdashg — APPROVED** [review]

**Comment by wbamberg** [comment]
@chrisdavidmills , do you know if requestPostAnimationFrame is implemented in Firefox? The only place I can find anything on this, apart from the WebGL "best practices" page, is https://github.com/WICG/request-post-animation-frame/blob/main/explainer.md. If it's not implemented by any browsers perhaps we should just remove this section?

**Comment by jdashg** [comment]
At one point this had a polyfill that I wrote, and I'm curious what happened to it.

**Comment by jdashg** [comment]
Here was that section in our collaboration draft, with the polyfill: https://hackmd.io/Ek2ntZHvQ8SpyYe8kYKTKg#Use-requestPostAnimationFrame-not-requestAnimationFrame

**Comment by jdashg** [comment]
I don't want to remove the section because it's definitely best-practice in Firefox, and it's only because there's some as-of-yet-undiagnosed issue with Chrome that we're adding this caveat.

**Comment by jdashg** [comment]
For reference I am the WebGL lead for Firefox and the main author of the original collaboration document.

**Comment by wbamberg** [comment]
So if I understand right (and thanks @sideshowbarker for helping me understand!):

* `requestPostAnimationFrame` isn't implemented in any browsers but is only used as a polyfill
* the polyfill should not be used in Chrome, but only in Firefox

If that's right, it would be helpful if this section said this, and also reinstated the polyfill itself, which used to be in this section but has disappeared.

**Comment by sideshowbarker** [comment]
@kenrussell This PR seems to be waiting on your response to https://github.com/mdn/content/pull/4688#issuecomment-833223515

**Comment by kenrussell** [comment]
Apologies for the delay coming back to this. Have revised based on review feedback and put in the previously-lost polyfill.

**Review by sideshowbarker — APPROVED** [review]

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Ken, thanks much, and congrats on landing your first docs changes here (along the patch from #4686) — welcome aboard 🎉

**Comment by kenrussell** [comment]
Thanks @sideshowbarker, @wbamberg and @jdashg !

**Pull request merged**
