### PR TITLE
docs: note on `yarn content flaws`

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
This looks like one for @peterbe to preside over really.

**Review by peterbe — CHANGES_REQUESTED** [review]
I love that you made improvements to the README, but there is already a CLI wrapper for applying fixable flaws. See `yarn tool flaws --help`

**Comment by nschonni** [comment]
> I love that you made improvements to the README, but there is already a CLI wrapper for applying fixable flaws. See `yarn tool flaws --help`

It seems like the `yarn content flaws` doesn't allow for file paths, but I've dropped the script change and updated the doc reference

**Review by peterbe — APPROVED** [review]

**Comment by peterbe** [comment]
> It seems like the `yarn content flaws` doesn't allow for file paths, but I've dropped the script change and updated the doc reference

I know @sideshowbarker did some interesting fixes to make those CLI commands more forgiving. Perhaps @fiji-flo can explain what happened to those PRs. It's the same as for `yarn content preview ...`

**Pull request merged**
