### PR TITLE
Mention API mocking in on the Service Workers page

### PR DESCRIPTION
**Pull request by kettanaito**
### Description

Mentions that Service Workers can be used for API mocking, and uses [Mock Service Worker](https://github.com/mswjs/msw) as a widely-used, approachable example of that.

### Motivation

Service Workers are incredible. I feel that it's essential to mention how well they may suit for API mocking, given all the advantages you get when using a Service Worker to intercept outgoing HTTP requests:

- No patches/stubs to native request-issuing modules like `window.fetch`;
- No alterations done to the system (i.e. request the same resources);
- Transparent network (requests intercepted by the worker are fully inspectable in the network);
- Out-of-the-box support for Fetch API, which includes streaming responses, serving binary data, etc. all while respecting the specification instead of using custom, library-specific abstractions. 

Mock Service Worker is an industry-proven choice for superb API mocking, and most of its benefits come from the unique usage of the Service Worker API for API mocking, which is worth mentioning on MDN for anybody who's learning about the workers and what they can do!

### Additional details

- [Mock Service Worker website](https://mswjs.io)
- [Mock Service Worker GitHub repository](https://github.com/mswjs/msw)

### Related issues and pull requests

This change does not relate to any issue.

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks for your PR!

I've discussed this change with other members of the maintenance team and we don't think we should link to the Mock Service Worker tool here. I think it is OK to include API mocking in the list, and it would be OK to have a [glossary](https://developer.mozilla.org/en-US/docs/Glossary) entry explaining in general terms what API mocking is. However, this isn't the right place to link to a specific tool, because this is service worker reference documentation, not tools documentation.

**Comment by kettanaito** [comment]
Thanks for looking into this, @wbamberg. We can drop the mention of any specific tools and just mention that you can use Service Workers for API mocking. If that sounds like something you'd be open to, I can open a pull request just for that.

**Comment by wbamberg** [comment]
Hey @kettanaito , yes I think that would be fine. I've reopened this PR in case you want to use it.

**Comment by kettanaito** [comment]
Thanks, @wbamberg! I've pushed the changes to remove the mention of specific technologies and instead simply list "API mocking" as something you can implement using the Service Worker API.

Let me know if this reads better now! I'd love to also illustrate how API mocking is achieved using the plain Service Worker API but we can do that in a follow-up pull request.

**Review by wbamberg — APPROVED** [review]
👍 thank you @kettanaito !

**Comment by kettanaito** [comment]
@wbamberg, my pleasure. I'd like for more people to learn what incredible API Service Workers are. 

Is there a place you'd recommend adding a quick example of how to use plain Service Workers for request interception and mocking? I recall something like this on MDN already but I couldn't find it.

**Pull request merged**
