### PR TITLE
Hg 8956 remove SVG screenshots

### LINKED ISSUE #8956: Issue with "Gradients in SVG": (screenshots missing in all examples? tested in chrome & firefox)
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients

#### What information was incorrect, unhelpful, or incomplete?
all the examples on this page have a left box that's labeled "screenshot."  but it's empty in chrome and firefox. 

#### Specific section or headline?

all examples

#### What did you expect to see?
if it's not needed, maybe we can not show the box?  if they are needed, the screenshots are missing?

#### Did you test this? If so, how?

Tried in chrome and firefox, don't see any screenshots. But can see the live examples. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/tutorial/gradients`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/tutorial/gradients/index.html
* Last commit: https://github.com/mdn/content/commit/45a7c78ec1b5fbe7aa9107059a15e9e2c142f834
* Document last modified: 2021-02-19T18:47:12.000Z

</details>

### PR DESCRIPTION
**Pull request by himanshugarg**
> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

Fixes #8956

> What was wrong/why is this fix needed? (quick summary only)

The screenshots were lost and they are not needed perhaps.

> Anything else that could help us review it

1. I have increased the heights a bit to remove the vscroll on wide screens
2. See https://github.com/mdn/content/pull/9160#pullrequestreview-761498820

### CODE REVIEW

**Comment by himanshugarg** [comment]
Can't tell why the check failed

**Review by wbamberg — APPROVED** [review]
👍 looks great, thank you @himanshugarg !

**Comment by wbamberg** [comment]
I don't know why CI fails, apparently because it thinks the PR changes system files, which it doesn't seem to. @himanshugarg , this PR does contain 11 commits though - maybe close this and start a new one from content/main with just this change? Sorry for the trouble :(.

**Comment by himanshugarg** [comment]
Thanks for the review. I have fixed the commit history. Let me know if I missed any other changes.

**Pull request merged**
