### PR TITLE
added alt attribute in image of Mozilla dinosaur

### LINKED ISSUE #12713: Image explaining the use of alt texts has no alt text
This image [here](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML) of the Mozilla red dinosaur illustrating how alt texts appear over images on hover has no alt text. 

image

Suggested alt text:

> Alt text tooltip reading "The Mozilla red dinosaur" hovering over the Mozilla red dinosaur.

### PR DESCRIPTION
**Pull request by Sanskar-khandelwal**
added an alt attribute in the image of the dinosaur.
fixes #12713

### CODE REVIEW

**Comment by teoli2003** [comment]
I'm not sure this is a pertinent change. The next sentence is:

> In this case, we are not using the `alt` attribute at all 

But with this change is no more the case!

I think we should close this PR and the associated issue.

**Comment by ericwbailey** [comment]
@teoli2003 I think there is a larger content issue here, in that using the `title` attribute is largely considered an antipattern. I think the content of this page, beyond the scope of this PR, needs to be updated to reflect that.

**Comment by Sanskar-khandelwal** [comment]
> I'm not sure this is a pertinent change. The next sentence is:
> 
> > In this case, we are not using the `alt` attribute at all
> 
> But with this change is no more the case!
> 
> I think we should close this PR and the associated issue.



> I'm not sure this is a pertinent change. The next sentence is:
> 
> > In this case, we are not using the `alt` attribute at all
> 
> But with this change is no more the case!
> 
> I think we should close this PR and the associated issue.

ohh  I got it! Thanks for helping mate

**Comment by Sanskar-khandelwal** [comment]
> But

OK sir Thanks

**Pull request closed without merging**
