### PR TITLE
Fix a spelling mistask

### PR DESCRIPTION
**Pull request by amanofuyu**
fix a spelling mistask

### CODE REVIEW

**Comment by pransh15** [comment]
Thanks for submitting a PR, but the current spelling is indeed, `progress`.

**Review by Josh-Cena — APPROVED** [review]
Thanks

@onkarruikar I'm a bit puzzled why this is not caught by the spell checker.

**Comment by OnkarRuikar** [comment]
@Josh-Cena Because the Cspell thinks it's a valid word:
```bash
fsh$ npx cspell trace "progess"
Word     F Dictionary           Dictionary Location
progess  - [flagWords]*         From Settings `flagWords`
progess  - [ignoreWords]*       From Settings `ignoreWords`
progess  - [suggestWords]*      From Settings `suggestWords`
progess  - [words]*             From Settings `words`
...
progess  - django*              node_modules/@cspell/dict-django/dict/django.txt
prog+ess * en_us*               node_modules/@cspell/dict-en_us/en_US.trie.gz        <=== Note
progess  - en-us-common-misspe* node_modules/@cspell/dict-en-common-misspellings/dict-en-us.yaml
...
```

**Comment by Josh-Cena** [comment]
Nice, I didn't know you can do that. And weird that `progess` gets allowed.

**Comment by OnkarRuikar** [comment]
The `prog+ess` in the trace means that we have `"allowCompoundWords": true` set and the prefix `prog` and suffix `ess` from the en_US dictionary make the `progess` word. We have to explicitly forbid the word using `!progess`. I'll do it in the upcoming weekly spell-check round.

**Comment by Josh-Cena** [comment]
Out of curiosity I wonder why they have it in the dictionary. And there's very possibly other uncaught typos like this.

**Comment by OnkarRuikar** [comment]
> Out of curiosity I wonder why they have it in the dictionary. And there's very possibly other uncaught typos like this.

Let us continue the discussion in https://github.com/mdn/content/pull/36004

**Pull request merged**
