### PR TITLE
Array map syntax fixes

### PR DESCRIPTION
**Pull request by hermaeusdev**
Minor consistency fixes and cleanup in Array.prototype.map syntax

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:

**Comment by Clavicus** [comment]
> Thanks a lot!
> 
> Looks good to me.
> 
> Congratulations upon your first merged commit here! Welcome aboard! 🎉

Oh wait I messed up, I just realized there was a reason the arrow function syntax didn't have thisArg is because it doesn't have its own `this`, my bad I wasn't thinking about that.

**Comment by teoli2003** [comment]
Can you open a follow-up PR?

**Comment by Clavicus** [comment]
I'll try, sorry, pretty new to PRs in general

**Comment by teoli2003** [comment]
(A follow-up PR is just a regular PR ;-) )

**Pull request merged**
