### PR TITLE
Fix line number references in CORS

### PR DESCRIPTION
**Pull request by falegh**
#### Summary
Fixes some line number references in CORS page

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by teoli2003** [comment]
Are you sure? If I count the lines, they are correct?

**Comment by falegh** [comment]
Hmm, I got confused in the first case because the `User-Agent:` spans two lines.

But then the paragraph that starts with "Lines 13 - 22 above are the response that the server returns" is not correct. I think it should be "Lines 12 - 21 above ...", or I miscounted again?

**Comment by teoli2003** [comment]
You are right for the second part: it should be 12-21. (Note that this was written when the line numbers were displayed next to the code. 

While technically correct, line numbers like this are not very practical.

Though, if you update your PR, for lines 12-21, I would accept it.

**Comment by falegh** [comment]
Hopefully I got it right this time

**Review by teoli2003 — APPROVED** [review]
Yes, thanks a lot!

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:

**Pull request merged**
