### PR TITLE
Added Programiz PRO to resources (content)

### PR DESCRIPTION
**Pull request by ashmitasth**
### Description

Added Programiz PRO to recommended resources (content > index.md) section

### Motivation

This commit introduces the Programiz PRO HTML course: A free beginner-friendly HTML course to build a strong foundation in creating and structuring web content.  This is a valuable resource as it helps beginners get all the necessary information for learning HTML.

### Additional details

https://programiz.pro/course/learn-html

**Disclaimer: I'm part of the Programiz team.**

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
Hi @ashmitasth! Thanks for the submission.

First, you need to make some changes to the markdown before we can accept this:

- The link doesn't work because there is a space between the closing square bracket and the opening parenthesis.
- You need to format this as a description list item, not an unordered list item. The link needs to go on one line, starting with `-`, and the description needs to go on the next line, starting with `- : `. Make sure the indentation of the lines matches the indentation of the existing lines.

Second, I worked through some of the HTML course. The content seems correct, and the environment is nice. My main question is around the cost of the platform - most of the other courses are locked until you pay for it. Are you intending to open up a few more of the courses for free access? On MDN, we don't tend to recommend paid products unless there is a significant amount of content available for free, so it is useful to any reader, regardless of their financial situation.

**Comment by bsmth** [comment]
Just a note that the author has failed to disclose their affiliation with Programiz, which is against the [external links policy](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#external_links).

**Comment by chrisdavidmills** [comment]
> Just a note that the author has failed to disclose their affiliation with Programiz, which is against the [external links policy](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#external_links).

Hrm...well, she does clearly state it on her GitHub profile.

**Comment by bsmth** [comment]
> > Just a note that the author has failed to disclose their affiliation with Programiz, which is against the [external links policy](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#external_links).
> 
> Hrm...well, she does clearly state it on her GitHub profile.

Right, I understood the guidelines to mean you should disclose it in your pull request, but this constitutes spam, I think:

* https://github.com/tayllan/awesome-algorithms/pull/157/files
* https://github.com/sdmg15/Best-websites-a-programmer-should-visit/pull/1930/files
* https://github.com/EbookFoundation/free-programming-books/pull/11239/files

I'm -1 on this change, unless there's really great merit in the resource

**Comment by ashmitasth** [comment]
Thanks for the review! I made changes to the link and format of the text.

I'm from the Programiz Team. I only wanted to share our helpful resource: the HTML course with your readers. It is completely free and accessible without payment. The rest of the courses have restricted content and are not fully free. However, we do have free features like Programiz Challenges and Programiz Playground.

**Comment by bsmth** [comment]
Thank you, Chris. @ashmitasth, I wish you success with your project, thanks for understanding.

**Comment by ashmitasth** [comment]
I get why my commits might have seemed a bit spammy. I was just trying to spread the word about our HTML course, which I really believe is a solid option for beginners. We’ve worked hard to make it top-notch and easy to follow, and it’s totally free—something we’re committed to keeping.
 
I appreciate your feedback and understand where you're coming from. No hard feelings at all. If you ever want to check it out, just let me know. Thanks!

**Pull request closed without merging**
