### PR TITLE
Make string building code consistent

### PR DESCRIPTION
**Pull request by chrisdavidmills**
Fixes https://github.com/mdn/content/issues/3158

Checklist — To help your pull request get merged faster, please do the following:

1. - [ ] Provide a summary of your changes — say what problem you are fixing, what files are changed, and what you've done. This doesn't need to be hugely detailed, as we can see exact changes in the "Files changed" tab.
1. - [ ] Provide a link to the issue(s) you are fixing, if appropriate, in the form "Fixes _url-of-issue_". GitHub will render this in the form "Fixes #1234", with the issue number linked to the issue. Doing this allows us to figure out what issues you are fixing, as well as helping to automate things (for example the issue will be closed once the PR that fixed it has been merged).
1. - [ ] Review the results of the automated checking we run on every PR and fix any problems reported (see the list of checks near the bottom of the PR page). If you need help, please ask in a comment!
1. - [ ] Link to any other resources that you think might be useful in reviewing your PR.

### CODE REVIEW

**Comment by wbamberg** [comment]
Is there a reason to avoid template literals here? It's in our standard to prefer them: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript#use_template_literals.

**Comment by chrisdavidmills** [comment]
Only really because it was quicker and easier to change one line rather than changing all instances in the article, plus the code examples that go with it ;-)

The learning area does need a massive overhaul at some point, to modernize all the JS we teach. At the moment, the strings article teaches old school concatenation at the forefront, but then mentions template literals as a mdoern option. We ought to just teach that by default.

But I've not got time for that at the moment.

**Comment by chrisdavidmills** [comment]
In fact, I'll write an RFC about it.

**Comment by wbamberg** [comment]
> In fact, I'll write an RFC about it.

Took the words right out of my mouth :)

**Review by wbamberg — APPROVED** [review]
OK, let's merge this now then. Thanks, Chris!

**Pull request merged**
