### PR TITLE
Update BCD paths for console (api.Console.* -> api.console.*)

### PR DESCRIPTION
**Pull request by foolip**
Follows https://github.com/mdn/browser-compat-data/pull/11534.

### CODE REVIEW

**Comment by foolip** [comment]
@teoli2003 this should be the last bit. Did you leave this out deliberate from previous PRs?

**Comment by teoli2003** [comment]
Only as the bcd still had the capital at that point. So no specific reason.

**Review by teoli2003 — APPROVED** [review]

**Comment by foolip** [comment]
Oops, I didn't intend for this to be merged yet, trying to coordinate the timing over in https://github.com/mdn/yari/pull/4225.

Should we revert, or let the tables be broken for a week?

**Comment by teoli2003** [comment]
I'm not worried here. But I don't know the policy: @Elchi3 ?

**Comment by Elchi3** [comment]
Would have been nice to coordinate this (especially when you land things just after the BCD train has left) but it is not that much of a big deal I would say.

**Comment by foolip** [comment]
As expected https://developer.mozilla.org/en-US/docs/Web/API/Console/log#browser_compatibility is broken now, but hopefully it will be fixed on Thursday or Friday then.

**Pull request merged**
