### PR TITLE
Footer and form elements modified

### PR DESCRIPTION
**Pull request by Mehrm0**
### Description
\<footer\> and \<form\> elements were modified.

### CODE REVIEW

**Comment by bsmth** [comment]
Hi @Mehrm0 - a lot of people receive notifications when there is a pull request made to this repository. If you would like to test out code changes, please [fork the repository](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository) and make changes there.

Thank you :)

**Comment by Mehrm0** [comment]
Sorry, I am a little confused, things are really complicated here. Actually I didn't know that I am doing things in the main branch.

**Comment by bsmth** [comment]
That's okay, there's some info on contributing on our [Getting Started](https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Getting_started) page and if you're stuck, feel free to get in touch on [one of our communication channels](https://developer.mozilla.org/en-US/docs/MDN/Community/Communication_channels).

Thanks :)

**Comment by Mehrm0** [comment]
Sorry, but I thought that you mentioned my previous pull requests. I don't understand what's wrong with this pull request. I modified two files and requested to be merged. Maye the title (=test) was misleading.
Regards.

**Pull request closed without merging**
