### PR TITLE
Fixing links in common questions

### LINKED ISSUE #1130: Issue with links in "Common questions"
Page with the problem: https://developer.mozilla.org/en-US/docs/Learn/Common_questions

Links on different questions work as anchor links and don't allow you to go to specific question pages.

### PR DESCRIPTION
**Pull request by rachelandrew**
Fixes #1130

The links contained in headings were being overwritten by whatever creates permalinks. I'll raise a separate issue for that. I've moved the links out of the headings. They weren't very obviously links as part of the heading anyway so perhaps this is a better approach.

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
I've had a look at this, tested the update locally. I did have a couple of thoughts immediately, such as "I don't see why the links have to be bolded", and "I think the links should be phrased in more of a CTA, e.g. See [LINK TO X] for more information."

Also, the link text should be in sentence case — there are quite a few rogue capitalized words in there.

But then I took a step back and started thinking that there's more of a fundamental problem here — this page is not in-keeping with standard MDN style for landing-type pages. The H3 headings are pretty pointless — they are all rendered with anchors, but they are not useful for navigation because you only have a small amount of text under each one, and noone would link to one of these fragments — they'd just link to the linked articles instead.

And they are not useful for accessibility because you have links with good link text available. The H3s are really just creating unneccessary noise, imo, and I think it'd be better to get rid of them, and then put the links and their description paragraphs inside description list structures instead, which is the standard way we usually structure lists of links on landing pages.

Thoughts?

**Comment by rachelandrew** [comment]
@chrisdavidmills yeah, I wasn't really sure what to do with it and so just copied the text from the headings to make a link that worked, as that seemed better than having links that didn't work at all. A definition list would work, I can recreate it like that if you want?

We should probably look for other places where this turning heading links into anchors has happened. I don't know how common this sort of use is.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills yeah, I wasn't really sure what to do with it and so just copied the text from the headings to make a link that worked, as that seemed better than having links that didn't work at all. A definition list would work, I can recreate it like that if you want?

That would be great, thanks!

> We should probably look for other places where this turning heading links into anchors has happened. I don't know how common this sort of use is.

I've not seen it in many places. https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web looks similar too...

I think this is something strange I ended up doing on a few learning area landing pages, for some unfathomable reason.

**Comment by rachelandrew** [comment]
I've made that change, it looks loads better.

Also lowercased all the instances of Web as per https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide#capitalization

**Review by chrisdavidmills — APPROVED** [review]
Yes, this looks great! Thanks @rachelandrew

**Pull request merged**
