### PR TITLE
rewrite the `print` examples

### PR DESCRIPTION
**Pull request by yin1999**
### Description

rewrite the `print` examples and use `{{EmbedLiveSample}}` macro instead of external link (so the live sample could be localized)

### CODE REVIEW

**Review by wbamberg — CHANGES_REQUESTED** [review]
Thanks for this PR, @yin1999 !

This works for me on Chrome but not Firefox (I get the `afterprint` event but `self.close()` does not work for me). However, the example is so hacky that I don't think we should include it. Our own docs for [`document.write()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/write) have a very strong warning against using it, which is very at odds with the line "you can use code like this" here.

Also, the hacks obscure the point of the example, which is relatively simple (close the window on `afterprint`).

I think it would be better, rather than implementing hacks to make this work as a live example, just to make this into a static example.

**Comment by yin1999** [comment]
Thank you @wbamberg. I've remove the livesample macro call and add a warning about the use of `document.write()`.

**Review by wbamberg — COMMENTED** [review]
Sorry to be slow reviewing this @yin1999 , and if my original review wasn't clear.

I think I meant to say, but wasn't very explicit, that the stuff we do with `document.write()` and so on is really a hack to get the example to work in the live sample framework. So if we make this a static example, we can make it a much simpler and better practice example. For example, we could just say something like:

> The following example will close the window after the user has printed its contents:
>
> ```js
> window.addEventListener("afterprint", () => self.close)
> ```

Does that make sense? Especially I don't think we should include hacky code in our pages, even if we then say "don't use this".

**Comment by yin1999** [comment]
Thanks @wbamberg. This does make sense. I've removed the code to make it work in the live sample framework.

**Review by wbamberg — APPROVED** [review]
👍 thank you for the fix, @yin1999 !

**Pull request merged**
