### PR TITLE
relnote(117): math-style, math-depth examples

### PR DESCRIPTION
**Pull request by bsmth**
Adds two examples for https://github.com/mdn/content/pull/28447

Feedback welcome

__Related issues and pull requests:__
- [x] Parent issue https://github.com/mdn/content/issues/28290
- [x] Relnote https://github.com/mdn/content/pull/28447

### CODE REVIEW

**Comment by dipikabh** [comment]
Thanks @bsmth! I believe Fred can check the technical accuracy of the examples.

I have only one comment about the "Examples" section on both the pages – can we add an H3 heading under "Examples"? This is as per the guideline in our templates (citing one example here: [Add a descriptive heading](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/CSS_property_page_template#add_a_descriptive_heading)).

**Comment by bsmth** [comment]
> I have only one comment about the "Examples" section on both the pages – can we add an H3 heading under "Examples"? This is as per the guideline in our templates (citing one example here: [Add a descriptive heading](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/CSS_property_page_template#add_a_descriptive_heading)).

Thank you! Done in https://github.com/mdn/content/pull/28454/commits/d5ee51ae245b4a0c1ecbccfe36dbf023bef348a5

**Review by dipikabh — APPROVED** [review]
Thank you, @bsmth! The rendered examples look good.
We can incorporate any feedback Fred might have in a subsequent PR.

(Perhaps we can get rid of the "HTML" and "CSS" headings because the langs are now getting rendered in the code block. Also, would be good to add some context in the examples, either at the beginning or in the "Result" section to explain what's happening and how using the property gives us the outcome we're looking for.)

**Comment by fred-wang** [comment]
Thanks @bsmth, the examples LGTM.

FYI `font-size: math` is actually the default on MathML element (see https://w3c.github.io/mathml-core/#user-agent-stylesheet) which maybe should be commented as a note. Also in practice, one would be to change the `math-depth` of a subformula, rather than the whole formula.

Note that `math-depth: auto-add` has no effect on the proposed example since the inherited math-style is normal (default value, but note that `math-style: compact` on the math element per the link above). Here is an alternative example (feel free to take/tweak it):

```
<p style="font-size: 2rem">
  <math style="font-size: math; math-style: compact"><!-- default per the UA stylesheet -->
    <mtext>0</mtext>
    <mrow style="math-style: normal">
      <mrow style="math-depth: auto-add">
        <mtext>0</mtext>
      </mrow>
    </mrow>
    <mrow style="math-depth: auto-add">
      <mtext>1</mtext>
    </mrow>
    <mrow style="math-depth: add(2)">
      <mtext>2</mtext>
      <mrow style="math-depth: add(-1)">
        <mtext>1</mtext>
      </mrow>
      <mrow style="math-depth: 0">
        <mtext>0</mtext>
      </mrow>
    </mrow>
  </math>
</p>
```

**Pull request merged**
