### PR TITLE
Dev branch

### PR DESCRIPTION
**Pull request by ericmoore123**
> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'
N/A

> What was wrong/why is this fix needed? (quick summary only)
Accessibility issue with <a href="https://developer.mozilla.org/en-US/docs/Web"> Web Landing Page </a> with links and lack of aria-labels. Screen readers can now get more insight into what the links lead to. 

> Anything else that could help us review it

### CODE REVIEW

**Comment by teoli2003** [comment]
I'm not sure this change is of any use for assistive technology. The text you put was the text of the link that is read by assistive technologies.

Can you elaborate? What does screen readers do before your changes, and after?

**Comment by ericmoore123** [comment]
> I'm not sure this change is of any use for assistive technology. The text you put was the text of the link that is read by assistive technologies.
> 
> 
> 
> Can you elaborate? What does screen readers do before your changes, and after?

The main reason I add the aria-label tag is to provide context as to what the link is used for instead of simply what the title of the link is. 

Perhaps adding more context onto the text that is currently within the label would provide a better solution. I.e. "Open web api's page". 

As the page currently stands, users reliant on screen readers have very little insight into what happens upon clicking a link. (New page, launch an online tool, etc.)

**Comment by teoli2003** [comment]
Per this [article](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA8.html):

> Per the Accessible Name and Description Computation and the HTML to Platform Accessibility APIs Implementation Guide, the aria-label text will override the text supplied within the link. As such the text supplied will be used instead of the link text by AT. Due to this it is recommended to start the text used in aria-label with the text used within the link. This will allow consistent communication between users. 

The change you propose contains the same text as the link. It has no effect.

**Comment by teoli2003** [comment]
In addition to my previous comment, the coming HTML to Markdown conversion would strip these attributes away.

**Pull request closed without merging**
