### PR TITLE
updated syntax

### PR DESCRIPTION
**Pull request by Abhiram-Gullapalli**
#### Related issues

Resolves issue #16662 

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by gullapalli9482** [comment]
Made the changes @wbamberg had to make the changes all over again! Could you review it whenever you are free?

**Review by Rumyra — APPROVED** [review]

**Comment by Rumyra** [comment]
Hi @gullapalli9482 - @wbamberg is out this week - but I've checked it over and this all looks great - thank you!

**Comment by Rumyra** [comment]
Hi @gullapalli9482 - @wbamberg is out this week - but I've checked it over and this all looks great - thank you!

**Comment by PrajwalBorkar** [comment]
@gullapalli9482 Please update the spreadsheet as soon as you make PR to avoid duplicate work.

**Comment by Abhiram-Gullapalli** [comment]
Yep just a bit busy at the moment with exams and stuff it'll be updated
tomorrow for sure. Sorry for the confusion.
Hope you understand 🙂

**Pull request merged**
