### PR TITLE
chore(CSS): Replace png images with SVG equivalents

### PR DESCRIPTION
**Pull request by bsmth**
### Description

This PR replaces `.png` images with SVG equivalents.

### Motivation

Repo maintenance & housekeeping - SVG can be diffed and are easier to maintain.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍 +1

**Comment by bsmth** [comment]
> Is this a policy? I very much like the idea of prefer-SVG-by-default for images.

Not yet, I'm upgrading these in parallel whenever I'm working on a doc with .png diagrams, but I would love to do some more in '24 with a bit more coordination. We could consider freezing new `.png` additions for diagrams while we do some conversions. Good topic for a discussion, I think.

**Comment by hamishwillee** [comment]
> Good topic for a discussion, I think.

Absolutely! If you create it, I'll join it.

**Comment by bsmth** [comment]
> > Good topic for a discussion, I think.
> 
> Absolutely! If you create it, I'll join it.

Thanks, @hamishwillee, put some thoughts here: https://github.com/orgs/mdn/discussions/631

Happy to see what you think!

**Pull request merged**
