### PR TITLE
docs: remove references of mozGetAsFile in htmlcanvaselement directory

### PR DESCRIPTION
**Pull request by dimitri-bourreau**
#### Summary
Removal of mozGetAsFile references.

#### Motivation
Reponse to issue #16152.

> Get rid of HTMLCanvasElement::mozGetAsFile - this was 'removed' (put behind a flag) in 74, it has now been deleted across desktop & mobile. We can delete this page https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/mozGetAsFile and also the reference here https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement#obsolete_methods

#### Related issues
#16152 

#### Metadata
- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by jpmedley — APPROVED** [review]

**Comment by cw118** [comment]
Hi @dimitri-bourreau, since the "Check redirects" test is failing, I was wondering if you used the `yarn content` tool to delete the page `Web/API/HTMLCanvasElement/mozGetAsFile`? (just using `git rm` won't "work properly")

Let me know if I can help in any way :)

**Comment by hamishwillee** [comment]
Hi @dimitri-bourreau 

Thanks for this. As @cw118 says, deleting a file is not necessarily as simple as just deleting the file in the file system. The recommended way to do this is described here: https://github.com/mdn/content#deleting-a-document

This will clean up redirects to the file you deleted. Sometimes you will also add a redirect yourself using https://github.com/mdn/content#redirecting-a-document but in this case there is nowhere reasonable to redirect too.

You will probably need to undo your delete commit and start again. If you want me to do this let me know - I have some other work to do for this for https://github.com/mdn/content/issues/16152

**Comment by dimitri-bourreau** [comment]
Hi!

You got it right, I did not use this tool!

Thank you for taking the time to explain, guide, and even let me correct the PR I made. I do appreciate it.
As I wish to gently contribute more and more, I believe your way of welcoming contributions is perfect and only gives motivation and capabilities.

I will undo my commit, do the removal properly, and ping you when it's done.
Thanks!

**Comment by dimitri-bourreau** [comment]
When doing `yarn content delete web/htmlcanvaselement/mozgetasfile` I get returned:

```bash
dimitri@iMac-de-Dimitri content % yarn content delete web/htmlcanvaselement/mozgetasfile  
yarn run v1.22.18
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/tool/cli.js delete web/htmlcanvaselement/mozgetasfile

error: document does not exists: /en-US/docs/web/htmlcanvaselement/mozgetasfile

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Sorry, but can you help me on this?

**Comment by teoli2003** [comment]
`yarn content delete Web/API/HTMLCanvasElement/mozGetAsFile --redirect Web/API/HTMLCanvasElement`

Maybe there is a better page to redirect it too, but I have not found it, so let's redirect it to the interface.

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by dimitri-bourreau** [comment]
Thanks again, and sorry, I've read the Readme way to fast.
I've learned the lesson for my next contributions. 👍

**Comment by teoli2003** [comment]
No worry, I did the same the first time 😄 That's why we have a review process.

**Comment by hamishwillee** [comment]
Yes, thanks @dimitri-bourreau !!!

**Pull request merged**
