### PR TITLE
Change `console.assert` summary to match API summary

### PR DESCRIPTION
**Pull request by DanKaplanSES**
### Description

Like `console.log(errorObj)`, `console.assert(condition, errorObj)` prints a stack trace. But `console log`'s summary doesn't mention this detail, nor does the API for `console.assert`. Therefore, it felt more consistent to remove it here.

### Motivation

See above

### Additional details

Modified page: https://developer.mozilla.org/en-US/docs/Web/API/console#instance_methods
console.assert page: https://developer.mozilla.org/en-US/docs/Web/API/console/assert_static
console.log page: https://developer.mozilla.org/en-US/docs/Web/API/console/log_static

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
The stack (in browsers) is printed by `assert` itself. However in Node `console.assert` doesn't print the stack.

**Comment by DanKaplanSES** [comment]
> The stack (in browsers) is printed by `assert` itself.

Thank you for pointing that out. To clarify, you are referring to when an `Error` object is passed in? Can you let me know if there's anything specific I should consider changing based on this information? Thanks again.

**Comment by Josh-Cena** [comment]
I'm not sure. At least consider the following:

image

No `Error` instances, still have stack trace.

**Comment by Josh-Cena** [comment]
Ah yes, mine was Chrome... I guess it's not consistent across browsers either 😄

**Comment by DanKaplanSES** [comment]
> Ah yes, mine was Chrome... I guess it's not consistent across browsers either 😄

Interesting... Would that go as a note in the compatibility table?

**Comment by Josh-Cena** [comment]
I don't know for sure. The console spec is messy and nothing is known for certain. I'll let others decide.

**Comment by wbamberg** [comment]
FWIW I think we should accept this PR whether or not we decide to update the BCD.

- the actual page for [assert()](https://developer.mozilla.org/en-US/docs/Web/API/console/assert_static) doesn't mention a stack trace
- [nor does the spec](https://console.spec.whatwg.org/#assert)

I know, console support is super-messy, but if we ever did want to address cross-platform divergences (rather than saying [as we currently do](https://developer.mozilla.org/en-US/docs/Web/API/console) that _"The specifics of how it works vary from browser to browser or server runtimes, but there is a de facto set of features that are typically provided."_) then that would be a separate thing from this PR.

**Comment by bsmth** [comment]
I'm just adding a +1 to what Will says, this LGTM for now and clearing up implementation docs is a bigger task. I'm not sure if BCD is the right place for it (maybe it is) but it would be nice to have a programmatic way to test and display this.

**Comment by wbamberg** [comment]
@Josh-Cena , are you OK to merge this, based on https://github.com/mdn/content/pull/30725#issuecomment-1965726083?

**Comment by Josh-Cena** [comment]
Yes, I have no opinions either way.

**Review by bsmth — APPROVED** [review]
Thanks, all - going ahead and merging 👍🏻

**Pull request merged**
