### PR TITLE
fix: Move Operators/new/target

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
LGTM!

**Comment by Elchi3** [comment]
What's the rationale for moving it? Is the dot problematic?
Does this PR make it a sub page or new? I think if it is now nested under Operators/new/target instead of say Operators/new-target, the sidebar will not pick up new.target anymore, right? Has this been tested?

**Comment by Elchi3** [comment]
Side note: We should also update the mdn_url in BCD to avoid a redirect.

**Comment by Elchi3** [comment]
Confirming this removes it from the sidebar and there is also a broken link now on http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Operators/#Left-hand-side_expressions

If for some reason the dot should be avoided, I would vote for this to be moved to `Operators/new-target` instead of `Operators/new/target`

**Comment by chrisdavidmills** [comment]
> Confirming this removes it from the sidebar and there is also a broken link now on http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Operators/#Left-hand-side_expressions
> 
> If for some reason the dot should be avoided, I would vote for this to be moved to `Operators/new-target` instead of `Operators/new/target`

Sure, sounds good to me. Are you OK to handle this @nschonni ? Sorry for being so hasty!

**Pull request merged**
