### PR TITLE
Point ESLint page to firefox source docs

### PR DESCRIPTION
**Pull request by Standard8**
All the information that is still relevant has been moved across to firefox source docs.

### CODE REVIEW

**Comment by nschonni** [comment]
Maybe `yarn content add-redirect` instead of leaving a stub. It looks like there are a few external redirects allowed to things like extensionworkshop and bugzilla already

**Comment by Standard8** [comment]
@nschonni I've just tried that, first I removed the existing page (to make the command happy), but then when running the remove I get:

```
% git rm files/en-us/mozilla/developer_guide/eslint/index.html
% yarn content add-redirect /en-US/docs/Mozilla/Developer_guide/ESLint https://firefox-source-docs.mozilla.org/code-quality/lint/index.html
yarn run v1.22.10
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/tool/cli.js add-redirect /en-US/docs/Mozilla/Developer_guide/ESLint https://firefox-source-docs.mozilla.org/code-quality/lint/index.html

error: Cannot access 'url' before initialization

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any idea what that means?

There is a firefox-source-docs redirect already in the _redirects file so I don't think that is the issue. The url is also valid. I've also tried putting the arguments in quotes.

**Comment by chrisdavidmills** [comment]
Hi @Standard8 ! Sorry for taking so long to look at this.

I suspected that the error might be because you removed the page that needs redirecting from, before trying the `add-redirect` comment. AFAIK, the "from" page still needs to be there.

I pulled down your PR branch, and tried running the following, which I believe should work:

```
yarn content add-redirect /en-US/docs/Mozilla/Developer_guide/ESLint https://firefox-source-docs.mozilla.org/code-quality/lint/index.html
```

But I got exactly the same error ;-|

@peterbe @escattone can you folks shed some light on why this might not be working? Do you have to do anything special to put an external redirect in place?

Thanks in advance.

**Comment by Standard8** [comment]
Just to clarify, when I try the command without removing the file first I get:

```
fe: From-URL resolves to a file (files/en-us/mozilla/developer_guide/eslint/index.html
```

**Comment by peterbe** [comment]
> Just to clarify, when I try the command without removing the file first I get:
> 
> ```
> fe: From-URL resolves to a file (files/en-us/mozilla/developer_guide/eslint/index.html
> ```

Yes, it seems like the old error you got was because of an old version of the CLI tool. 
And now it seems your `main` is up to date and you've run the `yarn install`. 

The error hopefully makes sense in itself. Right?

**Comment by Standard8** [comment]
> > Just to clarify, when I try the command without removing the file first I get:
> > ```
> > fe: From-URL resolves to a file (files/en-us/mozilla/developer_guide/eslint/index.html
> > ```
> 
> Yes, it seems like the old error you got was because of an old version of the CLI tool.
> And now it seems your `main` is up to date and you've run the `yarn install`.
> 
> The error hopefully makes sense in itself. Right?

Yes, but removing that file then gives me the error I originally quoted:

```
error: Cannot access 'url' before initialization
```

**Comment by peterbe** [comment]
> > > Just to clarify, when I try the command without removing the file first I get:
> > > ```
> > > fe: From-URL resolves to a file (files/en-us/mozilla/developer_guide/eslint/index.html
> > > ```
> > 
> > 
> > Yes, it seems like the old error you got was because of an old version of the CLI tool.
> > And now it seems your `main` is up to date and you've run the `yarn install`.
> > The error hopefully makes sense in itself. Right?
> 
> Yes, but removing that file then gives me the error I originally quoted:
> 
> ```
> error: Cannot access 'url' before initialization
> ```

Got it!
Yeah, that shouldn't happen. Lemme take care of that.

**Comment by Standard8** [comment]
@peterbe Thank you for fixing, I've just updated the PR.

Note that there's some additional redirect changes which the tool has done, I'm assuming they're expected.

**Comment by peterbe** [comment]
> Note that there's some additional redirect changes which the tool has done, I'm assuming they're expected.

Yeah, I think it looked through other redirects and "perfected" them. I.e. instead of redirecting to A to B, and B to C, it just makes it directly go A to C. 

@fiji-flo do you think it would be worthwhile NOT applying the redirect fixes when someone is using the `yarn content add-redirect ...` CLI? It's certainly a bit confusing to see a bunch of other unrelated lines suddenly change.

**Review by ghost — APPROVED** [review]

**Comment by Standard8** [comment]
Is there anything else that needs doing on this now, or can we get it landed?

**Review by chrisdavidmills — APPROVED** [review]
I've checked this out and tested it again locally, and the redirects look like they are working fine. I'm gonna go ahead and merge.

**Comment by Standard8** [comment]
Thank you.

**Pull request merged**
