### PR TITLE
Update remaining `rgba()`/`hsla()` occurences to use latest syntax

### PR DESCRIPTION
**Pull request by FormularSumo**
Following on from https://github.com/mdn/content/pull/31453 and https://github.com/mdn/content/pull/31497, this PR should finish updating legacy rgba and hsla syntax, closing https://github.com/mdn/content/issues/30844

I have left all Firefox releases as they were. I have also left https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles#firefox_panel_components_legacy as it was.

In _redirects lines 804 and 11674 redirect to [en-US/docs/Web/CSS/color_value#rgb()_and_rgba()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgb()_and_rgba()), however this heading doesn't exist in color_value. I thought maybe they should have instead redirected to [en-US/docs/Web/CSS/color_value/rgb](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb), but I'm not entirely sure so I haven't changed yet. If not, the heading part should probably be removed instead.

### CODE REVIEW

**Review by teoli2003 — CHANGES_REQUESTED** [review]
LGTM. But what is the change with the SVG file?

**Comment by FormularSumo** [comment]
The change to the svg file is the same as the other changes, updating a couple or rgb() uses to the more modern syntax. Git isn't very good at detecting differences in svg files I've found, it just gets confused and says everything has changed. I can undo the change if you like it doesn't really matter for what's effectively an image, I just thought I'd change it while doing everything else.

**Comment by teoli2003** [comment]
Ha! I understand: it is _inside_ the SVG. 

Thank you!

**Review by teoli2003 — APPROVED** [review]

**Comment by FormularSumo** [comment]
> In _redirects lines 804 and 11674 redirect to [en-US/docs/Web/CSS/color_value#rgb()_and_rgba()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgb()_and_rgba()), however this heading doesn't exist in color_value. I thought maybe they should have instead redirected to [en-US/docs/Web/CSS/color_value/rgb](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb), but I'm not entirely sure so I haven't changed yet. If not, the heading part should probably be removed instead.

@teoli2003 I completely forgot about this until now, but what did you make of the above - is it something that wants changing?

**Pull request merged**
