### PR TITLE
Reference for stage 3 is-usv-string

### PR DESCRIPTION
**Pull request by Josh-Cena**
### Description

https://github.com/mdn/content/issues/25737, not sure if fixes it

cc @Elchi3

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
LGTM! Thanks for writing this up so fast!
Should https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI link to these new methods for discoverability? 

I don't know enough about WebAssembly to propose any backlinks or updates in that area. (wasm seems to be a motivation for this)

**Review by zloirock — COMMENTED** [review]
You could add a link to `core-js` polyfills of those methods https://github.com/zloirock/core-js#well-formed-unicode-strings

**Comment by Josh-Cena** [comment]
Sounds good to me, although I doubt if many DOM methods will be able to return `DOMString`... We should definitely emphasize methods that only accept `USVString`.

**Comment by Elchi3** [comment]
> Not for this PR, but should we start using:
> 
> ```
> A [well-formed](/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/isWellFormed) string.
> ```
> 
> as the return value of methods/properties returning an IDL `USVString`. (instead of "A string.")
> 
> ?

I assume it would be correct to do that.
Maybe "well-formed string" should be a glossary page, though?

**Comment by teoli2003** [comment]
> Sounds good to me, although I doubt if many DOM methods will be able to return `DOMString`... We should definitely emphasize methods that only accept `USVString`.

Yes, only for USVStrings. There are not many of them mostly in API related to networking.

**Comment by Elchi3** [comment]
https://dontcallmedom.github.io/webdex/u.html#USVString%40%40%40%40interface

**Comment by Elchi3** [comment]
Merging here for now :)

**Pull request merged**
