### PR TITLE
fix: webextensions: change let to const, or remove assigning when unn…

### PR DESCRIPTION
**Pull request by rubiesonthesky**
…ecessary

#### Summary

Change let -> const where applicable. Remove assigning promise to variable.

If these changes are helpful, I can submit more.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by Rob--W** [comment]
This PR does a lot more than just converting let to const and removing assignments. It almost looks like an automatic code formatter was applied to format code within code blocks.

On `let` to `const` - let's not do that. `const` is a good way to show that a variable is supposed to be immutable, but in the examples we do not necessarily have to signal that. The presence of `const` can make it a little bit harder to modify a code example for one's own use.

On Removing assignment "when unnecessary":
There are two classes of code blocks here.
1. The first is the "syntax" block. IMO the current dummy variable names are barely useful because they don't show what the type or meaning of the return value, at least not more than what a method name says. Moreover, regular web API documentation does not include the return value either, and defers to the main text instead. So I am supportive of removing `let gettingText =` from the syntax.
2. The second class of code blocks are examples. In this case, simplicity is important to novice readers. Having a separate variable name can make it easier to read code. This example from your PR has the same result, but the original version is easier to scan:

```diff
- let gettingBadgeText = browser.action.getBadgeText({});
- gettingBadgeText.then(gotBadgeText);
+ browser.action.getBadgeText({}).then(gotBadgeText);
```

This one would be more readable due to the clear separation between method call and chained `.then`:

```js
browser.action.getBadgeText({})
  .then(gotBadgeText);
```

One potential issue with the above is that people may not easily recognize that `.then` is chaining to the code at the previous line.

In a similar vein, I recommend to keep the namespace + method name all on one single line. This example from your PR puts `browser.bookmarks` and `.create` on two lines. If someone where to use Ctrl-F `bookmarks.create` to find copy-pasteable examples, then they would not find this code snippet.
```diff
- let createBookmark = browser.bookmarks.create({
+ browser.bookmarks
+  .create({
+    title: "bookmarks.create() on MDN",
```

A way to solve that is to do something like this:
```js
browser.bookmarks.create(
  { ... }
).then(onCreated);
```

... but you can imagine that if the `{ ... }` spans multiple lines, that it may become a challenge to figure out where `).then(` is attached to. So in this case, a separate variable name can make it easier to read code by those who are not experienced in balancing parentheses.

**Comment by Josh-Cena** [comment]
@Rob--W FYI the code changes here are adhering to our new JS code guidelines: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript

**Review by Josh-Cena — COMMENTED** [review]
Overall LGTM. Wondering if you could revert the syntax box changes (except getting rid of the assignment)? The comments could be totally refactored in another commit and there's no need to format it right now.

**Comment by Rob--W** [comment]
> @Rob--W FYI the code changes here are adhering to our new JS code guidelines: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript

This PR makes multiple changes, and some of them are not explicitly covered by the writing guidelines. Prettier can help with consistently formatted code, but the result is not necessarily the best format for reference documentation. In particular, the case I mentioned above about the namespace being split may be an issue, and it may be more common in extension documentation because extension APIs are under nested namespaces.

To avoid inconsistencies or comprehensibility issues, I have started a discussion with my team. Once that discussion resolves, there should hopefully be more clarity on the desired direction.

Please do not merge yet until I (or another [module peer of the WebExtensions component](https://wiki.mozilla.org/Modules/All#Webextensions), or our technical writer (@rebloor)) have signed off on the changes.

**Pull request closed without merging**
