### PR TITLE
Add more ruby-position valid syntax examples

### PR DESCRIPTION
**Pull request by nt1m**
https://drafts.csswg.org/css-ruby/#rubypos

### CODE REVIEW

**Comment by Josh-Cena** [comment]
The note right below tells you that `inter-character` is unsupported and therefore not demonstrated or documented. Is the two-value syntax actually supported?

**Comment by nt1m** [comment]
@Josh-Cena Safari does actually implement it: https://searchfox.org/wubkat/rev/b36cbce69fddb7da33823f316bd8ead5bebee970/Source/WebCore/layout/formattingContexts/inline/ruby/RubyFormattingContext.cpp#592

(It also does work when used inside sites)

I actually opened an issue to fix the compat data: https://github.com/mdn/browser-compat-data/issues/23971

**Comment by nt1m** [comment]
Removed, thanks for pointing it out!

**Review by estelle — APPROVED** [review]
Thank you. Will encourage the BCD to get updatd ASAP.

Also, congratulations on your first merged MDN content PR. 
Welcome to the team!

**Pull request merged**
