### PR TITLE
Add description for :// within a URL structure

### LINKED ISSUE #1322: What is :// ?
In 
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#deeper_dive

what is `://`?

### PR DESCRIPTION
**Pull request by tannerdolby**
Fixes #1322 

Let's start with this and trim away extra text and/or refine things if needed. @hamishwillee

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
This looks pretty good to me. Approving.

**Comment by hamishwillee** [comment]
@tannerdolby Looks great thanks - absolutely closes the specific  issue.

Further to this "area" though, most docs (including, I believe, the spec) refer to scheme for the first part - ie this is the scheme, which may refer to a protocol. Do you think we should further modify like this?
image

**Comment by tannerdolby** [comment]
@hamishwillee Ok great! And your welcome.

You are correct. In the RFC spec, it refers to the `https` as the "scheme" which is essentially synonymous with "protocol". I only used protocol because thats what MDN already had in place. I originally had protocol (scheme) but opted for just protocol since that was the consistent usage elsewhere on the page.

Moreover, `https` is the scheme that tells the browser that the resource located at `www.example.com` will be served using the `https` protocol. 

If there is a resounding vote to add "scheme" usage then I definitely will. I'm in for it, but let me know in the coming days what the consensus is.

**Comment by hamishwillee** [comment]
@tannerdolby There is a resounding vote from me. If you could take that on would be very grateful. However I am equally happy to do it myself - just ping me back in that case.

**Comment by tannerdolby** [comment]
@hamishwillee Ok sounds good. I'm willing to take it on. I've submitted a PR (#1874) that updates the scheme (protocol) naming within the new description I recently added. I'm waiting to change the first paragraph "`http` is a scheme .." until the below `` is updated to reflect the Scheme (Protocol) usage.

The "Protocol" within the image I cannot change as I don't have access to that specific img asset to update it. You might have to take the reins for updating the `` for this update to be completed.

Screen Shot 2021-01-28 at 9 16 08 PM

**Pull request merged**
