### PR TITLE
Tag `example-bad` blocks with js-nolint

### PR DESCRIPTION
**Pull request by OnkarRuikar**
Adding to https://github.com/mdn/content/pull/19177

- Updating syntax code blocks with the new tag. Refer: https://github.com/mdn/yari/pull/7017

### CODE REVIEW

**Comment by OnkarRuikar** [comment]
We want to add `-nolint` only where Prettier changes the output.
I'll remove the cases where it's fine to run Prettier.

**Comment by wbamberg** [comment]
@OnkarRuikar , are you coming back to this?

**Comment by OnkarRuikar** [comment]
> @OnkarRuikar , are you coming back to this?

- I think it is better to handle this in(or after) the series https://github.com/mdn/content/pull/21230 along with rest of the stuff. Cos marking with `-nolint` first will prevent them from getting the basic Prettying (e.g. single quote to double quote). We can revisit this after the series completes.

Sadly the series is not getting much response so I haven't touched this. I have no idea how we've planned to get all JS prettified. ~3600 pages to go.

**Comment by Josh-Cena** [comment]
FWIW I don't really like this. I'd rather manually revert the "bad" fixes than to silence them, since loss of syntax highlighting and some basic DX features is a pretty big minus to me.

**Pull request closed without merging**
