### PR TITLE
Fix event listener callback example

### LINKED ISSUE #29132: Arrow function | Invocation context
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

### What specific section or headline is this issue about?

_No response_

### What information was incorrect, unhelpful, or incomplete?

class SomeClass {
  constructor() {
    this.name = "Something Good";
  }

  register() {
    const that = this; // Do we need const that = this since arrow functions inherit this value of the function that contains them?
    window.addEventListener("keydown", (e) => {
      that.someMethod(e);
    });
  }

  someMethod(e) {
    console.log(this.name);
    switch (e.keyCode) {
      case 5:
        // some code here…
        break;
      case 6:
        // some code here…
        break;
    }
  }
}

const myObject = new SomeClass();
myObject.register();

### What did you expect to see?

class SomeClass {
  constructor() {
    this.name = "Something Good";
  }

  register() {
    window.addEventListener("keydown", (e) => {
      this.someMethod(e);
    });
  }

  someMethod(e) {
    console.log(this.name);
    switch (e.keyCode) {
      case 5:
        // some code here…
        break;
      case 6:
        // some code here…
        break;
    }
  }
}

const myObject = new SomeClass();
myObject.register();

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/eventtarget/addeventlistener`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/eventtarget/addeventlistener/index.md
* Last commit: https://github.com/mdn/content/commit/3f6726b293a7ae1a428db4a983ebfd2826750ce5
* Document last modified: 2023-09-14T09:44:11.000Z

</details>

### PR DESCRIPTION
**Pull request by a-brcic**
Fix https://github.com/mdn/content/issues/29132

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
As I said in https://github.com/mdn/content/issues/29132, the code needs to be aligned with the description. The description says "invoking the method on an object that points to `this`". We need to use a normal function expression here, and add an arrow expression as another example.

**Comment by a-brcic** [comment]
Sorry, but I don't get it?
Only description I see regarding example that includes my change is:

> Another way of handling the reference to this is to pass to the EventListener a function that calls the method of the object that contains the fields that need to be accessed:

**Comment by a-brcic** [comment]
Anything?

**Comment by Josh-Cena** [comment]
Right. This description:

> Another way of handling the reference to this is to pass to the EventListener a function that calls the method of the object that contains the fields that need to be accessed:

Means "calling the method on an object that contains the field", which, in the original example:

```js
  register() {
    const that = this;
    window.addEventListener("keydown", function (e) {
      that.someMethod(e);
    });
  }
```

Means invoking the method on an object other than `this`, because `this` inside the callback is no longer the original `this`. However, when you use an arrow function, there isn't a new `this` value to begin with, and the description loses its point.

Worry not—I'll rewrite this section.

**Review by Josh-Cena — APPROVED** [review]
I've made small modifications to the previous examples and the description. Thanks for starting the work!

**Comment by a-brcic** [comment]
Wow, my first contribution to the open-source...ever.
Thank you.

**Pull request merged**
