### PR TITLE
replace non-existent @top-middle page margin box with @top-center

### PR DESCRIPTION
**Pull request by michaelficarra**
### Description

The correct name for this region is `@top-center`, not `@top-middle`.

### Motivation

This was an error.

### Additional details

https://drafts.csswg.org/css-page/#margin-box-def

### CODE REVIEW

**Comment by bsmth** [comment]
Thanks a lot for opening this one. Taking a look shortly 👀

**Comment by bsmth** [comment]
Well spotted, I think this is a copy-paste error, it's as follows:

```plain
                +-----------------------------+
                |          page-top           |
                +---+---------------------+---+
                |   |                     |   |
                |   |                     |   |
                |   |                     |   |
                |   |                     |   |
     Middle --> |   |     page area       |   |
                |   |                     |   |
                |   |                     |   |
                |   |                     |   |
                |   |                     |   |
                |   |                     |   |
                +---+---------------------+---+
                |         page-bottom         |
                +-----------------------------+
                              ↑
                            Center
```

So there's left and right "middle", top and bottom "center", and it looks like it's always been that way since these Page-margin boxes have been introduced.

**Review by bsmth — APPROVED** [review]
Thanks a lot. I'm fine with landing these corrections, but we should consider removing them from the example completely; according to https://github.com/mdn/content/pull/28697 these are not implemented anywhere.

Well done on your first PR here - welcome aboard!

**Comment by michaelficarra** [comment]
As mentioned in that issue, there is a polyfill that implements it, which I am using. The alternative for those users would be to read the spec directly, and I think this documentation is more accessible than that for users of polyfills for this standard.

**Comment by bsmth** [comment]
Oh very good, I missed this part:

>Suggesting the Paged.js polyfill in see also section because it actually implements most of these W3C specs and [provides way better printing experience](https://stackoverflow.com/a/70054545/15273968) than the browser default implementations.

Thanks for pointing it out.

**Pull request merged**
