### PR TITLE
Fix typo in `console.log` parameters

### PR DESCRIPTION
**Pull request by meduzen**
### Description

Fix typo in `console.log` parameters by replacing “substutition” by “substitution”.

### Motivation

Readability.

### CODE REVIEW

**Review by bsmth — DISMISSED** [review]
Nice catch! Unfortunately this is copy-pasted into multiple files:

```
grep -rio "substutition" ./files

./files/en-us/web/api/console/debug_static/index.md:substutition
./files/en-us/web/api/console/assert_static/index.md:substutition
./files/en-us/web/api/console/info_static/index.md:substutition
./files/en-us/web/api/console/error_static/index.md:substutition
./files/en-us/web/api/console/warn_static/index.md:substutition
```

Can we please get them all in this PR? Thank you!

**Review by estelle — APPROVED** [review]
Thanks! 🎉

**Comment by meduzen** [comment]
> Nice catch! Unfortunately this is copy-pasted into multiple files:
> 
> ```
> grep -rio "substutition" ./files
> 
> ./files/en-us/web/api/console/debug_static/index.md:substutition
> ./files/en-us/web/api/console/assert_static/index.md:substutition
> ./files/en-us/web/api/console/info_static/index.md:substutition
> ./files/en-us/web/api/console/error_static/index.md:substutition
> ./files/en-us/web/api/console/warn_static/index.md:substutition
> ```
> 
> Can we please get them all in this PR? Thank you!

Ha, so there were more! 😄 Done in b60f55e.

**Review by Josh-Cena — APPROVED** [review]
I'm rushing this fix because I made this typo and I don't want to see it stick in content for a few more days 😅 Thanks a lot!

**Pull request merged**
