### PR TITLE
another batch of mdn meta doc changes

### PR DESCRIPTION
**Pull request by chrisdavidmills**

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@peterbe the CLI is now failing because one of my images is not compressed enough. It says "Consider running again with '--save-compression' and run again to automatically save the newly compressed file."

How do I do this? What should we be telling people to avoid this?

Could we just get the build process to do this automatically?

**Comment by peterbe** [comment]
That's curious! How did you download the images in the first place?
If you used the "Fix fixable flaws" button, it should run through the compression automatically, thus making the error "moot". 
If you used the command line and it didn't first compress the images, as it downloads then, then we have a bug. 

But almost more importantly, we can "pause" and think up a way to document how to deal with this for the next person, who like you, runs into the error.

**Comment by chrisdavidmills** [comment]
> That's curious! How did you download the images in the first place?

The image was already available on the article when I came to edit it this time around, but when I originally created it I captured the image using the built-in macOS capture tool (Cmd + Shift + 4), and then optimized it using a free tool called Optimize Images.

> If you used the "Fix fixable flaws" button, it should run through the compression automatically, thus making the error "moot".

I've just checked it again in the local yarn environment, and it doesn't throw a flaw for this at all.

Interestingly enough (another bug), the image is repeated three time on the page, but it only displays in the first instance (you get the alt text shown for the other two). The code for the `` in the source is:

```
<img alt="This screenshot shows a vertical navigation menu for the OscillatorNode interface, with multiple sublists for methods and properties, as generated by the APIRef macro" src="apiref-links.png" style="border-style: solid; border-width: 1px; display: block; height: 384px; margin: 0px auto; width: 302px;">
```

In the rendered page, the `src` attribute is as follows for the first instance — `src="/en-US/docs/MDN/Contribute/Howto/Write_an_API_reference/apiref-links.png"`

But for the other two it is `src="apiref-links.png"`, hence they don't display.

the page in question is  `MDN/Contribute/Howto/Write_an_API_reference`

I've also noticed that all three instances of the image display correctly in the live version — https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Write_an_API_reference — so it is only a bug in the local test environment.

> If you used the command line and it didn't first compress the images, as it downloads then, then we have a bug.

Yup, looks like we have a bug.
 
> But almost more importantly, we can "pause" and think up a way to document how to deal with this for the next person, who like you, runs into the error.

Sounds good. I can add this to the all-new FAQ on the readme.

I will leave this one open for now in case it is useful for you to investigate it, and move on to the next few articles.

**Comment by peterbe** [comment]
@chrisdavidmills If you can just merge in the latest `main` into your branch and follow by running `yarn install`. Then you should have the latest and greatest from yari for doing file attachments and stuff. 

In particular, you can run `yarn filecheck path/to/your/new/image.png --save-compression` and that unblock you, right?

**Comment by chrisdavidmills** [comment]
@peterbe the plan worked! All checks have passed, and the compression tools works perfectly. Thanks for this Peter, you're amazing.

**Comment by chrisdavidmills** [comment]
@peterbe the only thought about the tool that I had was that currently it relies on you providing a path that is relative to where you are in the directory tree, so for example I was inside the `content` root, and had the enter the following:

```
yarn filecheck files/en-us/mdn/contribute/howto/write_an_api_reference/apiref-links.png --save-compression
```

It might be nice if it always expects a path relative to the locale directory, so it is consistent with the slugs that you enter for the move and delete commands, and the relative URLs to different pages in internal links, e.g.

```
yarn filecheck /en-us/mdn/contribute/howto/write_an_api_reference/apiref-links.png --save-compression
```

?

**Pull request merged**
