### PR TITLE
The count of the global attributes

### PR DESCRIPTION
**Pull request by ghost**
added length to a definition list

### CODE REVIEW

**Comment by rachelandrew** [comment]
Hi @mattiapontonio 

I don't understand this change, could you add some explanation as that would help reviewers. Thanks!

**Comment by mattiapontonio** [comment]
@rachelandrew i would count `dt` so the attributes in this list and provide this count to the reader.
Hope the count is correct, i counted `13`.
It's like the _minutes of reading_ but more accurate.

**Comment by rachelandrew** [comment]
That's probably not something we want to add, it doesn't add a lot of value and isn't consistent with the rest of the docs. 

Also a table with just headings wouldn't be a good way to represent that information.

cc: @chrisdavidmills

**Comment by mattiapontonio** [comment]
I need totals in general when I have to think about how much effort I put into both learning and analyzing things.

**Comment by mattiapontonio** [comment]
With respect, in my opinion, the only thing that scares the idea is that it is too mathematical and not very editorial and having to do it everywhere but it is not so and the total on a list is a value.

**Comment by mattiapontonio** [comment]
When I read the attributes of an html tag if I know the total of the globals I can think "ok the possibilities here are the attributes I am reading + 13". And so on.

**Comment by mattiapontonio** [comment]
@rachelandrew in this case You can suggest the deleting of all code rows. I don't commit probably but is more straight to the point.

**Comment by rachelandrew** [comment]
I don't think this is something we will want to add but I have already asked for a second opinion on the matter.

**Comment by chrisdavidmills** [comment]
Yeah, we're not adding this. It would be very hard to implement across the whole of MDN in a consistently useful way (someone else might read the lists a lot slower than you, or choose to read them in a different way; what does the 13 actually mean?) It would probably end up just confusing people..

**Comment by mattiapontonio** [comment]
> what does the 13 actually mean?

I counted `26` attributes in the prod Page but `13 dt` when i was editing the source and i chose `13` 🤷🏻‍♂️

**Pull request closed without merging**
