### PR TITLE
corrected a typo

### PR DESCRIPTION
**Pull request by YecineM**
A bad typo there, that changed the whole meaning

### CODE REVIEW

**Review by estelle — APPROVED** [review]
good catch. thank you!

**Comment by Josh-Cena** [comment]
The original wording is correct 😅 It means you don't have entirely different control flow for sync and async code, so that async code now looks exactly like sync code.

Before:

```js
doSomething().then((res) => ...)
```

Now:

```js
const res = await doSomething();
...
```

The latter looks exactly like sync code, which is the entire point here! The revised sentence doesn't make sense because they are not "as though they are asynchronous"—they are already asynchronous by every definition!

**Comment by YecineM** [comment]
I'm so sorry 😔
Thank you so much for clarifying.
Didn't intend to mess that up 🫣🫢

**Comment by YecineM** [comment]
On verifying though, it is indeed confusing, at least the way I understand it.
The paragraph does not at all say "so that async code now looks exactly like sync code", as you have generously objected,
but rather "behave as though they're synchronous".
It's really very different to say "look" versus "behave", so something is definitely confusing, or I am confused about the whole thing.
It goes on to say, "as though they're synchronous by suspending execution until the returned promise is fulfilled or rejected".
How does "suspending execution" make things synchronous ?
Anyway, maybe it's just a detail that doesn't matter.

**Comment by Josh-Cena** [comment]
It "behaves as though it's synchronous", because you call the function and get the value directly, instead of a promise. After you add the await, its behavior is exactly equivalent to a sync function.

**Comment by YecineM** [comment]
I see, it's kind of clear now. Since the await returns directly the fulfillment value rather than a promise, so it's more like synchronous programming.
That's cool.
I appreciate your help and your time.

**Pull request merged**
