### PR TITLE
fix: Typos with cSpell

### PR DESCRIPTION
**Pull request by nschonni**
Took a light pass through, but this can be split into smaller chunks to make it easier to review.
Built out a small dictionary for cSpell here https://gist.github.com/nschonni/543433be75df387b1c6830f80049fdf7 but it's not comprehensive

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]
Reviewed every single one 🥵 Looks great — really nice to see all these getting fixed

**Review by chrisdavidmills — APPROVED** [review]

**Comment by chrisdavidmills** [comment]
Just some conflicts to be fixed, then I think we can merge this.

**Comment by nschonni** [comment]
I rebased and threw in a few more. I did avoid the British spellings for a separate pass

**Comment by chrisdavidmills** [comment]
Nice, merged!

**Pull request merged**
