### PR TITLE
Clarify note about keyboard-activated click events

### PR DESCRIPTION
**Pull request by benignant**
### Description

Update the wording of the note to make it clear that it only refers to keyboard clicks.

### Related issues and pull requests

https://github.com/mdn/content/pull/35458

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks for the PR! A couple of things:

This is supposed to be about the third bullet only, right? Reading the preview page, that wasn't at all obvious to me (it was only reading the history of this bug that I understood it. Even indenting the note isn't going to help much, because it's in a new block, so it still won't obviously be glued to the third bullet. I think it would be better all round to not have a note here and add this as a new sentence to the bullet, like:

> * Any user interaction that is equivalent to a click occurs, such as pressing the <kbd>Space</kbd> key or <kbd>Enter</kbd> key while the element is focused. Note that in practice browsers don't fire the `click` event for custom controls (such as a `<div>` with `tabindex="0"`) when activated by keyboard. To check the reason behind this behavior, see this [Chromium issue](https://crbug.com/40776466).

However, the wording still talks about this as if it is a web compat issue (i.e. a de facto deviation from the spec) but this comment: https://issues.chromium.org/issues/40776466#comment18 suggests that the behavior is per spec. So could we try something like:

> * Any user interaction that is equivalent to a click occurs, such as pressing the <kbd>Space</kbd> key or <kbd>Enter</kbd> key while the element is focused. Note that this only applies for elements with a default key event handler, and therefore excludes elements such as `<div>` elements with `tabindex="0"`.

I don't love it but I also didn't like "custom controls" which I didn't really understand (makes me think of web components).

**Review by Josh-Cena — APPROVED** [review]
Thanks!

**Comment by Josh-Cena** [comment]
Oooops! I merged this before I see @wbamberg's comment.

**Comment by wbamberg** [comment]
No worries, @Josh-Cena :)

**Pull request merged**
