### PR TITLE
Method/attribute titles without parent scope

### PR DESCRIPTION
**Pull request by hamishwillee**
A whole bunch of methods and attributes were missing the parent scope - this adds it back.

@peterbe This might be a good case for a flaw check - ie if you're two levels under Web/API/xxx/yyy then yyy must have a period in the title.

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
Do we have agreement that we always want/need the object/interface names in the title?

**Comment by hamishwillee** [comment]
> Do we have agreement that we always want/need the object/interface names in the title?

@sideshowbarker These 83 or so are the only ones I found which do not have the parent names - the rest (several thousand?) have them. So I inferred it. To me it makes sense, in particular since search would show many hits for any remotely common interface name.

But either way, this fixes consistency, and if it should be otherwise that would be done as a post process.

**Comment by sideshowbarker** [comment]
> These 83 or so are the only ones I found which do not have the parent names - the rest (several thousand?) have them

ah OK — I hadn’t realized it was so few that lacked it

> But either way, this fixes consistency, and if it should be otherwise that would be done as a post process.

Yup, agreed

**Review by sideshowbarker — APPROVED** [review]

**Comment by hamishwillee** [comment]
FYI though there are a few that "feel" like they should be in a namespace but which are not - specifically the MS extensions

msCaching
msCachingEnabled
msCapsLockWarningOff
msFirstPaint
msGetPropertyEnabled
msGetRegionContent
msGraphicsTrustStatus
msIsBoxed
msPlayToDisabled
msPlayToPreferredSourceUri
msPlayToPrimary
msPlayToSource
msPutPropertyEnabled
msRealTime
msRegionOverflow
msSetMediaProtectionManager
msWriteProfilerMark
mssitemodejumplistitemremoved event
msthumbnailclick event

**Comment by peterbe** [comment]
> @peterbe This might be a good case for a flaw check - ie if you're two levels under Web/API/xxx/yyy then yyy must have a period in the title.

I'm doubtful of this because it's not a perfect rule. There could be exceptions and it's hard to avoid a flaw then. 
Or, perhaps I'm misinterpreting your latest comment here about all those `ms*` titles.

**Comment by hamishwillee** [comment]
>> @peterbe This might be a good case for a flaw check - ie if you're two levels under Web/API/xxx/yyy then yyy must have a period in the title.

> I'm doubtful of this because it's not a perfect rule. There could be exceptions and it's hard to avoid a flaw then.
Or, perhaps I'm misinterpreting your latest comment here about all those ms* titles.

The ms* titles are fine with this rule. BUT you're quite right - I don't "know" whether this rule is reliable. Just raising it as a possibility.

**Comment by peterbe** [comment]
> I don't "know" whether this rule is reliable. Just raising it as a possibility - my gut feeling is that it would be very easy for this to have exceptions.

Now that I have your attention... :)
The flaws are supposed to be very "Definitely wrong" or "Definitely NOT wrong". But the PR Review Companion can be our chance to do so much more. At the moment, it posts Preview URLs, lists flaws, and lists external link URLs. 
But if you can think of other powerful "warnings" we should include, we can. The code to add another warning is quite easy to extend actually. It's just more Python code to add to https://github.com/mdn/yari/blob/f445c1afd760dba79a26c3e2da70de3bbd82ab15/deployer/src/deployer/main.py#L238-L251

One thing that's been brought up before is that it could post comments if you touch files that in a translated locale we don't support. E.g. Spanish which we still publish but don't have CODEOWNERS for. 

So if you can think of a concise and simple way to express your business logic, all you have to do is write a Python function that yields a string of Markdown text and we can take a look at it. 

What do you think?

**Comment by hamishwillee** [comment]
@peterbe Re  https://github.com/mdn/content/pull/4024#issuecomment-819520245 You have my attention :-)

> What do you think?

I will keep this in mind for future, because I think it may end up being very useful.

With respect to this case, I don't know. My first thought was based on this:
```
title: Navigator.msSaveBlob
slug: Web/API/Navigator/msSaveBlob
```
Then a rule might be "for docs under Web/API, warning if the title is not the full slug below API/, with the "/" turned to a period (i.e. `Web/API/Navigator/msSaveBlob >  Navigator/msSaveBlob > Navigator.msSaveBlob == title`

But then I realised that while this probably works for all the API entities, we have cases that aren't entitites.
```
title: Writing WebSocket servers
slug: Web/API/WebSockets_API/Writing_WebSocket_servers
```

Since there is nothing to identify an actual API item, I don't see how this could work (well, adding exception lists etc, but at that point more work than it is worth).

**Comment by peterbe** [comment]
So perhaps not a slam-dunk in terms of building it. Yet. 

But I like the spirit of this discussion! ...and the notion that we can use the Review companion to hack up arbitrary useful "soft warnings" can are sufficiently loud but don't get in the way of merging the PR.

**Pull request merged**
