### PR TITLE
Pagemacro: include rather than transclude EffectTiming properties

### PR DESCRIPTION
**Pull request by hamishwillee**
This is part of fixing #3196 - replaces a page inclusion macro of the [EffectTiming](https://developer.mozilla.org/en-US/docs/Web/API/EffectTiming) dictionary properties into the two places it is used: [Element.animate()](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate), [KeyframeEffect()](https://developer.mozilla.org/en-US/docs/Web/API/KeyframeEffect)

I would like to update further, perhaps as a post process. To help with that, answers to the following would be great.
1. There is also `KeyframeEffectReadOnly()` that redirects to [KeyframeEffect()](https://developer.mozilla.org/en-US/docs/Web/API/KeyframeEffect) and a `AnimationEffectReadOnly` which we don't document. I can't see in spec but they do appear in https://docs1.w3cub.com/haxe~javascript/html/animationeffectreadonly/ . Is it "valid" or are these things that no longer really exist?
2. The [EffectTiming](https://developer.mozilla.org/en-US/docs/Web/API/EffectTiming#properties) dictionary should be removed altogether but I'm not quite sure how to deal with it:
   - The properties have sub-docs which I presume I can pull in most of. That would be painful but is doable.
   - What concerns me is that the thing has its own BCD https://developer.mozilla.org/en-US/docs/Web/API/EffectTiming#properties that is not included in the `Element.animate()` compatibility. I presume the action here is to update that with each of these options?

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Not merging, because I don’t have answers to the questions in the issue description…

**Comment by hamishwillee** [comment]
Thanks!
@Elchi3 Can you help with the questions in the description? (or advise on who might)?

**Comment by teoli2003** [comment]
To answer the 2nd question, I think `EffectTiming` may be one of these rare cases (the only other one I know being `RTCConfiguration`) where we want to have a separate page for a dictionary. They are more like interfaces without methods/properties (and unnamed for the Web dev).

**Comment by Ryuno-Ki** [comment]
By now, a wild merge conflict appeared.

**Comment by sideshowbarker** [comment]
I resolved the merge conflicts.

**Comment by hamishwillee** [comment]
Thanks. I should have merged as is, but was still hoping for response from Florian. Better in than out. I'll think some more on this. 
And cheers for your comment @teoli2003 !!!

**Comment by Elchi3** [comment]
Sorry, I missed this in all the notifications. It looks good to me. 

I think whether or not to consolidate EffectTiming under some constructors and not as a dictionary on its own is mostly best answered in BCD. Meaning that if we think we can make sensible structures there, the separate dictionary pages might not be needed. But this can be a follow-up. Thanks for getting rid of the page macro already.

https://github.com/mdn/browser-compat-data/issues/7287 and https://github.com/mdn/browser-compat-data/issues/6810 are related.

**Pull request merged**
