### PR TITLE
Tag syntax code blocks with `js-nolint`, part 1

### PR DESCRIPTION
**Pull request by OnkarRuikar**
Updating syntax code blocks with the new tag. Refer: https://github.com/mdn/yari/pull/7017

For more variety for testing let me know which files we need to add to the PR.
***
Edit: The yari PR got merged. The PR series is good to go.

cc:/ @teoli2003, @Josh-Cena

### CODE REVIEW

**Comment by teoli2003** [comment]
We are still thinking if the _naming_ jssyntax is good or not. I have an Action Item to think about it and discuss it, but had no time to get to it today. That's why I'm holding this PR.

**Review by Elchi3 — COMMENTED** [review]
The yari PR was merged. Has a decision been made?

**Comment by teoli2003** [comment]
Yes, we want to change the name from `jssyntax` to `jsnolint`. But I need to create the PR and check for the consensus (that I believed we had before already).

**Comment by Elchi3** [comment]
Marking as draft then. This isn't ready yet.

**Comment by OnkarRuikar** [comment]
The moment I used `jssyntax`, I immediately got response, "That is for `## Syntax` sections only!"

From documenters' perspective `js nolint` makes more sense as we want this to avoid linter. And it can be used with any code, not just syntax sections.

> We can have other nolint languages in the future, which may selectively turn off other checks.

Are we going to have `csssyntax` and `htmlsyntax` in that case?
Where as `nolint` can go with any language. e.g. ```` ```js nolint ````, ```` ```css nolint ````, ```` ```html nolint ```` etc.

***

For `js nolint`
**Pros:**
- can mark any JS code block `nolint`, and not just blocks under `## Syntax` sections
- for future, works with other languages as well e.g. ```` ```css nolint ````, ```` ```html nolint ```` etc.
- we can start JS linting the repo right away by marking troublesome blocks with `nolint` and fix them gradually
- no modifications required in yari side (this is not an issue)

**Cons**
- requires forking the parser
- not semantic
- may lead to non strict compliance, as people will use it to save time and no one will look at the `nolint` blocks later


***
`jssyntax` and `jsnolint` are similar.

**Comment by Josh-Cena** [comment]
The reason I like `js nolint` is because syntax highlighting is preserved in my editor. Syntax highlighting tremendously reduces the cognitive load to mentally parse the source code.

**Comment by teoli2003** [comment]
I've opened #7017 for the change. Please mark your approval there so that we can double-check we have a consensus.

Thank you for your patience.

**Review by teoli2003 — APPROVED** [review]
Let's merge this! We'll see in a few days how it goes. If all looks fine, we'll do this on a large scale.

**Review by teoli2003 — APPROVED** [review]

**Comment by teoli2003** [comment]
Is it only me, or did Prism stopped applying JS syntax colors on the files here?

**Comment by Josh-Cena** [comment]
Prism, or GitHub? I see the right highlighting on the preview site.

image

**Comment by teoli2003** [comment]
It works on all, but the one I checked: https://pr19177.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

And this is caused by `js-nolints` instead of `js-nolint`, that I missed when scanning the file.

Creating a follow-up PR.

**Comment by OnkarRuikar** [comment]
>  or GitHub?

We may face this issue with other tools as well. That is why we need ```` ```js nolint````.

Should we start rolling out batches? What size?

**Pull request merged**
