### PR TITLE
Javascript conditionals - add bad example

### LINKED ISSUE #14017: Mark deprecated/unrecommended differently
It would improve the readability if deprecated/unrecommended/poor-practice are marked differently..

Example:
https://developer.allizom.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals

image

Phrasing it differently, would also emphasis the point e.g.

 "While the code is valid, using it is not recommended ....."

### PR DESCRIPTION
**Pull request by hamishwillee**
Fixes #14017 - mark example as bad

### CODE REVIEW

**Comment by wbamberg** [comment]
These are I think intentionally not marked up as JS because they are pseudocode, not JS.

You can still use `example-bad`, but I think if we do that it would be less surprising to readers if we put the text that says this isn't recommended _before_ the code sample, not after it.

**Comment by hamishwillee** [comment]
Thanks @wbamberg . Good point, fixed that.

**Review by wbamberg — APPROVED** [review]
👍 thanks Hamish! Actually I think the pseudocode here is a bit confusing, and it might be better to use real JS. But that's for another PR (it would probably mean updating other parts of the page too, to be coherent).

**Comment by hamishwillee** [comment]
> Actually I think the pseudocode here is a bit confusing, and it might be better to use real JS. But that's for another PR (it would probably mean updating other parts of the page too, to be coherent).

Yes. I thought the same, but a problem for another day. Often the fixes I do follow the 80/20 rule - best bang for buck but not necessarily the best fix that could be done.

**Comment by cmsouzaac** [comment]
Obrigado

**Pull request merged**
