### PR TITLE
Remove CanvasRenderingContext2d method scrollPathIntoView

### LINKED ISSUE #34845: Remove CanvasRenderingContext2d scrollPathIntoView
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/scrollPathIntoView

### What specific section or headline is this issue about?

Canvas scrollPathIntoView

### What information was incorrect, unhelpful, or incomplete?

I'm removing the feature from the spec (agreed by the editors) and no browser has ever shipped it. So all the content needs to be removed. I'll will try to do it this week if nobody beats me.

### What did you expect to see?

The feature should not exist.

### Do you have any supporting links, references, or citations?

https://github.com/whatwg/html/issues/8216

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/scrollpathintoview`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/scrollPathIntoView
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/scrollpathintoview/index.md
* Last commit: https://github.com/mdn/content/commit/1f216a70d94c3901c5767e6108a29daa48edc070
* Document last modified: 2023-04-07T06:13:50.000Z

</details>

### PR DESCRIPTION
**Pull request by schenney-chromium**
### Description

Remove the content around the CanvasRenderingContext2d method scrollPathIntoView.

### Motivation

The CanvasRenderingContext2d method scrollPathIntoView was only ever implemented behind a flag in Chromium. With no developer interest or other implementations in almost 10 years, it is being removed from the spec. There
should be no documentation that still refers to the method.

### Additional details

https://github.com/whatwg/html/issues/8216
https://github.com/whatwg/html/pull/10482

### Related issues and pull requests

Fixes #34845

### CODE REVIEW

**Comment by bsmth** [comment]
Thank you! Taking a look shortly

**Review by bsmth — APPROVED** [review]
Looks good to me, thank you!

**Comment by schenney-chromium** [comment]
Thanks for the info about yarn. That's very helpful.

I may also dive in to add some more content about the custom highlight API and associated features, given I'm trying to finish shipping that in Chromium.

**Comment by bsmth** [comment]
You're very welcome, thank you for the housekeeping 🙏🏻 

>I may also dive in to add some more content about the custom highlight API and associated features, given I'm trying to finish shipping that in Chromium.

Super, looking forward to it!

**Pull request merged**
