### PR TITLE
Fixed error in compare function of sort() behavior

### PR DESCRIPTION
**Pull request by karimmakhloufi**
> What was wrong/why is this fix needed? (quick summary only)

Correct me if I'm wrong but I think the description of the effect of the return value is wrong and this is the correct description of the compareFunction behaviour.

> Issue number (if there is an associated issue)

> Anything else that could help us review it

The french version seams to be correct: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

### CODE REVIEW

**Comment by Elchi3** [comment]
@hamishwillee you've touched this in https://github.com/mdn/content/pull/5224 (see also the related issue in https://github.com/mdn/content/issues/2769). Can you comment on this PR?

If I understand things correctly from the issue and your prior PR then this PR isn't correct.

**Comment by karimmakhloufi** [comment]
I did a little code example to illustrate what I think is wrong in the new wording of the documentation:

```
const numbers = [{ number: 1 }, { number: 3 }, { number: 2 }];

console.log(
  numbers.sort((a, b) => {
    if (a.number < b.number) {
      return 0;
    }
    return 1;
  })
);
```

[You can test it here](https://replit.com/@KarimMakhloufi3/sort-function)

Am I missing something or is it an error in the documentation ?

**Comment by mistval** [comment]
I believe this change is correct and should be accepted. The current wording seems like it may be describing Firefox-specific implementation details.

Reproducing karimmakhloufi's example from above:

```js
const numbers = [{ number: 1 }, { number: 3 }, { number: 2 }];

console.log(
  numbers.sort((a, b) => {
    if (a.number < b.number) {
      return 0;
    }
    return 1;
  })
);
```

This returns different results in Firefox and Chrome.

In Firefox it results in correct sorting: `[ { number: 1 }, { number: 2 }, { number: 3 } ]`. In Chrome it results in incorrect sorting: `[[ { number: 1 }, { number: 3 }, { number: 2 } ]`.

In Firefox, from my testing, `a` is always an element from a lower index in the array than `b`, but this is *not the case* in Chrome. Here's an example:

```js
console.log(
  'Sorted array: ' + [2,1].sort((a, b) => {
    console.log(`a: ${a}`);
    console.log(`b: ${b}`);
    const compareResult = a - b;
    console.log(`Compare Result: ${compareResult}`);
    return compareResult;
  })
)
```

In Firefox, the console output is:

```
a: 2
b: 1
Compare Result: 1
Sorted array: 1,2
```

In Chrome, the console output is:

```
a: 1
b: 2
Compare Result: -1
Sorted array: 1,2
```

The current documentation in question states: `If compareFunction(a, b) returns a value ≤ 0, leave a and b in the same order. `

But from the example above we can see that this is NOT true in Chrome. The compare result is ≤ 0, and yet the order of a and b were switched ([2,1] was sorted to [1,2]).

The [ECMAScript standard](https://262.ecma-international.org/10.0/#sec-array.prototype.sort) says `If comparefn is not undefined, it should be a function that accepts two arguments x and y and returns a negative value if x < y, zero if x = y, or a positive value if x > y.`

I don't see anything in the standard to support the current wording.

**Comment by hax** [comment]
@karimmakhloufi  
As I understand, the words is describing how engine deal with the result of `compareFunction(a, b)`, not how programmers should implement `compareFunction`. Your test codes are not correct, u should always return `1`, `-1`, `0` for gt, lt, eq. So I think this PR is unnecessary .

**Comment by bakkot** [comment]
This PR is an improvement, though I note that `compareFunction`'s result is only meaningful when the it is consistent. The examples [above](https://github.com/mdn/content/pull/6255#issuecomment-873904312) involve inconsistent comparison functions, so the spec doesn't say anything about them.

(See [the specification](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.sort) for the requirements for a comparison function to be consistent. Notably, `compareFunction(a, b)` must be zero if and only if `compareFunction(b, a)` is zero, which is violated by the examples in this thread.)

**Comment by karimmakhloufi** [comment]
@hax I agree with you, "leave a and b in the same order" is not the best wording. What do you think of :

 <li>If <code>compareFunction(a, b)</code> returns 0, <code>a</code> and <code>b</code> are considered equal.
 
 ?

**Comment by karimmakhloufi** [comment]
Closing this PR as I openened a new one here: https://github.com/mdn/content/pull/8006

**Pull request closed without merging**
