### PR TITLE
Fix Object static methods' behavior for non-object argument

### PR DESCRIPTION
**Pull request by Ahmed-Hakeem**
##### Replacing "Coercion" with "argument" :
According to specs, there is no coercion happens for the non-object argument it just returns it in es2015 or throws an error in es5

##### Removing "a non-object argument will be treated as if it was a non-extensible ordinary object, return it":
Also, according to specs, no special behavior happens to a non-extensible object.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Thanks! We have the same problem with `isExtensible`, `isFrozen`, `isSealed`. Could you update those as well?

**Comment by Ahmed-Hakeem** [comment]
> Thanks! We have the same problem with `isExtensible`, `isFrozen`, `isSealed`. Could you update those as well?

Sure :)

**Review by Josh-Cena — APPROVED** [review]
Thank you

**Comment by Ahmed-Hakeem** [comment]
> Thank you

Always a pleasure :)

**Pull request merged**
