### PR TITLE
index.md

### PR DESCRIPTION
**Pull request by ghost**
sentence does not make any sense "which axis is which is important".

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:

**Comment by wbamberg** [comment]
This change is wrong: the original was correct (but written in a not-very-easy-to-understand way).

> Understanding which axis is which is important when we start to look at aligning and justifying flex items; flexbox features properties that align and justify content along one axis or the other.

...wants to say: "it is important to understand which axis is the cross axis and which axis is the main axis"

We might prefer to say:

"When we start to look at aligning and justifying flex items, it will be important to understand which axis is the cross axis and which axis is the main axis."

**Comment by teoli2003** [comment]
Ha!   _Which axis is which_ yes it makes sense now. I agree it wasn't clear when I read this.

Do you want to do the follow-up PR?

**Comment by wbamberg** [comment]
Sure, I can have a go :).

**Comment by teoli2003** [comment]
I'll review it tomorrow morning (time to go to bed for me)

**Pull request merged**
