### PR TITLE
Make it clearer (improve grammar) in Learn area

### LINKED ISSUE #6399: Issue with "Responsive images": (unintelligible sentence due to wrong grammar)
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

#### What information was incorrect, unhelpful, or incomplete?
Ideally, you would have multiple resolutions available and serve the appropriate size depending upon the device accessing the data on the website.

#### Specific section or headline?
Why responsive images?

#### What did you expect to see?
This is a compound sentence. The first clause is, "you would have multiple resolutions available". Supposing the same subject and auxiliary verb is being used, the second clause would be, "you would serve the appropriate size depending upon the device accessing the data on the website."

This doesn't make sense. And it wouldn't make sense if we didn't use the same subject and auxiliary verb, because there isn't any alternative.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.html
* Last commit: https://github.com/mdn/content/commit/be3c3e06d1d9b59d2ad38a3a3e9eb59fbaa9c6f1
* Document last modified: 2021-06-10T18:50:18.000Z

</details>

### PR DESCRIPTION
**Pull request by teoli2003**
Fix #6399

### CODE REVIEW

**Comment by sideshowbarker** [comment]
@ConsciousClay Does the wording in this change resolve the problem?

**Comment by ConsciousClay** [comment]
Hi,

Thanks for asking. After learning more about web development and after
rereading the passage in question, I find that the original phrasing was in
fact correct grammatically. My opinion though is that the phrasing can be
made clearer for beginners who are unfamiliar with such newly coined terms
as that of "*serve*". This term, though it has well over a dozen older
meanings, is used on MDN in the context of delivering web content to users
via a web server. I think for most people coming here looking for a
beginner's tutorial, this phrasing will be confusing. On the other hand,
the new phrasing is even worse to be honest:

Ideally, multiple resolutions would be available and *the image with the
> appropriate size depending upon the device accessing the data on the
> website* would be served.
>
 Here, the predicate of the subject "*the image*" doesn't come until the
very end of the clause. What's more, the verb "*depending*" isn't very
fitting.

Here's my suggestion:

"Ideally, multiple resolutions would be made available to the user’s web
browser. The browser could then determine the optimal resolution to load
based on the screen size of the user’s device."

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
> "Ideally, multiple resolutions would be made available to the user’s web browser. The browser could then determine the optimal resolution to load based on the screen size of the user’s device."

Thanks — @teoli2003 landed it with that wording

**Comment by ConsciousClay** [comment]
Who is @teoli2003?

It was my wording. 🤔

**Comment by ConsciousClay** [comment]
> > "Ideally, multiple resolutions would be made available to the user’s web browser. The browser could then determine the optimal resolution to load based on the screen size of the user’s device."
> 
> Thanks — @teoli2003 landed it with that wording

Who is @teoli2003?

It was my wording.

**Comment by sideshowbarker** [comment]
Sorry for my confused description — I should rather have written something like, *“@teoli2003 updated the patch to incorporate your suggested wording”*

@teoli2003 is Jean-Yves Perrier, who put together the patch in this pull request

**Comment by ConsciousClay** [comment]
Woohoo!

You guys should hire me.

😜

**Comment by sideshowbarker** [comment]
> You guys should hire me.

You should write up patches and open pull requests too — I reckon that you’d be better at it than I am at least 😋

**Comment by ConsciousClay** [comment]
Yes, you're the second person to inform me about the pull requests. I'll
give it a try!

But if your servers explode don't go pointing your fingers at me.

**Pull request merged**
