### PR TITLE
Remove polyfill for Array.map()

### PR DESCRIPTION
**Pull request by AnilSeervi**
#### Summary

Fix link to es5 spec in `Array.map()` example

_https://es5.github.com/#x9.11_ -> _https://es5.github.io/#x9.11_
#### Motivation

Open-source
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by sideshowbarker — CHANGES_REQUESTED** [review]
The entire Polyfill section should be removed instead. (I tried myself pushing a change to the branch to remove it, but it seems you must have unchecked the box that makes the branch writable by maintainers).

**Comment by AnilSeervi** [comment]
Does that mean you've given green flag 🟢 to #10072 ?

**Comment by sideshowbarker** [comment]
> Does that mean you've given green flag 🟢 to #10072 ?

No green flag is needed. We've already removed many polyfills in other pull requests

**Comment by AnilSeervi** [comment]
Should the link to polyfill at `core-js` also be removed?

**Comment by sideshowbarker** [comment]
> Should the link to polyfill at `core-js` also be removed? In See Also section

No, that link should not be removed

**Review by sideshowbarker — APPROVED** [review]

**Comment by AnilSeervi** [comment]
@sideshowbarker Can I address #10072 issue and remove the polyfills from the mentioned pages?

**Comment by sideshowbarker** [comment]
> @sideshowbarker Can I address #10072 issue and remove the polyfills from the mentioned pages?

Yes, please do 👍

**Pull request merged**
