### PR TITLE
Clean up JavaScript “Functions” guide a bit further

### PR DESCRIPTION
**Pull request by sideshowbarker**
This is a follow-up to https://github.com/mdn/content/pull/12324

See also https://stackoverflow.com/questions/6605640/javascript-by-reference-vs-by-value/6605700#6605700

### CODE REVIEW

**Comment by sideshowbarker** [comment]
@spazmodius your review of this would be welcome

**Comment by spazmodius** [comment]
It's true, "passing an object" as a function argument results in "sharing" (including the ability to mutate) that object. 

But, being the nature of references, this is pervasive in Javascript. It is not specific or special to parameter passing. It happens via simple assignment, return values, shallow copies, prototypes, everywhere.  It is surely critical for Javascript programmers to understand this concept for what it is, not mentally tied somehow to parameters.

As far as the term "call by sharing": I think this term was useful when the deeply respected Barbara Liskov coined it, to help her readers grasp the significant difference between CLU and ALGOL. Now 40-some years on, I'm not sure it's helpfully applied here. 

For that matter, even saying "pass by value" seems vacuous. It _is_ strictly true; however, it's only utility is to contrast with "pass by reference", a notion no one would contemplate, save for us mentioning it.

**Comment by sideshowbarker** [comment]
@spazmodius OK, given your comments in https://github.com/mdn/content/pull/12344#issuecomment-1019385523, I’ve updated the patch in this PR to drop any mention of call-by-passing.

Please take a look at https://github.com/mdn/content/pull/12344/files and let me know if you think any further changes are needed.

**Comment by spazmodius** [comment]
👍

**Review by Rumyra — APPROVED** [review]

**Comment by Rumyra** [comment]
Apologies I just realised I may have pre-empted the thumbs up as we are good to go 😬

**Pull request merged**
