### PR TITLE
chore(ci): Label & add 'mdn-bot' as author and committer to auto-generated PRs

### PR DESCRIPTION
**Pull request by bsmth**
### Description

In https://github.com/mdn/content/pull/32028, the new default for 'committer' is:

```
github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
```

Current [behavior for v5 is](https://github.com/mdn/content/actions/runs/7807766173/job/21296780418):

```
  Configured git committer as 'GitHub <noreply@github.com>'
  Configured git author as 'mdn-bot <108879845+mdn-bot@users.noreply.github.com>'
```

While not pressing, we can duplicate the mdn-bot account for both author and committer info.

__Additions:__

- Add `committer` field with mdn-bot details mirroring `author`
- Add an "automated pr" label to these pull requests
- cache yarn deps in setup node step

__Updates:__

- Bump `peter-evans/create-pull-request@v6`

### Additional details

- https://github.com/peter-evans/create-pull-request/releases/tag/v6.0.0

### Related issues and pull requests

- https://github.com/mdn/content/pull/32028

### CODE REVIEW

**Review by LeoMcA — APPROVED** [review]
lgtm

**Comment by bsmth** [comment]
Thank you 👍🏻

**Comment by yin1999** [comment]
Hey @bsmth. Would you mind to reflect this in translated-content :)

**Comment by bsmth** [comment]
> Would you mind to reflect this in translated-content

Not at all. PR incoming 🙏🏻

**Pull request merged**
