### PR TITLE
ARIA: delete `ARIA_Test_Cases` and `widgets` pages

### PR DESCRIPTION
**Pull request by OnkarRuikar**
Resolves https://github.com/mdn/content/pull/19171#pullrequestreview-1062799972

The pages are outdated.

### CODE REVIEW

**Comment by teoli2003** [comment]
You should not delete the page, but delete the page and add a redirect:
`yarn content delete <slug> --redirect <slug_to_redirect>`

**Review by teoli2003 — CHANGES_REQUESTED** [review]
Use the right command

**Review by teoli2003 — APPROVED** [review]
Thank you!

**Comment by OnkarRuikar** [comment]
Done! Redirected to `/en-US/docs/Web/Accessibility/ARIA`.

**Pull request merged**
