### PR TITLE
fix wording in 'tolocaltimestring' documentation

### PR DESCRIPTION
**Pull request by tangjm**
Fix sentence wording.

### Description

This is to fix the wording of documentation on the 'toLocaleTimeString' function so the meaning is clear and distinct.

### Motivation

This helps improve the clarity of the documentation by making the meaning of the changed sentence clear and distinct.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Hi! This means you check the existence of `Intl` for support of the `locales` and `options` parameters. You are not checking for support of `Intl`.

**Comment by tangjm** [comment]
This makes sense now, thanks for clarifying. 

I think it would be good if the documentation made it explicit that "you can check `Intl` for support of the `locales` and `options` parameters". Currently, the emphasis is on 'existence' which was misleading for me:

"The locales and options parameters may not be supported in all implementations, because support for the internalization API is optional ..."

"Because any implementation that supports the locales and options parameters must support the [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) API, you can check the existence of the latter for support:"

What I understood by this is that all implementations that support `locales` and `options` parameters also support `Intl`. And for me, this implies that to check whether an implementation supports `locales` and `options` parameters, we can simply check that it supports `Intl`.

**Comment by Josh-Cena** [comment]
> on the fact that support for Intl doesn't imply support for locales and options parameters as this is something we must further check

On the contrary, this is exactly the correlation we rely on: support for Intl implies support for locales and options. Not sure what causes you to understand it otherwise.

**Comment by tangjm** [comment]
Thanks for the reply. Just want to check my understanding by asking a few more questions if that's okay.

1. Can an implementation support Intl but not support locales and options? 
2. Can an implementation support locales and options without supporting Intl? 

My original understanding was that the answer is 'no' for both questions. In other words, Intl is the only way to support locales and options. But if this correct, then would it not be sufficient to check for support for `Intl` to determine if an implementation supports locales and options parameters?

**Comment by Josh-Cena** [comment]
The answers would be no and no, which means "an implementation supports locales and options if and only if it supports Intl". Therefore by checking support for Intl, we can know if it supports the locales and options parameters.

**Comment by tangjm** [comment]
Thanks, this is very helpful. In this case, I would suggest the following change to make this idea explicit. 

"Because any implementation that supports the `locales` and `options` parameters must support the {{jsxref("Intl")}} API, you can check the existence of the latter for support of the former."

**Pull request closed without merging**
