### PR TITLE
Give regular expression example of raw template literals

### PR DESCRIPTION
**Pull request by johnhawkinson**
### Description

With respect to regular expressions, raw strings allow you to avoid double-escaping backslashes (just as the /foobar/ regexp literal does) at the same time as allowing a delimiter that is not / (as is available in many other languages).

Example from #30389

### Additional details

I adjusted the variable names in the example to be a little more clear.
I'm uncomfortable with the line-break and additional comma in the `RegExp()` constructor that `prettier` mandates, but I'm not sure of a good way around them. Shortening the URL to fit within 80 columns makes it hard to come up with an example with a reasonable number of slashes and dots, and therefore fails to be a good demonstration of the value of this.

### Related issues and pull requests

Only resolves the first half of #30389.

### CODE REVIEW

**Comment by johnhawkinson** [comment]
Query: should

```
console.log(re_raw_template.source == re_regexp_literal.source);
```

Instead be `===` (triple-equals)?

**Comment by johnhawkinson** [comment]
2nd query: Does some discussion of this additionally belong in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw? That does seem to be fairly expansive. Perhaps it's an orthogonal question.

**Comment by Josh-Cena** [comment]
> Query: should
> 
> ```
> console.log(re_raw_template.source == re_regexp_literal.source);
> ```
> 
> Instead be `===` (triple-equals)?

Yes.

> Does some discussion of this additionally belong in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw?

In the current state I would suggest moving the entire section to `String.raw`, since it seems more like a concrete use case of the function rather than a discussion about the `raw` property. Granted, they are tightly connected, but the existing text is more conceptual about how you may find the `String.raw` function useful to process the `raw` array.

**Review by Josh-Cena — APPROVED** [review]
I've moved the RegExp example to `String.raw` as I don't think it offers much new information about how raw strings work. I also changed the LaTeX example a bit so we are clearer about how it works. I hope this clears up all the confusion in https://github.com/mdn/content/issues/30389.

**Pull request merged**
