### PR TITLE
Move Mozilla/Firefox/Privacy to Web/Privacy

### PR DESCRIPTION
**Pull request by annevk**
There's a lot more that can be done here with regards to having more vendor-neutral introductions and pointers to relevant specifications, but hopefully this seems like a reasonable first step.

### CODE REVIEW

**Comment by peterbe** [comment]
@annevk Try running `yarn content fix-redirects` and see what that does.

**Comment by annevk** [comment]
That suggests the redirects are orphaned and removes them, which seems bogus?

**Comment by peterbe** [comment]
> That suggests the redirects are orphaned and removes them, which seems bogus?

I suspect those are just warnings during the run of that. 
The person who wrote most of this tooling is on PTO. Even I struggle to understand them.

**Comment by peterbe** [comment]
Perhaps try this. Manually delete the two lines from the `_redirects.txt` file so it goes back to same as `main`. Then, run:
```
yarn tool add-redirect /en-US/docs/Mozilla/Firefox/Privacy /en-US/docs/Web/Privacy
```
push that and we'll see if it works.

**Comment by annevk** [comment]
Assuming s/tool/content/ I get back

> `error: From-URL resolves to a file ($ARCHIVED/en-us/mozilla/firefox/privacy/index.html)`

**Comment by peterbe** [comment]
Oh no. I think we'll need to delete all lines from the `content/archived.txt` in Yari first. 
I just don't understand why it was in there and always has been for the last 3 months. I'll take care of that.

**Comment by peterbe** [comment]
I *think* what happened was that the mozilla/firefox/privacy was considered archived in the initial migration to Yari. Then it was un-archived and now it's not only un-archived (again), but it's being moved too. 

https://github.com/mdn/yari/pull/3716 will hopefully solve your problems but once that lands you'll need to upgrade the version of `@mdn/yari` in your `content` repo. So, in a matter 30min you should be able to merge in the latest `main` for `mdn/content` and then run `yarn install`.

**Comment by annevk** [comment]
CI issues are resolved now, thanks! https://github.com/mdn/content/pull/4729#issuecomment-832688247 still lists some issues, but despite it saying it was last updated recently the information appears stale as I cannot find the broken links it talks about.

So I think this is good for review now.

cc @johannhof

**Review by chrisdavidmills — APPROVED** [review]
I've checked this out locally and tested it, and it all looks fine for now. The page locations look correct, and the redirects work.

I think I'm going to merge this now, and you can work more on the content later on.

**Pull request merged**
