### PR TITLE
Fix: remove few unnecessary <div> tags

### PR DESCRIPTION
**Pull request by bershanskiy**

### CODE REVIEW

**Comment by bershanskiy** [comment]
@chrisdavidmills We are almost done, after this PR there is only one left.

**Review by chrisdavidmills — APPROVED** [review]
LGTM; thanks @bershanskiy !

**Comment by chrisdavidmills** [comment]
Ah, sorry, I didn't realize it was marked as a draft. Have you still got a few changes to add @bershanskiy ?

**Comment by sideshowbarker** [comment]
@bershanskiy Do you still plan in revisiting this PR?

**Comment by rachelandrew** [comment]
Closing as no response @bershanskiy please reopen if you want to finish it!

**Pull request closed without merging**
