### PR TITLE
fixed JXON, relabeled to JSON

### PR DESCRIPTION
**Pull request by futurelogic**
### Fixed JXON, relabeled to JSON

Description summarizes, no additional details needed

### Motivation

Eliminate confusion on name of protocol, and also fix dead links in doc

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Sorry, but it's actually JXON. See https://github.com/mdn/content/pull/21585

**Comment by sideshowbarker** [comment]
Maybe what should instead be done (along with whatever gets done for https://github.com/mdn/content/pull/21585) is that all the _references_ to JXON (like the ones that were changed in this PR) get completely removed. They don’t seem to be serving any useful purpose to anybody at this point — so it’d seem like nobody would miss them if we remove them.

**Comment by Josh-Cena** [comment]
Which means doing a lot of changes to the document object model tree ¯\\_(ツ)\_/¯ This is tracked in https://github.com/mdn/content/issues/21620

**Comment by futurelogic** [comment]
Hmm... ok. Why is this link dead?

[JXON](/en-US/docs/JXON)

But this one is not?

[JSON](/en-US/docs/JSON)

**Comment by futurelogic** [comment]
Screen Shot 2023-01-17 at 9 50 08 AM

**Comment by Josh-Cena** [comment]
Because JXON is mostly an obsolete technology so that section got removed without setting up a redirect or cleaning all references to them—a typical thing when MDN had less-decent governance.

**Pull request closed without merging**
