### PR TITLE
add SVG attribute and element

### PR DESCRIPTION
**Pull request by qibing147147**
### Description

Add page-type in page of SVG attribute and SVG element

### Related issues and pull requests
[page types] Define page types for SVG [#22762](https://github.com/mdn/content/issues/22762)

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks for your PR.

Page types should be lowercase and use hyphens instead of spaces, like `svg-attribute`. I know this isn't explained anywhere and I'm sorry for that, but I wasn't really expecting other people to file PRs for this work without contacting me first.

I just filed https://github.com/mdn/content/pull/22829 for all of SVG.

**Comment by qibing147147** [comment]
> Thanks for your PR.
> 
> Page types should be lowercase and use hyphens instead of spaces, like `svg-attribute`. I know this isn't explained anywhere and I'm sorry for that, but I wasn't really expecting other people to file PRs for this work without contacting me first.
> 
> I just filed #22829 for all of SVG.

I edit these files with a script written by myself, I can do it again if u need. And I'm glad for that if u can tell me how to add it.

**Comment by wbamberg** [comment]
Thank you @qibing147147 ! We have a few open issues to add page types for [HTML](https://github.com/mdn/content/issues/22705), [HTTP](https://github.com/mdn/content/issues/22761), and [JavaScript](https://github.com/mdn/content/issues/16156). I don't think these are quite ready to be implemented yet: I want to wait a few more days in case people have more comments to make.

But, as soon as I think we are ready to add these page types I can let you know if you like.

**Comment by qibing147147** [comment]
> Thank you @qibing147147 ! We have a few open issues to add page types for [HTML](https://github.com/mdn/content/issues/22705), [HTTP](https://github.com/mdn/content/issues/22761), and [JavaScript](https://github.com/mdn/content/issues/16156). I don't think these are quite ready to be implemented yet: I want to wait a few more days in case people have more comments to make.
> 
> But, as soon as I think we are ready to add these page types I can let you know if you like.

It would be greate if you can let me know.I am glad to do it.

**Pull request closed without merging**
