### PR TITLE
Replace `var` with `let`

### PR DESCRIPTION
**Pull request by MrBrain295**
#### Summary

Replace `var` with `let`.
#### Motivation

It was wrong
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thanks for your PR!

But I think this code sample has bigger problems. It won't work on Firefox or Chrome, and the glossary entry as a whole is very confusing (The Wikipedia article is much better: https://en.wikipedia.org/wiki/XInclude ).

I think we should delete the code sample and rewrite this glossary entry to be much shorter.

**Comment by wbamberg** [comment]
Specifically, I think we could say something like:

******

XInclude is a W3C Recommendation defining inclusion tags which enable documents to include other documents or parts of other documents. Content can be included from other XML files or from text files.

The XInclude mechanism is not supported natively by any major browsers.

See also

* XInclude standard
* XPath

******

**Comment by MrBrain295** [comment]
@wbamberg should I adapt this PR to do that or should I make a new PR?

**Comment by wbamberg** [comment]
Whichever is easiest for you :)

**Pull request closed without merging**
