### PR TITLE
Add page-type to Web_component and relocate them

### PR DESCRIPTION
**Pull request by teoli2003**
As part of openwebdocs/project#91 we adds page-type to every document on MDN.

This PR adds them (_landing-page_ and _guide_) to the documents under Web/Web_components.

In addition, it relocates the folder under Web/API. Its location at the top of the Web/ hierarchy is incongruous: It is a set of APIs. Its sidebar was `{{DefaultAPISidebar}}` and used `GroupData.json` anyway.

### CODE REVIEW

**Comment by wbamberg** [comment]
This is incongruous under Web/API as well though, isn't it? AFAIK this is the only `landing-page` under Web/API, and the only `landing-page` to get DefaultAPISidebar. There's a little history on this here: https://discourse.mozilla.org/t/defaultapisidebar-apiref-and-groupdata/40210/18.

I think we should decide whether it's a `web-api-overview` page, and if so put it in Web/API, or a `landing-page` and keep it where it is...

**Comment by teoli2003** [comment]
I would see it as a `web-api-overview` then. Even if it touched a bit HTML, you need to use the API part of it to use it.

**Comment by wbamberg** [comment]
Fair enough, I'm happy with that for now.

I think the underlying issue here is that we have this IA in Web/API in which top-level things are supposed to be "Web APIs", narrowly conceived as things that map to specifications, but then we quite often want to talk about higher-level concepts that cut across "Web APIs", narrowly conceived, and we don't have a systematic way to present these. See also, things like the PWA docs and to a lesser extent the new Performance API docs.

Some day we will need to resolve this.

**Comment by teoli2003** [comment]
> Some day we will need to resolve this.

I think we will be able to resolve this the day we can have the Divio system applied at the top level. For this, we first need to clean the top level, though.

**Comment by wbamberg** [comment]
This will also need:

```
       "overview": ["Web components"]
```

...in groupdata.json, or it won't appear in https://developer.mozilla.org/en-US/docs/Web/API and the sidebar won't have the name at the top:

Screen Shot 2023-04-13 at 2 06 18 PM

I'm still a bit uncomfortable having this in Web/API, but I take the point that we don't have a perfect solution here.

**Review by wbamberg — APPROVED** [review]
Thanks @teoli2003 !

**Pull request merged**
