### PR TITLE
fix flaws in svg/tutorial/paths and inner_and_outer_windows

### PR DESCRIPTION
**Pull request by peterbe**
Because this is depending on file attachments with non-ascii characters, this PR won't work (in production) until we merge [this Yari PR](https://github.com/mdn/yari/pull/2343). Hence the Draft status.

### CODE REVIEW

**Comment by peterbe** [comment]
https://github.com/mdn/yari/pull/2343 has landed but if you're testing *this* PR using the Yari within `mdn/content` you'll have to wait at least 1 day to review so you get the latest release of Yari within content.

**Comment by peterbe** [comment]
...or you can review using the `master` branch of Yari.

**Comment by peterbe** [comment]
ping @chrisdavidmills r?

**Review by chrisdavidmills — APPROVED** [review]
r+

**Pull request merged**
