### PR TITLE
(Railway) Add updated image connect mongodb explanation

### PR DESCRIPTION
**Pull request by marcusicaro**
### Description
The image used on the tutorial is outdated and does not show where the link is.

### Motivation
Improving a resource that has teached me a lot.

Readers will be able to find the link to the mongodb connection easier.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @marcusicaro 

Really appreciate you providing images that capture changes in the Railway interface. 

Can you please regenerate the image, highlighting it as I have done below rather than using the red box?

image

There are three reasons for this:
- consistency: everywhere else in the tutorial uses the yellow highlight.
- The way I have done this shows the copy button - that's more useful than copying the text directly.
- Red is pretty virulent as a colour - the yellow looks more friendly. That of course is just an opinion.

**Review by hamishwillee — CHANGES_REQUESTED** [review]
Thanks @marcusicaro 

Really appreciate you providing images that capture changes in the Railway interface. 

Can you please regenerate the image, highlighting it as I have done below rather than using the red box?

image

There are three reasons for this:
- consistency: everywhere else in the tutorial uses the yellow highlight.
- The way I have done this shows the copy button - that's more useful than copying the text directly.
- Red is pretty virulent as a colour - the yellow looks more friendly. That of course is just an opinion.

**Comment by marcusicaro** [comment]
> Thanks @marcusicaro
> 
> Really appreciate you providing images that capture changes in the Railway interface.
> 
> Can you please regenerate the image, highlighting it as I have done below rather than using the red box?
> 
> image
> 
> There are three reasons for this:
> 
> * consistency: everywhere else in the tutorial uses the yellow highlight.
> * The way I have done this shows the copy button - that's more useful than copying the text directly.
> * Red is pretty virulent as a colour - the yellow looks more friendly. That of course is just an opinion.

Hello, Hamish, thank you for your time to give a detailed explanation of what you think could be improved in this PR.

I agree with both changes on color, but there's one detail. On the actual interface of Railway, they do not show the Mongo Connection URL. But instead, they show a mongosh command.

For this, I suggest two alternatives:
1. Show an image like the one I did (but with yellow borders).
2. To teach the users how to run the mongosh command on Railway terminal for theirs project. 

For now, I will upload a updated image with yellow borders, but, if anything, please let me know how I can help improving this lesson.

Thanks!

**Comment by hamishwillee** [comment]
Thanks @marcusicaro - this is better, but I still can't see the "Show" button highlighted - i.e. if you hover you can see the "copy" symbol. That's useful because most people will want to just click that button. So the highlight should look like this (just mocked below)

image

**Comment by hamishwillee** [comment]
PS, and now I read your comment properly. Let me think a minute.

**Comment by hamishwillee** [comment]
@marcusicaro Thanks. I see where you are coming from. The user has to copy the URL. They can either do it by copying it as you have shown - but omitting the `"` around it, OR they can press the copy button and then take the URL part out of it.

W.r.t. the image I think we should still show the "copy" button on hover, but highlight as you have done around the actual URL.

Note however that the text around it needs to change to explain that you doing. How about the text in blue below?

image

**Comment by marcusicaro** [comment]
Hey, sorry for taking too long to answer, I had not seem any notifications.

I guess your image is good, it clearly explains what has to be done.

You want me to change my image or should we use yours?

**Comment by hamishwillee** [comment]
Can you please change your image?

**Comment by bsmth** [comment]
Hi @marcusicaro - there's a request above from a reviewer that needs a response. Do you plan to come back to this?

**Comment by marcusicaro** [comment]
> Hi @marcusicaro - there's a request above from a reviewer that needs a response. Do you plan to come back to this?

Hello, @bsmth. Yes, I do. I'll check it out later today. Thanks for getting in touch.

**Comment by bsmth** [comment]
Going to close this one now as fixed in https://github.com/mdn/content/issues/32075 - thanks a lot for your proposal, though :)

**Comment by marcusicaro** [comment]
> Going to close this one now as fixed in https://github.com/mdn/content/issues/32075 - thanks a lot for your proposal, though :)

All right, thanks!

**Pull request closed without merging**
