### PR TITLE
Font fix for description of abbreviation

### PR DESCRIPTION
**Pull request by simonvarey**
#### Summary
I replaced the markdown for italics and bold in the abbreviation description with HTML tags.

#### Motivation
The markdown for italics and bold didn't render properly because there was no space between them.

#### Supporting details
This Stack Exchange post describes how they now have intra-word emphasis in their markdown: https://meta.stackexchange.com/questions/240354/markdown-change-intra-word-emphasis-now-works

#### Metadata
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thanks for finding this!

I would much rather not have inline HTML for things like this. I feel like if we start allowing inline HTML for any kind of typography that our Markdown can't handle, we'll end up with source that's a mixture of Markdown and HTML, and that negates the value of using Markdown. I think in this case it would be fine to say:

```
**co**der-**dec**oder
```

**Review by wbamberg — COMMENTED** [review]
👍 thank you, @simonvarey !

**Review by wbamberg — APPROVED** [review]

**Comment by simonvarey** [comment]
@wbamberg Thanks for the merge. It might still be handy to be able to intra-word bold italics in Markdown (unless there's some way of doing that I'm missing).

**Comment by wbamberg** [comment]
What's odd is that the post you referenced says CommonMark can do this, so we ought to be able to as well, since we use GFM which is just CommonMark plus a couple of extensions.

But AFAICT CommonMark does not support this: https://spec.commonmark.org/dingus/?text=**_co_**der-**_dec_**oder

If there is a way to support this in GFM I'd be happy for us to use it, but I don't think it's an important enough case for us to extend our Markdown.

**Comment by simonvarey** [comment]
Now that I look more closely at that post, all they were saying now works is a _single_ level of intra-word emphasis. I assumed that if it would work for a single level it would work for multiple levels, but now I think about it more that would introduce parsing difficulties. I agree its probably not important enough for its own extension.

**Pull request merged**
