### PR TITLE
Update sample rendering for menclose and mfenced

### PR DESCRIPTION
**Pull request by pepelsbey**
### Description

- Uses SVG instead of PNG for sample rendering (for `menclose` and `mfenced` elements)
- Adds sample rendering for the circle-box example
- Scales up demos a bit and aligns them vertically

image

### Motivation

To improve rendering examples.

### Additional details

I used MathJax’s SVG rendering to source images.

### CODE REVIEW

**Review by bsmth — APPROVED** [review]
Nice, looking good, ty 👍🏻

**Comment by pepelsbey** [comment]
@fred-wang could you please have a look? Thank you!

**Review by fred-wang — APPROVED** [review]
rubber-stamp=me

**Comment by bsmth** [comment]
Thanks, both. I'm going to merge this one now :+1:

**Pull request merged**
