### PR TITLE
Remove duplicate words

### PR DESCRIPTION
**Pull request by myogh**
### Description
- Fixed an extra word from a sentence.

### Motivation
- For better reading experience.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Good catch. Could you update `function*` and `async function*` too? I'm going to do that myself in a few hours so I can merge this, but I don't have a computer at the moment.

**Review by Josh-Cena — APPROVED** [review]
Thanks

**Comment by myogh** [comment]
> Good catch. Could you update `function*` and `async function*` too? I'm going to do that myself in a few hours so I can merge this, but I don't have a computer at the moment.

Sorry @Josh-Cena. I was sleeping and didn't catch this comment. Anyway, I'm glad they are fixed now. Thanks.

**Comment by Josh-Cena** [comment]
It's totally okay. I'm just sending the message so (a) other maintainers won't merge it in the meantime (b) you may be able to do this and save me the effort although it's totally not necessary.

**Pull request merged**
