### PR TITLE
Fixed header/footer removal

### PR DESCRIPTION
**Pull request by OliverBrotchie**
#### Summary
The example code for removing the header/footer of a key would leave the first character of the footer, this change fixes that.

#### Metadata
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by sideshowbarker** [comment]
@twiss If you could review this, that’d be great

**Comment by twiss** [comment]
This patch removes a trailing newline from the base64, but not the leading newline - and anyway, the string is passed to `atob()` immediately after that, which removes all ASCII whitespace. So I don't think this patch is needed. (In other cases, it may be needed to get the base64 without the newlines, but this is just an example - I think it can be adapted by the user, and the code is clear enough as-is, imho.)

**Comment by sideshowbarker** [comment]
@OliverBrotchie Given https://github.com/mdn/content/pull/13780#issuecomment-1068351297 I’m going ahead and closing this — but if you have additional info that merits re-considering it, this could be re-opened

**Comment by OliverBrotchie** [comment]
> This patch removes a trailing newline from the base64, but not the leading newline - and anyway, the string is passed to `atob()` immediately after that, which removes all ASCII whitespace. So I don't think this patch is needed. (In other cases, it may be needed to get the base64 without the newlines, but this is just an example - I think it can be adapted by the user, and the code is clear enough as-is, imho.)

You are correct that `atob` removes the whitespace but in the current example, the first `-` of the footer is left which gives an error when run by `atob`.

**Comment by twiss** [comment]
Is it..? The examples run correctly for me.

Maybe you're passing a different key with a trailing newline, or something like that?

**Pull request closed without merging**
