### PR TITLE
contentvisibilityautostatechangeevent not changeDevent

### PR DESCRIPTION
**Pull request by hamishwillee**
The spec names the `contentvisibilityautostatechangedevent` but there was a working group discussion to name them with suffix "change" - i.e. without the "D". This is what Firefox and Chromium have actually implemented.
The change hasn't happened in the spec yet but should given it was agreed - that can be tracked as https://github.com/w3c/csswg-drafts/pull/8413

The corresponding BCD changes are in https://github.com/mdn/browser-compat-data/pull/18848 and https://github.com/mdn/browser-compat-data/pull/18865

Related work can be tracked in #23687

### CODE REVIEW

**Comment by wbamberg** [comment]
Is this the same as https://github.com/mdn/content/pull/24263 ?

**Comment by hamishwillee** [comment]
Arrrggg. Yes. Closing - their one has the required group data. I'll review it.

**Comment by wbamberg** [comment]
I did review that one but wanted to wait for the BCD to get deployed, so we didn't get broken tables, per https://github.com/mdn/content/pull/24263#issuecomment-1423064978. But no worries :).

**Comment by hamishwillee** [comment]
Sorry about that. Broken tables are not good, but "less bad" in this case because they are also wrong w.r.t. FF - this is delivered behind a preference.

**Pull request closed without merging**
