### PR TITLE
Added multiple wasm pages

### PR DESCRIPTION
**Pull request by MendyBerger**
**BEFORE MERGING:** Please make sure that mdn/interactive-examples/pull/2008 is also merged, otherwise some pages will be left with blank examples.

#### Summary

Added multiple wasm test format pages, including variable and memory manipulation, as well as numeric operations.

#### Motivation

I'm trying to slowly write as much documentations/examples as I can for the wasm/wat reference.

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
> **BEFORE MERGING:** Please make sure that [mdn/interactive-examples/pull/2008](https://github.com/mdn/interactive-examples/pull/2008) is also merged, otherwise some pages will be left with blank examples.

I’ve merged https://github.com/mdn/interactive-examples/pull/2008) but I suppose before merging this mdn/content PR, we need to wait until the `interactive-examples` content is actually deployed. Right, @mdn/core-yari-dev? I guess that means waiting for about ~48 hours.

Putting this at Draft status in the meantime — so that we don’t merge it prematurely.

**Comment by hamishwillee** [comment]
@MendyBerger This looks excellent, but does not appear to be linked from anywhere - i.e. I would expect this to be in the sidebar all linked to each other, . Also from https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format and in the sidebar for https://developer.mozilla.org/en-US/docs/WebAssembly/Reference

Any particular reason?

Context for me is that I'm trying to get my head around web assembly for the exception handling spec.

**Comment by MendyBerger** [comment]
@hamishwillee no real reason besides I haven't gotten around to do it...

BTW I didn't write any docs specifically for exception handling yet, as I wanted to finish the MVP spec first, and even in the MVP there is still a lot of work.

Needless to say, if you're able to figure out how exception handling works and you have the time, a PR adding docs about it would be greatly appreciated!

**Comment by hamishwillee** [comment]
Thanks @MendyBerger - I'm employed by Mozilla to document Firefox release features. WASM exception handling is supported in FF100 so I will either need to do it myself or find someone to advise ;-)

**Comment by MendyBerger** [comment]
@hamishwillee that's so cool! If there's anything I can help feel free to reach out to me

**Comment by hamishwillee** [comment]
@MendyBerger Reserve judgement until I'm done :-) . I will certainly point you to the PR for comments.

**Pull request merged**
