### PR TITLE
WebAPI: Clean syntax from property pages, part 12

### PR DESCRIPTION
**Pull request by OnkarRuikar**
## Summary

Sequel of #14195 
As per the template API_property_subpage_template, Syntax section is redundant in property pages. So getting rid of the cruft.

Changes:
- Removed syntax sections
- Enforced heading names to ## Value, ## Examples.
- Other small corrections

#### Metadata

- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by teoli2003 — CHANGES_REQUESTED** [review]
Can you remove the changes to `onXYZ` (except `Navigator.onLine`). There are been moved and this will create a change conflict.

Thanks!

**Comment by OnkarRuikar** [comment]
> Can you remove the changes to `onXYZ` (except `Navigator.onLine`). There are been moved and this will create a change conflict.

You mean revert all files under "globaleventhandlers" like "onanimationiteration"?

**Comment by teoli2003** [comment]
Yes, please. (Sorry didn't think about them before)

**Comment by OnkarRuikar** [comment]
@teoli2003 I've replaced them with new files. 

When will the migration end? so that I'll commit "globaleventhandlers" files after that.

**Comment by teoli2003** [comment]
The migration should end in the next few days: you won't need to redo this work afterward as these pages will be gone (renamed and with a different structure).

**Review by teoli2003 — APPROVED** [review]
👍

**Pull request merged**
