### PR TITLE
Add Lume to list of WebGL libraries.

### PR DESCRIPTION
**Pull request by trusktr**
### Description

https://lume.io

### Motivation

To help web developers around the world more easily write 3D content with vanila HTML; or within their favorite web frameworks such as React, Vue, Angular, Svelte, Solid.js; in the simplest way without needing to know higher-level JavaScript (as we do with plain JS engines such as Three.js, PlayCanvas, or Babylon.js).

### Additional details

Besides aiming to make 3D in the web easier, Lume aims to make it robot and human accessible. Lume's elements can be rendered from server-side applications, indexed by search engines, or described to blind users via screen readers with the help of ARIA attributes.

Lume has embarked on a journey to try to answer the question "what might 3D HTML in future browsers look like?" A-Frame had the first attempt, but we still have a ways to go, and Lume provides a fresh set of new and improved ideas that fully embrace the future of web development.

For example Lume elements support having `ShadowRoot`s and are fully composable with `<slot>` elements, giving developers the ability to compose higher-level 3D elements out of Lume's lower-level 3D elements. This is unlike React/Vue/Svelte whose components are not compatible with web standards and not interoperable, not inspectable in devtools out of the box, etc.

Lume elements are highly-inspectable and debuggable in a browser's element inspector! [See a demo](https://docs.lume.io/guide/debugging) of hovering on an element in element inspector and seeing the location of the 3D model on the screen.

So, it is time! I aim to get Lume into people's hands and begin to teach the world not only the simplest, but also the best and most futureproof, way to write the 3D web apps.

### CODE REVIEW

**Comment by bsmth** [comment]
Thanks a lot for opening a pull request, however I'm going to close this as the contribution guidelines strongly [discourage submitting links to your own projects](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#external_links). I wish you success with your project, and thanks for your understanding.

**Comment by eslachance** [comment]
> Thanks a lot for opening a pull request, however I'm going to close this as the contribution guidelines strongly [discourage submitting links to your own projects](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#external_links). I wish you success with your project, and thanks for your understanding.

I don't get it. What's the conflict here? @trusktr disclosed their relationship with the project, and it is appropriate for the page where it's being added. The guideline says it's *discouraged*, not *forbidden*, can you elaborate on why you're closing this without further consideration?

**Comment by bsmth** [comment]
Hi @eslachance, I considered this submission thoughtfully, I don't want to give the impression that I did not. Adding links to projects when they're submitted by the project authors is a very common occurrence on MDN, and these PRs are almost always rejected. It falls under the policy:

>Self-linking or self-promotional (e.g., the author's own work off of MDN Web Docs)

Such projects are hard to vet for reviewers and incur maintenance costs for the quality of external resources. My judgement in this case is to close the PR. I understand this can be frustrating, but the editorial policy is in place to ensure content quality for readers and keep the site maintainable. I hope that makes sense, and sorry if that's disappointing.

**Comment by eslachance** [comment]
It is pretty disappointing, and it also probably pushes people to lie by asking someone else to submit the same changes. I bet this has been discussed to death, but can you please explain to me how it's harder to vet code that's been submitted by the author, versus that same code submitted by anyone else?

Also, your quote from the page you linked to doesn't address my point which you're outright ignoring: the page is worded in such a way that one is *allowed* to submit one's own work, but it's discouraged due to a vague sense of "self-promotion" which is only really distinguishable from regular old promotion by the username submitting the PR and does not substantially change the nature of the content modification or the quality of such.

If all PRs done to MDN that fall under this guideline are rejected with the same unreasonably strong metric, then the page should be edited to reflect this, with language that indicates to library authors that it is simply not allowed for them to do so.

I'm sure they'll just skip the "self promo" and just ask one of their users to submit it for them. What reason would you give then, for the rejection, I wonder.

**Comment by dipikabh** [comment]
Hello @eslachance, thank you for sharing your perspective. We understand that this situation can be frustrating. We also acknowledge that our guidelines might lead some folks to ask others to submit on their behalf to avoid the "self-promotion" label. However, regardless of who submits the link, our review process remains the same.

As also outlined under ["Good external links"](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#external_links), we evaluate the relevance, durability, age, reliability, etc. of the submission. The decision to include a link or project is made on a case-by-case basis, and it really depends on a mix of different considerations. MDN reviewers are empowered to make a judgement call based on these factors.

Also note that a submission that is not approved today could potentially be approved in the future as the project matures and gains wider recognition and usage in the community.

**Pull request closed without merging**
