### PR TITLE
Update HTML input pattern attribute documentation (fixes #26907)

### LINKED ISSUE #26907: u flag => v flag
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern

### What specific section or headline is this issue about?

Overview

### What information was incorrect, unhelpful, or incomplete?

The implicit `u` flag has been changed to `v` in ECMAScript 2023.

### What did you expect to see?

>the `'v` flag is specified when compiling the regular expression

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/input.html#attr-input-pattern

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/pattern`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/pattern/index.md
* Last commit: https://github.com/mdn/content/commit/942a529383ee7ee3996fb234187641c08935f3ff
* Document last modified: 2023-04-13T06:13:15.000Z

</details>

### PR DESCRIPTION
**Pull request by gijsk**
I've tried to apply the feedback from #29842 and reorganized some of the sections to hopefully make them clearer.

### Description

This adds language around the specifics of how the `pattern` attribute's functionality compares with "normal" JS regular expression (notably the addition of the `v` flag). It also reorganizes the a11y and usability considerations so they read a bit better and aren't spread out across the document.

### Motivation

Because I got confused about why `[\w-]` was not working inside a pattern attribute. It took asking several people before someone was able to point out that the `v` flag gets applied and that's why the behaviour was different.

### Additional details

https://github.com/whatwg/html/pull/7908

### Related issues and pull requests

fixes #26907, relates to #29842.

### CODE REVIEW

**Comment by teoli2003** [comment]
Added @estelle as a reviewer, as this PR adds additional accessibility info, and she will be able to review it.

**Comment by gijsk** [comment]
> Added @estelle as a reviewer, as this PR adds additional accessibility info, and she will be able to review it.

It doesn't, actually - it just moves existing content around so it's not under the "example" section and groups usability and accessibility together.

**Comment by gijsk** [comment]
So I'm pretty confused here because this now has conflicts as a result of https://github.com/mdn/content/pull/31180 which was @estelle's PR to "standardize" the a11y header. It references "guidelines" (where are those? They are not linked - I found https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines but not sure which subdoc the specific guidelines referenced are in). But the header is still in the "examples" section which seems wrong, and I can't tell if the guidelines mean it's "wrong" for me to rename it and include UX-y considerations in the same place. I did so because IMO how and when to show guidance on form validation is not _just_ about accessibility but about usability in general.

**Review by estelle — APPROVED** [review]
Thanks! 🎉

**Pull request merged**
