### PR TITLE
A little bit of rewording [can't make a better title than that😁]

### PR DESCRIPTION
**Pull request by softorangetech1122**
#### Summary

This PR does a little reword on the creating hyperlinks document.
#### Motivation

There's not really anything.
#### Related issues

It's just a reword
#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by Josh-Cena** [comment]
I don't think this change brings any clear improvement to our content's quality. I wouldn't encourage contributions like this.

**Comment by softorangetech200** [comment]
> I don't think this change brings any clear improvement to our content's quality. I wouldn't encourage contributions like this.

But it was closed anyway,

**Comment by Josh-Cena** [comment]
Yeah I commented immediately after it was opened, but I'm on the phone so typing takes time...

**Comment by softorangetech200** [comment]
> Yeah I commented immediately after I saw it was opened, but I'm on the phone so typing takes time... Was about to close but it then became closed anyway.

lol😁

**Pull request closed without merging**
