### PR TITLE
OPTIMAZE IMAGES

### PR DESCRIPTION
**Pull request by akaday**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@akaday Thanks, but we have an image optimizer in place and I don't know the implications of taking this change. Can you tell us what software/library you are using for this?

@caugner Is this a discussion the yari team could own (i.e. I added you as a reviewer and I'd like to remove myself)?

**Comment by akaday** [comment]
@akaday I used ImgBot for optimizing the images. ImgBot automates image compression and ensures that images are optimized without compromising quality. It's designed to integrate seamlessly with GitHub projects and can be a valuable addition to our existing setup. Happy to provide more details or discuss further!

@caugner, any thoughts on this? I believe your insights would be invaluable here. Thanks for stepping in!

**Comment by akaday** [comment]
@hamishwillee I understand your concern about the existing image optimizer. Let me provide some details about ImgBot:

- **How ImgBot Works**: ImgBot automates image compression, ensuring images are optimized without compromising quality. It seamlessly integrates with GitHub projects and runs as part of the CI/CD pipeline.
- **Advantages**: ImgBot reduces image file sizes, which can improve page load times and overall performance. It's designed to be unobtrusive and efficient.
- **Testing Compatibility**: I'm happy to assist with testing ImgBot alongside the existing optimizer to ensure there are no conflicts or redundancy issues.

@caugner, I would appreciate your insights on this. Thanks!

**Comment by caugner** [comment]
The intention of this PR is good, but indeed all images should automatically get optimized as part of deployment, and optimizing the images here will increase the repository size.

There may be a case to optimise images here that are >1MB and can be optimised to <100 kB, but otherwise I don't think it's justified.

/cc @fiji-flo to take the final decision.

**Comment by bsmth** [comment]
> There may be a case to optimise images here that are >1MB and can be optimised to <100 kB, but otherwise I don't think it's justified.

Just to add that I agree, and this PR is shaving a few bytes off most images in a lot of cases (less than 1% reduction in size), it might be worth looking at images where there's a certain percentage reduction, like Claas mentioned.

**Comment by pepelsbey** [comment]
I'd rather start with implementing guidelines/tooling to avoid such images added in the first place. And only then optimize the worst offenders that affect user traffic and loading speed.

As for the approach:

> all images should automatically get optimized as part of deployment

I don't think it's a very sustainable solution to optimize images over and over again for every commit/deploy, given the energy intensity of a typical optimization tool. It's better to either store already optimized images or use CDN that does it once and keeps them in cache.

**Comment by caugner** [comment]
> I'd rather start with implementing guidelines/tooling to avoid such images added in the first place. And only then optimize the worst offenders that affect user traffic and loading speed.

We already have tooling for this, see: https://github.com/mdn/yari/blob/6ccdb3f8bbf870c88150fa800e3ee88b7ef73739/filecheck/checker.ts#L206-L289

The filecheck is run
- on commit:
  https://github.com/mdn/content/blob/caff4a64ad91783cb22d08f6c622664521b594c6/.lintstagedrc.js#L16-L18
- and on content PRs:
  https://github.com/mdn/content/blob/caff4a64ad91783cb22d08f6c622664521b594c6/.github/workflows/pr-test.yml#L134

**Comment by akaday** [comment]
Thanks for the feedback, everyone!

I appreciate the insights and understand the concerns regarding the repository size and existing optimization tools. Here are a few points I’d like to clarify about ImgBot and its potential benefits:

1. **Complementing Existing Tools**:
   - ImgBot can work alongside our existing tools to target specific cases where images can be significantly optimized. For instance, we can focus on images that are larger than 1MB and can be reduced by a substantial percentage without compromising quality.

2. **Efficiency**:
   - ImgBot automates the compression process and integrates seamlessly with our CI/CD pipeline, ensuring consistent optimization across all images. This can be especially beneficial for new images added to the repository.

3. **Proposed Next Steps**:
   - I suggest starting with a subset of images (e.g., those greater than 1MB) to see the impact and efficiency of ImgBot. This approach can help us evaluate its benefits without affecting the overall repository size.

I’d love to hear your thoughts on this and am happy to assist with any testing or integration efforts.

Thanks again for considering this PR and for the opportunity to discuss it further!

**Comment by bsmth** [comment]
Closing for now, thanks.

**Pull request closed without merging**
