### PR TITLE
Drop link to outdated “New in JavaScript” doc

### PR DESCRIPTION
**Pull request by Rumyra**
Lots of external links on this page, so just running through and adding `class="external"` to them.

Also removed one 'New in JS' link as those articles appear to be archived

### CODE REVIEW

**Review by chrisdavidmills — COMMENTED** [review]
Hold on; we're trying to remove `class="external"` from everywhere. We don't need it in the source code because it is added automatically during rendering.

**Comment by chrisdavidmills** [comment]
Ooops, wait, there is other stuff in this PR, isn't there. Sorry about that!

**Comment by sideshowbarker** [comment]
> Hold on; we're trying to remove `class="external"` from everywhere. We don't need it in the source code because it is added automatically during rendering.
> Ooops, wait, there is other stuff in this PR, isn't there. Sorry about that!
>
>> Also removed one 'New in JS' link as those articles appear to be archived

I think that removal is the only other thing in this patch, so @chrisdavidmills, I guess what you’re saying is that the patch should be reduced to just that change?

**Comment by chrisdavidmills** [comment]
> > Hold on; we're trying to remove `class="external"` from everywhere. We don't need it in the source code because it is added automatically during rendering.
> > Ooops, wait, there is other stuff in this PR, isn't there. Sorry about that!
> > > Also removed one 'New in JS' link as those articles appear to be archived
> 
> I think that removal is the only other thing in this patch, so @chrisdavidmills, I guess what you’re saying is that the patch should be reduced to just that change?

Yes. I think this is the "JavaScript versions and release notes" we are talking about? In which case we should remove the corresponding description (`<dd>`) as well as the term.

**Comment by Rumyra** [comment]
Sorry! I totally got the wrong end of the stick with class="external" - updated 👍

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
