### PR TITLE
Fix examples for backgroud-position-[x/y]

### PR DESCRIPTION
**Pull request by queengooborg**
This PR fixes the examples for the `background-position-x` and `background-position-y` CSS properties.  The examples use two-value syntax for `background-position-y`, which is currently unsupported in Chrome.  This fixes the issue by adding a second example for the two-value syntax, instead of integrating it into the basic example.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
I made an extra change, but LGTM

**Comment by queengooborg** [comment]
Oop, don't merge just yet!

**Comment by queengooborg** [comment]
(I'm surprised I caught you in time!  😆 )

I just made a realization: I was looking at the "Multiple values" section of the syntax and totally overlooked the "Side-relative values" section.  I used the term "two-value syntax" because that's what is called in BCD.  The spec doesn't actually have a formal name for this syntax though.

We should probably pick just one and stick with it everywhere.  Because "Multiple values" is a thing, I'm thinking "Side-relative values" is the term to use.  WDYT?

**Comment by teoli2003** [comment]
> (I'm surprised I caught you in time! 😆 )

I always wait for the tests to finish running when I do an extra modification.

**Review by teoli2003 — APPROVED** [review]

**Pull request merged**
