### PR TITLE
Add HTML page types

### LINKED ISSUE #22705: [page types] Define page types for HTML
Part of https://github.com/mdn/content/issues/15539.

In https://docs.google.com/spreadsheets/d/14RX8EEKPpeYkP2cF5Y_ZKF3JpNJ_24OL7stvZWNJLIY/edit#gid=2083448819, in the "HTML" tab, I've listed every page under https://developer.mozilla.org/en-US/docs/Web/HTML and made an initial determination about the page type.

Apart from the generic "guide" and "landing page" types, I have come up with just:

```
HTML attribute (52)
HTML attribute value (11)
HTML element (156)
```

In the IA attributes are a mess, we have them in at least three places:
- global attributes under https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes
- some non-global attributes under https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
- some other non-global attributes under some element

Some day we should sort this out but I don't think it affects page types.
From a page types perspective, I opted not to have a separate type for "global attributes". AFAICT they are structurally the same, they just apply to a different set of elements.

I opted to call input types "HTML element" to align with the general fiction we have of treating them as individual elements. I think this is a reasonable approach although we do have an organizational problem that they live under another element page. This is especially confusing since we also have some attributes under element pages.

An alternative I suppose could be to call input types "HTML attribute value" pages, which is technically correct. But it is perhaps less helpful.

******

BTW I wanted to do this now because removing [one of the places we use tags](https://github.com/mdn/yari/blob/2720d1f9998be94428a822dcc06946d6a53879d0/kumascript/macros/CSSInfo.ejs#L44) depends on having HTML element page types.

### PR DESCRIPTION
**Pull request by wbamberg**
Add HTML page types following the discussion at https://github.com/mdn/content/issues/22705. Fixes https://github.com/mdn/content/issues/22705.

### CODE REVIEW

**Review by Elchi3 — CHANGES_REQUESTED** [review]
Did you run your scripts against latest main? 
A few pages miss a page type still if I see it correctly.

Web/HTML
Web/HTML/Content_categories
Web/HTML/Constraint_validation
Web/HTML/Element/script/type
Web/HTML/Element/script/type/importmap
Web/HTML/Global_attributes/virtualkeyboardpolicy

**Comment by wbamberg** [comment]
> Did you run your scripts against latest main? A few pages miss a page type still if I see it correctly.
> 
> Web/HTML Web/HTML/Element/script/type/importmap Web/HTML/Global_attributes/virtualkeyboardpolicy

Sorry Florian, my spreadsheet is a bit out of date.

**Comment by Elchi3** [comment]
I did a negative search for "page-type" and updated the list. A few more missing

**Comment by Elchi3** [comment]
To verify, I think the number of files with "slug" should be the same amount of files with "page-type".

**Review by Elchi3 — APPROVED** [review]
Great! 👍

**Pull request merged**
