### PR TITLE
Almost all browsers support Worker modules now

### PR DESCRIPTION
**Pull request by codedread**
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by wbamberg — CHANGES_REQUESTED** [review]
Thanks for your PR, @codedread ! We think it would be better to remove this note entirely, as this is covered in the Browser compatibility table, and will be easier for us to keep up to date there.

**Comment by wbamberg** [comment]
> @wbamberg - if we removed the note, it would remove the link to the Bugzilla issue, which is important to let folks know the current status... thoughts?

The conventional way to do this in BCD is to add a note like "See <a href='https://bugzil.la/1234567'>bug 1234567</a>." although there is a longstanding request to have a dedicated mechanism for this: https://github.com/mdn/browser-compat-data/issues/126.

But this info is very patchily added AFAIK. There are probably thousands of tracking bugs for features in Firefox alone and I don't know how many of them are represented anywhere on MDN at the moment.

I think it's a bit questionable how much help the link is tbh. The issue has been open for 6 years. It does appear like it's being actively worked on, but there's no guarantee it will land any time soon. I'm not sure how this information is going to be actionable for a developer.

But since it exists currently, would you like to file a PR against https://github.com/mdn/browser-compat-data to add a note like "See <a href='https://bugzil.la/1234567'>bug 1234567</a>."  into the BCD for this item? I appreciate it if you don't want to, I will take care of it in that case :).

**Comment by codedread** [comment]
Ok, I just submitted https://github.com/mdn/browser-compat-data/pull/14967 now

**Comment by wbamberg** [comment]
@codedread , since your PR to browser-compat-data was merged, would you like to update this PR to remove that note?

I think the updated compat table should start showing up in pages tomorrow. (@queengooborg , is it right that BCD still makes releases on Thursdays?)

**Comment by queengooborg** [comment]
More or less, though I've seen releases on Wednesdays lately -- either way, except for holidays, a BCD release usually happens every week!

**Comment by codedread** [comment]
@wbamberg I removed the note now that BCD has updated with the other change. LMK if I need to do something more here.

**Review by wbamberg — APPROVED** [review]
👍 looks good to me, @codedread , and your BCD note is showing up in the page now. Thank you!

**Pull request merged**
