### PR TITLE
Description fix

### PR DESCRIPTION
**Pull request by Konrud**
Description for `timeout property has been changed.

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
To me the original version is clearer, could you explain why you made this change?

In particular I like _and the callback has not already been called **by the time timeout milliseconds have passed**_ . Is this not correct, or was there another reason to change it?

**Comment by Konrud** [comment]
@wbamberg, you are probably right, but this redundant _time timeout milliseconds_ sounds quite confusing, well at least for me a non-native speaker.

Maybe we could retain the meaning but with a different approach like say: 
_...and the callback has not already been called by the defined `timeout`_. What do you think?

**Comment by wbamberg** [comment]
> @wbamberg, you are probably right, but this redundant **_time timeout milliseconds_** sounds quite confusing, well at least for me a non-native speaker.
> 

Oh yes, I can see that now. What do you think of:

> If the number of milliseconds represented by this parameter has elapsed and the callback has not already been called, then a task to execute the callback is queued in the event loop, even if doing so risks causing a negative performance impact. `timeout` must be a positive value or it is ignored.

?

**Comment by Konrud** [comment]
@wbamberg, changed it according to your suggestion. Thank you.

**Review by wbamberg — APPROVED** [review]
👍 thanks @Konrud !

**Pull request merged**
