### PR TITLE
Fix typo in image in “Native messaging” article

### LINKED ISSUE #4082: Content suggestion: Fix a typo of `runtime.connectExternal` in a native messaging image
## What is the new suggestion?

- Replace `connectExternal` with `connectNative` in [the native messaging image](https://github.com/mdn/content/blob/3d36450e504d7a31e73cb6667b90e69392ae8655/files/en-us/mozilla/add-ons/webextensions/native_messaging/native-messaging.png).

## Why is it important or useful?

It seems to be a typo of `connectNative` as there is no such API called `runtime.connectExternal` while we have `onConnectNative` and `onConnectExternal`.

It would be a few-minute fix and avoids confusion to developers.

## Other supporting information

- [The corresponding page on MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging)

### PR DESCRIPTION
**Pull request by Prometheus7-creator**
> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'
'Fixes #4082'

> What was wrong/why is this fix needed? (quick summary only)
There was typo error of connectNative()

> Anything else that could help us review it
Edited text in the image from connectExternal() to connectNative()

### CODE REVIEW

**Comment by sideshowbarker** [comment]
For the record here, this is the replacement image:

image

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Ansh, thanks much for fixing this, and congrats on landing your first docs change here — welcome aboard 🎉

**Comment by caitmuenster** [comment]
Yay, congrats @Prometheus7-creator! Hope to see you around the project. :)

**Comment by Prometheus7-creator** [comment]
Thanks for being helpful @caitmuenster! Looking forward to working with you again.

**Pull request merged**
