### PR TITLE
Itemize 0, -0, 0n, -0n separately in Falsy doc

### PR DESCRIPTION
**Pull request by sideshowbarker**
Related: https://github.com/mdn/content/issues/1309#issuecomment-770255687

### CODE REVIEW

**Comment by sorawee** [comment]
Well, `0n` and `-0n` are the same value (in the same way `0` and `0.0` are the same value). I don't think they should be in separated row.

**Comment by sideshowbarker** [comment]
> Well, `0n` and `-0n` are the same value (in the same way `0` and `0.0` are the same value). I don't think they should be in separated row.

OK, thanks — amended the commit to correct that part. Please take another look and let me know if it looks OK now.

**Comment by sorawee** [comment]
Yep, looks good now. Thanks! :)

**Comment by sideshowbarker** [comment]
> Yep, looks good now. Thanks! :)

Thanks for you review!

**Review by chrisdavidmills — APPROVED** [review]
LGTM, cheers @sideshowbarker !

**Pull request merged**
