### PR TITLE
Create Fix

### PR DESCRIPTION
**Pull request by jculver050**
files/en-us/web/javascript/reference/global_objects/array/splice/index.html

### CODE REVIEW

**Comment by sideshowbarker** [comment]
Closing the PR, as the patch it contains isn’t valid and can’t be merged.

Can you explain what you were attempting here?

**Comment by jculver050** [comment]
My lg stylo 6 someone was messing with the coding on it stilling my info
trying to find out how to set it back to stock coding

**Comment by jculver050** [comment]
Someone put a bunch of json strings and apis on phone and its fucking my
phone up

**Comment by chrisdavidmills** [comment]
> Someone put a bunch of json strings and apis on phone and its fucking my phone up

I know problems like this can be frustrating sometimes, but please can you refrain from swearing on our repos? We want our community to be as inclusive as possible, and it does put some people off. Thanks for listening.

**Comment by jculver050** [comment]
Yes sorry can you please help me fix this i.  Have a hard time
understanding what i read

**Pull request closed without merging**
