### PR TITLE
Fix note headings to use H4

### PR DESCRIPTION
**Pull request by hamishwillee**
This was in page on how to use correct style. I found it amusing :-)

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
hehe, nice find. I wonder if the recommendation with the heading is wrong, though. I don't think I've seen it used a lot this way. The bold **Note:** is more common. 

Examples from various content areas:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head
- https://developer.mozilla.org/en-US/docs/Web/CSS/border-image
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Keyed_collections#converting_between_array_and_set
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

**Comment by hamishwillee** [comment]
@Elchi3 Agree, it is as ugly as hell. I know that when I started. However I'm looking at this the same way I would if we had a macro - if you use a "standard way" everywhere then you can always fix up the rendering later. In fact, making it the same everywhere provides impetus for that to happen.

**Comment by Elchi3** [comment]
Yeah, makes sense and I'm all for making it consistent. 

Just wasn't sure if the standard (preferred) way is `<strong>Note</strong>: ` as implemented almost everywhere or if it is `<h4>Note</h4>`. 

Glad we're making a call here and this is something to give editors a heads-up about because I might get it wrong due to old habits that die hard 😄

**Review by chrisdavidmills — APPROVED** [review]
Yup, @hamishwillee is right here. We made this change to the structure for notes recently. I'm going to start a changelog document somewhere, to record updates to standard styling and process in case anyone is thinking "what, when did that change?"

**Pull request merged**
