### PR TITLE
Remove reference to bold text and specify malicious input directly

### PR DESCRIPTION
**Pull request by swap-10**
### Description

The article text mentions what a malicious user could do by specifying "the text in bold" for the input of a field. The article goes on to show the code block with no text in bold. My changes make the relevant part of the SQL code block bold

### Motivation

The article aims to show how malicious input text in a form field can be dangerous. But it isn't currently clear what part exactly is the malicious text. The article indicates that text to be present in bold but it isn't currently in bold.
My changes make the relevant part bold. This makes it clearer to understand how cleverly input text can trick the system without input sanitization, and be dangerous.

### CODE REVIEW

**Review by wbamberg — CHANGES_REQUESTED** [review]
Thank you for your PR, @swap-10 !

But I think we don't need to resort to HTML here. It would be better to avoid the reference to bold formatting, and directly quote the malicious text.

**Comment by swap-10** [comment]
> Thank you for your PR, @swap-10 !
> 
> But I think we don't need to resort to HTML here. It would be better to avoid the reference to bold formatting, and directly quote the malicious text.

That makes a lot of sense! I've made a commit with the suggested changes.
Thank you!

**Review by wbamberg — APPROVED** [review]
👍 thank you for the fix, @swap-10 !

**Comment by swap-10** [comment]
Happy to be of help!

**Pull request merged**
