### PR TITLE
Updates to Accessible Color

### PR DESCRIPTION
**Pull request by Myndex**
Clarified  some items, added a new infographic regarding color vision, and fixed/updated several links.

#### Summary
Clarified  some items, added a new infographic regarding color vision, and fixed/updated several links.

#### Motivation
Just updating the article I wrote last year, to fix/updte some links, status, and add a new helpful graphic.

#### Metadata

This PR…
-->
- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [X] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by Myndex** [comment]
> The workflow is complaining about the unoptimized SVG . You can optimize it in your local environment using command:
> 
> ```
> yarn filecheck "files/en-us/web/accessibility/understanding_colors_and_luminance/normalizedconeresponse.svg" --save-compression
> ```

HI @OnkarRuikar   Yes I saw that thank you, I compressed it and all seems to pass now!

**Comment by estelle** [comment]
Links are to author's pages.

**Comment by Myndex** [comment]
> Links are to author's pages.

A couple are, but I am happy to remove them if that's a problem?

**Comment by Myndex** [comment]
> Links are to author's pages.

Hi @estelle 
]
One is, but I am happy to remove them if that's a problem? The link is

**https://git.myndex.com** which is the github repo, and is a catalog of the open discussions regarding the Visual Contrast Research Group and APCA.

I am a co-author of WCAG 3, and some of the latest information is in the specific APCA repo, as is the continuing discussion.

**Comment by Myndex** [comment]
> Links are to author's pages.

Hi Estelle, I removed the link to the link list of resources & discussion for the WCAG 3 candidate contrast tool. Please let me know of other questions or issues.

**Review by teoli2003 — APPROVED** [review]
Thanks a lot for removing the link! Maintaining external links, or a list of links, is really a time-consuming activity for us. So we are becoming more and more strict about them. Having a link to an external list, how good it is, is even harder. 

That's why we are not keen on them.

Thanks a lot for the work, you improved the article significantly. I committed a small nit (an extraneous line) and I think we are good to go.

**Comment by Myndex** [comment]
Thank you Jean-Yves @teoli2003

> _Thanks a lot for removing the link! Maintaining external links, or a list of links, is really a time-consuming activity for us. So we are becoming more and more strict about them. Having a link to an external list, how good it is, is even harder._

Understood — I had included it as it's a list I am actively maintaining, and the depth of this material is quite dense, nevertheless, I understand... just trying to keep this article current, as some things at the W3 are changing in this area.

> _Thanks a lot for the work, you improved the article significantly._ 

Thank you, funny reading what I wrote a year ago, some things just leapt out at me as needing correction that I missed initially.

> _I committed a small nit (an extraneous line) and I think we are good to go._

Ooops, and I should probably take a closer look at your style guide as things are also now on markdown (which is brilliant by the way).

Thank you!

**Pull request merged**
