### PR TITLE
Use local fonts for font-variant-alternates

### PR DESCRIPTION
**Pull request by wbamberg**
Update https://developer.mozilla.org/en-US/docs/web/css/font-variant-alternates to use a local font, so we can make a live sample work.

This should be possible now https://github.com/mdn/yari/pull/7605 has landed.

Updates https://github.com/mdn/content/pull/21597.

### CODE REVIEW

**Comment by caugner** [comment]
@wbamberg We only support `woff2`, not `woff`. Can we use the [woff2 version of MonteCarlo](https://github.com/googlefonts/monte-carlo/blob/master/fonts/webfonts/MonteCarlo-Regular.woff2)?

**Comment by wbamberg** [comment]
It works! Thank you @caugner ! @Elchi3 , we have a live sample for `font-variant-alternates` now!

**Review by dipikabh — APPROVED** [review]
Thank you 👍

**Comment by drott** [comment]
@wbamberg , thanks very much for following up, great to see this working in the preview link! https://pr27206.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/font-variant-alternates - Out of curiosity: when does this roll to public MDN?

**Comment by wbamberg** [comment]
Ah, thank you for the investigation, @caugner ! -> https://github.com/mdn/content/pull/27277

**Comment by wbamberg** [comment]
@drott , am I right in thinking that in the CSS for the example:

```css
.variant {
  font-feature-settings: "swsh" 1;
  font-variant-alternates: swash(fancy);
}
```

...the first part `font-feature-settings: "swsh" 1;` is not needed: that in fact the two lines are alternative ways of doing the same thing, and the point of `font-variant-alternates` is that it offers a less low-level way to do it, and should be preferred (as described in the first paragraph of http://localhost:5042/en-US/docs/Web/CSS/font-feature-settings#syntax, after the example)?

So we should remove the first line from this example?

**Comment by wbamberg** [comment]
Or even, include both versions, but in different rules:

```css
.variant1 {
  font-feature-settings: "swsh" 1;
}

.variant2 {
  font-variant-alternates: swash(fancy);
}
```

**Pull request merged**
