### PR TITLE
Fix broken links for drag-and-drop events

### PR DESCRIPTION
**Pull request by teoli2003**
We already did this for the `drag` event in #30615.

Applying the same resolution to the other drag-and-drop events.

### CODE REVIEW

**Comment by bsmth** [comment]
Does it make sense to add the same note about bubbling / other nodes? 

https://github.com/mdn/content/pull/30615/files#diff-2d7a7b6b215f864c8492208bc256d5c64f4036d0083de9971a299eb213ec8effR13

**Review by chrisdavidmills — APPROVED** [review]
@teoli2003 LGTM, pending any action you might take in response to @bsmth's [comment](https://github.com/mdn/content/pull/30680#issuecomment-1835691139). I'll approve but not merge, so you can make the change if you agree, before merging. Otherwise feel free to just merge.

**Comment by teoli2003** [comment]
I will add the notes.

**Comment by teoli2003** [comment]
As I made additional grammar change, requesting a review by bsmth.

**Review by bsmth — APPROVED** [review]
Looks good, thank you 👍🏻

**Pull request merged**
