### PR TITLE
Add example of acquiring RadioNodeList instance

### LINKED ISSUE #11476: RadioNodeList - Missing an example
#### What information was incorrect, unhelpful, or incomplete?

From the actual [browser-compat-data of the english page](https://developer.mozilla.org/en-US/docs/Web/API/RadioNodeList), it seems RadioNodeList is supported on IE, but after a bug I faced, I've made some tests which demonstrate that it isn't.

#### What did you expect to see?

I expect to see IE not supporting the RadioNodeList api.

#### Did you test this? If so, how?

We faced a bug when checking with `instanceof RadioNodeList` which throw `RadioNodeList is undefined`.

I then tested it by running in IE11's console `typeof RadioNodeList === 'undefined'` which returns `true`.

Is there really a mistake in the doc or did I misunderstand the support table and it's not related to that?

<details>
<summary>MDN page report details</summary>

* Query: `api.RadioNodeList`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RadioNodeList
* Report started: 2021-07-21T11:21:08.558Z

</details>

### PR DESCRIPTION
**Pull request by Josh-Cena**
Fix https://github.com/mdn/content/issues/11476

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
I don't think this is a helpful example to add. How is this a thing web developers are going to want to do? If we do want to have an example it would be better to have an example showing the intended use, which is AFAICT accessing the checked radio button value.

I also think, for web developers, rather than "It is not exposed as a global." it would be better to say something like "You can't construct a `RadioNodeList`, but an instance of it is returned by `HTMLFormControlsCollection.namedItem()`".

(and I think some text like that would be a totally adequate fix for the issue, if any fix is needed at all)

**Comment by Josh-Cena** [comment]
@wbamberg The linked issue is specifically confused because they  are not aware that it doesn't exist as a global. OTOH, most DOM interfaces are not constructable.

**Comment by wbamberg** [comment]
Regarding the linked issue:

> We faced a bug when checking with instanceof RadioNodeList which throw RadioNodeList is undefined.
>
> I then tested it by running in IE11's console typeof RadioNodeList === 'undefined' which returns true.

I don't know about IE, but this isn't what I'm seeing in Chrome or Firefox:

```js
const form = document.createElement("form");
for (let i = 0; i < 3; i++) {
	const input = document.createElement("input");
	input.value = i;
	input.type = "radio";
	input.name = "radio";
	form.appendChild(input);
}
const instance = form.elements.namedItem("radio");
console.log(instance instanceof RadioNodeList); // true
```

**Comment by Josh-Cena** [comment]
Hmmm, thanks for being so careful. Apparently it was exposed in https://github.com/whatwg/html/pull/3009, so modern browsers have it but not IE.

Maybe no action is necessary since we don't document IE anyway.

**Pull request closed without merging**
