### PR TITLE
notranslate classes have been removed from pre elements

### PR DESCRIPTION
**Pull request by rvigil24**

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
@dk-github-acc Heads up! There seem to be an open PR for https://github.com/mdn/content/issues/1822 already :-(

**Comment by rvigil24** [comment]
Sorry, my mistake! :(

**Comment by Ryuno-Ki** [comment]
Don't worry. I defer to @Elchi3 for reviewing this.
I should have checked for open PRs before assigning the ticket.

Would have helped if you would reference the issue this PR is resolving :-)
We've got it now.

**Review by Elchi3 — APPROVED** [review]
Thanks a lot and welcome to mdn/content 🎉

**Pull request merged**
