### PR TITLE
appinstalled_event: Remove deprecation header.

### PR DESCRIPTION
**Pull request by jpmedley**
#### Summary
Remove deprecation event.

#### Motivation
This event is not deprecated. It changed specs.

#### Supporting details
https://wicg.github.io/manifest-incubations/#extensions-to-the-window-object

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @jpmedley Fair enough. Seems like this is also true for beforeinstallprompt event, which was removed from BCD at the same time: https://github.com/mdn/browser-compat-data/pull/5960

Happy to merge this but consider BCD the "master" of this information. Are you planning on updating https://github.com/mdn/browser-compat-data/blob/main/api/Window.json#L532 as well - and perhaps linking the new spec?

**Comment by jpmedley** [comment]
https://github.com/mdn/browser-compat-data/pull/13829

**Comment by hamishwillee** [comment]
Thanks, can you please update these too:
- https://developer.mozilla.org/en-US/docs/Web/API/Window/onappinstalled
- https://developer.mozilla.org/en-US/docs/Web/API/Window#event_handlers (top level inline deprecated)

Looks like BCD will take a big. I'm happy to merge this once the other ones are done.

**Comment by jpmedley** [comment]
Done. Please look again.

**Review by hamishwillee — APPROVED** [review]
Thanks @jpmedley

**Pull request merged**
