### PR TITLE
Refactor using pointer events example

### LINKED ISSUE #34904: Pointer Events incoherence
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Using_Pointer_Events

### What specific section or headline is this issue about?

Tracking new touches

### What information was incorrect, unhelpful, or incomplete?

https://github.com/mdn/content/blob/main/files/en-us/web/api/pointer_events/using_pointer_events/index.md?plain=1#L73-L88

### What did you expect to see?

variable `i` is not defined, `touches` is not defined I think it should be `ongoingTouches` as for `i` I'm not sure 

Happy to do a pull request but I don't know about `i` would probably be replaced by 
```js
  const idx = ongoingTouchIndexById(evt.pointerId);
```

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by erwanvivien**
### Description

Tries to fix #34904

### CODE REVIEW

**Comment by Josh-Cena** [comment]
@erwanvivien Hi, are you going to keep working on this?

**Comment by erwanvivien** [comment]
Hey @Josh-Cena happy to. I left comments here: https://github.com/mdn/content/issues/34904

Basically saying that I'm not sure how to interleave explanations and code

**Comment by Josh-Cena** [comment]
Are you unsure about editorial conventions or just what explanation to put down in general? Unfortunately I don't think the reviewers can help you much on writing out all the English without us actually doing it for you—but if you think that's necessary, you can definitely say so and one of the maintainers could take it over.

**Comment by erwanvivien** [comment]
> just what explanation to put down in general

I think that would probably be that, in fact I think the previous explanations were kind of redundant with the code. That said I don't know who's the target of such page, is that experimented programmers?

> one of the the maintainers could take it over

I'd appreciate that 🙏

**Comment by Josh-Cena** [comment]
> That said I don't know who's the target of such page, is that experimented programmers?

That usually depends on the advancedness of the API itself. For example you can usually assume people reading about `Proxy` are experienced with JavaScript and people reading about WebGL is experienced with programming (but not necessarily JS). For this one, some level of familiarity with web APIs and JS is expected.

**Comment by Josh-Cena** [comment]
I looked at the code. It's big enough that we need to split them into chunks and explain each one. Remember that we are on a guide page anyway, so we need to explain how we arrive at each step. Code here is for demonstration, not for copy/pasting into your own application without knowing how it works.

**Review by Josh-Cena — APPROVED** [review]
I made some refactors and little fixes. Our code is no longer consistent with the `dom-examples` repo and we self-host this live example anyway, so I've removed the links to that. Thanks for the PR!

**Comment by erwanvivien** [comment]
@Josh-Cena thanks for pushing this to the finish line! I was in vacation, sorry for the late reply!

**Pull request merged**
