### PR TITLE
Update binocular-vision.svg

### LINKED ISSUE #30516: FOV graphic should use different angles for the view cones of each eye
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Fundamentals

### What specific section or headline is this issue about?

Field of View

### What information was incorrect, unhelpful, or incomplete?

I was confused for a second because the image with the head and the two view cones for the eyes are simply translated but not rotated. 

"A human eye is able to take in a FOV of around 135°. Assuming a person has two healthy eyes, the total field of view ends up being about 200° to 220° wide. Why is the FOV wider with two eyes, but not double the single-eye FOV? It's because the two eyes' FOVs overlap a lot."

### What did you expect to see?

in the image, the cones should be slightly rotated away from each other. 

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

If you agree this would be useful, I can do it!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webxr_device_api/fundamentals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Fundamentals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webxr_device_api/fundamentals/index.md
* Last commit: https://github.com/mdn/content/commit/4f0f7386262363103a3e9cf482bb348d8570b331
* Document last modified: 2023-02-19T08:44:25.000Z

</details>

### PR DESCRIPTION
**Pull request by felixniemeyer**
### Description
This PR updates the binocular-vision graphics on the webxr fundamentals. 

### Motivation

I was confused when reading the article and trying to bring together the information from the text (single FOV 135, total FOV 200...)  and the previous graphic. I like mdn docs and I'm happy to help improving it. 

I think readers can grasp the information from the webxr fundamentals page better with the updated graphics. 

### Related issues and pull requests

Fixes #30516

### CODE REVIEW

**Comment by felixniemeyer** [comment]
@zfox23, you [asked me to set you as a reviewer](https://github.com/mdn/content/issues/30516#issuecomment-1853796581) but I missed an option to do so during creating the pull request and I cant find a way to do it now other than mentioning you in this post! :relaxed:

**Comment by bsmth** [comment]
> I cant find a way to do it now other than mentioning you in this post!

I've just added Zach as a reviewer now 👍🏻 I see CI is failing, would you like me to run a fix for this for you?

**Comment by felixniemeyer** [comment]
I already had cloned it to see how it looks ;) 
Thanks for explaining the context about svg optimization. 
I ran your proposed `yarn filecheck ...` command and now the svg is somewhat minimized, just one line, like the replaced file. 
Is it correct like this?

**Review by zfox23 — APPROVED** [review]

**Comment by zfox23** [comment]
> I already had cloned it to see how it looks ;) Thanks for explaining the context about svg optimization. I ran your proposed `yarn filecheck ...` command and now the svg is somewhat minimized, just one line, like the replaced file. Is it correct like this?

Yes, this is correct! Excellent graphical improvement and contribution. Thank you for your help, and for the fun discussion on https://github.com/mdn/content/issues/30516. I look forward to your future contributions.

And thank you @bsmth for stepping in above 😄

**Comment by bsmth** [comment]
Thanks both 🎉

**Pull request merged**
