### PR TITLE
fix: Typos in file/en-us/game folder

### PR DESCRIPTION
**Pull request by nschonni**
Fixed related spelling issues when the same misspelling was found outside the `game` folder through find/replace

### CODE REVIEW

**Comment by sideshowbarker** [comment]
Might be good to re-title this PR — since there are changes in trees other than just in the file/en-us/game tree (which is fine of course, assuming it’s intentional — that you didn’t intend to restrict this to just the file/en-us/game, despite the title…)

**Comment by nschonni** [comment]
@sideshowbarker yeah, I was running cSpell on the games folder, but did find/replace the fixes outside the folder when I got hits

**Review by vkWeb — APPROVED** [review]
Now I'm a fan of cspell. :100: 

LGTM @nschonni.

**Review by chrisdavidmills — APPROVED** [review]
Brilliant fix ;-)

I love the mass copy and paste "milliseconds" error ;-)

**Pull request merged**
