### PR TITLE
fixed issue #1899

### PR DESCRIPTION
**Pull request by ghost**
Checked by me :

- [x] original content
- [x] original example
- [x] no copy paste
- [x] all links working

### CODE REVIEW

**Comment by ericwbailey** [comment]
@Aayushap1 I noticed you removed @mdn/yari-content and specifically requested me as a reviewer. Given your prior efforts to contribute to this project, I am wondering why you did that. Could you please provide more context?

**Comment by Aayushap1** [comment]
Wait, I just sent a PR to MDN and not specifically mention you to review my code.
All these things have happened automatically.

**Comment by ericwbailey** [comment]
This is what I'm seeing:

Aayushap1 requested review from ericwbailey and removed request for mdn/yari-content-html 4 hours ago.

**Comment by Aayushap1** [comment]
It had happened with me in all of my PR's

**Comment by Aayushap1** [comment]
you can see #2077

**Comment by ericwbailey** [comment]
Ah, gotcha. I'll review this in a bit, then.

**Comment by Aayushap1** [comment]
Please review

**Comment by chrisdavidmills** [comment]
@Aayushap1 I suspect that you ought to revisit this work again, given some of the comments I posted yesterday (see https://github.com/mdn/content/issues/1476#issuecomment-776194108).

**Comment by Aayushap1** [comment]
First check PR #2150  then comment

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills First check PR #2150 then comment

Ummmm, this is PR 1250?

**Comment by Aayushap1** [comment]
I am talking about 2150 this one in which we are talking.

**Comment by Ryuno-Ki** [comment]
@Aayushap1 I assume, Chris is confused, because your words could be interpreted as „Go to PR 2150 [where you are already] and then comment”. Instead, it would help to get pointed to #1899 (the issue this PR tries to resolve).

A review includes the commenting of files if necessary.

**Comment by ericwbailey** [comment]
@Aayushap1 I know you've been told this before, but I would like to re-stress that many MDN contributors are working full-time in addition to conducting their duties here. This includes me.

I know that you are excited to participate in this project, but it is considered rude to bump things this way. I'd ask that you have a little empathy—I haven't forgotten this work, but I'm also balancing work, quarantine, and other obligations.

**Comment by Aayushap1** [comment]
sir, I am not saying that I am not able manage my time.
The main thing that I want to tell you is :
From past days I observed that @rachelandrew don't want me to contribute to MDN and I don't know why???
The first PR that I have send that was having a mistake. But I fixed them and sent a new PR that was rejected because most of content (not whole content) was copy-paste. 

Then @chrisdavidmills told me how to write content and I can't copy paste but I can reword the content.
link of message(comment): https://github.com/mdn/content/issues/1712#issuecomment-772745250
Point 1 last second sentence by @chrisdavidmills  "Generally I would say that you are welcome to use other sites as information sources, as long as you rewrite the content in your own words." Okay no problem till this point.

**Problem start now,**
After that I researched content on W3C, W3School, GeekforGeek and Whatwg  and sent a new PR #2070  that was reviewed by Rachel and she closed that PR also by saying that I have just reworded the content. 
But sir I can't change the defination and usage of the any attribute : "I can't async is attribute for form not for script."  How it works. In which case we should use it these thing will remain same I can just reword them and give explaination of example in my own language.

So I request @Ryuno-Ki @chrisdavidmills @ericwbailey please review my PR #2150 (In which we are talking) and PR #2145 .In place of @rachelandrew.

**Comment by chrisdavidmills** [comment]
OK, so it looks like you've had another go at this one. I'll review this as well.

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
# async feedback

OK, so the async page is now looking somewhat better in terms of plagiarism. Let's not talk about that any more, and give you some feedback.

## General feedback

* In general there seem to be a lot of spelling mistakes in the page. You ought to run your content through a spell checker before uploading it.
* Your notes are not marked up correctly. See https://developer.mozilla.org/en-US/docs/MDN/Guidelines/CSS_style_guide#.note.notecard for a guide on how to mark up notes.
* You have all instances of "async" bolded in the article. You don't need to do this. The general best practice is to bold the first instance of an important term in an article. So you should go with that.

## Specific feedback

### 1

The following bit is somewhat repetitive:

```
<p>The <strong><code>async</code></strong> attribute is a boolean type of attribute which indcates browser how script should be executed.</p>

<p>The <strong><code>async</code></strong> attribute is an allowed attribute for {{htmlelement("script")}}. When used on a <code>&lt;script&gt;</code> element,
the script will be executed automatically without clicking on any button, with loading of page.</p>
```

It is also kind of missing the point — `async` means that the script will be downloaded without blocking page load, and will execute as soon as it is available. See [this section](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript#script_loading_strategies) for more useful details.

You could probably lose the first line and just go with something simple like

```
<p><strong><code>async</code></strong> is a boolean attribute that can be set on the {{htmlelement("script")}} element, only when used to load an external script file. When `async` is used, the script will be downloaded without blocking page load, and will execute as soon as it is available.</p>
```

### 2

The "Usage" section seems repetitive — You can probably just delete the heading and the first line underneath it.

This line is useful:

```
<p><b>Note</b>: Use the <strong><code>async</code></strong> attribute only when script is external file and linked to web page by using <code>src</code> attribute.</p>
```

But it is not very clear, and the grammar is untidy. I dealt with this point in my above paragraph suggestion. So you can probably delete this note too

### 3

The example you've included misses the point — using modern loading strategies like sync and defer means that you can put all your script tags in the head of the page, and don't need to include them at bottom of your HTML.

The form seems like a distraction, and you'd realistically never include a script file with just a single `alert()` statement in it to load this this. You'd just such information in your HTML. Have a think about the sort of script you'd realistically load using the async strategy. Maybe some kind of data that isn't essential for the DOM display, but you just want it loaded as soon as possible without stalling the HTML loading, to improve performance.

It doesn't have to be a really in-depth working example. To be honest, you probably don't need to show the contents of the script file, just describe the way it is used.

https://flaviocopes.com/javascript-async-defer/#async-and-defer is pretty helpful for understanding these attributes better.

### 4

This line:

```
<p>See examples of usage on the element pages for {{htmlelement("script")}}.</p>
```

Doesn't make any sense. There are no examples of using `async` on the `<script>`  page.

### 5

The "Try this yourself" section doesn't make sense on this page — we don't usually have that kind of section on a reference page, and the content isn't really very helpful.

The description list is also missing a closing tag, which is causing this bit to not display properly. I have to ask again, did you actually run this locally and check it before you submitted the pull request?

I'd just delete this bit, to be honest.

# defer feedback

A lot of the problems talked about above exist in the `defer` page too. I'd like you to have a go at fixing up the `async` page first, and then think about applying those fixes to `defer` too.

**Comment by sideshowbarker** [comment]
@Aayushap1 Do you plan in finishing up this PR?

**Comment by sideshowbarker** [comment]
Closing for lack of response.

**Comment by sideshowbarker** [comment]
@Aayushap1 If you decide to continue work on this, it can be reopened

**Pull request closed without merging**
