### PR TITLE
Typo - non conformity with other explanations

### PR DESCRIPTION
**Pull request by olawanlejoel**
> What was wrong/why is this fix needed? (quick summary only)

It's just a basic typo that doesn't conform with the other explanations.

> Issue number (if there is an associated issue)

> Anything else that could help us review it

### CODE REVIEW

**Review by teoli2003 — CHANGES_REQUESTED** [review]
Good catch. But I would do the opposite, adding the missing _s_ to the other entries (41, 43 and 47)

**Comment by olawanlejoel** [comment]
Oh great,  didn’t think of that. That is far better and makes more sense.

**Review by teoli2003 — APPROVED** [review]

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here!

**Comment by olawanlejoel** [comment]
Thanks so much.

**Pull request merged**
