### PR TITLE
Adding Firefox State Partitioning documentation

### PR DESCRIPTION
**Pull request by Trikolon**
This un-archives the Firefox privacy page and adds new documentation for State Partitioning in Firefox.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Hi there @Trikolon ! Sorry for taking so long to get back to you about this.

I'm afraid unarchiving content isn't quite a simple as just copying it back over into the `content` repo. There's actually a tool that lives in the `yari` repo that handles sorting out the plumbing for a unarchive. I wrote a guide to using it here: https://github.com/mdn/yari/blob/master/docs/unarchiving.md

I'm happy to help with the unarchiving bit if you'd like, and then you could just worry about putting the new content on top of it?

**Comment by Trikolon** [comment]
Sorry I missed that unarchiving doc somehow.

> I'm happy to help with the unarchiving bit if you'd like, and then you could just worry about putting the new content on top of it?

That would be great! I haven't modified the privacy page so it should be fairly straightforward. Thanks!

**Comment by Trikolon** [comment]
@chrisdavidmills I've unarchived the privacy section and rebased the changes on top of that.
We also want to unarchive the other anti-tracking pages in "privacy", so I took this opportunity to do that. Let me know if this works for you.

**Review by chrisdavidmills — APPROVED** [review]
Tested this locally, and it works. Thanks @Trikolon !

**Pull request merged**
