### PR TITLE
Migrate kumascript jsondata to content repo

### PR DESCRIPTION
**Pull request by peterbe**
This is the company of https://github.com/mdn/yari/pull/4081

### CODE REVIEW

**Comment by teoli2003** [comment]
Should we merge this so we can start modifying these files here? Even if they won't be used until the yari's PR land?

**Comment by peterbe** [comment]
I think so. 
The next action item is actually:
1. A refresh of https://github.com/mdn/yari/pull/4081 (to prove the tests pass)
2. @escattone to review https://github.com/mdn/yari/pull/4081

@escattone If you think we can get around to the yari side of this within days, I think we can go ahead with this here PR. In fact, then the content folks can start actually sending PRs to these even if it's a bit delayed till it actually appears in production builds.

**Comment by escattone** [comment]
@peterbe Yes, sounds good to me!

**Comment by peterbe** [comment]
> @peterbe Yes, sounds good to me!

So, mergy merge?

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
