### PR TITLE
Update View Form data section on Browser Dev Tools

### LINKED ISSUE #33729: To view Form data on Chrome Dev Tools no longer under Headers tab, but under the new Payload tab
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data

### What specific section or headline is this issue about?

On the client side: defining how to send the data

### What information was incorrect, unhelpful, or incomplete?

Under the section [Viewing HTTP requests](https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data#viewing_http_requests), the directions on how to view the form data on Chrome Dev Tools instructed that the Form data can be viewed unders the Headers tab.  

### What did you expect to see?

I'm using Chrome browser - _**Version 124.0.6367.210 (Official Build) (64-bit)**_ and the Form data isn't under the headers tab but under the new **Payload** tab:
Chrome Dev Tools screenshot

### Do you have any supporting links, references, or citations?

Update your chrome browser and try to view the form data as directed in the article.

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/sending_and_retrieving_form_data`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/sending_and_retrieving_form_data/index.md
* Last commit: https://github.com/mdn/content/commit/9087a17d60546adb8806da3b7c575b6adb8aebd1
* Document last modified: 2024-03-15T12:24:46.000Z

</details>

### PR DESCRIPTION
**Pull request by ragul1697**
### Description
Fixes #33729 for viewing the form data in a browser network tab.

### CODE REVIEW

**Comment by Josh-Cena** [comment]
@ragul1697 FYI since you've made a few PRs already: you need to use the substring "fixes #xxx" in your description, no text like "the issue" in between. Otherwise GitHub won't link your PR to that issue and autoclose that issue.

**Comment by hamishwillee** [comment]
@ragul1697 Can you please also update the image that follows this text (i..e after "You can then get the form data, as shown in the image below."). That doesn't match the text now.

**Review by hamishwillee — CHANGES_REQUESTED** [review]
@ragul1697 Can you please also update the image that follows this text (i..e after "You can then get the form data, as shown in the image below."). That doesn't match the text now.

**Review by hamishwillee — APPROVED** [review]
Thanks very much for sorting this out @ragul1697 !

**Comment by onyedikachi23** [comment]
Took some months after I reported the issues before it was fixed.

At least now, new visitors to the article won't get confused.

**Pull request merged**
