### PR TITLE
up-to-date check script

### PR DESCRIPTION
**Pull request by peterbe**
Gets in your face that you haven't run `yarn install` in too long a time. 
Screen Shot 2021-01-08 at 9 23 17 AM

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
Suggested edit:

The installed version of Yari (0.1.458) is older than the version referenced in package.json (0.1.469). Please make sure your `main` git branch is up-to-date with https://github.com/mdn/content/, then run `yarn install` to install the latest Yari.

I wanted to tidy the message up a bit, be precise as to what we mean, and also make sure the instructions are in a logical order.

**Comment by peterbe** [comment]
@chrisdavidmills I took your edit/suggestion verbatim and put it.

**Comment by peterbe** [comment]
@fiji-flo ping. Can you take a look at the code changes whilst Chris is pondering the updated prose.

**Review by chrisdavidmills — APPROVED** [review]
Lookin' good, @peterbe !

**Review by fiji-flo — APPROVED** [review]
does the trick

**Comment by BezRegi** [comment]
https://github.com/tree-sitter

**Pull request merged**
