### PR TITLE
fix(js): fix the comment of CSSStyleDeclaration

### PR DESCRIPTION
**Pull request by heyongqi02bot**
### Description

In the comments, CSSStyleDeclaration was written as CSStyleDeclaration.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by teoli2003** [comment]
Thanks a lot!

This PR looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! ✌️

**Comment by xxhls** [comment]
Thanks

**Comment by skyclouds2001** [comment]
The issue also existed in `SVGElement.style` and `MathMLElement.style`

**Pull request merged**
