### PR TITLE
No comments necessary

### PR DESCRIPTION
**Pull request by fwqaaq**

### CODE REVIEW

**Comment by Josh-Cena** [comment]
There are a lot of occurrences of these comments in the `Intl` docs. If you want to remove it you need to remove them all; I personally don't mind the comment as it helps new contributors and is a net benefit.

**Comment by fwqaaq** [comment]
> There are a lot of occurrences of these comments in the `Intl` docs. If you want to remove it you need to remove them all; I personally don't mind the comment as it helps new contributors and is a net benefit.

Maybe, @yin1999 is it necessary to add these comments? While it's useless for the readers, it doesn't seem to be useful for contributors either. Maybe the localization process deletes it?

**Comment by fwqaaq** [comment]
> There are a lot of occurrences of these comments in the `Intl` docs. If you want to remove it you need to remove them all; I personally don't mind the comment as it helps new contributors and is a net benefit.

I don't quite understand why these comments are only added in the intl docs

**Comment by Josh-Cena** [comment]
It has been there since before GitHub, so we may never know 😄 It used to be an actual hidden div. See https://github.com/mdn/content/pull/881

**Comment by yin1999** [comment]
> Maybe the localization process deletes it?

It seems that we added them when we were on kuma. When I deal with markdown convertion for l10n-zh docs, I've found much more comments like this, but they are not in mdn/content.

Additional idea: if we want to keep them, is it a better idea to add the note to [macro](https://github.com/mdn/yari/blob/546337ed1031aba9dfcaa12f2674a96ec1ccb26a/kumascript/macros/EmbedInteractiveExample.ejs). Just like [compat macro](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Compatibility_tables#compatibility_table_example).

image

**Comment by fwqaaq** [comment]
> Additional idea: if we want to keep them, is it a better idea to add the note to [macro](https://github.com/mdn/yari/blob/546337ed1031aba9dfcaa12f2674a96ec1ccb26a/kumascript/macros/EmbedInteractiveExample.ejs)? Just like [compat macro](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Compatibility_tables#compatibility_table_example).

But if you use the macro, then these comments will not appear in the body. It has little effect unless we go head and explain this macros in the mdn docs.

> it helps new contributors and is a net benefit.

**Comment by yin1999** [comment]
> > Additional idea: if we want to keep them, is it a better idea to add the note to [macro](https://github.com/mdn/yari/blob/546337ed1031aba9dfcaa12f2674a96ec1ccb26a/kumascript/macros/EmbedInteractiveExample.ejs)? Just like [compat macro](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Compatibility_tables#compatibility_table_example).
> 
> But if you use the macro, then these comments will not appear in the body. It has little effect unless we go head and explain this macros in the mdn docs.
> 
> > it helps new contributors and is a net benefit.

There are a lot of EmbedInteractiveExample macros in content and translated-content. If we added them in content, we have to spend much time to "maintain" them. And for l10n, some we may have many different translations for a single locale.

IMO, this is about "how to contribute", they should be placed in writing guidelines (see below), rather than here.

- https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples#interactive_example_demo
- https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Our_repositories

**Comment by fwqaaq** [comment]
You use a macro to wrap a comment, but this comment is for EmbedInteractiveExample macros, and you will not see this comments in the body, so it is better to explain the EmbedInteractiveExample macro directly in `how to contribute`.

**Review by teoli2003 — APPROVED** [review]

**Pull request merged**
