### PR TITLE
fix(web/api): mention charset in the demo

### PR DESCRIPTION
**Pull request by OnkarRuikar**
It is not easy to realise that charset can also be mentioned in the constructor options. It is trivial but very important setting.

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
Personally I am not sure that on balance it’s helpful to users in 2024 to point out that they can specify a charset there. They should just always be using UTF-8, which is what it will default to if they don’t manually specify it. They should never need to specify any other character encoding, as far as I can see.

All that said, I don’t feel very strongly about it and would not object to it being merged — I’m just not enthusiastic about being the one to push the merge button on it.

So you probably want to ask another reviewer to review and merge this one.

**Comment by OnkarRuikar** [comment]
> They should just always be using UTF-8, which is what it will default to if they don’t manually specify it. They should never need to specify any other character encoding, as far as I can see.

Not sure if the encoding always defaults to UTF-8. Making this change considering this StackOverflow answer: https://stackoverflow.com/a/78506250/15273968

**Comment by sideshowbarker** [comment]
> > They should just always be using UTF-8, which is what it will default to if they don’t manually specify it. They should never need to specify any other character encoding, as far as I can see.
> 
> Not sure if the encoding always defaults to UTF-8. Suggesting this change considering this StackOverflow answer: [stackoverflow.com/a/78506250/15273968](https://stackoverflow.com/a/78506250/15273968)

Yeah, I don’t know whether that answer is actually correct. It may well be, but I’m not familiar enough with the soec requirements to know. So it may be worthwhile to seek out some specific technical review — for example, from one of the spec editors, or from someone else who’s done technical review for us in the past on any related patches/PRs.

**Comment by OnkarRuikar** [comment]
Closing as it would be redundant in most cases.

**Pull request closed without merging**
