### PR TITLE
Add aria roles technical summary

### LINKED ISSUE #22699: Show *Implicit ARIA Role* on each `<input type="*">` page
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

### What specific section or headline is this issue about?

/Web/HTML/Element/input/*

### What information was incorrect, unhelpful, or incomplete?

The `<input type="*">` pages are missing information about their implied ARIA role. 

The implicit ARIA roles are described on the `<input>` page, which is good. Unfortunately, if a reader doesn't think to go up a level from the type pages, they won't have access to this information.

### What did you expect to see?

There's a table on each input type page. I expect implied ARIA role to be one of those rows.

<table class="properties">
  <tbody>
    <tr>
      <td><strong><a href="#value">Value</a></strong></td>
      <td>
        A string representing the value contained in
        the search field.
      </td>
    </tr>
    <tr>
      <td><strong>Events</strong></td>
      <td>
        {{domxref("HTMLElement/change_event", "change")}} and
        {{domxref("HTMLElement/input_event", "input")}}
      </td>
    </tr>
    <tr>
      <td><strong>Supported Common Attributes</strong></td>
      <td>
        {{htmlattrxref("autocomplete", "input")}},
        {{htmlattrxref("list", "input")}},
        {{htmlattrxref("maxlength", "input")}},
        {{htmlattrxref("minlength", "input")}},
        {{htmlattrxref("pattern", "input")}},
        {{htmlattrxref("placeholder", "input")}},
        {{htmlattrxref("required", "input")}},
        {{htmlattrxref("size", "input")}}.
      </td>
    </tr>
    <tr>
      <td><strong>IDL attributes</strong></td>
      <td><code>value</code></td>
    </tr>    
    <tr>
      <td><strong>Implicit ARIA roles</strong></td>
      <td>
            <ul>
              <li>
                with no <code>list</code> attribute: {{ARIARole("searchbox")}}
              </li>
              <li>
                with <code>list</code> attribute:{{ARIARole("combobox")}}
              </li>
            </ul>
      </td>
    </tr>
    <tr>
      <td><strong>DOM interface</strong></td>
      <td><p>{{domxref("HTMLInputElement")}}</p></td>
    </tr>
    <tr>
      <td><strong>Methods</strong></td>
      <td>
        {{domxref("HTMLInputElement.select", "select()")}},
        {{domxref("HTMLInputElement.setRangeText", "setRangeText()")}},
        {{domxref("HTMLInputElement.setSelectionRange", "setSelectionRange()")}}.
      </td>
    </tr>
  </tbody>
</table>

### Do you have any supporting links, references, or citations?

[Input page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input)
[Example Input Type page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search) (one of many)

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/index.md
* Last commit: https://github.com/mdn/content/commit/8e16e19d3ee35157c81b299c0ccb9d5effd2ac22
* Document last modified: 2022-11-26T11:30:26.000Z

</details>

### PR DESCRIPTION
**Pull request by dawei-wang**
Fixes https://github.com/mdn/content/issues/22699

### CODE REVIEW

**Comment by Josh-Cena** [comment]
FWIW, the format changes are making the PR harder to review, since it's already a multi-page update.

**Comment by dawei-wang** [comment]
@Josh-Cena Thanks for reviewing this PR. The formatting changes are generated by Prettier. I only added the Implicit Aria Roles table entries. I can submit this change in multiple PRs then. What do you think?

**Comment by Josh-Cena** [comment]
Yes, I suggest doing Prettier changes in a separate PR.

**Comment by dawei-wang** [comment]
Submitted new PR without Prettier changes so closing this one

**Pull request closed without merging**
