### PR TITLE
Advanced form styling issues apply only to earlier browsers

### PR DESCRIPTION
**Pull request by MohitMaheshwari1711**
### Description

This PR updates the content for styling the select and datalists elements capabilities around the different browsers. The mentioned issue was a problem for past browsers and does not apply to today's browsers. However, to keep the content around it updated, I have added a note around it.

### Motivation

Correctness of the doc so that it helps other fellow members of the community

### Related issues and pull requests

Issue :- [#26182](https://github.com/mdn/content/issues/26182)

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @MohitMaheshwari1711 

I think this page reflects the situation from more than 2 years ago. It probably should be rewritten entirely, such that it reflects how things are in the current browser set. Then you might just have a note _like_

> In older browsers styling applied to the select was not also applied to options. You can work around this ...

Upshot, this is kind of like applying a bandaid to a severed leg :-0. It's good, but not going to sort the whole problem. Given how out of date this is, do you think you could update at least this section, and possibly the page?

**Comment by MohitMaheshwari1711** [comment]
> Thanks @MohitMaheshwari1711
> 
> I think this page reflects the situation from more than 2 years ago. It probably should be rewritten entirely, such that it reflects how things are in the current browser set. Then you might just have a note _like_
> 
> > In older browsers styling applied to the select was not also applied to options. You can work around this ...
> 
> Upshot, this is kind of like applying a bandaid to a severed leg :-0. It's good, but not going to sort the whole problem. Given how out of date this is, do you think you could update at least this section, and possibly the page?

Sure I will work on updating the same

**Comment by hamishwillee** [comment]
Thanks very much.

**Comment by hamishwillee** [comment]
@MohitMaheshwari1711 Should I close this or are you still using it as a base for your updated PR?

**Comment by hamishwillee** [comment]
OK, I am closing this. Looking forward to your fix @MohitMaheshwari1711

**Pull request closed without merging**
