### PR TITLE
typeof: custom func, final useful granular descrip

### PR DESCRIPTION
**Pull request by DarrenSem**
// Final way to get a useful granular description of the type of value.
  const objectType = Object.prototype.toString.call(value); // e.g. "[Object Date]"
  return objectType.slice(8, -1); // e.g. "Date"

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Mostly LGTM. In almost all cases, this will be handled by `value.constructor.name`, but I can account for corner cases where primitives have been tampered with.

**Comment by DarrenSem** [comment]
After I submitted this I found a couple of previous Issues *[see note below]* for the "typeof" page, and one of them listed a BUNCH of test cases ... and some of those differ in the uppercase/lowercase of "Object" that gets returned -- so on second thought I would say maybe skip this Pull Request. 🤷‍♂️
Also, I saw what you or someone else said about why `Symbol.toStringTag` exists (preferred instead of using `Object.prototype.toString.call` / `{}.toString.call`) ... so... yeah. Sorry.
I didn't know there was that much previous history for this page's custom "type" function (the previous discussions were quite informative though! Thanks!)
*[note]*
PR [#18125](https://github.com/mdn/content/pull/18125)
PR [#19595](https://github.com/mdn/content/pull/19595) this has the "**Test cases**" I just compared

**Comment by DarrenSem** [comment]
@Josh-Cena 
After I submitted this I found a couple of previous Issues *[see note below]* for the "typeof" page, and one of them listed a BUNCH of test cases ... and some of those differ in the uppercase/lowercase of "Object" that gets returned -- so on second thought I would say maybe skip this Pull Request. 🤷‍♂️ I will just close it now...
Also, I saw what you or someone else said about why `Symbol.toStringTag` exists (preferred instead of using `Object.prototype.toString.call` / `{}.toString.call`) ... so... yeah. Sorry.
I didn't know there was that much previous history for this page's custom "type" function (the previous discussions were quite informative though! Thanks!)
*[note]*
PR [#18125](https://github.com/mdn/content/pull/18125)
PR [#19595](https://github.com/mdn/content/pull/19595) this has the "**Test cases**" I just compared

**Comment by Josh-Cena** [comment]
The only case where the current code falls short is when you run `delete Object.prototype.constructor` or re-define `Date.name`. However, I'd rather not pre-emptively handle such corner cases, because then `Function.prototype.toString` may not be secure either. So yes, I think the current code is already acceptable.

**Pull request closed without merging**
