### PR TITLE
fix: Remove stub pages

### PR DESCRIPTION
**Pull request by nschonni**
Wiki created stub for child pages that not longer exist

### CODE REVIEW

**Comment by bershanskiy** [comment]
@nschonni Should this PR also include this page?
https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/widgets/index.html

**Comment by nschonni** [comment]
@bershanskiy that's in https://github.com/mdn/content/pull/2272 because it was more than a delete

**Comment by bershanskiy** [comment]
Makes sense, thanks for fast reply.

**Review by chrisdavidmills — APPROVED** [review]
LGTM

**Pull request merged**
