### PR TITLE
strip <strong> from <h3> tags' text

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by hamishwillee** [comment]
Nice one - this is why I like markdown - hard to inject crap into headings.

Can we lint on this kind of thing?

**Review by vkWeb — APPROVED** [review]
@hamishwillee I respect your opinion friend :) But I would say we should stick with HTML. Any abstraction layer above HTML at some point will remind us how powerful HTML was. 

@peterbe Looks good!

**Comment by hamishwillee** [comment]
> I respect your opinion friend :) But I would say we should stick with HTML. Any abstraction layer above HTML at some point will remind us how powerful HTML was.

@vkWeb Please don't take this the wrong way, but you are so very very wrong :-)

What markdown does for you is make editing and reviewing very simple, because there isn't anything to clutter the content. It is also incredibly hard to screw up. 

Great documentation is about structure. So essentially all you need in most cases is to have headings and paragraphs. The rest of HTML just gets authors into trouble (though I will admit the occasional table, notes, tips, warnings can be useful :-)).

But even if you disagree, I have never missed the power of HTML in a markdown system, because the markdown spec includes HTML :-)

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
> Can we lint on this kind of thing?

We can and maybe we should, IMHO. I guess that going forward, as far as new cases of things like this getting added, those should ideally get caught during (human) review. But it’d still be good to have the linter helping to make it more obvious.

**Comment by peterbe** [comment]
> Can we lint on this kind of thing?

A problem with that is the legacy. There's a LOT of HTML within the `<h3>` in our content. Huge amounts. In cases like this PR it was easy to remove, but there's lots of things like `<code>` and `<svg>` within the `h3` tags.

**Comment by hamishwillee** [comment]
Thanks. I think a lint "hint" would be good. FWIW the [guide says](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide#Heading_dos_and_donts)

image

This is a case where I'd disagree with the guide - code markup in headings can provide useful context.

**Comment by peterbe** [comment]
In my Markdown, I often type things like:

```
## Test `emacs` today
```
But I definitely think we need to review all our `<h2>` tags and turn them into a flaw. We should probably first settle the argument about perhaps making `<code>`  and `<i>` and `<em>` allowed exceptions.

**Comment by peterbe** [comment]
On the heated topic about HTML vs Markdown, a couple of observations of my own:

1. Even though a minority, there exists people who prefer HTML in the content management systems. Just like there are people who say "jiff" instead of "gif" :)
2. HTML is more powerful and more capable. 
3. Markdown is an abstraction on top of HTML which limits what you can do.
4. That "limits what you can do" is a good thing! Especially when you have tens of thousands of pages. 
5. GitHub UI + Markdown = ❤️  It's undeniably useful.
6. I did a prototype using `unified` (a Node Markdown rendering lib(s)) and combined with HTML support plus KS macros, it's really close to being a good transition for us since starting over most likely isn't an option.

**Comment by hamishwillee** [comment]
Yes, in particular "4" and "5" resonate. To that I would add that HTML is a barrier to contribution - just one more hassle.

Another markdown library you might want to look at is https://github.com/markdown-it/markdown-it. This is used by vuepress, which does a better job than many of rendering github-compatible markdown. I'm not advocating, but I compared a bunch of SSGs recently and I was surprised by how bad some of them are at that.

**Comment by hamishwillee** [comment]
> We should probably first settle the argument about perhaps making <code> and <i> and <em> allowed exceptions.

Who can make that decision? I'd lean towards "allowed but discouraged" for that set.

**Comment by vkWeb** [comment]
> 
> 
> @vkWeb Please don't take this the wrong way, but you are so very very wrong :-)

@hamishwillee I love to collaborate with people with different point of views, it gives me wider perspective :-) 

> What markdown does for you is make editing and reviewing very simple, because there isn't anything to clutter the content. It is also incredibly hard to screw up.

Hmm, I agree.
 
> Great documentation is about structure. So essentially all you need in most cases is to have headings and paragraphs. The rest of HTML just gets authors into trouble (though I will admit the occasional table, notes, tips, warnings can be useful :-)).
> 
> But even if you disagree, I have never missed the power of HTML in a markdown system, because the markdown spec includes HTML!



> On the heated topic about HTML vs Markdown, a couple of observations of my own:
> 
> 1. Even though a minority, there exists people who prefer HTML in the content management systems. Just like there are people who say "jiff" instead of "gif" :)
> 2. HTML is more powerful and more capable.
> 3. Markdown is an abstraction on top of HTML which limits what you can do.
> 4. That "limits what you can do" is a good thing! Especially when you have tens of thousands of pages.
> 5. GitHub UI + Markdown = :heart:  It's undeniably useful.
> 6. I did a prototype using `unified` (a Node Markdown rendering lib(s)) and combined with HTML support plus KS macros, it's really close to being a good transition for us since starting over most likely isn't an option.

I did a bit of rethinking and I would say Markdown will be good :+1:.

**Comment by peterbe** [comment]
> Another markdown library you might want to look at

Here's my prediction for moving to Markdown:
1. 1 months researching and prototyping different Node libraries and hacks for doing Markdown
2. 1 hour to implement it
3. 3-5 months of, after making the switch, "Oh crap! Didn't realize that would happen to this weirdo old page!"

Another opinion of mine is that this is best done in piecemeal chunks. We make the builder able to deal with *both* `index.md` or `index.html` wherever today it's only able to deal with `index.html`. Then we do it on a page-by-page basis. Or subtree-by-subtree. With PRs that are manageable in size :)

**Comment by hamishwillee** [comment]
> Another opinion of mine is that this is best done in piecemeal chunks. We make the builder able to deal with both index.md or index.html wherever today it's only able to deal with index.html. Then we do it on a page-by-page basis. Or subtree-by-subtree. With PRs that are manageable in size :)

Yes.

It is quite easy to convert things via a scripted approach using pandoc but these things never work perfectly - every single page should be checked. So yes, in parts, with a toolchain that can support both file types.

Pain points are likely to be heading anchor links, tables, and deciding what things we want to keep from HTML. You might want to consider the gitbook syntax to allow ourselves the ability to create explicit heading anchors. It does not render properly in github, but I still like it as it makes keeping links up to date a lot easier.
```
## My heading {#anchor-for-heading}
```

In particular I am looking forward to being able to view semi-rendered pages in github.

**Comment by Ryuno-Ki** [comment]
> This is used by vuepress,

And also Eleventy :-)
(Disclaimer: I'm a contributor there, too)

**Comment by peterbe** [comment]
> In particular I am looking forward to being able to view semi-rendered pages in github.

You and me both!

If it's something that's clear about non-HTML is:

1. There exists people who think HTML is better, but they're a minority.
2. A lot of gut-thoughts seems to indicate the plain Markdown is not going to be good enough. 
3. There'll be frustration and friction when people realize that you can do less than you used to be able to do.

**Pull request merged**
