### PR TITLE
modules->module-examples

### PR DESCRIPTION
**Pull request by wbamberg**
This is the other half of the fix for https://github.com/mdn/content/issues/14677, along with https://github.com/mdn/js-examples/pull/17.

### CODE REVIEW

**Review by estelle — APPROVED** [review]

**Comment by OrToR-KJM** [comment]
Hawaiian 3내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: Estelle Weyl ***@***.***> 날짜: 22/5/12  13:40  (GMT+09:00) 받은 사람: mdn/content ***@***.***> 참조: Subscribed ***@***.***> 제목: Re: [mdn/content] modules->module-examples (PR #15934) 
Merged #15934 into main.

**Comment by OnkarRuikar** [comment]
This breaks the link till https://github.com/mdn/js-examples/pull/17 is merged.

**Comment by OrToR-KJM** [comment]
Break

2022년 5월 12일 (목) 13:50, Onkar Ruikar ***@***.***>님이 작성:

**Comment by teoli2003** [comment]
I think the link is broken now, as mdn/js-examples#17 has not landed. I don't have the rights to merge on that repo: @Rumyra , @dipikabh ?

**Pull request merged**
