### PR TITLE
Add the HIDInputReportEvent

### PR DESCRIPTION
**Pull request by jpmedley**

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by teoli2003** [comment]
Hi!
We have two problems here:
1. The most important: these pages are Markdown (which is fine), but the content is in `index.html`. It should be in `index.md`. (Yari doesn't transform pages ending in `.html` but does for `.md`
2. The use of `{{domxref("DataView")}}` is not correct. `DataView` is part of JavaScript, and not of the Web APIs. These should be `{{jsxref("DataView")}}`. The flaws are raised by yari:
Screenshot 2021-08-17 at 07 02 48

@jpmedley, do you want to make the follow-up PR (I can help if you are too busy, but you may want to use your script to test it)

**Comment by sideshowbarker** [comment]
>  We have two problems here:
> 
> 1. The most important: these pages are Markdown (which is fine), but the content is in `index.html`. It should be in `index.md`. (Yari doesn't transform pages ending in `.html` but does it for `.md`
> 
> 2. The use of `{{domxref("DataView")}}` is not correct. `DataView` is part of JavaScript, and not of the Web APIs. These should be `{{jsxref("DataView")}}`. The flaws are raised by yari:

My bad for not having reviewed these more carefully.

For future reviews, I’ll make sure to check on both problems.

**Comment by teoli2003** [comment]
No worry, I guess the .md is a small bug of the script that will be fixed easily, and the macro errors would have been caught anyway as we are down to 0 for these flaws, and they would have dragged our attention on the flaws dashboard :-)

**Comment by jpmedley** [comment]
I'm surprised this was merged. If you want to back this out, I can resubmit.  

My tool for writing boilerplates does a string concatenation to create the file names. I forgot to change the file extension in the name generation routine. It's fixed now.

**Comment by jpmedley** [comment]
@sideshowbarker See above.

**Pull request merged**
