### PR TITLE
Added indication that "new Symbol()" is wrong

### PR DESCRIPTION
**Pull request by jimmonte**

### CODE REVIEW

**Comment by Josh-Cena** [comment]
@jimmonte I see that this PR is created successfully and in good shape. Is there more you want to add?

**Comment by jimmonte** [comment]
> @jimmonte I see that this PR is created successfully and in good shape. Is there more you want to add?

No, but I would like to know what is going on... I was checking something out about using a symbol and noticed that the new Symbol() example was not flagged as being bad. So I edited the file on the page, and the process got stuck after the  commit was made. There was no prompt to create a pull request and the checks were not done. Conveniently I found a second occurrence and was able to create the pull request after that.

**Review by Josh-Cena — APPROVED** [review]
Sorry for being a bit slow. Thank you!

**Comment by jimmonte** [comment]
Oh... I thought you were busy tracking down the bug in the editing process. Anyhow, I would be overjoyed if yours was a slow review.
2023-04-06 21_55_44-Pull Requests

**Comment by Josh-Cena** [comment]
Lol, the GitHub UI has always been a bit confusing for me. FYI, you can click <kbd>.</kbd> when viewing https://github.com/jimmonte/content and you will be able to use a real editor.

**Pull request merged**
