### PR TITLE
fix apiref of CookieStoreManager and some word fix

### PR DESCRIPTION
**Pull request by skyclouds2001**
### Description

fix apiref of CookieStoreManager

use {{jsxref("Promise")}} instead of {{jsxref("promise")}}

adding {{AvailableInWorkers}}, waiting for https://github.com/mdn/yari/pull/10029 for better using experimence

some other fix

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Review by teoli2003 — COMMENTED** [review]
Oops too early.

**Comment by skyclouds2001** [comment]
I guess we could go ahead first and update the usage of {{AvailableInWorkers}} afterwards

**Review by teoli2003 — APPROVED** [review]
I'm not a fan of `self`, but we don't have an official policy here.

**Pull request merged**
