### PR TITLE
Fix macro syntax

### PR DESCRIPTION
**Pull request by robokozo**
### Description

The page was not rendering correctly.
image

### Motivation

Correcting the template syntax

### CODE REVIEW

**Review by Josh-Cena — APPROVED** [review]
Thank you, and welcome to MDN!

**Comment by HHOLTpheonix81** [comment]
Hi my name is Horace Randy Holt.. I am messaging from lloydminster Saskatchewan canada. There are issues here that people will try say are drug related.. but that's not the case. It may be for part of whatever 
. But the mistreatment by some officers is unbelievable also the ignorance of those around that are aware of the situation but are too scared or on a mind trip themselves. I just want want what is right by me and also for my loved ones. Also maybe if right it may help others that could need this feeling if completeness to help them as well or their families. I have been repeated victimized  and targeted.. I ain't trying to be anything but me and I ain't that smart with technology and been depending on kot only tech but those around me to do the right things. My number is 3068304100 and if I could I could use some help in getting legal help as been put through enough to do something stupid to simple minds that are trying to only piss me off. .. coincidences happen but so does other shit I can't explain. And wint untill I know myself that I'm being helped by people instead of lut out as a fucking goof. My name is again horace randy holt. A link that was started is   gf.me/u/y5jc4h and it was originally started to try seek legal help. But dont know what I can do now. One thing I'm not seeking is a fake made up world where it seems to of been like this lately. And that's not what anyone would want I'd say for trying to make a difference in how people that can't afford representation get treated if they dont shit up. A company I started in 2018-19 is pheonix81. Lloydminster and digital dockery has shown me that my personal info has been used to only promote harm to families like mine.... but I'm different in how I mean it when I say I'm different hey. Hi from canada  and I'd like the continual clean up of sick fucks to be dealt with is one thing. For sure

**Comment by HHOLTpheonix81** [comment]
Gf.me/u/y5jc4h

**Comment by HHOLTpheonix81** [comment]
Horace randy holt

**Comment by HHOLTpheonix81** [comment]
Pheonix81

**Comment by HHOLTpheonix81** [comment]
Hell's angels

**Comment by HHOLTpheonix81** [comment]
ASAP

**Comment by HHOLTpheonix81** [comment]
Red alert

**Comment by HHOLTpheonix81** [comment]
Crazy cree

**Comment by HHOLTpheonix81** [comment]
IP

**Comment by HHOLTpheonix81** [comment]
NS

**Comment by HHOLTpheonix81** [comment]
ANTI VIOLENCE

**Comment by HHOLTpheonix81** [comment]
ANTI

**Comment by HHOLTpheonix81** [comment]
Wethepeople

**Comment by HHOLTpheonix81** [comment]
#nevergiveup

**Comment by HHOLTpheonix81** [comment]
Canada

**Comment by hamishwillee** [comment]
@HHOLTpheonix81 Please stop using MDN as a sandbox. A lot of  busy people unnecessarily get emails when you post here.

**Pull request merged**
