### PR TITLE
Remove tag attribute form front matter

### PR DESCRIPTION
**Pull request by OnkarRuikar**

### CODE REVIEW

**Comment by fred-wang** [comment]
This looks good to me, but I don't have the context of what these tags were used for and why we decide to remove them.

**Comment by OnkarRuikar** [comment]
@fred-wang this is part of the project [Remove tags from front-matter across mdn/content](https://github.com/mdn/mdn/issues/262). These tags were part of old Wiki platform. They are being replaced with a new `status` front matter attribute.

**Comment by teoli2003** [comment]
@OnkarRuikar We cannot remove the ones in MathML yet as the sidebar makes use of them (to remove them we need to add `page-type:` to the page, then update the macro).

**Comment by estelle** [comment]
> @OnkarRuikar We cannot remove the ones in MathML yet as the sidebar makes use of them (to remove them we need to add `page-type:` to the page, then update the macro).

Thanks. I didn't realize this either.

**Comment by teoli2003** [comment]
Yes, SVG and MathML are not ready. The SVG sidebar has been updated by @wbamberg and is under review in Yari. MathML will come soon after.

**Comment by wbamberg** [comment]
> Yes, SVG and MathML are not ready. The SVG sidebar has been updated by @wbamberg and is under review in Yari. MathML will come soon after.

There's a PR for this now -> https://github.com/mdn/yari/pull/8309.

**Comment by OnkarRuikar** [comment]
- As https://github.com/mdn/yari/pull/8309 got merged this is good to go now.

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by hamishwillee** [comment]
Hurray! Thanks

**Pull request merged**
