### PR TITLE
Explain Bluetooth command/request

### PR DESCRIPTION
**Pull request by Playit3110**
### Description

For better search of opcodes like "command" and "request"

### Motivation

I couldn't find references to request and command to the functions. I searched for "web bluetooth send command" and couldn't find it.

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
I don't think we've ever mentioned "bluetooth command" or "bluetooth request" anywhere. They may be terms defined in the Bluetooth spec? If you want to mention these, we need to write a section on the landing page explaining what they mean.

**Comment by Playit3110** [comment]
Bluetooth "command" and "request" are protocoll specific terms, which are used in the opcode header. It would be nice to have them, so you can find this reference with, for example, Wireshark, which decodes Opcodes as "requests" or "command"

**Comment by Playit3110** [comment]
I am right now in my hollidays, but sure I can write one or two paragraphs on "command" and "request"

**Comment by Josh-Cena** [comment]
Sure, no hurries :)

**Comment by Josh-Cena** [comment]
@Playit3110 Are you coming back to this?

**Comment by Playit3110** [comment]
Yeah

**Comment by Josh-Cena** [comment]
@Playit3110 I'm closing it for now to keep our PR backlog small. If you are still interested in working on it, feel free to open a new PR that's ready for review.

**Pull request closed without merging**
