### PR TITLE
Remove confusing comma in Web/JavaScript

### PR DESCRIPTION
**Pull request by AaronAtP123**
### Description

Removed a comma from the first sentence.

### Motivation

The comma changed the meaning, being read as (lightweight), (interpreted), or (just-in-time compiled).

### CODE REVIEW

**Review by hamishwillee — COMMENTED** [review]
What this says now is that interpreted and just in time are synonyms. 
@Josh-Cena I don't think they are - right?
I'd change to "interpreted, and"

**Comment by Josh-Cena** [comment]
I think they are synonyms, to some degree. Both can be antonyms with ahead-of-time compiled. In this case I would frame it as:

> lightweight interpreted (or just-in-time compiled)

**Comment by AaronAtP123** [comment]
I've adjusted it accordingly

**Review by Josh-Cena — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
