### PR TITLE
HTML link types: use browser-compat front-matter + spec macro

### PR DESCRIPTION
**Pull request by Elchi3**
BCD lacks a spec url for https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types but I'm adding that in https://github.com/mdn/browser-compat-data/pull/10544. For the sub pages BCD has specs in place already.

### CODE REVIEW

**Comment by wbamberg** [comment]
> I'm adding that in mdn/browser-compat-data#10544. 

Do you want to wait till that's deployed, or shall we live with "No specification found" for the interim?

**Comment by Elchi3** [comment]
> Do you want to wait till that's deployed, or shall we live with "No specification found" for the interim?

I guess let's live with "No specification found" and see if there are complaints. This BCD train just departed and so this PR would sit here the maximum amount of waiting time (one week) ...

**Review by wbamberg — APPROVED** [review]
👍

**Comment by teoli2003** [comment]
(For tracking purpose) This is part of #1146.

**Pull request merged**
