### PR TITLE
Added arcTo() details and demo

### PR DESCRIPTION
**Pull request by jimmonte**
The demo that was added is a useful way to see how arcTo() works. However, the code is more related to the user interactions than arcTo(), so it was hidden using the methods described at https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples. So the HTML should be hidden, but it appears in the preview. Perhaps this is a bug in the previewer?

### CODE REVIEW

**Comment by bsmth** [comment]
Hi @jimmonte thanks for suggesting the changes. Just a note: there are a lot of contributors watching this repository who receive notifications when pull requests are opened here, it would be great if you could limit the number of pull requests to as few as possible in future (i.e. #25344, #25345, #25346, #25347). Thank you :)

**Comment by jimmonte** [comment]
Hi @bsmth Thanks for the feedback. I had some issues that only showed up after the pull requests were submitted. Can you suggest a way that I could easily view the results of the checks and the live sample output without creating a pull request?

**Comment by jimmonte** [comment]
Hi @dipikabh. Thanks for the information regarding the checks and live sample output. However, I was hoping for a way to obtain the information they provide without cloning the entire repository. Here I only made one change (albeit large) to a single file. That is, is there a way to see the checks and live sample output after clicking the link to "[Edit the page on GitHub](https://github.com/mdn/content/edit/main/files/en-us/web/api/canvasrenderingcontext2d/arcto/index.md)" and editing a page but before making a pull request?

**Comment by bsmth** [comment]
Thanks @dipikabh for helping. @jimmonte: at the moment there are two ways to contribute:

1. Open a PR on GitHub like you have done.
2. Fork the repository, make a branch, serve the changes locally, commit your changes and open a pull request.

__After opening a pull request:__ a preview will be built showing the build of your proposed changes (linked in the comment above).

__If checks are failing:__ or it doesn't look right, make changes to the same branch on the open pull request (on GitHub or on your fork). The preview will be recreated after every commit is made to the branch. You can take a look at [this submission as an example](https://github.com/mdn/content/pull/25135).

I hope that helps 👍🏻

**Comment by jimmonte** [comment]
@bsmth Thanks for the details, but I seem to be missing something. I was aware of option 2, but it requires cloning the repository and installing software, which is why I opted for the option 1. That method can be done entirely online, making it more approachable and convenient for a casual contributor to fix small issues or make other minor contributions. I have previously seen the links for the created branches. However, when I have followed them, I have found no way to continue with the online editing. That is, it appears that to make additional changes that may only manifest themselves after the checks have been performed and the preview has been generated, it is necessary to proceed essentially as in option 2. How are additional changes made via online editing?

**Comment by bsmth** [comment]
When you suggest changes to a file in the mdn/content repo on GitHub, this happens:

* the repo is forked to your account (if one doesn't exist) - https://github.com/jimmonte/content
* Your edits are done on a branch in your fork: https://github.com/jimmonte/content/tree/patch-36

You have opened a pull request from `jimmonte:patch-36` into `mdn:main`. 
If you continue making changes (commits) to any files on the `patch-36` branch while the pull request is open, you will trigger builds above. You can do this at https://github.com/mdn/content/pull/25348/files or at https://github.com/jimmonte/content/blob/patch-36/files/en-us/web/api/canvasrenderingcontext2d/arcto/index.md

**Comment by jimmonte** [comment]
@bsmth Again thanks for the information, but I am not seeing how to continue doing online editing as I had enquired about in my previous comment using the links you gave. The closest I have found was leaving review comments and changing the bug description at https://github.com/mdn/content/pull/25348/files. What is the process to continue online editing from one of those links?

**Comment by bsmth** [comment]
At the top of the file there is an **edit file** option. Please refer to the [GitHub documentation](https://docs.github.com/en/get-started/quickstart/github-flow) for more information. Thank you :)

**Comment by jimmonte** [comment]
This pull request was submitted about a month ago, and it appears to have not yet been reviewed. If there has already been a review, please indicate where it is located, and if not, I would be interested in an estimate of when it might be reviewed.

**Comment by hamishwillee** [comment]
@jimmonte Probably the reviewers were distracted by the discussion of how to make edits online. Thanks for reminding us about this one.

Note, I know you don't want to use github and the toolchain for edits. That's a pity - it is so much easier than working through github.


@bsmth @Elchi3 You planning on reviewing this?

Just fly-by comments ...
- The example is visually cool. 
- I would put it under a heading "special cases" or similar rather than daisy chaining immediately after the example "How arcTo works". 
- The text uses terminology that is probably well understood by mathematicians, but not accessible to me - e.g. collinear. Makes it hard to read. Do not know if it can be reduced to be easier for those less expert.
- It talks about `IndexSizeError DOMException` - that info should also go in an Exceptions section.

**Comment by teoli2003** [comment]
I plan to work on Path2D methods this Quarter, I'll review this at the same time. I agree with Hamish comments, though I'm not sure of the section name.

The colinear part is weird as there is no description of what happens when the three points are aligned.

**Comment by jimmonte** [comment]
The specs at [https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-arcto-dev](url) that define the operation of `arcTo()` are given at the end of this comment. I had tried to summarize them in the description. Regarding collinear, I realize that MDN should be usable from people with a wide variety of backgrounds. It is easy to forget that a word is not well known after you use it enough.

@teoli2003,
>The colinear part is weird as there is no description of what happens when the three points are aligned.

I do not understand this comment, in particular what "aligned" means here. I would have thought it would be a less precise description of collinear, i.e., the three points lie along the same straight line.

Incidentally, [https://stats.stackexchange.com/questions/316213/origin-and-spelling-of-multicollinear-colinear#:~:text=Colinear%20is%20a%20U.S.%20English,and%20modeling%20(especially%20U.S.).](url) The spellcheckers I have prefer the longer version.

Specs:
> The arcTo(x1, y1, x2, y2, radius) method, when invoked, must run these steps:
> 
> If any of the arguments are infinite or NaN, then return.
> 
> [Ensure there is a subpath](https://html.spec.whatwg.org/multipage/canvas.html#ensure-there-is-a-subpath) for (x1, y1).
> 
> If radius is negative, then throw an ["IndexSizeError"](https://webidl.spec.whatwg.org/#indexsizeerror) [DOMException](https://webidl.spec.whatwg.org/#dfn-DOMException).
> 
> Let the point (x0, y0) be the last point in the subpath, transformed by the inverse of the [current transformation matrix](https://html.spec.whatwg.org/multipage/canvas.html#transformations) (so that it is in the same coordinate system as the points passed to the method).
> 
> If the point (x0, y0) is equal to the point (x1, y1), or if the point (x1, y1) is equal to the point (x2, y2), or if radius is zero, then add the point (x1, y1) to the subpath, and connect that point to the previous point (x0, y0) by a straight line.
> 
> Otherwise, if the points (x0, y0), (x1, y1), and (x2, y2) all lie on a single straight line, then add the point (x1, y1) to the subpath, and connect that point to the previous point (x0, y0) by a straight line.
> 
> Otherwise, let The Arc be the shortest arc given by circumference of the circle that has radius radius, and that has one point tangent to the half-infinite line that crosses the point (x0, y0) and ends at the point (x1, y1), and that has a different point tangent to the half-infinite line that ends at the point (x1, y1) and crosses the point (x2, y2). The points at which this circle touches these two lines are called the start and end tangent points respectively. Connect the point (x0, y0) to the start tangent point by a straight line, adding the start tangent point to the subpath, and then connect the start tangent point to the end tangent point by The Arc, adding the end tangent point to the subpath.

**Comment by bsmth** [comment]
Hi @jimmonte - let's try to make some small fixes to get your additions merged. I agree with the reviews above that the example showing construction of paths looks really nice. We need to make the following changes, however:

* We need to put it in a different section lower on the page after the simple examples. Other sections we commonly have for this purpose are "Usage notes" (and "{Topic} considerations").
* We need to simplify the language somewhat, even explaining collinear inline would work.

I'm willing to make changes directly on this branch if you're okay with that. I would add "Usage notes" with some of your prose, move the example down into the "Examples" section with some context (maybe "Visualizing arcTo calculation" or similar. Does that sound okay?

**Comment by bsmth** [comment]
@teoli2003 - I've just assigned myself to pick up some edits on this to get it finished, FYI. Let me know if that's okay with you.

**Review by bsmth — APPROVED** [review]
Thanks @jimmonte - I'm +1 on merging this in the current state. The example is a lot longer than we usually have, but I think it adds great value to readers, and it certainly looks and works great, so I would like to add this. 

One part that would be great to improve as a follow-up would be to use different elements instead of `contenteditable` spans, so we have more appropriate controls for the demo, but I don't want to block on this given the focus is understanding `arcTo` here.

**Comment by bsmth** [comment]
Merging shortly, thank you all! 👍🏻

**Comment by jimmonte** [comment]
@bsmth
I am all for making the language more understandable, but it still needs to be correct. Commit 11e28a3c6abae267d2cd5516b991d6db78eaca5a has some issues with the wording.

>Note that `arcTo` will create a straight line when <em>P<sub>1</sub></em>
and <em>P<sub>2</sub></em> are in a line. Additionally, nothing is drawn by
`arcTo` if <em>P<sub>1</sub></em> and <em>P<sub>2</sub></em> have the same
coordinates.

Neither statement of this paragraph is correct. Points <em>P<sub>1</sub></em> and <em>P<sub>2</sub></em> are *always* in a line, and <em>P<sub>1</sub></em> and <em>P<sub>2</sub></em> being coincident does not guarantee that nothing is drawn. The special cases require conditions on all three points as I had described in the earlier version. Also, it may be worth keeping the information about the special case when the radius is 0.

For easy reference, here is the original text related to special cases:

>If _r_ is 0, `arcTo()` behaves as if <em>P<sub>0</sub></em>,
<em>P<sub>1</sub></em>, and <em>P<sub>2</sub></em> are collinear.
In the case of all of the points being collinear, a line from
<em>P<sub>0</sub></em> to <em>P<sub>1</sub></em> is drawn
unless the points <em>P<sub>0</sub></em> and <em>P<sub>1</sub></em> are
coincident, in which case nothing is drawn.

**Comment by bsmth** [comment]
> I am all for making the language more understandable, but it still needs to be correct. Commit [11e28a3](https://github.com/mdn/content/commit/11e28a3c6abae267d2cd5516b991d6db78eaca5a) has some issues with the wording.

I agree entirely. I was a little overzealous with merging; my apologies!

> For easy reference, here is the original text related to special cases:
> 
> > If _r_ is 0, `arcTo()` behaves as if _P0_,
> > _P1_, and _P2_ are collinear.
> > In the case of all of the points being collinear, a line from
> > _P0_ to _P1_ is drawn
> > unless the points _P0_ and _P1_ are
> > coincident, in which case nothing is drawn.

I understand. Much appreciated, I will correct this shortly and CC you on the changes.

**Pull request merged**
