### PR TITLE
Added Sepia option

### PR DESCRIPTION
**Pull request by tusharv**
Added sepia option in code example related to https://github.com/mdn/dom-examples/pull/76

### CODE REVIEW

**Review by Rumyra — CHANGES_REQUESTED** [review]
Hi @tusharv - this looks great 👍

As the code block in this page is pretty large because of the different functions for colour changes, could you add some comments throughout specifying what each part of the code does. I realise the function names are clear, but also it helps to break up the code slightly for the reader.

Thanks!

**Comment by Ryuno-Ki** [comment]
@tusharv Any updates? :-)

**Comment by sideshowbarker** [comment]
Closing for lack of any response at all from OP since mid-December when this PR was opened.

**Comment by tusharv** [comment]
Changes of Example HTML and JavaScript file is already live.

See the page at https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas#painting_pixel_data_into_a_context

So now example and the source file is having Sepia option but the corresponding code block is not having sepia.

https://github.com/mdn/dom-examples/blob/master/canvas/pixel-manipulation/color-manipulation.js#L16-L28

Please consider removing that from https://github.com/mdn/dom-examples/ too.

**Comment by sideshowbarker** [comment]
@tusharv As far as https://github.com/mdn/content/pull/352#issuecomment-849044219, please consider re-submitting a PR — one that also includes the changes in @Rumyra’s review comments at https://github.com/mdn/content/pull/352#pullrequestreview-555496692, which were:

> could you add some comments throughout specifying what each part of the code does. I realise the function names are clear, but also it helps to break up the code slightly for the reader

The reason I closed this PR is that we never got a response from you to those review comments, nor a response to @Ryuno-Ki’s request at https://github.com/mdn/content/pull/352#issuecomment-778780915 asking for your attention.

**Pull request closed without merging**
