### PR TITLE
Fix argument order in String.p.replace() example

### LINKED ISSUE #11743: Issue with "String.prototype.replace()": Wrong order of parameters
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

#### What information was incorrect, unhelpful, or incomplete?

`function upperToHyphenLower(match, offset, string) {`

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#using_an_inline_function_that_modifies_the_matched_characters

#### What did you expect to see?

`function upperToHyphenLower(match, string, offset) {`

#### Did you test this? If so, how?
https://stackoverflow.com/a/70588678/295783

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/replace`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/replace/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

### PR DESCRIPTION
**Pull request by sideshowbarker**
Fixes https://github.com/mdn/content/issues/11743

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
It looks to me like the page is correct here.

Try the existing code, with a bit of logging:

```js
function styleHyphenFormat(propertyName) {
  function upperToHyphenLower(match, offset, string) {

    console.log(`Match: ${match}`);
    console.log(`Offset: ${offset}`);
    console.log(`String: ${string}`);
  
    return (offset > 0 ? '-' : '') + match.toLowerCase();
  }
  return propertyName.replace(/[A-Z]/g, upperToHyphenLower);
}

styleHyphenFormat('borderTop');
```

> Match: T
> Offset: 6
> String: borderTop
> "border-top"

Now the new version:

```js
function styleHyphenFormat(propertyName) {
  function upperToHyphenLower(match, string, offset) {

    console.log(`Match: ${match}`);
    console.log(`Offset: ${offset}`);
    console.log(`String: ${string}`);

    return (offset > 0 ? '-' : '') + match.toLowerCase();
  }
  return propertyName.replace(/[A-Z]/g, upperToHyphenLower);
}

styleHyphenFormat('borderTop');
```

> Match: T
> Offset: borderTop
> String: 6
> "bordertop"

...seems wrong, and the result is wrong too.

I'm not great at reading the ES specs, but it looks like the relevant bit is step 12a of https://tc39.es/ecma262/multipage/text-processing.html#sec-string.prototype.replace, where we pass this to the replacer:

> « searchString, 𝔽(position), string »

**Comment by sideshowbarker** [comment]
> It looks to me like the page is correct here.

@mplungjan? https://github.com/mdn/content/pull/11770#pullrequestreview-845997341

**Comment by sideshowbarker** [comment]
Closing for lack of response

**Comment by sideshowbarker** [comment]
> I'm not great at reading the ES specs, but it looks like the relevant bit is step 12a of [tc39.es/ecma262/multipage/text-processing.html#sec-string.prototype.replace](https://tc39.es/ecma262/multipage/text-processing.html#sec-string.prototype.replace), where we pass this to the replacer:
> 
> > « searchString, 𝔽(position), string »

Yeah, agreed — as far as I can tell from the spec, that’s correct.

So I’m going ahead and re-closing this PR.

**Pull request closed without merging**
