### PR TITLE
DO NOT REVIEW or MERGE: CSS longhand properties

### PR DESCRIPTION
**Pull request by estelle**
in case anyone wants a list of all the longhand CSS properties supported in chromium and/or FF at the moment

Please don't review or merge this. It's just a FYI resource  for us to look at the flaws / missing pages.

This is not meant to be merged.

Just created this so people could look at the preview and see what is is missing and NOT redirected. some pages, like `flood-color`, don't have a CSS page (yet), and are redirected. In such cases, the link is neither red nor disabled.

### CODE REVIEW

**Comment by Josh-Cena** [comment]
@estelle, what are the next step plans with this PR?

**Comment by Josh-Cena** [comment]
If you want to find all non-broken links that are redirected: `[...document.querySelectorAll(".section-content > ul > li > a")].filter((x) => x.href && !x.href.endsWith(`/en-US/docs/Web/CSS/${x.innerText}`)).map((x) => x.innerText)`

**Comment by Josh-Cena** [comment]
I've compared the broken links here with web docs backlog. There are only 18 properties here that are not in the backlog (most are prefixed properties):

- `app-region` (`-webkit-app-region` in backlog)
- `buffered-rendering`
- `color-rendering`
- `glyph-orientation-horizontal`
- `mask-position-x`
- `mask-position-y`
- `text-box-edge`
- `text-box-trim`
- `-webkit-backdrop-filter`
- `-webkit-box-decoration-break`
- `-webkit-box-flex-group`
- `-webkit-box-lines`
- `-webkit-clip-path`
- `-webkit-line-break`
- `-webkit-ruby-position`
- `-webkit-text-orientation`
- `-webkit-writing-mode`
- `-moz-window-dragging`

**Comment by estelle** [comment]
Closed so this doesn't appear in the list of open PRs. But still using this as a resource / referencing it in other issues and prs

**Pull request closed without merging**
