### PR TITLE
Use htmlattr macros

### PR DESCRIPTION
**Pull request by geppy**
### Description

I updated the `<input>` article to use the [`htmlattrdef`](https://github.com/mdn/yari/blob/main/kumascript/macros/htmlattrdef.ejs) macro, and updated references to use [`htmlattrxref`](https://github.com/mdn/yari/blob/main/kumascript/macros/htmlattrxref.ejs).
I fixed some related typos as well: 60af5771, 088cb4b, 7f9ab376, 3c3db63.

### Motivation

Not using `htmlattrdef` breaks `htmlattrxref` (unless you manually prefix `id`s with `attr-`).

I noticed [a broken link](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory#:~:text=the%20webkitdirectory%20HTML%20attribute), which led me to the cause (not using `htmlattrdef`) and to other instances (of links matching `a[href^="/en-US/docs/Web/HTML/Element/input#attr-"]`).

### Additional details

Unprefixed links still work, as the `<dt>`'s `id` has the attribute name in unprefixed form.

### Related issues and pull requests

None, as far as I know.

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
Thanks for your PR. We are slowly moving away from macros and generally prefer pure markdown, so I'm not sure how useful this PR is to us.

Thoughts from other reviewers?

**Comment by hamishwillee** [comment]
@Elchi3 I strongly feel that we should not accept this PR for the reason given. Though I do feel a bit bad about this as @geppy has put some real work into this, and we do not provide proper direction alongside the macro docs.

Would very happily accept the typo fixes and of course fixes to any links that were actually broken before the change was made.

If this does not get accepted I propose we globally remove the macro including docs.

**Comment by geppy** [comment]
Should I create a new PR

**Comment by hamishwillee** [comment]
@geppy I'll leave that to @Elchi3 to answer - he may want further feedback. 

If it were me though:
- yes, create a new PR for the specific bugs.
- "whether or not to keep the attr- prefix?" 
  -  I think you are saying that some anchors are defined using `htmlattrdef`, and that the anchors are created with the prefix `attr-` for each attribute. 
    - The links have to work. So you will either have to link to this full URL as it is now with the `attr-`  OR remove the `htmlattrdef` as well. I think we should remove `htmlattrdef` as well, and use a definition list or similar to create the anchor - but let's see what @Elchi3 says.

**Comment by Josh-Cena** [comment]
> If this does not get accepted I propose we globally remove the macro including and guidance docs.

I agree a PR that purely refactors one link format to another is not constructive, but I disagree about removing xref macros (as I have spoken in several other places). I don't have opinions about `htmlattrxref` because I don't use it often and I have little idea about its pains (although I have noticed quite a few broken link reports related to it). However, I think in general xrefs are invaluable.

1. It avoids duplication. In a link like `{{jsxref("Array.prototype.push()")}}`, the text is exactly what gets rendered. `{{jsxref("Statements/async_function", "async function")}}` is slightly longer, but stays very focused nonetheless. Compare that to ``[`Array.prototype.push()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push)`` or ``[`async function`](/en-US/docs/Web/JavaScript/Reference/Statements/async_function)``. Not only is the link twice as long, it also contains a lot of useless information. The entire `/en-US/docs/Web/JavaScript/Reference` prefix just tells me it's a JS ref; `Array/push` is purely repeated from the link text `Array.prototype.push()`. If we can make the xref macro smarter, we can probably avoid even more duplication. For example, `{{jsxref("Array/push()")}}` could just render `push()` and avoid the `Array/` qualifier.
2. Following the point above, a shorter link helps with source authoring. If you are writing a Markdown table, a single link could make the row over 100 characters long, compared to a macro which is reasonably short. Short links also help me estimate the length of a paragraph—three Markdown links could make the text look like a whole paragraph, while in fact it's just a single line when rendered.
3. Less mental burden. If I want to write a Markdown link, I have to actually go to the website page and copy the URL, because I keep making errors like forgetting `/Web/` or changing `Reference/` to `References/`. Using the link text itself as the macro content makes it much more robust as I can just write the link from my head.
4. Possible link enhancement. For example, if we want to automatically render `{{deprecated_inline}}` or `{{experimental_inline}}` next to links, it would be far easier if the link comes from a macro, as macros have their own template anyway, compared to a Markdown link which should semantically just be an `<a>`.

**Comment by hamishwillee** [comment]
Closing. There is cherry picking action that may or may not already have happened, but it is out of scope for this issue: https://github.com/mdn/content/pull/22924#issuecomment-1370780170

**Pull request closed without merging**
