### PR TITLE
fix: add accesskeys to some of the categories in the table

### LINKED ISSUE #25608: Keyboard shortcuts table suggest accesskeys aren't supported in Safari and Chrome on Mac, as well as in Edge on Windows
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey

### What specific section or headline is this issue about?

_No response_

### What information was incorrect, unhelpful, or incomplete?

This table seems to be a bit inaccurate:

Screen Shot 2023-03-24 at 2 25 57 PM

* It makes it look like accesskeys are not supported in Safari and Chrome on mac, but `ctrl` + `opt` + `key` appears to work in both cases
* It also makes it look like Edge on Windows doesn't support accesskeys, but `alt` + `key` seems to work

### What did you expect to see?

It would be nice to have the table fully reflect what I'm experiencing testing accesskeys in different browsers.

### Do you have any supporting links, references, or citations?

Those keyboard shortcuts in the different browser/platform combinations can be tested via this simple demo: https://jsfiddle.net/hmjones/5tzxfvo0/5/

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/accesskey`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/accesskey/index.md
* Last commit: https://github.com/mdn/content/commit/ba96f2f183353872db6d9242c7d2dffe2dbc0c35
* Document last modified: 2023-02-24T05:52:35.000Z

</details>

### PR DESCRIPTION
**Pull request by CBID2**
### Description

This PR adds accesskeys to the table. 
### Motivation
This would ensure that the table provides accurate information about which accesskeys work in the browsers. 

### Related issues and pull requests
Fixes #25608

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
Hi there @CBID2;, and thanks for the updates! 

Couple of things I think it would be great for you to look at:

I think the key values look correct, however the table is a little confusing given that some places have separate duplicate entries, and some places have a single entry that spans multiple rows or columns. Like that box in the middle for Edge/Google Chrome and Linux — which browsers do they apply to?!? And surely Edge/Mac should also have "N/A". I think it would be easier to understand if it were consistent throughout. Maybe try having an individual entry for every cell, and see if that doesn't look too repetitious. 

Also, in your PR you've changed the `.vscode/settings.json` file. I'm assuming that wasn't intentional.

**Comment by CBID2** [comment]
Hi @chrisdavidmills. The VsCode settings was a mistake on my part. As far as the table, I was trying to follow the pattern of the other columns to no avail. Would you mind put your comments about the table as an inline comment? It'll make it easier for me to visualize how I should format it.

**Comment by chrisdavidmills** [comment]
@CBID2 

> As far as the table, I was trying to follow the pattern of the other columns to no avail. Would you mind put your comments about the table as an inline comment? It'll make it easier for me to visualize how I should format it.

@CBID2 Sure thing! I did try to leave inline comments, but it seems impossible to comment on a line that has not been modified in the PR. I ended up dumping the table into a code editor and playing with it, coming up with this:

```html
<table class="standard-table">
  <tbody>
    <tr>
      <th></th>
      <th>Windows</th>
      <th>Linux</th>
      <th>Mac</th>
    </tr>
    <tr>
      <th>Firefox</th>
      <td colspan="2"><kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd><em>key</em></kbd></td>
      <td>
        Firefox 57+: <kbd>Control</kbd> + <kbd>Option</kbd> +
        <kbd><em>key</em></kbd> or <kbd>Control</kbd> + <kbd>Alt</kbd> +
        <kbd><em>key</em></kbd><br>Firefox 14-56: <kbd>Control</kbd> + <kbd>Alt</kbd> +
        <kbd><em>key</em></kbd><br>Firefox 13 or older: <kbd>Control</kbd> +
        <kbd><em>key</em></kbd>
      </td>
    </tr>
    <tr>
      <th>Edge</th>
      <td rowspan="2"><kbd>Alt</kbd> + <kbd><em>key</em></kbd></td>
      <td rowspan="2">
        <kbd>Control</kbd> + <kbd>Option</kbd> + <kbd><em>key</em></kbd><br>or <kbd>Control</kbd> + <kbd>Option</kbd> + <kbd>Shift</kbd> +
        <kbd><em>key</em></kbd>
      </td>
      <td>n/a</td>
    </tr>
    <tr>
      <th>Google Chrome</th>
      <td><kbd>Control</kbd> + <kbd>Option</kbd> + <kbd><em>key</em></kbd></td>
    </tr>
    <tr>
      <th>Safari</th>
      <td colspan="2">n/a</td>
      <td><kbd>Control</kbd> + <kbd>Option</kbd> + <kbd><em>key</em></kbd></td>
    </tr>
    <tr>
      <th>Opera 15+</th>
      <td colspan="2"><kbd>Alt</kbd> + <kbd><em>key</em></kbd></td>
      <td><kbd>Control</kbd> + <kbd>Alt</kbd> + <kbd><em>key</em></kbd></td>
    </tr>
    <tr>
      <th>Opera 12</th>
      <td colspan="3">
        <kbd>Shift</kbd> + <kbd>Esc</kbd> opens list of available accesskeys; choose an item by then pressing
        <kbd><em>key</em></kbd>.
      </td>
    </tr>
  </tbody>
</table>
```

I've basically:

- Removed some of the more confusing rowspan stuff, making it consistent for the Edge/Chrome ones.
- Added in the n/a I talked about
- Made the Safari row make sense
- Shortened some of the text down to make it fit in the table better.

What do you think of this? Feel free to use my suggestion or do it some other way, but this communicates what I was on about.

**Comment by CBID2** [comment]
> @CBID2
> 
> > As far as the table, I was trying to follow the pattern of the other columns to no avail. Would you mind put your comments about the table as an inline comment? It'll make it easier for me to visualize how I should format it.
> 
> @CBID2 Sure thing! I did try to leave inline comments, but it seems impossible to comment on a line that has not been modified in the PR. I ended up dumping the table into a code editor and playing with it, coming up with this:
> 
> ```
> <table class="standard-table">
>   <tbody>
>     <tr>
>       <th></th>
>       <th>Windows</th>
>       <th>Linux</th>
>       <th>Mac</th>
>     </tr>
>     <tr>
>       <th>Firefox</th>
>       <td colspan="2"><kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd><em>key</em></kbd></td>
>       <td>
>         Firefox 57+: <kbd>Control</kbd> + <kbd>Option</kbd> +
>         <kbd><em>key</em></kbd> or <kbd>Control</kbd> + <kbd>Alt</kbd> +
>         <kbd><em>key</em></kbd><br>Firefox 14-56: <kbd>Control</kbd> + <kbd>Alt</kbd> +
>         <kbd><em>key</em></kbd><br>Firefox 13 or older: <kbd>Control</kbd> +
>         <kbd><em>key</em></kbd>
>       </td>
>     </tr>
>     <tr>
>       <th>Edge</th>
>       <td rowspan="2"><kbd>Alt</kbd> + <kbd><em>key</em></kbd></td>
>       <td rowspan="2">
>         <kbd>Control</kbd> + <kbd>Option</kbd> + <kbd><em>key</em></kbd><br>or <kbd>Control</kbd> + <kbd>Option</kbd> + <kbd>Shift</kbd> +
>         <kbd><em>key</em></kbd>
>       </td>
>       <td>n/a</td>
>     </tr>
>     <tr>
>       <th>Google Chrome</th>
>       <td><kbd>Control</kbd> + <kbd>Option</kbd> + <kbd><em>key</em></kbd></td>
>     </tr>
>     <tr>
>       <th>Safari</th>
>       <td colspan="2">n/a</td>
>       <td><kbd>Control</kbd> + <kbd>Option</kbd> + <kbd><em>key</em></kbd></td>
>     </tr>
>     <tr>
>       <th>Opera 15+</th>
>       <td colspan="2"><kbd>Alt</kbd> + <kbd><em>key</em></kbd></td>
>       <td><kbd>Control</kbd> + <kbd>Alt</kbd> + <kbd><em>key</em></kbd></td>
>     </tr>
>     <tr>
>       <th>Opera 12</th>
>       <td colspan="3">
>         <kbd>Shift</kbd> + <kbd>Esc</kbd> opens list of available accesskeys; choose an item by then pressing
>         <kbd><em>key</em></kbd>.
>       </td>
>     </tr>
>   </tbody>
> </table>
> ```
> 
> I've basically:
> 
> * Removed some of the more confusing rowspan stuff, making it consistent for the Edge/Chrome ones.
> * Added in the n/a I talked about
> * Made the Safari row make sense
> * Shortened some of the text down to make it fit in the table better.
> 
> What do you think of this? Feel free to use my suggestion or do it some other way, but this communicates what I was on about.

Done @chrisdavidmills

**Review by chrisdavidmills — APPROVED** [review]
@CBID2 I made a couple more small tweaks, and think this is all ready to go now. Thank you so much for your contribution!

**Pull request merged**
