### PR TITLE
Fix up images in WebExtensions:User Interface et al

### LINKED ISSUE #659: Issue with "The JavaScript input interpreter": images has bad ratio (height should be set to auto)
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter

#### What information was incorrect, unhelpful, or incomplete?
image
Bad image height (should be set to auto)

#### Specific section or headline?
Single-line mode

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/web_console/the_command_line_interpreter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/tools/web_console/the_command_line_interpreter/index.html
* Report started: 2020-12-27T09:22:07.195Z

</details>

### LINKED ISSUE #695: Issue with "User interface": Images are skewed
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface

#### What information was incorrect, unhelpful, or incomplete?

Several images are skewed.

Either apply `object-fit: contain` to each image, set the correct dimensions, or set it for all table images in `_base.scss` or `_table.scss`

#### Specific section or headline?

The main table, "Example" column.

#### What did you expect to see?

Images should not be skewed.

#### Did you test this? If so, how?

mdn-screenshot

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/user_interface`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/add-ons/webextensions/user_interface/index.html
* Report started: 2020-12-28T17:37:24.261Z

</details>

### PR DESCRIPTION
**Pull request by hamishwillee**
Fixes #695
Fixes #659

Just removes height styling to fix stretched images. Pages render properly locally.

### CODE REVIEW

**Comment by zombie** [comment]
From a brief look, this local change seems ok, but I'm not familiar with history why this ended up like this, nor if there are plans to fix this globally (and if manual changes interfere with those plans), so probably better if someone like @chrisdavidmills takes a look.

**Comment by mattiapontonio** [comment]
Example showing a toolbar button (browser action).

**Comment by hamishwillee** [comment]
@mattiapontonio What is the point of your highlighted image - it isn't distorted, which indicates the change worked?

**Comment by mattiapontonio** [comment]
@hamishwillee 
This Is the HTML.
I'm expecting similar, in terms of style.

**Comment by mattiapontonio** [comment]
I say that it is not correct that I set properties and they do not work. The basic layout principle is right but even GitHub in theory should at least expose a warning to avoid thinking about a bug or badly formatted code or anything else.

**Comment by mattiapontonio** [comment]
Regarding deleting these properties, it might not be right because potentially content could be used on other non-Yari platforms with other rules. In my opinion the validation must be moved first to the standard and then to the editorial rules of Yari.

**Comment by mattiapontonio** [comment]
https://github.com/mdn/content/issues/648

**Review by chrisdavidmills — APPROVED** [review]
LGTM; eventually we will be pushing a global fix for all the incorrect aspect ratio screenshots...

**Pull request merged**
