### PR TITLE
Fix function name reference

### PR DESCRIPTION
**Pull request by geryogam**

### CODE REVIEW

**Comment by teoli2003** [comment]
Hi!

Please don't use this repository as a sandbox to test GitHub. It is a production repository, and each time numerous reviewers get notified.

To learn GitHub, you can create a new repository. You can delete it afterward.

Thank you!

**Comment by maggyero** [comment]
@teoli2003 It’s not a test, it’s a real PR fixing a typo in the MDN documentation.

**Comment by maggyero** [comment]
@teoli2003 So could you reopen this PR?

**Review by Josh-Cena — APPROVED** [review]
Thank you @maggyero and sorry for the confusion. Welcome to MDN!

**Comment by maggyero** [comment]
Thank you for the review and friendly message @Josh-Cena!

**Pull request merged**
