### PR TITLE
Remove some self-links in Learn area

### PR DESCRIPTION
**Pull request by mathewhodson**
This fixes the broken link flaw "Link points to the page it's already on"

### CODE REVIEW

**Comment by hamishwillee** [comment]
@mathewhodson Not sure about the self link change in the learn module list - we need a more general strategy as this approach is used across the whole Learn area.

The links show up properly as black and unclickable so there is no actual "problem".

**Comment by mathewhodson** [comment]
> The links show up properly as black and unclickable so there is no actual "problem".

You can click on them and they reload the page.

**Comment by hamishwillee** [comment]
That would probably be a bug - the fact they are black tells you that you shouldn't click them.

Either way though, I don't have a problem with deciding that modules don't include the current page, but it would be better if this was agreed and managed globally.

**Review by teoli2003 — APPROVED** [review]
👍

**Pull request merged**
