### PR TITLE
fix: window typo

### PR DESCRIPTION
**Pull request by thestelz**
Fix `Window` to `window` in the syntax example for better copy, paste.

### CODE REVIEW

**Comment by jpmedley** [comment]
Actually, we're removing syntax sections for properties because they're kind of obvious. Would you mind changing this?

**Comment by thestelz** [comment]
@jpmedley Sure! I'll give it a shot

**Comment by thestelz** [comment]
@jpmedley done

**Review by wbamberg — APPROVED** [review]
👍 thank you!

**Pull request merged**
