### PR TITLE
Fix issue 14864: use a different example macro

### LINKED ISSUE #14864: Kumascript example uses {{anch}} macro
### MDN URL

/en-US/docs/MDN/Tools/KumaScript/Troubleshooting

### What specific section or headline is this issue about?

DocumentParsingError

### What information was incorrect, unhelpful, or incomplete?

Kumascript example uses {{anch}} macro.

### What did you expect to see?

A different example.

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/tools/kumascript/troubleshooting`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Tools/KumaScript/Troubleshooting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/tools/kumascript/troubleshooting/index.md
* Last commit: https://github.com/mdn/content/commit/a59a9f4f7015a462c16905403cd315475b7da1de
* Document last modified: 2022-04-05T16:10:17.000Z

</details>

### PR DESCRIPTION
**Pull request by wbamberg**
Fixes [14864](https://github.com/mdn/content/issues/14864).

### CODE REVIEW

**Comment by MrBrain295** [comment]
It doesn’t look like the issue will automatically be closed.

**Comment by wbamberg** [comment]
> It doesn’t look like the issue will automatically be closed when this is merged.

Ooops, try now :).

**Comment by MrBrain295** [comment]
It’s fixed!

**Review by teoli2003 — APPROVED** [review]
Thank you!

**Pull request merged**
