### PR TITLE
Describe what DOMHighResTimeStamp is

### PR DESCRIPTION
**Pull request by ranile**
### Description

Describe what `DOMHighResTimeStamp` is

### Motivation

There is no description about what a `DOMHighResTimeStamp` is supposed to mean. For example, [PushSubscription.expirationTime](https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/expirationTime) states:
> The expirationTime read-only property of the [PushSubscription](https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription) interface returns a [DOMHighResTimeStamp](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp) of the subscription expiration time associated with the push subscription, if there is one, or null otherwise.

There is no telling what the 

### Additional details

From: https://w3c.github.io/hr-time/#sec-domhighrestimestamp

>  A DOMHighResTimeStamp is a double, so it can only represent an epoch-relative time—the number of milliseconds from the Unix epoch to a moment—to a finite resolution. For moments in 2023, that resolution is approximately 0.2 microseconds.

### CODE REVIEW

**Comment by wbamberg** [comment]
I think the origin is not always the Unix epoch, though, is it? [From the spec](https://w3c.github.io/hr-time/#sec-domhighrestimestamp):

> Depending on its context, it may represent the [moment](https://w3c.github.io/hr-time/#dfn-moment) that is this [duration](https://w3c.github.io/hr-time/#dfn-duration) after a base [moment](https://w3c.github.io/hr-time/#dfn-moment) like a [time origin](https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-time-origin) or the [Unix epoch](https://w3c.github.io/hr-time/#dfn-unix-epoch).

That's why [para 2 of the MDN page says](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp):

> The starting time can be either a specific time determined by the script for a site or app, or the [time origin](https://pr26752.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Performance/timeOrigin).

**Comment by wbamberg** [comment]
So rather than updating the definition of `DOMHighResTimestamp` maybe it would be better to update [`expirationTime`](https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/expirationTime) to explain how it is used in that property:

([from the spec](https://w3c.github.io/push-api/#dfn-subscription-expiration-time)):

> A [push subscription](https://w3c.github.io/push-api/#dfn-push-subscription) MAY have an associated subscription expiration time. When set, it MUST be the time, in milliseconds since 00:00:00 UTC on 1 January 1970, at which the subscription will be [deactivated](https://w3c.github.io/push-api/#dfn-deactivate). The [user agent](https://w3c.github.io/push-api/#dfn-user-agent) SHOULD attempt to [refresh](https://w3c.github.io/push-api/#dfn-refresh) the push subscription before the subscription expires.

**Comment by hamishwillee** [comment]
@hamza1311 The response from @wbamberg is correct - do you want to update [PushSubscription.expirationTime](https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/expirationTime) in _this_ PR or should we close it?

**Comment by hamza1311** [comment]
> @hamza1311 The response from @wbamberg is correct - do you want to update [PushSubscription.expirationTime](https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/expirationTime) in _this_ PR or should we close it?

That looks like the correct place, yes. I'm going to close this PR

**Pull request closed without merging**
