### PR TITLE
Format Function reference pages

### PR DESCRIPTION
**Pull request by scffs**
изображение

### CODE REVIEW

**Comment by Josh-Cena** [comment]
MDN style uses double quotes. Could you simply run Prettier over this file instead?

**Review by Josh-Cena — COMMENTED** [review]
MDN style uses double quotes. Could you simply run Prettier over this file instead?

**Review by Josh-Cena — APPROVED** [review]
Actually, doing formatting here is non-trivial, so I've done it myself. Thanks!

**Comment by scffs** [comment]
So if anywhere I see `'` and in the same article see `"` which one I should replace?
Thanks for review

**Comment by Josh-Cena** [comment]
You should replace `'`.

**Pull request merged**
