### PR TITLE
rid of mdn.mozillademos.org in CSS live samples (part 1)

### PR DESCRIPTION
**Pull request by peterbe**
This won't work until https://github.com/mdn/yari/pull/3798 has landed. 

What I did was I found a page that uses `https://mdn.mozillademos.org/files/*` in the CSS `<pre>` tag. I then ran `wget` to download that image file into the same folder as the `index.html`. 
The image flaw checker should be OK with `starsolid.gif` being present where it is even though it can't find a `` in the HTML because the image reference flaw checker only looks for `starsolid.gif` anywhere inside the `index.html` as a string.

### CODE REVIEW

**Comment by peterbe** [comment]
Note that the live sample on https://pr4973.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/background#setting_backgrounds_with_color_keywords_and_images if 404'ing on https://pr4973.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/background/_samples_/starsolid.gif but once https://github.com/mdn/yari/pull/3798 lands (and we re-run this PR) that URL will become https://pr4973.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/background/starsolid.gif and that should work.

**Comment by peterbe** [comment]
Note-to-self; this document was just one of many in  https://gist.github.com/peterbe/7d884d5fe45dd34e49cc0d630979a5dd

**Review by escattone — APPROVED** [review]

**Comment by peterbe** [comment]
This does NOT yet work. 
What happens is that `starsolid.gif` is NOT shipped. 
The `buildDocment()` function returns an array called `fileAttachments` but that array is only populated based on files that are mentioned (and checked!) in `` tags on the page. I think.

**Comment by peterbe** [comment]
Yeah, `const fileAttachments = checkImageReferences(doc, $, options, document);`

**Comment by peterbe** [comment]
We can proceed with this PR once https://github.com/mdn/yari/pull/3848 lands and upgrade `@mdn/yari`.

**Comment by peterbe** [comment]
@escattone Now that `@mdn/yari` has been upgraded, https://pr4973.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/backGrOund works as expected. And you've already reviewed it so I'm going to merge.

**Pull request merged**
