### PR TITLE
alt + picture fix

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/mdn/yari/issues/1498

### CODE REVIEW

**Comment by peterbe** [comment]
This fixes to distinctly different things in one PR: 1) the edit of the `alt` value and 2) changing from a `` to `<picture>`. 
I don't think we should switch to `<picture>` yet.

**Comment by mattiapontonio** [comment]
@peterbe can You reopen, suggest only the alt and so we take half job?

**Comment by peterbe** [comment]
Change the code first. 
Also, note that you deleted the `<p>` too without explanation.

**Comment by mattiapontonio** [comment]
@peterbe yes it's not a paragraph a think.
What happens Is that if I suggest to myself i cannot commit since it's pending review 🤷🏻‍♂️
Anyway I will try something to recommit with a trusted commit.

**Pull request closed without merging**
