### PR TITLE
Fix number of round trips in TLS handshake

### PR DESCRIPTION
**Pull request by geryogam**

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
Hi @geryogam. Thanks for the PR. The actual content changes look useful. However, you've also made a lot of language style changes that make the page inconsistent with the rest of the site:

- We write headings in sentence case, rather than capitalizing the start of all words, so the ones you've changed are unfortunately now all wrong. "TLS Negotiation" for example should be "TLS negotiation".
- We don't really have a fast and hard rule for use of em-dashes, and I know that strictly speaking, typographical best practice suggests that you are meant to not have spaces around them. However, this looks really crappy in body copy on the web, so we started putting spaces around them.
- We also don't have a hard and fast rule for use of suffixes like "MB" and "KB", but generally we tend to put them after the value with no space, and
  - in all caps for file sizes like KB and MB
  - in lowercase for suffixes that also appear in CSS, like s, ms, or deg (we just follow the pattern from CSS)

So, I don't know what you want to do about this, just close this PR and open a new one with the use content changes included, or just revert the changes I've mentioned here as not being particularly helpful.

Thanks again.

**Comment by geryogam** [comment]
Hi @chrisdavidmills, thanks for your detailed review! I have addressed the three points you mentioned.

**Review by chrisdavidmills — APPROVED** [review]
@geryogam great stuff, thanks! I've made a few more small tweaks, and I think this is now ready to merge.

**Comment by geryogam** [comment]
Thank you very much for the review @chrisdavidmills!

**Pull request merged**
