### PR TITLE
Change "<option>s" to "<option> elements"

### PR DESCRIPTION
**Pull request by ya-sh-vardh-an**
### Description

Replace "`<option>`s" with "`<option>` elements" at line `194` in `files/en-us/web/html/element/select/index.md`

### Motivation

I am learning web development and using MDN documentation as source and I feel this is great help. 
(Update: Thanks Josh-Cena for the correcting me)

### Additional details

_No response_

### Related issues and pull requests

None

### CODE REVIEW

**Comment by ya-sh-vardh-an** [comment]
I think I have done mistake somewhere maybe I should fork the repository again and remove the existing one.

**Review by Josh-Cena — COMMENTED** [review]
This is not a typo. It's the plural of `<option>`. If you want to avoid confusion, maybe say "`<option>` elements".

**Comment by ya-sh-vardh-an** [comment]
Thank you but I don't why my PR is showing "flaws(1)". Can you please help me. I am new to this.

**Comment by Josh-Cena** [comment]
It has nothing to do with your PR, so no worries :)

**Review by Josh-Cena — APPROVED** [review]
Sure, thanks :)

**Pull request merged**
