### PR TITLE
Correction for the formal syntax not found issue - 03

### PR DESCRIPTION
**Pull request by ghost**
This is for issue #18780
In this PR I edited the tags of these pages:

- Custom properties
- align-tracks
- justify-tracks
- masonry-auto-flow
- padding-block
- padding-inline
- paint-order
- scrollbar-gutter
- text-decoration-thickness
- text-underline-offset

I simply added **CSS property** tag.

### CODE REVIEW

**Comment by teoli2003** [comment]
> This is for issue #18780
> 
> In this PR I covered:
> 
> 17.https://developer.mozilla.org/en-US/docs/Web/CSS/--_star_ **Resource:** https://www.w3.org/TR/css-variables-1/
> 
This sounds like it should be coming from w3c/webref…

**Comment by najmiehsa** [comment]
@teoli2003 how should I change it?

**Comment by teoli2003** [comment]
Can you double-check the values from w3cub with the ones in mdn/data? If some are different, it would be interesting to double-check.

**Comment by najmiehsa** [comment]
How should I do that? 
Sorry for asking because I am not sure.

**Comment by teoli2003** [comment]
> How should I do that? Sorry for asking because I am not sure. MDN is not retrieving formal syntax data? and this should not be the same as w3doc?

I don't where w3cub is taking its syntax. It isn't a w3c official site, it's just somebody maintaining docs (which is fine).

In mdn/data we were maintaining a list of formal syntax, and I would like to be sure we are completely coherent here:
like there for CSS Properties: https://github.com/mdn/data/blob/main/css/properties.json

**Comment by teoli2003** [comment]
> @teoli2003 how should I change it?

You shouldn't do it manually, we should fix the macro (or webref) to get it from w3c/webref.

Only non-standard features should have hard-coded values.

**Comment by wbamberg** [comment]
@najmiehsa , it looks like this updated all the tags, which I already did in https://github.com/mdn/content/pull/19469 , as noted in https://github.com/mdn/content/issues/18780#issuecomment-1213256936.

If you want to help out with this issue, then I think it would be best to work on the items listed in https://github.com/mdn/content/issues/18780#issuecomment-1213231721: these are nonstandard items for which we want to hardcode the formal syntax.

"hardcode the formal syntax" means: find the formal syntax entry for the item in the [mdn/data repository](https://github.com/mdn/data) and copy it into the page, inside a [Markdown `<pre>` block](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#example_code_blocks).

For example, considering the first in this list, https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-float-edge. You can find the entry for it in mdn/data, in the "properties.json" file: https://github.com/mdn/data/blob/80aedce42a7f3a523a17e54ba87b0680ee171daf/css/properties.json#L936-L951. The formal syntax is in the "syntax" key and is given as "border-box | content-box | margin-box | padding-box".

So copy that value, and in https://github.com/mdn/content/blob/main/files/en-us/web/css/-moz-float-edge/index.md, replace `{{csssyntax}}` with the value, inside a Markdown `<pre>` block, like:

````
```
border-box | content-box | margin-box | padding-box
```
````

I think it would be good to submit an initial PR fixing just the https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-float-edge, to be sure you have the right idea. Then you can submit another fixing the rest.

Thanks for your help!

**Comment by najmiehsa** [comment]
@wbamberg I've already edited the other PR based on this.

**Pull request closed without merging**
