### PR TITLE
Fix analogy for chained promises #33742 

### PR DESCRIPTION
**Pull request by Ashish-CodeJourney**
### Description

wrote a description that accurately reflects the sequential nature of promise chains

### Motivation

 A correct explanation would clarify that promises in a chain are executed in the order they are created, with each promise waiting for the previous one to resolve.

### Related issues and pull requests

Fix #33742

### CODE REVIEW

**Comment by Maddily** [comment]
Thanks for creating this PR. This addresses the issue I raised in [issue #33788](https://github.com/mdn/content/issues/33788).

**Comment by wbamberg** [comment]
> > Thanks for creating this PR. This addresses the issue I raised in [issue #33788](https://github.com/mdn/content/issues/33788).
> 
> waiting for approving review by Josh-Cena

Please don't tag people the day after opening a PR. Reviewers already have a queue they are working through, and they'll get to your PR when they can. Tagging people like this just adds extra noise in their notifications and general stress. If you're not getting any review in a couple of weeks or so it is fine to ask for an update IMO.

**Comment by Ashish-CodeJourney** [comment]
> > > Thanks for creating this PR. This addresses the issue I raised in [issue #33788](https://github.com/mdn/content/issues/33788).
> > 
> > 
> > waiting for approving review by Josh-Cena
> 
> Please don't tag people the day after opening a PR. Reviewers already have a queue they are working through, and they'll get to your PR when they can. Tagging people like this just adds extra noise in their notifications and general stress. If you're not getting any review in a couple of weeks or so it is fine to ask for an update IMO.

Yes, sorry I will keep this in mind

**Review by Josh-Cena — APPROVED** [review]
I don't terribly like the queue analogy either, because the promises themselves are not tasks; the actions associated with them are. I've tried rewriting it a bit so it's at least fully accurate. @Maddily please let me know if this explanation makes sense to you.

**Comment by Maddily** [comment]
@Josh-Cena Thanks for taking the time to rewrite the explanation and make it clearer. I appreciate it.
I went through your changes and they look great. Here are a few thoughts:
- The way you explain `catch()` and `finally()` as essentially using `then()` internally is really clear and helpful.
- I like the new terms initial promise and new promise. They make the explanation easier to follow. The detailed steps about which handler runs based on the promise's state are very clear.
- The new details about how the returned value or thrown error from a handler affects the new promise are very helpful. It adds clarity on how to manage promise states effectively.
- The new explanation about how promises work with the job queue and event loop is much clearer.
- Clarifying how a promise can be part of multiple chains and how settled promises are handled is very clear and understandable now.

Overall, these changes make the whole concept much easier to understand. Thanks again for improving the explanation and for addressing my initial feedback.

**Pull request merged**
