### PR TITLE
chore: Remove FF project issue template

### PR DESCRIPTION
**Pull request by nschonni**
### Description

@Rumyra I think you've migrated all these flows over to the mdn/mdn repo like https://github.com/mdn/mdn/issues/281

### CODE REVIEW

**Comment by bsmth** [comment]
Thanks @nschonni - I think the `mdn/mdn` ones are just tracker issues, we're still using this template as far as I know.

**Comment by Rumyra** [comment]
Hey @nschonni - project flows stem from mdn/mdn, but the issue template here is for Firefox release updates/tasks and they stay on content so we need to keep this template 👍

**Comment by Rumyra** [comment]
Thank you tho :)

**Comment by nschonni** [comment]
OK, may be worth converting to the YAML form if it's sticking around

**Pull request closed without merging**
