### PR TITLE
WebExtensions - fix up all the tags except for apis

### PR DESCRIPTION
**Pull request by hamishwillee**
Fixes up all WebExtension tags. Yes, this is a huge PR. But then only one review. I scanned through them all and script still seems to be working well.

Part of https://github.com/mdn/mdn/issues/262

### CODE REVIEW

**Comment by wbamberg** [comment]
@rebloor , I've assigned this for you but if you like I am happy to review it.

**Comment by wbamberg** [comment]
Actually one thing I would say is that this PR adds a lot of `non-standard` status values, which if we then start using that to drive "non-standard" banners, will mean we will add lots of these banners to the pages, which they don't currently have.

So in this PR we should suppress `non-standard`.

Note that the BCD does **not** list these features as non-standard, which is a good thing since it means the automation that keeps `status` in sync with BCD will not cause this to break.

**Comment by rebloor** [comment]
@wbamberg seems like you might be on the ball with this one. Would you like to finish commenting and reviewing? From my POV your comment about `non-standard` makes sense. Otherwise, I'm happy to spot-check the changes and approve on that basis. The number of files changed and the impact this has on the performance of the files tab makes much more impractical.

**Comment by wbamberg** [comment]
Thanks @rebloor . I'm happy to review :). But actually I agree about the size of this, because GitHub hides diffs beyond a certain number of files.

@hamishwillee could you split this into say 3 PRs, as well as remove `non-standard` as mentioned in https://github.com/mdn/content/pull/25117#issuecomment-1457260926 ? (non-standard is weird for WebExtensions, so I think it is OK to omit it).

**Comment by hamishwillee** [comment]
Sure! This is now all the webext except for /api - with "non-standard" removed. There are still some "deprecated". New PRs to follow for APIs.

**Comment by hamishwillee** [comment]
FYI @rebloor @wbamberg

**Review by wbamberg — APPROVED** [review]
🎉

**Comment by pars0900** [comment]
Please reverse this action

**Pull request merged**
