### PR TITLE
ondragend: Update and convert static code example to live example

### LINKED ISSUE #11364: Content suggestion: Convert drag and drop event examples to live examples
## What is the new suggestion?

To convert the **static code examples** on the following pages to a **live example**:

 - [x] https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragend

- [x] https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragleave

- [x] https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragover

- [x] https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragstart

- [ ] https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondrop

## Why is it important or useful?

Having live examples will make the concept be understood well for the readers, like I converted for `ondragenter` in PR #8667
## Other supporting information
I'd like to follow upon https://github.com/mdn/content/pull/8667#issuecomment-913198125 and replace static code in the above pages with working live samples.

### PR DESCRIPTION
**Pull request by AnilSeervi**
#### Summary

Convert static `ondragend` code example to a live example
#### Motivation

Open-source
#### Related issues

partially adresses #11364 
#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by AnilSeervi** [comment]
is the syntax correct or should is look something like :
```js
targetElement.ondragend = dragendHandler;
```

or

are both valid syntax like on this page - https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onmouseenter
```js
element.onmouseenter = handlerFunction;
var handlerFunction = element.onmouseenter;
```

**Comment by wbamberg** [comment]
> is the syntax correct or should is look something like :
> 
> ```js
> targetElement.ondragend = dragendHandler;
> ```
> 
> or
> 
> are both valid syntax like on this page - https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onmouseenter
> 
> ```js
> element.onmouseenter = handlerFunction;
> var handlerFunction = element.onmouseenter;
> ```

Sorry, I don't understand - are you referring to https://github.com/mdn/content/pull/11365/files#diff-b89bc6eb14bb33cf8205bc714ca9ab382d125293d70589fa9d1c3e2afa9de0edR113

```js
source.ondragend = dragend_handler;
```

? Because that is the same syntax as `targetElement.ondragend = dragendHandler;`, isn't it? One difference is `dragendHandler` (camelCase) versus `dragend_handler` (snake_case), is that what you meant? For that, camelCase is preferred in our sample code.

**Comment by AnilSeervi** [comment]
I was referring to the `Syntax` section of the page where the syntax is defined as : 
```js
var dragendHandler = targetElement.ondragend;
```

**Comment by wbamberg** [comment]
Oh I see! No, it should be something like:

```js
element.ondragend = handlerFunction;
```

**Comment by AnilSeervi** [comment]
> Oh I see! No, it should be something like:
> 
> ```js
> element.ondragend = handlerFunction;
> ```

There are many pages with the syntax shown in that format!

**Comment by wbamberg** [comment]
Eventually these `on-*` pages are going to go away and we will have a single page for each event. See https://github.com/mdn/content/discussions/9098 . So I don't think it's worth updating lots of syntax values now. 

I hope we will be able to adapt and integrate the live samples you are making, so your work in this PR is not wasted. @Elchi3 , what do you think?

**Review by wbamberg — CHANGES_REQUESTED** [review]
Thanks @AnilSeervi ! This looks fine but I think it really helps readability to have some whitespace. See https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragenter#javascript for example.

**Review by wbamberg — APPROVED** [review]
Thank you @AnilSeervi!

**Review by Elchi3 — APPROVED** [review]
Definitely not wasted work, the example will appear on new-style event pages, too.

**Pull request merged**
