### PR TITLE
Improve Media Queries diagram

### PR DESCRIPTION
**Pull request by SphinxKnight**
### Description

An improvement for the existing diagram incl. complementary wording in the alternative text.

### Motivation

I was translating/updating the article in French and I couldn't understand the added value of the diagram in the page since there was no content in the mobile viewport. Plus the text "Media Queries" at the top was not really necessary in my opinion.

### Additional details

Source of the diagram: https://gist.github.com/SphinxKnight/13d5579d400c84efa78a830a887fd0a6

### CODE REVIEW

**Comment by bsmth** [comment]
Thanks for the improvement! Out of curiosity; do you have an SVG version that we can replace the binary with? I think this might be nice to do for maintenance as we can edit in a vector editor in future and reduce bins in the repo.

**Comment by SphinxKnight** [comment]
Yeah I can export that. Will do when back in front of the computer:)

**Review by wbamberg — APPROVED** [review]
👍 much better, thank you @SphinxKnight !

**Comment by wbamberg** [comment]
Oh sorry @bsmth , I had this tab open when we started our SC meeting and just merged when I got back, and missed your comments!

**Comment by bsmth** [comment]
> Oh sorry @bsmth , I had this tab open when we started our SC meeting and just merged when I got back, and missed your comments!

No problem, looks like we can fix in a follow up 👍

**Comment by SphinxKnight** [comment]
> > Oh sorry @bsmth , I had this tab open when we started our SC meeting and just merged when I got back, and missed your comments!
> 
> No problem, looks like we can fix in a follow up 👍

Sure thing, I'll open another one in the coming hours :)

**Pull request merged**
