### PR TITLE
Delete cubic bezier tool

### PR DESCRIPTION
**Pull request by wbamberg**
This PR deletes https://developer.mozilla.org/en-US/docs/Web/CSS/Tools/Cubic_Bezier_Generator, which has never been a usable tool in the many years since it was started, and which we have no plans to finish.

### CODE REVIEW

**Comment by teoli2003** [comment]
Sniff, but yes, we have to do it!

**Comment by wbamberg** [comment]
Sorry @teoli2003 ! I hadn't realized this was yours!

**Comment by teoli2003** [comment]
No worry. I was experimenting with tooling before proposing a Summer Of Code project. But the back-end and the ressources were not adapted back then.

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
merging while @teoli2003 cries on my shoulder at little

**Pull request merged**
