### PR TITLE
Corrected `buttonText` & `buttonFace` definitions

### PR DESCRIPTION
**Pull request by MahdiAljazairi**
#### Summary
Reflipped the definitions.

#### Metadata
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by teoli2003** [comment]
@MahdiAljazairi : This looks good. Just curious: how did you test/find this? (I can't check as I don't have IE right now).

**Comment by MahdiAljazairi** [comment]
Needn't be tested.. since `buttonText` obviously doesn't refer to background color 🙂

**Comment by teoli2003** [comment]
I am more unsure about buttonFace ;-)

**Review by estelle — APPROVED** [review]
good catch!

**Pull request merged**
