### PR TITLE
updated popup interaction code with working code

### PR DESCRIPTION
**Pull request by ShamarYarde**
### Description
Previous version of code wouldn't produce desired results.

### Motivation
To allow readers to understand how to interact with the popup in the [Testing your element](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment#testing_your_element) example, i.e. print string from popup to the reader's console.

### CODE REVIEW

**Review by hamishwillee — COMMENTED** [review]
Thanks @ShamarYarde . Wrapping the code in an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) makes sense to me because otherwise this code would just fall through on load.

Do you think it worth explaining the code uses an IIFE and why?

**Comment by ShamarYarde** [comment]
@hamishwillee You could. I looked through the previous MDN JavaScript tutorial, but I see no mention of it.

**Review by hamishwillee — APPROVED** [review]
I'll add IIFE to your other doc.

Best to make only one PR per doc - having lots that might touch the same area of the doc is a recipe for clashes to resolve.

**Comment by hamishwillee** [comment]
> 

Arrgg. This actually did clash with https://github.com/mdn/content/pull/31050 - I've ended up with the changes in that one.

**Pull request merged**
