### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by VGBijpuria**
### Description

Adding Canvascript in the list of tools in the HTML canvas page of MDN web docs

### Motivation

The purpose of the list of tools section is to navigate readers to relevant resources that can easily help them in their code. Canvascript is an open-source no-code tool that allows developers to easily render their drawings in the HTML canvas without mapping out every single coordinate. It thus allows readers cum users of the canvas to quickly create graphics without this tiresome step.

### Additional details

This is the link to the repo-
https://github.com/VBproDev/Canvascript

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks for your PR, @VBproDev !

MDN's very conservative about adding links to third-party tools, because of the risk that a tool will not be well maintained in the future. So when we consider adding a new tool we always look for a few things, including:

- evidence that it's a really essential tool for a lot of developers
- evidence of a lot of usage by web developers
- a long track record of maintenance

At the moment your tool doesn't meet these criteria, so I'm going to close this PR, while wishing you the best of luck with your project.

**Comment by VBproDev** [comment]
@wbamberg can you specify what are the requirements in solid numbers?

**Comment by wbamberg** [comment]
No, we don't have numbers. It's a judgement call by individual maintainers.

**Comment by VBproDev** [comment]
@wbamberg for the second point I must say that I have contributed less than 20% of it's current codebase, so it would make it the opposite of a one man project. But anyway, thanks for giving your time. Maybe I will raise this PR again after 2-5 years :)

**Pull request closed without merging**
