### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by HoldOffHunger**
This is resuming after x-many milliseconds, not seconds.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thanks for this PR, @HoldOffHunger !

According to [the spec](https://wicg.github.io/speech-api/#dom-speechsynthesisevent-elapsedtime) this is seconds:

> **elapsedTime attribute, of type float, readonly**
>      This attribute indicates the time, in seconds, that this event triggered, relative to when this utterance has begun to be spoken.

Do you have a reason to believe that this is not correct?

**Comment by HoldOffHunger** [comment]
Hey hey,

I was just about to put together that note, but I decided to test a bunch of browsers first.  Firefox (V. 93), Edge, Brave, and Chrome all report this in milliseconds.  They're not all the same, though; Edge and FF report only integer values, while Chrome seems to go off to the 8th or 9th decimal point.  But they all seem to be milliseconds.  That's odd that it's showing seconds for you, this can't be controlled by some internal, OS config, can it?

Thanks for confirming and letting me know that there might be issues with other browsers.  Probably good to think about on "experimental technology."

**Comment by wbamberg** [comment]
> Hey hey,
> 
> I was just about to put together that note, but I decided to test a bunch of browsers first. Firefox (V. 93), Edge, Brave, and Chrome all report this in milliseconds. They're not all the same, though; Edge and FF report only integer values, while Chrome seems to go off to the 8th or 9th decimal point. But they all seem to be milliseconds. That's odd that it's showing seconds for you, this can't be controlled by some internal, OS config, can it?

I'm on macOS. Like you I see milliseconds on Firefox release (93) and Chrome, but apparently seconds on Firefox Nightly (95, and my default browser) and Safari. Do you see that as well?

**Comment by HoldOffHunger** [comment]
> I'm on macOS. Like you I see milliseconds on Firefox release (93) and Chrome, but apparently seconds on Firefox Nightly (95, and my default browser) and Safari. Do you see that as well?

I do indeed see seconds for FF Nightly, wasn't able to test Safari but I'll take your word for it.  Hrm, okay, let me see about adding in that note now.

**Comment by HoldOffHunger** [comment]
Hey, how does this look?

https://github.com/mdn/content/pull/10179

**Comment by wbamberg** [comment]
Closed, since I think this is covered in https://github.com/mdn/content/pull/10179.

**Pull request closed without merging**
