### PR TITLE
Fix aria-expanded & aria-haspopup links in “ARIA: button role”

### PR DESCRIPTION
**Pull request by merciermk**
Add 2 missed links on aria page

> What was wrong/why is this fix needed? (quick summary only)

> MDN URL of main page changed

> Issue number (if there is an associated issue)

> Anything else that could help us review it

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
@merciermk Thanks much for this update, and congrats on landing your first docs change here — welcome aboard 🎉

**Comment by sideshowbarker** [comment]
@merciermk There’s something odd and unusual which happened with this PR: The PR somehow got set to be merged against the `minorFixes` branch, rather than the `main` branch.

Do you have any idea how that might have happened?

The same thing actually happened with your other PR, https://github.com/mdn/content/pull/4801 (but I subsequently switched the target branch to `main` before merging it).

Did you use the GitHub web UI to create this PR? Or did you use the GitHub Desktop client? Or something else?

**Comment by merciermk** [comment]
Hello!
I m sorry for this inconvenient.

I use GitHub desktop for the pull request. I don't know what I did wrong. 

What can I do to fix that mistake?

**Comment by sideshowbarker** [comment]
@merciermk I think you didn’t do anything wrong but instead there might be a bug in GitHub Desktop which caused it — because the same thing happened with a different pull request, https://github.com/mdn/content/pull/4769.

Regardless, there’s nothing you need to do at this point to fix it — I already merged the commits to the `main` branch. So we got all your content changes in — so thanks again very much.

**Pull request merged**
