### PR TITLE
Restore StrictMode wrapper

### PR DESCRIPTION
**Pull request by geryogam**

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
We probably need to update the explanation above as well. I can't remember why we removed `StrictMode`—maybe check git history?

**Comment by geryogam** [comment]
> We probably need to update the explanation above as well.

What do you suggest?

> I can't remember why we removed StrictMode—maybe check git history?

I checked and there was no StrictMode from the start at this place in the tutorial, whereas StrictMode is used at every other mentions of index.js contents in the tutorial and in the code repository, so I think it was an oversight.

**Comment by Josh-Cena** [comment]
> What do you suggest?

The paragraph that says "Line 8 calls..." definitely needs to be updated to say "Renders the `App` component in strict mode (with link to the React docs)".

**Comment by geryogam** [comment]
> > What do you suggest?
> 
> The paragraph that says "Line 8 calls..." definitely needs to be updated to say "Renders the `App` component in strict mode (with link to the React docs)".

I agree as I myself had to Google what is React’s strict mode while doing the tutorial. Updated.

**Review by Josh-Cena — APPROVED** [review]
TBH, React 18's `StrictMode` was quite controversial, especially effect double-firing. I work on a few React toolings and have interacted with new learners, so I can tell you that `StrictMode` is not the greatest tool for pedagogy... But since it's present in the init template (right?) I think it's best we keep it.

**Comment by geryogam** [comment]
Thanks!

**Comment by geryogam** [comment]
> But since it's present in the init template (right?) I think it's best we keep it.

Yes `React.StrictMode` is present from the start in the create-react-app template (https://github.com/facebook/create-react-app/blob/main/packages/cra-template/template/src/index.js) to the end in the Todo app (https://github.com/mdn/todo-react/blob/main/src/index.js).

**Comment by wils81ouwehand** [comment]
I doint understand this shit  my englis sucks
.please send it i  dutch netherlands  .iam not  good whit it

w ouwehand

Op ma 22 mei 2023 23:49 schreef Géry Ogam ***@***.***>:

**Pull request merged**
