### PR TITLE
chore: add JSON linting scripts

### PR DESCRIPTION
**Pull request by nschonni**
This pins the dependienes and adds the scripts to align with the Markdownlint CI.
This could alternately be swapped with prettier like the open YML lint PR instead of ESLint

### CODE REVIEW

**Comment by schalkneethling** [comment]
> This could alternately be swapped with prettier like the open YML lint PR instead of ESLint

Thank you for getting this in place, @nschonni. As it is a standard across our repositories to use Prettier for this kinda work, I would say we should do the same here. Thanks

**Review by bsmth — APPROVED** [review]
Looks good to me, thanks 👍🏻

**Comment by schalkneethling** [comment]
> @schalkneethling I've swapped to the default Prettier formatter. I could use the JSON.stringify one to reduce the folding of arrays to the same line if that would be better

I reckon this look and works well, thanks @nschonni

**Review by schalkneethling — APPROVED** [review]
🎉

**Pull request merged**
