### PR TITLE
Remove `PaintSizes` dead link

### PR DESCRIPTION
**Pull request by dawei-wang**
mdn/content#33681

### CODE REVIEW

**Comment by hamishwillee** [comment]
Would you prefer to just document the interface? It is supported in browsers https://github.com/mdn/browser-compat-data/blob/main/api/PaintSize.json and is very simple https://drafts.css-houdini.org/css-paint-api/#paintsize

**Comment by pepelsbey** [comment]
> Would you prefer to just document the interface?

I agree. It would be better to have a barebone page instead of no page.

**Comment by Josh-Cena** [comment]
@dawei-wang, are you interested in creating this page? If not let's close this PR.

**Comment by pepelsbey** [comment]
By the way, `PaintRenderingContext2D` is also missing: [see the list of interfaces](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Painting_API#interfaces). Let’s remove them both from the sidebar until they’re documented.

**Comment by Josh-Cena** [comment]
I'm going to close this. The linked issue already mentions `PaintRenderingContext2D`. We should just add the docs instead.

**Pull request closed without merging**
