### PR TITLE
Fix beastify code

### PR DESCRIPTION
**Pull request by aloopuri**
### Description
The code displayed on ['your second extension'](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_second_WebExtension#testing_it_out) features a bug which blanks out the page

I requested a fix here https://github.com/mdn/webextensions-examples/pull/505

This pull request is to keep both repos aligned

### CODE REVIEW

**Comment by estelle** [comment]
Is it possible to change the other code instead? It feels like a regression away for suggested best practices.

**Comment by aloopuri** [comment]
Could you please clarify what the other code you are referring to is?

If you are talking about changing the css class name "button" like you did [here](https://github.com/mdn/content/pull/21410#issuecomment-1278495245), I can rename it.

**Comment by estelle** [comment]
in reference to "to keep both repos aligned" -- i meant the other repo; the one you were referring to in your original comment.

**Comment by aloopuri** [comment]
So what should I do now then?

**Comment by aloopuri** [comment]
Now that my pull request has been merged in the other repo, I have updated this page with the relevant changes.

**Comment by aloopuri** [comment]
Hey @estelle. I'm just pinging you for a review on my pull request. My code has been [approved](https://github.com/mdn/webextensions-examples/pull/505) now.

**Comment by bsmth** [comment]
Thanks for your submission @aloopuri. There's a conflict that has to be resolved, would you like to take a look?

**Comment by aloopuri** [comment]
Thanks for telling me @bsmth. I have resolved the merge conflict.

**Review by bsmth — APPROVED** [review]
Looks good to me, thanks. @willdurand or @estelle - any objections to merging?

**Comment by willdurand** [comment]
I suppose it's fine.

**Comment by schalkneethling** [comment]
Welcome to the community, @aloopuri  🎉 Thank you for your contribution. If you are interested in more ways to contribute to MDN Web Docs, please have a look at our [contributor task board](https://github.com/orgs/mdn/projects/25). If you have any questions or need help finding something to work on, please ask for help in our [community discussions](https://github.com/orgs/mdn/discussions). We look forward to more of your contributions. 🙌

**Pull request merged**
