### PR TITLE
specify absolute and relative font-size values multipliers

### PR DESCRIPTION
**Pull request by UniBreakfast**
### Description

specify absolute and relative font-size values multipliers

### Motivation

had to search for it elsewhere while expected that to be specified at MDN

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
We already have the information here: https://developer.mozilla.org/en-US/docs/Web/CSS/absolute-size so you should just link to this page in the "Values" list. In any case, we don't add these kinds of comments in syntax blocks.

**Comment by bsmth** [comment]
Thanks, both. @UniBreakfast are you able to make the suggestion from Josh?

**Comment by UniBreakfast** [comment]
> Thanks, both. @UniBreakfast are you able to make the suggestion from Josh?

I'm not sure how to do that properly.

**Comment by bsmth** [comment]
> I'm not sure how to do that properly.

That's okay, one of the team can do this on your branch here if that's alright.

**Comment by Josh-Cena** [comment]
@bsmth Do you think you could make the change (add the link) and then I can review it?

**Review by Josh-Cena — APPROVED** [review]

**Pull request merged**
