### PR TITLE
fix inaccuracy section "in Precedence order of regular cascade layers"

### PR DESCRIPTION
**Pull request by eranww**
"@import url(C.css);" does not create an unnamed layer, but appends to the implicit layer of unlayered styles.

### Description

Fixed an inaccuracy: using "@import url(C.css);" doesn't create a new unamed layer. but appends the C.css styles into the final unlayered layer styles.
### Motivation

Fix an inaccuracy on the docs.

### CODE REVIEW

**Review by chrisdavidmills — COMMENTED** [review]
Thanks for your contribution, @eranww. I'm currently picking through the spec trying to make sure I understand this change, as it seems like quite a subtle change. I mean, you could argue that the implicit layer is also unnamed, so the old text and the new text both sound kinda right ;-)

However, looking at https://drafts.csswg.org/css-cascade-5/#unnamed-layers, what you are saying is that for an import to be put in an unnamed (or anonymous) layer, you'd need to include the `layer` keyword after the import, just without a name, correct?

Whereas in the example on this page, the `layer` keyword is not included, so the CSS is included in the implicit layer (the spec says "any declaration not assigned to an explicit layer is added to an implicit final layer")?

**Review by estelle — APPROVED** [review]
Thank you! Good catch. 🎉

**Comment by eranww** [comment]
> Thanks for your contribution, @eranww. I'm currently picking through the spec trying to make sure I understand this change, as it seems like quite a subtle change. I mean, you could argue that the implicit layer is also unnamed, so the old text and the new text both sound kinda right ;-)
> 
> However, looking at https://drafts.csswg.org/css-cascade-5/#unnamed-layers, what you are saying is that for an import to be put in an unnamed (or anonymous) layer, you'd need to include the `layer` keyword after the import, just without a name, correct?
> 
> Whereas in the example on this page, the `layer` keyword is not included, so the CSS is included in the implicit layer (the spec says "any declaration not assigned to an explicit layer is added to an implicit final layer")?

Yes, exactly. My intention was to emphasize that a new layer is not created when omitting the 'layer' keyword.
In this article, the author is using the terms "unnamed layer" and "anonymous layer" interchangeably, therefore I think this change would reduce confusion for future readers.

**Review by chrisdavidmills — APPROVED** [review]
Perfect, makes sense to me. Thanks for the useful contribution @eranww!

**Pull request merged**
