### PR TITLE
[Markdown] [Web/SVG] Convert Web/SVG to Markdown - DO NOT SQUASH MERGE

### PR DESCRIPTION
**Pull request by wbamberg**
See https://github.com/mdn/content/issues/8969 for the "preparation" work.

This PR converts Web/SVG to Markdown.

Conversion report summary:

```
## All unhandled elements

- table.properties (473)
- table.no-markdown (247)
- sub (48)
- table.fullwidth-table (1)
```

Full conversion report: https://gist.github.com/wbamberg/03b1ada19cd261927560c44a56ec4b6b

The only unconverted elements are `<sub>` and tables.

## \<sub>

For `<sub>`: these elements only occur in four files:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/diffuseConstant
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/specularConstant
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feConvolveMatrix

For such a small number of pages it seemed better to keep them, as we have in other places (https://github.com/mdn/content/issues/7898#issuecomment-910843992).

## \<table>

For `<table>`, most uses of `<table>` are either `.properties` tables, which are all staying as HTML, or specifications tables.

The specifications tables are generally Markdown-compatible, but they are almost all wider than the 150-character max width that we have adopted for GFM tables (https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#gfm_table_maximum_width).

In fact the narrowest spec table was 137 chars wide, and only about 30 spec tables out of about 240 are less than 150 chars wide. So it seemed better to be consistent here and just suppress table conversion throughout.

### CODE REVIEW

**Comment by wbamberg** [comment]
To coordinate reviews I've created https://docs.google.com/spreadsheets/d/1ddI7K0uy0ZDyefFSC2hnNxiaO_xm3lBX4gFEC0zPDZM/edit#gid=0

As before, the purpose of this is just to ensure different people review different pages.

**Comment by Rumyra** [comment]
I took a tiny few and added some notes to the spreadsheet

**Comment by wbamberg** [comment]
> I took a tiny few and added some notes to the spreadsheet

Thanks! For your comment on http://localhost:5000/en-US/docs/Web/SVG/attribute/display "Code inside table", is that a comment about the terrible contrast? Because that's a Yari issue, that I would love to have fixed, but not one I can do anything about.

**Review by teoli2003 — APPROVED** [review]
I added three commits to fix oddities (not sure it was the conversion, but they were trivial to fix).

For me, it is good to merge. @wbamberg I let you make the call.

**Comment by teoli2003** [comment]
(There was a 2nd occurrence of "note inside table" that is far too dark, but that's yari, not the conversion.

**Comment by wbamberg** [comment]
Thanks @Rumyra and @teoli2003 for the reviews!

**Pull request merged**
