### PR TITLE
Fix lint error and add requested changes #7563

### PR DESCRIPTION
**Pull request by AnilSeervi**
- Changes requested in #7563
- Fix line-length to within 80 characters to pass linter test

### CODE REVIEW

**Comment by AnilSeervi** [comment]
Does this seem ok? @teoli2003

**Comment by teoli2003** [comment]
Mmmh, why is this is a separate PR?

**Comment by AnilSeervi** [comment]
> 
> 
> Mmmh, why is this is a separate PR?

Sorry about that. I couldn't find how to commit to the same PR.

**Comment by teoli2003** [comment]
I'm ok to merge this or the orignal PR: can you coordinate with the creator of the original PR, by asking them in the other PR?

**Comment by sideshowbarker** [comment]
> Mmmh, why is this is a separate PR?

I have the same question.

I have difficulty seeing why this PR is necessary, and why it was created to begin with.

#7563 remains open and the intent is to fix the brokenness in the linter so that #7563 gets unblocked.

As far as I see, what this PR, #7583, is doing is what has already been intentionally decided not to do — which is, to re-wrap the text just to make the broken linter happy.

If we wanted to re-wrap the text, that could be done in the #7563 PR branch — without needing this separate PR to do it.

**Comment by sideshowbarker** [comment]
Superseded by #7563 — which has now been merged — so let’s go ahead and close this

**Review by SirJosh1987 — COMMENTED** [review]
Please help me

**Pull request closed without merging**
