### PR TITLE
32 new interactive examples

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
#### Summary
This PR adds 32 new interactive examples to pseudo-classes, pseudo-elements, font-variant-east-asian and few functions.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by NiedziolkaMichal** [comment]
Some of them may still not be available, as they were merged today in interactive examples repo.

**Comment by teoli2003** [comment]
> Some of them may still not be available, as they were merged today in the interactive examples repo.

But all of these have been merged? Am I correct?

**Comment by NiedziolkaMichal** [comment]
@teoli2003 Yes

**Comment by teoli2003** [comment]
All of the pseudo-classes examples, and only these ones (not the functions or pseudo-elements). I find this strange. Let's wait a bit to see if they appear in a day or so.

**Comment by NiedziolkaMichal** [comment]
When I checked [any interactive example page](https://interactive-examples.mdn.mozilla.net/pages/tabbed/aside.html), their last-modified date is Tue, 28 Jun 2022 13:09:59 GMT. [All of the merges](https://github.com/mdn/interactive-examples/commits/main) were done after that date and I think that's the reason examples are not available.

**Review by teoli2003 — APPROVED** [review]
Thanks to @schalkneethling who regenerated the production website, they all work now.

**Pull request merged**
