### PR TITLE
fix: Remove placeholder "Image:" alt text

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@peterbe figured out the commit signing with https://github.com/pstadler/keybase-gpg-github
This might conflict with your other PR 😉

**Review by peterbe — APPROVED** [review]

**Comment by peterbe** [comment]
Please go ahead and merge in `main` and ping me.

**Comment by nschonni** [comment]
@peterbe rebased

**Review by peterbe — APPROVED** [review]

**Comment by peterbe** [comment]
And signed commit too! 🎉

**Pull request merged**
