### PR TITLE
Add missing 'Literal' page to Glossary

### LINKED ISSUE #1385: Feature request in "MDN Web Docs Glossary": 'Literal' is missing.
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary

#### What information was incorrect, unhelpful, or incomplete?

The concept 'literal' is missing. 

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Glossary

#### What did you expect to see?

A definition of 'literal' like: https://en.wikipedia.org/wiki/Literal_(computer_programming)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/glossary/index.html
* Report started: 2021-01-16T10:06:51.981Z

</details>

### PR DESCRIPTION
**Pull request by tannerdolby**
Fixes #1385 

After merging with the upstream `main` branch, it looks like the merge commits stuck around. Let me know if this is a problem and I can try doing a rebase to drop those commits and submit a PR with only the "Add page to glossary for Literal" commit.

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
I think your definition is good, but it might be nice to show a couple of examples, for example a string literal and an object literal?

**Comment by tannerdolby** [comment]
@chrisdavidmills Ok sounds good. I will add those examples. Also, the definition I used is from [MDN - Grammar and types](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#literals)

**Comment by sideshowbarker** [comment]
I suggest also including the following bulleted list of links to specific types of literals:

```html
<ul>
 <li><a href="/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Array_literals">Array literals</a></li>
 <li><a href="/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Boolean_literals">Boolean literals</a></li>
 <li><a href="/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Floating-point_literals">Floating-point literals</a></li>
 <li><a href="/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Numeric_literals">Numeric literals</a></li>
 <li><a href="/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Object_literals">Object literals</a></li>
 <li><a href="/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#RegExp_literals">RegExp literals</a></li>
 <li><a href="/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#String_literals">String literals</a></li>
</ul>
```

**Comment by tannerdolby** [comment]
@sideshowbarker Good idea, I added that bulleted list of literal links to the page.

@chrisdavidmills I added examples for String literals and Object literals. Let me know if we should include anything else.

**Comment by Ryuno-Ki** [comment]
I can only think of template string literal (could be another „string literal” example).
Nice work!

**Comment by tannerdolby** [comment]
Thanks @Ryuno-Ki! Yeah I didn't include an example of template literals since it would make this Glossary page quite long. But I'm happy to add it if requested.

**Comment by sideshowbarker** [comment]
> Yeah I didn't include an example of template literals since it would make this Glossary page quite long. But I'm happy to add it if requested.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#string_literals — which the bulleted list links to — includes a detailed description of template literals. So I think we’re already covered.

**Comment by tannerdolby** [comment]
@sideshowbarker Ok sounds good. Thanks for the heads up

**Review by chrisdavidmills — APPROVED** [review]
Looks good to me; thanks @tannerdolby !

**Comment by tannerdolby** [comment]
Great, your welcome @chrisdavidmills !

**Pull request merged**
