### PR TITLE
Add references to HTTP Link header

### PR DESCRIPTION
**Pull request by mb**
#### Summary
Add relevant rfc and mdn document to http link header page.

#### Motivation
Was searching for attribute meaning of the link header. Found it in the http link attribute. Adding the reference for better discoverability. Added link to rfc for better discoverability too.

#### Supporting details
* RFC8288 Section 3: https://datatracker.ietf.org/doc/html/rfc8288#section-3

#### Metadata

This PR…
-->
- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by hamishwillee — COMMENTED** [review]
Thanks @mb! The `{{Specifications}}` and `{{Compat}}` macros are supposed to import the required [specification data](https://httpwg.org/specs/rfc8288.html#header) from the [BCD](https://github.com/mdn/browser-compat-data) repository. In theory the "right" way to fix this is to add a BCD entry for the header.

@mnot I am contemplating adding a browser compatibility entry for the Link HTTP header. Sometimes  browser compatibility is a meaningless term for HTTP headers, but it seems to me that a browser that uses this is essentially sending early request for resources - so support is meaningful. If so, would compatibility match the [link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#browser_compatibility) HTML element?

**Comment by mnot** [comment]
The problem is that link, on its own, doesn't do anything -- it's really just a way to carry link relations that do things. So saying that a browser supports it doesn't really mean anything.

You *could* say that, for example, a browser supports the `stylesheet` relation in the `Link` header, or that `prefetch` is supported in a `Link` trailer.

**Comment by hamishwillee** [comment]
Thanks @mnot We run into this problem in BCD all the time for http headers.

@ddbeck This PR adds a spec for HTTP Link header, which we'd normally link from BCD. However this is another case where browser compatibility is pretty meaningless. We might mark it as `false` but that implies not supported rather than "not applicable". 
Did you come up with an agreed solution to this problem? Last time we talked it sounded like you might be allowing spec_url metadata in MDN, or possibly and empty version section in BCD but still add spec data [my preference].

If not, advice on how I should proceed would be appreciated. I could merge this while we think about it.

**Comment by teoli2003** [comment]
Are we waiting on something here? I think this PR improves things and we should land it. Finding the ideal way of doing it may be done in a follow-up. (Maybe we should have a spec_url in front-matter and `{{Specifications}}` looking for it if there is no bcd entry or no `spec_url `entry there.

**Review by Elchi3 — APPROVED** [review]
Yes, I'd also say let's land this for now. We've added manual specification tables like this elsewhere, too.

**Pull request merged**
