### PR TITLE
Remove 'experimental' status from revert-layer

### PR DESCRIPTION
**Pull request by sarajw**
### Description

It doesn't appear to be experimental any more - it's available across browsers and has over 93% global usage according to caniuse.cpm

### Motivation

I was curious whether I could use this in my own personal projects, and it may be useful for new work projects too.

### Additional details

https://caniuse.com/?search=revert-layer

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
@OnkarRuikar This was not synced with BCD?

@sarajw Could you remove the `{{SeeCompatTable}}` in the content too?

**Comment by sarajw** [comment]
> @sarajw Could you remove the `{{SeeCompatTable}}` in the content too?

Done! I haven't been able to run this locally to see how it turned out, hopefully that's good now.

**Review by Josh-Cena — APPROVED** [review]
Thanks

**Comment by OnkarRuikar** [comment]
> @OnkarRuikar This was not synced with BCD?

We [stopped synching inline status macros on CSS pages](https://github.com/mdn/content/pull/32756), because BCD doesn't track all the value types and value syntaxes. We did keep the banners at the top. I think the bot has stopped syncing top banners as well. I'll check the script.

**Pull request merged**
