### PR TITLE
Note and Warning fixes across docs

### PR DESCRIPTION
**Pull request by hamishwillee**
This fixes a whole bunch of incorrectly formatted Notes and Warnings - things like putting the `:` outside of the bold text, or omitting the preceding `>`.

FYI @wbamberg

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thanks for this PR!

In most of these cases (basically, all the cases where the Markdown doesn't include a blockquote) it was an intentional choice not to convert the original markup to a note. I only converted markup with `<div class="note">` or `<div class="warning">` to the Markdown syntax.

In other cases the original markup just had `<strong>Note:</strong>` (see e.g. https://github.com/mdn/content/blob/05024ffe9a3ba596fc50b1a088caecce0fa031ed/files/en-us/glossary/base64/index.html#L77). In cases like this it didn't seem clear that the author intended to add a note box, so I left them. We might decide that they did actually intend this, and OK, but that seems like a bit of a stretch to me.

There are a few cases we do need to fix in here though, as far as I can see:
* https://github.com/mdn/content/pull/10553/files#diff-ed8bb7f3cd813748cdf499609fb754971dd81c330317f3e8d40808bee9bc2c57
* https://github.com/mdn/content/pull/10553/files#diff-b936d4374350eed9795048a38b278e1ccabb54f00b1755aca5b162a9044035d3
* https://github.com/mdn/content/pull/10553/files#diff-1da2d0080ac441ce08bbe15b751425735b6dab1f9c44a46591432e9f07f8563d
* https://github.com/mdn/content/pull/10553/files#diff-cfd4dcd883622bc0bd1544005a38e838aeb92b55d34073d313e7292803703e55
* https://github.com/mdn/content/pull/10553/files#diff-d32f54f7daf498c886766adfd2a980d75fdfcfc0f4ebb09a1d51c2d953a5fbef
* https://github.com/mdn/content/pull/10553/files#diff-4b57ec72a0b490e94517b7e020b7a3406f41f1e37dd1492620b965ab3e8a2b74
* https://github.com/mdn/content/pull/10553/files#diff-72624ab05e9b5283fe0b664bf33bc02a65b2cb018ffbc463213925903757596e

All the ones I have checked here are when people have added new notes or warnings after conversion and have used incorrect markup (e.g. https://github.com/mdn/content/pull/8511/files#diff-1da2d0080ac441ce08bbe15b751425735b6dab1f9c44a46591432e9f07f8563dR19). It's a bit worrying that this is happening and suggests that this markup is hard for people to get right. Maybe it will improve as people get used to it?

**Comment by hamishwillee** [comment]
@wbamberg If something is sufficiently important to separately markup as `**Note:**` or `**Note**` then it is worth making into a proper aside. If not then it should (should have) been made as normal inline text. Sitting in the middle is inconsistent. 

In any case, deliberate or not, I am happy that none of these changes are worse and most of them are better. How do you want to proceed?

> It's a bit worrying that this is happening and suggests that this markup is hard for people to get right. Maybe it will improve as people get used to it?

I hope so. I may well be the cause of some of this because the syntax I have used elsewhere is `> **Note**` (i.e. no colon). The MDN syntax is better.

**Comment by wbamberg** [comment]
> @wbamberg If something is sufficiently important to separately markup as `**Note:**` or `**Note**` then it is worth making into a proper aside. If not then it should (should have) been made as normal inline text. Sitting in the middle is inconsistent.
> 
> In any case, deliberate or not, I am happy that none of these changes are worse and most of them are better. How do you want to proceed?
>

Yeah, that's fair enough. Rather than worrying about authorial intent it's better to think about what we'd like to have in the docs now. The actual content of many of these notes make me cry but I'm happy for them to use the proper syntax.

**Review by wbamberg — APPROVED** [review]
I've checked through these and they look fine. Thanks @hamishwillee !

**Comment by hamishwillee** [comment]
> Yeah, that's fair enough. Rather than worrying about authorial intent it's better to think about what we'd like to have in the docs now. The actual content of many of these notes make me cry but I'm happy for them to use the proper syntax.

@wbamberg Yeah. Had to limit myself to just the job in hand. Spend lots of time in the last few days on minor tidy stuff - which is satisfying but not very strategic.

**Pull request merged**
