### PR TITLE
Prevent comments in code sample from wrapping

### PR DESCRIPTION
**Pull request by wbamberg**
Make code sample in https://developer.mozilla.org/en-US/docs/Web/API/Cache#examples more readable by preventing hard-wrapping of comments.

### CODE REVIEW

**Comment by bsmth** [comment]
Taking a look now 👀

**Comment by bsmth** [comment]
It's certainly better. A good follow-up would be to show the whole code block without comments and move the comments into prose before breaking the example down in steps or parts we want to elaborate on:


```js
self.addEventListener("activate", (event) => {
  const expectedCacheNamesSet = new Set(Object.values(CURRENT_CACHES));
  event.waitUntil(
    caches.keys().then((cacheNames) =>
      Promise.all(
        cacheNames.map((cacheName) => {
          if (!expectedCacheNamesSet.has(cacheName)) {
            console.log("Deleting out of date cache:", cacheName);
            return caches.delete(cacheName);
          }
        })
      )
    )
  );
});
```

> While there is only one cache in this example, the same logic
> will handle the case where there are multiple versioned caches.


```js
            if (
              response.status < 400 &&
              response.headers.has("content-type") &&
              response.headers.get("content-type").match(/^font\//i)
            ) {
              console.log("  Caching the response to", event.request.url);
              cache.put(event.request, response.clone());
            } else {
              console.log("  Not caching the response to", event.request.url);
            }
            return response;
```

>This avoids caching responses that we know are errors (i.e. HTTP status code of
4xx or 5xx). We also only want to cache responses that correspond to fonts, i.e.
have a Content-Type response header that starts with "font/". Note that for
opaque filtered responses
https://fetch.spec.whatwg.org/#concept-filtered-response-opaque we can't access
to the response headers, so this check will always fail and the font won't be
cached.

**Review by bsmth — APPROVED** [review]
Thanks, @wbamberg 👍🏻

**Comment by wbamberg** [comment]
> It's certainly better. A good follow-up would be to show the whole code block without comments and move the comments into prose before breaking the example down in steps or parts we want to elaborate on:
> 
> ```js
> self.addEventListener("activate", (event) => {
>   const expectedCacheNamesSet = new Set(Object.values(CURRENT_CACHES));
>   event.waitUntil(
>     caches.keys().then((cacheNames) =>
>       Promise.all(
>         cacheNames.map((cacheName) => {
>           if (!expectedCacheNamesSet.has(cacheName)) {
>             console.log("Deleting out of date cache:", cacheName);
>             return caches.delete(cacheName);
>           }
>         })
>       )
>     )
>   );
> });
> ```
> 
> > While there is only one cache in this example, the same logic
> > will handle the case where there are multiple versioned caches.
> 
> ```js
>             if (
>               response.status < 400 &&
>               response.headers.has("content-type") &&
>               response.headers.get("content-type").match(/^font\//i)
>             ) {
>               console.log("  Caching the response to", event.request.url);
>               cache.put(event.request, response.clone());
>             } else {
>               console.log("  Not caching the response to", event.request.url);
>             }
>             return response;
> ```
> 
> > This avoids caching responses that we know are errors (i.e. HTTP status code of
> > 4xx or 5xx). We also only want to cache responses that correspond to fonts, i.e.
> > have a Content-Type response header that starts with "font/". Note that for
> > opaque filtered responses
> > https://fetch.spec.whatwg.org/#concept-filtered-response-opaque we can't access
> > to the response headers, so this check will always fail and the font won't be
> > cached.

Yeah, I agree about this and the same occurred to me too, but I wanted to do something quick. Also I think then we get into the code itself, and whether we can avoid this deep nesting which IMO makes it hard to read.

**Pull request merged**
