### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by timohaver**
favourite -> favorite
colour -> color

### CODE REVIEW

**Review by zombie — CHANGES_REQUESTED** [review]
Is there any discussion for doing this change?

`favourite colour` is sort of a theme in webext examples, see https://github.com/mdn/webextensions-examples/tree/master/favourite-colour, which is linked from some mdn pages, and all of that would need to change for consistency, while being careful not to break links.

Unless there are good reasons, I don't think these kinds of changes are worth the hassle.

**Comment by hafixo** [comment]
> Is there any discussion for doing this change?
> 
> `favourite colour` is sort of a theme in webext examples, see https://github.com/mdn/webextensions-examples/tree/master/favourite-colour, which is linked from some mdn pages, and all of that would need to change for consistency, while being careful not to break links.
> 
> Unless there are good reasons, I don't think these kinds of changes are worth the hassle.

Merge pull requested

**Comment by hamishwillee** [comment]
Well, the default language of the docs is US-English, and the changes are being done generally to match that across the wiki. So FWIW I think that if someone is willing to do these changes and make them carefully everywhere this is a good thing.

**Comment by Ryuno-Ki** [comment]
@zombie See https://github.com/mdn/content/issues/373

**Review by sideshowbarker — DISMISSED** [review]

**Comment by sideshowbarker** [comment]
Closing this unmerged per https://github.com/mdn/content/pull/1357#pullrequestreview-570075639

**Pull request closed without merging**
