### PR TITLE
Missing declaration

### PR DESCRIPTION
**Pull request by EzioMercer**

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
It's declared at the very top of this code block :)

**Comment by EzioMercer** [comment]
> It's declared at the very top of this code block :)

Yeah, you are right! Just saw the same code and thought that here is the same mistake :) But will not be it better to declare the variable inside the function like in other examples?

**Comment by Josh-Cena** [comment]
I'm not sure why it's done like this either, but I would assume there's some reasoning, likely because this function, unlike the other, only demonstrates retrieving the file handle but not reading the file content, so it's assumed that code to use the file handle actually resides elsewhere instead of within this function.

**Comment by EzioMercer** [comment]
> I'm not sure why it's done like this either, but I would assume there's some reasoning, likely because this function, unlike the other, only demonstrates retrieving the file handle but not reading the file content, so it's assumed that code to use the file handle actually resides elsewhere instead of within this function.

Fair point but they wrote this comment `// run code with our fileHandle` inside the same function :) It is not a big deal just wanted to notice but I'm good with keeping variable outside of function

**Pull request closed without merging**
