### PR TITLE
Remove the NonDocumentTypeChildNode mixin

### PR DESCRIPTION
**Pull request by Elchi3**
NonDocumentTypeChildNode is just a specification construct, aka mixin, and web developers don't interact with it at all.

When I first read the name I wasn't even sure what it does... It is relatively simple though: It adds two properties to two interfaces: 

Element.previousElementSibling
Element.nextElementSibling
CharacterData.previousElementSibling
CharacterData.nextElementSibling

Right now these are buried here, though: https://developer.mozilla.org/en-US/docs/Web/API/NonDocumentTypeChildNode
This PR moves the two existing NonDocumentTypeChildNode sub pages under Element and avoids the mixin complexity altogether.

For CharacterData, there are no sub pages for the whole interface right now, so I wasn't feeling motivated to get that work done now. We should document this interface properly one day.

The BCD change happened in https://github.com/mdn/browser-compat-data/pull/9065

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
Nice work @Elchi3.

I did some light copy edits, and had one query, which I'm not sure what you'll think about — I don't think it needs to block the merging of this PR:

On the API/CharacterData page, there are several uses in the method descriptions of "...when this method returns, <code>data</code> contains..." — is this referring to `e.data`, i.e. the data available on the event object? If so, which events are relevant in each case? I guess this would be explained more clearly in the pages themselves, when written, but it seems to me that this description itself could be a bit clearer.

**Comment by Elchi3** [comment]
Thanks Chris, I appreciate you taking a look here so fast!

On CharacterData, I mostly left it as is, see what we have live now: https://developer.mozilla.org/en-US/docs/Web/API/CharacterData I just removed the mention of the ridiculous NonDOcumentTypeChildNode mixin really.

Should I file an issue that proposes to improve/document CharacterData?

**Comment by chrisdavidmills** [comment]
> Thanks Chris, I appreciate you taking a look here so fast!
> 
> On CharacterData, I mostly left it as is, see what we have live now: https://developer.mozilla.org/en-US/docs/Web/API/CharacterData I just removed the mention of the ridiculous NonDOcumentTypeChildNode mixin really.

No worries, let's get this merged then.

> Should I file an issue that proposes to improve/document CharacterData?

If you could, yes please.

**Comment by chrisdavidmills** [comment]
Ah, you've got a merge conflict to fix too...

**Comment by Elchi3** [comment]
> > Should I file an issue that proposes to improve/document CharacterData?
> 
> If you could, yes please.

--> https://github.com/mdn/content/issues/2396

**Comment by Elchi3** [comment]
Conflict solved

**Pull request merged**
