### PR TITLE
Documenting some regex group limitations

### PR DESCRIPTION
**Pull request by Mike96Angelo**
There are some regex patterns that do not work as one might expect.

#### Summary
Documented some regex pattern limitations.

#### Motivation
I came across some regex patterns that didn't behave as I expected so I thought I would add them here to help others.

#### Supporting details

N/A

#### Related issues

N/A

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by Mike96Angelo** [comment]
The `Deploy Preview` action appears to get canceled for any commits pushed after a PR is made...

**Comment by wbamberg** [comment]
> The Deploy Preview action appears to get canceled for any commits pushed after a PR is made...

It's because we have to manually trigger CI for PRs from first-time contributors :(.

**Review by sideshowbarker — APPROVED** [review]
Excellent

**Comment by sideshowbarker** [comment]
Michaelangelo, nice work — thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

(And incidentally, excluding Dependabot, you’re the 2000th unique contributor to this repo)

**Pull request merged**
