### PR TITLE
Replace alert in canvas_api_tutorial

### LINKED ISSUE #7566: Remove alert() from live samples
`window.alert()` [doesn't work cross-origin in Chrome any more](https://www.chromestatus.com/feature/5148698084376576), meaning that any of our live samples that rely on `alert()` are now broken.

See also https://github.com/mdn/content/issues/7553.

This is (I think) all the live samples in Web/API that use `alert()` in a live sample (list now maintained by @Josh-Cena):

- [ ] [Games/Tutorials/2D_Breakout_game_pure_JavaScript/Build_the_brick_field](https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Build_the_brick_field)
- [ ] [Games/Tutorials/2D_Breakout_game_pure_JavaScript/Collision_detection](https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Collision_detection)
- [ ] [Games/Tutorials/2D_Breakout_game_pure_JavaScript/Finishing_up](https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Finishing_up)
- [ ] [Games/Tutorials/2D_Breakout_game_pure_JavaScript/Game_over](https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Game_over)
- [ ] [Games/Tutorials/2D_Breakout_game_pure_JavaScript/Mouse_controls](https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Mouse_controls)
- [ ] [Games/Tutorials/2D_Breakout_game_pure_JavaScript/Track_the_score_and_win](https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Track_the_score_and_win)
- [x] [Learn/JavaScript/First_steps/Variables](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables) https://github.com/mdn/content/pull/34487
- [x] [MDN/Writing_guidelines/Page_structures/Live_samples](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples) https://github.com/mdn/content/pull/34479
- [x] [Web/API/Attr/localName](https://developer.mozilla.org/en-US/docs/Web/API/attr/localname)
- [x] [Web/API/Canvas_API/Tutorial/Applying_styles_and_colors](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors) https://github.com/mdn/content/pull/34629
- [x] ~~[Web/API/CanvasRenderingContext2D/addHitRegion](https://developer.mozilla.org/en-US/docs/Web/API/canvasrenderingcontext2d/addhitregion)~~
- [x] [Web/API/Document/queryCommandState](https://developer.mozilla.org/en-US/docs/Web/API/document/querycommandstate)
- [x] [Web/API/DOMException/DOMException](https://developer.mozilla.org/en-US/docs/Web/API/domexception/domexception)
- [x] [Web/API/Element/scrollWidth](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollWidth) https://github.com/mdn/content/pull/34733
- [x] [Web/API/EventTarget/addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/eventlistener)
- [x] [Web/API/File/name](https://developer.mozilla.org/en-US/docs/Web/API/file/name)
- [x] [Web/API/HTMLInputElement/showPicker](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/showPicker) https://github.com/mdn/content/pull/37373
- [x] [Web/API/KeyboardEvent/metaKey](https://developer.mozilla.org/en-US/docs/Web/API/keyboardevent/metakey)
- [x] [Web/API/MouseEvent](https://developer.mozilla.org/en-US/docs/Web/API/mouseevent)
- [x] [Web/API/Notifications_API/Using_the_Notifications_API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) https://github.com/mdn/content/pull/34734
- [ ] [Web/API/WebGL_API/By_example/Simple_color_animation](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example/Simple_color_animation)
- [ ] [Web/API/WebGL_API/By_example/Clearing_by_clicking](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example/Clearing_by_clicking)
- [x] [Web/API/Window/find](https://developer.mozilla.org/en-US/docs/Web/API/window/find)
- [x] [Web/API/WindowOrWorkerGlobalScope/setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/windoworworkerglobalscope/settimeout) https://github.com/mdn/content/pull/7560

(I might have missed some).

In addition, the following ones use `prompt()` and are also broken:

- [x] [Learn/JavaScript/First_steps/Strings](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings) https://github.com/mdn/content/pull/38253
- [x] [Learn/JavaScript/First_steps/What_is_JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript) https://github.com/mdn/content/pull/7560
- [x] [Web/API/HTMLTextAreaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement)

We should replace all of these with some alternative. A common alternative is to write the output into an element in the example's document.

### PR DESCRIPTION
**Pull request by evelinabe**
### Description

 ✍️ Replace alert in Web/API/Canvas_API/Tutorial/Applying_styles_and_colors

### Motivation

❓ Current example is not working, there's an ongoing issue to replace all alerts. In this case I resolved it by removing the else statement with the alert and placing a minimum value on the form input, which is the standard way of handling minimum values.

### Additional details

 🔗  #7566 

### Related issues and pull requests

🔨 Fixes (Partly) #7566

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Please don't use the substring "fixes #xxx" in your description unless you are actually closing that issue, otherwise GH automatically links it.

**Comment by wbamberg** [comment]
Thanks for your PR! Unfortunately the example still doesn't work. I wonder if this is actually because of the way it's triggering the redraw call: https://github.com/mdn/content/blob/d18e8247ac5c593e6e95f4ad84173c4099609fac/files/en-us/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md?plain=1#L422.

If I replace it with a more conventional click handler it seems to work fine. Also I think we can get rid of this regex:

https://github.com/mdn/content/blob/d18e8247ac5c593e6e95f4ad84173c4099609fac/files/en-us/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md?plain=1#L395

...and call [`checkValidity()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/checkValidity) instead:

````

```js
function draw() {
  const ctx = document.getElementById("canvas").getContext("2d");

  // Clear canvas
  ctx.clearRect(0, 0, 150, 150);

  // Draw guides
  ctx.strokeStyle = "#09f";
  ctx.lineWidth = 2;
  ctx.strokeRect(-5, 50, 160, 50);

  // Set line styles
  ctx.strokeStyle = "#000";
  ctx.lineWidth = 10;

  // check input
  if (document.getElementById("miterLimit").checkValidity()) {
    ctx.miterLimit = parseFloat(document.getElementById("miterLimit").value);
  }

  // Draw lines
  ctx.beginPath();
  ctx.moveTo(0, 100);
  for (let i = 0; i < 24; i++) {
    const dy = i % 2 === 0 ? 25 : -25;
    ctx.lineTo(Math.pow(i, 1.5) * 2, 75 + dy);
  }
  ctx.stroke();
  return false;
}
```

```html hidden
<table>
  <tr>
    <td>
      <canvas id="canvas" width="150" height="150" role="presentation"></canvas>
    </td>
    <td>
      Change the <code>miterLimit</code> by entering a new value below and
      clicking the redraw button.<br /><br />
      <label for="miterLimit">Miter limit</label>
      <input type="number" size="3" id="miterLimit" />
      <input type="button" id="redraw" value="Redraw" />
    </td>
  </tr>
</table>
```

```js hidden
document.getElementById("miterLimit").value = document
  .getElementById("canvas")
  .getContext("2d").miterLimit;
draw();

const redraw = document.querySelector("#redraw");
redraw.addEventListener("click", draw);
```

{{EmbedLiveSample("A_demo_of_the_miterLimit_property", "", "180")}}

````

**Comment by evelinabe** [comment]
> Thanks for your PR! Unfortunately the example still doesn't work. I wonder if this is actually because of the way it's triggering the redraw call:
> 
> https://github.com/mdn/content/blob/d18e8247ac5c593e6e95f4ad84173c4099609fac/files/en-us/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md?plain=1#L422
> .
> 
> If I replace it with a more conventional click handler it seems to work fine. Also I think we can get rid of this regex:
> 
> https://github.com/mdn/content/blob/d18e8247ac5c593e6e95f4ad84173c4099609fac/files/en-us/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md?plain=1#L395
> 
> ...and call [`checkValidity()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/checkValidity) instead:
> 
> ```
> 
> ```js
> function draw() {
>   const ctx = document.getElementById("canvas").getContext("2d");
> 
>   // Clear canvas
>   ctx.clearRect(0, 0, 150, 150);
> 
>   // Draw guides
>   ctx.strokeStyle = "#09f";
>   ctx.lineWidth = 2;
>   ctx.strokeRect(-5, 50, 160, 50);
> 
>   // Set line styles
>   ctx.strokeStyle = "#000";
>   ctx.lineWidth = 10;
> 
>   // check input
>   if (document.getElementById("miterLimit").checkValidity()) {
>     ctx.miterLimit = parseFloat(document.getElementById("miterLimit").value);
>   }
> 
>   // Draw lines
>   ctx.beginPath();
>   ctx.moveTo(0, 100);
>   for (let i = 0; i < 24; i++) {
>     const dy = i % 2 === 0 ? 25 : -25;
>     ctx.lineTo(Math.pow(i, 1.5) * 2, 75 + dy);
>   }
>   ctx.stroke();
>   return false;
> }
> ```
> 
> ```html hidden
> <table>
>   <tr>
>     <td>
>       <canvas id="canvas" width="150" height="150" role="presentation"></canvas>
>     </td>
>     <td>
>       Change the <code>miterLimit</code> by entering a new value below and
>       clicking the redraw button.<br /><br />
>       <label for="miterLimit">Miter limit</label>
>       <input type="number" size="3" id="miterLimit" />
>       <input type="button" id="redraw" value="Redraw" />
>     </td>
>   </tr>
> </table>
> ```
> 
> ```js hidden
> document.getElementById("miterLimit").value = document
>   .getElementById("canvas")
>   .getContext("2d").miterLimit;
> draw();
> 
> const redraw = document.querySelector("#redraw");
> redraw.addEventListener("click", draw);
> ```
> 
> {{EmbedLiveSample("A_demo_of_the_miterLimit_property", "", "180")}}
> ```

I was only focusing on the replacement for the alert functionality, but you're right, the example is not working as is. I have updated the PR with your proposed changes, thanks!

**Review by wbamberg — APPROVED** [review]
👍 thank you @evelinabe !

**Pull request merged**
