### PR TITLE
Update a broken link

### PR DESCRIPTION
**Pull request by OnkarRuikar**

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
Well found.

**Comment by OnkarRuikar** [comment]
> Well found.

After a URL brakes it's not easy to find proper replacements for it. 
That is why we need to keep updating redirected URLs more frequently.

**Comment by teoli2003** [comment]
Yes, once we are done with this cleaning, we should add a periodical detection of broken URLs.

Note that we had such a script at the ODP, flagging URLs not returning 200: there were a lot of false-positive notifications due to temporary outages.

**Comment by OnkarRuikar** [comment]
> there were a lot of false-positive notifications due to temporary outages.

301(moved permanently) are safe to update. 
For 404, we can give broken URLs some time, e.g. if they are still broken after a week we update them.

**Comment by teoli2003** [comment]
This is what we did.

Note that there are plenty of temporary errors that are not temporary: we saw plenty of 302s that were permanent. 5xx that were permanent (and others not)...

Also _giving some time_ is what creates the complexity: instead of a stateless script that runs periodically, we suddenly need to memorize the output of previous runs.

**Comment by OnkarRuikar** [comment]
> Note that there are plenty of temporary errors that are not temporary: we saw plenty of 302s that were permanent. 5xx that were permanent (and others not)...

Good to know!
Complete automation will create more issues. Looks like doing this manually every weekend is safer option.

**Comment by teoli2003** [comment]
The ODP corpus had more links (in the 100'000s) so that was a problem. Once the initial cleaning is done on MDN, a weekly semi-automatic cleaning may be possible. Maybe by area…

We have far fewer links than a link directory.

Also, note that this won't detect _parked urls_ that don't hold the relevant content anymore but are not broken.

**Pull request merged**
