### PR TITLE
title of a few elements missing context in the title

### PR DESCRIPTION
**Pull request by estelle**
the title was just `<wbr>`. Pages like `td` have titles like " `<td>` the table celll element

### CODE REVIEW

**Review by wbamberg — CHANGES_REQUESTED** [review]
As for https://github.com/mdn/content/pull/9634, the title needs to be quoted (single quotes for consistency), presumably because it contains ":" which upsets the YAML parser.

**Comment by estelle** [comment]
not sure how i let you know changes were made, but changes were made ;) 
cc: @wbamberg

**Review by wbamberg — DISMISSED** [review]
Thanks for the updates! Since we use single-quotes in titles for all the other ones (that I could see) can we use single quotes for these as well?

**Review by Elchi3 — APPROVED** [review]
I changed this to single quotes

**Pull request merged**
