### PR TITLE
[Markdown] [Web/API] Convert webapi to markdown (DO NOT SQUASH MERGE)

### LINKED ISSUE #8741: [Markdown] Convert Web/API to Markdown
This is a tracking bug for actually converting Web/API to Markdown.

I think the plan could be something like:
* [x] Get sign-off on conversion report (meaning: close https://github.com/mdn/content/issues/7898)
* [ ] Merge as many open Web/API PRs as possible
* [ ] Freeze PRs to Web/API for a little while. Ensure that all Web/API reviewers know about this!
* [ ] File a PR to convert all of Web/API to Markdown
* [ ] Ask reviewers to review converted pages
* [ ] Make any updates needed
* [ ] Merge PR (without squashing :-)
* [ ] Unfreeze PRs to Web/API

We should aim to keep the tree frozen for not more than 2 days, say. We should ensure that all reviewers know in advance when the freeze is expected to happen, and ensure all reviewers know it's actually happening.

We should have a set of volunteers to help review the PR. Suggestions:
@Rumyra 
@sideshowbarker 
@hamishwillee 
@Elchi3 
@teoli2003 
@estelle 
@ddbeck 

Am I missing anyone?

I thought this time I could make batches of randomly selected 200 pages and each reviewer could review a batch. If we have 8 reviewers that's 1600 oages or about 1/4 the total number.

### PR DESCRIPTION
**Pull request by wbamberg**
Fixes https://github.com/mdn/content/issues/8741 .

This PR converts all the docs under Web/API into Markdown.

### CODE REVIEW

**Comment by wbamberg** [comment]
Here's a Google sheet listing 2000 randomly selected pages under Web/API: https://docs.google.com/spreadsheets/d/1kKeUNNZlxaLUV2KsDtnflHNedm9Jm2EwDvdgb64QnPw/edit#gid=0 . I've shared with possible reviewers.

The purpose of this is just to ensure different people review different pages.

To use it:
* put your name beside some set of pages, in the "Reviewer" column
* check out this branch, and run `yarn start`
* open the pages you claimed, and see how they look. Look especially for mangled formatting and live samples that don't work properly.
* you could also check the Markdown source, although I think that is less likely to be a problem (since the conversion report tells us that all expected elements got converted) 
* capture any problems as comments to this PR

Thanks!

**Comment by teoli2003** [comment]
@wbamberg : There is something strange with http://localhost:5000/en-US/docs/Web/API/Document_object_model/Using_the_W3C_DOM_Level_1_Core/Example. It gets a new flaw: unsafe_html…

**Comment by wbamberg** [comment]
> @wbamberg : There is something strange with http://localhost:5000/en-US/docs/Web/API/Document_object_model/Using_the_W3C_DOM_Level_1_Core/Example. It gets a new flaw: unsafe_html…

The converter seems to be converting something like:

```
<pre> &lt;html&gt;
...
</pre>
```

...into:

```
<html>
...
```

...which is... surprising?

**Comment by wbamberg** [comment]
It seems like if there's a `<pre>` block containing HTML, and there are no elements before it, then it's getting converted as raw HTML.

files/en-us/web/api/document_object_model/using_the_w3c_dom_level_1_core/example/index.html is the only page in Web/API whose first element is a `<pre>` .

I wonder if this is connected with the converter using indentation for plain `<pre>` blocks rather than backticks (and then the indentation is getting destroyed somehow).

I can fix this by adding `class="brush: html"` to the `<pre>` block. I'm going to wait to see whether any other issues are found in these pages before making that fix though.

**Comment by hamishwillee** [comment]
It isn't a problem with this conversion, but we should remember to report that `{{InheritanceDiagram}}` does not have a sensible default rendering. i.e. it _aways_ needs to be scrolled by default.

**Comment by sideshowbarker** [comment]
http://localhost:5000/en-US/docs/web/api/offscreencanvas/converttoblob has this:

```markdown
**`OffscreenCanvas.convertToBlob()`**method
```

…because the source has this:

```html
The <strong><code>OffscreenCanvas.convertToBlob()</code></strong>method
```

That HTML renders as expected but the lack of a space in <code>`**method</code> causes the markdown to not render as expected.

What should I do for these kinds of cases? Ignore it?

I could do a regex replace across all `files/en-us/web/api/` files in this branch to do <code>s/`\*\*(\w)/`\*\* $1/</code> — and also <code>s/(\w)\*\*`/$1 \*\*`/</code> — and that would make the markdown render as expected.

```
rg -P '`\*\*\w' files/en-us/web/api/ | wc -l
      14
```

So that’s 14 cases of the pattern like `convertToBlob()`**method`

```
$ rg -P '\w\*\*`' files/en-us/web/api/
files/en-us/web/api/bluetoothremotegattcharacteristic/writevaluewithresponse/index.md
15:The**`BluetoothRemoteGATTCharacteristic.writeValueWithResponse()`** method sets a {{domxref("BluetoothRemoteGATTCharacteristic")}} object’s `value` property to the bytes contained in a given {{JSxRef("ArrayBuffer")}}, calls [`WriteCharacteristicValue`(_this_=`this`, _value=value_, _response_=`"required"`)](https://webbluetoothcg.github.io/web-bluetooth/#writecharacteristicvalue), and returns the resulting {{JSxRef("Promise")}}.

files/en-us/web/api/bluetoothremotegattcharacteristic/writevalue/index.md
19:The**`BluetoothRemoteGATTCharacteristic.writeValue()`** method sets a {{domxref("BluetoothRemoteGATTCharacteristic")}} object’s `value` property to the bytes contained in a given {{JSxRef("ArrayBuffer")}}, calls [`WriteCharacteristicValue`(_this_=`this`, _value=value_, _response_=`"optional"`)](https://webbluetoothcg.github.io/web-bluetooth/#writecharacteristicvalue), and returns the resulting {{JSxRef("Promise")}}.

files/en-us/web/api/rtcpeerconnection/icegatheringstate/index.md
15:The read-only property**`RTCPeerConnection.iceGatheringState`** returns a string
```

So that’s 3 cases of the flip-side pattern like <code>**`BluetoothRemoteGATTCharacteristic</code>.

If we want, I can push a commit with those fixes to this branch.

**Comment by wbamberg** [comment]
Great catch @sideshowbarker ! If you could push a fix for these 17 cases to this PR I think that would be ideal. (I assume you mean fix the converted Markdown, not fix the upstream HTML?)

**Comment by sideshowbarker** [comment]
> (I assume you mean fix the converted Markdown, not fix the upstream HTML?)

Yup, I meant fixing the Markdown output.

Will run into and write up a commit.

**Comment by wbamberg** [comment]
> It seems like if there's a `<pre>` block containing HTML, and there are no elements before it, then it's getting converted as raw HTML.
> 
> files/en-us/web/api/document_object_model/using_the_w3c_dom_level_1_core/example/index.html is the only page in Web/API whose first element is a `<pre>` .
> 
> I wonder if this is connected with the converter using indentation for plain `<pre>` blocks rather than backticks (and then the indentation is getting destroyed somehow).
> 
> I can fix this by adding `class="brush: html"` to the `<pre>` block. I'm going to wait to see whether any other issues are found in these pages before making that fix though.

I just pushed a fix for this "unsafe HTML" issue.

**Comment by wbamberg** [comment]
I've found a few places where conversion of `<kdb>` elements inside `<dd>` was getting mangled, and have (I think) found and fixed all of these in https://github.com/wbamberg/content/commit/830104e9610820bdf6421e47805f367d08ca52f7.

**Comment by wbamberg** [comment]
I found one `<dd>` containing just a space, which the converter did not make sense of. I fixed that in https://github.com/mdn/content/pull/8886/commits/d52e248913fc8b8dab803f49c88672670684f3cf but couldn't find any other instances of this issue.

**Comment by sideshowbarker** [comment]
http://localhost:5000/en-US/docs/web/api/document/createelement#parameters has this:

```markdown
- _options _{{optional_inline}}
```

…because the HTML it was converted from has this:

```html
 <dt><var>options </var>{{optional_inline}}</dt>
```

I’ll try to see if I can put together a regex pattern to catch any other possible cases of that (without catching a bunch of false positives)

**Comment by teoli2003** [comment]
In http://localhost:5000/en-US/docs/web/api/webglrenderbuffer, there was a `<code>`missing at the beginning. Do you want me to fix the output here or in a follow-up (not a conversion problem per se)?

**Comment by wbamberg** [comment]
> In http://localhost:5000/en-US/docs/web/api/webglrenderbuffer, there was a `<code>`missing at the beginning. Do you want me to fix the output here or in a follow-up (not a conversion problem per se)?

I think this is strictly optional. On the one hand it's a small low-risk change that's a definite improvement. On the other it's out of scope for this PR, isn't a regression from the HTML and is one of probably many bits of broken markup (we have fixed many in this work, but I'm sure there are many left).

**Comment by teoli2003** [comment]
> I think this is strictly optional. On the one hand it's a small low-risk change that's a definite improvement. On the other it's out of scope for this PR, isn't a regression from the HTML and is one of probably many bits of broken markup (we have fixed many in this work, but I'm sure there are many left).

I will do follow-ups afterward then.

**Comment by wbamberg** [comment]
We've reviewed the 2000 pages in the spreadsheet, about 1/3 of the total number of pages. We've found a smattering of small issues, mostly to do with badly formed inline markup. We've tried to make generalized fixes across the Web/API docs (especially @sideshowbarker ! I think there's a good chance that there will be a few more of these little issues in the docs, but I don't think it's likely that there are big problems with this conversion, so I think we should merge it.

**Comment by sideshowbarker** [comment]
> I think there's a good chance that there will be a few more of these little issues in the docs, but I don't think it's likely that there are big problems with this conversion, so I think we should merge it.

+1 — I think we can be confident at this point that we’ve scrutinized everything pretty thoroughly

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
