### PR TITLE
ARIA suggestion_role fix for issue #34567

### LINKED ISSUE #34567: Sentence on "ARIA: suggestion role" page is incomplete
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/suggestion_role

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The following sentence is incomplete:

> Browsers tend to provide a default black strikethrough for deletions, and a black underline for insertions, but you'll probably want to use

https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/roles/suggestion_role/index.md?plain=1#L42

### What did you expect to see?

Browsers tend to provide a default black strikethrough for deletions, and a black underline for insertions, but you'll probably want to use **CSS to customize the visual styling of deletions and insertions.**

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by JusticeMatthew**
### Description

Added the missing text as described in issue #34567

### Motivation

I like fixing things where I can

### Additional details

N/A

### Related issues and pull requests

Fixes #34567

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Hi, please check existing PRs before you write your own. There's already one at https://github.com/mdn/content/pull/34585.

**Comment by JusticeMatthew** [comment]
Apologies! Not sure how I missed that when searching

**Comment by Josh-Cena** [comment]
The better way is to look at the issue: https://github.com/mdn/content/issues/34567 you can see a list of PRs that reference this issue, and check whether they intend to close the issue.

**Comment by JusticeMatthew** [comment]
Thank you for the advice, still new to open source contributing 😅

**Pull request closed without merging**
