### PR TITLE
Added hreflang for Array anchor tag. #842

### PR DESCRIPTION
**Pull request by toshkv**

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
What’s the reason for adding this? I’ve looked at #842 and I must be missing something, because I don’t see a reason given there either.

**Comment by toshkv** [comment]
See the first comment on that issue:
add hreflang to the a of #777

**Comment by sideshowbarker** [comment]
> See the first comment on that issue:

Yeah I’ve read all the comments there already, multiple times. So clearly I’m missing something.

So could you please paraphrase the reason for me? Explain it in your own words?

**Comment by toshkv** [comment]
Add English hreflang attribute to anchor tag, because the page is in "en-US".
Was I not supposed to make that change? I'm new to Github. Was that a bad first issue to try?

**Comment by sideshowbarker** [comment]
> Add English hreflang attribute to anchor tag, because the page is in "en-US".

We don’t put `hreflang` attributes on any other links we add in articles here — literally 55,000+ existing anchors in the sources, without `hreflang` attributes.

So my question is, why add an `hreflang` to this particular anchor tag? Is there something special about this particular anchor tag that merits this one having an `hreflang` attribute while the other 55,000+ don’t?

> Was I not supposed to make that change?

It’s unclear to me how you chose which issue to submit a change for — but in general, just because somebody has raised an issue here, that doesn’t mean it has anyone else’s endorsement as meriting a change. So you’d not want to assume that any given issue is automatically worth your time to work on.

> I'm new to Github. Was that a bad first issue to try?

This doesn’t seem to me at least like an ideal one to start with.

As far as what criteria to use in deciding which issues might be worth your time, one thing that comes to mind is, look to see who else has commented on the issue, and see if anyone has indicated support for making any change related to that issue.

**Comment by chrisdavidmills** [comment]
I think I'm going to close this one, @toshkv , as this isn't really a valuable addition. However, I've already assigned you some much better issues to work on, so I think you are on the right path now ;-)

In general, it is good to just check out the [issues list](https://github.com/mdn/content/issues) for this repo, and choose something fairly clean. Also note that I add labels to the issues once I've triaged them, like "Content: JS" or "30 minutes task". Choose one to work on that I've already triaged, and you'll know that it is a valid issue.

Thanks again for contributing!

**Comment by toshkv** [comment]
Thank you both for explaining. I appreciate it!

**Pull request closed without merging**
