### PR TITLE
Add info about restrictions to `Domain` in `set-cookie`

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
### Description

Source: [rfc6265](https://www.rfc-editor.org/rfc/rfc6265#section-4.1.2.3)

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by teoli2003** [comment]
I merged the changes into the current main. @NiedziolkaMichal, can you double-check if I have merged correctly? Thank you!

**Comment by NiedziolkaMichal** [comment]
@teoli2003 Two sentences were deleted:
```
Contrary to earlier specifications, leading dots in domain names (`.example.com`) are ignored.

Multiple host/domain values are _not_ allowed, but if a domain _is_ specified, then subdomains are always included.
```
Was it intentional, or should I bring them back?

**Comment by teoli2003** [comment]
Please bring them back. It was unclear to me what was intended to be kept and what was not when I merged.

**Comment by NiedziolkaMichal** [comment]
@teoli2003 That's ok. I have reapplied them.

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by NiedziolkaMichal** [comment]
Thank you

**Pull request merged**
