### PR TITLE
WebDriver conformance changes in Firefox 101

### PR DESCRIPTION
**Pull request by whimboo**
This PR adds the WebDriver conformance changes to the Firefox 101 release notes. It's all around WebDriver BiDi and there seems to be no potential candidate from Marionette. This is the [full list of changes](https://bugzilla.mozilla.org/buglist.cgi?component=Agent&component=Marionette&component=WebDriver%20BiDi&v1=fixed&query_format=advanced&f1=cf_status_firefox101&o1=equals&product=Remote%20Protocol&product=Testing&j_top=OR&list_id=16095473&resolution=FIXED).

### CODE REVIEW

**Comment by whimboo** [comment]
@Rumyra as it looks like adding links within brackets doesn't seem to work. Is that a known bug with the current markdown usage on the Wiki, and if yes is there a workaround?

**Comment by whimboo** [comment]
> @Rumyra as it looks like adding links within brackets doesn't seem to work. Is that a known bug with the current markdown usage on the Wiki, and if yes is there a workaround?

This is actually not a problem anymore and happened due to some missing characters and extra empty lines.

**Comment by whimboo** [comment]
@juliandescottes would you mind taking a look? I tried to make the release notes as compact as possible but if you would like to see something extended changed please let me know. Thanks.

**Comment by whimboo** [comment]
@dipikabh or @Rumyra could you please review? Thanks.

**Comment by Rumyra** [comment]
Thanks so much @whimboo 👍

**Review by Rumyra — APPROVED** [review]

**Pull request merged**
