### PR TITLE
Fix: Gaia page

### PR DESCRIPTION
**Pull request by Blakelist7**
> What was wrong/why is this fix needed? (quick summary only)
Changes made to Gaia page.
> MDN URL of the main page changed

> Issue number (if there is an associated issue)
#5623 
> Anything else that could help us review it

### CODE REVIEW

**Comment by Blakelist7** [comment]
@wbamberg

**Comment by wbamberg** [comment]
So I'm really sorry to mess you around with this PR, having first suggested it. But having thought it over I think we should just delete this page and the Gonk one too. I think there's value in keeping an entry for Firefox OS, but I don't see any in keeping entries for component parts of it. I checked and as far as I can see nowhere in the site is linking to either of these pages.

**Comment by Blakelist7** [comment]
That sounds good, then should I delete the page and then push or you would directly delete them from GitHub?

**Comment by wbamberg** [comment]
You should be able to delete by following https://github.com/mdn/content#deleting-a-document, and then send me a PR (or update this one). Thanks @Blakelist7 !

**Comment by Blakelist7** [comment]
@wbamberg Done :)

**Review by wbamberg — APPROVED** [review]
Thanks @Blakelist7 , looks perfect!

**Pull request merged**
