### PR TITLE
Remove var

### PR DESCRIPTION
**Pull request by Abhiram-Gullapalli**
#### Related issues

Resolves issue #16614 

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by teoli2003** [comment]
@Abhiram-Gullapalli This is an explanation about how `var` is working, so that's ok and expected to have some `var` there.

(We still have `var` to remove in Web/API)

**Comment by Abhiram-Gullapalli** [comment]
Oh I'll just close this pull then, could you give the list of files yet to be updated under the web/api section

**Review by Josh-Cena — APPROVED** [review]
This one is actually an oversight and I just didn't get around to change it. After this one, JavaScript should be fully done.

**Comment by Abhiram-Gullapalli** [comment]
Else you can just add them up in the doc containing all the files which are yet to be  updated @teoli2003

**Comment by Josh-Cena** [comment]
Most of the `var` on this page is intentional—just one oversight ^^

**Pull request merged**
