### PR TITLE
Fix typo in catalog.js

### PR DESCRIPTION
**Pull request by anandawira**
fix bookinstanceController to bookInstanceController

> What was wrong/why is this fix needed? (quick summary only)
There is a typo in importing module name

> Issue number (if there is an associated issue)

> Anything else that could help us review it

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
I can find two more instances of it in https://github.com/mdn/content/blob/9714c518f22b789aef0a700c7f6169a0f0bdad4b/files/en-us/learn/server-side/express_nodejs/routes/index.html

Could you update the PR to include them as well?

(I haven't checked out the Express project locally right now).

**Comment by anandawira** [comment]
> I can find two more instances of it in https://github.com/mdn/content/blob/9714c518f22b789aef0a700c7f6169a0f0bdad4b/files/en-us/learn/server-side/express_nodejs/routes/index.html
> 
> Could you update the PR to include them as well?
> 
> (I haven't checked out the Express project locally right now).

Fixed on this commit 592e262707ebb65cbad24f57f7141d46a46530b4

**Comment by Ryuno-Ki** [comment]
@hamishwillee I'd love to see your review on this.

**Comment by Ryuno-Ki** [comment]
Good to know. Will do next time around :-)

**Pull request closed without merging**
