### PR TITLE
Iss1410

### LINKED ISSUE #1410: addAttribute or setAttribute
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role

**Function contains wrong method**
the above documentation says HTMLParagraphElement have addAttribute function. 
_function triggerAlert() {
	var alertEl = document.querySelector('.alert');
	alertEl.addAttribute("role", "alert");
}_

**wrong way of inline function listening**
I think, we need to use onclick="triggerAlert()" instead of onclick="triggerAlert"
&lt;button type="button" onclick="triggerAlert">Trigger alert&lt;/button>

### PR DESCRIPTION
**Pull request by CreaTorAlexander**
Fixes #1410

Instead of using the onclick html attribute here we use an eventlistener

I don't know why the other commit with #2658 is here it should already merged, but idk how to remove this commit.

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
@CreaTorAlexander there are a couple of problems here, and this code snippet won't work as it stands:

1. `Document.querySelector()` doesn't take a second argument of a function to invoke. You'd have to do this using something like `addEventListener()` instead.
2. `addAttribute()` doesn't exist —  `setAttribute()` is what you need.

the following works:

```
const btn = document.querySelector('button');
btn.addEventListener('click', triggerAlert);

function triggerAlert() {
  var alertEl = document.querySelector('.alert');
  console.log(alertEl)
  alertEl.setAttribute('role', 'alert');
}
```

Make sure you test code snippets before submitting.

**Comment by CreaTorAlexander** [comment]
Damn sorry, did it in the UI what was obviously here a mistake. 
I will update it later on.

**Comment by chrisdavidmills** [comment]
> Damn sorry, did it in the GitHub UI what was obviously here a mistake.
> I will update it later on.

No need to apologize at all. We all make mistakes sometimes, and what you do for us is hugely helpful.

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills is there a reason for the *console.log*?

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills is there a reason for the _console.log_?

Oh, no, there isn't! That was leftover from a test I did. you can remove that ;-)

**Comment by CreaTorAlexander** [comment]
Okay, I assumed it so I already did a PR. https://github.com/mdn/content/pull/3270

**Pull request closed without merging**
