### PR TITLE
Correct grammatical error

### PR DESCRIPTION
**Pull request by BradleyYeo**
### Description

It should be "a" HTML document instead of "an".

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Whether to use "a" or "an" does not depend on the first letter—it depends on the first _syllable_. For example, you would say "an hour", because "hour" is pronounced as [aʊəɹ], where [a] is a vowel sound. "H" in "HTML" is pronounced as [eɪtʃ], and [e] is also a vowel, so it should be "an".

**Comment by BradleyYeo** [comment]
Thank you so much for the detailed response!

**Comment by hamishwillee** [comment]
It's all good fun until you start talking about URL, which some people pronouce YouAreL, and other's pronounce "earl". FWIW in MDN it is "a URL".

**Comment by Josh-Cena** [comment]
> earl

I can accept "CLI" as "clee" but this sounds appalling...

**Pull request closed without merging**
