### PR TITLE
Make async function error handling consistent with promise example

### PR DESCRIPTION
**Pull request by kelvinmacharia254**
The example fetchProduct():

Let handler work this way by ensuring data exists(returned) incase the async function throws an error.

```
const promise = fetchProducts();
promise.then((data) => {
    if(data){ 
    console.log(data[0].name);
    }})
```

### Description

Check if  data object is returned by the async function fetchProduct() to  prevent TypeError in the line:

```
console.log(data[0].name);
```

I propose this change in the example,

```
const promise = fetchProducts();
promise.then((data) => {
    if(data){ 
    console.log(data[0].name);
    }})
```

### Motivation

To help future readers as I have benefited from contribution of others.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
There is no code path in this function that returns nonexistent data. If your own async function does that you need to change your own code.

**Comment by kelvinmacharia254** [comment]
What if there is an error in fetching what will be the return of the async
function? I am just enclosing the data retrieval with an if statement to
ensure no error, that's all


*Kind Regards,*
*Kelvin Macharia*

**Comment by Josh-Cena** [comment]
I know what's wrong. We don't re-throw the error in the catch.

**Review by Josh-Cena — APPROVED** [review]
I changed the way we handle errors here, because we want our code to be consistent in terms of how errors are handled. Thanks for letting us know.

**Review by kelvinmacharia254 — COMMENTED** [review]
This align better with my earlier thoughts. The async function promises to handle errors  e.g. 'TypeError: fetch failed' as a result of a malformed resource endpoint. Great

**Pull request merged**
