### PR TITLE
Update vue  getting started recommendation note ininitliation

### PR DESCRIPTION
**Pull request by Kampouse**
the current tutorial using vue-cli that is in maintenance mode  i think is its a good idea to at least mention the current way of starting vue project;  considering if porting the tutorial to the current state of vue worth the hassle

The vue documentation was lacking a mention about the  recommended way of starting a vue project.
i thought adding a note about it would help the reader!

note about    create-vue repository hosted on  github 
### Motivation

The documentation as been made about three years ago and  vue as evolved  and  thought
adding a mention about create-vue  would be a good   tips for the reader

### CODE REVIEW

**Review by skyclouds2001 — COMMENTED** [review]
I think combine with the previous note will be better

**Comment by pepelsbey** [comment]
@Kampouse, I combined the notes. What do you say? :)

**Comment by Kampouse** [comment]
> @Kampouse, I combined the notes. What do you say? :)

All good to me

**Comment by Kampouse** [comment]
All  good to me

**Review by Josh-Cena — COMMENTED** [review]
This section has been rewritten in https://github.com/mdn/content/pull/33167 and the original context it's trying to address doesn't exist anymore

**Pull request closed without merging**
