### PR TITLE
Remove broken link

### PR DESCRIPTION
**Pull request by ygoe**
That link is redirected multiple times and ends up at the MDN website again which still shows the external link. A circular reference but not the needed content.

**Note:** I forgot to remove the link a second time near the end of the document. I cannot do this anymore, need to create a separate PR. Or you do it.

### CODE REVIEW

**Comment by Josh-Cena** [comment]
> Note: I forgot to remove the link a second time near the end of the document. I cannot do this anymore, need to create a separate PR. Or you do it.

You can always commit to your existing PR. Just edit the file on this branch.

**Comment by ygoe** [comment]
> Just edit the file on this branch.

I can't find it here on GitHub and don't want to download the entire repository to my computer.

**Comment by Josh-Cena** [comment]
You can navigate to https://github.com/mdn/content/pull/22293/files, and at the top right of the file diff, you'll see a "..." button, click it and select "edit file".

**Comment by ygoe** [comment]
Second link also removed

**Review by Josh-Cena — APPROVED** [review]
Thanks

**Comment by Glauip** [comment]
Muito obrigada pela sua contribuição. 
Att. Glaucia Pereira e equipe Boutique Baby - https://boutiquebaby.com.br/

**Pull request merged**
