### PR TITLE
Update index.md where glossary linking was wrong

### PR DESCRIPTION
**Pull request by glmvc**
#### Summary

missing "docs" path when linking to the glossary entry of "Clickjacking" & "US" in en-US in lowercase
added ...-**US/docs/**... to the 3 links where it was incorrect (Clickjacking glossary linking)

#### Motivation

I'm currently learning with MDN and want to give everyone else a perfect learning experience.

#### Related issues

I am a *beginner* and *new to MDN*. But could it probably be that previously the docs path did not exist and for some reason it **did not update the links** for "clickjacking"?

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by glmvc** [comment]
I just saw that also on other pages, e.g. [CSP Glossary entry](https://developer.mozilla.org/en-US/docs/Glossary/CSP), the link to the Clickjacking Glossary entry is wrong in the same way. :face_with_spiral_eyes:

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
ivan, thanks much for catching this and fixing it, and congrats on landing your first docs change here — welcome aboard 🎉

**Comment by sideshowbarker** [comment]
> I just saw that also on other pages, e.g. [CSP Glossary entry](https://developer.mozilla.org/en-US/docs/Glossary/CSP), the link to the Clickjacking Glossary entry is wrong in the same way. 😵‍💫

It’d be great if you could raise a separate pull request with a fix for that

**Comment by glmvc** [comment]
@sideshowbarker Thank you for the kind welcome. I have made the seperate pull request and fixed the mistake.

**Pull request merged**
