### PR TITLE
Text revision for US English spelling

### PR DESCRIPTION
**Pull request by timohaver**
realise -> realize

https://developer.mozilla.org/en-us/docs/MDN/Guidelines/Writing_style_guide#spelling

### CODE REVIEW

**Comment by avivmu** [comment]
Thanks.
BTW instead of submitting several PRs regarding this typo, you can search & replace all occurrences of this, and have it fixed at once.

**Comment by timohaver** [comment]
Thanks for the suggestion. I am enjoying learning GitHub as an editorial contributor to MDN, but  I am early in the process.  

My concern with a  broader find-replace operation is that it might errantly replace text where non-US spelling has been used as an example of non-US spelling. It's also easier for me to proof smaller amounts of changes. Mainly for those reasons, I am inclined to continue working the same way as before -- at least in the near term.

But if multiple PR's cause other problems downstream, I would want to understand that too.

**Comment by avivmu** [comment]
It's not causing problems, but it requires a review each time, which means spending time on it. I agree it is safer to do it one by one but I think it's unlikely that there is an intentional non US spelling. But do what works for you

**Review by sideshowbarker — APPROVED** [review]

**Comment by timohaver** [comment]
@avivmu, here is one of the instances of UK spelling in MDN that would be errantly revised with a global replacement. I have seen others, but this was my most recent find. Search _favour_ or _neighbour_ to see the example.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Quantifiers

**Comment by avivmu** [comment]
Globally find and replace, manually remove the cases where it's intentional

**Pull request merged**
