### PR TITLE
feat: Add SVG diagrams for HTTP sequences

### PR DESCRIPTION
**Pull request by bsmth**
### Description

While we do not yet have support for Mermaid inline in markdown, I've converted a few `.png` diagrams to SVG using https://www.mermaidchart.com.

### Motivation

Removing binaries from the repo, improving maintenance of diagrams, easing transition to mermaid syntax in future.

### Additional details

- Discussion: https://github.com/orgs/mdn/discussions/631

<details>

<summary> Mermaid syntax</summary>

```mermaid
%%{init: { "sequence": { "wrap": true, "width":250, "noteAlign": "center", "messageAlign": "center" }} }%%


sequenceDiagram
    participant Client
    participant Server

    Note left of Client: Request resource
    Client->>Server: GET /doc HTTP/1.1
    Note right of Server: Resource moved<br>Respond with new location
    Server-->>Client: HTTP/1.1 301 Moved Permanently<br/>Location: /doc_new

    Note left of Client: Request resource at new location
    Client->>Server: GET /doc_new HTTP/1.1
    Note right of Server: Return resource
    Server-->>Client: HTTP/1.1 200 OK
```

```mermaid
%%{init: { "sequence": { "wrap": true, "width":380, "noteAlign": "center", "messageAlign": "left" }} }%%

sequenceDiagram
    participant Client
    participant Server

    Note over Client: The client signifies its ability to understand two compression algorithms.
    Client->>Server: GET /doc HTTP/1.1<br/>Accept-Encoding: br, gzip
    Note over Server: The resource is sent compressed. The Vary header indicates that content negotiation has been used to select the algorithm.
    Server->>Client: HTTP/1.1 200 OK<br/>Content-Encoding: br<br/>Vary: Accept-Encoding
```

```mermaid
%%{init: { "sequence": { "wrap": true, "width": 175, "noteAlign": "center", "messageAlign": "left" }} }%%

sequenceDiagram
    participant Client
    participant Proxy1 as Proxy
    participant Proxy2 as Proxy
    participant Server

    Note over Client: Resource requested.
    Client->>Server: 
    Note over Server: Resource is compressed and returned.
    Server->>Client: 
    Note over Proxy1,Proxy2: Intermediate nodes do not uncompress the body.
    Note over Client: Client decompresses the body.
```

```mermaid
%%{init: { "sequence": { "wrap": true, "width": 130, "noteAlign": "center", "messageAlign": "left" }} }%%

sequenceDiagram
    participant Client
    participant N1 as Node
    participant N2 as Node
    participant N3 as Node
    participant Server

    Client-->>N1: Uncompressed
    Note left of Client: Client sends an uncompressed body.
    Note over N1,N3: Intermediate nodes send the body with or without compression on a hop-by-hop basis.
    N1-->>N2: Uncompressed
    N2->>N3: Compressed
    N3-->>Server: Uncompressed
    Note right of Server: The server receives an uncompressed body.

```

```mermaid
%%{init: { "sequence": { "wrap": true, "width": 175, "noteAlign": "center" }} }%%

sequenceDiagram
    participant Client
    participant Node1 as Node
    participant Node2 as Node
    participant Server

    Note over Client: Request message
    Client->>Node1: GET /doc HTTP/1.1

    Note over Node1: Shows support for compression while forwarding message.
    Node1->>Node2: GET /doc HTTP/1.1<br/>TE: gzip, br

    Note over Node2: Forwards message
    Node2->>Server: GET /doc HTTP/1.1

    Note over Server: Returns resource in an uncompressed body.
    Server->>Node2: HTTP/1.1 200 OK


    Note over Node2: Compresses body and forwards message.
    Node2->>Node1: HTTP/1.1 200 OK<br/>Transfer-Encoding: br

    Note over Node1: Uncompresses resource and returns message to Client.
    Node1->>Client: HTTP/1.1 200 OK

```

</details>

### Related issues and pull requests

- [x] https://github.com/mdn/content/pull/30820
- [x] https://github.com/mdn/shared-assets/pull/7

### CODE REVIEW

**Comment by Annekalray** [comment]
My. Boyfriend or ex boyfriend. Jason Porter as of. Last night who by the way beat me up with his foist and stru.ck me with a malllit twice after which he choked me for about 10 seconds with his arm wrapped around my neck after I told him that I used his computer like he told me I should because my phone is hacked
i was on my phone first. And trying to figure out where my messages were stored because they weren’t in my iCloud so I typed it into settings which led me to looking for a braille keyboard which popped up on my boyfriends computer. Long story short. It led me to GitHub on his computer which I’d asked him about over a year ago and he lied staighr to mr face and hit me that night too. I have police and hospital records of his physical and metal abuse   He also was brought up on charges of domestic violence but I did not show up to court and his because he said to from getting served with a subpoena and he got off and did not go to prison or jail. When I got to GitHub I took photos on my phone and only signed in on GitHub not knowing what I was doing I was and a totally distressed emotionally and physically over the weeks and years of dealing with him and. Knowing. My phone is hacked   I just wanted to be able to show he was the. Person who hacked my phone again 


I’m sorry. I don’t know. Wet muck about computers but I’m not an idiot. I don’t want approval. Just please sign me off of every link url website app or any other thing you sent anything you all sent things to including intockalock.   Between Jason my phone my dads illnesses and my sons new diagnosis his reaction to my even bringing up Jason’s name and my upcoming surgery fior a broken screw in my neck. Which I really don’t want to get into my life is falling apart right now and knowing that the man I loved and kept out of jail who never went to anger management or got counseling as he swore to me that he would if I didn’t go to court has been hacking my phone and watching me has just destroyed me although I can’t ever let him know how much it’s destroying me. Please take me off and just know I can prove all of what I said. Please stop what you’re doing to me.  Stop him. He’s hurt and destroyed his past girlfriends too. One. Told me to run away as fast as I can. He’s stalking me. What happened at my bank is fraud. His abuse is a felony. I’ve had someone put me in a. Coma before and I thought it was him at first and I was petrified. Jason. Didn’t even care how scared I was if that gives you any tof what type of person he can be. Please kick him off. Thank you 
Sincerely Anneka I’m sorry. I was not thinking clearly. I was in shock call I could think of was follow the trail. Get pictures and keep listening for Jason. I was so petrified he would show up any second even though he told me to use the computer even though now I think it’s now somehow a setup. I made so many mistakes not knowing what I was doing and because I thought I heard him pulling up.  I don’t know why but m writhing this to you all. You don’t care. I’m nothing to you.  This my life. My families. His family has cut him off. I alll he had basically and he did this to me. If that gives you another clue. Thank you for your time. U don’t know why I still ha. E love for him. I don’t want hi. In jail. I want him to get some intense therapy’s. He needs fine serious anger management Sent from Yahoo Mail for iPhone


On Friday, January 19, 2024, 10:11, github-actions[bot] ***@***.***> wrote:




Preview URLs
   
   - /en-US/docs/Web/HTTP/Compression
   - /en-US/docs/Web/HTTP/Redirections

**Review by Josh-Cena — COMMENTED** [review]
Can you embed the Mermaid source somewhere, either in the Markdown or in the SVG, as a comment? Makes it easier to make modifications in the future.

**Comment by bsmth** [comment]
> Can you embed the Mermaid source somewhere, either in the Markdown or in the SVG, as a comment? Makes it easier to make modifications in the future.

Yeah, it's collapsed in the PR description at the moment, but it would be nice to capture it in git. Another option is to put it in https://github.com/mdn/shared-assets/tree/main/images to keep it out of source comments here, what do you think?

**Comment by teoli2003** [comment]
Another would be to have it in a file next to xyz.svg (xyz.mermaid) that will not be deployed by yari. That way they would be next to each other.

**Comment by bsmth** [comment]
> Another would be to have it in a file next to xyz.svg (xyz.mermaid) that will not be deployed by yari. That way they would be next to each other.

I also like this suggestion, that's a good one. I'm going to bring it up in content/eng sync so that Yari team are aware.

**Comment by hamishwillee** [comment]
Obviously mermaid support in Yari would be the preferred solution - is there an associated yari PR for that?

There is another option - https://mermaid-js.github.io/ provides a mechanism to allow you to click a link to get some text that embeds the image and links to the place where it is edited. The flaw is that it relies on the service existing and running when needed. I.e.

```
[![](https://mermaid.ink/img/pako:eNqtUk9rgzAU_yrhnTawsl0zKAwrQ0YtW-xNKEFfa6BJXHwZjNLvvlgVJu1hh-YQ8n7_3gvJCSpbI3Do8MujqXCl5MFJ_VIaFlYrHalKtdIQe0vENbhy1uAAB36xXF4AztaZENkm3yWbbV785cPOmaAQwUhptJ4G9uKb-Mn9mX5sU1HssrxgD0-Pc-XY6UZW3-l6lKxI1_Ok3BIy-42ud0SjPI5jpgidDBw1zvpD09e665n_zlpZb2jxfLeJb-fN-r8m7xCBRqelqsODnnptCdSgxhJ4ONa4l_5IJZTmHKS-rcMd01qRdcD38thhBNKTFT-mAk7O4yQaP8UAnn8BbMew9A?type=png)](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNqtUk9rgzAU_yrhnTawsl0zKAwrQ0YtW-xNKEFfa6BJXHwZjNLvvlgVJu1hh-YQ8n7_3gvJCSpbI3Do8MujqXCl5MFJ_VIaFlYrHalKtdIQe0vENbhy1uAAB36xXF4AztaZENkm3yWbbV785cPOmaAQwUhptJ4G9uKb-Mn9mX5sU1HssrxgD0-Pc-XY6UZW3-l6lKxI1_Ok3BIy-42ud0SjPI5jpgidDBw1zvpD09e665n_zlpZb2jxfLeJb-fN-r8m7xCBRqelqsODnnptCdSgxhJ4ONa4l_5IJZTmHKS-rcMd01qRdcD38thhBNKTFT-mAk7O4yQaP8UAnn8BbMew9A)
```

Gives (click on image)

[](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNqtUk9rgzAU_yrhnTawsl0zKAwrQ0YtW-xNKEFfa6BJXHwZjNLvvlgVJu1hh-YQ8n7_3gvJCSpbI3Do8MujqXCl5MFJ_VIaFlYrHalKtdIQe0vENbhy1uAAB36xXF4AztaZENkm3yWbbV785cPOmaAQwUhptJ4G9uKb-Mn9mX5sU1HssrxgD0-Pc-XY6UZW3-l6lKxI1_Ok3BIy-42ud0SjPI5jpgidDBw1zvpD09e665n_zlpZb2jxfLeJb-fN-r8m7xCBRqelqsODnnptCdSgxhJ4ONa4l_5IJZTmHKS-rcMd01qRdcD38thhBNKTFT-mAk7O4yQaP8UAnn8BbMew9A)

**Comment by bsmth** [comment]
> Obviously mermaid support in Yari would be the preferred solution - is there an associated yari PR for that?

Not yet, this might be something to consider for incoming Yari refactoring this year.

> There is another option - https://mermaid-js.github.io/ provides a mechanism to allow you to click a link to get some text that embeds the image and links to the place where it is edited. 

That's clever. I agree it's tricky to rely on a service like this. 
I wonder if this is interesting: https://github.com/mermaid-js/mermaid-cli, i.e.:

```bash
npm install -g @mermaid-js/mermaid-cli
mmdc -i input.mmd -o output.svg
```

We could generate SVGs from `.mmd` files at some point.

Re: this PR I am happy to constrain it to replacing the .png files with SVG. I have checked everything in here so it's not lost: https://github.com/mdn/shared-assets/tree/main/images/diagrams/http

**Comment by Josh-Cena** [comment]
> I wonder if this is interesting: https://github.com/mermaid-js/mermaid-cli, i.e.:
> 
> ```
> npm install -g @mermaid-js/mermaid-cli
> mmdc -i input.mmd -o output.svg
> ```

FWIW this is what I already do for my mermaid diagrams.

**Comment by hamishwillee** [comment]
I would be happy to approve this, but I assume you're still going to add the mermaid text in comments as per https://github.com/mdn/content/pull/31812#issuecomment-1904210555 or as a text file. 

Personally I think the right way to do this is to create an issue for the yari support for mermaid (can you/have you done this?). On the assumption that this will happen at some point having the text in the doc content is better.

**Comment by bsmth** [comment]
> I would be happy to approve this, but I assume you're still going to add the mermaid text in comments as per [#31812 (comment)](https://github.com/mdn/content/pull/31812#issuecomment-1904210555) or as a text file.


Done in https://github.com/mdn/content/pull/31812/commits/4236fe9cdae69f9a39a811dfdcb3bd1e8b20023d

> Personally I think the right way to do this is to create an issue for the yari support for mermaid (can you/have you done this?). On the assumption that this will happen at some point having the text in the doc content is better.

Sure, I've opened this one which might be a good tracker -> https://github.com/mdn/yari/issues/10497

**Review by Josh-Cena — APPROVED** [review]

**Review by hamishwillee — APPROVED** [review]
Looks great to me. Thanks for this.

**Comment by bsmth** [comment]
Thanks, all

**Pull request merged**
