### PR TITLE
Update index.md with minor changes for consistency

### PR DESCRIPTION
**Pull request by glmvc**
#### Summary

Compared all assessment pages (from the HTML and CSS modules so far) and found some small differences (content-wise) in the "Assessment or further help" sections. To keep everything consistent, I used the variant that currently appears on most of this pages (so that it also doesn't need so many changes) and adjusted it on those pages where there were small differences (different wording for example).

#### Motivation

Only some minor changes for the consistency of the assessment pages.

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks, but I'm going to reject this as "not really any better than the previous version".

It takes a bit of time to review every PR so generally we recommend avoiding simple grammatical changes unless they fix ambiguity or otherwise make the text a lot easier to read.

**Comment by glmvc** [comment]
@hamishwillee All right, just thought it would help for better reading and understanding if everything was written in a standard way - otherwise every other section was written the same way and I thought it should be the same here.

On the other assessment pages I also made small changes that were accepted, so I don't quite understand. But surely I accept the decision, understand that it is a lot of work to review everything and apologize for the effort, cheers!

**Comment by hamishwillee** [comment]
@glmvc Very sorry, but on rechecking your changes I ONLY saw the change you made in line 58 and not the other ones - which is why I made the comment. I have no idea how that could have happened. I'll reopen and look at this again.

**Review by hamishwillee — APPROVED** [review]
This is good. Thanks. Sorry for the mistake in review last time round.

**Pull request merged**
