### PR TITLE
Daily markdownlint

### PR DESCRIPTION
**Pull request by OnkarRuikar**

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by Josh-Cena** [comment]
I thought we are waiting for the GH actions fixer...

**Comment by teoli2003** [comment]
I don't think it landed. We'll create a specific "bug" for it.

(The Markdownlint error in every PR was bothering me, and I wanted to be sure this detected the errors, which it did)

**Comment by Josh-Cena** [comment]
Ah, I thought I merged https://github.com/mdn/content/pull/16036 but apparently I didn't want to press the button.

**Comment by OnkarRuikar** [comment]
> The Markdownlint error in every PR was bothering me

It will be fixed by 
- https://github.com/mdn/content/pull/19884

To prove the point I deliberately rebased the PR before this one gets merged. That feature branch has all these lint errors and the PR, as expected, doesn't involve them. :)

**Pull request merged**
