### PR TITLE
Clarify the use of `npx` with `express-generator`

### LINKED ISSUE #6219: Issue with "Setting up a Node development environment": (short summary here please)
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment

#### What information was incorrect, unhelpful, or incomplete?
npm install express-generator -g => this command works to some extent (there are some errors and warnings). According to the official documentation, the appropriate command is: npx express-generator

#### Specific section or headline?
Under the heading: Installing the Express Application Generator

#### What did you expect to see?
New express application after using that command line

#### Did you test this? If so, how?
Yes. I put this command line into my git bash. It worked but with some errors & warnings.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/development_environment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/development_environment/index.html
* Last commit: https://github.com/mdn/content/commit/87c896192dce2d07786b58ef9abc197912a4c737
* Document last modified: 2021-05-26T07:38:46.000Z

</details>

### PR DESCRIPTION
**Pull request by FarazzShaikh**
> What was wrong/why is this fix needed? (quick summary only)

Clarify the use of `npx` with `express-generator`. 

> Issue number (if there is an associated issue)

Fixes #6219

> Anything else that could help us review it

Nope, that's all.

### CODE REVIEW

**Comment by FarazzShaikh** [comment]
I am not sure why its showing my previous (already merged) commits too. any ideas @sideshowbarker?

**Comment by sideshowbarker** [comment]
> I am not sure why its showing my previous (already merged) commits too. any ideas @sideshowbarker?

I believe that would be due to the branch having been created based on the branch you used for your previous pull request, rather than starting from the `main` branch.

When you create new branches from the command line, the recommended way to do it is like this:

```
git switch  -c your-branch-name origin/main
```

The `origin/main` part there is optional — but that’s what ensures the branch gets created from the `main` branch, rather than being created from whatever other branch you might currently be in.

Anyway, to remove the old commits from this branch, you can do this:

```
git rebase -i origin/main
```
…and the interactively mark for deletion the old commits.

Or else, you can do this:

```
git reset --hard origin/main
git cherry-pick 63b7cf65b019ba6a9a2d728f33c941fee24fc511
```
But be careful: That `git reset --hard origin/main` will wipe out _all_ the commits in your branch that aren’t yet merged to the `main` branch — including the 63b7cf65b019ba6a9a2d728f33c941fee24fc511. But git saves a reflog that still has the 63b7cf65b019ba6a9a2d728f33c941fee24fc511 commit recorded internally. So that `git cherry-pick 63b7cf65b019ba6a9a2d728f33c941fee24fc511` restores it.

**Review by sideshowbarker — APPROVED** [review]

**Comment by FarazzShaikh** [comment]
Right so for next time, create a new branch for a fix, then PR that branch in?

**Comment by sideshowbarker** [comment]
> Right so for next time, create a new branch for a fix, then PR that branch in?

Yup, exactly

**Comment by FarazzShaikh** [comment]
Gotcha, sorry for the error this time.

**Comment by Ryuno-Ki** [comment]
Do we have that process documented? https://github.com/mdn/content/pull/6251#issuecomment-866586495

Personally, I have a fork set as origin, this repo here as upstream, so my way looks like:

```sh
git checkout main
git fetch upstream
git rebase upstream/main
git checkout -b my-feature-branch
# Do changes
git add .
git commit -S -s
git push
# Open PR
```

I recall having read something about `rebase` not being preferred way (but to merge updates, i.e.

```sh
git checkout main
git fetch upstream
git rebase upstream/main
git checkout my-feature-branch # no -b as the branch was already created
git merge main
# Do moar changes and proceed as above
```

**Pull request merged**
