### PR TITLE
Fix a few "Bad BCD queries" flaws

### PR DESCRIPTION
**Pull request by queengooborg**
This PR performs a few adjustments to the content following BCD changes, fixing "Bad BCD queries" flaws.  The changes include the following:

- WebKitCSSMatrix was folded into DOMMatrix
- Remove Window.applicationCache
- Fold :-moz-focusring into :focus-visible
- Fold WorkerGlobalScope.console into console
- Rename convertPointFromNodeToPage to webkitConvertPointFromNodeToPage

### CODE REVIEW

**Comment by dipikabh** [comment]
Hi @queengooborg, I was going through the changes here.
Under CSS, I am not sure about the reason for deleting the `:-moz-focusring` page. Is it possible to remove only the [Browser compatibility]((https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-focusring#browser_compatibility)) section (that is, the corresponding front matter key) and keep the page around?

From a quick look, other similar `:-moz-*` pages on Non-standards track also do not have "Browser compatibility" sections (example: https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-first-node).

Or perhaps I am not aware if `:-moz-focusring` functionality was really replaced by `:focus-visible`.

**Comment by queengooborg** [comment]
Hey Dipika,

It may be best to review this per commit to get a better idea of what each change is!  In BCD, we have `:-moz-focusring` set as an alternative name to `:focus-visible`, so I had deleted the page and redirected it to the new selector.  I can do some digging into the selector to see when that alt. name was added and make sure that it was properly researched, though!

**Comment by queengooborg** [comment]
Looks like that change was made in https://github.com/mdn/browser-compat-data/pull/4250, which was to follow CanIUse -- so I trust its accuracy!

**Comment by dipikabh** [comment]
Thanks for digging and clarifying 👍

**Review by dipikabh — APPROVED** [review]
Changes look good to me, @queengooborg. Thank you!

**Pull request merged**
