### PR TITLE
Added Entity header Content-MD5 markdown

### PR DESCRIPTION
**Pull request by sundonghui**
#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by wbamberg** [comment]
This header seems to have been removed? https://www.rfc-editor.org/rfc/rfc7231#appendix-B

**Comment by teoli2003** [comment]
Given that anything with MD5 is a security risk, I wonder if we should document it, indicate that it has been removed, and put prominent information about the security risk of MD5?

**Comment by wbamberg** [comment]
> Given that anything with MD5 is a security risk, I wonder if we should document it, indicate that it has been removed, and put prominent information about the security risk of MD5?
> 

If no browser supports it and it has been dropped from the spec since 2014 I'm not sure this is worth doing.

**Comment by teoli2003** [comment]
You are right.

Given that there is no mention of `Content-MD5` elsewhere on MDN (my `ripgrep` gave back nothing), there is nothing more to do.

@HDS3991 Thank you very much for your help, here. Let's see you soon again!

**Pull request closed without merging**
