### PR TITLE
Fix caches.AddAll that is not origin-relative

### LINKED ISSUE #19665: Caches.addAll is not origin-relative
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

### What specific section or headline is this issue about?

Install and activate

### What information was incorrect, unhelpful, or incomplete?

It says that URLs passed to Caches.addAll are "origin-relative". This is misleading, they're relative to the document or service worker's base URL.

### What did you expect to see?

Reference to the appropriate base of the relative URL.

### Do you have any supporting links, references, or citations?

From the [service worker spec](https://www.w3.org/TR/service-workers/#dom-cache-addall):

Let r be the associated [request](https://fetch.spec.whatwg.org/#concept-request-request) of the result of invoking the initial value of [Request](https://fetch.spec.whatwg.org/#request) as constructor with request as its argument. If this [throws](https://webidl.spec.whatwg.org/#dfn-throw) an exception, return [a promise rejected with](https://webidl.spec.whatwg.org/#a-promise-rejected-with) that exception.

[Constructor of the Request object](https://fetch.spec.whatwg.org/#dom-request):

Let baseURL be [this](https://webidl.spec.whatwg.org/#this)’s [relevant settings object](https://html.spec.whatwg.org/multipage/webappapis.html#relevant-settings-object)’s [API base URL](https://html.spec.whatwg.org/multipage/webappapis.html#api-base-url).

...

Let parsedURL be the result of [parsing](https://url.spec.whatwg.org/#concept-url-parser) input with baseURL.

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/service_worker_api/using_service_workers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/service_worker_api/using_service_workers/index.md
* Last commit: https://github.com/mdn/content/commit/997c48175d0becac5936f3ea3a67749acae74f26
* Document last modified: 2022-07-27T05:54:36.000Z

</details>

### PR DESCRIPTION
**Pull request by softorangetech1122**
#### Summary

Fixes #19665 by saying it is document-and-service-worker-relative, not origin-relative.
#### Motivation

It's incorrect, and newbies to service workers may not realize this.
#### Supporting details

Issue #19665.
#### Related issues

Fixes #19665
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thank you for your PR, @softorangetech200 !

In https://github.com/mdn/content/issues/19665#issuecomment-1226731828, @noamr suggests that we should also update:

- https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll
- https://developer.mozilla.org/en-US/docs/Web/API/Cache/add 
- https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers

...with this detail. Do you think you could add these to your PR? Thank you!

**Comment by softorangetech200** [comment]
> Thank you for your PR, @softorangetech200 !
> 
> In [#19665 (comment)](https://github.com/mdn/content/issues/19665#issuecomment-1226731828), @noamr suggests that we should also update:
> 
> * https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll
> * https://developer.mozilla.org/en-US/docs/Web/API/Cache/add
> * https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers
> 
> ...with this detail. Do you think you could add these to your PR? Thank you!

I'll ask @noamr about what to add. Thanks.

**Comment by noamr** [comment]
> > Thank you for your PR, @softorangetech200 !
> > In [#19665 (comment)](https://github.com/mdn/content/issues/19665#issuecomment-1226731828), @noamr suggests that we should also update:
> > 
> > * https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll
> > * https://developer.mozilla.org/en-US/docs/Web/API/Cache/add
> > * https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers
> > 
> > ...with this detail. Do you think you could add these to your PR? Thank you!
> 
> I'll ask @noamr about what to add. Thanks.

Yes, I think we need to add them in all the above.
Also in [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request).

Note that the URL can also be relative to a regular worker script, not just a service worker.

Perhaps (thinking out loud) the right way to wording would be that those functions receive URLs or requests - basically anything that could be an `input` to the [Request constructor](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request), and in that constructor mention that the URLs are relative to the base URL, which is the document [URL](https://developer.mozilla.org/en-US/docs/Web/API/Document/URL) or the worker's [location](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/location).

**Comment by softorangetech200** [comment]
> > > Thank you for your PR, @softorangetech200 !
> > > In [#19665 (comment)](https://github.com/mdn/content/issues/19665#issuecomment-1226731828), @noamr suggests that we should also update:
> > > 
> > > * https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll
> > > * https://developer.mozilla.org/en-US/docs/Web/API/Cache/add
> > > * https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers
> > > 
> > > ...with this detail. Do you think you could add these to your PR? Thank you!
> > 
> > 
> > I'll ask @noamr about what to add. Thanks.
> 
> Yes, I think we need to add them in all the above. Also in [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request).
> 
> Note that the URL can also be relative to a regular worker script, not just a service worker.
> 
> Perhaps (thinking out loud) the right way to wording would be that those functions receive URLs or requests - basically anything that could be an `input` to the [Request constructor](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request), and in that constructor mention that the URLs are relative to the base URL, which is the document [URL](https://developer.mozilla.org/en-US/docs/Web/API/Document/URL) or the worker's [location](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/location).

I'll push all changes later. Thanks!

**Comment by wbamberg** [comment]
@softorangetech1122 , are you intending to come back to this PR? Otherwise I will have a go at finishing it off myself. Thanks!

**Comment by sideshowbarker** [comment]
@softorangetech1122, this is still waiting in your response to https://github.com/mdn/content/pull/19955#issuecomment-1287544579

**Comment by sideshowbarker** [comment]
@wbamberg I went ahead and closed this one for lack of response. https://github.com/mdn/content/pull/19955/files still has the patch (such as it is). No further commits were ever pushed to the PR branch in response to the review comments.

**Pull request closed without merging**
