### PR TITLE
Web CSS Extensions - fix fixable flaws

### PR DESCRIPTION
**Pull request by hamishwillee**
Just auto-fixing flaws - while testing PeterB's new whole-site flaw checker.

EDITED. Now ready for review. See https://github.com/mdn/content/pull/7058#issuecomment-885436309 for explanation - basically had to add both link and link text to ensure that page does not get broken as webkit extensions get proper fixes.

### CODE REVIEW

**Comment by hamishwillee** [comment]
This is a page of webkit extensions. Many of these have been aliased by the flaw checker to their proper replacements. That would be a good thing elsewhere, but here we're trying to show the actual extensions, not their replacements. 

So for example, currently the page has `{{CSSxRef("-webkit-border-fit")}}`, which gets "fixed" to `{{CSSxRef("border-image-repeat")}}`. I think that before running flaw fix I should change `{{CSSxRef("-webkit-border-fit")}} to `{{CSSxRef("-webkit-border-fit","-webkit-border-fit")}}. That way the link might get fixed by the flaw fixer, but the information indented to be presented will be right.

**Review by ericwbailey — APPROVED** [review]

**Comment by ericwbailey** [comment]
@hamishwillee Oop, looks like there's a failing test here.

**Comment by hamishwillee** [comment]
Thanks @ericwbailey - dunno how that crept in. Fixed now.

**Comment by ericwbailey** [comment]
No worries, thanks for getting it.

**Pull request merged**
