### PR TITLE
Release notes for NSS 3.66

### PR DESCRIPTION
**Pull request by beurdouche**

### CODE REVIEW

**Comment by mathewhodson** [comment]
The NSS release notes are no hosted at https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_66.html

I don't think this needs to be merged anymore.

**Comment by teoli2003** [comment]
cc/ @Rumyra, so making a call on this PR is on her radar.

**Comment by Rumyra** [comment]
> The NSS release notes are now hosted at https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_66.html
> 
> I don't think this needs to be merged anymore.

Yup - thanks @beurdouche but these docs have been removed 👍

**Comment by hamishwillee** [comment]
FYI @Rumyra the removal of NSS docs I did yesterday got reverted. I'm hoping @beurdouche and Ryan will get together and put in a proper plan for it's removal: https://github.com/mdn/content/pull/8215#issuecomment-904193203

That said, I agree with you - we should only do minimal changes to this area since we actually don't know what has been ported and what has not.

**Comment by Rumyra** [comment]
So yes we're 'in the process' of removal - so I'll push this through as it's not a huge change 👍

**Review by Rumyra — APPROVED** [review]

**Pull request merged**
