### PR TITLE
style: use json-stringify for wikihistory

### PR DESCRIPTION
**Pull request by nschonni**
Noticed using a `yarn content ...` command that when the wikihistory file is output, it's with JSON.stringify, so if the file is directly pushed, the CI will complain. Rather than changed the formater for all the JSON files, I just override it for the one.

### CODE REVIEW

**Comment by teoli2003** [comment]
Yes, I hit this twice and this would be very welcome fix. (Approving but not merging, I'd like @caugner to have a look first)

**Review by teoli2003 — APPROVED** [review]
(Note that I had to run prettier the last time I deleted a file)

**Review by caugner — CHANGES_REQUESTED** [review]
https://github.com/mdn/yari/pull/7032 should fix this upstream, avoiding the special case here.

**Comment by Josh-Cena** [comment]
I don't think this is needed after https://github.com/mdn/yari/pull/7032. Closing.

**Comment by Alarcon1234** [comment]
>

**Pull request closed without merging**
