### PR TITLE
fix(css): add repeating-conic-gradient to syntax section

### LINKED ISSUE #31307: Inconsistent gradient documentation
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/gradient

### What specific section or headline is this issue about?

Syntax and Formal syntax

### What information was incorrect, unhelpful, or incomplete?

The syntax section does not describe repeating conic gradients while the formal syntax describes neither these nor ordinary conic gradients.

### What did you expect to see?

Consistency and completeness

### Do you have any supporting links, references, or citations?

The CSS level 4 link on the page describes conic and repeating conic gradients

### Do you have anything more you want to share?

https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/conic-gradient
and
https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-conic-gradient
have formal syntax sections that describe these types. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/gradient`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/gradient
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/gradient/index.md
* Last commit: https://github.com/mdn/content/commit/5e7d1f9ae2cce0cb3f7693dfb8dc6e8d375b2231
* Document last modified: 2023-07-18T00:16:24.000Z

</details>

### PR DESCRIPTION
**Pull request by OnkarRuikar**
- fixes https://github.com/mdn/content/issues/31307

### CODE REVIEW

**Comment by jimmonte** [comment]
That is definitely an improvement, but the remainder of the page should be modified to include the additional repeating gradient in the examples and organized so in a systematic way. One possibility is to use an order of linear, radial, conic then the repeating gradients. Or, since linear, radial, and conic all have repeating versions, the latter types could be grouped with their non-repeating versions.

**Comment by dipikabh** [comment]
The update looks good, @OnkarRuikar.

The only other minor thing that can be updated (somewhat along the lines of https://github.com/mdn/content/pull/31625#issuecomment-1885001872) is to change the order of the examples, that is, move [Repeating gradient examples](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient#repeating_gradient_examples) after the "Conic gradient example". Out of scope for this PR, but "example" in all example sub-headings is redundant.

Let me know what you think of the other changes, but in either case I'm happy to approve it.

**Review by dipikabh — APPROVED** [review]
Thanks 👍

**Comment by jimmonte** [comment]
It is too bad that the formal syntax cannot be (easily) fixed, but otherwise the page looks good.

**Pull request merged**
