### PR TITLE
Intl resolved options order correction, normalize description

### LINKED ISSUE #36055: resolvedOptions for Intl objects not given in spec order
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/resolvedOptions

### What specific section or headline is this issue about?

`resolvedOptions()` for several `Intl` objects

### What information was incorrect, unhelpful, or incomplete?

The properties of the object returned by calls to `resolveOptions()` of `Intl` objects, insofar as is possible, should be listed on the relevant MDN page in the order in which those properties are added to the object returned by `resolveOptions()` in the specification of the `Intl` object in question. See, for example, https://tc39.es/ecma402/#sec-intl.numberformat.prototype.resolvedoptions. See also discussion at https://github.com/mdn/content/pull/33340

I'll have a PR up in about ten seconds that reorders the previously misordered properties.

### What did you expect to see?

`resolvedOptions()` properties in spec order

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by ben-allen**
### Description

Reorders the `resolvedOptions` of `Intl` objects to the order in which properties are added in the spec. Adds a few properties that were previously left off `resolvedOptions` return value.

### Motivation

Improve readability/consistency of `Intl` documentation.

### Additional details

See discussion here: https://github.com/mdn/content/pull/33340

### Related issues and pull requests

Fixes https://github.com/mdn/content/issues/36055

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Thanks! It has always been on my TODOs to fix the Intl options and reordering them was one of the goals. Will check this soon.

**Comment by ben-allen** [comment]
rebased!

**Review by Josh-Cena — APPROVED** [review]
I've audited all pages, and also changed the descriptions to keep everything consistent. Thank you!

**Comment by ben-allen** [comment]
Thank you so much!

**Pull request merged**
