### PR TITLE
fix: Reomve "_clone" from page name

### PR DESCRIPTION
**Pull request by nschonni**
References and content didn't have "clone" appears to have been accidentally renamed

### CODE REVIEW

**Comment by sideshowbarker** [comment]
Looks like there’s more in here than just the “Remove "_clone" from page name” change? Specifically, other unrelated changes to redirects?

**Comment by nschonni** [comment]
@sideshowbarker yeah, I used yari to rename with `yarn content move Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE_clone Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE` and it added those extra changes at the same time.
Ran into an odd naming problem with the resulting folder due to a windows issue, and manually re-fixed the folder name

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
> @sideshowbarker yeah, I used yari to rename … and it added those extra changes at the same time.

Ah OK, I see now — yeah, it seems like that maybe causes yari to regenerate he redirects file — sorted, I guess, and also with redirect chains flattened out. Which seems good.

**Comment by nschonni** [comment]
Yeah, I guess some of #234 got implemented already

**Review by chrisdavidmills — APPROVED** [review]

**Pull request merged**
