### PR TITLE
fix(barcode): prefer positive conditional

### PR DESCRIPTION
**Pull request by BastiDood**
### Description

This PR refactors the example code (for browser compatibility checking) in the Barcode Detection API so that it uses a more "positive" or "affirmative" conditional style.

### Motivation

I believe that an affirmative style in writing conditionals makes the code more readable. There is no need to jump through hoops negating what is already a negation.

### Additional details

A few months ago, I wrote about this exact refactoring technique in my article titled ["Please don't write confusing conditionals"](https://dev.to/somedood/please-dont-write-confusing-conditionals-2n32). This sentiment has also been reiterated in a [now-publicized internal note by Google](https://testing.googleblog.com/2023/10/improve-readability-with-positive.html) as part of their [Code Health](https://testing.googleblog.com/2017/04/code-health-googles-internal-code.html) series since 2017.

> [!NOTE]
> As I have been participating in [Hacktoberfest 2023](https://hacktoberfest.com/), I would greatly appreciate having this PR count towards my progress. To do so, you may add the `hacktoberfest-accepted` label to this PR before merging. See the [Maintainers](https://hacktoberfest.com/participation/#maintainers) page for more details.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Hi, it is more common in feature detection to put the negative branch first, because in a real application you would bail out, saving yourself an `else` block and a level of indentation entirely. We are also generally not interested in microrefactors because examples are written by people with various backgrounds and experiences and reflect their idioms.

Also, correct me if I'm wrong, but as far as I can tell, we are not participating in Hacktoberfest.

**Comment by BastiDood** [comment]
> Hi, it is more common in feature detection to put the negative branch first, because in a real application you would bail out, saving yourself an else block and a level of indentation entirely.

Yes, I can agree with this. However, putting the negative branch first is generally only recommended for _early returns_ such as in the following example:

```ts
function hello(doReturnEarly: boolean) {
    // Negative branch is fine because of early return.
    if (!doReturnEarly) return;

    // This saves us one level of indentation! 🎉
    console.log('hello');
}
```

Note, though, that this is not the case for the particular example used in the feature detection for the Barcode Detection API. I can only assume that the code snippet belongs in the top level (i.e., not inside a function).

Hence, due to the impossibility of an early return in top-level execution, I appeal that the positive conditional is more readable here.

```js
// ASSUMPTION: We are in the top-level execution.
if ('BarcodeDetector' in window) {
    // This is more readable because we follow the positive code path.
} else {
    // Not supported...
}
```

> Also, correct me if I'm wrong, but as far as I can tell, we are not participating in Hacktoberfest.

Aw, that is unfortunate. I would still love to have this example refactored, though. 👍

**Comment by Josh-Cena** [comment]
Another maintainer expressed the same sentiment through another channel:

> I like positive conditionals too, but I prefer to have the short exception case dealt with initially so you can get it out of your head while reading the code. So I'd be -1 on this PR.

In a real program, you would not be using if...else, but the same early return pattern you mentioned above.

**Comment by BastiDood** [comment]
> I prefer to have the short exception case dealt with initially so you can get it out of your head while reading the code.

Ah, this is a fair point. I will concede.

Thanks for taking the time to read the PR, though! 🙇

**Pull request closed without merging**
