### PR TITLE
Add note about the existence of classes

### PR DESCRIPTION
**Pull request by edazpotato**
#### Summary
This adds a note to the [re-introduction to javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript) article about the existence of classes.

#### Motivation
To keep the page factually correct, as the page currently says that javascript doesn't have a class statement. 

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by hamishwillee** [comment]
@edazpotato Thanks for this - really good catch.

@wbamberg This is a reasonable quick fix for the specific incorrect statement that we don't support classes, but I think we need to do a lot more here. 

Specifically classes should not be "out of scope" for a Javascript tutorial so we should cover them. I'm not quite sure how to do that though since the existing doc refers to the half-way house of `new` and factory functions that I think were in ES5. Would we talk about the path that JavaScript went through to get here, or start with classes? 

There probably also needs to be some review of other docs that might make similar statements. https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects looks OK on quick scan but https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_JS is still function-oriented.

Does it seem reasonable to  you that we merge this and create an issue for the doc to be revisited?

I'll take this on if no one else wants to, but it would be better if someone who actually likes Javascript did it :-). We can chat offline maybe?

**Comment by edazpotato** [comment]
Yeah, this should definitely only be a temporary fix, but I think it's also important that this note is added as soon as possible so that people don't get confused.

I'm not sure if this is something that MDN typically does, but a note could be added to the top of the sections on the JS tutorial page (and possibly the other pages that you linked) that says that while the content isn't incorrect, it doesn't necessarily reflect the current state of JavaScript in regards to that concept and that an update is being worked on.

**Comment by hamishwillee** [comment]
I tend to agree, but it is worth waiting on the experts to look at. After all, it has been wrong for quite a while now.

**Comment by wbamberg** [comment]
> @edazpotato Thanks for this - really good catch.
> 
> @wbamberg This is a reasonable quick fix for the specific incorrect statement that we don't support classes, but I think we need to do a lot more here.
> 
> Specifically classes should not be "out of scope" for a Javascript tutorial so we should cover them. I'm not quite sure how to do that though since the existing doc refers to the half-way house of `new` and factory functions that I think were in ES5. Would we talk about the path that JavaScript went through to get here, or start with classes?
> 
> There probably also needs to be some review of other docs that might make similar statements. https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects looks OK on quick scan but https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_JS is still function-oriented.
> 
> Does it seem reasonable to you that we merge this and create an issue for the doc to be revisited?

I suppose so. I don't particularly like this fix though. I'd probably prefer to just remove the incorrect statement, since "beyond the scope" isn't really accurate either - it's more like "we haven't got around to updating this article yet", which we don't really want to say.

So I'd probably prefer to say something like:

> In classic Object Oriented Programming, objects are collections of data and methods that operate on that data. <strike>JavaScript is a prototype-based language that contains no class statement (actually it does, but that's beyond the scope of this article), as you'd find in C++ or Java (this is sometimes confusing for programmers accustomed to languages with a class statement). Instead,</strike> JavaScript uses functions as classes.

...and maybe also add a note admitting that this page does not document modern practices.

In a way though, whatever we do "for now" will be bad.

So I agree that there's a big issue here which we should fix. Actually there are two issues:
* updating our JS docs overall to document JS objects properly
* aligning the various JS guides that we have

For the second of these, I can think of three places offhand which cover the same ground, at different depths:
1. the JS Learn docs: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects
2. this page, a re-introduction to JS: https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript
3. The JS guide: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Details_of_the_Object_Model

At this point I wonder if anything would be lost if we retired "a re-introduction to JS" and just redirected it to the JS guide. I think it served a purpose at a particular time in the history of JS, but that time has moved on, and in many other ways this page looks dated.

That leaves us with 2 sets of JS guides, Learn and the JS guide, which I think makes sense - Learn is organized as pathway for beginners, omitting lots of gory details, and the Guide goes deep and is organized by subject.

For the first issue, the Learn area and the JS guide **also** don't do a good job of explaining modern JS objects. I'm working on https://github.com/mdn/content/blob/main/rfcs/modernize-learn-js.md in this quarter, and as part of that will need to update the way Learn talks about objects. But we would need a new vehicle for updating the JS guide.

> someone who actually likes Javascript 

Also cc @Elchi3 . I'm not sure if he likes JavaScript exactly, but he cares about it :).

**Comment by hamishwillee** [comment]
Thanks very much @wbamberg @edazpotato 

Will, I have updated the text here more or less in line with your suggestion. If you're OK with it let's merge. I decided not to simply do a redirect from this doc as I'm not confident that some of the information might not be useful in another context.

I've moved the discussion of future work to #10301. 

Hopefully you and @Elchi3 can own that. I care too, I just don't like to suffer unnecessarily :-)

**Review by wbamberg — APPROVED** [review]
Yes, this looks good to me! Thanks for the update and for filing the issue. And thanks for filing @edazpotato , let's hope we will be able to get some updated docs soon!

**Pull request merged**
