### PR TITLE
Update page-type for JS/Reference/Errors to landing-page

### PR DESCRIPTION
**Pull request by Josh-Cena**
### Description

This is needed to check page structure.

### CODE REVIEW

**Comment by wbamberg** [comment]
Yes for "Errors", but the other two don't look like landing pages to me.

I think landing pages are basically nav: they primarily exist to collect links to other pages, and don't have a lot of 'original content' at all. If anything the other two look like guide pages.

If this content were to be refactored into "Classes overview" as a guide page under "Classes", and "Classes" to be a landing page listing it and the related reference pages, then that might work.

**Comment by Josh-Cena** [comment]
Hmmm, I remember we had this discussion before, but now I can't find it. Maybe I'm daydreaming. I thought we previously had the idea that a page can be `landing-page` but have some more description, as long as it does have organized navigation to all subpages.

**Comment by wbamberg** [comment]
> Hmmm, I remember we had this discussion before, but now I can't find it. Maybe I'm daydreaming. I thought we previously had the idea that a page can be `landing-page` but have some more description, as long as it does have organized navigation to all subpages.

Well I suppose it's perhaps subjective.

Yes, IMO it's fine for a landing page to have some content explaining what a thing is, before listing all the instances of the thing. That's what https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors does. But to me https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes reads like a guide page about classes, and just because it has links to the subfeatures it talks about doesn't change that.

When I say "basically nav" what I mean is: people go there to get to somewhere else. Which means that the nav needs to be really clear. But this page has a lot of explanation, and it's not really obvious which links are to subpages and which are just links to associated stuff. As a guide page, it's great. As nav, it's not.

But this is just my opinion. And maybe it doesn't matter, unless/until we want to do something with the distinction between landing pages and guide pages.

**Comment by Josh-Cena** [comment]
OK, these aren't necessary for me either. My idea was that I could check if a landing page contains links to all subpages, but maybe I can expand that to guide pages as well.

**Review by Elchi3 — APPROVED** [review]
I think this change has consensus. Merging :)

**Pull request merged**
