### PR TITLE
fix: flaws in learn/server-side

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@chrisdavidmills ping

**Comment by hamishwillee** [comment]
@nschonni This is great. Unfortunately Peter did this fix with significant overlap, which I merged first: https://github.com/mdn/content/pull/1746

I note that you touched 57 files and he touched 29. So it might be worth rebasing and resolving the conflicts before review?

**Comment by nschonni** [comment]
@hamishwillee rebased

**Review by hamishwillee — APPROVED** [review]
Excellent. Thank you.

**Pull request merged**
