### PR TITLE
redirects: html to md

### PR DESCRIPTION
**Pull request by estelle**
Redirect all the older aria-attribute files written in HTML to the new files written in markdown

### CODE REVIEW

**Review by ddbeck — DISMISSED** [review]
It looks like some of the new redirects are causing failures in old redirects. I think the fix here is to change the old redirects from `/en-US/docs/Accessibility/ARIA/` and `/en-US/docs/ARIA/` directly to the new slugs, rather than redirecting through the slugs removed by this PR.

**Comment by estelle** [comment]
fixed the merge conflict

**Review by sideshowbarker — DISMISSED** [review]

**Comment by sideshowbarker** [comment]
I notice that at https://github.com/mdn/content/runs/4706614643?check_suite_focus=true CI is still reporting an error:

> Error: Invalid redirect for /en-US/docs/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute -> /en-US/docs/ARIA/ARIA_Techniques/Using_the_banner_role or /en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute -> /en-US/docs/Web/Accessibility/ARIA/Roles/Banner_role

**Comment by estelle** [comment]
Let's hope this fixes it. 🤞

**Comment by estelle** [comment]
i think we're good

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
