### PR TITLE
Updated the description of `targetOrigin`  to specify the intended re…

### LINKED ISSUE #34090: terms "this", "target", "recipient", "window", "origin" appear indistinctly used
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

### What specific section or headline is this issue about?

multiple

### What information was incorrect, unhelpful, or incomplete?

> [targetOrigin](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#targetorigin) Optional
Specifies what the origin of this window must be for the event to be dispatched,

"this"

> Any window (including, for example, http://evil.example.com) can send a message to any other window

"window"

### What did you expect to see?

depending on what is really meant, I expected to see "this" replaced by "the intended recipient" and "window" replaced by "contentWindow within the iframe hierarchy from top to every iframe below of the current document"

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

"window": can a post occur to another tab? another users PC's tab? a server? any browser's having the same document open?

how is targetOrigin safety? If the iframe src can be changed away while posting to its contentWindow or the to-be-sender's page is copied and run on a malicious host, that host can simply replace the text inside the JavaScript code of postMessage.

postMessage operates on a contentWindow already obtained. It is not BroadcastChannel.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/postmessage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/postmessage/index.md
* Last commit: https://github.com/mdn/content/commit/45fdc5d8cce894088d4c270b8f160841ecb11a2a
* Document last modified: 2024-04-26T17:21:55.000Z

</details>

### PR DESCRIPTION
**Pull request by Ashish-CodeJourney**
Clarified the `targetOrigin` parameter to specify the intended recipient window and updated references to "any window" to denote contentWindow within the iframe hierarchy. Added enhanced security notes to improve understanding of `postMessage` usage and limitations.

### Description

Clarified the `targetOrigin` parameter to specify the intended recipient window and updated references to "any window" to denote contentWindow within the iframe hierarchy. Added enhanced security notes to improve understanding of `postMessage` usage and limitations.

### Motivation

These changes improve the clarity and accuracy of the documentation for `window.postMessage()`. By specifying what is meant by "this window" and "any window", readers can better understand the correct usage and security implications of the `postMessage` method.

### Additional details

This update ensures that the documentation accurately reflects the behavior and security considerations of the `postMessage` method, helping developers to use it correctly and securely.

### Related issues and pull requests

Fixes #34090

### CODE REVIEW

**Comment by u-an-i** [comment]
Hi, nice. I do a review on the preview:  
  
  
image
  
**picture 1**  

1. "documents in different window objects are allowed to access each other by script if and only if they originate from the same origin".
    - Link "origin" to an article eg. about `location.origin`.  
2. "Furthermore an accessing script must have obtained the window object the document of the accessed script is in beforehand. Obtaining can occur by ..."  
    - Link to an article about `open` and `contentWindow`.
3. "`window.postMessage()` provides ..."
    - continue.
  
  - - -
image
  
**picture 2**  

1. choose 1 wording and stay with it throughout the whole document.  
2. "limited" should be "intended", singular.  
3. Punctuation.  
  
  - - -
image
  
 **picture 3**  

1. "the scheduling window's document"
     - `this` could be understood as referring to the subject of the previous sentence in which `window` is the `intended recipient window`.  
2. "its counterpart".  
  
  - - -
image
  
**picture 4**  

1. "Any script in a document in a window can request to let a message get dispatched to any script in a document in another window whose window object it has obtained by `.postMessage()` on that window object."  
2. Consider using 1 term of `dispatched`, `posted` throughout the whole document.  
  
  - - -
image
  
**picture 5**  

1. duplicate

**Comment by Ashish-CodeJourney** [comment]
> Hi, nice. I do a review on the preview:
> 
> image
> 
> **picture 1**
> 
> 1. "documents in different window objects are allowed to access each other by script if and only if they originate from the same origin".
>    
>    * Link "origin" to an article eg. about `location.origin`.
> 2. "Furthermore an accessing script must have obtained the window object the accessed document is in beforehand. Obtaining can occur by ..."
>    
>    * Link to an article about `open` and `contentWindow`.
> 3. "`window.postMessage()` provides ..."
>    
>    * continue.
> 
> image
> 
> **picture 2**
> 
> 1. choose 1 wording and stay with it throughout the whole document.
> 2. "limited" should be "intended", singular.
> 3. Punctuation.
> 
> image
> 
> **picture 3**
> 
> 1. "the intended recipient window's document"
>    
>    * `this` could be understood as referring to the window in which the document is which contains the code which is getting executed right now.
> 2. "its counterpart".
> 
> image
> 
> **picture 4**
> 
> 1. "Any script in a document in a window can request to let a message get dispatched to a document in another window whose window object it has obtained, by `.postMessage()` on that window object."
> 2. Consider using 1 term of `dispatched`, `posted` throughout the whole document.
> 
> image
> 
> **picture 5**
> 
> 1. duplicate

Made some changes i don't know why Lint review is failing as i haven't changed the part its suggesting
i think any Maintainer should suggest something.

**Comment by Ashish-CodeJourney** [comment]
@sideshowbarker if you can review this out

**Review by sideshowbarker — APPROVED** [review]
In future PRs, please don’t remove linebreaks the way did in this PR. Whitespace-only changes like that makes it very much more difficult to review the substantive changes in the patch.

For example, you removed the linebreak before _“The ownership of these objects is given to the destination side and they are no longer usable on the sending side.”_

I realize the rendered output from that is the same. But it’s an unnecessary change.

Next time, if you want to make a bunch of whitespace-only changes like that, please do them in a separate follow-up PR — with a title that explicitly says “Whitespace-only changes”.

**Comment by Ashish-CodeJourney** [comment]
> In future PRs, please don’t remove linebreaks the way did in this PR. Whitespace-only changes like that makes it very much more difficult to review the substantive changes in the patch.
> 
> For example, you removed the linebreak before _“The ownership of these objects is given to the destination side and they are no longer usable on the sending side.”_
> 
> I realize the rendered output from that is the same. But it’s an unnecessary change.
> 
> Next time, if you want to make a bunch of whitespace-only changes like that, please do them in a separate follow-up PR — with a title that explicitly says “Whitespace-only changes”.

i will keep this in mind next time, thanks :)

**Pull request merged**
