### PR TITLE
Align docs on Function constructor params with spec

### LINKED ISSUE #6000: Issue with "Function() constructor": definition for arg1, arg2, ... argN too restrictive compared to spec
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Function

#### What information was incorrect, unhelpful, or incomplete?
The parameter part claims the values for `arg1, arg2, ... argN` can only be valid identifiers. However, per https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-createdynamicfunction, it can be much more.

#### Specific section or headline?
"Parameters"

#### What did you expect to see?
Rephrase to the following to match FormalParameters grammar:

> Names to be used by the function as formal argument names. Each must be a string that corresponds to a valid JavaScript parameter (any of plain identifier, rest parameter, or destructed parameter, optionally with a default) or a list of such strings separated with a comma.
>
> As the members are parsed in the same way as that of function declaractions, whitespace and comments are accepted. For example: `"x", "theValue = 42", "[a, b] /* numbers */"`—or `"x, theValue = 42, [a, b] /* numbers */"`. (`"x, theValue = 42", "[a, b]"` is also correct, but it is very confusing to read.)

I am unable to muster up the infrastructure to figure out what the compatibility is like, although I imagine it to be similar to the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions page. The related constructors of `GeneratorFunction` and `AsyncFunction` also need to be changed.

#### Did you test this? If so, how?
```js
const sum = new Function('a', '...b', 'return a + b[0]');
console.log(sum(2, 6));

const sum2 = new Function('{a, b}, c = 0 /* optional */', 'return a + b + c');
console.log(sum2({a: 2, b: 6}));
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/function/function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Function
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/function/function/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

### PR DESCRIPTION
**Pull request by sideshowbarker**
Fixes https://github.com/mdn/content/issues/6000

### CODE REVIEW

**Comment by sideshowbarker** [comment]
@Artoria2e5 It would be great if you could check this and confirm it’s correct. (It’s essentially just the suggested wording from #6000, with minor refinements.)

**Comment by Artoria2e5** [comment]
I can't find any issues with this PR since it's basically identical to my wording.

**Comment by sideshowbarker** [comment]
@wbamberg this one should be ready for review

**Review by wbamberg — APPROVED** [review]
👍 thanks!

**Pull request merged**
