### PR TITLE
fix: Escape tags in title frontmatter

### LINKED ISSUE #416: Escape HTML elements in title frontmatter
Running the vnu-jar validations across the content, it often gets tripped up by these stand-alone HTML tags.
I think escaping them to `&lt;TAG_NAME&gt;` tag name would make sense, but I'm not sure if that has downstream impacts for yari.

### PR DESCRIPTION
**Pull request by nschonni**
Fixes #416

### CODE REVIEW

**Comment by peterbe** [comment]
Why? :)

**Comment by nschonni** [comment]
Looking at the generated source it looks like yari is doing this as part of the build.
EX: `<title>&lt;alpha-value&gt; - CSS: Cascading Style Sheets | MDN</title>`
From the linked issue this gives (better) compat with vnu-jar, since it doesn't treat the un-esacped elements as unclosed HTML tags

**Comment by peterbe** [comment]
No, I don't think this is right. The YAML values (for `title:`) shouldn't need to be escaped. 
Yes, Yari will eventually escape it when it renders it into HTML. The `index.html` isn't HTML so it would be fundamentally wrong to ask `vnu-jar` to parse it. The KS makes it even less of an HTML document :)
But the truth is, I happen to know what if you strip the front-matter, despite all the KS macros, the remaining "HTML" that's left actually can all be parsed with `cheerio.load()`. That's because, like a browser, `cheerio` is very forgiving. 

If you want to run `vnu-jar` on the `index.html` files, you can use Yari itself to dump the raw HTML, and then run it that. 
In a Node shell for example:
```
> const { Document } = require('./content')
> doc = Document.findByURL('/en-us/docs/web/css')
> doc.rawHTML
```

Another potentially interesting option is to write a script that uses `await buildDocument(doc)` but before you call it, you do a regex replace on all `{{KSMACROS}}` in the `doc.rawHTML` string. Now when you build it, you'll get the fully rendered HTML but without the KS macros messing things up.

**Comment by nschonni** [comment]
@peterbe  you can see the annotations that vnu-jar can add to PRs here https://github.com/mdn/content/pull/418/files#file-files-en-us-web-accessibility-aria-aria_techniques-using_the_aria-valuemax_attribute-index-html-L51
But adding it will require the escaping

**Comment by sideshowbarker** [comment]
> you can see the annotations that vnu-jar can add to PRs here [#418 (files)](https://github.com/mdn/content/pull/418/files#file-files-en-us-web-accessibility-aria-aria_techniques-using_the_aria-valuemax_attribute-index-html-L51)

That is extremely cool

> But adding it will require the escaping

Considered me convinced at least and so FWIW, I personally think the value of being able to catch those legitimate markup errors is worth the tradeoff for the cost of escaping the frontmatter (and I say that as someone who, until I saw https://github.com/mdn/content/pull/418/files#file-files-en-us-web-accessibility-aria-aria_techniques-using_the_aria-valuemax_attribute-index-html-L51, previously didn’t believe it was worth our time to escape the metadata).

As I said in a comment for another issue, the sources can in fact be seen as fully “real” HTML, with the frontmatter just being a text node that’s a direct child of the `body` element — and because the `<body>` and `<html`> start tags are optional (according to the HTML standard), that is in fact what the files are: they’re HTML that has the `<html>` and `<body>` start tags omitted, and the frontmatter is a text node that’s the first child of the `body` element. That’s exactly how an HTML parser sees them.

I am very glad @nschonni put the work into showing that it was practical to run the HTML checker (vnu.jar) on the source files in a useful way. If he hadn’t taken the time to do that — to show evidence of a case where it helps us catch an error we wouldn’t have otherwise, as https://github.com/mdn/content/pull/418/files#file-files-en-us-web-accessibility-aria-aria_techniques-using_the_aria-valuemax_attribute-index-html-L51 does — I think I would have remain unconvinced.

So I think if we were to not do the escaping, and not run the HTML checker on the sources, we will be missing a big opportunity to have something we’d otherwise find extremely useful and end up valuing very highly over the long term.

**Review by sideshowbarker — APPROVED** [review]

**Comment by peterbe** [comment]
I still don't think this is right. If you want to extract the raw HTML with all the kumascript macros unexpanded, and send it into vnu-jar (or something) I would instead recommend something like this:

```javascript
const { Document } = require("./content");
const documents = Document.findAll();
for (const document of documents.iter()) {
  console.log(document);
  const html = `<!doctype>
  <html>
  <head><title>${document.metadata.title}</title></head>
  <body>
  ${document.rawHTML}
  </body>
  </html>
  `
  const errs = await validateHTML(html)
  if (errs) {
    console.log(document.metadata);
    console.log(errs);
    console.log('------------\n');
  }
}
```

**Comment by nschonni** [comment]
The problem with doing the template example like that is that the problem matcher would no longer match the line number correctly.
It's possible that a separate script could try and do the regex/escaping the file in-place before running and leave it in a dirty state, but run in-place afterwards

**Comment by peterbe** [comment]
> The problem with doing the template example like that is that the problem matcher would no longer match the line number correctly.

When use the API, you get the front-matter converted into an object (and the `rawHTML` as discussed/demonstrated) but you also get the offset. I.e. an integer count that basically explains when the second `---` delimiter appeared in the original `index.html`. That's how we can connect the "Show flaws" with a specific line in the original `index.html` file.

**Comment by sideshowbarker** [comment]
> When use the API, you get the front-matter converted into an object (and the `rawHTML` as discussed/demonstrated) but you also get the offset. I.e. an integer count that basically explains when the second `---` delimiter appeared in the original `index.html`. That's how we can connect the "Show flaws" with a specific line in the original `index.html` file.

OK, so the vnu.jar sources internally support a lineOffset parameter, though it’s just not exposed yet to the command-line checker. But I can add a new option to the command-line checker to allow specifying a command-line lineOffset option.

But one big downside: using it would require re-invoking/re-starting the checker once per file — vs running it in batch mode.

It takes only about 3 minutes for vnu.jar to check all 11,000+ files in the tree, in batch mode.

But it’s take hours instead for vnu.jar to check all 11,000+ files in the tree, if it needs to be re-invoked/re-started once per file.

The difference is due the fact that re-invoking the checker once per file means incurring the cost of re-starting the Java VM each time, as well as the cost of re-initializing the checker each time (which takes on the order of 1 or 2 seconds).

In contrast, in batch mode, the VM is started once and kept running and re-used, and the checker is initialized exactly one time.

So for recursively checking all sources in the tree, running the checker in non-batch mode wouldn’t be practical.

But for checking just the specific changed files in a PR, running vnu.jar in non-batch mode would be practical, and would allow the lineOffset option to be used.

**Comment by peterbe** [comment]
Batch mode is awesome. Thanks for building that!

What you could do is dump all the `rawHTML` into `/tmp/` and potentially pad the HTML a bit so the line numbers line up with the error messages. 

We're getting off track, but just thought I'd put that one down for the record.

**Comment by nschonni** [comment]
Closing this one in favour of https://github.com/mdn/content/pull/418

**Pull request closed without merging**
