### PR TITLE
Update index.md adapting the module title

### PR DESCRIPTION
**Pull request by glmvc**
#### Summary

Adapted the module title (and slug) because the other modules in this course also always have "CSS" in front of them.

#### Motivation

I looked over the "overview pages" and noticed that little things differ - just for the sake of consistency of the pages...

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by glmvc** [comment]
Note: Changing the slug gives error because the folder name is still `/Styling_text`.

**Comment by wbamberg** [comment]
Thanks for this PR, @glmvc !

You need to use a special command for moving a document: https://github.com/mdn/content#moving-one-or-more-documents .

**Comment by glmvc** [comment]
@wbamberg no problem, thank you for the reference! As soon as I'm a little more familiar with the git commands (and yarn), I'll make the change properly.

**Comment by glmvc** [comment]
> Thanks for this PR, @glmvc !
> 
> You need to use a special command for moving a document: https://github.com/mdn/content#moving-one-or-more-documents .

Hi @wbamberg,

After revisiting this pr and getting a little more comfortable with git etc, I noticed that the slug on the other CSS module pages doesn't start with `CSS_` - except for the [css layout module](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout) - check its [index.md](https://github.com/mdn/content/edit/main/files/en-us/learn/css/css_layout/index.md)? That's why I thought the slug has to be changed...

But what they all have in common is the title that starts with "CSS".
I do not know now if only by changing the title, the text in the sidebar is also changed?
If so, I can undo the slug change and just change the title accordingly, right?
If not, is this an issue again with `{{LearnSidebar}}` like in [Issue #5164](https://github.com/mdn/yari/issues/5164)?

I apologize for bothering and hope you can help me out - thanks in advance!

**Comment by glmvc** [comment]
@wbamberg Now I know (thanks to you) roughly how LearnSidebar works, thanks again.
So only the title had to be changed here. I'll make the change that affects the sidebar in another PR.

>After revisiting this pr and getting a little more comfortable with git etc, I noticed that the slug on the other CSS module pages doesn't start with CSS_ - except for the [css layout module](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout) - check its [index.md](https://github.com/mdn/content/edit/main/files/en-us/learn/css/css_layout/index.md)? That's why I thought the slug has to be changed...

As already mentioned, the naming of the folder is different for the CSS layout module - i.e. the folder has "Css_" as a prefix.
I do not know now how high the priority on a uniform naming of the folders/documents is... Feel free to let me know if this needs to be changed.

**Review by wbamberg — APPROVED** [review]
Sorry to be slow reviewing this one @glmvc ! Looks good to me.

**Pull request merged**
