### PR TITLE
Replace smart quotes

### PR DESCRIPTION
**Pull request by Josh-Cena**
Markdownlint only replaces smart quotes in plain text.

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
I’m going to not be the one to merge this — because, while I recognize the project seems to have a policy of replacing actual typographical “smart” quotation marks with “dumb” quotation marks instead, I don’t know _when_ a formal decision was ever made to do that, nor _why_ such a decision may have ever been made. I honestly do not understand what the rationale for it is.

**Comment by sideshowbarker** [comment]
Ah, I only just now read the _“Markdownlint only replaces smart quotes in plain text”_ statement in the PR description.

I don’t actually know what the means, but I really hope this is not (another) case where we’re degrading the quality of the content for end users due to wanting to make things work with tooling members of the project have voluntarily chosen to deploy as part of the CI being used.

**Comment by Josh-Cena** [comment]
@sideshowbarker see https://github.com/mdn/content/pull/17988, https://github.com/mdn/content/pull/16770, https://github.com/mdn/content/pull/16324. We have automation that would replace curly quotes in text, but it won't check code because those may be legitimate. Also see our style guide: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#apostrophes_and_quotation_marks

**Comment by sideshowbarker** [comment]
> We already have 99% of the corpus using straight quotes, so I don't think this would degrade quality by any means, and as you can see, there are actual syntax errors caused by someone wrongly using curly quotes to delimit string literals, so it seems far less bug prone to just recommend writers to turn off smart quotes while authoring documentation.

I hear all that. We never should have gotten to the point to begin with where 99% of the corpus using straight quotes. That was the first mistake. And that first mistake is not a sound rationale for further mistakes.

It seems pretty fair to say that in general, replacing typographical quotation marks with “dumb” quotes is objectively not an an improvement in readability and usability for end users.

And the problem of actual someone wrongly using curly quotes to delimit string literals is the kind of thing any linter the project has chosen should be made smart enough to recognize — rather than instead choosing to degrade quality overall.

So I think the entire rationale behind making these changes is pretty seriously misguided, and based on the wrong [Priority of Constituencies](https://www.w3.org/TR/design-principles/#priority-of-constituencies) — which rightly should always be _“If a trade-off needs to be made, always put user needs above all.”_

But if someone from the project can express an actually compelling rationale _based on putting user needs first_ for replacing all smart quotes with dumb quotes, then that would make sense. But as far as I can see, that’s yet to be articulated.

Certainly _“we need to choose one or the other for consistency. If curly quotes or apostrophes make their way into code snippets, even inline ones, readers may copy and paste them, expecting them to function (which they will not)”_ is not that.

All that said, I don’t object to this particular PR being merged. I can see the ship has already sailed on this. But it’s a shame.

**Review by estelle — APPROVED** [review]

**Comment by estelle** [comment]
> But if someone from the project can express an actually compelling rationale _based on putting user needs first_ for replacing all smart quotes with dumb quotes, then that would make sense. But as far as I can see, that’s yet to be articulated.

From my perspective, it's good to catch right single quotes before they enter the code base. 
When typing in a text editor, the single quote comes out as `'`, but when typing in a word processor it comes out as `’`. The ' is similar to ’. And both are similar to ` used in JS. Linting catches unintentional uses of ’, as well as intentional ones, but using ' when ’ is fine in almost all cases (not sure when it's not fine other than when explaining the use, such as in this comment), but using ’ when ' is needed can cause issues.

As an example, I sometimes work on devices other than my main Mac.  When doing so, I email/slack/DM/SMS myself code snippets to copy and paste when I am back at work. It has happened that the code snipped has converted a ' to a ’. The linter has caught it for me, saving me from entering invalid code into our examples / prose.

Lintining out the ’ prevents many headaches. This linting is helpful and is likely even more beneficial for those with cognitive or vision differences.

**Pull request merged**
