### PR TITLE
Fix anchors, JS/HTTP/HTML

### PR DESCRIPTION
**Pull request by Josh-Cena**
Part of https://github.com/mdn/mdn/issues/561

### CODE REVIEW

**Comment by bsmth** [comment]
I'm confused about this reported flaw:

```
/en-US/docs/Glossary/Rendering_engine redirects to /en-US/docs/Glossary/Engine/Rendering
```

What's the macro usage supposed to be here? It's because it's a disambiguation?

**Review by bsmth — APPROVED** [review]
One non-blocking comment (question, really) other changes looking good to me, thank you!

**Comment by Josh-Cena** [comment]
Yes, it was changed to a disambiguation. Not the focus of this PR though.

**Comment by Josh-Cena** [comment]
I am including HTTP docs in this PR because there are only 8 of them.

**Review by bsmth — APPROVED** [review]
Changes since last approval look good, so another +1 and will merge shortly. Thank you, Josh!

**Pull request merged**
