### PR TITLE
add brave to the list of browsers

### PR DESCRIPTION
**Pull request by AlexEG**
### Browsers
line 70
add brave to the list of browsers

update the number of browsers
### Motivation

yes, It might help other to be up to date with the major browsers out there

### CODE REVIEW

**Comment by AlexEG** [comment]
it's my first PR so I hope you give me feedback

**Comment by hamishwillee** [comment]
Thanks, but I don't think we should accept this.

The market share for Brave is relatively insignificant, and you might argue that many other browsers should be mentioned before it.

Browser | Market share
--- | ---
QQ | 1.98%
Sogou Explorer | 1.76%
Yandex | 0.91%
Brave | 0.05%

More important, this isn't supposed to be an exhaustive list of browsers - it's a short list of popular browsers that people might have heard of, to provide context. 

Thanks for contributing.

**Comment by hamishwillee** [comment]
PS Generally MDN is reducing lists of external tools/software throughout the documentation - the lists are hard to maintain and often go out of date. Generally users are better off doing an internet search to find the available options.

**Comment by AlexEG** [comment]
yup, I agree but Brave has mentioned here so I thought it might be not updated yet.

[Installing modern web browsers](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Installing_basic_software#installing_modern_web_browsers)

**Comment by hamishwillee** [comment]
Thanks. Fair enough. IMO it shouldn't have been added there either. Without a stated policy sometimes things slip through - if I were ever to touch that page I would remove it.

**Pull request closed without merging**
