### PR TITLE
code example on white-space property

### LINKED ISSUE #26338: white-space live sample text has different line breaks than HTML sample lorem ipsum
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

### What specific section or headline is this issue about?

in_action

### What information was incorrect, unhelpful, or incomplete?

The "lorem ipsum" HTML sample has different line breaks than the actual HTML used in the live sample "result"

### What did you expect to see?

The HTML sample and the HTML used in the EmbedLiveSample should be the same

### Do you have any supporting links, references, or citations?

Compare: 

https://github.com/mdn/content/blob/main/files/en-us/web/css/white-space/index.md#html

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/white-space`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/white-space/index.md
* Last commit: https://github.com/mdn/content/commit/b82ff59aab7883b7bb2222cf9f9f9b6eed818e08
* Document last modified: 2023-02-21T06:13:19.000Z

</details>

### PR DESCRIPTION
**Pull request by postmeback**
Example text changed

 ❓ The previous example was kind of misleading visually. My changes will make them better.

"Fixes #26338"

### CODE REVIEW

**Comment by estelle** [comment]
We still want to have more than one line of HTML to better show how some values work, and a bit of indenting to show that as well.

I think the main issue is that the text was "prettified". To prevent the automatic processing from breaking lines, instead of starting the HTML example with  
```html
   ```html
```
start the example with 

```html
   ```html-nolint
```

(the indents in the code above can be removed, but I had to indent to show the examples)

**Comment by postmeback** [comment]
So, is it good to go ? @estelle

**Comment by postmeback** [comment]
As, I have just started in this open source contributions, I would be asking question which may sound silly. Please have patience with me !!!

**Review by estelle — APPROVED** [review]
Thank you. Also, congratulations on your first merged MDN content PR. Welcome to he team!

**Comment by postmeback** [comment]
Thanks :smiley:

**Pull request merged**
