### PR TITLE
Update index.md

### LINKED ISSUE #26883: <link> to stylesheet won't work because of missing xmlns
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_and_CSS

### What specific section or headline is this issue about?

First example

### What information was incorrect, unhelpful, or incomplete?

`<link>` needs `xmlns="http://www.w3.org/1999/xhtml" to work`, since `<link>` is not a SVG element. The existing xmlns:xlink in the example is not sufficent.

### What did you expect to see?

Either `xmlns:xhtml="http://www.w3.org/1999/xhtml"` in the SVG element and <xhtml:link...> to reference the stylesheet, or a local namespace declaration like this:

`<link xmlns="http://www.w3.org/1999/xhtml" rel="stylesheet" href="style8.css" type="text/css" />`

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/tutorial/svg_and_css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_and_CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/tutorial/svg_and_css/index.md
* Last commit: https://github.com/mdn/content/commit/b4f998244660723175f8e06b5d77f68cfb1d1f1a
* Document last modified: 2023-03-06T23:38:10.000Z

</details>

### PR DESCRIPTION
**Pull request by chenghao125**
### Description

I have tried the stylesheet dose not work without `xmlns="http://www.w3.org/1999/xhtml`. So I update it.

### Related issues and pull requests
link to stylesheet won't work because of missing xmlns [#26883](https://github.com/mdn/content/issues/26883)

Fix #26883

### CODE REVIEW

**Comment by chenghao125** [comment]
@Josh-Cena Would you mind review the code for me?

**Comment by Josh-Cena** [comment]
Sorry, I'm not familiar enough with SVG to review this PR. Let's wait for some other reviewer.

**Review by wbamberg — APPROVED** [review]
From my reading this is correct, and testing this, the example did not work (outside the page) before, and does with this fix. Thanks @chenghao125 !

I need to find out what the best thing to do about this annoying Prettier error is though, so not merging yet.

**Comment by chenghao125** [comment]
> From my reading this is correct, and testing this, the example did not work (outside the page) before, and does with this fix. Thanks @chenghao125 !
> 
> I need to find out what the best thing to do about this annoying Prettier error is though, so not merging yet.

I'll try to fix it

**Pull request merged**
