### PR TITLE
Improve ResizeObserver examples

### PR DESCRIPTION
**Pull request by iscultas**
I've removed the code duplication and corrected the formatting.

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
I like this code change, but:

First, the code in the page is copied from an example hosted on GitHub (https://github.com/mdn/dom-examples/blob/master/resize-observer/resize-observer-text.html) and it would be good to keep these in sync. It's unfortunate that we have to do this manually :(.

Second. I don't understand this little dance we do with `contentBoxSize`. The comment says "// Checking for chrome as using a non-standard array" but I don't understand what that means. In our docs for this API there is no mention anywhere else of Chrome "using a non-standard array". [The spec](https://drafts.csswg.org/resize-observer/#dom-resizeobserverentry-contentboxsize) says:

> The box size properties are exposed as FrozenArray in order to support elements that have multiple fragments, which occur in multi-column scenarios. However the current definitions of content rect and border box do not mention how those boxes are affected by multi-column layout. In this spec, there will only be a single ResizeObserverSize returned in the FrozenArray, which will correspond to the dimensions of the first column. A future version of this spec will extend the returned FrozenArray to contain the per-fragment size information. 

...which suggests that array is standard. Our docs for [contentBoxSize](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/contentBoxSize) say "The contentBoxSize read-only property of the ResizeObserverEntry interface returns an array", which, OK, but the rest of the page doesn't talk as if it's an array.

It would be great for the docs to be clearer here about what the browser compat issue here is, if there is one. If you know this, perhaps you'd like to have a go at fixing it? If not, perhaps we should file a separate bug (plus one in https://github.com/mdn/dom-examples/ to update the GitHub version of this example).

**Comment by iscultas** [comment]
> Second. I don't understand this little dance we do with `contentBoxSize`. The comment says "// Checking for chrome as using a non-standard array" but I don't understand what that means. In our docs for this API there is no mention anywhere else of Chrome "using a non-standard array". [The spec](https://drafts.csswg.org/resize-observer/#dom-resizeobserverentry-contentboxsize) says:

I've missed the mistake (at this moment) of original author of the example. Because problem not with Chrome returning array, but Firefox returning plain object. I suppose this behavior and comment left from times when specs were very unclear and changeable.

Here small example from my project:
```js
new ResizeObserver(
    entries => {
        for (const entry of entries) {
            console.log('Is contentBoxSize array =', Array.isArray(entry.contentBoxSize));

            console.log(entry.contentBoxSize);

            const contentBoxSize = Array.isArray(entry.contentBoxSize)
                ? entry.contentBoxSize[0]
                : entry.contentBoxSize;

            canvas.width = contentBoxSize.inlineSize;
            canvas.height = contentBoxSize.blockSize;

            requestBarsDraw(drawBars_);
        }
    }
).observe(document.getElementById('canvas-wrapper'));
```

Firefox 86.0 (64-bit) console output:
```
Is contentBoxSize array = false main.js:60:21
ResizeObserverSize { inlineSize: 1536, blockSize: 460.6666666666667 }
main.js:62:21
```

Chrome Version 91.0.4442.4 (Official Build) dev (64-bit) console output:
```
main.js:60 Is contentBoxSize array = true
main.js:62 [ResizeObserverSize]0: ResizeObserverSize {inlineSize: 1028, blockSize: 646.390625}length: 1__proto__: Array(0)
```

So comment `Checking for chrome as using a non-standard array` could be changed to `Checking for Firefox because contentBoxSize returns plain object`.

It also would be great to note this in ResizeObserverEntry documentation as Firefox specific behavior.

**Review by wbamberg — CHANGES_REQUESTED** [review]
Thanks for the clarification, that's really interesting, and explains why the other example: https://mdn.github.io/dom-examples/resize-observer/resize-observer-border-radius.html does not work in Chrome :/.

I'm going to file a couple of extra bugs to update the docs here more generally and to update mdn/dom-examples, but I'm happy to merge this PR, given a little rewording of the comment as suggested.

**Comment by wbamberg** [comment]
I filed https://github.com/mdn/content/issues/3276 for the other updates.

**Review by wbamberg — APPROVED** [review]
Thanks @iscultas !

**Pull request merged**
