### PR TITLE
Remove WindowOrWorkerGlobalScope mixin page

### PR DESCRIPTION
**Pull request by Elchi3**
Follow up to https://github.com/mdn/content/pull/8351

Removing the mixin page as it has no sub pages anymore.

### CODE REVIEW

**Comment by teoli2003** [comment]
I have a few questions:

1. After this PR we will still have mentions of `WindowOrWorkerGlobalScope` in links like:
```
files/en-us/web/http/headers/content-security-policy/script-src/index.html
169:   <li>{{domxref("WindowOrWorkerGlobalScope.setTimeout")}}</li>
170:   <li>{{domxref("WindowOrWorkerGlobalScope.setInterval")}}</li>
```
Do you think we should fix these in this PR?
(I think these are the only ones, but I have not checked old mixins like `WindowTimers` or `WindowBase64` that predates `WindowOrWorkerGlobalScope`)

2. `InterfaceData.json` (now in mdn/content) should be fixed too.
3. Not for this PR, but what sidebar do we want for the now top-level `setTimeout()`, `setInterval()`, `origin`, etc?

**Review by teoli2003 — CHANGES_REQUESTED** [review]
See my previous comment.

**Comment by Elchi3** [comment]
Did you see this PR has two commits? The second fixes links and interfaceData.

**Comment by teoli2003** [comment]
Strange. I looked at the "Files Changed" tab and the files of the 2nd commit didn't appear there. They do now. Weird.

**Review by teoli2003 — APPROVED** [review]
Looks good to me.

**Pull request merged**
