### PR TITLE
Add example for XSLTProcessor `getParameter()` method

### PR DESCRIPTION
**Pull request by T34-active**
### Description
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XSLTProcessor/getParameter
### Related issues and pull requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/xsltprocessor/getparameter/index.md
* Last commit: https://github.com/mdn/content/commit/e561fa67af347b9770b359ba93e8579d2a540682

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
See https://github.com/mdn/content/pull/35431#pullrequestreview-2240690810

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
See https://github.com/mdn/content/pull/35431#pullrequestreview-2240690810

**Review by Josh-Cena — COMMENTED** [review]
So this one is a bit tricky. `getParameter` is actually insignificant in transforming documents, so we don't need to show a complete transformation. I think all we need as example is this:

```js
const xsltProcessor = new XSLTProcessor();
xsltProcessor.setParameter(null, "foo", "bar");
console.log(xsltProcessor.getParameter(null, "foo")); // "bar"
```

...and we can get rid of all the other bluff like the HTML and live result, since this can be verified in the console directly. What do you think?

**Comment by T34-active** [comment]
> So this one is a bit tricky. `getParameter` is actually insignificant in transforming documents, so we don't need to show a complete transformation. I think all we need as example is this:
> 
> ```js
> const xsltProcessor = new XSLTProcessor();
> xsltProcessor.setParameter(null, "foo", "bar");
> console.log(xsltProcessor.getParameter(null, "foo")); // "bar"
> ```
> 
> ...and we can get rid of all the other bluff like the HTML and live result, since this can be verified in the console directly. What do you think?

Yes, I agree with you.

**Comment by Josh-Cena** [comment]
I would suggest removing all comments, except the output indicator. What I wrote above is fine to be put literally as an example.

**Review by Josh-Cena — APPROVED** [review]
Thanks

**Pull request merged**
