### PR TITLE
fix URL fragments in links

### PR DESCRIPTION
**Pull request by mfuji09**
#### Summary

Fix URL fragments in links

#### Motivation

They are reported as link flaws.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by wbamberg — CHANGES_REQUESTED** [review]
Thanks for the PR!

It looks like these want to be "#bitwise_operators" ?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators#bitwise_operators

**Review by estelle — CHANGES_REQUESTED** [review]
I think the anchor is #bitwise_operators
```html
<h3 id="bitwise_operators"><a href="#bitwise_operators" title="Permalink to Bitwise operators">Bitwise operators</a></h3>
```

**Comment by mfuji09** [comment]
@wbamberg @estelle 
Thank you your reviews!
As you said, they should be \#bitwise_operators. 
I have replaced all of them and in additional two files,

**Review by estelle — APPROVED** [review]
Thank you!

**Review by wbamberg — APPROVED** [review]
Sorry @mfuji09 ! These look good now.

**Pull request merged**
