### PR TITLE
add slot tag to flow content list

### LINKED ISSUE #27991: <slot> missing from Flow content element list
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories

### What specific section or headline is this issue about?

Flow content

### What information was incorrect, unhelpful, or incomplete?

The `<slot>` element is missing from the Flow content list of elements. I noticed it was included in Phrasing content, but not Flow content.

If the `<slot>` element is not meant to be missing in Flow content, then I don't think the Phrasing content should be described as `a subset of Flow content` (under the Phrasing content heading) and the [Venn diagram](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories/content_categories_venn.png) is wrong.

### What did you expect to see?

The `<slot>` element should appear under the `<select>` element within the Flow content section.

### Do you have any supporting links, references, or citations?

No, I didn't look at the docs... 😆  
Either the `<slot>` element is also Flow content, or the [Venn diagram](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories/content_categories_venn.png) is wrong and some Phrasing content is outside of Flow content.

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/content_categories`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/content_categories/index.md
* Last commit: https://github.com/mdn/content/commit/c302e71520c9df718363d8ce81d93568ff84be14
* Document last modified: 2023-05-22T12:42:48.000Z

</details>

### PR DESCRIPTION
**Pull request by ir3ne**
### Description

Closes: #27991

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Not a blocker, but could you add the other changes I suggested in https://github.com/mdn/content/issues/27991?

> - `<bdi>` is phrasing
> - `<a>` is interactive only if `href` is present
> - `<dialog>` is flow
> - `<search>` is flow
> - Text is flow

**Comment by ir3ne** [comment]
@Josh-Cena added.

**Review by Josh-Cena — APPROVED** [review]
I've made some edits myself. FYI:

- When I say "text" I mean "text", not `<text>` (you could tell from my formatting).
- `Location.href` and `HTMLAnchorElement.href` are different, and both are different from the HTML `href` attribute. We don't link from HTML to the IDL attribute.

**Comment by Josh-Cena** [comment]
Thank you, and welcome to MDN :)

**Comment by ir3ne** [comment]
@Josh-Cena thanks for the explanation 😀

**Pull request merged**
