### PR TITLE
EyeDropper can only be used in a secure context

### PR DESCRIPTION
**Pull request by felipemarcos**
This wasn't true in Chrome 95 though.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@FelipeMarcos Has there been a corresponding update to browser compatibility? 

Can you also please update https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper with the macro `{{securecontext_header}}` (up the top)

**Comment by FelipeMarcos** [comment]
> @FelipeMarcos Awesome - has there been a corresponding update to browser compatibility data for EyeDroppe (i.e. the secure_context sub-feature)?

This is my first contribution, so I'm not sure where to look for that info. 
Does [this PR](https://github.com/WICG/eyedropper-api/commit/dcaa8e28da87a5ad0ec4680fd91bf645430a3bc0) answer your question?

**Comment by hamishwillee** [comment]
Thanks @FelipeMarcos 

OK, so this is great as far as it goes, but I need to verify this. That's why I asked about browser compatibility data - if that had been done the verification process would be complete and I could just merge this.

Have you any links to information that states the version the requirement is added? I tried this on a local file on Chrome 96 and it did not fail, as I would have expected (as a local file is not a secure context I don't think).

I've started the browser compat data, here: https://github.com/mdn/browser-compat-data/pull/13808
That is pending confirmation too.

**Comment by FelipeMarcos** [comment]
> Have you any links to information that states the version the requirement is added?

No, sorry! I couldn't find anywhere a link to support this claim. 

> (as a local file is not a secure context I don't think)

I thought the same, but according to the docs "`file://` URLs are considered to have been delivered securely."

**Review by jpmedley — APPROVED** [review]

**Pull request merged**
