### PR TITLE
Fix various problems in Array.p.find|findIndex

### LINKED ISSUE #4239: mixup find vs findIndex doc?
The note warning: "Index 0 will be interpreted as a Falsy value in conditional statements." that is found in find() docs seems to be intended for findIndex() doc.
https://github.com/mdn/content/blob/904d4bece328bd19d8aea952aebf4ed5e05d367c/files/en-us/web/javascript/reference/global_objects/array/find/index.html#L78

### PR DESCRIPTION
**Pull request by sideshowbarker**
* Move statement about return value being falsy if array element found at index 0. Fixes https://github.com/mdn/content/issues/4239.

* Remove polyfills

* Fix fixable flaws

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
This looks great, but it also needs to delete the corresponding:

> \<p class="warning">Index \<code>0\</code> will be interpreted as a {{Glossary("Falsy")}}
  value in conditional statements.\</p>

...from the find() page.

**Comment by sideshowbarker** [comment]
> This looks great, but it also needs to delete the corresponding:
> 
> > <p class="warning">Index <code>0</code> will be interpreted as a {{Glossary("Falsy")}}
> > value in conditional statements.</p>
> 
> ...from the find() page.

oops — thanks, pushed a fix now

**Review by wbamberg — APPROVED** [review]
Thanks @sideshowbarker !

It's weird that the preview URL for the page is still showing that paragraph: https://pr4247.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#return_value although you've definitely removed it in this PR.

**Comment by sideshowbarker** [comment]
> It's weird that the preview URL for the page is still showing that paragraph: [pr4247.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#return_value](https://pr4247.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#return_value) although you've definitely removed it in this PR.

Maybe it was due to browser having loaded from is cache?

**Pull request merged**
