### PR TITLE
Improve browsing context definition

### PR DESCRIPTION
**Pull request by adamchainz**
### Description

Changes to clarify and improve the grammar of this definition.

### Motivation

Correct grammar and disambiguation.

### Additional details

n/a
n
### Related issues and pull requests
n/a

### CODE REVIEW

**Comment by adamchainz** [comment]
Netlify tests failed with some kind of race condition:

```
9:11:39 AM: Failed during stage 'preparing repo': git ref pull/21149/head does not exist
```

**Comment by adamchainz** [comment]
@j9t would you like to review? Your tweet inspired me to look this up 😅

**Review by j9t — COMMENTED** [review]
Haha, thanks @adamchainz!

Don’t have approval rights here but from what I can tell, LGTM!

(Side note: I had drafted a post on this depending on the [poll](https://twitter.com/j9t/status/1575013368167305216) results… not that anyone is surprised that there’s also something coming up from my end :)

**Review by Elchi3 — APPROVED** [review]
Thanks much and welcome to mdn/content! 🎉 

(no idea about the netlify thing, updating this branch to latest main made it work as intended)

**Pull request merged**
