### PR TITLE
Add an example for IntersectionObserver.observe()

### PR DESCRIPTION
**Pull request by takeaways**
> What was wrong/why is this fix needed? (quick summary only)
I wanted to find some example here but i couldn't,
so I tried to add some example code

> Issue number (if there is an associated issue)

> Anything else that could help us review it

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks for this PR! It looks like your editor is reformatting the content, could you please not do this? It makes it much harder to review the change you've made.

**Review by wbamberg — CHANGES_REQUESTED** [review]
This example looks great to me. If you would revert the other formatting changes in this file I'll merge it.

**Comment by takeaways** [comment]
> This example looks great to me. If you would revert the other formatting changes in this file I'll merge it.

@wbamberg I followed your guide, Thank You.

**Review by wbamberg — APPROVED** [review]
Looks great, thanks @takeaways !

**Pull request merged**
