### PR TITLE
chore(ci): limit where PR labeler workflow can run

### PR DESCRIPTION
**Pull request by bsmth**
Currently the pr labeler workflow runs on forks, see https://github.com/bsmth/content/pull/2/checks

__changes:__
* Check that it's running against `mdn/content` repo
* prefer `pull_request` with branches instead of `pull_request_target`. See [keeping actions secure](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/).
* Sentence-case workflow name

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by bsmth** [comment]
Thank you 🙌🏻

**Comment by teoli2003** [comment]
I'm reverting. There is a problem.

**Comment by caugner** [comment]
> I'm reverting. There is a problem.

@teoli2003 @bsmth I'm curious, what was the problem?

**Comment by teoli2003** [comment]
Citing @bsmth who investigated and found the problem:

> oh, it doesn't have credentials for the labeler action.restricted (recommended if the action does a checkout):
> 
>```
> on:
>   pull_request:
>     branches:
>       - main
>```
> 
> allowed to pass repo creds to actions/labeler:
> 
>```
> on:
>   - pull_request_target
>```

**Pull request merged**
