### PR TITLE
Remove-redirect non agnostic webext page about Fx WebExt differentiators

### PR DESCRIPTION
**Pull request by SphinxKnight**
While working on https://github.com/mdn/translated-content/issues/12579, I came across https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Firefox_differentiators and thought the content was not agnostic enough and such a topic would be better covered by https://extensionworkshop.com/documentation/develop/browser-compatibility/

Please let me know if I was too incisive.

### CODE REVIEW

**Comment by hamishwillee** [comment]
My gut feeling is that this is "too incisive", because there is a difference between compatibility and differentiators. The browser compatibility is about coding - things that you will need to compensate for as you are writing an extension. The differentiators doc is by contrast is about features that users get as benefits when working in Firefox.

However I'm not the right reviewer. @rebloor Would it be you, or someone else you can point to?

**Comment by rebloor** [comment]
@SphinxKnight @hamishwillee I'm not sure whether this is a regression or an omission, but the content of this page is already on Extension Workshop: https://extensionworkshop.com/documentation/develop/unique-firefox-capabilities/ 
So could we:
- amend the redirect accordingly
- remove Firefox differentiators item from the [Browser extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) sidebar menu

**Comment by SphinxKnight** [comment]
Thanks a lot @hamishwillee and @rebloor, I was naively thinking the sidebar was dynamically generated from the content tree and should have known better.

I've fixed the redirect and created https://github.com/mdn/yari/pull/8649

**Review by rebloor — APPROVED** [review]

**Comment by rebloor** [comment]
@SphinxKnight thanks for this, and just to confirm, you followed the [delete a page instructions](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Creating_moving_deleting#deleting_pages)?

**Comment by SphinxKnight** [comment]
> @SphinxKnight thanks for this, and just to confirm, you followed the [delete a page instructions](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Creating_moving_deleting#deleting_pages)?

Yes, I used `yarn content Mozilla/Add-ons/WebExtensions/Firefox_differentiators --redirect https://extensionworkshop.com/documentation/develop/unique-firefox-capabilities/` on my local repo

**Pull request merged**
