### PR TITLE
Avoid confusing mention of header in "Responsive images"

### PR DESCRIPTION
**Pull request by ddbeck**
#### Summary

The text here brings up the header when it's talking about the content image. This fixes it to avoid the confusion mentioned in https://github.com/mdn/content/issues/9858.

#### Related issues
https://github.com/mdn/content/issues/9858.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
I'm not sure this fix is right and I'm not sure I agree with the report. (That said if the report is confused that's clearly evidence for the page being confusing :).

The paragraph is talking about 2 separate images: the header image (featuring an avenue of trees) and the content image (featuring Chris and a small child).

The paragraph says:

> The header below looks OK, but it's starting to take up a lot of the screen height for a mobile device. 

...which is true - because the header isn't being scaled it ends up using a lot of screen space.

The paragraph also says:

> at this size, it is difficult to see the people within the first content image.

...which is also true - because the image is being scaled to fit the screen width, the people (Chris and the small child) get tiny.

It looks like the issue report:

> The information in this section I mentioned above is not making any sense. It says "In small screen the header image is taking lot of height" but that is not that case actually it's the opposite. The header image is getting very small instead of large so that's why the people in the image are hard to see.

...thinks this paragraph is only talking about the content image, but it's not.

I'm not sure how we could make this clearer. The page already distinguishes "the header image" and "the content image", and refer to them in this paragraph using those names. Maybe we could annotate the screenshot to label the images?

Or we could change this paragraph to, say "the header image" rather than "the header below"?

**Comment by Junaid-1993** [comment]
I noticed another thing while I was investigating this example on both browsers chrome and firefox. In the first example not-responsive.html there is no "<meta name="viewport" content="width=device-width" />" tag. So generally if we don't have this tag in the head of our document then things are not responsive. The thing is by not having this tag and having this tag in both conditions firefox is behaving the same but chrome on the other by not having this tag is behaving differently on the header image which is scaling down and by having this tag it behaves differently by not scaling the header image down.

My question is why firefox don't act like chrome when "<meta name="viewport" content="width=device-width" />" is not present in out document.

Below is the link to MDN not-resonsive.html document. 

> https://github.com/mdn/learning-area/blob/master/html/multimedia-and-embedding/responsive-images/not-responsive.html

Below is the link to MDN responsive.html document.

> https://github.com/mdn/learning-area/blob/master/html/multimedia-and-embedding/responsive-images/responsive.html

**Comment by ddbeck** [comment]
> This seems to be dependent on the browser and the exact numbers used for the simulated device in responsive design mode.

OK, this is the thing. I didn't see any change in the header image between the unresponsive and responsive examples, so I took this to mean that the header would _never_ change and it didn't make sense to talk about it.

It seems to me that this needs a more pervasive rewrite, either to spell out the breakpoints (and maybe deal with a bit of compat fussiness) or to eliminate the header from consideration. Both routes seem to call for quite a lot of work, which I'm not really available to do at the moment (I thought this would be a quick fix, as you can tell). I'm not sure if I should leave this open for someone else to take up (or for me to get around to it, someday) or close it and make a note of things on the original issue.

**Comment by Junaid-1993** [comment]
Ok, You can do whatever you think is best. I just wanted to express my thoughts on the confusion that it made when I was reading this paragraph in responsive images that's all.

Thank you.

**Comment by ddbeck** [comment]
I've left a comment referring to the discussion here on the original issue.

**Pull request closed without merging**
