### PR TITLE
Add whitespace around images, to make black edges visible in dark mode.

### PR DESCRIPTION
**Pull request by wilcooo**
### Description

Images on [this page](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/menclose) about the <menclose> element don't work as intended when using dark mode. You cannot see the black edges & borders, which are quite relevant.

I added some white padding around them.

### Motivation

Lines & borders of these images where invisible in dark mode.

### Additional details

I also made all images of equal size for visual appearance.

### CODE REVIEW

**Comment by fred-wang** [comment]
Thanks!

Yes using images of formulas is problematic for dark mode :innocent: 

PR test bot is failing. Can you please ensure the images are compressed? https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Images_media#compressing_images

**Comment by wilcooo** [comment]
Images are compressed now, so marking this PR as ready again.

Sidenote: Somehow the test already succeeded only after merging main.. Are those compression tests set up to only check the files changed in the latest commit, as opposed to the full PR?

**Comment by fred-wang** [comment]
@wilcooo Thanks. the tests are not run automatically for new contributors ; I just launched them now.

**Comment by teoli2003** [comment]
@fred-wang I think this is good to go?

**Comment by fred-wang** [comment]
@teoli2003 yes sure.

Thanks again @wilcooo !

**Review by teoli2003 — APPROVED** [review]

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:

**Pull request merged**
