### PR TITLE
Smoothly animate seconds hand in the clock

### PR DESCRIPTION
**Pull request by ADTC**
### Description

Smoothly animate seconds hand in the clock in the Animated Clock example for `canvas`. Sample video below:

https://github.com/mdn/content/assets/6047296/5506aad9-9cf5-4de0-aec5-13abe6cea799

### Motivation

To properly showcase the fact that the canvas is drawn 60 times per second, the second hand in the clock now smoothly moves instead of jumping from tick to tick (once per second).

### Additional details

* Applies to: [Basic_animations#an_animated_clock](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_animations#an_animated_clock)
* Tested using MDN Playground.

### Related issues and pull requests

Superseded by #29534

**PS: Please use "Squash and Merge"; thank you.**

### CODE REVIEW

**Comment by hamishwillee** [comment]
> To properly showcase the fact that the canvas is drawn 60 times per second, the second hand in the clock now smoothly moves instead of jumping from tick to tick (once per second).

Thank you, but I don't believe this change proves the assertion ^^^ and it isn't really adding anything for readers.

- The user looking at this now is not going to think "hey, I'm seeing a 60 FPS update". The truth is, it could be a 20K update and they'd see the same thing. 
- It doesn't shows them anything "new" - the previous examples shows smooth animations, and this one shows you a discrete animation.

What would be a slight benefit perhaps is an explanation of the example telling readers that the image is updated at 60FPS but you only see the change when the call to now() updates the seconds.

Closing as "not an improvement".

**Comment by ADTC** [comment]
Fair point. I can open a PR for that, as I consider it important to disclose. I think it will also be nice to include how to make it a sweeping second hand. Here are two versions:

### 1: Result block

> ### Result
> > **Note:** Though the image appears to change only once every second, it is updated at 60 frames per second. For a sweeping second hand, change the constant `sec` to `now.getSeconds() + now.getMilliseconds() / 1000`.
> 
> _(Result block follows.)_

### 2: JS comment + Result block

> ### JavaScript
> ```js
> ...
> ctx.restore();
> 
> const sec = now.getSeconds();
> // For a sweeping second hand, use:
> // const sec = now.getSeconds() + now.getMilliseconds() / 1000;
> const min = now.getMinutes();
> const hr = now.getHours() % 12;
> 
> ...
> ```
> ...
> ### Result
> > **Note:** Though the image appears to change only once every second, it is updated at 60 frames per second. For a sweeping second hand, use the alternative version of `const sec`.
> 
> _(Result block follows.)_

I think including it in JS would make it easier to try using the Playground. Or you can suggest.

**Comment by hamishwillee** [comment]
That's reasonable and useful.

**Comment by hamishwillee** [comment]
Reopening it to make it easier for you to modify

**Comment by ADTC** [comment]
Closing in favor of #29534

**Pull request closed without merging**
