### PR TITLE
Add a missing comma

### PR DESCRIPTION
**Pull request by hannob**
### Description

The sentence is missing a comma.

### Motivation

Correct punctuation makes reading easier.

### Additional details

-

### Related issues and pull requests

-

### CODE REVIEW

**Comment by bsmth** [comment]
Thanks a lot for the suggestion, but I will close this as we do not accept grammar-only (or punctuation-only) changes, see https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests#open_a_pull_request. Thank you :)

**Comment by hannob** [comment]
I am a bit surprised by the fact that you don't appear to want to have correct spelling and punctuation in MDN. It's also not how I read the policy you linked.

It says: "This document describes how contributors make changes to MDN Web Docs and how the changes are reviewed and land on the site. Content changes to MDN Web Docs include: [...] Minor fixes and small updates to the site for fixing typos, grammatical issues, and technical inaccuracies."

Further down it says this about grammar changes: "Don't make grammar-only changes: MDN Web Docs contains technical documentation; you should not suggest prose style changes except where grammar is incorrect."

This is a bit unclear, but I read it as: "Don't make stylistic/prose changes like 'I like this sentence better if we turn things around'". But it says "except where grammar is incorrect" <- I think this applies here.

The sentence as it is right now is incorrect grammar.

**Comment by Josh-Cena** [comment]
@hannob Commas after adverbs are optional in many informal styles in English, especially casual American English. MDN does not try to be exactly literary in terms of register.

**Comment by dipikabh** [comment]
Hi @hannob, we appreciate your enthusiasm for contributing to MDN to keep our docs correct! 🙌 

While the addition of the comma is correct, but in this instance, its absence does not hamper the comprehension of the sentence.

We do care about readability and clarity of the content on MDN. In future pull requests, consider including multiple corrections rather than focusing on minor changes. It will be more likely to get such a pull request merged. We want to prioritize changes that have a substantial impact.

We look forward to seeing your contributions in the future! Thank you.

**Pull request closed without merging**
