### PR TITLE
Fix typo - Line #45

### PR DESCRIPTION
**Pull request by jayantchandra**
### Description

Fix a typo on Line #45 from "sunch" to "such". 
The typo is currently active in production at https://developer.mozilla.org/en-US/docs/Web/HTML/Element#sectioning_root

### Motivation

I'm making these changes to contribute in ironing out the unintended errors compiled while writing the documentation.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by teoli2003** [comment]
There is a strange test failure (Likely unrelated to this PR). I have called for help.

**Comment by teoli2003** [comment]
The problem has been solved. (It was independent of this PR)

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! 🎉 

(If you are looking to contribute further, here is a list of possible tasks: https://github.com/orgs/mdn/projects/25 )

**Comment by model-map** [comment]
> Thanks a lot!
> 
> Looks good to me.
> 
> Congratulations upon your first merged commit here! Welcome aboard! tada
> 
> (If you are looking to contribute further, here is a list of possible tasks: https://github.com/orgs/mdn/projects/25 )

Thank you :) I checked out your work. You have commendable achievements. Honored to have come across you. Cheers!

**Comment by teoli2003** [comment]
Thank you for your kind words. 😃

**Pull request merged**
