### PR TITLE
lowercase all anchor links

### PR DESCRIPTION
**Pull request by peterbe**
A "temporary" solution to https://github.com/mdn/yari/issues/2524

### CODE REVIEW

**Comment by peterbe** [comment]
@chrisdavidmills This'll make those anchor links work. For now. Ideally it should be  flaw check. But one thing at a time.

**Comment by peterbe** [comment]
It's a draft PR because I only started in a sub-tree.

**Comment by peterbe** [comment]
@chrisdavidmills I can do more later. This'll get us started. Would you mind reviewing these changes here and I'll create a PR tomorrow to do the remaning ones?

**Review by chrisdavidmills — APPROVED** [review]
LGTM; thanks!

**Pull request merged**
