### PR TITLE
Add InheritanceDiagram to some WebXR event pages

### PR DESCRIPTION
**Pull request by Elchi3**
Per https://github.com/mdn/content/pull/10923#discussion_r761312499 and https://github.com/mdn/content/discussions/10544#discussioncomment-1739581

Thoughts?

### CODE REVIEW

**Comment by ddbeck** [comment]
I like it with the text alongside. 👍

**Comment by jpmedley** [comment]
I like this proposal. I'm happy to merge for you if we have consensus.

**Comment by Elchi3** [comment]
Rebased to not update inheritance data here. I merged https://github.com/mdn/content/pull/8797 instead.

**Comment by Elchi3** [comment]
> I like this proposal. I'm happy to merge for you if we have consensus.

It seems this proposal has indeed consensus. At least I haven't heard otherwise.

**Comment by Rumyra** [comment]
Yeh I'm into it! Looks good @Elchi3 👍

**Comment by Elchi3** [comment]
https://github.com/mdn/yari/pull/5056 will make this a lot better and avoid the weird sizing parameters. Converting to draft for the moment.

**Comment by Elchi3** [comment]
https://github.com/mdn/yari/pull/5056 landed so this PR works nicely now :)

**Comment by Rumyra** [comment]
So we're good to go @Elchi3 ?

**Comment by Elchi3** [comment]
@Rumyra Yes we are :)

**Review by Rumyra — APPROVED** [review]

**Pull request merged**
