### PR TITLE
External links begin with http, not contain it

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
#### Summary

Changed *= to ^= selector while matching external links.

#### Related issues

Issue #13573 

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by NiedziolkaMichal** [comment]
Actually I see that whole example is messed up. Text "(like the second and third ones)" refers to links in example, but those point to "#" which are not external links. Additionally why is external link icon added to "#"? Even selector a[href*="#"] is incorrect.
I will review it further and add another commit.

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by NiedziolkaMichal** [comment]
@teoli2003 Ok I will make another PR then, with changes that I mentioned.

**Comment by teoli2003** [comment]
Sorry, read your comment afterward. Yes, please create another PR:

**Comment by NiedziolkaMichal** [comment]
No problem, #13580

**Pull request merged**
