### PR TITLE
chore: remove meta sub-site

### PR DESCRIPTION
**Pull request by nschonni**
@ddbeck looks like this got scaffolded, but then didn't get filled in. Feel free to close if it's still planned

The Netlify hook could probably be disabled after this

### CODE REVIEW

**Comment by ddbeck** [comment]
@nschonni I started this, but have since left Mozilla and I no longer have privileges on this repo. Probably better to put this question to @Rumyra or @schalkneethling, though if I remember correctly they're probably all busy with an all-company meeting (or travel or recovery holiday) right now.

**Review by caugner — APPROVED** [review]

**Comment by Rumyra** [comment]
Thanks @nschonni - yes we're looking to remove this, but we can't until we have reviewed the content that's already there. Once we've done this, if it's ok, I'll pick it back up with you for removal 👍

**Comment by Rumyra** [comment]
FYI I only closed it so no one would merge it pre-emtively - worth noting we do want to remove, just after a review :)

**Comment by nschonni** [comment]
No problem, if you want to use if for the future cleanup, you can re-open and leave a "Request Changes" review to block it.
Otherwise I can just delete the branch

**Comment by bsmth** [comment]
I'll be taking a look through to decide, @nschonni 🙏🏻  thanks

**Pull request closed without merging**
