### PR TITLE
Wrap children of <mtd> elements into an <mrow> to prevent line breaking.

### PR DESCRIPTION
**Pull request by fred-wang**
#### Summary

This wraps children of MathML `<mtd>` cells into an `<mrow>` group, except for the mtable and mtd articles:

    find files/ -type f -name '*.md' | grep -v mtable/index.md | grep -v mtd/index.md | xargs sed -i 's|<mtd>|<mtd><mrow>|g;s|</mtd>|</mrow></mtd>|g'

Per the MathML specifications, there should be no rendering change. However Firefox does perform line breaking inside MathML table cells when the explicit `<mrow>` is absent (and does not otherwise). Note that this change is really only useful when the `<mtd>` element contains at least two children, but it's easier to write a command line if the remaining cases are included too.

#### Motivation

Users reported broken rendering in Firefox on twitter. Adding an explicit `<mrow>` prevents undesired line breaking inside MathML table cells.

#### Supporting details
[twitter thread where the issue was reported](https://twitter.com/anatudor/status/1487491392251351044)
[fix for the missing parentheses](https://github.com/mdn/content/pull/12531)

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by fred-wang** [comment]
cc @bkardell @meyerweb @Elchi3

**Comment by fred-wang** [comment]
Mmh, actually I'm not sure https://twitter.com/anatudor/status/1487491392251351044) was reported for Firefox. I can't see the bug, I think I'm confused with something else.

I see the bug in chromium and adding these explicit mrow don't help.

**Comment by Elchi3** [comment]
There are many conflicts now. Not sure if you want to revisit this one. Maybe close if this isn't the fix?
Removing my review request for now.

**Comment by fred-wang** [comment]
Yes, let's forget about this for now.

**Pull request closed without merging**
