### PR TITLE
Updated Syntax for fetch-related pages

### PR DESCRIPTION
**Pull request by PrajwalBorkar**
#### Summary

Updated syntax from `Request.*` and `Response.*` files as suggested by @teoli2003 & @OnkarRuikar 
#### Supporting details

Reference [issue](https://github.com/mdn/content/pull/17820#pullrequestreview-1025798386)
#### Related issues

Part of #16662 
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by teoli2003** [comment]
I'm waiting for https://github.com/mdn/fetch-examples/pull/21 to be merged before reviewing again this PR. That way we can reach consistency between the examples in fetch-examples and the snippets in mdn/content.

Thanks for your patience.

**Review by Josh-Cena — COMMENTED** [review]
Should we refactor these changes to align with the fetch-examples changes?

**Comment by teoli2003** [comment]
Yes, we should synchronize them. (So many things in parallel, I can't cope with all: sorry for the delay)

**Comment by Josh-Cena** [comment]
Did the changes myself...

**Review by hamishwillee — APPROVED** [review]
LTGTM - thanks for sorting out.

**Pull request merged**
