### PR TITLE
Typo - remove colon after screenorientation example

### PR DESCRIPTION
**Pull request by hamishwillee**
Just a typo fix.

### CODE REVIEW

**Review by wbamberg — APPROVED** [review]
👍 , but this example doesn't seem to do anything on Firefox or Chrome, despite the BCD?

**Comment by hamishwillee** [comment]
@wbamberg 

Did you try this on mobile? (it works for me)

image

If not, that's the problem. This API is supported but not enabled on Desktop. What I'd like to do is query if locking is supported, but there is no mechanism for this, or for knowing if there are additional conditions like setting full screen that require you to use it. 

If you did try on mobile, what did you see?

**Comment by wbamberg** [comment]
Oh sorry, I only looked at the BCD, which indicated that it is supported on Firefox Desktop.

**Comment by hamishwillee** [comment]
@wbamberg No that's fair enough. The problem is that supported on desktop just means implemented, not "enabled" so it looks like it isn't working. The spec even allows for this, so it is not technically a compat issue. I've asked in BCD if anything can/should be done: https://github.com/mdn/browser-compat-data/pull/14453#issuecomment-1007124535

**Pull request merged**
