### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by ssolunna**
Fixed a typo.

### CODE REVIEW

**Comment by cw118** [comment]
Hi @ssolunna, the original doesn't look like a typo to me — I think it uses the possessive of plural noun "other ISPs" *(as in "other Internet service provider**s**")*, and since that ends with an "s", the apostrophe was just appended to the end of the word: "ISP**s'** ".

**Comment by estelle** [comment]
i think it's the possessive plural as well.

**Comment by ssolunna** [comment]
Oh, I see. Didn't knew that. I'm sorry for wasting your time, should have filed an issue first.

**Comment by cw118** [comment]
> Oh, I see. Didn't knew that. I'm sorry for wasting your time, should have filed an issue first.

Nothing to worry about! Honestly, it's usually not worth it to file an issue just for a small typo, though you can do so to confirm whether a fix is required (and/or what it would consist of) if you're having doubts :)

**Comment by ssolunna** [comment]
Will keep that in mind. Thank you!

**Pull request closed without merging**
