### PR TITLE
Tone done the introduction of the CORS article

### PR DESCRIPTION
**Pull request by mogoh**
#### Summary

I just toned down the aggressive wording.
No content changed.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
I saw this the other day, but had no time to rewrite it.

Thank you!

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:

**Comment by Elchi3** [comment]
Maybe the "Who should read this article?" section isn't needed at all? At least we don't generally make such advices. 

In the learning area, we talk about articles to read before reading the article at hand and that makes sense to me. However, I don't think it makes generally sense to talk about who should read something and who doesn't.

**Comment by teoli2003** [comment]
> Maybe the "Who should read this article?" section isn't needed at all? At least we don't generally make such advices.
> 
> In the learning area, we talk about articles to read before reading the article at hand and that makes sense to me. However, I don't think it makes generally sense to talk about who should read something and who doesn't.

Good point. PR is in.

**Comment by mogoh** [comment]
Thanks for being so welcoming.

**Pull request merged**
