### PR TITLE
fix: correct alphabet case in wiki history

### PR DESCRIPTION
**Pull request by yin1999**
### Description

fix: correct alphabet case in wiki history. Some keys in wikihistory are not the same as the on in document's `slug`.

used script: https://gist.github.com/yin1999/4231a1ee8f60dc3368f0135ee14fed92

### CODE REVIEW

**Comment by bsmth** [comment]
Thanks @yin1999. What's the motivation for the changes? 

I presume this wikihistory file is only updated automatically, so I'm curious if tooling is not respecting the case of the slug or is it the case that the slug has changed and the wikihistory file hasn't been updated to reflect it?

**Comment by yin1999** [comment]
> Thanks @yin1999. What's the motivation for the changes?
> 
> I presume this wikihistory file is only updated automatically, so I'm curious if tooling is not respecting the case of the slug or is it the case that the slug has changed and the wikihistory file hasn't been updated to reflect it?

maybe `the case that the slug has changed and the wikihistory file hasn't been updated to reflect it`

I think we may just change the case manually (did not use `yarn content move`). I've picked up an example: #3649.

**Comment by yin1999** [comment]
And if we do not match the slug and wikihistory (even only with different case), the [Original Wiki contributors](https://developer.mozilla.org/en-US/docs/Glossary/Safe/contributors.txt) would not be listed.

image

**Comment by bsmth** [comment]
> And if we do not match the slug and wikihistory (even only with different case), the [Original Wiki contributors](https://developer.mozilla.org/en-US/docs/Glossary/Safe/contributors.txt) would not be listed.

Thanks for pointing that out

**Review by bsmth — APPROVED** [review]
I tested most of these by grepping over the content repo and they all look correct, for example:

```bash
grep -rE "slug:.+user-valid" files
files/en-us/web/css/_colon_user-valid/index.md:slug: web/css/:user-valid
grep -rE "slug:.+application_role" files
files/en-us/web/accessibility/aria/roles/application_role/index.md:slug: Web/Accessibility/ARIA/Roles/application_role
grep -rE "slug:.+alert_role" files
...
```

Looks good from my side 👍🏻

**Comment by bsmth** [comment]
I'm going to merge this shortly so that it doesn't get stale. Thanks @yin1999 👍🏻

**Pull request merged**
