### PR TITLE
sample edit (please ignore)

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by peterbe** [comment]
@bershanskiy Hey. I think we broke something :(
It seems to get stuck on the `check_redirects`. 
Here's what it looks like:
Screen Shot 2020-12-08 at 3 28 42 PM

I don't know why it's not running. In fact, it shouldn't run at all because the `paths` patterns in that workflow don't match any of the files in this PR. Any idea?

**Comment by peterbe** [comment]
Perhaps this is why! 
Screen Shot 2020-12-08 at 3 47 13 PM

The reason `check_redirects` is even in there is that it's a "required status check before merging". But it's a check that, thanks to your work and my review, is actually optional now. 

Hmm... What to do. 
I wish there was a way to tell GitHub "It's required only if it matters" :)

For now, I'm just going to uncheck that requirement for branch protection because it's unfortunately illogical to depend on something that never happen.

**Comment by peterbe** [comment]
yeah, that solved it.

**Comment by bershanskiy** [comment]
I probably should have mentioned that in #153 or at least linked [earlier discussion](https://github.com/mdn/content/pull/134#issuecomment-735636258).

**Comment by peterbe** [comment]
> I probably should have mentioned that in #153 or at least linked [earlier discussion](https://github.com/mdn/content/pull/134#issuecomment-735636258).

So you did mention it. I was just too lazy to notice. Again, thank you!

I've removed the restriction for now and emailed all the people who should be aware about it.

**Pull request closed without merging**
