### PR TITLE
Updated the incomplete description of TypeError

### PR DESCRIPTION
**Pull request by SaurabhCha**
Please refer the below link for more information and comments:
https://github.com/mdn/content/issues/5545

> What was wrong/why is this fix needed? (quick summary only)
Description of TypeError for fetch was incomplete.

> Issue number (if there is an associated issue)
5545

> Anything else that could help us review it
Please check comments on the issue. I confirmed the change before opening the PR.

### CODE REVIEW

**Review by sideshowbarker — CHANGES_REQUESTED** [review]
Looking back at https://github.com/mdn/content/issues/5545#issue-908374398, I see the issue description was asking for a lot more than just what’s currently in this patch. It says this:

> Maybe something along these lines could work:
> 
> ```
> TypeError
>     There are several reason fetch can be interrupted with a `TypeError`:
>     - it was not possible to build a `Request` object with the provided parameters (e.g. malformed url)
>     - the request was interrupted due to a network error 
>     - ... other reasons for fetch to reject with TypeError ... 
> ```

So the task of resolving issue #5545 involves reading the spec in order to fill out that list — that is, to also list what the spec says are all the “other reasons for fetch to reject with TypeError”.

**Comment by sideshowbarker** [comment]
Closing for lack of response to review comments.

**Comment by SaurabhCha** [comment]
Sorry to see that this is closed, but I never received any kind of notification regarding the required changes. Today I got the mail regarding your comment. I might have provided more clarification. 
Will keep the tab next time. Thanks for the opportunity.

**Comment by sideshowbarker** [comment]
@SaurabhCha I’ve reopened this PR — so you can continue work on this

**Comment by SaurabhCha** [comment]
Thank you, I will check and update the description.

**Comment by SaurabhCha** [comment]
As per description of the issue, there should be several points to be included in the description of Type Error. 
One point was already mentioned in the description. I did the search regarding the same and other reason I could find was network error.  Hence updated the same. If required I can give reference to the other sites regarding the same.

**Comment by sideshowbarker** [comment]
@SaurabhCha I’m closing this again for lack of any actual update to the PR. What would need to be done to complete this is, to go through the Fetch spec and look at each of the places where the spec says the user agent must throw a TypeError, and evaluate whether it’s a case that fits into what the #5545 issue description is asking for, and then write up a description for it to add to the list proposed in https://github.com/mdn/content/issues/5545#issue-908374398.

I count 36 places in the spec where it requires a TypeError to be thrown.

**Pull request closed without merging**
