### PR TITLE
Remove `InterWiki` macro calls, part 8

### PR DESCRIPTION
**Pull request by OnkarRuikar**
Adding to #18974

We are phasing out the `Interwiki` macro: https://github.com/mdn/content/pull/18723#pullrequestreview-1048593401

The PR converts `{{interwiki(...)}}` macro calls to markdown style links `[...](https://…)`.

### CODE REVIEW

**Comment by OnkarRuikar** [comment]
~20 special cases left. I'll pull them tomorrow.

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by teoli2003** [comment]
> ~20 special cases left. I'll pull them tomorrow.

When you are done in en-US can you open an mdn discussion (like https://github.com/mdn/mdn-community/discussions/65) to get them removed from the different translated locales? 

That way, localization leads are aware of the change, and will pay a special attention to PRs cleaning them there.

Thank you very much.

**Comment by OnkarRuikar** [comment]
> When you are done in en-US can you open an mdn discussion?

Ok, I'll do that.

**Pull request merged**
