### PR TITLE
Add color wheel to the glossary

### PR DESCRIPTION
**Pull request by teoli2003**
As part of openwebdocs/project#92 and as suggested in #14651, this PR adds a simple glossary entry for the color wheel.

### CODE REVIEW

**Comment by wbamberg** [comment]
My main reason for asking for a link to a color wheel in https://github.com/mdn/content/pull/14651 is that to understands how to use `hsl()` I need to know which color wheel it uses. The page says "By definition, red is 0deg", but what color is 45deg, or 270deg? I would expect there to be a "standard" color wheel that I can use when I'm trying to work out what values to give to `hsl()`.

Or am I misunderstanding something here?

**Comment by teoli2003** [comment]
Like always, things are more complicated.

I agree with you that we should display the information about which angle corresponds to which hue (for `hsl()` and `hwb()` (In both cases the angle represents the _hue_ and they have the same mapping angle-hue). 

But it doesn't lead to a unique color wheel. These are _cylindrical coordinates_ while a wheel represents only _polar coordinates_ which is a **section** of the cylinder. So a wheel can represent hue-saturation (with a fixed luminance), hue-luminance (with a fixed saturation) in `hsl()`, or hue-whiteness (with a fixed blackness), hue-blackness (with a fixed whiteness in `hwb()`.

Things get even muddier with `lab()` as these are _cylindrical coordinates_ too, but not representing sRGB colors this time. The angle represents the _chroma_ (I still need to double-check that this is a synonym for the hue) and I'm not sure at all that 0% represents red or that the other angles match. 

So I think I will do the following:
- add several examples (3?) of wheels (hue-saturation, hue-luminance, hue-whiteness, hue-blackness, lab one) here in _Color wheel_.
- add a glossary entry about _Cylindrical coordinates_ (for representing colors) [I have been trying to avoid going into such details, but I think we should]
- explicit the hue-angle mapping (likely with a color wheel) in both `hsl()` and `hwb()`.

**Review by estelle — APPROVED** [review]
LGTM

**Comment by teoli2003** [comment]
I resolved the conflict. I think all is ok.

**Pull request merged**
