### PR TITLE
Games - remove tag attribute form front matter

### PR DESCRIPTION
**Pull request by OnkarRuikar**

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by teoli2003** [comment]
For bookkeeping purposes: mdn/mdn#262

**Review by Rorrote — COMMENTED** [review]
307cd1cc634fd306d59cf954090b7de30cd8326f

**Review by Rorrote — COMMENTED** [review]
307cd1cc634fd306d59cf954090b7de30cd8326f

**Pull request merged**
