### PR TITLE
updatecontent/index.html

### LINKED ISSUE #2537: Issue with "How to structure a web form": (providing unlocalized instructions for date formatting)
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form

#### What information was incorrect, unhelpful, or incomplete?
In step 6, example code, you inserted a `<em>formatted as mm/dd/yyyy</em>` element. Apart from the fact that you might offer the same instruction with a `placeholder` or a `title` attribute, this is bad for 2 reasons:
- Card expiry date usually consists of just a month/year date
- `<input type="date">` is formatted according to user's locale, so for an Italian like me the order is dd/mm/yyyy. You are providing conflictual pieces of information. 
`placeholder` is HTML5 feature, so browser either support both it and `<input type="date">`, or none. If the order is relevant, or if you do not want to mention a polyfill at that point, or you want to keep such an instruction, it would be more convenient to express a date in separate `input` or `select` controls, in the preferred order.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/how_to_structure_a_web_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_structure_a_web_form/index.html
* Last commit: https://github.com/mdn/content/commit/ae7855b7d2e257273ab276daa9565de2786947b1
* Document last modified: 2021-01-27T07:44:46.000Z

</details>

### PR DESCRIPTION
**Pull request by Biki-das**
Changed the Card expiry date format which was eariler in "mm/dd/yyyy" to "=MM/YY".

Fixes #2537.

### CODE REVIEW

**Comment by sideshowbarker** [comment]
Hi @Biki-das — can you explain why this change is necessary?

**Comment by Biki-das** [comment]
> Hi @Biki-das — can you explain why this change is necessary?


Debit card expiry date fomat is usually MM/YY  and not dd/mm/yyyy

**Comment by Biki-das** [comment]
> Hi @Biki-das — can you explain why this change is necessary?

I am new to open source, and have started contributing there is another issue in the input format which is set to dd/mm/yyyy, this input can be changed to mm/yy but it's. Not possible to do that with pure html, we will have to use a little bit of JavaScript so can you suggest me some stuff

**Comment by sideshowbarker** [comment]
I notice there’s #2537 has a second part:

> `placeholder` is HTML5 feature, so browser either support both it and `<input type="date">`, or none. If the order is relevant, or if you do not want to mention a polyfill at that point, or you want to keep such an instruction, it would be more convenient to express a date in separate `input` or `select` controls, in the preferred order.

**Comment by Biki-das** [comment]
We can do something like an input area and give a placeholder of mm/yy and that will do the same job,@sideshowbarker

**Comment by Biki-das** [comment]
Hello @sideshowbarker , how do i see the project live, after cloning it, doing yarn start, gives me a page of error

**Comment by sideshowbarker** [comment]
> Hello @sideshowbarker , how do i see the project live, after cloning it, doing yarn start, gives me a page of error

What errors exactly?

**Comment by Biki-das** [comment]
> > Hello @sideshowbarker , how do i see the project live, after cloning it, doing yarn start, gives me a page of error
> 
> What errors exactly?
💔 Loading error - Google Chrome 09-08-2021 21_50_05

this is what i get whenever i start the github repo in my local machine

**Comment by sideshowbarker** [comment]
To fix the https://user-images.githubusercontent.com/72331432/128739658-39bbd06b-e987-4308-bb90-8dfbccf5fc15.png problem, you must ensure there are no spaces in any directory names in the directory tree into which you cloned the repo.

The system reports that *"Folder contains whitespace which is not allowed"* message if it finds the MDN content is in directory tree with any directories that have space in their names.

**Comment by Ryuno-Ki** [comment]
Which operating system do you use?
I found some scripts for Linux / macOS, but the screenshot makes me think you are using a Windows OS.
I filled an issue with Yari (the platform code underneath) to improve the error message.

**Comment by Biki-das** [comment]
Yeah i am on windows currently, thanks for looking to the matter

**Comment by Ryuno-Ki** [comment]
Yari got an update to output the directory in question that causes problems.
Can you merge / rebase the current main into this PR?
(If you need assistance, just say the word)

**Comment by Biki-das** [comment]
> Yari got an update to output the directory in question that causes problems.
> Can you merge / rebase the current main into this PR?
> (If you need assistance, just say the word)

yes i need some help, thanks for asking out

**Comment by Ryuno-Ki** [comment]
Okay. Let's try the GitHub way first.

When you go to https://github.com/Biki-das/content on a desktop / laptop, GitHub shows a banner above the list of files telling you, that your branch is about 300 commits behind master.
Since it is your branch, there should be an option for you to update the branch.

See https://ahmadawais.com/quick-tip-update-an-outdated-fork-on-github-with-a-click/

If that does not work, let us know (I wouldn't do the steps outlined in the article above the video).

**Comment by Biki-das** [comment]
> Okay. Let's try the GitHub way first.
> 
> When you go to https://github.com/Biki-das/content on a desktop / laptop, GitHub shows a banner above the list of files telling you, that your branch is about 300 commits behind master.
> Since it is your branch, there should be an option for you to update the branch.
> 
> See https://ahmadawais.com/quick-tip-update-an-outdated-fork-on-github-with-a-click/
> 
> If that does not work, let us know (I wouldn't do the steps outlined in the article above the video).

Thanks for guiding,will try it as ASAP

**Comment by Biki-das** [comment]
> Okay. Let's try the GitHub way first.
> 
> When you go to https://github.com/Biki-das/content on a desktop / laptop, GitHub shows a banner above the list of files telling you, that your branch is about 300 commits behind master.
> Since it is your branch, there should be an option for you to update the branch.
> 
> See https://ahmadawais.com/quick-tip-update-an-outdated-fork-on-github-with-a-click/
> 
> If that does not work, let us know (I wouldn't do the steps outlined in the article above the video).

tried not working , let me sharing the terminal logs ,when i do a yarn start
app js - projbackend - Visual Studio Code 01-07-2021 12_24_02

**Comment by Biki-das** [comment]
> Okay. Let's try the GitHub way first.
> 
> When you go to https://github.com/Biki-das/content on a desktop / laptop, GitHub shows a banner above the list of files telling you, that your branch is about 300 commits behind master.
> Since it is your branch, there should be an option for you to update the branch.
> 
> See https://ahmadawais.com/quick-tip-update-an-outdated-fork-on-github-with-a-click/
> 
> If that does not work, let us know (I wouldn't do the steps outlined in the article above the video).

tried but did not got the expected result , i am also sharing my current terminal logs when i try to do yarn start
document js - content - Visual Studio Code 18-08-2021 12_37_17

**Comment by teoli2003** [comment]
Your username is `BIKI PC` has a space. Yari can't be built.

**Comment by Biki-das** [comment]
> Your username, `BIKI PC`, has a space. Yari can't be built because of this.
> 

Thank you, will change that !

**Comment by Biki-das** [comment]
Thanks @teoli2003  and @Ryuno-Ki , i was succesfully able to run it in the browser😀😀, now will be working on this file

**Comment by Biki-das** [comment]
https://github.com/mdn/learning-area/pull/393

Changed the Expiry date ,see if this way is appropriate or else we can think of someother way to put in around.feedback much appreciated.

**Comment by Biki-das** [comment]
closing this PR as the payment form is under Mdn/learning-area

**Comment by Biki-das** [comment]
> [mdn/learning-area#393](https://github.com/mdn/learning-area/pull/393)
> 
> Changed the Expiry date ,see if this way is appropriate or else we can think of someother way to put in around.feedback much appreciated.

@teoli2003 @Ryuno-Ki  @sideshowbarker  , please refer the PR

**Comment by Biki-das** [comment]
Hello @teoli2003  @Ryuno-Ki  https://github.com/mdn/content/pull/7643#issuecomment-901345004

hope you look at this and give me a feedback

**Comment by teoli2003** [comment]
Hi! I can't land anything in mdn/learning-area, so I have to pass my turn.

**Comment by Biki-das** [comment]
ok know somenone who is linked with it, Learning-area seems to be unactive from a long time

**Comment by Ryuno-Ki** [comment]
Same. I only have rights on mdn/content.
Perhaps contact @hamishwillee

**Comment by hamishwillee** [comment]
This is closed, so I'm not sure what I'm supposed to do with it. Without looking deeply, the change to a MM/YY format seems sensible.

**Pull request closed without merging**
