### PR TITLE
Fixed a small typo in the Media Streams API Page

### PR DESCRIPTION
**Pull request by davidbludlow**
> What was wrong/why is this fix needed? (quick summary only)

Small typo

> MDN URL of main page changed

https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API

> Issue number (if there is an associated issue)

> Anything else that could help us review it

### CODE REVIEW

**Review by Ryuno-Ki — APPROVED** [review]
Oops. Nice catch!

**Comment by Ryuno-Ki** [comment]
@wbamberg Could you help what to do with these macro flaws?
Can we safely ignore them for this PR?

**Comment by wbamberg** [comment]
> @wbamberg Could you help what to do with these macro flaws?
> Can we safely ignore them for this PR?

I think so, yes. Obviously the PR didn't introduce them and asking PRs to fix all the flaws that were already there is too much. If the PR improves the docs (as this one does) we should take it IMHO.

The flaws seem to be mostly about parts of the API that haven't been documented yet: for example `MediaDeviceKind` is  a real thing in the API. We could remove the link but should also file a big asking for the extra bits of the API be be documented. Some of them seem to be questionable links though, like the BCD links to `active` and `inactive` events, which I don't see in the spec.

Either way it doesn't look trivial to disentangle this.

If we were being lazy (which I generally am) we would just merge this PR. If we were being unlazy we could file an issue to disentangle things, and also merge this PR :).

**Comment by Ryuno-Ki** [comment]
I've been semi-lazy and filled an issue at #4570.

**Comment by Ryuno-Ki** [comment]
This is fine. Thanks, @davidbludlow !

**Comment by hamishwillee** [comment]
> ... We could remove the link but also file a bug asking for the extra bits of the API be be documented. Some of them seem to be questionable links though, like the BCD links to active and inactive events, which I don't see in the spec.

We could, but FWIW I disagree with the approach of deleting links to missing docs that are genuinely required. The flaws are a useful hint that something needs to be done, generated at the location where the work might start. If you remove them, then a lot of people who might see the missing link and do something about it won't even think about it. 

If there is a concern for first time users it should be fixed by improving the flaw description - for any of the broken links from a macro you might for example have `/en-US/docs/Web/API/InputDeviceInfo does not exist - help us by creating a document` (or whatever)

**Comment by wbamberg** [comment]
Honestly I don't feel particularly strongly about this. We used to do it a lot - write links to docs that don't exist. But we edged away from it over the last few years, as it seemed to confuse normal users of the site more than it helped. People just think the link is broken, or the site is broken...

Mostly I think that if the docs are important we should file appropriate-priority bugs to write them.

**Comment by hamishwillee** [comment]
The two things are not mutually exclusive - yes prioritised bugs are important, but placeholder links are useful too.

**Pull request merged**
