### PR TITLE
fix: move/rename "devtools." articles

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@peterbe looks like `yarn conten move ...` missed a few nested slugs one one of the moves. It seemed to work well with one level of folders, but may have run into an issue with a a secont level for the `devtools.panels` stuff

**Comment by nschonni** [comment]
Going to keep this open as a draft for tracking and submit separate PRs that should easier to land

**Comment by nschonni** [comment]
@chrisdavidmills now the the others mostly landed separately, I've rebased out everything but the `devtools.` changes

**Review by chrisdavidmills — APPROVED** [review]
Sorry, keep forgetting about this one.

**Pull request merged**
