### PR TITLE
Fix typo in a code comment

### PR DESCRIPTION
**Pull request by luciandex**
Fix typo in a code comment
The console result is 3 not 4 as is stated in the first comment.

### CODE REVIEW

**Comment by himanshugarg** [comment]
Unless I am missing something, there is no typo there and the comment says what the code does:-
```js
var a, b, c;
<- undefined
a = b = 3, c = 4; // Returns 4 in the console
<- 4
```

**Comment by wbamberg** [comment]
@himanshugarg , yes I think you are right, but this is confusing.


I understand what this code is doing: `a` and `b,` are getting assigned to `3` and `c` is getting assigned to 4.

It seems like the example could be clearer about this effect:

```js
var a, b, c;

a = b = 3, c = 4;
console.log(a); // 3 (left-most)
console.log(c); // 4
```

maybe? But I'm not sure what the point of this example is. "may appear not to have the normal effect of comma operators" - what is the "normal effect" and how is this different?

**Comment by luciandex** [comment]
Yeah, "normal effect" is that we put comma when the last expression is a result of precedent expressions(s).
In that specific case, we give 3 value to `a` & `b` and finally give 4 value to `c` which is not related to `a` or `b`.
I think this is the point of `normal`. :)

**Comment by wbamberg** [comment]
> Yeah, "normal effect" is that we put comma when the last expression is a result of precedent expressions(s).
> In that specific case, we give 3 value to `a` & `b` and finally give 4 value to `c` which is not related to `a` or `b`.
> I think this is the point of `normal`. :)

But by that definition none of the examples in this page are "normal", are they? I guess I just don't understand what is surprising about:

```js
a = b = 3, c = 4; // Returns 4 in console
console.log(a); // 3 (left-most)
```

Anyway, I think this PR is not correct compared with the current page, so we should close it.

**Pull request closed without merging**
