### PR TITLE
Remove WAVE mime type

### PR DESCRIPTION
**Pull request by broofa**
### Description

Remove the `audio/wav` mime type.

### Motivation

Given that the title of this page says, "MIME types (IANA media types)", it should only include official IANA types.

... and despite numerous citations around the web from unauthoritative sites, `audio/wav` is not actually listed anywhere in the IANA MIME type registry: https://www.iana.org/assignments/media-types/media-types.xhtml

In fact, the only [mentions of wav mime types on iana.org](https://www.google.com/search?q=site%3Aiana.org+%22audio%2Fwav) refer to the [experimental] `audio/x-wav` type.

(And, fwiw, the audio/wav type is not mentioned in Apache or NGINX's mime type files.)

### CODE REVIEW

**Comment by broofa** [comment]
Are we (editors) expected to fix failing CI checks?

I've tried to do so, but running `npm run lint:md` doesn't show any issues locally:
```bash
$ npm run lint:md

> @mdn/content@1.0.0 lint:md
> markdownlint-cli2 "**/*.md" && prettier -c "**/*.md"

markdownlint-cli2 v0.11.0 (markdownlint v0.32.1)
Finding: **/*.md !node_modules !.git !.github !tests
Linting: 12013 file(s)
Summary: 0 error(s)
Checking formatting...
All matched files use Prettier code style!
```

(Aside: Doing the above required `git clone`ing this repo (350MB) and `npm install`ing (another 350MB) , and then linting 12,000+ files (2 minutes).  Which seems... "excessive", given the terseness of this change.  Is there a simpler way of doing this?   Should I not worry about the CI checks?)

**Comment by bsmth** [comment]
I also couldn't figure out what's failing here, it's on my list, so I'll investigate this hopefully tomorrow.

**Comment by teoli2003** [comment]
Removing the line created the need for the table to be resized. The message was unclear, I agree.

I fixed this by running Prettier locally using the GitHub and git CLI. This set of command always works to quickly fix an unclear Markdownlint problem.

```
 gh pr checkout 30913
 cd files/en-us/web/http/basics_of_http/mime_types
 npx prettier -w index.md
 git add .
 git commit -m "Run Prettier"
 git push
```

**Comment by teoli2003** [comment]
For one-liner, I'm using most of the time the GitHub UI (not practical in this case because of the table, but works well in a lot of case where you need to edit only one page)

**Review by bsmth — COMMENTED** [review]
Thanks @broofa - I'm okay with merging this given we have separate guides for [web audio codecs](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs) that are linked above this table. It should be noted, thought, that the `webm` subtype is not listed for audio or video types on https://www.iana.org/assignments/media-types/media-types.xhtml, so we could also remove these given the motivation to remove `wav`. Additionally, I'm surprised `audio/mpeg` and `audio/mp4` are missing as I think these are more common. What do you think?

**Comment by broofa** [comment]
> the webm subtype is not listed for audio or video ... so we could also remove these given the motivation to remove wav.

Yup, I don't see any IANA registration for `webm` types. (see below)

> Additionally, I'm surprised audio/mpeg and audio/mp4 are missing as I think these are more common. 
 
These are actually covered by IANA.  [audio/mpeg](https://www.iana.org/assignments/media-types/audio/mpeg) [audio/mp4](https://www.iana.org/assignments/media-types/audio/mp4)

> What do you think?

**This table should be deleted altogether**.  It's described as "The most commonly used MIME types used for web content _[sic]_" which, even in it's current form, is pretty laughable.  And if we remove the non-IANA types all we're left with are the `ogg` types.  So... yeah... it should just go away.

The text already references the [media container formats guide](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers) page, which is a much more useful/accurate/canonical list of media formats for users that actually care about that.

**I would also consider changing the page title to just "MIME types"**. (Remove the "(IANA media types)" bit).   I know that IANA bit is meant to clarify that the page is about RFC6838 types - and maybe it's good for SEO juice - but it's not necessary.  And having "IANA" in the title makes it awkward to discuss non-IANA types, of which there are a lot, including some of the most common types used on the web, as we're (re)discovering.

Historical note: FWIW, I suspect the main reason this table is included in this page is as a relic of the old (years ago) MDN page that actually did contain a pretty comprehensive list of common MIME types.  There used to be 50+ types listed, if memory serves.  I think what we're seeing here are the last vestiges of that after slowly being edited down as the page emphasis has shifted from describing what MIME types exist to what MIME types _are_.

**Comment by bsmth** [comment]
Thanks a lot for the feedback.

> **This table should be deleted altogether**.

Yes, I agree, lets remove it. Shall I make these changes on your branch or would you like to? I cannot submit this as a suggestion because they're outside of the diffed changes.

> I would also consider changing the page title to just "MIME types".

Alternatively, "MIME and IANA media types" although this is so-so. It might be useful for people looking to find out what IANA media types are.

> I think what we're seeing here are the last vestiges of that after slowly being edited down as the page emphasis has shifted from describing what MIME types exist to what MIME types are.

I bet you're right, it's quite interesting, actually.

**Comment by broofa** [comment]
> > **This table should be deleted altogether**.
> 
> Yes, I agree, lets remove it. Shall I make these changes on your branch or would you like to? I cannot submit this as a suggestion because they're outside of the diffed changes.

Whatever is simplest for you.  This has already taken more time that intended to invest in this.

> Alternatively, "MIME and IANA media types" although this is so-so. It might be useful for people looking to find out what IANA media types are.

IANA's role in mime types is relatively obscure (this, despite it being the official registry).  I don't think it warrants a mention in the title, but it's not worth haggling over.  Whatever you think is best.

**Comment by broofa** [comment]
Note: There's also [the Common Mime Types page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types), which I think is the page I remembered as listing 50-some types.

So... maybe remove the current table and just link to that page?

**Comment by bsmth** [comment]
> Note: There's also [the Common Mime Types page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types), which I think is the page I remembered as listing 50-some types.
> 
> So... maybe remove the current table and just link to that page?

Done in 71400d2773712c8305180703ff464adbee1b109c if you want to have a look

**Review by bsmth — APPROVED** [review]
Thanks for your suggestions and feedback. Merging shortly 👍🏻

**Pull request merged**
