### PR TITLE
fix MediaStreamAudioSourceNode usage notes

### LINKED ISSUE #3050: MediaStreamAudioSourceNode recommends unsupported API
https://github.com/mdn/content/blob/f4b8c9ce03bfab2b2a81dc45aa108d1a58aaf301/files/en-us/web/api/mediastreamaudiosourcenode/index.html#L78

While MediaStreamTrackAudioSourceNode seems appealing, it is supported only by Firefox, so its use probably shouldn't be advised against.

### PR DESCRIPTION
**Pull request by mirexdoors**
Fixes #3050

Checklist — To help your pull request get merged faster, please do the following:

1. - [ ] Provide a summary of your changes — say what problem you are fixing, what files are changed, and what you've done. This doesn't need to be hugely detailed, as we can see exact changes in the "Files changed" tab.
1. - [x] Provide a link to the issue(s) you are fixing, if appropriate, in the form "Fixes _url-of-issue_". GitHub will render this in the form "Fixes #1234", with the issue number linked to the issue. Doing this allows us to figure out what issues you are fixing, as well as helping to automate things (for example the issue will be closed once the PR that fixed it has been merged).
1. - [ ] Review the results of the automated checking we run on every PR and fix any problems reported (see the list of checks near the bottom of the PR page). If you need help, please ask in a comment!
1. - [ ] Link to any other resources that you think might be useful in reviewing your PR.

### CODE REVIEW

**Comment by mirexdoors** [comment]
In  MediaStreamTrackAudioNode  there is a mention of the defference between  MediaStreamTrackAudioNode and MediaStreamAudioSourceNode

https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrackAudioSourceNode

**Review by wbamberg — CHANGES_REQUESTED** [review]
Thanks for this PR, @mirexdoors !

The "keep the following in mind." refers to the H3 "Track ordering", and so having a note in between obscures that fact. I think it might be clearer to keep all this advice after the H3.

So what I'd suggest is:
* remove all the stuff between H2 "Usage notes" and H3 "Track ordering"
* keep all of H3 "Track ordering" as it is, except for the last sentence: *"This is why it is typically wiser to use MediaStreamTrackAudioSourceNode, which provides similar capabilities but was better-defined upon being added to the specification, so it's more reliable."* Replace that with a new paragraph, something like:

```
<p>The {{domxref("MediaStreamTrackAudioSourceNode")}} interface is similar to <code>MediaStreamAudioSourceNode</code>, but avoids this problem by letting you specify which track you want to use.</p>
```

**Comment by mirexdoors** [comment]
@wbamberg Ok, thanks! I did it

**Review by wbamberg — APPROVED** [review]
@mirexdoors , sorry to be so slow reviewing this PR again. What you have here looks great to me, and thanks for your contribution!

**Pull request merged**
