### PR TITLE
code example contained copy text

### PR DESCRIPTION
**Pull request by ZPiDER666**
a code example for Proxy contained a text meant to be part of the main text body without being marked as comment.

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thanks for your PR!

I don't understand this comment at all, do you?

Also I think the comment at line 246 is weird: "//giving error here, i1 is null" - presumably it means if you try to run it in a page without a `#item-1` element you get an error? But that's pretty obvious...

I also think the code at 246-255 is quite terse, making it hard to understand. What do you think about:

```js
const item1 = document.getElementById('item-1');
const item2 = document.getElementById('item-2');

view.selected = item1;

console.log(`item1: ${item1.getAttribute('aria-selected')}`);
// item1: true

view.selected = item2;
// selecting item2 de-selects item1:

console.log(`item1: ${item1.getAttribute('aria-selected')}`);
// item1: false

console.log(`item2: ${item2.getAttribute('aria-selected')}`);
// item2: true
```

It would also be good to expand on thew preamble a bit:

> Sometimes you want to toggle the attribute or class name of two different elements. Here's how using the [set()](https://pr13457.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/set) handler.

...it could say something like:

> Sometimes you want to toggle the attribute or class name of two different elements: so when you set the attribute on one element, the attribute is unset on the other one. Here's how to do this using the set() handler.
>
> In the example below we use the `set()` handle to create a proxy `view` which has a `selected` property. When we assign an HTML element to `view.selected`, the element's `'aria-selected'` attribute is set to `true`.
>
> If we then assign a different element to `view.selected`, this element's `'aria-selected'` attribute is set to `true` and the previous element's `'aria-selected'` attribute is automatically set to `false`.

...or something better?

**Comment by sharonytlau** [comment]
> Thanks for your PR!
> 
> I don't understand this comment at all, do you?
> 
> Also I think the comment at line 246 is weird: "//giving error here, i1 is null" - presumably it means if you try to run it in a page without a `#item-1` element you get an error? But that's pretty obvious...
> 
> I also think the code at 246-255 is quite terse, making it hard to understand. What do you think about:
> 
> ```js
> const item1 = document.getElementById('item-1');
> const item2 = document.getElementById('item-2');
> 
> view.selected = item1;
> 
> console.log(`item1: ${item1.getAttribute('aria-selected')}`);
> // item1: true
> 
> view.selected = item2;
> // selecting item2 de-selects item1:
> 
> console.log(`item1: ${item1.getAttribute('aria-selected')}`);
> // item1: false
> 
> console.log(`item2: ${item2.getAttribute('aria-selected')}`);
> // item2: true
> ```
> 
> It would also be good to expand on thew preamble a bit:
> 
> > Sometimes you want to toggle the attribute or class name of two different elements. Here's how using the [set()](https://pr13457.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/set) handler.
> 
> ...it could say something like:
> 
> > Sometimes you want to toggle the attribute or class name of two different elements: so when you set the attribute on one element, the attribute is unset on the other one. Here's how to do this using the set() handler.
> > In the example below we use the `set()` handle to create a proxy `view` which has a `selected` property. When we assign an HTML element to `view.selected`, the element's `'aria-selected'` attribute is set to `true`.
> > If we then assign a different element to `view.selected`, this element's `'aria-selected'` attribute is set to `true` and the previous element's `'aria-selected'` attribute is automatically set to `false`.
> 
> ...or something better?

Hi wbamberg, I was just planning to submit a PR to suggest modification of this example and saw this PR. I totally agree with your opinion on modifying the code a little bit. The original code has used chaining assignments, and the accompanying comment is confusing. Selecting the elements using separate statements definitely improves its readability. Adding more explanation is also good!

**Comment by ZPiDER666** [comment]
agreed, good improvement!

**Comment by wbamberg** [comment]
@ZPiDER666 , @sharonytlau , thanks!

I think as it is I can't really merge this PR because the comment line doesn't make sense to me. If you like the version I have at https://github.com/mdn/content/pull/13457#pullrequestreview-900824903 . I can close this PR and open a new one with that change in, and ask you for any feedback/improvements you can think of. Does that sound like a good plan to you?

**Comment by wbamberg** [comment]
> @ZPiDER666 , @sharonytlau , thanks!
> 
> I think as it is I can't really merge this PR because the comment line doesn't make sense to me. If you like the version I have at [#13457 (review)](https://github.com/mdn/content/pull/13457#pullrequestreview-900824903) . I can close this PR and open a new one with that change in, and ask you for any feedback/improvements you can think of. Does that sound like a good plan to you?

OK, I have had a go at this in https://github.com/mdn/content/pull/13712.

**Pull request closed without merging**
