### PR TITLE
Fix Vue URL used in <script>

### PR DESCRIPTION
**Pull request by qppq54s**
Fix: Vue development version link is not available

### Description

Vue development version link is not available

### Motivation

When I use this link, it is not available. This can cause confusion for other developers.

### Additional details

`https://cdn.jsdelivr.net/npm/vue@3.2.45/index.js` return some import javascript like
```
'use strict'

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./dist/vue.cjs.prod.js')
} else {
  module.exports = require('./dist/vue.cjs.js')
}
```
and `https://cdn.jsdelivr.net/npm/vue@3.2.45` import the development version of vue 

### Related issues and pull requests

There is no related issue

### CODE REVIEW

**Comment by hamishwillee** [comment]
Hi @qppq54s 

So when I try `https://cdn.jsdelivr.net/npm/vue@3.2.45/index.js` I do get the script as documented. If I follow the development link `https://cdn.jsdelivr.net/npm/vue@3.2.45/dist/vue.cjs.js` I get an unminified version of what looks like a sensible development script, in particular if compared to the proposed production script.

If I try the link you are suggesting `https://cdn.jsdelivr.net/npm/vue@3.2.45` I get a file that is a miniified version of `/npm/vue@3.2.45/dist/vue.global.js`

Are you saying that `/npm/vue@3.2.45/dist/vue.global.js` is the minified equivalent of the original script?

@Josh-Cena You know much about Vue?

**Comment by Josh-Cena** [comment]
Sorry, I've never used Vue with a CDN-distributed script :) (Not with Vue 3, at least) But this change looks good to me since the original seems nonfunctional anyway.

**Comment by Josh-Cena** [comment]
Maybe we should follow the official guide, which uses unpkg? https://vuejs.org/guide/quick-start.html#using-vue-from-cdn

**Comment by qppq54s** [comment]
@Josh-Cena I agree with your opinion. I will replace the url with the same as the official website document.

**Review by hamishwillee — APPROVED** [review]
Looks good thanks @qppq54s . Also for advice @Josh-Cena

**Pull request merged**
