### PR TITLE
Markdown links on one line (Part 5 and final part for javascript/)

### PR DESCRIPTION
**Pull request by teoli2003**
Fixes Markdown links to be on one line (better readability and maintenance) + typos

This is the final part for javascript/ 🎉

### CODE REVIEW

**Review by hamishwillee — APPROVED** [review]
@teoli2003 Thanks for this. Markdown links that break across lines really irritate me.

@nschonni Can Markdown link catch this case too?

**Comment by nschonni** [comment]
I'm not sure there is a built in rule for that. I believe the line length rule (not currently enabled) does ignore links though.
There is an option of creating custom rules with Markdownlint, but I've never really done it.

**Comment by teoli2003** [comment]
It would be nice if Markdownlink could catch this.

Note there are still about 680 of them in api/.

I'll remove them little by little: I'm doing this activity when I'm tired and need some easy tasks to perform 😄  (I have a script helping me, but I still need to review carefully as there are quite a few edge cases).

**Comment by hamishwillee** [comment]
FWIW the vast majority of these breaks were carry-over from HTML into markdown. While I am so pleased the current set are being fixed, I don't think that we'll get many of these once those have been fixed.

Summary - very grateful these are being fixed. Rule would be nice. But you'd have to question giving it high priority given the problem isn't likely to be recurrent.

**Pull request merged**
