### PR TITLE
Rewrite intro to <col> element

### PR DESCRIPTION
**Pull request by Manu-crypto**
### Description

 changed the content a little bit.

### CODE REVIEW

**Comment by Manu-crypto** [comment]
have reviewed the urls

**Comment by dipikabh** [comment]
Thanks for you contribution, @Manu-crypto.

I've considered the changes you've submitted and have the following feedback:

- We follow the same writing style for the intro descriptions for all HTML elements. So the first sentence should stay as is. I'm not sure why you added "often"; `<col>` is always created as a child of `<colgroup>`.
- If you check the [Attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col#attributes) section, you'll notice that only the `span` attribute is valid. All others are [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col#deprecated_attributes). So your first sentence referring to width and alignment is not accurate.
- I don't see any issue with the last sentence the way it is now.

I'll be closing this pull request. Please don't hesitate to ping me if you have any questions.

Thank you for using MDN! We look forward to seeing your contributions in the future.

**Comment by Manu-crypto** [comment]
So should I just change the word often

**Comment by dipikabh** [comment]
Hi @Manu-crypto, the original description is okay as is.

**Comment by Manu-crypto** [comment]
ok

**Pull request closed without merging**
