### PR TITLE
Remove docs for the <blink> element

### PR DESCRIPTION
**Pull request by Elchi3**
For https://github.com/mdn/browser-compat-data/pull/19658

### CODE REVIEW

**Review by estelle — APPROVED** [review]
Wow. This is kind of sad. So many memories.

**Comment by bojavou** [comment]
The 90s are officially over.

**Comment by macabeus** [comment]
If someone wants to feel a bit of nostalgia from the golden age of the Internet, here's the doc available from Internet Archive:
http://web.archive.org/web/20230415231254/https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blink

**Comment by MrBrain295** [comment]
@Elchi3 https://github.com/orgs/mdn/discussions/296

**Pull request merged**
