### PR TITLE
remove devicePizelRatio

### PR DESCRIPTION
**Pull request by toastal**
This file/folder/slug shouldn't exist, but I saw it reading some documentation. There already exists a correctly named `devicePixelRatio` page.  Not really sure how the `_wikihistory` works though.

### CODE REVIEW

**Review by chrisdavidmills — COMMENTED** [review]
This looks like it is probably OK. Did you use the delete commend to do this, as in https://github.com/mdn/content#deleting-a-document ?

**Comment by peterbe** [comment]
@toastal You might wanna try again and see if you can avoid the conflict this time.

**Comment by nschonni** [comment]
I'm thinking this is actually the right file (rather than the weird zero width space one I fixed), so maybe #324 is corrected, and is just missing a redirect

**Comment by sideshowbarker** [comment]
Closing as superseded by 6d9a4ed / #975

**Pull request closed without merging**
