### PR TITLE
Remove Mozilla/Projects/NSS

### PR DESCRIPTION
**Pull request by peterbe**
It's added to the archive here: https://github.com/mdn/archived-content/pull/19

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
LGTM

**Comment by chrisdavidmills** [comment]
@peterbe hrm, this one has redirect failures on it.

**Comment by peterbe** [comment]
I'm really struggling to get the redirects to work. :(
When I add the `*/docs/Mozilla/Projects/NSS/*` lines, it fails the redirects checks. When I run `fix-redirects` it goes nuts and removes a bunch of weird files. 
Either way, I'd rather not do it anyway. It's better to use fundamental redirects for large blocks like this. So I'm going to wait till https://github.com/mdn/yari/issues/3692 lands then merge this PR.

**Comment by peterbe** [comment]
@escattone @chrisdavidmills Actually, I think this one is ready to merge. 
What will happen is: nothing. Sort'a. We've just moved the content from `mdn/content` to `mdn/archived-content`. 
Those pages will get [a yellow banner](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Documentation) saying they're archived. 

It's not until we shut down all archived-content use (June 30) that the redirects matter. And for the Mozilla/Projects/NSS that stuff lies with a [separate PR just for the redirects](https://github.com/mdn/yari/pull/3725).

So if you can sanity check my above logic, I think we can safely merge this.

**Comment by hamishwillee** [comment]
Did we consider deleting all this an pointing to the new docs once they exist?

**Comment by sideshowbarker** [comment]
@peterbe Not sure who this PR is waiting on action from…

**Comment by peterbe** [comment]
> @peterbe Not sure who this PR is waiting on action from…

We'll merge this on June 30 2021.

**Comment by sideshowbarker** [comment]
> We'll merge this on June 30 2021.

@peterbe I notice this has merge conflicts now — which I guess all can be overridden since the files are all being deleted anyway.

But there’s also a conflict in the `files/en-us/mozilla/projects/nss` file

**Comment by Ryuno-Ki** [comment]
@Rumyra Perhaps worth to think about how to track PRs like this that should be merged on a specific date.
(Be it as a personal todo list, a label, a GitHub project or similar)

**Comment by peterbe** [comment]
Too old now.

**Comment by hamishwillee** [comment]
@peterbe The master plan was to delete this whole tree, which is what this PR did. Whether or not it happens in the PR it still needs to happen. Have you created a replacement PR? 

Are you OK if I do? We should let the NSS team know and merge before end of next week.

**Comment by peterbe** [comment]
> Are you OK if I do? We should let the NSS team know and merge before end of next week.

Please do.

**Comment by hamishwillee** [comment]
Done https://github.com/mdn/content/pull/8215

Obviously the redirects issue is not sorted. I am at the point where I'd rather remove this and have broken redirects that have it present.

**Pull request closed without merging**
