### PR TITLE
justify-content:left/right in flexbox doesn't work with vertical writing modes

### PR DESCRIPTION
**Pull request by yisibl**

### CODE REVIEW

**Comment by rachelandrew** [comment]
Hi, @yisibl I don't think this is correct.

Chrome has just implemented all of those values. The Firefox issue was to fix a bug in column flex containers.

**Comment by Rumyra** [comment]
Yes agreed @rachelandrew this seems like a fix, I'm assuming FF already supported these keywords (without checking 😬)

**Comment by rachelandrew** [comment]
Yep, Firefox has had support for a long time.

**Comment by yisibl** [comment]
Thanks for the review, I updated it.

**Comment by Rumyra** [comment]
Thanks so much for the update @yisibl - however we don't tend to list small update modifications such as these. I'll close this PR, but thanks for the effort, it's appreciated.

**Comment by yisibl** [comment]
Once this release page can record every change in detail. Not only can I not record these details, but I can only modify them through a GitHub PR. I am very disappointed.

**Pull request closed without merging**
