### PR TITLE
Fix scheme in CORS example code

### PR DESCRIPTION
**Pull request by uberswe**
> Issue number to be fixed

N/A, I did not see any issue related to this

> What was wrong/why is this fix needed? (quick summary only)

The example uses `https://` instead of `http://` without mentioning that this is wrong. The same example is later referenced with `http://` on https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/index.html#L216. 

> Anything else that could help us review it

I found this confusing as I was trying to understand if CORS cares about the scheme and the example implies that it does not without specifically stating that it does or not.

### CODE REVIEW

**Comment by sideshowbarker** [comment]
> The example uses `https://` instead of `http://` without mentioning that this is wrong. The same example is later referenced with `http://` on [https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/index.html#L216](https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/index.html?rgh-link-date=2021-07-30T08%3A27%3A24Z#L216).

Given that, I think the better fix here would be to replace that reference with `https://foo.example` — and to also replace the other remaining cases of `http://foo.example` with `https://foo.example`.

**Comment by uberswe** [comment]
> > The example uses `https://` instead of `http://` without mentioning that this is wrong. The same example is later referenced with `http://` on [https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/index.html#L216](https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/index.html?rgh-link-date=2021-07-30T08%3A27%3A24Z#L216).
> 
> Given that, I think the better fix here would be to replace that reference with `https://foo.example` — and to also replace the other remaining cases of `http://foo.example` with `https://foo.example`.

Should I make a new commit on this existing PR or make a new branch and PR with these changes?

**Comment by sideshowbarker** [comment]
> Should I make a new commit on this existing PR

Please go ahead and add the new commit on this existing PR branch. It’s also find to `git commit --amend` the existing commit — to overwrite it — and then force-push to this branch.

**Comment by uberswe** [comment]
@sideshowbarker I have changed every example to use https, if this is unwanted please let me know.

One thing I want to note is that I did not update the images which I would need help with to change as they also use `http://`.

96e7e79f244643e123f94588f7d8f9e2

**Comment by teoli2003** [comment]
Unfortunately I lost the source file of these diagrams, but can you open a follow-up issue? I'm planning to rework the http area starting next Monday, and redoing and improving all these diagrams are in my plans. (But I need to have problems recorded so I don't forget). It would be useful.

**Comment by uberswe** [comment]
> Unfortunately I lost the source file of these diagrams, but can you open a follow-up issue? I'm planning to rework the http area starting next Monday, and redoing and improving all these diagrams are in my plans. (But I need to have problems recorded so I don't forget). It would be useful.

I have opened #7455 regarding this.

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Markus, thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

**Pull request merged**
