### PR TITLE
Add sidebars to XPATH axes pages

### PR DESCRIPTION
**Pull request by OnkarRuikar**

### CODE REVIEW

**Review by bsmth — APPROVED** [review]
Thanks @OnkarRuikar. LGTM, would like to ping @wbamberg before merging who is working on sidebars at the moment 👀

**Comment by OnkarRuikar** [comment]
Not exactly related to this PR, there is anomaly in `https://github.com/mdn/content/tree/main/files/en-us/web/xslt/transforming_xml_with_xslt/the_netscape_xslt_xpath_reference/axes` hierarchy.
- It has the exact same duplicate axes pages as this `/web/xpath/axes/*` hierarchy does.
- These pages are not deleted but redirect for these pages exist:
  ```log
  /en-US/docs/Web/XSLT/Transforming_XML_with_XSLT/Mozilla_XSLT_XPath_Reference/Axes	/en-US/docs/Web/XPath/Axes
  /en-US/docs/Web/XSLT/Transforming_XML_with_XSLT/Mozilla_XSLT_XPath_Reference/Axes/ancestor	/en-US/docs/Web/XPath/Axes/ancestor
  /en-US/docs/Web/XSLT/Transforming_XML_with_XSLT/Mozilla_XSLT_XPath_Reference/Axes/ancestor-or-self	/en-US/docs/Web/XPath/Axes/ancestor-or-self
  ...
  ```

Should we delete the duplicate pages or the redirects? Due to the redirects, sidebar macros are not able to create proper sidebars for these duplicate pages.

**Comment by OnkarRuikar** [comment]
Ping @wbamberg

**Comment by wbamberg** [comment]
Why not use the sidebar from https://github.com/mdn/content/blob/08c729a06194abbe1fb15dce0b9f6357f36dcaf4/files/en-us/web/xpath/index.md?plain=1#L15-L29 ? It gives much better context.

Honestly though it's hard to know what to say about these docs. If we really cared about them we would give them a proper sidebar with their own macro, probably based on https://github.com/mdn/content/blob/main/files/en-us/web/xpath/index.md?plain=1#L15-L29.

**Comment by OnkarRuikar** [comment]
For now I've added `Quick_links` section. Will work on macro later.

**Comment by wbamberg** [comment]
OK @OnkarRuikar , I'm really sorry to put you to extra work, again, but now I actually look at these pages I'm thinking: why on earth are they separate pages at all? They are tiny, and in most cases don't add anything above the corresponding `<dd>` in https://pr22899.content.dev.mdn.mozit.cloud/en-US/docs/Web/XPath/Axes. So now I am thinking, why not just delete them and redirect to https://pr22899.content.dev.mdn.mozit.cloud/en-US/docs/Web/XPath/Axes ?

**Comment by OnkarRuikar** [comment]
> OK @OnkarRuikar , I'm really sorry to put you to extra work, again,

No worries. What about the pages under `the_netscape_xslt_xpath_reference/axes`? They are duplicates of these and  something [weird is going on with their redirects](https://github.com/mdn/content/pull/22899#issuecomment-1347695610).

**Comment by wbamberg** [comment]
> > OK @OnkarRuikar , I'm really sorry to put you to extra work, again,
> 
> No worries. What about the pages under `the_netscape_xslt_xpath_reference/axes`? They are duplicates of these and something [weird is going on with their redirects](https://github.com/mdn/content/pull/22899#issuecomment-1347695610).

So these pages still exist but are redirected to the corresponding page under https://developer.mozilla.org/en-US/docs/Web/XPath/Axes ? I think we should delete them, too - I can't think of any reason we would want to keep them, as they are inaccessible to users anyway, right?

**Review by wbamberg — APPROVED** [review]
👍 thank you @OnkarRuikar !

**Pull request merged**
