### PR TITLE
change the returned value of Object(null) or Object(undefined) to mat…

### PR DESCRIPTION
**Pull request by Ahmed-Hakeem**
…ch specs

According to specification : 
' If NewTarget is neither undefined nor the active function, then
a. Return ? OrdinaryCreateFromConstructor(NewTarget, "%Object.prototype%"). '
check the below link :
https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-object-objects

that means it returns a new object of the same value and adds to it Object.prototype  = `new Object(value, Object.prototype)`

for ex :
Object(null) // returns {}

//an object without prototypal inheritance or without [[prototype]] property that points to Object.prototype 

new Object(Object(null))     // returns  {[[prototype]]:Object.prototype}

//so it will not return the exact value as hinted but a new one from the value with prototypal inheritance

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
`OrdinaryCreateFromConstructor` is not exposed by ECMAScript APIs (`new Object` only takes one parameter). You need to describe this with prose. I'll leave that to you since you already spent time digging into the spec :)

Your current text says "What does `new Object(o)` do? Well it calls `new Object(o, Object.prototype)`." That's infinite recursion.

**Comment by Josh-Cena** [comment]
Also, I think you are misunderstanding this statement:

> If NewTarget is neither undefined nor the active function

"Active function" means `Object`. This is specifically talking about the case of instantiating `class Something extends Object`—which is required to treat `extends Object` as "transparent". For `new Object()`, the current text is correct.

**Comment by Ahmed-Hakeem** [comment]
sorry for that, It should be `Object.create(value, Object.prototype)`
will change it right away.

**Comment by Josh-Cena** [comment]
Sorry, I think you are misunderstanding the spec language.

```js
const d = new Date();
console.log(Object(d) === d); // true
```

For objects, it always returns the exact same object.

**Comment by Josh-Cena** [comment]
Also, I'm not sure what you mean by this either:

> Object(null) // returns {}
>
> //an object without prototypal inheritance or without [[prototype]] property that points to Object.prototype

Because:

```js
console.log(Object.getPrototypeOf(Object(null)) === Object.prototype); // true
```

Could you demonstrate how the current description deviates from actual JS behavior, and how you revised content aligns with it? Let's use actual experiments.

**Comment by Ahmed-Hakeem** [comment]
> Sorry, I think you are misunderstanding the spec language.
> 
> ```js
> const d = new Date();
> console.log(new Object(d) === d); // true
> ```
> 
> For objects, it always returns the exact same object.

the case I'm talking about is Objects that deliberately created (e.g. by [Object.create(null)])
I mean don't inherit from Object Object. 

In this case: 

const ObjectWithNoInheritance = Object.create(null) 

console.log(ObjectWithNoInheritance ) // returns {}   an empty deliberate object from inheritance 

const ObjectWithInheritance = new Object(x) 
console.log(ObjectWithInheritance ) // returns {[[prototype]]:Object}   an object inherits from Object Object.

console.log(ObjectWithInheritance === ObjectWithNoInheritance) // returns false

**Comment by Josh-Cena** [comment]
`Object.getPrototypeOf(new Object(Object.create(null))) === null` is true.

**Comment by Josh-Cena** [comment]
image

Which runtime are you using? If you actually tested it, that definitely doesn't seem compliant.

**Comment by Ahmed-Hakeem** [comment]
> > Sorry, I think you are misunderstanding the spec language.
> > ```js
> > const d = new Date();
> > console.log(new Object(d) === d); // true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For objects, it always returns the exact same object.
> 
> the case I'm talking about is Objects that deliberately created (e.g. by [Object.create(null)]) I mean don't inherit from Object Object.
> 
> In this case:
> 
> const ObjectWithNoInheritance = Object.create(null)
> 
> console.log(ObjectWithNoInheritance ) // returns {} an empty deliberate object from inheritance
> 
> const ObjectWithInheritance = new Object(ObjectWithNoInheritance ) console.log(ObjectWithInheritance ) // returns {[[prototype]]:Object} an object inherits from Object Object.
> 
> console.log(ObjectWithInheritance === ObjectWithNoInheritance) // returns false



> image
> 
> Which runtime are you using? If you actually tested it, that definitely doesn't seem compliant.

My bad, I tested it multiple times in Microsoft edge Version 103.0.1264.77 console, and It did work as I mentioned.
now tested in multiple browsers and it did work as you mentioned, sorry for the disturbance, 
and It should be noted that I didn't get the specs correctly. 

thank you for your time, and I hope I can help Mozilla in the future.

**Comment by Josh-Cena** [comment]
In Egde `new Object(Object.create(null))` is not idempotent?? That can't happen AFAICT since they are using Chromium/V8 already. Do you have screenshots? May be worth a bug report.

**Comment by Ahmed-Hakeem** [comment]
> In Egde `new Object(Object.create(null))` is not idempotent?? That can't happen AFAICT since they are using Chromium/V8 already. Do you have screenshots? May be worth a bug report.

Unfortunately no, and It now works the same as other browsers after the update. 
Anyway, thank you so much for your time, I hoped that this pull request would be more useful for Mozilla documentation, but unfortunately, wasn't accurate, thank you again, and I hope you have a nice day.

**Pull request closed without merging**
