### PR TITLE
fix: replace plain text formulas with MathML markups

### PR DESCRIPTION
**Pull request by yin1999**
### Description

replace plain text formulas with MathML markups

### Motivation

We have used MathML to represent formulas in some other documents, which makes it easier for readers to read.

[The LaTeX is provided here](<https://temml.org/#COLOR_%7BX,Y%7D%20=%20%5Cfrac%7B%5Csum_%7BI=0%7D%5E%7BorderX-1%7D%5Csum_%7BJ=0%7D%5E%7BorderX-1%7D%7B%5Cleft(%20SOURCE_%7BX-targetX+J,Y-targetY+I%7D%20*kernelMatrix_%7BorderX-J-1,orderY-I-1%7D%20%5Cright)%7D%7D%7Bdivsor+bias*ALPHA_%7BX,Y%7D%7D>)

### CODE REVIEW

**Comment by wbamberg** [comment]
Would it be better to include the LaTex in the code using `<annotation>`, as some of the other instances seem to? e.g. https://github.com/mdn/content/blob/d2594e013e684003562b47b29cd4277c84dc8e51/files/en-us/web/javascript/reference/global_objects/math/sqrt2/index.md?plain=1#L16

?

**Review by bsmth — APPROVED** [review]
That looks way better, thank you! 👍🏻 

__edit:__ Will commented in the meantime while I had the preview open, sorry for the timing of hitting `submit` :)

**Comment by wbamberg** [comment]
Thanks! I agree we should do this, it looks much better, it was just a bit shocking to see that big slab of markup in there, so anything we could do to make it more manageable for authors is great.

**Comment by yin1999** [comment]
Thanks for the suggestion. Although I had to add transfer to avoid incorrect parsing of markdown parser and/or prettier, the rendered web content looks much better :)

image

**Pull request merged**
