### PR TITLE
Add interactive example to rotate function

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
#### Summary

Simply adding [Interactive Example](https://interactive-examples.mdn.mozilla.net/pages/css/function-rotate.html) to [rotate ](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate) function.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by wbamberg — APPROVED** [review]
👍 thank you @NiedziolkaMichal !

**Comment by NiedziolkaMichal** [comment]
@wbamberg Hey, I have noticed few more interactive examples of transform property, that are ready, but not added to content. They have illustrations in place of interactive examples, so I am not sure if they should be added or not. Could you check and let me know please?
Those functions are: [scale](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale), [scaleX](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scaleX), [scaleY](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scaleY), [translate](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate), [translateX](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translateX), [translateY](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translateY).

**Comment by wbamberg** [comment]
I can't see any reason not to add these. Maybe we just forgot?

**Comment by NiedziolkaMichal** [comment]
Probably. Should I remove illustrations or let them be below added examples?

**Comment by wbamberg** [comment]
I think I would vote to remove them. What do you think?

**Comment by NiedziolkaMichal** [comment]
I think so too. I will make PR tomorrow.

**Pull request merged**
