### PR TITLE
Add Spanish translation L10n-CSS.json

### PR DESCRIPTION
**Pull request by JuanVqz**
### Description

Add Spanish keys

### Motivation

Help with Spanish translations

### Related issues and pull requests
Reference to https://github.com/mdn/translated-content/issues/8749

### CODE REVIEW

**Comment by bsmth** [comment]
Can you put `"es"` in alphabetical order for this one? e.g.:

```
    "en-US": "Data types",
    "es": "Tipos de datos"
    "fr": "Types de donnée",
    "ja": "データ型",
    "pt-BR": "Tipos de dados",
    "ru": "Типы данных",
    "zh-CN": "数据类型",
```

**Comment by JuanVqz** [comment]
> Can you put `"es"` in alphabetical order for this one? e.g.:
> 
> ```
>     "en-US": "Data types",
>     "es": "Tipos de datos"
>     "fr": "Types de donnée",
>     "ja": "データ型",
>     "pt-BR": "Tipos de dados",
>     "ru": "Типы данных",
>     "zh-CN": "数据类型",
> ```

since the linter didn't have an opinion related to the order I left it as it is

**Comment by bsmth** [comment]
Hi @JuanVqz I've reordered the JSON keys in https://github.com/mdn/content/pull/21404/commits/db073e042ceea8ceb04366ea96b6b704841f4533

The rest of the keys are in alphabetical order, so I think we should keep the pattern

**Review by bsmth — APPROVED** [review]
Thanks :)

**Comment by JuanVqz** [comment]
Thank you!

**Pull request merged**
