### PR TITLE
fix: DETAILS example missing SUMMARY 

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Review by Elchi3 — CHANGES_REQUESTED** [review]
I think in line 340 there is a missing closing details tag. 
At least the text talks about how meta this is and so details should be there :)

**Comment by nschonni** [comment]
@Elchi3 this is leftover cleanup from #868, because all the `<details>` on this page were invalid with no `<summary>` children

**Comment by chrisdavidmills** [comment]
FYI, I've just fixed the missing `<details>` in another PR that I'm about to push and merge. So you can close this.

**Comment by chrisdavidmills** [comment]
OK, no worries then. I'll handle it when I get to it.

**Comment by chrisdavidmills** [comment]
By that I mean, go ahead with your PR ;-)

**Comment by nschonni** [comment]
@Elchi3 I've updated the example to include the SUMMARY tags

**Review by Elchi3 — APPROVED** [review]
Very nice! Thank you!

**Pull request merged**
