### PR TITLE
Remove outdated Sanitizer API content

### PR DESCRIPTION
**Pull request by lukewarlow**
### Description

Removes content for unshipped and out of date Sanitizer API spec.

### Motivation

In their current form these documents are more confusing than helpful, and the API shape has changed a large amount since written. As a result they'd need to be almost fully rewritten anyway.

### Related issues and pull requests

Relates to https://github.com/mdn/content/issues/32731

### CODE REVIEW

**Comment by lukewarlow** [comment]
Flaws are unrelated to this change but happy to fix them.

**Review by skyclouds2001 — COMMENTED** [review]
maybe you should run a shell to delete documentation
see https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Creating_moving_deleting

**Comment by skyclouds2001** [comment]
the api entry in files/jsondata/GroupData.json also seems to need to remove

image

**Comment by hamishwillee** [comment]
> In their current form these documents are more confusing than helpful, and the API shape has changed a large amount since written. As a result they'd need to be almost fully rewritten anyway.

While this is true, it is contrary to MDN policy. MDN follows BCD. BCD policy is that if something has been in the web platform, it gets removed after 2 years. Given that Chrome removed this in 119 we're a long way from that.

I don't think we should change our policy for any one case. But since you're right, we should start by making this all as deprecated in BCD.

**Comment by hamishwillee** [comment]
P.S. Though if there is a replacement API appearing in browsers, then it might be OK to remove much of this.

**Comment by lukewarlow** [comment]
Okay I'll close this for now then

**Comment by hamishwillee** [comment]
> Okay I'll close this for now then

Thanks @lukewarlow. I've added deprecated to the BCD which should help a bit. Maybe we'll get lucky and be allowed to delete the content some point soon.

**Pull request closed without merging**
