### PR TITLE
fix: typo timout -> timeout

### PR DESCRIPTION
**Pull request by nschonni**
Assuming the BCD isn't miss-spelling. Something that Yari should probably check/catch

### CODE REVIEW

**Comment by nschonni** [comment]
Looks like it is "timeout" https://github.com/mdn/browser-compat-data/blob/470e6d9dfb2e4d18e27c66acd919ff61dd7c4d07/api/AbortSignal.json but the build previous isn't pulling the date right?

**Comment by wbamberg** [comment]
> the build previous isn't pulling the date right?

I'm not sure what that means, but I think your PR is good!

**Review by wbamberg — APPROVED** [review]
👍

**Comment by nschonni** [comment]
Sorry, it's there, I just had a custom CSS running and visually skipped the date. It does look OK on the preview
image

**Comment by hamishwillee** [comment]
Thanks guys. I'm the responsible idiot. I assumed BCD was just slow to update rather than I had made a typo.

**Comment by nschonni** [comment]
No worries, just checked on the original PR and saw
```
bad_bcd_queries:

    No BCD data for query: api.AbortSignal.timout
```
So good that Yari is catching that stuff, but maybe it needs to be raised up to an error level to give it a bit of a "hard CI failure". May also be worth linking to the target BCD file, since then you'd be able to see if the file is missing vs a misspelled property. (Sorry for feature requesting on a PR comment, I'm just passing an idea you could take or leave)

**Comment by hamishwillee** [comment]
Thanks. I wouldn't make it a hard CI failure, because it's better not to block content going in while we wait on BCD data to sync. 

>May also be worth linking to the target BCD file

I don't know what you are suggesting here.

**Comment by nschonni** [comment]
EX: 
```
bad_bcd_queries:
    No BCD data for query: [api.AbortSignal.timout](https://github.com/mdn/browser-compat-data/blob/main/api/AbortSignal.json)
```
As an example of linking to the top level BCD json file. You wouldn't be able link to the actual property without weird search fragment stuff, but at least with a quick link to the BDC file, you could see if the file exists and if the property is there. Maybe this is too infrequent a problem to help though

**Comment by hamishwillee** [comment]
@nschonni I like that, as it make checking a bit easier. Fact is though, I made an assumption in this case and perhaps would simply not have bothered to check. So yes, but I don't think would be a priority. 

What would be nice would be if this link was the the actual file:
image

**Pull request merged**
