### PR TITLE
Fix 400 Bad Request spec URLs

### PR DESCRIPTION
**Pull request by LucaBlackDragon**
### Description

Update URLs of cited RFCs

### Motivation

The previous link showed a warning and redirected to the new link

### Additional details

I suppose similar changes should be made somewhere else

### CODE REVIEW

**Comment by teoli2003** [comment]
We have systematically used `httpwg.org` links for the HTTP specifications (and removed all older HTTP spec links), while we are using `rfc-editor.org` ones for other RFCs.

@mnot As an author of these specs, which URLs do you think are best for the HTTP specs: `httpwg.org` or the `rfc-editor.org` ones?

**Comment by teoli2003** [comment]
(Note that I don't see a warning with the link, as the original author suggests; but I have not digged much here)

**Comment by LucaBlackDragon** [comment]
> (Note that I don't see a warning with the link, as the original author suggests; but I have not digged much here)

You should see the warning if you click on the link under "See also", as shown here:

image

This is the warning itself:

image

So, to clarify:
- I have changed the link on line 31 because of the warning
- I have also changed the other link on line 10 for uniformity
- of course the http working group is good enough and I should have used that link, it was careless of me, I'll change the PR at once

**Comment by teoli2003** [comment]
Yes, links to the old RFC have to go. I am hesitating between a link httpwg.org or rfc-editor.org. For HTTPbis specs, we have linked to httpwg.org, so let's keep it for the moment. We could always do a find-and-replace later if rfc-editor.org turns out to be more pertinent.

Let's merge this.

**Review by teoli2003 — APPROVED** [review]

**Pull request merged**
