### PR TITLE
Experiment with a new PR template format

### PR DESCRIPTION
**Pull request by ddbeck**
#### Summary

This PR:

- formats the PR template with meaningful headings and help text hidden in comments
- adds a new metadata section, to solicit scope information from contributors

#### Motivation

I want to learn if PR authors will provide categorical information about their changes, to facilitate content metadata and process automation.

#### Supporting details

This was heavily inspired by [BCD's PR template](https://raw.githubusercontent.com/mdn/browser-compat-data/main/.github/PULL_REQUEST_TEMPLATE.md), which has well-served BCD for several months.

I've used the template in this PR to illustrate it in use!

#### Related issues

Historic discussions on the existing template structure:
 - https://github.com/mdn/content/issues/7404
 - https://github.com/mdn/content/pull/3402

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by Rumyra** [comment]
This all looks good to me - if you need an approver @ddbeck just assign me 👍

**Comment by teoli2003** [comment]
I agree, I think this is better. Let's see if it solves the problem (people not removing comments) and improve them further later if needed.

**Review by teoli2003 — APPROVED** [review]

**Comment by ddbeck** [comment]
Thanks for the feedback, folks. I'm going to merge this now.

@hamishwillee if you've got ideas on how to make the headings less stuffy, I'd welcome a PR. 👍

**Comment by hamishwillee** [comment]
>  I'd welcome a PR.

I'm a complaints guy, not a solutions guy :-)

**Pull request merged**
