### PR TITLE
Fix code in example

### PR DESCRIPTION
**Pull request by crs1138**
The double brackets around media queries within the `sizes` attribute do not work. Tested in Brave (Version 1.39.122 Chromium: 102.0.5005.115) and Firefox (103.0b1).

#### Summary

There seems to be error in syntax of the media queries in the example.
#### Motivation

I believe this is wrong and I'd like to save other people losing her over this. It was after a while when I just randomly tried to remove the encapsulating bracket that my code started working.
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a bug

### CODE REVIEW

**Comment by crs1138** [comment]
Btw. It is "_losing hair_" not "_losing her_" - even though I'm pretty bold this wasn't so dramatic and I'm still happily married. 😃

**Comment by teoli2003** [comment]
@wbamberg I think you fixed the images on this page yesterday, can you check this additional change?

**Comment by wbamberg** [comment]
@crs1138 , your PR seems to work fine, but as far as I can see the current page works fine as well (https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/HTMLImageElement/sizes/_sample_.Selecting_an_image_to_fit_window_width.html). I'm not against merging your PR but I'd like to understand better the motivation for your PR. Am I right that the current example is working, or am I missing something here?

**Comment by teoli2003** [comment]
It may be that there were broken images and this PR was trying to fix it (while it was a problem with the image links, which you fixed in the other PR between the submission and the review of this PR).

**Comment by crs1138** [comment]
I don't know. Perhaps, I'm missing something but for me the double brackets don't work. Here's a codepen example – https://codepen.io/crs1138/full/dymyQyw and a link to a video that demonstrates how the image that has a media query in the `sizes` attribute wrapped in an extra pair of brackets is not loading the 640px wide image.
https://watch.screencastify.com/v/lqX8GvLHMhp5vt9Jr1hr

**Comment by wbamberg** [comment]
Sorry to be slow responding. I'm closing this because the existing example appears to work fine, and the code validates at https://validator.w3.org/.

**Pull request closed without merging**
