### PR TITLE
Remove title case

### PR DESCRIPTION
**Pull request by collin-klippel**
### Description

Remove title case of "Using Promises"

### Motivation

Titles do not use title case

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Hi, we don't use title case in titles. If you find this confusing, maybe change the "Using Promises" article title to sentence case instead?

**Comment by collin-klippel** [comment]
> "Using Promises" is the title of an article and so both words should be capitalized.

Hmm okay...it seems like we could run a code mode to make sure everything is consistent across the site?

**Comment by Josh-Cena** [comment]
There's only one other instance in the JS section (namely "JavaScript Guide") so it should not be a big issue. Feel free to fix that as well.

**Comment by collin-klippel** [comment]
> There's only one other instance in the JS section (namely "JavaScript Guide") so it should not be a big issue. Feel free to fix that as well. Fixing things in prose is going to be trickier, but you can also do that bit-by-bit.

Sounds good!, thanks again! I updated to just make this small change for now 😄

**Review by hamishwillee — APPROVED** [review]
Thanks!

**Comment by hamishwillee** [comment]
> we could run a code mod to make sure everything is consistent across the site?

Possibly. It isn't quite that simple, because proper names can still be capitalized

**Pull request merged**
