### PR TITLE
Fix links to `Web/API/console` methods

### PR DESCRIPTION
**Pull request by leon-win**
### Description

This PR updates links to `console` API methods like:
```
domxref("console.log()" -> domxref("console.log_static")
```

### Motivation

Reduce flaws in documents

### CODE REVIEW

**Comment by bsmth** [comment]
Hi @leon-win thanks for opening this one. There is work already underway on this:

- [ ] https://github.com/mdn/content/pull/30528
- [ ] https://github.com/mdn/content/pull/30506

Sorry about the duplication of work, we may have to close this in favor of the linked PRs.

**Comment by bsmth** [comment]
No problem, then let's leave this open and take a look when the related PRs are merged, we can check the diff with `main` afterwards 👍

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
These changes are incorrect btw, they show up as `console.log_static`. You want to add a second parameter to make the displayed text stay the same. https://github.com/mdn/content/pull/30528 has correct examples.

**Comment by teoli2003** [comment]
After merging the two previous PRs, this PR is empty. So I'm going to close it.

Thank you for the work, @leon-win. Don't hesitate to do more of these in the future; it is unfortunate that we both work on this in parallel.

**Comment by leon-win** [comment]
Everything is fine! I'll be more attentive in the future =)

**Pull request closed without merging**
