### PR TITLE
Api: /xs /xrv - remove tags and replace with status

### PR DESCRIPTION
**Pull request by hamishwillee**
This is first test of script run removal of tags, replacing experimental and other status if present as "status" frontmatter.

### CODE REVIEW

**Review by wbamberg — APPROVED** [review]
👍 looks great! Leaving it open in case anyone else wants a go.

**Review by teoli2003 — APPROVED** [review]

**Comment by teoli2003** [comment]
Same here. 👍  Two comments:

1. I'm cc/ing @OnkarRuikar, who controls and runs the script synchronizing statuses between bcd and mdn/content. This script will need an update: it updates `Tags:` and the in-text macros. It should update `Status:` and the in-text macros.
2. @hamishwillee How does your script handle already existing `status`. If it handles it well, this decouples the update of Onkar's script and the run of your script, which will make the transition easier.

I'm happy to see the removal of `Tags:` become a reality.

**Comment by teoli2003** [comment]
Ok, it looks like these PRs will rot quickly and the sooner we do it, the better.

That means that PRs from Onkar's script must not be merged until the tool is fixed.

Given that this concern only web/api for now, let's merge these.

**Comment by OnkarRuikar** [comment]
>  it updates `Tags:` and the in-text macros

The script handles head banners as well. To be specific it handles tags, head banner macros, and any definition list macros.

> It should update `Status:` and the in-text macros.

Thanks for the heads-up!
I'll update the BCD sync script. Couple of queries:
1. So looks like the `status:` is optional. I mean for standard, non-experimental and non-deprecated page the front matter attribute it won't be there, right?
2. Are we doing this for all the pages in one go? Or just for web/api for now? It'll be hard to do handle `tags` for some pages and `status` for some. If it's going to take some time like weeks then I'll turn off front matter updates for now.
3. Are values for `status` lowercase? Please decide and provide all possible values, because `tag` values were not uniform.
4. In yari, can we infer the header banners from the new `status` attribute and get rid of the header macros. Because clearly these two are now providing the same info.

***
We'll have to update these pages as well:
- https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Compatibility_tables#using_bcd_data_in_mdn_pages
- https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/Page_type_key
- https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_method_subpage_template
- other "page types" pages

**Comment by teoli2003** [comment]
>     1. So looks like the `status:` is optional. I mean for standard, non-experimental and non-deprecated page the front matter attribute it won't be there, right?
Yes, it is optional.

> 
>     2. Are we doing this for all the pages in one go? Or just for web/api for now? It'll be hard to do handle `tags` for some pages and `status` for some. If it's going to take some time like weeks then I'll turn off front matter updates for now.

No, we are not yet ready to do it everywhere. (For example, there is still a macro using tags in Add-ons, but the PR should be merged next week)

You could test if the `page-type: web-api-*` and apply only to these, for the moment.

It should be a matter of weeks, if not days, until we can remove `Tags:` everywhere.


>     3. Are values for `status` lowercase? Please decide and provide all possible values, because `tag` values were not uniform.

Yes, they are lowercase. The three values are listed [here](https://github.com/mdn/mdn/issues/262#issue-1472262040)

>     4. In yari, can we infer the header banners from the new `status` attribute and get rid of the header macros? Because, clearly, these two are now providing the same info.

This is the goal! It will be the next step.


> We'll have to update these pages as well:
Yep!


Thanks a lot for maintaining this synchronization script!

**Comment by hamishwillee** [comment]
My script assumes that if there is either status or no tags, it should do nothing. Thank you for merging. 

Worth just doing the lot of Web API ASAP - broken up a little of course? I'll do JavaScript then CSS after that.

**Comment by teoli2003** [comment]
Yep! To break them by 250 batches (or less) would be perfect.

**Comment by OnkarRuikar** [comment]
> 1. So looks like the `status:` is optional.
>> Yes, it is optional; they default to false.

This makes it a little bit complicated. Do we prefer the front matter properties in a particular order?
```yml
# a
title: Web Authentication API
slug: Web/API/Web_Authentication_API
page-type: web-api-overview
status:
  - deprecated
  - non-standard
spec-urls: 
  - https://drafts.csswg.org/first
  - https://drafts.csswg.org/second
browser-compat:
  - api.Credential
  - api.CredentialsContainer
  - api.PublicKeyCredential
  - api.AuthenticatorResponse
  - api.AuthenticatorAttestationResponse
  - api.AuthenticatorAssertionResponse
```
VS
```yml
# b
title: Web Authentication API
slug: Web/API/Web_Authentication_API
page-type: web-api-overview
spec-urls: 
  - https://drafts.csswg.org/first
  - https://drafts.csswg.org/second
browser-compat:
  - api.Credential
  - api.CredentialsContainer
  - api.PublicKeyCredential
  - api.AuthenticatorResponse
  - api.AuthenticatorAttestationResponse
  - api.AuthenticatorAssertionResponse
status:
  - deprecated
  - non-standard
```
Approach #b:
Without any front matter schema/order defined, it is hard to find insertion point. I think Hamish's script looks for the `page-type` attribute to insert the `status`, but CSS pages do not have `page-type` attribute. It will be easy for the script to append the missing `status` property at the end like in #b.

Approach #a:
To make it look like #a, we'll have to decide the order and schema. Then the script will have to parse the yaml and make sure the properties are written back in the mentioned order. In long run it'll be useful to lint and prettify the front matter in CI.

Let me know which option are we choosing?

**Comment by teoli2003** [comment]
Note: we removed (3 minutes ago) the last `tags:` under Web/API.

We will continue with the other repos this week.

Approach #c: do not run the script until the `tags:` removal is finished (max. 2 weeks, likely less). Then run it with `status:` and not `tags:

**Comment by teoli2003** [comment]
(And `status:` should be right after `page-type:`, that is mandatory.)

**Pull request merged**
