### PR TITLE
Replace the way of intentionally coercing primitives to objects

### PR DESCRIPTION
**Pull request by Ahmed-Hakeem**
This way is the exact same used in the js methods that use object coercion

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
We should mention both ways, in a structure similar to /en-US/docs/Web/JavaScript/Reference/Global_Objects/String#string_coercion

**Comment by Ahmed-Hakeem** [comment]
actually we should change the string one as well .... it needs some modification

**Comment by Ahmed-Hakeem** [comment]
> actually we should change the string one as well .... it needs some modification

Done .... What do you think? @Josh-Cena

**Review by Josh-Cena — APPROVED** [review]
I'm using the exact same structure as the `Number` and `String` pages. Thanks for catching this :)

**Comment by Ahmed-Hakeem** [comment]
> I'm using the exact same structure as the `Number` and `String` pages. Thanks for catching this :)

Thank you : ) ..... I have other modifications to the string one though 

will add it in another PR then

**Pull request merged**
