### PR TITLE
Add info about indexOf(NaN) behavior

### PR DESCRIPTION
**Pull request by IgorSuharev**
I have added information about behavior of indexOf() with NaN passed as argument.

### Description

I added a paragraph to Description. I also updated an example with sparse arrays, because the behavior of indexOf() with undefined and NaN have the same reason.

### Motivation

I have noticed that there are no mention about such nuance. Though it was indicated that indexOf() uses the strict equality algorithm, I have found the indication insufficient. I believe my amendment will make beginners pay attention to such aspect.

### Additional details

There are no additional detailes.

### Related issues and pull requests

There are no related issues nor pull requests.

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Thanks, but `NaN` has nothing to do with sparse arrays. Could you add a new example instead? (This behavior comes from its use of the `===` algorithm, so I'll also prefer you to add that sentence at the end of the first paragraph.)

**Review by Josh-Cena — COMMENTED** [review]
Thanks, but `NaN` has nothing to do with sparse arrays. Could you add a new example instead? (This behavior comes from its use of the `===` algorithm, so I'll also prefer you to add that sentence at the end of the first paragraph.) You should make sure the `lastIndexOf` page is updated as well.

**Comment by IgorSuharev** [comment]
I am sorry, but now i have little time; also I doesn't know how to to edit my pull request or create a new one.

**Review by Josh-Cena — APPROVED** [review]
I applied the changes myself since it's not worth blocking this PR. Thank you for the improvement, and congratulations on both your first contribution here and the first PR on GitHub—welcome aboard!

**Pull request merged**
