### PR TITLE
get rid of mdn.mozillademos.org files (part 5)

### PR DESCRIPTION
**Pull request by peterbe**
> What was wrong/why is this fix needed? (quick summary only)

Lots of samples use the deprecated `https://mdn.mozillademos.org/files/...` URLs. 

> MDN URL of the main page changed

See preview URLs in review companion

> Issue number (if there is an associated issue)

n/a

> Anything else that could help us review it

See existing ongoing work: https://github.com/mdn/content/pulls?q=is%3Apr+is%3Aclosed+mdn.mozillademos.org

### CODE REVIEW

**Comment by peterbe** [comment]
How I tested it was that I opened each URL with the Network panel in devtools open to observe all requests. No 404s in sight!

**Comment by peterbe** [comment]
@wbamberg Here's another example of these. I'm trying to break down the flood of PRs to be per-tree and even then trying to limit it to not be too many files at a time.

**Review by wbamberg — CHANGES_REQUESTED** [review]
It looks like one of these is missing, but the others all look great.

**Review by wbamberg — APPROVED** [review]
Thanks @peterbe !

**Pull request merged**
