### PR TITLE
Clean _redirects.txt file: update external broken links

### PR DESCRIPTION
**Pull request by OnkarRuikar**
The PR removes from-to pairs where:
- to link is external and it is broken (HTTP 404 etc.)
- from link isn't used anywhere in the content

***
I've written following simple shell script to find the broken links:
```bash
#!/usr/bin/env bash

# The script finds broken external URLs in the _redirects.txt

function check() {
    wget --spider -q -O /dev/null -o /dev/null "$1"
    if [[ $? -ne 0 ]]; then
  	    echo -ne '\r      \r'; echo $1
    else
        echo -ne '\r      \r'; echo -n $2
    fi
}

count=0
urls=( $( grep -oP 'https://.*$' files/en-us/_redirects.txt ) )
echo "Total ${#urls[@]} URLs to verify."

for url in ${urls[@]}; do
    ((count++))
    check $url $count
done

echo -e '\ndone!'

```

We can commit the script under https://github.com/mdn/content/tree/main/scripts and use it in daily lint cron automation.

### CODE REVIEW

**Comment by Rumyra** [comment]
Hey @OnkarRuikar - thanks for this...

> from link isn't used anywhere in the content

So these are here so external sites that link to those removed pages are re-directed to where the material was moved - can we alter the above function to change that?

**Comment by bsmth** [comment]
It looks like a lot of these have been moved: https://firefox-source-docs.mozilla.org/devtools-user/performance/ to https://profiler.firefox.com/docs/#/

**Comment by Rumyra** [comment]
Hey @OnkarRuikar - thanks for this but can we hold off on this change. It looks like the docs have been moved (again) and to reduce us receiving issues about the 404, we should redirect to the new location 👍

**Comment by OnkarRuikar** [comment]
@Rumyra 
> to reduce us receiving issues about the 404

These redirects are not being used anywhere in the content, so this change won't create any issue in any content page.

Regarding direct use of these redirects on Internet, these have been broken for a long time now. How long we keep redirecting the non content locations?

> we should redirect to the new location 👍

The new profiler is not going to have same features or documentation, e.g. https://github.com/firefox-devtools/profiler/issues/1104 . So we'll have to discard most of these anyway.🤔

**Comment by Rumyra** [comment]
Thanks both :) I think what I wanted to avoid was folks coming and asking where these docs were, as we had to deal with a huge amount of that last year (when moved to firefox docs) - if they haven't been working for some time and we haven't received any requests I guess it's ok 👍

**Comment by bsmth** [comment]
An alternative is to change the broken redirects to either the [placeholder page](https://firefox-source-docs.mozilla.org/devtools-user/performance/) or the new docs:

```bash
# All destinations https://firefox-source-docs.mozilla.org/devtools-user/performance/* 
# From                                  To
/en-US/docs/Tools/Performance/Call_Tree	https://profiler.firefox.com/docs/
```

Generic landing page for the new docs might be better than 404? What do you think?

**Comment by OnkarRuikar** [comment]
> Generic landing page for the new docs might be better than 404? What do you think?

@bsmth this is better!  This way we won't have to worry about finding exact replacements, and it will also save us from any restructuring on Firefox docs' side.

**Review by bsmth — APPROVED** [review]
I think this makes sense, thanks 👍🏻

**Pull request merged**
