### PR TITLE
Update maximum zoomFactor value

### LINKED ISSUE #6629: Issue with "tabs.setZoom()": maximum zoomFactor should be increased fro m3 to 5
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/setZoom

#### What information was incorrect, unhelpful, or incomplete?
zoomFactor states that acceptable values are between 0.3 and 3. The API actually accepts a zoomFactor up to 5 now.

#### Specific section or headline?
Description of the zoomFactor parameter.

#### What did you expect to see?
Description should say "a number between 0.3 and 5"

#### Did you test this? If so, how?
Tested it by calling the API with values 3, 4, 5, and 6.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/tabs/setzoom`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/setZoom
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/tabs/setzoom/index.html
* Last commit: https://github.com/mdn/content/commit/eb5d682cbe5664b933e793ff6434fb252686f3c3
* Document last modified: 2021-05-31T17:26:19.000Z

</details>

### PR DESCRIPTION
**Pull request by AnilSeervi**
> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

- Fixes #6629 

> What was wrong/why is this fix needed? (quick summary only)

> Anything else that could help us review it

### CODE REVIEW

**Comment by rebloor** [comment]
@AnilSeervi Thanks for this. Would you also consider updating the [example](https://github.com/mdn/webextensions-examples/tree/master/tabs-tabs-tabs) and [how to guide](https://github.com/mdn/content/blob/9ac9ff201b0e8de930af4f19cd5850eeba63ecc6/files/en-us/mozilla/add-ons/webextensions/working_with_the_tabs_api/index.html#L390) which mentioned 3 as the maximum zoom level?

**Comment by AnilSeervi** [comment]
> @AnilSeervi Thanks for this. Would you also consider updating the [example](https://github.com/mdn/webextensions-examples/tree/master/tabs-tabs-tabs) and [how to guide](https://github.com/mdn/content/blob/9ac9ff201b0e8de930af4f19cd5850eeba63ecc6/files/en-us/mozilla/add-ons/webextensions/working_with_the_tabs_api/index.html#L390) which mentioned 3 as the maximum zoom level?

Yea, Sure.

**Comment by sideshowbarker** [comment]
@rebloor, @rpl, this PR seems to be waiting on final review

**Review by rebloor — APPROVED** [review]
Thank @AnilSeervi these all look good.

**Pull request merged**
