### PR TITLE
Remove Mozilla/Firefox/Privacy

### PR DESCRIPTION
**Pull request by peterbe**
This removes Mozilla/Firefox/Privacy and it gets added to the archive in https://github.com/mdn/archived-content/pull/15

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
This one looks fine. Want me to merge it yet?

**Comment by peterbe** [comment]
> This one looks fine. Want me to merge it yet?

I have to figure out what the problem is with the redirects.

**Comment by chrisdavidmills** [comment]
> > This one looks fine. Want me to merge it yet?
> 
> I have to figure out what the problem is with the redirects.

OK, I'll hold off for now.

**Comment by peterbe** [comment]
I started over in https://github.com/mdn/content/pull/4534

**Pull request closed without merging**
