### PR TITLE
remove extra `"`

### PR DESCRIPTION
**Pull request by yin1999**
### Description

remove extra `"`

### CODE REVIEW

**Review by CBID2 — COMMENTED** [review]
Looks pretty good @yin1999! :)

**Review by hamishwillee — DISMISSED** [review]
Thanks for the fix. Running prettier on HTML is usually not a good idea - it does a horrible job. Was this something you chose to do or the toolchain forced you to do?

**Comment by yin1999** [comment]
> Thanks for the fix. Running prettier on HTML is usually not a good idea - it does a horrible job. Was this something you chose to do or the toolchain forced you to do?

We still run prettier format check in translated-content. After I fix the broken html (in mdn/translated-content#14568),  the format check just failed. So I run `yarn prettier -w /path/to/file` to those two PR.

**Comment by hamishwillee** [comment]
OK. Thanks. @queengooborg Thoughts on this? @yin1999 is "doing the right thing", but the resulting prettier changes to HTML are rubbish.

**Review by queengooborg — APPROVED** [review]
Prettier's formatting for HTML is not great, I think we all agree on this.  We don't have any control over it, though.  Plus, we already format all our HTML with Prettier.

**Comment by hamishwillee** [comment]
Really? I thought we formatted only the JS. I hate this. I would have suggested nolint.

**Comment by hamishwillee** [comment]
Hi @yin1999 

Just FYI, following some advice from @queengooborg I improved the HTML in https://github.com/mdn/content/pull/28230 . What I hadn't realized is that prettier does different things based on your starting point. So by putting some of the text on different lines it did a better job of formatting. 

Thanks for your fix!

**Comment by yin1999** [comment]
> Hi @yin1999 
> 
> Just FYI, following some advice from @queengooborg I improved the HTML in https://github.com/mdn/content/pull/28230 . What I hadn't realized is that prettier does different things based on your starting point. So by putting some of the text on different lines it did a better job of formatting. 
> 
> Thanks for your fix!

Thanks for the additional work on this @hamishwillee 👍

**Pull request merged**
