### PR TITLE
Removed obsolete page: sniffing animation support

### PR DESCRIPTION
**Pull request by estelle**
Sniffing support for CSS animation with JS is no longer needed and hasn't been needed for over 5 years.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
Yes, this can go. Yeah!

**Comment by teoli2003** [comment]
@estelle Did you use `yarn content delete` ([docs](https://github.com/mdn/content#deleting-a-document)) to delete the page? The redirect file looks broken

**Review by dipikabh — APPROVED** [review]

**Review by teoli2003 — CHANGES_REQUESTED** [review]
The redirect file must be fixed

**Comment by estelle** [comment]
For the life of me, I couldn't get yarn delete to work. So hand did the
delete, and didn't touch the redirect file. This is what I put in:

> yarn content delete
web/css/css_animations/detecting_css_animation_support/ --recursive


with and without the --recursive and preceded by a / and not followed by a
/. nothing worked

**Comment by estelle** [comment]
in the meantime, i manually edited the redirectss file.

**Comment by teoli2003** [comment]
> For the life of me, I couldn't get yarn delete to work. So hand did the delete, and didn't touch the redirect file. This is what I put in:
> yarn content delete
> web/css/css_animations/detecting_css_animation_support/ --recursive with and without the --recursive and preceded by a / and not followed by a /. nothing worked

I'll review it tomorrow.

Why the `yarn delete` is not working: I think you need to put the same capitalization as the slug: `Web/API/…` (recursive is not needed) and that's likely why it is failing. (When possible, I also use the `--redirect _slugname_` option so that's not a 404 after the deletion but a 30x Moved Permanently).

**Comment by estelle** [comment]
I copied the slug from the document itself, and also tried all lowercase, with slashes and without. Nothing worked. Maybe the  4 or 5 redirects in the redirect file may have been the issue.

Thanks!

**Comment by estelle** [comment]
I had the wrong version of node.
https://github.com/mdn/content/pull/17334 was done using yarn. I left it in draft mode as a comparison. My hand edit looks good.

**Review by teoli2003 — APPROVED** [review]
Let's merge this!

**Pull request merged**
