### PR TITLE
Express-validator: Updates for 7.0

### PR DESCRIPTION
**Pull request by TruePadawan**
### Description
I update part of the example code that was using deprecated methods from the `express-validator` package

### Motivation
I simply felt that its best to use the recommended methods and not the deprecated ones.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @TruePadawan . The problem here is that the tutorial is written for express-validator 6.15 and that module recently updated to v7 - making some things deprecated. 

Very happy with this update but we can't merge it without:
1. First updating https://github.com/mdn/express-locallibrary-tutorial
2. Checking there are no other uses of these deprecated items
3. Making sure nothing else in the release notes require an update: https://github.com/mdn/express-locallibrary-tutorial/pull/179#issue-1671617667

Would you like to make those checks? I can do it, but perhaps not for a few weeks.

**Comment by TruePadawan** [comment]
1. I should clone it to my PC, update the express-validator package and manually test the app?
2. Go through the code and update other places where this exact deprecated code is used?
3. I'm not sure what you mean here, Are you saying I should check if other deprecated code other than this one I specified, and update them?

If yes then sure I can do that.

**Comment by hamishwillee** [comment]
Hi @TruePadawan 

With respect to https://github.com/mdn/content/pull/26798#issuecomment-1554418765 then "yes".

After we have an updated version of https://github.com/mdn/express-locallibrary-tutorial that uses the code that is now recommended/not deprecated we would then update THIS PR with any other changes we find. Then merge both together. That way we know that the fixes work and are complete.

Thanks so much!

**Comment by TruePadawan** [comment]
> Hi @TruePadawan
> 
> With respect to [#26798 (comment)](https://github.com/mdn/content/pull/26798#issuecomment-1554418765) then "yes".
> 
> After we have an updated version of https://github.com/mdn/express-locallibrary-tutorial that uses the code that is now recommended/not deprecated we would then update THIS PR with any other changes we find. Then merge both together. That way we know that the fixes work and are complete.
> 
> Thanks so much!

I've done it and tested the app.
https://github.com/mdn/express-locallibrary-tutorial/pull/189

**Review by hamishwillee — APPROVED** [review]
That looks good to me. Thank you @TruePadawan for taking the time to fix this end to end.

You can see that it consumes a bit of time, which is one reason why I often batch up the updates. Really good to have this tidied in a timely manner.

**Pull request merged**
