### PR TITLE
Remove reference to NaN heading value

### PR DESCRIPTION
**Pull request by reillyeon**
### Description

Removes the reference to the `heading` field being set to `NaN` when `speed` is `0`. This matches the specification change in https://github.com/w3c/geolocation/pull/173.

### Motivation

As discussed in https://github.com/w3c/geolocation/pull/171, existing implementations do not provide the `NaN` value previously required by the specification and so the specification has been changed. Documentation such as MDN should also be updated to reflect this reality and avoid developer confusion around whether this is a potential value returned by the API.

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Did any browser ship with `NaN`? From a quick look at the issue, seems like no?

**Comment by reillyeon** [comment]
> Did any browser ship with `NaN`? From a quick look at the issue, seems like no?

We don't believe so.

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
Could you update https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/heading too?

**Comment by reillyeon** [comment]
> Could you update https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/heading too?

Done.

**Review by Josh-Cena — APPROVED** [review]
Thanks, LGTM 👍

**Pull request merged**
