### PR TITLE
Removing distracting/inaccurate commentary

### PR DESCRIPTION
**Pull request by getify**
The example (with try..catch) is more verbose, unnecessary, and distracting, so I removed it.

It's also misleading to claim that's "more "faithful to the spec, as it's not *more* faithful, but just a different way of accomplishing the same thing; it merely obviates machinery (basically, try..catch) that's already in the Promise constructor.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
You removed the "correct" implementation of `Promise.try()`. The first one is well-advertised but incorrect, because as said immediately after, this is only because the `Promise` constructor handles errors, but other constructors used as the `this` value may not. If we want to illustrate behavior via code we have to do it very precisely.

Technically this "precise" example is inaccurate too, because it doesn't actually use the `this` value. I propose we should change `new Promise` to `new this`, but keep this illustration, what do you think?

**Comment by getify** [comment]
> but other constructors used as the this value may not. 

Eh. Nobody does that kind of stuff. You could line up 10,000 JS developers and *maybe* find one who even knows it's possible or has ever done something like that.

Such an incredibly nuanced detail such as "you took something built into the web platform and re-bound it to userland code that's not spec compliant... and it behaved slightly differently" isn't helpful to distract readers of the MDN page with. That's good stuff for a blog post, but I don't think it's helpful on MDN.

> If we want to illustrate behavior via code we have to do it very precisely.

MDN probably shouldn't be in the business of displaying code -- even with disclaimers like "this isn't exactly a polyfill and shouldn't be used as such" -- that's sensitive to extremely nuanced spec details that the vast majority of readers will never use or care about. Leave the spec-wonk polyfill writing to folks who do it regularly and prolifically.

That's why I think the snippet should be removed entirely.

----

That said, the wording preceding the initial snippet of "exactly equivalent to" should probably be changed to "essentially".

**Comment by Josh-Cena** [comment]
What about we move it down to the "Calling try() on a non-Promise constructor" section?

**Comment by getify** [comment]
I would still think the section itself should be removed (as I just did in the last commit), because I still that stuff is more wonky and distracting, and actually not even a *good practice* MDN should be promoting. It's highly likely that approach could create some really hard-to-debug issues in various code bases.

But anyway, if that section really needs to stay, I think moving the part about the "more compliant" polyfill down to that section, as you suggest, *does make more sense*.

**Comment by Josh-Cena** [comment]
Please don't remove examples. That's the least we could say for power readers. The JS docs is for everyone, not just for average web developers. There always will be people interested in the exact semantics of the language and we need to do them a favor by not hiding things away. This is from my experience from interacting with various readers.

**Comment by getify** [comment]
This probably isn't the place to open a debate as to whether that sort of practice -- rebinding natives to userland contexts -- is a *good* or *bad* practice. I certainly think it's a bad one. I wish MDN wasn't sort of "promoting" it by including it on the page.

But as I said previously, if it has to stay, the polyfill related to that practice makes more sense there than where it currently sits, up top.

**Comment by Josh-Cena** [comment]
I think one common mindset is "well if they are interested in this they should read the spec". But our goal as writers is that if you are a user of JavaScript and not an implementor of a polyfill or an engine, you should never need to read the spec. Documentation should be a 1-to-1 representation of the spec, laid out in a way that's user-friendly, without losing any information.

**Comment by getify** [comment]
My take: not all things you *can* do with JS (according to the spec) are things you *should* do, or should be encouraged to do. But... shrugs.

**Comment by Josh-Cena** [comment]
So, we do "hide" things, such as input argument coercion (we just say "this function accepts a string" and you are on your own if you pass non-strings). But this is a big enough semantic that people actually may care about.

**Comment by getify** [comment]
Final thought: the `this`-rebinding "design" in the spec, as it relates to Promises -- and to subclassing, etc etc etc -- was primarily motivated by the fact that in ES6, JS was adding promises to a userland world that was vibrant with lots of similar/compatible promise implementations. That's what drove most of Promises/A+ design. TC39 really wanted as much interop with all those existing libs, to drive adoption of `Promise`, so they were quite concerned with meta-extensibility.

That was 9 years ago, in ES6. I don't think the landscape is nearly the same. I don't think there's very much userland overriding/extending of `Promise` going on. I think it's far less likely to be relevant today.

**Comment by Josh-Cena** [comment]
I don't think it's very relevant either for the vast majority, but we should assume every code that can be written will be written, so unless it's an actively bad practice that's either insecure, unstable, or extremely confusing (there are things that are "confusing" just because they are unfamiliar, not because they are inadequate), we should present it.

**Comment by getify** [comment]
OK, I'll close this PR and I'll re-submit one (later this evening) moving the polyfill down to that section. Thanks.

**Pull request closed without merging**
