### PR TITLE
Add example with Math.imul

### PR DESCRIPTION
**Pull request by mike-lischke**
#### Summary
Added another (and potentially more relevant) use case for integer multiplication.

#### Motivation
Found `Math.imul()` to be a life saver for hash computations, where I got many hash conflicts by using standard (floating point) multiplication.

#### Supporting details
https://github.com/mike-lischke/a4tstool/blob/master/lib/MurmurHash.ts

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Not meant to block this, but do you want to add a more real-world relevant example to the "Examples" section as well?

**Comment by mike-lischke** [comment]
Not sure what to add there. There's not so much to show beyond how to call the function, right :-)

**Comment by Josh-Cena** [comment]
Well, you can show an example of hash computation (_if_ it's less than 100 LOC), and how it solves conflicts?

**Comment by mike-lischke** [comment]
Please give me a few days for that.

**Comment by mike-lischke** [comment]
Unfortunately, I cannot reproduce the problems I had before using `Math.imul`. Too much has changed since then I guess. So feel free to close this pull request, if a new example is mandatory.

**Comment by Josh-Cena** [comment]
Yeah—sorry, if I could help you I would. At the current rate, I feel like this sentence is too handwavy. New examples aren't _mandatory_, but in this specific instance, we are better off illustrating our claim with an example because the claim is so technically specific. I will close this for now. If some day you managed to put together an example, feel free to send another PR!

**Pull request closed without merging**
