### PR TITLE
Update: remove fallback for datalist and textarea image

### PR DESCRIPTION
**Pull request by estelle**
1. Remove the `<textarea>` image. Moved the text that was under the image to under the live example

2. Removed the fallback for `<datalist>` as it is no longer needed.

### CODE REVIEW

**Review by pepelsbey — COMMENTED** [review]
Looks good! I suggest removing the `datalist-safari.png` image as well since it seems to be no longer needed.

**Comment by estelle** [comment]
> Looks good! I suggest removing the `datalist-safari.png` image as well since it seems to be no longer needed.

good catch. removed

**Comment by Mrh-bd** [comment]
https://en-gb.example.com/page.html

**Review by pepelsbey — APPROVED** [review]
Thanks!

**Pull request merged**
