### PR TITLE
chore(pwa): IntelliJ doesn't allow you to serve generated HTML anymore

### PR DESCRIPTION
**Pull request by bsmth**
I can't find any documentation about using a built-in server, only configuring access to an already running server, and it appears this functionality is removed, so I think we should remove this para.

We're covering how to start a local server in multiple places, this should be consolidated, but I'd like to at a minimum remove broken docs in the meantime.

### CODE REVIEW

**Comment by pepelsbey** [comment]
You can still select Run or Debug command in the file menu to open a local server:

image

image

**Comment by pepelsbey** [comment]
Though it’s not limited to IntelliJ Idea, I believe you can use any IDE (WebStorm, for example) to run it.

**Comment by bsmth** [comment]
Ah interesting, does this start a server implicitly for you, or do you have to have one running already? For some reason I cannot find documentation for this.

**Comment by bsmth** [comment]
Any objections to merging, @pepelsbey? 🚢

**Review by pepelsbey — APPROVED** [review]
:shipit:

**Comment by bsmth** [comment]
Thank you!

**Pull request merged**
