### PR TITLE
add the missing section tags in the main html code example

### PR DESCRIPTION
**Pull request by otakutyrant**
### Motivation

The page has mentioned section tags for several times, but the main html code example does not include them!

### CODE REVIEW

**Comment by estelle** [comment]
We would need to update https://github.com/mdn/learning-area/blob/main/html/introduction-to-html/document_and_website_structure/index.html to reflect these changes as well.

**Comment by otakutyrant** [comment]
> We would need to update https://github.com/mdn/learning-area/blob/main/html/introduction-to-html/document_and_website_structure/index.html to reflect these changes as well.

I wonder that there are two duplicate sources, and some of them are not the same even, like those foreign paragraph of one source have many breakline and the other otherwise. Is there any way just to make to let the page embed the example from learning-area rather than maintains the duplicate example?

**Comment by estelle** [comment]
> How about letting the page embed the example from learning-area rather than maintaining the duplicate example of the page?

I agree that we should. This requires other edits to the page. The section "Our example seen above is represented by the following code (you can also [find the example in our GitHub repository](https://github.com/mdn/learning-area/blob/main/html/introduction-to-html/document_and_website_structure/index.html)).'" would need updating.  The image at the top of the page can be replaced with the liveexample, with the content of https://github.com/mdn/learning-area/blob/main/html/introduction-to-html/document_and_website_structure/style.css as hidden CSS

**Comment by otakutyrant** [comment]
I am going to sleep. Let me see what I can do tomorow.

**Comment by Josh-Cena** [comment]
Duplicated  code is the way the learning area works unfortunately, and while the code in content is well-updated and maintained, the code in the learning-area repo often goes outdated because the lintin/formatting infra is close to nonexistent. In this case we should just copy the code in content to the learning-area HTML file and hope they stay the same in the future.

**Comment by otakutyrant** [comment]
> The image at the top of the page can be replaced with the liveexample, with the content of https://github.com/mdn/learning-area/blob/main/html/introduction-to-html/document_and_website_structure/style.css as hidden CSS

I think it is unnecessary to update the image because they seem the same even with one of them missing the section tags.

**Comment by otakutyrant** [comment]
Since the code from the learning-area is inconsistent with the code from the content already, I think we can merge the pull here first. I have already to submit https://github.com/mdn/learning-area/pull/765 to keep consistence, and that PR is another matter.

**Review by estelle — APPROVED** [review]

**Pull request merged**
