### PR TITLE
Fixed String.prototype.replace page internal links

### PR DESCRIPTION
**Pull request by kauer3**

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
I don’t believe these changes are going to affect anything. The Yari backend automatically regenerates heading ID values in the DOM based on the text content of the headings — and overwrites any ID values manually specified in the source markup.

**Comment by Ryuno-Ki** [comment]
@sideshowbarker We were wondering over in #1854 what was going on.
There's definitively something broken on the production site, so I suggested to make these changes here to see, whether it has any effect.

**Comment by sideshowbarker** [comment]
@peterbe Can you please take a look at this, and at #1854?

**Comment by peterbe** [comment]
Correct. At this time, we should *not* manually edit the `id="..."` attribute to just fix the casing. And the anchor links will get corrected automatically anyway at build-time. But, it's considered a flaw, so it's actually a good idea to...
```diff
-<a href="#Specifying_a_function_as_a_parameter">Specifying a function as a
+<a href="#specifying_a_function_as_a_parameter">Specifying a function as a
```

But I would recommend we don't make PRs that manually fix a couple of single anchor links. Instead, use the automatic flaw fixer and when you do, that'll including fixing the act over lowercasing all anchor links.

**Comment by peterbe** [comment]
Let's close this PR and focus on https://github.com/mdn/yari/issues/2763

**Comment by Ryuno-Ki** [comment]
Thank you for your effort, @kauer3.
I hope, you understand.

**Comment by kauer3** [comment]
It's ok, thanks for your help.

**Pull request closed without merging**
