### PR TITLE
remove "callBackFn" from inline callback function

### PR DESCRIPTION
**Pull request by dangduomg**
should I?

#### Summary

Change the function statement in "Inline callback function" to a function expression

#### Motivation

Using function statements as arguments is pretty strange

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by dangduomg** [comment]
> should I?
> 
> #### Summary
> Change the function statement in "Inline callback function" to a function expression
> 
> #### Motivation
> Using function statements as arguments is pretty strange
> 
> #### Supporting details
> #### Related issues
> #### Metadata
> * [ ]  Adds a new document
> * [x]  Rewrites (or significantly expands) a document
> * [ ]  Fixes a typo, bug, or other error

**Review by wbamberg — COMMENTED** [review]
I agree it does look a bit strange but this is our standard: https://developer.mozilla.org/en-US/docs/MDN/Structures/Syntax_sections#callback_syntax_blocks

If we want to change this we should discuss, update the standard, and update all pages, not just this one (also see e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#syntax).

@Elchi3 , since you were involved in the new syntax sections, do you have an opinion here?

**Comment by Elchi3** [comment]
> @Elchi3 , since you were involved in the new syntax sections, do you have an opinion here?

Happy to remove that everywhere and make it the guideline. Agree function expressions are more common.

**Review by wbamberg — APPROVED** [review]
OK, I filed https://github.com/mdn/content/pull/9995 to update the standard and it is merged, so let's merge this, too.

Thanks @dangduomg !

**Pull request merged**
