### PR TITLE
Adding drag & drop note to file system landing page

### PR DESCRIPTION
**Pull request by Rumyra**

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by Rumyra** [comment]
Thanks @sideshowbarker - I don't feel I've followed process properly. @chrisdavidmills said we had the ability to merge our own small prs such as this one, but evidently it doesn't seem the case 🤔 if anyone could enlighten that would be great ☺️

**Comment by chrisdavidmills** [comment]
@Rumyra I thought you would, but there seems to be a problem with it....we'll have to investigate it next year ;-)

**Comment by sideshowbarker** [comment]
> Thanks @sideshowbarker - I don't feel I've followed process properly. @chrisdavidmills said we had the ability to merge our own small prs such as this one, but evidently it doesn't seem the case 🤔 if anyone could enlighten that would be great ☺️

Yeah I’m not sure but I think the one of the effects of using the CODEOWNERS mechanism is that it causes GitHub to require an approval by someone other than the PR author. (Or maybe more precisely, it causes GitHub to require an approval, full stop — and since GitHub doesn’t allow authors to approve their own PRs, that means somebody else needs to.)

**Comment by Rumyra** [comment]
Thank you both!

@sideshowbarker I did wonder if it was gh process after my first comment - thanks for clearing it up for me 👍

**Pull request merged**
