### PR TITLE
Glossary: classes and functions are block scoped too

### PR DESCRIPTION
**Pull request by dragunovartem99**
I've added example for function declarations, they can also be block-scoped (in strict mode)

You can check this in node.js or browser, I am learning a popular Udemy course (JS), and encountered this topic. I think it might be a usefull addition

I would be happy to receive feedback!

### CODE REVIEW

**Review by hamishwillee — APPROVED** [review]
I think adding heading structure is good, but given it is mostly JavaScript focused, would appreciate @Josh-Cena comment.

A few thoughts
- The fact that scopes share with children but not parents is mentioned but not demonstrated
- Once you start adding demos for various cases this topic grows beyond what you should do in a Glossary. Is there an MDN topic on JavaScript scopes that we should link to and perhaps cut this back to a bare minimum?

**Comment by Josh-Cena** [comment]
I agree this should be cut back to a minimum, and in fact I basically did to the point that I was comfortable with the last time I rewrote this. However people really want to see more content on this page, and content is scattered in the references of different syntaxes.

As for this PR, the only change I'm comfortable with is to make a passing mention of "block-scoped function declarations in strict mode" and "class declarations" when we talk about block scopes, because the current phrasing suggests that only these two things are block-scoped. Any more explanation should belong to the reference pages.

**Comment by dragunovartem99** [comment]
@Josh-Cena good, how you see the final result? I understood it like:

1. no addition sections (subheading), to keep page flat
2. make a brief mention of function declaration behavior (probably remove the example?)

And sorry, I didn't understand your mention of "class declaration", I have little experience with OOP, just tried it in "sloppy mode", console throwed an error. Maybe I did something wrong?

Screenshot_20240730_073834

**Comment by Josh-Cena** [comment]
I meant that both function declarations in strict mode and class declarations are block-scoped. So the change I would like to see is that instead of this sentence:

> In addition, variables declared with [`let`](/en-US/docs/Web/JavaScript/Reference/Statements/let) or [`const`](/en-US/docs/Web/JavaScript/Reference/Statements/const) can belong to an additional scope:

We say something more generic such as "certain declarations can belong to an additional scope", while I think other changes are unnecessary and can be put in see also if necessary.

**Comment by hamishwillee** [comment]
Removing myself as reviewer  - I'm in line with your thinking @Josh-Cena

**Comment by dragunovartem99** [comment]
@Josh-Cena I understand, so what can be best way to continue?

I think the problem is that current page "Glossary/Scope" can create false impression that block scope is only relevant to `const` and `let` variables

I think, one way possible way is to use your generic line, for example:

"In addition, identifiers declared with let, const, class, or (in strict mode) functions can belong to an additional scope"

And I found great section just about this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block#block_scoping_rules_with_let_const_class_or_function_declaration_in_strict_mode

I think the balanced approach may be:

- use generic line with mentioning of class/function declarations
- include link to block statement's scoping rules in the specified sentence, or in "See also"
- remove examples with `alarm()` from PR
- maybe, to trim this Glossary page more, remove "var vs const" comparison, because it is perfectly described in the reference/statements/block

What do you think?

It's the 1st time I am trying to contribute content to MDN, and I haven't understood architecture yet 😅

**Comment by PassionPenguin** [comment]
> * use generic line with mentioning of class/function declarations
> * include link to block statement's scoping rules in the specified sentence, or in "See also"

I would prefer to implement such: leave a generic line with a link to the specified document. Leaving the readers to the document that talks about these will allow them to have just a deeper (and of course, a correct) insights into the field. Glossary will be best when it just provide as most general impression to readers, like the dictionaries do :)

**Comment by Josh-Cena** [comment]
It seems the majority of the opinion is to reduce this PR to a one-paragraph change. And add more links to things like function declarations, blocks, different variable declarations, etc.

**Comment by dragunovartem99** [comment]
@Josh-Cena can you please check it?

I am using GitHub editor right now and created additional commit. I have reduced PR as community advised

**Review by Josh-Cena — APPROVED** [review]
Looks good—thanks for the changes!

**Pull request merged**
