### PR TITLE
fix fixable flaws in web/css/css_box_alignment

### PR DESCRIPTION
**Pull request by peterbe**
I went to http://localhost:3000/en-us/docs/Web/CSS/CSS_Box_Alignment#_flaws and pressed the "Fix fixable flaws" button. 

As you can see, it downloaded a bunch of images, ran compression on them and changed the image references. 
What's cool about this is that the new combined total image size is:

2.86 KB + 221 B + 1.40 KB + 257 B + 256 B

Before, it was:

7.83 KB + 1.44 KB + 3.26 KB + 1.56 KB + 1.57 KB

So, in total the amount of stuff you had to download, as a reader, **went from 15.7 KB to 5.0 KB**
How cool is that?!

### CODE REVIEW

**Comment by peterbe** [comment]
And, prior, all 5 images had to go through Kuma and do a redirect to the S3 public URL. That takes time too whereas now, when they're all from the same domain, we can pipeline them in HTTP2 (some of it was pipelined before too) so you can get a slight performance boost from the delivery too.

**Comment by vkWeb** [comment]
@peterbe A BIG WIN HERE! :tada: :partying_face:

**Review by vkWeb — APPROVED** [review]

**Comment by vkWeb** [comment]
@peterbe I think we should raise an issue asking contribution on applying fixable flaws to all the directories piece by piece...?

The performance improvement is non-trivial here. What do you think?

**Comment by peterbe** [comment]
> on applying fixable flaws to all the directories piece by piece

Unfortunately, there's a bug :(
If a page has two identical `src` values in two different `` tags, it causes weirdness. 
It's being fixed in https://github.com/mdn/yari/pull/2249 but that won't be merged until January.

**Pull request merged**
