### PR TITLE
[Markdown] [Web/HTML] Convert HTML docs to Markdown - DO NOT SQUASH MERGE

### PR DESCRIPTION
**Pull request by wbamberg**
See https://github.com/mdn/content/issues/8961 for the "preparation" work.

This PR converts Web/HTML to Markdown.

Conversion report summary:

```
## All unhandled elements

- table.properties (140)
- kbd (96)
- tr (73)
- table.no-markdown (30)
- td (29)
- th (22)
- table.standard-table (19)
- td[colSpan="2"] (17)
- th[scope="row"] (13)
- sub (5)
- td[rowSpan="3"] (5)
- td[rowSpan="4"] (5)
- table.fullwidth.standard-table (3)
- sup (3)
- th[colSpan="2"][scope="col"] (2)
- table (2)
- td[rowSpan="2"] (2)
- th[scope="col"] (2)
- table.fullwidth-table (1)
- td[colSpan="3"] (1)
- th[colSpan="2"] (1)
- th[rowSpan="2"][scope="col"] (1)
- td[rowSpan="6"] (1)
- td[rowSpan="14"] (1)
- td[rowSpan="7"] (1)
- td[rowSpan="9"] (1)
```

Full conversion report: https://gist.github.com/wbamberg/af1992d83e5fa9bb4fc255c7417bfdde

The only unconverted elements are `<sub>`, `<sup>`, `<kbd>` and tables.

## \<sub> and \<sup>

These elements only appear in the actual pages that document them, to demonstrate proper usages:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sub#usage_notes
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup#usage_notes

It seems much better to keep the HTML here.

## \<kbd>

As we have for other doc sets, this PR keeps `<kbd>` as HTML.

## \<table>

Many tables here are unconverted:
* HTML elements all have `.properties` tables, which as in other docsets are kept as HTML
* Many tables are not convertible.
* Some tables that would be convertible produce GFM tables >150 character wide, and https://github.com/mdn/content/pull/9216 prevents these from being converted.

### CODE REVIEW

**Comment by wbamberg** [comment]
To coordinate reviews I've created https://docs.google.com/spreadsheets/d/1QnKzVj8Q4OIw7_FFjCTyx3U5wWO9cIUUgVozKDtcm2o/edit#gid=0

As before, the purpose of this is just to ensure different people review different pages.

**Review by teoli2003 — APPROVED** [review]
Found 2 sectioning flaws introduced by md, fixed them (and checked with the flaw dashboard that I didn't miss any), and two other nits.

I think we are good to go.

**Comment by wbamberg** [comment]
Thanks for all your work on this @teoli2003 !

**Comment by teoli2003** [comment]
💯 👏

**Pull request merged**
