### PR TITLE
fix(workflows): add Playground env variables

### LINKED ISSUE #9193: Live sample in PR preview is broken
### Summary

The live sample is broken in PR preview (got 404), see:

- mdn/content#27637 - https://pr27637.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/input/datetime-local
- mdn/translated-content#13957 - https://pr13957.content.dev.mdn.mozit.cloud/zh-CN/docs/Web/API/EyeDropper

image

### URL

see above

### Reproduction steps

open preview page and scroll to the live sample.

### Expected behavior

could see the live samples in PR preview

### Actual behavior

got 404

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

_No response_

### Anything else?

_No response_

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

### PR DESCRIPTION
**Pull request by caugner**
### Description

Adds new environment variables that are required for live samples since the introduction of the MDN Playground.

### Motivation

The live samples on the preview URLs were broken since the launch of the MDN Playground.

### Related issues and pull requests

Fixes https://github.com/mdn/yari/issues/9193.

### CODE REVIEW

**Comment by caugner** [comment]
Looking at the CSP error now:

> Content-Security-Policy: The page’s settings blocked the loading of a resource at https://live.mdnyalp.dev/en-US/docs/Glossary/Block-level_content/runner.html?id=examples (“frame-src”).

**Comment by caugner** [comment]
> Looking at the CSP error now:

✅ Published a new version of the AWS Lambda that sets the response header for this dev environment (Note: All other environments are already in GCP), and set that version on the CloudFront behavior.

It is now working:
image

**Review by fiji-flo — APPROVED** [review]
This should do the trick 👍

**Comment by OnkarRuikar** [comment]
:tada: It's working now: https://github.com/mdn/content/pull/27688

**Note:** Rebase on PR is required to see this work. Haven't tried manually re-runing the workflows.

**Comment by yin1999** [comment]
We also need to update https://github.com/mdn/translated-content/blob/main/.github/workflows/pr-test.yml

**Pull request merged**
