### PR TITLE
Update index.md regarding issue#11119

### LINKED ISSUE #11119: Content bug: channelCountMode
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/AudioNode/channelCountMode

## Specific page section or heading?

The table at the top of the page

## What is the problem?

1. The `channelCountMode` of a `ChannelMergerNode` is documented as `max` while [the spec](https://webaudio.github.io/web-audio-api/#dom-audionode-channelcountmode) states it should always be `explicit`
2. The value of `max` is documented to consider the maximum across all connections, while [the spec states it should only consider the input connections](https://webaudio.github.io/web-audio-api/#enumdef-channelcountmode).

### PR DESCRIPTION
**Pull request by moflaky**
#### Summary
ChannelMergerNode element has been moved from the max row to the explicit row in the table.

#### Motivation
Contribute to MDN docs

#### Related issues
Fixes #11119 

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x ] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thank you @moflaky !

It looks like we should also update the table in https://developer.mozilla.org/en-US/docs/Web/API/ChannelMergerNode : https://github.com/mdn/content/blob/909797b3d12b98928f46bfa05847c19d4c5783c2/files/en-us/web/api/channelmergernode/index.md?plain=1#L36

...do you think?

**Comment by moflaky** [comment]
Ah yes! That makes sense I didn't even think to look because I'm so new to MDN docs and open source. Should I edit that and put in a pull request with this same issue as a label?

**Comment by wbamberg** [comment]
> Ah yes! That makes sense I didn't even think to look because I'm so new to MDN docs and open source. Should I edit that and put in a pull request with this same issue as a label?

I think it would be easiest to add it to this PR, if you're OK with that.

**Comment by moflaky** [comment]
> > Ah yes! That makes sense I didn't even think to look because I'm so new to MDN docs and open source. Should I edit that and put in a pull request with this same issue as a label?
> 
> I think it would be easiest to add it to this PR, if you're OK with that.

I believe I correctly changed that in the web api docs and successfully pushed the commit to this PR. Very new to all of this so hopefully I did it right. Thanks for the feedback!

**Review by wbamberg — APPROVED** [review]
Looks great, thank you @moflaky - and welcome to MDN!

**Pull request merged**
