### PR TITLE
Fix a bunch of broken image references

### PR DESCRIPTION
**Pull request by peterbe**
Sorry for the rather big change but I grabbed a bunch based on https://github.com/mdn/content/pull/937 and just fixed them.

### CODE REVIEW

**Comment by peterbe** [comment]
@nschonni Can you take a look?

**Comment by nschonni** [comment]
Skimmed it and it makes sense. Few minor things for later:
- For the files is lowercases from `camelCase.jpg`, maybe hiphenate it instead like `camel-case.jpg` so that the non-alt text ones give something a little better for the screen reader
- Some file names are short and non-descriptive. Once you start checking them in here, it gets more "expensive" (larger repo) later when you want to rename them to something more descriptive. Might be a good time to layout some guidelines for filename. Didn't find anything here to use https://docs.microsoft.com/en-us/style-guide/accessibility/graphics-design-media

**Review by chrisdavidmills — APPROVED** [review]
LGTM.

And I agree about hypenated being a preferable convention to camel-cased, but we can work on this as we go.

**Comment by peterbe** [comment]
>     * For the files is lowercases from `camelCase.jpg`, maybe hyphenate it instead like `camel-case.jpg` so that the non-alt text ones give something a little better for the screen reader

I agree. So screen readers will read out the filename?? That's amazing. 
But isn't it more pressing that the `` tags don't have a good `alt` text? Seems like a flaw that we should elevate so that writers can find all alt-less images and give them good texts.

**Comment by peterbe** [comment]
>     * Some file names are short and non-descriptive. Once you start checking them in here, it gets more "expensive" (larger repo) later when you want to rename them to something more descriptive. Might be a good time to layout some guidelines for filename. Didn't find anything here to use https://docs.microsoft.com/en-us/style-guide/accessibility/graphics-design-media

Yes please!
In fact, we can enforce it with a flaw checking. Too. It's currently a flaw if the filename isn't all lower-case. So it wouldn't be hard to extend that with a check that you use `-` instead of `_`. But I don't know how you can confidently write an if-statement that says that `offsetleft.jpg` isn't a good name and that it should be `offset-left.jpg` instead.

**Comment by nschonni** [comment]
> But I don't know how you can confidently write an if-statement that says that `offsetleft.jpg` isn't a good name and that it should be `offset-left.jpg` instead.

You'd probably need to use something like https://github.com/pineapplemachine/camel-to-kebab-js instead of just lowercasing it. Didn't actually test the library, was just the first hit for "camelcase to kebab"

**Comment by peterbe** [comment]
Converting `camelCase` to `camel-case` doesn't scare me. But converting `camelcase` to `camel-case` does. :)

**Pull request merged**
