### PR TITLE
Remove private field from accessible fields

### PR DESCRIPTION
**Pull request by geryogam**

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Hi! Instead of removing this, we should add `#privateField`. Both Chrome and Firefox dev tools show private properties in the log message. However, we should also add a note that this is only the console output, and they are not really accessible in practice.

**Comment by geryogam** [comment]
Hi @Josh-Cena! I agree that if we decide to show private properties we should show both, like in Firefox and Chrome dev tools. Note that Node and Safari dev tools don’t show private properties at all though.

**Comment by geryogam** [comment]
I updated the PR by adding Chrome dev tools output using the wording already used in the next example in the ‘Returning overriding object’ section.

**Review by Josh-Cena — APPROVED** [review]
Thanks

**Comment by geryogam** [comment]
Thanks for the review!

**Pull request merged**
