### PR TITLE
Added note to subtraction assignment operator

### PR DESCRIPTION
**Pull request by mighty-odewumi**
### Description

I added a note to clarify that the expression before the subtraction assignment operator is evaluated once.

### Motivation

I want to improve the documentation so that users can better digest concepts.

### Related issues and pull requests

Relates to #29524

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
Please don't do it one page at a time. Update all assignment operators within one PR.

**Comment by Josh-Cena** [comment]
Closing in favor of https://github.com/mdn/content/pull/29563

**Comment by mighty-odewumi** [comment]
Please, I would like to have this PR labeled as ```hacktoberfest-accepted``` after merge if that's fine by you as I would like my contribution to count in the Hacktoberfest event.

Thanks. 🙏

**Comment by mighty-odewumi** [comment]
> Please don't do it one page at a time. Update all assignment operators within one PR.

Oh. I'm sorry. 

I'm not with a PC at the moment. I'm using a mobile phone and I wanted to make the PRs on time. I would do as you've said.

**Comment by Josh-Cena** [comment]
See my comment https://github.com/mdn/content/pull/29563#issuecomment-1753747231

**Pull request closed without merging**
