### PR TITLE
Iss3386

### LINKED ISSUE #3386: Content bug: space before </code> on many pages
## What page(s) did you find the problem on?

Lots of them!

## Specific page section or heading?

Example: https://developer.mozilla.org/en-US/docs/Web/API/Attr#properties

## What is the problem?

There's a space in the code instead of after it, so it shows `true ` instead of `true`.

Some cases fixed in https://github.com/mdn/content/pull/3385, but there are too many so I'm filing an issue instead.

### PR DESCRIPTION
**Pull request by CreaTorAlexander**
In this PR all spacing issues in the /mozilla subdirectorys gets fixed.

Partly Fixes #3386 

I have seen that the *.CONTENT_TRANSLATED_ROOT*  File is included but unfortunately Idk how to remove it.
I would be happy if someone can help me with this.

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
The changes look good overall, thanks @CreaTorAlexander .

To remove the unwanted file, this might help: https://developer.mozilla.org/en-US/docs/MDN/Contribute/GitHub_beginners#reversing_a_commit_that_has_been_pushed_to_the_remote_fork

But only if that file was added in its own commit.

So to get rid of this, you'd have to remove the file, add that removal as another commit, and push it to the same branch.

**Comment by CreaTorAlexander** [comment]
I don't think that it worked :/

**Comment by chrisdavidmills** [comment]
> I don't think that it worked :/

heh, the pains of GitHub ;-)

I'll try deleting it from the PR manually.

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander hrm, looks like that worked. For future reference, just go to the files changed tab, and use that file's three dot menu > Delete file option.

**Comment by CreaTorAlexander** [comment]
Oh wow okay ^^, thanks a lot for your help :)

**Pull request merged**
