### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by loxcel**
The phrase "imported into" makes no sense. You either "import from" or "export to"

### CODE REVIEW

**Comment by bsmth** [comment]
Hi @loxcel, thanks for opening the PR. I'm going to close this as the original is correct in this case. Importing 'into' is grammatically correct and helps with the context of instantiation here.

Thank you :)

**Comment by Josh-Cena** [comment]
To help with your understanding: if you are in a module X, and you are importing a value Y from somewhere else, then you are "importing Y into X". The module here has just been created, so surely you can't import anything "from" it; only "into" it.

**Comment by loxcel** [comment]
Joshua,

*if you are in a module X*


Ok, our context is X. We are in X.


*importing Y into X*


Because we know where we are -- in X -- saying "into X" is redundant
because we know where we are.

What would be more helpful if we knew from where we are importing, eg
"importing from Z"

But, let's put the technology aside for a second, and see how import and
export are commonly used.

Assume you live in the United States and are importing a luxurious alpaca
sweater from Ecuador.

Now, if you said to a friend "I'm importing a sweater into the United
States" your friend might be puzzled because he knows where you both are.
The statement has redundant information.

That statement, "I'm importing a sweater into the United States," is
analogous to saying "importing Y into X" because the statement is made in
the context that "we are in X."

A more helpful statement would be something like "I'm importing a sweater
from Chile." The corollary to that would be the exporter who would say "I'm
exporting a sweater to the United States."

Hope that makes sense.


Thanks

Kevin.

**Comment by Josh-Cena** [comment]
It is indeed redundant if you are unambiguously in module X. For example, if you are writing an `import` statement, you can simply say "import a value from somewhere", because where that import statement is located is exactly the module into which the value is imported. However, in the case of WASM instantiation, the call to `WebAssembly.instantiateStreaming` neither happens in the source module nor in the target module—rather, it's the "middleperson" that connects two modules (and indeed, because these modules are WASM while you are in JS). You can both import values from the newly-created `Instance` into the surrounding scope, or you can import values collected from the surrounding scope into the `Instance`.

To use your analogy, you are a global company that does a lot of international trades between countries. You are not based in any particular country; neither is your listener. All these countries are just "objects". In this case, you must be explicit about the source and target.

**Pull request closed without merging**
