### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by RajaSardar**
source description of null

### CODE REVIEW

**Comment by RajaSardar** [comment]
more description on null

**Comment by chrisdavidmills** [comment]
@RajaSardar Hi there! Is there a particular problem you were trying to fix with this addition? On reading it, it is interesting, but I'm not convinced it really improves the page in the sense of allowing people to understand the concept of null.

Sorry to sound picky here, but I'm just trying to understand the motication for this change. Thanks!

**Comment by RajaSardar** [comment]
As I was trying to find a full description about null I barely find any descriptive information about null, so I think this piece of code can help others for better understanding

**Comment by wbamberg** [comment]
This seems to be copy/pasted from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#typeof_null.

**Comment by RajaSardar** [comment]
Yes, but it should be here too

**Comment by sideshowbarker** [comment]
Closing this per https://github.com/mdn/content/pull/2895#issuecomment-791999882 — it doesn’t seem necessary to have this text repeated verbatim in a different place.

**Pull request closed without merging**
