### PR TITLE
Revert "dump 2020-11-12" for certificate_transparency

### PR DESCRIPTION
**Pull request by lol768**
This reverts commit bbcf9eb1ed2f5890d373e7b338e259b6811678c2.

### CODE REVIEW

**Comment by peterbe** [comment]
I don't think that PR title is great. Do you think you can phrase the PR differently so it's more specifically to the content you're fixing?

**Comment by lol768** [comment]
I'd love to use a more descriptive commit message describing the exact edit that was reverted, but the history log has seemingly been lost in the move to this platform.

I've asked if there's any way to access the revision history.

**Comment by peterbe** [comment]
> I've asked if there's any way to access the revision history.

Not at the moment, unfortunately.

**Comment by lol768** [comment]
It sounds like a backup of the history _was_ taken though, which is great to hear.

I hope that in due course this data can be made available (even if it's just a SQL file), I'm somewhat surprised the migration just happened with the repository history in its current state to be honest, it's a bit disappointing.

**Comment by lol768** [comment]
can you tell me what I need to do to get this merged, please? I can do it and then resolve the conflicts.

**Review by chrisdavidmills — APPROVED** [review]
Reviewed, and it looks fine. I've also resolved the conflict. Let's get this merged.

**Comment by peterbe** [comment]
> It sounds like a backup of the history _was_ taken though, which is great to hear.
> 
> I hope that in due course this data can be made available (even if it's just a SQL file), I'm somewhat surprised the migration just happened with the repository history in its current state to be honest, it's a bit disappointing.

Not a SQL file, but a CSV :)
https://github.com/mdn/wiki-revision-history

**Comment by lol768** [comment]
Thank you @peterbe!

**Pull request merged**
