### PR TITLE
Adds the welcome bot to the content repo

### PR DESCRIPTION
**Pull request by dipikabh**
### Description

This task is part of making all mdn repositories similar in settings and configuration (https://github.com/mdn/mdn/issues/168)

### CODE REVIEW

**Comment by dipikabh** [comment]
I guess the 'system-file-changes.yml' workflow failure is expected.

The GitHub link in the error message is invalid.

```
Run # It would be nice if we could disable this workflow if the PR
  # It would be nice if we could disable this workflow if the PR
  # was made from a branch within the origin repo. But it seems you
  # can't do that :(
  # See https://github.community/t/how-do-you-figure-out-if-a-pr-is-from-a-work-in-pull-request-target-workflows/170001
  
  echo "If you're an admin, you have to use your admin privileges to override."
  echo "If you're not an admin, please ping someone for a review."
  exit 1
  shell: /usr/bin/bash -e {0}
If you're an admin, you have to use your admin privileges to override.
If you're not an admin, please ping someone for a review.
Error: Process completed with exit code 1.
```

**Review by schalkneethling — APPROVED** [review]
Thank you, @dipikabh 🍵

**Review by bsmth — APPROVED** [review]

**Review by estelle — APPROVED** [review]

**Review by caugner — APPROVED** [review]

**Comment by dipikabh** [comment]
Thank you, @caugner!

**Comment by bsmth** [comment]
After feedback, I'm going to revert this one for the moment 🤖

**Pull request merged**
