### PR TITLE
Fixed missed logged value of array

### PR DESCRIPTION
**Pull request by quincyhill**
#### Summary

the `arr` array should have the added key: "foo" with value: "hello".

#### Motivation

Minor typo that could lead javascript learners to wonder why the appended key value pair is missing its value.

#### Supporting details

[link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration#continue_statement)

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
`for...of` loops only visit array indices. Please see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#difference_between_for...of_and_for...in and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator.

You would have confirmed the same if you've done some tests yourself.

image

**Comment by Josh-Cena** [comment]
Closing because the original example is correct

**Comment by quincyhill** [comment]
You referenced the wrong example, here is the image
mdndocstypofix
I ran this example my self and theres the typo

**Comment by wbamberg** [comment]
I think the error is that [line 448](https://github.com/mdn/content/blob/5c5bb88bdd50a6599e25ad544511924ffb694a76/files/en-us/web/javascript/guide/loops_and_iteration/index.md?plain=1#L448) needs to be:

```
  console.log(i); // logs "0", "1", "2", "hello"
```

**Pull request closed without merging**
