### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by JennMP88**
I changed line 672. The forLoop contained a , instead of a semi colon.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thanks for this PR, but the existing code is correct: the first bit `var i = 0, j = arr.length;` is declaring two variables `i` and `j`, which are then getting used in the next bit `i < j;`.

I guess the reason it's doing this rather than:

```js
function avgArray(arr) {
  var sum = 0;
  for (var i = 0; i < arr.length; i++) {
    sum += arr[i];
  }
  return sum / arr.length;
}

avgArray([2, 3, 4, 5]); // 3.5
```

...is some kind of micro-optimization so you don't have to access `arr.length` more than once.

Still it would be better if we just did this:

```js
function avgArray(arr) {
  let sum = 0;
  for (const item of arr) {
    sum += item;
  }
  return sum / arr.length;
}

avgArray([2, 3, 4, 5]); // 3.5
```


...for all the loops in the section. I note that we do actually talk about this a little earlier:

> We will also replace the for loop with a for...of loop to return the values within our variable.

...but then it goes back to an old-style `for` loop.

So I suggest that we *either*:

* just close this PR, and leave things as they are, *or*:
* update all these loops to be `for...or` loops.

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

**Comment by JennMP88** [comment]
Hello again, 
Thank you for the quick response. I really love your detailed explanation and that I learned something valuable in this process. I will delete the branch shortly. 
All the best, 
Jen

**Comment by wbamberg** [comment]
You're welcome, @JennMP88 , and I'm glad it was helpful!

**Pull request merged**
