### PR TITLE
What Went Wrong exercise: Remove warning about live server code injection and line numbers

### PR DESCRIPTION
**Pull request by mao-sz**
### Description

- Amends line/char numbers from error messages to reference the right lines from the changes in https://github.com/mdn/learning-area/pull/775
- Amends the 3 screenshots to also show the new line numbers
- Removes the "live server code injection" warning

### Motivation

In the ["What went wrong?" exercise](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong), there is a warning about line numbers in error messages potentially not matching source code line numbers due to code injection from extensions like live-server.

This is a result of the code's script tag being placed after the closing body tag, so live-server's injected code comes before it (as it injects right before the closing body tag).

By placing the script tag before the closing body tag, live-server injects code after it, preserving line numbers in the error messages, making the lesson much easier to follow for more people. The relevant warning can then be removed from the lesson. This warning and exercise has thrown a few people off in The Odin Project curriculum, and they are apprehensive about using tools like live-server.

This has been tested with [VSCode's Live Server extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer), [VSCode's Live Preview extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server) and the [live-server npm package](https://www.npmjs.com/package/live-server).

### Related issues and pull requests

Depends on: https://github.com/mdn/learning-area/pull/775

### CODE REVIEW

**Comment by wbamberg** [comment]
@MaoShizhong , CI is complaining because it wants you to compress the screenshots in this PR. You should be able to do that by running:

```
yarn filecheck 'files/en-us/learn/javascript/first_steps/what_went_wrong/console-log-output.png' --save-compression
yarn filecheck 'files/en-us/learn/javascript/first_steps/what_went_wrong/not-a-function.png' --save-compression
yarn filecheck 'files/en-us/learn/javascript/first_steps/what_went_wrong/variable-is-null.png' --save-compression
```

Once it's green I'll review this. Thank you!

**Comment by MaoShizhong** [comment]
No problem, I'll get that done tomorrow :+1:

**Comment by wbamberg** [comment]
Thanks @MaoShizhong ! This all works and is aligned with the version in the learning-area repo.

The only issue I can see - and sorry I didn't pick up on this before - is that when the source gets Prettier-formatted, the line number and character position change to 87:16. So if someone (like me) has Prettier installed to reformat on save, they will likely get different values.

I don't know how common this setup is especially for new starters, but it's probably better to use Prettier-formatting, and that is our general standard for code samples on MDN, although learning-area hasn't caught up fully yet.

I appreciate this would mean you doing all this again! If you don't want to just let me know and I'll merge it as is, because it does fix the code injection issue and is an improvement IMO.

**Comment by MaoShizhong** [comment]
@wbamberg Not a problem! I wasn't 100% sure there was a style standard for the learning area (given the original code) so I didn't want to introduce anything more than just using consistent indentation (on top of the tag-moving).

If Prettier is the standard used across MDN then I'm all for using that and redoing the lines here as necessary. Not a problem at all.

**Comment by MaoShizhong** [comment]
Line number refs and screenshots amended and PR ready for review again.

**Review by wbamberg — APPROVED** [review]
👍 thank you @MaoShizhong , this looks great!

**Pull request merged**
