### PR TITLE
relnote(Fx114): mozImageSmoothingEnabled no longer supported

### PR DESCRIPTION
**Pull request by bsmth**
The prefixed prop is deprecated for a long time and is now no longer supported.
Also removing references in examples showing the prefixed props.

__Related issues and pull requests:__
- [x] Parent issue https://github.com/mdn/content/issues/26686
- [x] BCD https://github.com/mdn/browser-compat-data/pull/19828

__Bugzilla:__
- Tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1228850

__Other resources:__
* Intent to Remove: CanvasRenderingContext2D.webkitImageSmoothingEnabled https://groups.google.com/a/chromium.org/g/blink-dev/c/qeFgqezm0cM/m/z708BVaGAAAJ
* https://chromestatus.com/metrics/feature/timeline/popularity/267
* BCD: https://github.com/mdn/browser-compat-data/blame/93c166cb0b0409dfda8950fca3ad148b2ff12050/api/CanvasRenderingContext2D.json#L1478

### CODE REVIEW

**Comment by hamishwillee** [comment]
FWIW it doesn't make any difference in the long haul, but for these cases I tend to do a release note entry for the thing being disabled by default, and one for final removal. So an entry in both months. 

But if you want just one, then moving it to 113 does make more sense.

**Comment by bsmth** [comment]
Thanks both, added a note that this is disabled in Fx113 and left the Fx114 addition in for good measure: f36b724267e7d73730ab4b9266a73d29092a1c80

**Review by Elchi3 — APPROVED** [review]
LGTM 👍

**Comment by bsmth** [comment]
Thank you!

**Pull request merged**
