### PR TITLE
fix license in package.json

### PR DESCRIPTION
**Pull request by escattone**
Per https://docs.npmjs.com/files/package.json#license:

> If you are using a license that hasn’t been assigned an SPDX identifier, or if you are using a custom license, use a string value like this one:
> 
> ```json
> { "license" : "SEE LICENSE IN <filename>" }
> ```
> 
> Then include a file named <filename> at the top level of the package.

### CODE REVIEW

**Review by peterbe — CHANGES_REQUESTED** [review]
That won't take away the ultimate problem of having to see that darned warning from `yarn` umpteen times. 

Screen Shot 2020-09-25 at 1 07 44 PM

I wouldn't be sure that we'll never ever ship this whole thing to a package repository. Who knows, perhaps someday we do so it can be downloaded by the likes of VSCode without having to rely on `git clone`. So it'd be nice to get that right.

**Comment by escattone** [comment]
@peterbe Strange, I don't see any of those license warnings!

image

**Comment by escattone** [comment]
@peterbe We're following the recommendation of `npm` itself (https://docs.npmjs.com/files/package.json#license) so it seems like a `yarn` issue rather than our issue. The only other thing I can think of, that we might do, is something like this:
```json
{ "license" : "(CC-BY-SA-2.5 AND (CC0-1.0 OR MIT))"
```
but that doesn't include the details/nuances (e.g., regarding which license applies to code examples based on date created) like our `LICENSE.md` does, so it may not be legally appropriate.

**Review by peterbe — APPROVED** [review]
Gross me! I think I tested it before actually checking out your branch. 
I blame getting used to the new default branch being called `main`. Either way, no warnings now when I `yarn install`.

**Pull request merged**
