### PR TITLE
Remove remaining {{draft}} KS macro calls (ex accessibility)

### PR DESCRIPTION
**Pull request by tannerdolby**
#### Summary

Removes all remaining `{{draft}}` KS macro calls.

#### Related issues

Cleans up #10501 

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document (Removes content)
- [ ] Fixes a typo, bug, or other error

cc @wbamberg

### CODE REVIEW

**Comment by estelle** [comment]
I would prefer to keep the draft on the /Web/Accessibility/ARIA/roles/*/index.md pages.

you'll note, they're definitely in draft state: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/roles/menuitem_role

**Comment by wbamberg** [comment]
@tannerdolby , unless/until we have consensus for removing `{{draft}}`, could you are Estelle says undo this change for the /Web/Accessibility/ARIA/roles/*/index.md pages? Then I would be happy to merge this.

It's a big improvement anyway to remove this banner from a lot of these pages.

> exception is en-US/docs/Learn/Common_questions/HTML_features_for_accessibility. Information is incomplete and not fully correct, so please keep draft on that page as well.

Can we file an issue for this instead? Lots of our pages are incomplete and not fully correct, but we should handle this by filing bugs, where we can track them.

**Comment by tannerdolby** [comment]
@wbamberg Ok great. Yeah, I can do what Estelle mentioned and undo this change for `/Web/Accessibility/ARIA/roles/*/index.md` pages.

> Can we file an issue for this instead? Lots of our pages are incomplete and not fully correct, but we should handle this by filing bugs, where we can track them.

Yeah, sure thing. I will create a new issue to keep track of this.

**Comment by Elchi3** [comment]
What's the next step here? I think we should close this PR and come back to draft pages in smaller chunks? I guess we could agree to remove {{draft}} from some pages but maybe not from everything at once?

**Comment by wbamberg** [comment]
> What's the next step here? I think we should close this PR and come back to draft pages in smaller chunks? I guess we could agree to remove {{draft}} from some pages but maybe not from everything at once?

I think as noted in https://github.com/mdn/content/pull/10504#issuecomment-971811094 we should:

* undo this change for the accessibility pages and then merge this PR
* file an issue for en-US/docs/Learn/Common_questions/HTML_features_for_accessibility

**Comment by Elchi3** [comment]
@tannerdolby can you undo the changes for the accessibility pages and resolve the conflicts. I bet we could get this in then :)

**Comment by tannerdolby** [comment]
@Elchi3 yeah I can do that! :) later today or tomorrow I will resolve conflicts and undo changes to /web/accessibility/ pages.

**Review by ddbeck — APPROVED** [review]
Thank you! 🚀 🎉

**Comment by tannerdolby** [comment]
You're welcome! Thanks again for everyones help to get this merged 🎉

**Pull request merged**
