### PR TITLE
webauthn links corrected

### PR DESCRIPTION
**Pull request by jpstotz**
The webauthn links were to the old working version on https://w3c.github.io/webauthn where you can now find the current level 3 document. 
I have corrected those links to point to the official spec at https://www.w3.org/TR/webauthn-1

One link may be still wrong, but I wasn't able to find where the link is defined shown in the `Specifications` section: https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#specifications

`Web Authentication: An API for accessing Public Key Credentials Level 1` pointing to https://w3c.github.io/webauthn/ should also be changed to https://www.w3.org/TR/webauthn-1 and a second link should be added for https://www.w3.org/TR/webauthn-2

### CODE REVIEW

**Comment by peterbe** [comment]
@sideshowbarker this might be your wheelhouse?

**Comment by sideshowbarker** [comment]
> The webauthn links were to the old working version on [w3c.github.io/webauthn](https://w3c.github.io/webauthn)

That is not the “old working version” — instead that is the current version. It’s the version that browser implementors use when they write code for implementing the spec in their browsers. Therefore, it’s also the version that web developers should read.

>  I have corrected those links to point to the official spec at [w3.org/TR/webauthn-1](https://www.w3.org/TR/webauthn-1)

That’s not the official spec — that’s an obsolete version that’s now more than two years out of date. Browser implementors completely ignore that version, so web developers should as well.

We very intentionally have been following a practice of not referencing obsolete versions of specs.

The current, actively-maintained versions of specs, with few exceptions, are the ones at w3c.github.io URLs. So that’s why we have been following a practice of intentionally referencing the w3c.github.io versions.

For those reasons, the existing https://w3c.github.io/webauthn/ spec URLs in these articles are correct as-is and should not be changed. So I’m going ahead and closing this PR.

**Comment by jpstotz** [comment]
@sideshowbarker I wasn't aware that the level3 draft is linked intentionally. But what you write does not really match what is currently shown e.g. on https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#specifications

There only WebAuthn level1 is mentioned, Level 2 is completely missing and the working draft of Level 3 is also missing.

**Comment by sideshowbarker** [comment]
>  I wasn't aware that the level3 draft is linked intentionally.

The fact that the current spec happens to have “level3” label isn’t the reason we’re linking to it. The label is arbitrary and really has no meaning in practice. We’re linking to the current spec simply because it’s the current spec — as opposed to being some other obsolete, out-of-date version.

>  But what you write does not really match what is currently shown e.g. on [developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#specifications](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#specifications)
> 
> There only WebAuthn level1 is mentioned,

ah — that’s just because the tooling we use to assign a title to the https://w3c.github.io/webauthn spec URL hasn’t been updated and is unfortunately assigning it the wrong label. But we will be fixing that very soon.

> Level 2 is completely missing and the working draft of Level 3 is also missing.

Yeah, it’s intentional that we don’t link on any URLs except the https://w3c.github.io/webauthn URL

**Pull request closed without merging**
