### PR TITLE
Replacing `ƒ` with `function` in code sections

### PR DESCRIPTION
**Pull request by yarusome**
### Description

This PR replaces all (~30) occurrences of `ƒ` in code sections with `function`.

### Motivation

`function` is more intuitive than `ƒ` for learners, and the vast majority of code sections on MDN pages also use `function` instead of `ƒ`.

### CODE REVIEW

**Comment by Josh-Cena** [comment]
This is the verbatim console output of Chrome. Changing it to `function` makes it resemble no browser. We'd rather stick with at least one browser's output format.

**Comment by yarusome** [comment]
@Josh-Cena So for consistency, could I copy the outputs from Firefox console? Also, the line in the "Destructuring assignment" where `ƒ` occurrs is *definitely not* verbatimly copied from Chrome console since the variable `a` should also be logged as `undefined`.

**Comment by Josh-Cena** [comment]
> the variable `a` should also be logged as `undefined`.

It is logged as `undefined` and included in the comment. It's directly preceding the `ƒ`.

> could I copy the outputs from Firefox console

FWIW, I have a slight preference for Chrome's output, because it makes it look less like actual JavaScript code. In addition, the formatting of the internal slots are nicer in Chrome, and it's mentioned in the prototype chain as well:

> **Note:** The Chrome console uses `[[Prototype]]` to denote the object's prototype, following the spec's terms; Firefox uses `<prototype>`. For consistency we will use `[[Prototype]]`.

**Comment by yarusome** [comment]
On Firefox:
```js
const {a, toFixed} = 1;
console.log(a, toFixed);
```
logs
```
undefined
undefined function toFixed()
```
And
```js
const {toString} = 1;
console.log(toString);
```
logs
```
undefined
function toString()
```
The former logging has two `undefined`, though.

**Comment by Josh-Cena** [comment]
Are you sure? Here's the output:

image

The second `undefined` is the return value of the statement block, not the logged value. The first `undefined` is the logged value.

> If Chrome's output format is preferred, could this be explicitly mentioned in the contribution guide?

This is a weak guide, and most people choose to not care anyway. As a general rule, formatting changes rather than content improvements are more likely to be picked on, although you do have a case about why `function` may be more preferable (although I don't see that very clearly, since this is the console output anyway, not real code fragment). I'd say that should these changes be part of a bigger content improvement, some of them may be accepted (e.g. the destructuring one), but we would not encourage a PR that purely makes such copy edits.

**Pull request closed without merging**
