### PR TITLE
Update convert to stream code example

### PR DESCRIPTION
**Pull request by mehran-anzx**
The current example misses the last chunk, updated it to enqueue all chunk even the last chunk.

### Description

The current example misses the last chunk, updated it to enqueue all chunk even the last chunk.

### Motivation

Fix incorrect example.

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
The last chunk is usually yielded as an intermediate result, and the done value is usually for other purposes (e.g. how many chunks were yielded, aggregate statistics, how the reader should continue, etc.) Do you have examples of iterators actually yielding the chunk as the `done: true` value??

**Comment by mehran-anzx** [comment]
> The last chunk is usually yielded as an intermediate result, and the done value is usually for other purposes (e.g. how many chunks were yielded, aggregate statistics, how the reader should continue, etc.) Do you have examples of iterators actually yielding the chunk as the `done: true` value??

I tried the example and didn't work until I made the change, because in my case, `{done: true}` come along with the last chunk and with the original example, the `enqueue` of the last chunk would have not been reached to be executed.

**Comment by Josh-Cena** [comment]
What's the iterator you are converting from? Is that from a library?

**Comment by mehran-anzx** [comment]
> What's the iterator you are converting from? Is that from a library?

It is sourced from an gPRC stream generated using `createPromiseClient` in `@connectrpc/connect` lib. Though, my change should work even when the  `{done: true}` being yielded separately after the last chunk.

**Review by Josh-Cena — APPROVED** [review]
I see. I'm fine to recommend this by default, but what about adding a warning saying "the value when `done: true` may or may not be a chunk and you should enqueue it based on your knowledge of the API"?

**Comment by mehran-anzx** [comment]
I don't see any harm in adding that extra comment though my suggested change should work regardless.

**Comment by mehran-anzx** [comment]
I don't see any harm in adding that extra comment though my suggested change should work regardless.

**Comment by Josh-Cena** [comment]
Added a warning. What do you think?

**Comment by mehran-anzx** [comment]
Hey @Josh-Cena , do you know what is the next step for this PR?

**Comment by Josh-Cena** [comment]
As long as my change looks good to you, I can merge it.

**Comment by Josh-Cena** [comment]
Great, thanks :)

**Pull request merged**
