### PR TITLE
Add sidebars to HTML guide pages

### PR DESCRIPTION
**Pull request by OnkarRuikar**

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
Thanks for your PR!

Isn't the goal that we have one sidebar macro per domain?
Why isn't this `{{HTMLSidebar}}`?

**Comment by OnkarRuikar** [comment]
@Elchi3 good point! I've used `{{HTMLSidebar}}` now.

I think these pages need to be under `/en-US/docs/Web/HTML/` along with other HTML guide pages:
guidepages



At the moment these pages are not listed in `{{HTMLSidebar}}` macro because they are under guide hierarchy:
`/en-US/docs/Web/Guide/HTML/`.

**Comment by Elchi3** [comment]
> At the moment these pages are not listed in `{{HTMLSidebar}}` macro because they are under guide hierarchy:
> `/en-US/docs/Web/Guide/HTML/`.

ahh I didn't even realize this was a different hierarchy. Should we move the pages to `HTML/`? The XHTML page one looks like it should be in `Glossary/`.

**Comment by OnkarRuikar** [comment]
> Should we move the pages to `HTML/`? The XHTML page one looks like it should be in `Glossary/`.

- I've deleted the XHTML page, and updated exiting `Glossary/XHTML` page with extra info from it.
-  Other two pages have been moved to `Web/HTML` hierarchy.

**Review by Elchi3 — APPROVED** [review]
Thanks for going the extra miles to fix this properly! 👍

**Pull request merged**
