### PR TITLE
Fixed ugly markdown

### PR DESCRIPTION
**Pull request by okyanusoz**
> What was wrong/why is this fix needed? (quick summary only)

In https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#avoiding_user_agent_detection, there was some broken markdown that caused text to look like code. This PR fixes the issue.

### CODE REVIEW

**Comment by okyanusoz** [comment]
Fixing tabs...

**Review by Ryuno-Ki — APPROVED** [review]
I compared the before and after carefully.

**Comment by Ryuno-Ki** [comment]
@okyanusoz Thank you for catching this and taking the time to write a fix.
Congratulations for landing your first Pull Request with MDN!
Welcome aboard :partying_face:

**Comment by okyanusoz** [comment]
Thanks!

**Pull request merged**
