### PR TITLE
Fix incorrect comment in Object.create() doc

### LINKED ISSUE #5449: Issue with "Object.create()": (short summary here please)
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create

#### What information was incorrect, unhelpful, or incomplete?
Incorrect comment below:
Object.setPrototypeOf(ocn, Object); // set new object's prototype to the standard-object
What is incorrect :
Object.setPrototypeOf(ocn, Object); // set new object's prototype to the Object 'Function'

#### Specific section or headline?
Sub Section : Some NON-solutions
Example number 3, correction in comment for more clarity for readers.

#### What did you expect to see?
Object.setPrototypeOf(ocn, Object); // set new object's prototype to the Object 'Function'

#### Did you test this? If so, how?
As per the mdn documentation : The Object.setPrototypeOf() method sets the prototype (i.e., the internal [[Prototype]] property) of a specified object to **another object** or null. Here 'Object' which is passed as the second argument is a function.Hence it would not work.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/create`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/create/index.html
* Last commit: https://github.com/mdn/content/commit/3c394e62835ef7b443fb5208343ecba892bbf6d5
* Document last modified: 2021-05-26T11:36:38.000Z

</details>

### PR DESCRIPTION
**Pull request by sideshowbarker**
Fixes https://github.com/mdn/content/issues/5449

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
I'm finding this part of the docs really hard going: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#custom_and_null_objects. It seems like it is discussing a case where we try to create an empty object by doing `ocn = Object.create( null );` , and then this isn't behaving like an object in various ways, and various hacky ways are attempted to fix it.

Is there a use case for `ocn = Object.create( null );`, or could we just instead say, don't do this?

**Comment by sideshowbarker** [comment]
> Is there a use case for `ocn = Object.create( null );`, or could we just instead say, don't do this?

There are definitely legitimate use cases for `Object.create(null)`.

Maybe the most convincing evidence is https://github.com/search?l=JavaScript&q=Object.create%28null%29&type=code, which shows literally millions of results for instances of it in code from GitHub repos.

But for an example close to home, see: https://github.com/mdn/browser-compat-data/blob/a2010d4a68f38db9b0f667945f0e9989b1c26843/test/utils.js#L6-L16

And for some examples only a little bit further from home, see https://github.com/w3c/mdn-spec-links/blob/master/.browser-compat-data-process.js#L426 and https://github.com/w3c/mdn-spec-links/blob/master/.browser-compat-data-process.js#L32 and the other places in that script.

And while I can imagine some better JavaScript programmer than I am could figure out a way to rewrite that code (my mdn-spec-links code) so it doesn’t need `Object.create(null)`, I can say with certainty that code as currently written will break if I were to just replace the `Object.create(null)` calls with `Object.create({})` or such, rather than `Object.create(null)`.

For further evidence, see https://stackoverflow.com/questions/20803224/use-cases-for-object-createnull/20804241#20804241:
> You can use such an object for a key-value map. Without the prototype chain, you can be sure that things like `.toString()` do not unwittingly exist on the object. That means you can incautiously access properties on it, and you can use the `in` operator instead of `Object.prototype.hasOwnProperty.call`.

…and see https://stackoverflow.com/questions/32262809/is-it-bad-practice-to-use-object-createnull-versus/46395899#46395899:

> if you are using `{}` as a dictionary, and your keys are unpredictable (e.g., input from a user), then you should really opt for `Object.create(null)` or `Map` since its conceivable that assigning a value to a certain key using the `=` operator (i.e., the object's *setter*) may silently fail because its trying to modify a read-only property in the prototype chain, for example on the `__proto__` property

https://stackoverflow.com/questions/24678660/object-createnull-in-javascript-creating-new-top-level-objects/24679007#24679007:

> A good use case I can think about is when you actually need an absolutely memberless object, e.g., to perform a safe iteration… but with this approach you ensure you don't have ANY prototype and thus every property will be own by default. So you can safely treat the object as a hash and iterate it as I told, holding only true data.

**Comment by sideshowbarker** [comment]
>> Is there a use case for `ocn = Object.create( null );`, or could we just instead say, don't do this?
>
> But for an example close to home, see: [mdn/browser-compat-data@`a2010d4`/test/utils.js#L6-L16](https://github.com/mdn/browser-compat-data/blob/a2010d4a68f38db9b0f667945f0e9989b1c26843/test/utils.js#L6-L16)

For some examples even closer to home, see https://github.com/mdn/content/search?q=Object.create%28null%29 — and see the first row of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#objects_vs._maps —

> An <code>Object</code> has a prototype, so it contains default keys that could collide with your own keys if you're not careful.</p>
>
> <strong>Note:</strong> As of ES5, this can be bypassed by using  <a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create"><code>Object.create(null)</code></a>, but this is seldom done.

**Comment by sideshowbarker** [comment]
@wbamberg This seems to be waiting on response from you to https://github.com/mdn/content/pull/5493#issuecomment-852763810 and https://github.com/mdn/content/pull/5493#issuecomment-852754478.

**Review by wbamberg — APPROVED** [review]
👍

**Pull request merged**
