### PR TITLE
Removed link which no longer exists, Fixes #2533

### LINKED ISSUE #2533: Issue with "Advanced text formatting": affirmations for positive thinking website no longer exists
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting

The "Active Learning: Who Said That?" exercise uses a link to http://www.affirmationsforpositivethinking.com, which no longer exists and is for sale.  

(This link isn't vital for the exercise, just that it might link to something inappropriate later on.)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/advanced_text_formatting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.html
* Last commit: https://github.com/mdn/content/commit/201f6cfd272aa6d7d0bc8e9fa53cbf5fbe5abb87
* Document last modified: 2021-02-13T11:21:31.000Z

</details>

### PR DESCRIPTION
**Pull request by CreaTorAlexander**
#2533 Removed link which no longer exists

### CODE REVIEW

**Comment by avivmu** [comment]
Look at the page, a few lines after your change the exercise asks to cite this link, so it's better to leave it, but indicate that the link is not real and its sole purpose is for the exercise

**Comment by hamishwillee** [comment]
As @avivmu says, you can't delete the link because it is part of the example. It could be replaced with almost any other link though (or explicitly a fake link)

**Comment by rachelandrew** [comment]
Yes the example would need changing to reference something unlikely to go away (such as pages on MDN), or use 'example.com' here as that domain is maintained for that purpose.

**Comment by CreaTorAlexander** [comment]
Okay, I will update it

**Review by chrisdavidmills — APPROVED** [review]
LGTM; thanks for the updates.

**Pull request merged**
