### PR TITLE
Remove non-standard error properties in examples

### PR DESCRIPTION
**Pull request by i4pg**
### Description

Just a small typo in referencing the error

### Motivation

by referencing the correct line caused the error, Hope that's could actually help readers

### CODE REVIEW

**Review by Josh-Cena — APPROVED** [review]
Thanks! Because `stack` is a non-standard property, I've decided to just omit what is actually displayed. I've also removed references to other non-standard, Firefox-specific properties. Thanks for bringing this up :)

**Comment by i4pg** [comment]
> Thanks! Because `stack` is a non-standard property, I've decided to just omit what is actually displayed. I've also removed references to other non-standard, Firefox-specific properties. Thanks for bringing this up :)

Thank you, @Josh-Cena. I noticed that only SyntaxError examples use `console.error` instead of `console.log`. It might be better to consider using `console.error` as the standard for all Error instances. I'd be happy to work on that. Thanks!

**Comment by Josh-Cena** [comment]
I suggest using `console.log` here, because we are not actually giving out indications of exceptions, just information about an `Error` object. I would happily merge a PR if you could change that `console.error` to `log`—it was an oversight of mine.

**Comment by i4pg** [comment]
> 

Indeed it's information about `Error` object, Just submitted a new PR. Thanks for giving me this chance

**Pull request merged**
