### PR TITLE
Issue/12834 Fix Content Negotiation Blurry Text In Diagram

### LINKED ISSUE #12834: Issue with "Content negotiation": (Blurry text in diagrams)
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation

#### What information was incorrect, unhelpful, or incomplete?

The diagrams have difficult to read text.

#### Specific section or headline?
Check the [Server-driven content negotiation section](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation#server-driven_content_negotiation). It's diagram contain text difficult to read. Currently, this is the image: Server-driven content negotiation with blurry text.

#### What did you expect to see?
I was expecting to be able to read the text on those diagrams easily.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/content_negotiation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/content_negotiation/index.md
* Last commit: https://github.com/mdn/content/commit/b025303a06f3e69f06976f88681eb62d9f3d7814
* Document last modified: 2021-11-03T11:44:58.000Z

</details>

### PR DESCRIPTION
**Pull request by hh-shiung**
#### Summary

Redrew diagram for Content Negotiation to fix blurry text with previous image.

#### Motivation

The image clarity should be an improvement over the old image. Bad images strains eyeballs.

#### Related issues

Fixes #12834 

#### Metadata

This PR
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by teoli2003 — CHANGES_REQUESTED** [review]
The new image looks good, but you haved replaced httpnego.png instead of httpnegoserver.png. If you fix this, we are good to go.

**Comment by hh-shiung** [comment]
Thanks for the catch!

Did some fiddling to clean up git history, but now it should be one commit for the correct image.

**Review by teoli2003 — APPROVED** [review]
👍

**Review by teoli2003 — CHANGES_REQUESTED** [review]
According to the test, you need to compress the image more:

image

(I always forget about this!)

**Comment by hh-shiung** [comment]
It was my mistake, I skipped reading the image protocol.

Updated with a compressed image that should passed tests.

**Review by teoli2003 — APPROVED** [review]

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:

**Pull request merged**
