### PR TITLE
Update the Express Tutorial - MongoDB Atlas - "Choose a connection method"

### PR DESCRIPTION
**Pull request by blobtub**
### Description

Updated "choose a connection method" step to reflect MongoDB Atlas UI.
Bringing this part of the tutorial up to date (Part 3 - Setting up the MongoDB database - step 11), because the MongoDB Atlas UI appears to have changed.

### Motivation

Helps readers by showing an up-to-date view of the MongoDB Atlas service as they are following the tutorial.

### Additional details

N/A

### Related issues and pull requests

Relates to previous PR #15635

### CODE REVIEW

**Comment by hamishwillee** [comment]
THanks - I hope to try this out on Monday or Tuesday.

**Comment by hamishwillee** [comment]
Thanks @blobtub . I just tested this from a clean cluster and I get a different connection screen and URL. You can see these in #22914

I'm not sure why yours would be different!

**Comment by blobtub** [comment]
Thanks for testing @hamishwillee.  I have commented on #22914 re the simplified connection URL.

**Comment by hamishwillee** [comment]
Thanks for this. Closing, as work now done (with follow up PR to fix the issue you identify above)

**Pull request closed without merging**
