### PR TITLE
Fix issue 13208: document response body access exceptions

### LINKED ISSUE #12387: Issue with "AbortController": (missing info on behavior of .text() or .json() or other body promise)
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AbortController

#### What information was incorrect, unhelpful, or incomplete?
This was missing information about whether calling the `controller.abort()` function would cause the promise returned from `.json()`, `.text()`, (or any of the body-downloading functions on the resolved `Request` object) to fail with `Uncaught DOMException: The user aborted a request.` (Chrome's behavior), From experimentation, it seemed that calling `controller.abort()` would cancel either the request promise or the body promise, so I think that detail should be added to save others the trouble.

#### Specific section or headline?
2 found pages: <https://developer.mozilla.org/en-US/docs/Web/API/AbortController> and <https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal>
The section was the Note under the examples on these pages

#### What did you expect to see?
Details on the promise abortions returned from `Response.prototype.text()`, or `.json()`, or others.

#### Did you test this? If so, how?
Yep, tested chrome console interaction when downloading a large file with Slow 3G network throttling. Test code:
```
var ctrl = new AbortController();
var res = await fetch('https://www.ledger-cli.org/3.0/doc/ledger3.pdf', { signal: ctrl.signal });
console.log('response received');
var data = await res.text();
console.log('text downloaded');

// ^ Executed the above, then after "response received" and before "text downloaded", manually executed:
ctrl.abort();

// Resultant behavior is that "text downloaded" never was displayed, and we received this:
// (x) Uncaught DOMException: The user aborted a request.
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/abortcontroller`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AbortController
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/abortcontroller/index.md
* Last commit: https://github.com/mdn/content/commit/e89a324e54cfc261f00ae08052d63c697cd99ba2
* Document last modified: 2022-01-12T16:54:36.000Z

</details>

### LINKED ISSUE #13208: Issue with "Response.json()": Possible exceptions not documented
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/json

#### What information was incorrect, unhelpful, or incomplete?
This function can raise exceptions, but these are not documented. Try using it on a response that is not actually JSON, e.g.

#### Specific section or headline?
Exceptions

#### What did you expect to see?
The list of possible exceptions and their causes. See the [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions) documentation for an example of a function that documents its exceptions well.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/response/json`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/json
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/response/json/index.md
* Last commit: https://github.com/mdn/content/commit/93ae23dec42bba9d71d6f1ed45668d8d26847e9c
* Document last modified: 2022-02-18T09:26:54.000Z

</details>

### LINKED ISSUE #24466: `Response.text()` can throw a `TypeError`
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Response/text

### What specific section or headline is this issue about?

Return value

### What information was incorrect, unhelpful, or incomplete?

It says that it returns "A Promise that resolves with a String."
But in reality it's possible for this promise to reject with a TypeError.

### What did you expect to see?

Mentioning of the rejected promise similar to what's shown at https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions

### Do you have any supporting links, references, or citations?

https://fetch.spec.whatwg.org/#concept-body-consume-body mentions:
> If object is [unusable](https://fetch.spec.whatwg.org/#body-unusable), then return [a promise rejected with](https://webidl.spec.whatwg.org/#a-promise-rejected-with) a [TypeError](https://webidl.spec.whatwg.org/#exceptiondef-typeerror).

which is called by https://fetch.spec.whatwg.org/#dom-body-text

### Do you have anything more you want to share?

- [`Response.arrayBuffer()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/arrayBuffer)
- [`Response.blob()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/blob)
- [`Response.formData()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/formData)
- [`Response.json()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/json)
- [`Response.text()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/text)

all refer to [`consume body`](https://fetch.spec.whatwg.org/#concept-body-consume-body) in the spec, and would benefit from similar documentation.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/response/text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/response/text/index.md
* Last commit: https://github.com/mdn/content/commit/16e398809d62247dbadc89ff4024a0ffa4781f0e
* Document last modified: 2022-09-13T06:27:50.000Z

</details>

### PR DESCRIPTION
**Pull request by wbamberg**
Fixes https://github.com/mdn/content/issues/13208.
Fixes https://github.com/mdn/content/issues/24466 and closes https://github.com/mdn/content/pull/31707.
Fixes https://github.com/mdn/content/issues/12387.

### CODE REVIEW

**Comment by Josh-Cena** [comment]
How does this relate to https://github.com/mdn/content/pull/31707 and https://github.com/mdn/content/issues/24466?

**Comment by wbamberg** [comment]
> How does this relate to #31707 and #24466?

It fixes https://github.com/mdn/content/issues/24466 and closes https://github.com/mdn/content/pull/31707.

**Comment by wbamberg** [comment]
Although there might be some additional exceptions, given https://stackoverflow.com/questions/49785911/is-it-possible-to-cause-a-fetchs-text-function-to-throw/49786130#49786130 ?

**Comment by sideshowbarker** [comment]
> Although there might be some additional exceptions, given [stackoverflow.com/questions/49785911/is-it-possible-to-cause-a-fetchs-text-function-to-throw/49786130](https://stackoverflow.com/questions/49785911/is-it-possible-to-cause-a-fetchs-text-function-to-throw/49786130#49786130) .

I see that says this:

> text may throw
>
>  - if its request is aborted between the completion and the consumption

As far as I can see, that wouldn’t at all be a case of `text()` throwing — because `text()` operates on the response body, after the browser has has successfully made the request, and after the browser has received the response. Calling `text()` doesn’t cause the browser to initiate a new request.

> if the Content-Encoding response header doesn't match the corresponding entity-body

OK, that one seems basically right.

It appears to be based on https://github.com/whatwg/fetch/issues/657 and https://github.com/whatwg/fetch/pull/710, with related tests in http://wpt.live/fetch/content-encoding — for example, http://wpt.live/fetch/content-encoding/gzip/bad-gzip-body.any.html

There are open browser bugs for it at https://bugs.webkit.org/show_bug.cgi?id=184882 and https://bugzilla.mozilla.org/show_bug.cgi?id=1456105 — but it’s not clear to me what else needs to be done on those, since the tests I tried all passed.

Anyway, the relevant exception isn’t specific to `text()`; it also gets thrown for any of the Body methods:  `arrayBuffer()`, `blob()`, `formData()`, `json()`, too.

As far as what it should say, I think it should just be:

```markdown
- {{jsxref("TypeError")}}
  - A `Content-Encoding` decoding failure occurred.
```
…that is, rather than something like what that SO answer says — _“if the Content-Encoding response header doesn't match the corresponding entity-body”_, which is too specific to cover all the possible decoding-failure cases.

**Review by sideshowbarker — APPROVED** [review]
This looks great to me. I don’t think it needs to be blocked on adding anything for the additional case I commented about in https://github.com/mdn/content/pull/34576#issuecomment-2205034664 — I think that could be handled in follow-up PR if you wanted. Or if you wanted to add it here instead, I’d be happy to review it here too.

**Comment by Josh-Cena** [comment]
> because `text()` operates on the response body, after the browser has has successfully made the request, and after the browser has received the response. Calling `text()` doesn’t cause the browser to initiate a new request.

That is talking about `abort()` being called after the request promise has fulfilled but before the `text()` promise has fulfilled, I think. See also https://github.com/mdn/content/issues/12387

**Comment by sideshowbarker** [comment]
> That is talking about `abort()` being called after the request promise has fulfilled but before the `text()` promise has fulfilled, I think. See also #12387

aha, thanks — so that would also apply to all other Body methods too. I guess something like this:

```markdown
- {{jsxref("DOMException")}}
  - The [AbortController: abort() method](/en-US/docs/Web/API/AbortController/abort) is called
    before the promise returned by the method fulfills. 
```

**Comment by wbamberg** [comment]
Yes, I can confirm that with code like this in the console:

```js
async function get() {
    const controller = new AbortController();
    const url = "https://httpbin.org/get";
    const req = new Request(url, {
        signal: controller.signal
    })
    const resp = await fetch(req);
    controller.abort();
    console.log("aborted...")
    const text = await resp.text();
    console.log(text);
}
```

**Comment by Josh-Cena** [comment]
OK, maybe we should fix one more issue in this PR then ^^ (Also needs one-sentence addition to `AbortController` but that should be it)

**Comment by wbamberg** [comment]
I can reproduce the content decoding error with code like this:

```js
async function f() {
	try {
		const request = new Request(
			"https://httpbin.org/response-headers?Content-Encoding=gzip"
		);
		const resp = await fetch(request);
		console.log(resp);
		console.log(`Content-Encoding:${resp.headers.get("content-encoding")}`); // Content-Encoding:gzip
		const text = await resp.arrayBuffer(); // Throws here
		console.log(text);
	} catch (e) {
		console.log(e); // TypeError: Decoding failed.
	}
}
```

**Comment by wbamberg** [comment]
OK, I added 2 new exceptions to each of these methods:

```
- {{domxref("DOMException")}} `AbortError`
  - : The request was [aborted](/en-US/docs/Web/API/Fetch_API/Using_Fetch#canceling_a_request).
- {{jsxref("TypeError")}}
  - : There is an error decoding the body content (for example, because the {{httpheader("Content-Encoding")}} header is incorrect).
```

...so I chose a slightly different text from suggested, mostly because I thought "`Content-Encoding` decoding" sounded weird.

For https://github.com/mdn/content/issues/12387 I added a bit in "Using Fetch" about this, and also updated https://developer.mozilla.org/en-US/docs/Web/API/AbortController and https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal. I don't like documenting this in the last two places, for a couple of reasons: (1) that is in examples, which should not introduce new concepts, ever, and (2) this is an aspect of the Fetch API, not the AbortController API. But I'm not going to try to untangle that in this PR.

**Pull request merged**
