### PR TITLE
docs: omit deprecation information

### LINKED ISSUE #32449: slope is not deprecated
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/slope

### What specific section or headline is this issue about?

deprecated header

### What information was incorrect, unhelpful, or incomplete?

the slope attribute is listed as useful for font-face, but never supported and deprecated.

`slope` is an attribute of the `<feComponentTransfer>` element's children: `<feFuncR>`, etc., and is supported, not deprecated, as far as I can tell.

### What did you expect to see?

the slope page being up to date, and about it's use within `<feComponentTransfer>`, not font-face.

### Do you have any supporting links, references, or citations?

see https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComponentTransfer. It's also in the css filter effects pages.

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/attribute/slope`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/slope
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/slope/index.md
* Last commit: https://github.com/mdn/content/commit/b4f998244660723175f8e06b5d77f68cfb1d1f1a
* Document last modified: 2023-03-06T23:38:10.000Z

</details>

### PR DESCRIPTION
**Pull request by CBID2**
### Description
The `<slope>`element is not deprecated and works with the `<feComponentTransfer>`attribute, not the `<font -face>` attribute. 

### Motivation
By making the changes, developers will receive accurate information about this element. 

### Additional details

I'm not sure how to omit the information shown in the screenshot below:
deprecated browser chart

### Related issues and pull requests

Fixes #32449

### CODE REVIEW

**Comment by Rumyra** [comment]
Hey @CBID2 - before I add anything I'm curious where you found the information that the `scope` attribute works with the `<feComponentTransfer>` element - as from looking at the spec it does seem deprecated - thanks!

**Comment by CBID2** [comment]
> feComponentTransfer

Here @Rumyra: https://www.w3.org/TR/SVG11/filters.html#feComponentTransferElement

**Comment by skyclouds2001** [comment]
but this standard is on 2011, maybe this has been outdated

**Comment by skyclouds2001** [comment]
> I'm not sure how to omit the information shown in the screenshot below:

the bcd is at https://github.com/mdn/browser-compat-data/blob/main/svg/elements/font-face.json#L687

**Comment by CBID2** [comment]
> but this standard is on 2011, this has been outdated
> 
> the browser compat data also proves that
> 
> the newest versThe newest version is at https://svgwg.org/svg2-draft/

Hey. Thanks for the link. I can not find the information on the slope attribute in there. Can you point it out?

**Comment by estelle** [comment]
> > feComponentTransfer
> 
> Here @Rumyra: https://www.w3.org/TR/SVG11/filters.html#feComponentTransferElement

That link indicates the attributes for `<feComponentTransfer>` are as follows:
[core attributes](https://www.w3.org/TR/SVG11/intro.html#TermCoreAttributes) — [‘id’](https://www.w3.org/TR/SVG11/struct.html#IDAttribute), [‘xml:base’](https://www.w3.org/TR/SVG11/struct.html#XMLBaseAttribute), [‘xml:lang’](https://www.w3.org/TR/SVG11/struct.html#XMLLangAttribute), [‘xml:space’](https://www.w3.org/TR/SVG11/struct.html#XMLSpaceAttribute)
[presentation attributes](https://www.w3.org/TR/SVG11/intro.html#TermPresentationAttribute) — [‘alignment-baseline’](https://www.w3.org/TR/SVG11/text.html#AlignmentBaselineProperty), [‘baseline-shift’](https://www.w3.org/TR/SVG11/text.html#BaselineShiftProperty), [‘clip’](https://www.w3.org/TR/SVG11/masking.html#ClipProperty), [‘clip-path’](https://www.w3.org/TR/SVG11/masking.html#ClipPathProperty), [‘clip-rule’](https://www.w3.org/TR/SVG11/masking.html#ClipRuleProperty), [‘color’](https://www.w3.org/TR/SVG11/color.html#ColorProperty), [‘color-interpolation’](https://www.w3.org/TR/SVG11/painting.html#ColorInterpolationProperty), [‘color-interpolation-filters’](https://www.w3.org/TR/SVG11/painting.html#ColorInterpolationFiltersProperty), [‘color-profile’](https://www.w3.org/TR/SVG11/color.html#ColorProfileProperty), [‘color-rendering’](https://www.w3.org/TR/SVG11/painting.html#ColorRenderingProperty), [‘cursor’](https://www.w3.org/TR/SVG11/interact.html#CursorProperty), [‘direction’](https://www.w3.org/TR/SVG11/text.html#DirectionProperty), [‘display’](https://www.w3.org/TR/SVG11/painting.html#DisplayProperty), [‘dominant-baseline’](https://www.w3.org/TR/SVG11/text.html#DominantBaselineProperty), [‘enable-background’](https://www.w3.org/TR/SVG11/filters.html#EnableBackgroundProperty), [‘fill’](https://www.w3.org/TR/SVG11/painting.html#FillProperty), [‘fill-opacity’](https://www.w3.org/TR/SVG11/painting.html#FillOpacityProperty), [‘fill-rule’](https://www.w3.org/TR/SVG11/painting.html#FillRuleProperty), [‘filter’](https://www.w3.org/TR/SVG11/filters.html#FilterProperty), [‘flood-color’](https://www.w3.org/TR/SVG11/filters.html#FloodColorProperty), [‘flood-opacity’](https://www.w3.org/TR/SVG11/filters.html#FloodOpacityProperty), [‘font-family’](https://www.w3.org/TR/SVG11/text.html#FontFamilyProperty), [‘font-size’](https://www.w3.org/TR/SVG11/text.html#FontSizeProperty), [‘font-size-adjust’](https://www.w3.org/TR/SVG11/text.html#FontSizeAdjustProperty), [‘font-stretch’](https://www.w3.org/TR/SVG11/text.html#FontStretchProperty), [‘font-style’](https://www.w3.org/TR/SVG11/text.html#FontStyleProperty), [‘font-variant’](https://www.w3.org/TR/SVG11/text.html#FontVariantProperty), [‘font-weight’](https://www.w3.org/TR/SVG11/text.html#FontWeightProperty), [‘glyph-orientation-horizontal’](https://www.w3.org/TR/SVG11/text.html#GlyphOrientationHorizontalProperty), [‘glyph-orientation-vertical’](https://www.w3.org/TR/SVG11/text.html#GlyphOrientationVerticalProperty), [‘image-rendering’](https://www.w3.org/TR/SVG11/painting.html#ImageRenderingProperty), [‘kerning’](https://www.w3.org/TR/SVG11/text.html#KerningProperty), [‘letter-spacing’](https://www.w3.org/TR/SVG11/text.html#LetterSpacingProperty), [‘lighting-color’](https://www.w3.org/TR/SVG11/filters.html#LightingColorProperty), [‘marker-end’](https://www.w3.org/TR/SVG11/painting.html#MarkerEndProperty), [‘marker-mid’](https://www.w3.org/TR/SVG11/painting.html#MarkerMidProperty), [‘marker-start’](https://www.w3.org/TR/SVG11/painting.html#MarkerStartProperty), [‘mask’](https://www.w3.org/TR/SVG11/masking.html#MaskProperty), [‘opacity’](https://www.w3.org/TR/SVG11/masking.html#OpacityProperty), [‘overflow’](https://www.w3.org/TR/SVG11/masking.html#OverflowProperty), [‘pointer-events’](https://www.w3.org/TR/SVG11/interact.html#PointerEventsProperty), [‘shape-rendering’](https://www.w3.org/TR/SVG11/painting.html#ShapeRenderingProperty), [‘stop-color’](https://www.w3.org/TR/SVG11/pservers.html#StopColorProperty), [‘stop-opacity’](https://www.w3.org/TR/SVG11/pservers.html#StopOpacityProperty), [‘stroke’](https://www.w3.org/TR/SVG11/painting.html#StrokeProperty), [‘stroke-dasharray’](https://www.w3.org/TR/SVG11/painting.html#StrokeDasharrayProperty), [‘stroke-dashoffset’](https://www.w3.org/TR/SVG11/painting.html#StrokeDashoffsetProperty), [‘stroke-linecap’](https://www.w3.org/TR/SVG11/painting.html#StrokeLinecapProperty), [‘stroke-linejoin’](https://www.w3.org/TR/SVG11/painting.html#StrokeLinejoinProperty), [‘stroke-miterlimit’](https://www.w3.org/TR/SVG11/painting.html#StrokeMiterlimitProperty), [‘stroke-opacity’](https://www.w3.org/TR/SVG11/painting.html#StrokeOpacityProperty), [‘stroke-width’](https://www.w3.org/TR/SVG11/painting.html#StrokeWidthProperty), [‘text-anchor’](https://www.w3.org/TR/SVG11/text.html#TextAnchorProperty), [‘text-decoration’](https://www.w3.org/TR/SVG11/text.html#TextDecorationProperty), [‘text-rendering’](https://www.w3.org/TR/SVG11/painting.html#TextRenderingProperty), [‘unicode-bidi’](https://www.w3.org/TR/SVG11/text.html#UnicodeBidiProperty), [‘visibility’](https://www.w3.org/TR/SVG11/painting.html#VisibilityProperty), [‘word-spacing’](https://www.w3.org/TR/SVG11/text.html#WordSpacingProperty), [‘writing-mode’](https://www.w3.org/TR/SVG11/text.html#WritingModeProperty)
[filter primitive attributes](https://www.w3.org/TR/SVG11/intro.html#TermFilterPrimitiveAttributes) — [‘x’](https://www.w3.org/TR/SVG11/filters.html#FilterPrimitiveXAttribute), [‘y’](https://www.w3.org/TR/SVG11/filters.html#FilterPrimitiveYAttribute), [‘width’](https://www.w3.org/TR/SVG11/filters.html#FilterPrimitiveWidthAttribute), [‘height’](https://www.w3.org/TR/SVG11/filters.html#FilterPrimitiveHeightAttribute), [‘result’](https://www.w3.org/TR/SVG11/filters.html#FilterPrimitiveResultAttribute)
[‘class’](https://www.w3.org/TR/SVG11/styling.html#ClassAttribute)
[‘style’](https://www.w3.org/TR/SVG11/styling.html#StyleAttribute)
[‘in’](https://www.w3.org/TR/SVG11/filters.html#FilterPrimitiveInAttribute)
[‘order’](https://www.w3.org/TR/SVG11/filters.html#feConvolveMatrixElementOrderAttribute)
[‘kernelMatrix’](https://www.w3.org/TR/SVG11/filters.html#feConvolveMatrixElementKernelMatrixAttribute)
[‘divisor’](https://www.w3.org/TR/SVG11/filters.html#feConvolveMatrixElementDivisorAttribute)
[‘bias’](https://www.w3.org/TR/SVG11/filters.html#feConvolveMatrixElementBiasAttribute)
[‘targetX’](https://www.w3.org/TR/SVG11/filters.html#feConvolveMatrixElementTargetXAttribute)
[‘targetY’](https://www.w3.org/TR/SVG11/filters.html#feConvolveMatrixElementTargetYAttribute)
[‘edgeMode’](https://www.w3.org/TR/SVG11/filters.html#feConvolveMatrixElementEdgeModeAttribute)
[‘kernelUnitLength’](https://www.w3.org/TR/SVG11/filters.html#feConvolveMatrixElementKernelUnitLengthAttribute)
[‘preserveAlpha’](https://www.w3.org/TR/SVG11/filters.html#feConvolveMatrixElementPreserveAlphaAttribute)

`slope` is not in this list.

**Comment by Rumyra** [comment]
Thanks all - I missed the original issue which I have now read (sorry) and it seems the _child_ elements of https://drafts.fxtf.org/filter-effects/#feFuncRElement should be referenced on this page.

As for the compat table we shoudn't remove it, but should reference the child elements (@CBID2 you do that in the frontmatter)

**Comment by estelle** [comment]
When updating this page, the entire page needs to be updated. Swapping out one element for another element does not suffice. The browser compate and usage need to be updated to reflect the elements for which this attribute is valid.

**Comment by bsmth** [comment]
Is it clear what has to be done to resolve the linked issue? Is there enough information there to work on this?

**Comment by estelle** [comment]
> Is it clear what has to be done to resolve the linked issue? Is there enough information there to work on this?

the duplicate/closed https://github.com/mdn/content/issues/24935 has more context

**Comment by estelle** [comment]
This PR doesn't address the issues in the issue https://github.com/mdn/content/issues/32449 and is not accurate or being worked on. Closing.

**Pull request closed without merging**
