### PR TITLE
Fix some layout problems with Django skeleton page

### PR DESCRIPTION
**Pull request by hamishwillee**
- Removed some bold styling in code block because it wasn't working - see https://github.com/mdn/yari/issues/2198
- Removed empty spaces after full stop: `. </p>`
- Fixed up some list layout issues.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@chrisdavidmills Any idea why I can't self-merge this?

**Comment by sideshowbarker** [comment]
> @chrisdavidmills Any idea why I can't self-merge this?

Maybe the CODEOWNERS mechanism requires somebody other than the PR author to approve?

**Review by chrisdavidmills — APPROVED** [review]

**Comment by chrisdavidmills** [comment]
@hamishwillee I'm not sure, TBH. We'll have to look into this.

**Comment by hamishwillee** [comment]
> @hamishwillee I'm not sure, TBH. We'll have to look into this.

@chrisdavidmills Cool. I haven't yet been offered the opportunity to merge anyone else's PR yet either. I feel so powerless :-)

**Pull request merged**
