### PR TITLE
Remove WebRTC custom sidebar

### PR DESCRIPTION
**Pull request by wbamberg**
This PR removes all references to the custom sidebar implemented by the [WebRTCSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/WebRTCSidebar.ejs) macro, and replaces them with references to the standard `DefaultAPISidebar`.

The `WebRTCSidebar` macro doesn't really have any features missing in `DefaultAPISidebar`. In fact, there is already a group for WebRTC in groupdata.json, and the WebRTC overview page already uses `DefaultAPISidebar` (https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API) although its children don't.

Because the usage of this sidebar is quite inconsistent, this PR makes a few different changes:

- I fixed three pages that should be using `APIRef`:
    - https://developer.mozilla.org/en-US/docs/Web/API/RTCIceTransport/statechange_event
    - https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/currentLocalDescription
    - https://developer.mozilla.org/en-US/docs/web/api/rtcdtmfsender/tonechange_event
- I deleted https://developer.mozilla.org/en-US/docs/Web/Guide/API/WebRTC/Peer-to-peer_communications_with_WebRTC and redirected it to the main page
- everything under https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API I updated to use `DefaultAPISidebar`. Some of these pages were using `WebRTCSidebar` and some were incorrectly using `APIRef`.

I also added one guide to the groupdata entry for WebRTC - that was the only relevant thing that seemed to be missing, compared with the custom sidebar contents.

All the other changes are Prettier. I hope that's OK (and sorry about the noise).

After merging this we can deprecate `WebRTCSidebar`.

### CODE REVIEW

**Comment by bsmth** [comment]
- [x] Prettier formatting looks good
- [x] Sidebars look better
- [x] Redirects look good

Why are we deleting https://developer.mozilla.org/en-US/docs/Web/Guide/API/WebRTC/Peer-to-peer_communications_with_WebRTC ?

**Review by bsmth — APPROVED** [review]
Thanks @wbamberg, LGTM 👍🏻

Once comment open about rationale for deleting the page, everything else looks good.

**Comment by wbamberg** [comment]
> * [x]  Prettier formatting looks good
> 
>     * [x]  Sidebars look better
> 
>     * [x]  Redirects look good
> 
> 
> Why are we deleting https://developer.mozilla.org/en-US/docs/Web/Guide/API/WebRTC/Peer-to-peer_communications_with_WebRTC ?

Because:

- it doesn't fit into any IA we have: it's not integrated at all with the other WebRTC docs, and isn't even linked from anywhere in the site. So it's basically impossible to find.
- I don't think it adds anything over https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API

**Comment by bsmth** [comment]
Thank you, merging now 👍🏻

**Pull request merged**
