### PR TITLE
Replace jargon in stroke-miterlimit/index.md

### PR DESCRIPTION
**Pull request by getsnoopy**
### Motivation

They replace jargon with clearer language.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
"Impact" is not a jargon in any sense; it's a common English word. We also do not avoid jargon in reference documentation. So while this PR is not wrong, it merely switches the word choice where both are applicable. Thanks for the contribution.

**Comment by getsnoopy** [comment]
*Impact* is corporate jargon used to inflate claims, so it's proscribed by many style guides when used figuratively (it actually just means "crash force"). Nevertheless, even when it's used figuratively, [it means](https://www.merriam-webster.com/dictionary/impact) "strong/violent/marked effect", which makes no sense in the documentation. E.g., "Strong/violent/marked effect of the default miter limit" makes no sense (are there weak effects of it too?) and therefore not applicable, and it only serves to confuse readers when there's clearly an alternative. There's really no reason to deny this pull request.

**Comment by Josh-Cena** [comment]
Microsoft guide, the guide we use as a catch-all, doesn't forbid "impact" as a noun: https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/impact

[OED definition](https://www.oed.com/dictionary/impact_n?tab=meaning_and_use#822203):

> figurative. Now commonly the effective action of one thing or person upon another; the effect of such action; influence; impression.

Which means "impact" and "effect", "influence" are exact synonyms.

And OED says it dates back to 1817, so not sure where the source for it's "corporate jargon" comes from.

**Comment by getsnoopy** [comment]
The Microsoft style guide just says that the word can be used; it says nothing about what it means.

As for what it means, different dictionaries slightly differ in their definitions, but the majority of dictionaries (including Cambridge & Collins, and Oxford itself in their other dictionaries) agree that it's not synonymous with "effect":
* https://www.oxfordlearnersdictionaries.com/us/definition/english/impact_1?q=impact
* https://www.merriam-webster.com/dictionary/impact
* https://dictionary.cambridge.org/dictionary/english/impact
* https://www.collinsdictionary.com/dictionary/english/impact
* https://en.wiktionary.org/wiki/impact

The OED records first usage, not when the usage became popular. US corporations (especially marketing teams) popularized the word as hyperbole in the 1960s.

Again, I really don't understand why such a simple change warrants such a large discussion, especially when the alternative to objectionable to no one.

**Comment by Josh-Cena** [comment]
> Again, I really don't understand why such a simple change warrants such a large discussion, especially when the alternative to objectionable to no one.

We typically don't accept "improvements" that improve on already-acceptable text. Unless the previous version is non-understandable, or has serious bugs, we prefer to keep things as-is. MDN has a diverse writer base and everyone has different language habits because they come from different regions and different backgrounds, and it's not constructive if everyone edits the language to what they find the most comfortable with. Is "impact" understandable? Yes. (This is a primary-school-level word.) Does it have connotations that hurt certain groups? I hope not. The fact that it was "popularized by corporations" is not a big deal to us; we don't have a beef with corporations.

I don't object that your edit is a good one, but let's stick with a "good enough" word written by another human like you and me and move on to more significant matters. We have to uphold our rules of what counts as valid contributions, otherwise MDN is going to be filled with "grammar improvements" and "word-choice improvements" and crowd out the actually valuable work. I see you have done other PRs that meet the standards of MDN contributions (such as fixing typos and bad grammar), and I encourage you to keep on doing that.

**Comment by getsnoopy** [comment]
The word is not "good enough" when it's clearly objectionable and decreases clarity for many users (including myself). I've cited many dictionaries that define the word as something that's not how the word is presumably intended to mean when it was written, even if we're setting aside the apathy towards being associated with corporations. Saying "Strong/violent/marked effect of the default miter limit" is confusing in that it makes one wonder why the author would phrase something that way, and it opens up another inquiry as to what not-so-strong effects the miter limit would have.

All of this is avoided by using the standard, unambiguous word *effect*, which not only has a universal definition among all dictionaries, but doesn't send the reader looking for other potentially relevant information or leave them confused. Such words don't belong in technical documentation where precision and clarity are important. Your point would be valid if this was a case of swapping words such as "help" with "assist", "pick" with "choose", etc. This is not one of those cases; i.e., one of preference. By this metric, the edit is clearly valuable.

PS: As for "grammar improvements", I'm not sure why you phrased it as if it's a trivial point. Grammar is absolutely crucial in understanding documentation, as like I said above, technical documentation is where clarity and precision reign supreme.

**Pull request closed without merging**
