### PR TITLE
Drawing shapes with canvas": Live examples don't always match screenshots #13173

### LINKED ISSUE #13173: Issue with "Drawing shapes with canvas": Live examples don't always match screenshots
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes

#### What information was incorrect, unhelpful, or incomplete?

The "Quadratic Bezier curves" example's screenshot looks nothing like the live example (on chrome and FF, Linux and mobile)

#### Specific section or headline?

Quadratic Bezier curves

#### What did you expect to see?

The live example should match the screenshot to a decent extent

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvas_api/tutorial/drawing_shapes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/drawing_shapes/index.md
* Last commit: https://github.com/mdn/content/commit/b7aafea1ab7cfee11a7e854a4b5c83a6e6d329d4
* Document last modified: 2022-02-02T09:11:35.000Z

</details>

### PR DESCRIPTION
**Pull request by asususu**
#### Summary ✍️

1.   canvas_quadratic.png screenshot picture changed.
2.   canvas_rect.png screenshot picture changed.
3.   canvas_smiley.png screenshot picture changed.
4.   canvas_arc.png screenshot picture changed.
5.   canvas_bezier.png screenshot picture changed.
6.   canvas_lineto.png screenshot picture changed.

#### Motivation ❓

1.     Quadratic Screenshot and live sample difference removed. They are the same now.
2.     All the non-white background pictures are changed with white backgrounds on the page.

#### Related issues
Fixes #13173 

This PR…
-->
- [ ] changes picture file.

### CODE REVIEW

**Comment by teoli2003** [comment]
Thanks @asususu ! This looks good. Do you want to update in the same way the other screenshots on the page?

**Comment by asususu** [comment]
Ok, i will update the other pictures also 👍 .Thanks :)

**Comment by asususu** [comment]
@teoli2003 hi,
I updated the other pictures with a non-white background.

**Review by teoli2003 — APPROVED** [review]
Thanks! This looks much better!

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:

**Comment by asususu** [comment]
Thanks alot 👍 . I am very happy and excited for the first commit and hope to continue :)

**Pull request merged**
