### PR TITLE
WebExtensions: HttpHeaders: name: document capitalization

### PR DESCRIPTION
**Pull request by DavidJCobb**
### Description

Documented the exact capitalization and formatting used for header names in the HttpHeaders object, based on testing in Kiwi/Chromium.

### Motivation

Across MDN and Chrome's own webRequest documentation, headers are referred with `Capitalized-Dashed-Names`; however, the API requires `lowercase-dashed-names`. This ambiguity can lead to wasted time trying to get webRequest event handlers working.

### CODE REVIEW

**Comment by bsmth** [comment]
Hi @rebloor the changes look good to me, do you want to have a quick look to confirm?

**Review by rebloor — DISMISSED** [review]
Looks good to me too

**Comment by rebloor** [comment]
@DavidJCobb looking at this again, seems a little strange that the header is converted to lowercase. Are you able to test in Firefox or share the code you used for testing?

**Comment by bsmth** [comment]
Hi @DavidJCobb - there's some [information outstanding](https://github.com/mdn/content/pull/22865#issuecomment-1452057284) before this pull request can be merged. Can you provide some resources to confirm this, please? Thank you :)

**Comment by Josh-Cena** [comment]
I'm going to close this for now. Note that Chrome's own example: https://github.com/GoogleChrome/chrome-extensions-samples/blob/be334066a2d3ebc4c54eef464df655cb9730eaaa/_archive/apps/samples/websocket-server/http.js#L468 uses `Content-Length`.

**Pull request closed without merging**
