### PR TITLE
WebM does not support H.264

### PR DESCRIPTION
**Pull request by jrmuizel**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1562862

### CODE REVIEW

**Comment by hamishwillee** [comment]
Is it Firefox that does not support  H.264 codecs in WebM or is it the WebM container format itself (not clear from the bug). If this is just Firefox ( and not the format itself), then this is not the right fix. Instead you'd modify the table below the heading https://pr4388.content.dev.mdn.mozit.cloud/en-US/docs/Web/Media/Formats/Video_codecs#avc_h.264 to indicate the support constraints on Firefox.

**Comment by jrmuizel** [comment]
The same is true of Chrome:
https://source.chromium.org/chromium/chromium/src/+/master:media/formats/webm/webm_video_client.cc;l=71;drc=b33bfc1021de39d17baca16a311026d6798a2793

and suggested by the container spec: https://www.webmproject.org/docs/container/

**Comment by hamishwillee** [comment]
Thanks for the clarification. Could you also remove this from the container support column in https://pr4388.content.dev.mdn.mozit.cloud/en-US/docs/Web/Media/Formats/Video_codecs#avc_h.264 ?

**Review by hamishwillee — APPROVED** [review]
Thanks @jrmuizel !

**Pull request merged**
