### PR TITLE
New ARIA grid glossary entry

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

This PR proposes a new glossary entry for the ARIA Grid pattern.

#### Motivation

~~Originally I thought this would be disambiguation for the existing CSS Grid entry, but there are already many sibling 'grid-xyz' glossary entries for the various CSS grid properties.  Inserting this as another top-level sibling seemed less invasive than trying to introduce a nesting structure.~~

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by devbynicole** [comment]
Hi @Rumyra, thanks for the review!  I believe this has been updated as requested; please let me know if anything still needs attention.

**Comment by Rumyra** [comment]
Thanks @devbynicole ! This looks great :)

@estelle are you ok with the accessibility grid definition?

**Comment by estelle** [comment]
I am not sure we need this page. Most of this information should be added to https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/grid_role rather than being put into a glossary page.

**Comment by devbynicole** [comment]
@estelle ok, I'll go ahead and close this PR then.  Thanks for the feedback.

**Pull request closed without merging**
