### PR TITLE
WebAssembly | C to Wasm - Use C macro for externalising

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Rewrite the polyglot C/C++ example to use a macro for externalising from C++.

#### Motivation
The existing C preprocessor usage is split apart, which can be error-prone if either of them are mismatched, while also not being very extensible to exposing multiple functions to the web.

#### Supporting details
N/A.

#### Related issues
None.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by Phosra** [comment]
I'm running on fairly weak hardware, but if someone could confirm that the example compiles and runs correctly with the JavaScript, that would be great! The type signatures for `main` and `myFunction` seem fishy, as normally they would be swapped.

**Comment by Josh-Cena** [comment]
@Phosra I can confirm it works. Indeed, the main function lacks a return value. I believe it's better if you can add a `return 0;`.

**Comment by Phosra** [comment]
> @Phosra I can confirm it works. Indeed, the main function lacks a return value. I believe it's better if you can add a `return 0;`.

Thank you! Interesting, I was thinking about the parameters. I'll add the returns to all of the mains?

**Comment by Josh-Cena** [comment]
Ah, you mean `main` should receive `argc` and `argv` as well? Frankly I don't know. `myFunction` definitely doesn't receive them since `Module.ccall` is passing all `null`.

**Comment by Phosra** [comment]
> Ah, you mean `main` should receive `argc` and `argv` as well?

Yes, that's precisely why I was questioning this. Would you suggest tagging the original writer?

**Comment by Josh-Cena** [comment]
Maybe @MendyBerger knows? 😄

**Comment by MendyBerger** [comment]
I wish I would, I didn't write that page and I'm not very familiar with C/C++, I mainly do Rust.

**Comment by Josh-Cena** [comment]
Oh, so we do have Rustaceans who are not burnt-out C guys 😄

**Comment by Rumyra** [comment]
@teoli2003 do we know how wrote this originally?

**Comment by sideshowbarker** [comment]
> do we know how wrote this originally?

My guess is that it was @kripken himself — but regardless, I think he’d still be the best person to give us guidance on this

**Comment by kripken** [comment]
I didn't write the original here. But it looks good to me.

**Comment by Josh-Cena** [comment]
OK, waiting on someone to press the button, then... I think we can stay with what we have.

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
