### PR TITLE
update image alt text

### PR DESCRIPTION
**Pull request by jhhornn**
This PR…
-->
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by jhhornn** [comment]
I wrote an article around this project too.

https://dev.to/jhhornn/i-got-my-first-pull-request-merged-3ei9

**Comment by jhhornn** [comment]
Hello

**Review by estelle — APPROVED** [review]
Thank you! And thanks for the link to your blog post. https://twitter.com/OpenWebDocs/status/1559309088634220545

**Comment by jhhornn** [comment]
Thank you so much.

**Pull request merged**
