### PR TITLE
Update Intl.Locale polyfill URL to formatjs

### PR DESCRIPTION
**Pull request by longlho**
Zibi's polyfill is super old and no longer implements the latest spec.

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]
Very nice to get this updated

**Comment by sideshowbarker** [comment]
Much thanks, and congrats on landing your first patch here — welcome aboard 🎉 (there’s likely a lot of room for improvement in the ECMA-402-related MDN docs…)

**Comment by longlho** [comment]
happy to help :) any specific things you're talking about? ECMA402 does tend to add new options in newer spec so it's a bit tricky to clarify browser support.

**Comment by sideshowbarker** [comment]
> any specific things you're talking about?

Nothing in particular — but just looking for cases like this one, where the docs had out-of-date info. Beyond that, spotting any mistakes or inaccuracies that should be corrected.

**Pull request merged**
