### PR TITLE
Refactors code in lastIndexOf and indexOf articles

### PR DESCRIPTION
**Pull request by nlopin**
#### Summary
Replaces `var` keyword for `const` and `let` in code examples of articles [array.lastIndexOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/lastIndexOf) and [array.indexOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf).

#### Motivation
The [MDN JavaScript guideline suggests using `const` and `let` instead of `var`](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript#variables). I noticed obsolete code examples and decided to update them.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

I also wanted to delete the Polyfill section for `indexOf` because this method is supported by all major browsers for years now. What do you think?

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
Looks good!

**Comment by wbamberg** [comment]
@teoli2003 , were you waiting for something before merging this?

> I also wanted to delete the Polyfill section for indexOf because this method is supported by all major browsers for years now. What do you think?

I think we should delete it, yes. We are linking to core-js in "See also", and that's better than embedding a polyfill in the page. @teoli2003 , what do you think?

**Comment by teoli2003** [comment]
Sorry, I was waiting for the tests to complete (and forgot about this), or got distracted.

Yes, we should delete the polyfill. @nlopin: do you want to add a commit here for this?

**Comment by nlopin** [comment]
@teoli2003 yes, give me a moment

**Review by teoli2003 — APPROVED** [review]

**Comment by teoli2003** [comment]
Thanks a lot!

**Pull request merged**
