### PR TITLE
Updating CODEOWNERS

### PR DESCRIPTION
**Pull request by Rumyra**
The default has been changed to include a team with people in it

Learn groups have been removed as there was no one in them and replaced with content area teams

### CODE REVIEW

**Review by escattone — APPROVED** [review]
Thanks @Rumyra, I like these changes, and they look good to me!

**Review by ddbeck — APPROVED** [review]
This looks good to me and I'm approving, though I do have a question. As far as I can tell, the big consequences are:

- There's a catch-all for _everything_ en-US now; there wasn't before.
- Learn stuff is now distributed to reviewers by topic; there's no catch-all specific to learning content.
- There are groups on the left-side of the split diff that aren't on the right: those starting with `yari-content-learn` and `yari-content-tools`. All but one of them are empty groups anyway.

On that last point is my question: `yari-content-learn-css` has members. I take it it's being superseded by `yari-content-css`. Do I understand that correctly?

**Comment by Rumyra** [comment]
> This looks good to me and I'm approving, though I do have a question. As far as I can tell, the big consequences are:
> 
>     * There's a catch-all for _everything_ en-US now; there wasn't before.

Yes - there was one before, but it was just me making it kinda pointless. Luckily catch all is very low traffic, but docs will get distributed between 5-6 people instead of one 👍 

>     * Learn stuff is now distributed to reviewers by topic; there's no catch-all specific to learning content.
> 
>     * There are groups on the left-side of the split diff that aren't on the right: those starting with `yari-content-learn` and `yari-content-tools`. All but one of them are empty groups anyway.
> 
> On that last point is my question: `yari-content-learn-css` has members. I take it it's being superseded by `yari-content-css`. Do I understand that correctly?

Yes - most of the pr traffic is per topic, so it makes sense to keep specialised teams, but without people in learn teams we may as well just use the topic ones. Those in css were in learn/css so that's actually change with no change :)

**Comment by pswan004** [comment]
> This looks good to me and I'm approving, though I do have a question. As far as I can tell, the big consequences are:
> 
> * There's a catch-all for _everything_ en-US now; there wasn't before.
> * Learn stuff is now distributed to reviewers by topic; there's no catch-all specific to learning content.
> * There are groups on the left-side of the split diff that aren't on the right: those starting with `yari-content-learn` and `yari-content-tools`. All but one of them are empty groups anyway.
> 
> On that last point is my question: `yari-content-learn-css` has members. I take it it's being superseded by `yari-content-css`. Do I understand that correctly?

**Pull request merged**
