### PR TITLE
infinity set interval in code example

### PR DESCRIPTION
**Pull request by hrendzha**
### Description
fixed infinity set interval js in example about notifications api

### Motivation
I'm making these changes because I found these typo in code. Readers will be less confused.

### CODE REVIEW

**Review by jpmedley — APPROVED** [review]

**Comment by jpmedley** [comment]
@hrendzha, 

Thanks for submitting this. Unfortunately, I can't merge it. Git is complaining that it can't find a common ancestor. I've never seen this error before, so I'm not sure how to proceed. 

Did you start with an up to date fork?

Joe

**Comment by hrendzha** [comment]
@jpmedley 

I'm not sure. I've synced my fork just now.  Maybe it helped.

Sorry for taking your time.

**Comment by jpmedley** [comment]
@Elchi3 @wbamberg 

Guys, please help. One of the tests is failing on this PR. It says that a common ancestor can't be found between this and main. I don't know if this is safe to merge. I don't have any ideas for addressing this either.

**Comment by wbamberg** [comment]
> Guys, please help. One of the tests is failing on this PR. It says that a common ancestor can't be found between this and main. I don't know if this is safe to merge. I don't have any ideas for addressing this either.

There was some bug in the CI scripts that I think was fixed but if someone has an old fork they will still see it. You can update the PR from main and that apparently fixes it, which I have just done.

(also I think it is benign and can be ignored)

**Pull request merged**
