### PR TITLE
Mark Phaser docs as needing Phaser 2, and not later

### PR DESCRIPTION
**Pull request by Stan-Stani**
Clarify that Phaser 2 is the version that should be used as I've tried the tutorial with Phaser 3 and it does not work properly.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by OnkarRuikar** [comment]
Ideally we should update the tutorial to suit the latest version, which was released on February 13th 2018. They are working on Phaser 4 now.

We need to raise an issue saying the tutorial doesn't work on the current version v3.

**Comment by Rumyra** [comment]
Thanks so much for the pr @biometricPsychography ! I've given it a review

Thanks also the comment @OnkarRuikar :) I agree we should review this content, but I think it should be included in our content strategy as it's a chunky bit of work. I'm happy to make an explicit note about the Phaser version the tutorial uses for now to avoid confusion and I'll add this section to our content strategy 👍

**Comment by biometricPsychography** [comment]
I'm currently trying to run through the tutorial with Phaser 3 by consulting the Phaser 3 docs and the difference isn't too great once configuration is out of the way, it seems. I'd be happy to rewrite the tutorial for Phaser 3 but I'm not sure exactly where to start.

@Rumyra Is this the content strategy you mentioned? https://github.com/mdn/content/projects/11

**Comment by Rumyra** [comment]
@biometricPsychography thanks so much for offering :) A couple of things:

* The pr here is separate to the wider discussion of updating the tutorial - so I still think we should update with the comment you've added in the meantime to avoid reader confusion
* A goal we have for this quarter is to revise the content strategy and process, so we'll also be changing the project link above. I think just at this time it'd be better to hold off on larger updates so we can plan and support this work better 👍

**Comment by biometricPsychography** [comment]
Do I need to do anything more to merge?

**Comment by Rumyra** [comment]
> Do I need to do anything more to merge?

Hi @biometricPsychography yes - if you could accept (use the drop down and select 'commit') the requested change above, then we'll be able to merge :) Thanks!

**Comment by biometricPsychography** [comment]
@Rumyra Sorry, I guess I'm still not quite getting it. 
image

**Comment by Rumyra** [comment]
@biometricPsychography nws it can be confusing :) If you got to the 'Files changed' tab at the top, it should show you your edit and then a suggestion I made underneath. You can click on the drop down there should be an option to 'Commit suggestion' which will update the sentence. Once that's happened we'll be able to merge 👍 Let me know if that's clear.

**Comment by biometricPsychography** [comment]
@Rumyra This is all I see: 
image

I'm not seeing your suggestions.

**Review by Rumyra — CHANGES_REQUESTED** [review]

**Review by dipikabh — DISMISSED** [review]
Tiny edit required...

**Review by Rumyra — APPROVED** [review]

**Review by Rumyra — APPROVED** [review]

**Pull request merged**
