### PR TITLE
Remove the note about "opinions"

### PR DESCRIPTION
**Pull request by patrickhlauke**
It's unclear what "opinions" are mentioned here. For my own part, I've not come across any differing opinions about this use of `role="presentation"` ... it works, it does what it's supposed to. If there are genuine concerns/issues with it, keep the note and include them. Otherwise, this only spread doubt unnecessarily.

> What was wrong/why is this fix needed? (quick summary only)

> Issue number (if there is an associated issue)

> Anything else that could help us review it

### CODE REVIEW

**Review by rachelandrew — APPROVED** [review]
Agreed, this doesn't seem useful.

**Comment by patrickhlauke** [comment]
in hindsight, i should have ripped out the preceding heading as well... but i think this page needs a good overhaul (and I see the note there is present in most other ARIA pages on MDN at the moment), so might propose that separately...

**Review by ericwbailey — COMMENTED** [review]
Most of the MDN ARIA content needs an overhaul, unfortunately.

**Comment by rachelandrew** [comment]
I'm not an ARIA expert but happy to help clean it up if there are general pointers to things that are bad across multiple pages.

**Pull request merged**
