### PR TITLE
Update Firefox 85 release notes for known Marionette bugs.

### PR DESCRIPTION
**Pull request by whimboo**

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
LGTM; thanks @whimboo !

I did a copy edit and applied it directly to your PR; you might want to have a quick read and let me now if my wording looks OK before we merge it.

**Comment by whimboo** [comment]
That reads it hard for me. What about `WebDriver commands following the call to <code>WebDriver:SwitchToFrame</code> can fail with a "no such window" error if the frame's content hasn't finished loading yet`?

**Review by chrisdavidmills — APPROVED** [review]
Perfect, thanks for the clarification @whimboo . I got the wrong impression here, so I'm glad I checked. I've updated the text with (something very near to) your suggested copy.

**Comment by whimboo** [comment]
Thanks @chrisdavidmills !

**Pull request merged**
