### PR TITLE
Prevent exposure of MongoDB URI

### LINKED ISSUE #26873: Prevent exposure of MongoDB URI
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment

### What specific section or headline is this issue about?

Save changes to GitHub

### What information was incorrect, unhelpful, or incomplete?

Current instructions will expose the MongoDB uri to the GitHub repo:

// Set up mongoose connection
const dev_db_url =
  "mongodb+srv://your_user_name:your_password@cluster0.lz91hw2.mongodb.net/local_library?retryWrites=true&w=majority";
const mongoDB = process.env.MONGODB_URI || dev_db_url;

### What did you expect to see?

Can this section be expanded to explain how to best handle API keys and the MongoDB URI during development and production? People following the tutorial should be able to follow each step in order without exposing their MongoDB URI at any point, correct?

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/deployment/index.md
* Last commit: https://github.com/mdn/content/commit/0586fbecaf6683f5e793cd9510397b630fb43e61
* Document last modified: 2023-04-14T05:20:55.000Z

</details>

### PR DESCRIPTION
**Pull request by KingChampion36**
### Description

Fixes #26873

### CODE REVIEW

**Comment by hamishwillee** [comment]
You will note that the current version of the tutorial does not leak the production environment variable - see [database configuration](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment#database_configuration). It does leak the development environment variable, which is not great.

What's the benefit of the env file over just setting the environment variable on the server? You still have to keep that file safe somewhere, and you still have to get it onto the server, but now you have to do that without using the github automated deployment tools we describe later? How were you planning on doing this?
 
As it stands, this also duplicates the database configuration section a bit.

However my thinking is that this highlights that the database configuration section doesn't explain _why_ we might want to have a different production value and hide it using an environment variable. I also think that this is a common way of doing things, so it is well worth mentioning.

So we probably need to merge this with the database configuration section and present it as an option. How we do that depends on your answers to the questions about on deployment of the file and how you store it.

**Comment by josephrmartinez** [comment]
Thank you for the clarification @hamishwillee . I am accustomed to pushing to git somewhat regularly throughout the development process. It would have been more intuitive for me to set up the git repo right during the skeleton site setup section and push to github throughout the development process. But I wouldn't feel comfortable with the MongoDB credentials being exposed. I understand now that I could just regard these are my development credentials and not worry too much about them being exposed.

I think I would still prefer to install dotenv and set up the credentials in a .env file right before the "Install Mongoose" section in part 3 of the tutorial. Maybe I should just chill.  It could be explained right here that this credential is just for a development database and that we will be spinning up a production database and learn how to store that credential securely on the server at a later point in the tutorial. 

But I really don't have much experience with this. I'd prefer to just learn standard or best practice for handling these credentials throughout the development and production stages.

**Comment by hamishwillee** [comment]
@josephrmartinez I have created a PR to replace yours: https://github.com/mdn/content/pull/26977

This highlights that hardcoding the URL is not recommended back in the development section, and in the database section explains why we are making the change (for security). It mentions the .env solution but does not expand into it. 

Why? Because the .env is just one option, and it is one that is not better for the tutorial. Providing hints about options is good.

You make other good points about deploying to github early and perhaps you might also set up the database environment early and so on as well. I didn't do it that way, mostly because when I wrote this I didn't want to suggest github as the only option, or overload people with more non-express information. In hindsight I might do it differently if I was to start again now, but I don't think it is worth my time to restructure now. 

Thank you for the suggestions and discussion. I think this has improved the docs, even if perhaps not quite as you would have liked.

**Comment by hamishwillee** [comment]
Closing. Resolved by https://github.com/mdn/content/pull/26977

**Pull request closed without merging**
