### PR TITLE
add sms protocol to link href

### PR DESCRIPTION
**Pull request by estelle**
It's supported in Firefox: https://codepen.io/estelle/pen/ExGXoGw

### CODE REVIEW

**Review by caugner — COMMENTED** [review]
I was curious and tried it out on Firefox Desktop / Mac OS and Firefox Mobile / Android (Nightly versions), but on Firefox Desktop / Mac OS it just opened a new conversation in the "Messages" app, but without filling in the recipient / body, and on Android clicking the link did not have any effect.

**Comment by estelle** [comment]
> I was curious and tried it out on Firefox Desktop / Mac OS and Firefox Mobile / Android (Nightly versions), but on Firefox Desktop / Mac OS it just opened a new conversation in the "Messages" app, but without filling in the recipient / body, and on Android clicking the link did not have any effect.

Screenshot of android on browserstack with 'hello there' filled in the message.
This is what i got on browserstack, FF for android samsung galaxy note 20. I was first asked if ok to open an app, but the message is there. tried 3 others. same result.

**Comment by dipikabh** [comment]
Thanks for this update, @estelle. While the change seems okay, I feel this needs a corresponding example to say something like `<a href="sms:+1234567890">Send SMS</a>` will open the user's SMS client app (to compare with `mailto`, which opens the email client).

**Comment by estelle** [comment]
> Thanks for this update, @estelle. While the change seems okay, I feel this needs a corresponding example to say something like `<a href="sms:+1234567890">Send SMS</a>` will open the user's SMS client app (to compare with `mailto`, which opens the email client).

The example would only work on FF, and not on FF for iOS. It would also involve explaining international phone numbers, so intentionally did not include it. However, the surrounding text indicated that no other protocol was supported, so did want to include SMS, along with an update to bcd to reflect that support is limited to ff

**Review by dipikabh — APPROVED** [review]

**Pull request merged**
