### PR TITLE
Deleting old PNG file

### LINKED ISSUE #8155: Issue with "Toolbox": Images and Content out-of-date
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox

#### What information was incorrect, unhelpful, or incomplete?
- The Images and content for the most part doesn't match the https://developer.mozilla.org/en-US/docs/Tools page.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/tools_toolbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/tools_toolbox/index.html
* Last commit: https://github.com/mdn/content/commit/27ffb76e66e25862f9092d4eb80b217068d1c754
* Document last modified: 2021-08-20T00:06:10.000Z

</details>

### PR DESCRIPTION
**Pull request by NegiAkash890**
Updating the PNG files

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

Fixes #8155 

> What was wrong/why is this fix needed? (quick summary only)

> Anything else that could help us review it

### CODE REVIEW

**Comment by hamishwillee** [comment]
So why was this needed? What update lead to this?

**Comment by NegiAkash890** [comment]
> EDITED. Ah, so I interpret this as the images in https://developer.mozilla.org/en-US/docs/Tools do not match the same images in https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox - is that right?
> 
No I just updated them

> So how did you fix this? Did you regenerate all the images for https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox from the current version of Firefox?

I only updated images for the page : ` https://developer.mozilla.org/en-US/docs/Tools` 
But I think this needs to be updated too : `https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox`

**Comment by hamishwillee** [comment]
> No I just updated them

That's cool. But what I mean is where did you get the new images - screen shot from Firefox 91?

**Comment by NegiAkash890** [comment]
> > No I just updated them
> 
> That's cool. But what I mean is where did you get the new images - screen shot from Firefox 91?

Yes

**Review by hamishwillee — APPROVED** [review]
Fantastic - thank you.

**Pull request merged**
