### PR TITLE
Initial commit to updating wai-aria basics

### PR DESCRIPTION
**Pull request by scottaohara**
adjusting (and removing) content that was out of date or inaccurate.

This is not done yet.

Related to https://github.com/mdn/learning-area/pull/540

### CODE REVIEW

**Comment by bsmth** [comment]
Hi @scottaohara 👋🏻 are you going to come back to this one? I see there are some conflicts that need to be resolved in the meantime 🤔

**Comment by scottaohara** [comment]
yes @bsmth, sorry for the delay.  it's on my todo list, but unfortunately many other things are too.

i will eventually get this started again and fix any conflicts as needed

**Review by chaht72 — COMMENTED** [review]
sa

**Comment by bsmth** [comment]
Hi @scottaohara 

>sorry for the delay. it's on my todo list, but unfortunately many other things are too.

Not a problem :) 

Would it be okay to close this PR (not deleting the branch) and we reopen it when you're ready to pick it up again?

**Comment by scottaohara** [comment]
yes.  i'll do that now.  clearly i have not had the time to get back to this.  thanks

**Pull request closed without merging**
