### PR TITLE
Fix Array.prototype.sort examples

### PR DESCRIPTION
**Pull request by robtayl0r**
### Description

Fixes a few wrong numbers in the Array.prototype.sort method examples.

### Motivation

The existing values are incorrect and confusing.

### CODE REVIEW

**Review by estelle — APPROVED** [review]
Thanks! 🎉

**Comment by wbamberg** [comment]
@robtayl0r , I'm not sure what the purpose of this PR is, can you elaborate please?  The PR says the original code is wrong, but doesn't say how it is wrong or how this PR fixes it.

The original code:

```js
const numbers = [3, 1, 4, 1, 5];
const sorted = numbers.sort((a, b) => a - b);
// numbers and sorted are both [1, 1, 3, 4, 5]
sorted[0] = 10;
console.log(numbers[0]); // 10
```

...is correct, I think: the point is that `numbers` and `sorted` are the same array, so when you change `sorted[0]`, then `numbers[0]` gets changed as well.

Your change sets `sorted[0]` to `1`, which it already is, so it's redundant. So your code:

```js
const numbers = [3, 1, 4, 1, 5];
const sorted = numbers.sort((a, b) => a - b);
// numbers and sorted are both [1, 1, 3, 4, 5]
sorted[0] = 1;
console.log(numbers[0]); // 1
```

...has the same result as if we never set `sorted[0]`:

```js
const numbers = [3, 1, 4, 1, 5];
const sorted = numbers.sort((a, b) => a - b);
// numbers and sorted are both [1, 1, 3, 4, 5]
console.log(numbers[0]); // 1
```

...so it seems to defeat the purpose of the example.

**Comment by robtayl0r** [comment]
@wbamberg you're absolutely correct. I apologize, I misread the code.

**Comment by wbamberg** [comment]
> @wbamberg you're absolutely correct. I apologize, I misread the code. What's the best course of action, should I open a revert?

No worries @robtayl0r , it's easily done. Yes, let's revert.

**Pull request merged**
