### PR TITLE
Changed "A cool-looking box" page to be Semantically accurate

### LINKED ISSUE #15566: "A cool-looking box" exercise gives wrong impression about UI design
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/A_cool_looking_box

### What specific section or headline is this issue about?

Excercise as a whole

### What information was incorrect, unhelpful, or incomplete?

The exercise is about styling a `<p>`. The end result looks like a button and we even call it a button in the list of subtasks ("A reasonable width/height for a large button"). This gives the wrong impression that it's fine to use a styled `<p>` as a button.

### What did you expect to see?

I see two possibilities to prevent possible misunderstandings:
A) Change the styling of the box so it less looks like a button and change the mention of "button" in the subtasks.
B) Change the exercise to be about "A cool-looking button" and use `<button>` in the starting code.

Personally, I like the gradient, the shadows and the end result. I would tend to version B with no strong opinion either way.

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/a_cool_looking_box`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/A_cool_looking_box
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/a_cool_looking_box/index.md
* Last commit: https://github.com/mdn/content/commit/2777cdc8c8b54268a24beeeb7a98520e3331d3be
* Document last modified: 2022-04-26T11:32:33.000Z

</details>

### PR DESCRIPTION
**Pull request by vagadeeshwar**
#### Summary
- Changed **button** references to **box** and `p` to `div` to be semantically right
- Added new image with better contrast and updated the respective step in ### Styling the box

#### Motivation
- Better Semantics and Accessibility

#### Related issues
Fixes #15566 

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by vagadeeshwar — COMMENTED** [review]
CSS used to style new button:
image

**Review by estelle — APPROVED** [review]
Thank you!

**Review by estelle — APPROVED** [review]
Thank you. Red on red was NOT a good example. thank you for changing that.

**Comment by vagadeeshwar** [comment]
Very happy to have made my first successful PR... that too on my primary learning source!

Thankyou! @estelle @mikoMK

**Pull request merged**
