### PR TITLE
Move audio and video guides under Web/Media

### PR DESCRIPTION
**Pull request by teoli2003**
Part of openwebdocs/project#185

The _audio and video_ guides under Web/Guide are better than the others under Web/Media; that way:
- they are together with all the similar guides
- they don't clutter Web/Guide

In the future, we may want to assess and rewrite all that is below Web/Media, but having these articles all together is helpful for the web developers as they'll have a complete sidebar to navigate from one to the others.

### CODE REVIEW

**Comment by zfox23** [comment]
Thanks for your contribution, @teoli2003. Can you please help me understand this language here?

> The audio and video guides under Web/Guide are better than the others under Web/Media; that way:

I'm struggling to understand "...are better than the others under... -> that way".

Can you please rephrase?

**Comment by teoli2003** [comment]
The audio and video guides under Web/Guide are better located under Web/Media.

**Review by zfox23 — CHANGES_REQUESTED** [review]
Could you please update the links referenced by our bot in [this comment](https://github.com/mdn/content/pull/30766#issuecomment-1838021873)?

**Comment by teoli2003** [comment]
Yep, we always forgot them; a yari PR is waiting to be reviewed for months to fix internal links when we move pages...

We would have detected them using the flaw dashboard, but it is always better to fix them directly.

I also noticed that the sidebars were not all compatible, so I fixed these, too (this sidebar macro is far from perfect, but it is outside the scope of this PR to improve it, as it is used elsewhere).

**Review by zfox23 — APPROVED** [review]

**Pull request merged**
