### PR TITLE
fix: use `console.log` instead of `console.error`

### PR DESCRIPTION
**Pull request by i4pg**
Thanks to @Josh-Cena suggest using `console.log` here, because we are not actually giving out indications of exceptions, just information about an `Error` object.

### Related issues and pull requests
Relates to #26961

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Thanks but it's an empty PR :) I'm not sure what happened but could you commit the right changes?

**Review by Josh-Cena — APPROVED** [review]
Thank you!

**Comment by i4pg** [comment]
Oops, sorry about that empty commit! I was trying to copy and paste from Vim to the GitHub editor, but something went wrong. You know how it is with Vim sometimes. Anyway, thanks for giving me a chance to fix it, and I agree with your point of view.

**Review by antlsdl1 — COMMENTED** [review]
0aa8ef68a2c32b45b6636510309a48f6d24ad673

**Pull request merged**
