### PR TITLE
fix: remove height property to prevent stretched image

### LINKED ISSUE #243: Issue with "Getting started with React": …
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started

#### What information was incorrect, unhelpful, or incomplete?
A  _**img**_ tag is not properly set.

#### Specific section or headline?
Screenshot of Firefox MacOS, open to localhost:3000, showing the default create-react-app application
Screenshot (148)

_**height**_ attribute of the _**img**_ tag needs to be removed.

#### What did you expect to see?
Screenshot (149)

#### Did you test this? If so, how?
Yes, I have used dev tools. 
Removed the height attribute from the  tag, and it works fine.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.html
* Report started: 2020-12-15T15:07:09.633Z

</details>

### PR DESCRIPTION
**Pull request by sherwinski**
Fixes #243 by removing the `height` CSS property on the img element. The property is causing the image to appear distorted by stretching it vertically. Without it, the image maintains an appropriate aspect ratio.

Screen Shot 2020-12-17 at 6 39 17 PM

The inclusion of `default-create-react-app.png` in this PR is a result of running `Show flaws > Fix fixable flaws` on the project locally. Please let me know if that change should be rolled back. Thanks!

### CODE REVIEW

**Comment by sideshowbarker** [comment]
Thanks much for raising this. https://github.com/mdn/content/pull/390/checks?check_run_id=1574345808 shows we have a CI check that’s failing which we’ll need to figure out and fix so this can be merged

**Comment by sideshowbarker** [comment]
> The inclusion of `default-create-react-app.png` in this PR is a result of running `Show flaws > Fix fixable flaws` on the project locally. Please let me know if that change should be rolled back. Thanks!

Let’s wait to see what that Yari mavens have to say

**Comment by chrisdavidmills** [comment]
Let's alert @peterbe and @escattone to this to see what they think.

**Comment by peterbe** [comment]
See https://github.com/mdn/content/issues/356#issuecomment-748188078

**Comment by sherwinski** [comment]
> #390 (checks) shows we have a CI check that’s failing which we’ll need to figure out and fix so this can be merged

@sideshowbarker I was able to resolve the failing CI check locally (see [e1415c0](https://github.com/mdn/content/pull/390/commits/e1415c0f6a5cc510ce08c1f6f87e08ce9f82127a)) but for some reason cannot get the checks to rerun. Any suggestions? I could try force pushing to the branch.

@peterbe I'm in favor of using the `width` and `height` attributes to prevent CLS 👍 However, I don't have any suggestions on how to do this exhaustively for the entire site. If you prefer, I can manually set them this time until the team decides what's the best path forward.

I also want to call out that this PR conflicts with #389 -- funny enough our two PRs were opened within a minute of each other. I assume if we move forward with using `width`/`height` that we're ok with overwriting these changes, but just wanted to make sure.

**Comment by sideshowbarker** [comment]
> @sideshowbarker I was able to resolve the failing CI check locally (see [e1415c0](https://github.com/mdn/content/pull/390/commits/e1415c0f6a5cc510ce08c1f6f87e08ce9f82127a)) but for some reason cannot get the checks to rerun.

I think that might be due to the merge conflict. I’m not certain, but maybe the way GitHub Actions works is that if there’s a merge conflict, it doesn’t run any checks.

> Any suggestions? I could try force pushing to the branch.

It’s fine to try force pushing to the branch. You could even just squash the commits and force push. I doubt that’ll trigger the CI to re-run, though — but will happy if I’m proven wrong.

**Comment by sherwinski** [comment]
@sideshowbarker Thanks, looks like that did it 👍

**Review by sideshowbarker — APPROVED** [review]

**Review by chrisdavidmills — APPROVED** [review]

**Comment by peterbe** [comment]
I'm working on a fix so that the `style` attribute is automatically "scrubbed" at build-time. That means that any:
```html
<img src="SRC" style="width: 123px; height; 234px; other: thing">
```
automatically becomes:
```html
<img src="SRC" style="other: thing">
```
It was actually relatively easy so I thought I'd kill two birds with one stone. 
So, now if the `SRC` is a local image, it also checks the image dimensions with [image-size](https://www.npmjs.com/package/image-size) so it ends up becoming:
```html
<img src="SRC" style="other: thing" width="123" height="234">
```

I hope I can get that fix out soon so we don't have to manually fix each and every stretched image.

**Comment by sherwinski** [comment]
Out of curiosity, is the intention to eventually have all images stored locally or have there be a mix of local/fetched images?

**Comment by peterbe** [comment]
> Out of curiosity, is the intention to eventually have all images stored locally or have there be a mix of local/fetched images?

We decided to store all images locally. I.e. ``
You're allowed to refer to them in siblings and cousins. I.e. ``

The advantages are simplicity and reliability. It's also easier to confidently deal with optimization. For example, if you depend on `` you can't really complain if the image is huge or if gets replaced with a picture of a goat. 
And if we have images locally, we can easily and quickly find out their dimensions which is good for preventing CLS. 
And another cooling we can do with local images, is that we can control producing extra images such as retina/non-retina and responsive and/or AVIF/WEBP generate, on-the-fly, from once source we can control without depending on network.

**Comment by sherwinski** [comment]
Thanks for the responses @peterbe.

> And another cooling we can do with local images is that we can control producing extra images such as retina/non-retina and responsive and/or AVIF/WEBP generate, on-the-fly, from one source we can control without depending on network.

I'd be interested to hear more about how your team plans on implementing this, assuming you're comfortable with sharing. To be transparent, I work on developer tools for an [image solution](https://www.imgix.com/) provider and this is exactly the kind of thing we'd love to help out with if you and your team are interested.

**Comment by peterbe** [comment]
> Thanks for the responses @peterbe.
> 
> > And another cooling we can do with local images is that we can control producing extra images such as retina/non-retina and responsive and/or AVIF/WEBP generate, on-the-fly, from one source we can control without depending on network.
> 
> I'd be interested to hear more about how your team plans on implementing this, assuming you're comfortable with sharing. To be transparent, I work on developer tools for an [image solution](https://www.imgix.com/) provider and this is exactly the kind of thing we'd love to help out with if you and your team are interested.

It's all here: https://github.com/mdn/yari/pull/2251
It transforms something like:
```html
<img src="foo.png" style="width: 123px; height: 100px; other: things">
```
into:
```html
<img src="foo.png" width="123" height="100" style="other: things">
```

Simple as that :)

**Comment by sherwinski** [comment]
Just checked out that PR, and it looks like scrubbing all the images at build time is much quicker than I would have guessed 👍 
Regarding my last comment, I was more curious about this part:
> we can control producing extra images such as retina/non-retina and responsive and/or AVIF/WEBP generate

The main reason I ask is that it can be pretty tedious to generate multiple versions (sizes and formats) of the same image at build time. So I was curious if you planned on hand-rolling your own solution or might consider leaning on a service to accomplish this for you.

At the risk of sounding like something of a broken record, with a service like imgix you can take an image like this:
```html
<img src="foo.png" width="123" height="100" style="other: things">
```
and adjust the markdown to this:
```html
<img
	src="foo.png" 
	srcset="foo.png?dpr=1 1x,
		  foo.png?dpr=2 2x,
		  foo.png?dpr=3 3x"
	width="123"
	height="100"
	style="other: things">
```
Assuming imgix has access to `foo.png`, your users will only request and render the version of the image needed for their device. Each image version is generated on-the-fly and cached on a global CDN, so you don't have to worry about generating/storing the retina, webp, etc versions locally. Again, happy to discuss further if this is a path you'd like to test out. 😁

**Comment by peterbe** [comment]
I'm really impressed with Imgix and I'm well aware of the product and how awesome it is. I think it's a great idea to consider because we don't need to worry about uploading our images to it. We can just inject our URL prefix so that `` becomes ``. 
...the day the need comes. :)

**Comment by hamishwillee** [comment]
@peterbe YOu may already have thought about this, but image location is also important for translation. Unless you intend to translate all your images you need to either duplicate them in every tree or have an invariant location that can be referenced from the source across languages.

**Comment by peterbe** [comment]
> @peterbe YOu may already have thought about this, but image location is also important for translation. Unless you intend to translate all your images you need to either duplicate them in every tree or have an invariant location that can be referenced from the source across languages.

Translated content should be using the en-US images. E.g.:
(in some imaginary `translated-content/files/sv-SE/web/foo/bar/index.html`)
```html
<p>
 Öppna och titta på denna bilden <img src="/en-US/docs/Web/Foo/bar/pic.png" title="Visar nånting nyttigt">
</p>
```
Anything that isn't that should be considered a flaw.

**Pull request merged**
