### PR TITLE
Update Additional Links

### PR DESCRIPTION
**Pull request by ghost**
### Description

Updated links under the "See Also" section:
1. Added **The Odin Project** - https://www.theodinproject.com/
2. Removed EXLskills (the site's been down for months, and the curriculum has not been updated in years) - https://exlskills.com/

### Motivation

To help potential learners find the right resources.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@Raymond-Adams Thanks very much. Very happy with the removal of EXL skills. 

Can you remove the addition of Odin? To reduce the maintenance cost we are quite careful about adding new links unless a site has particular significance and a track record - which given this appeared in 2023 the odin project does not.

**Comment by Raymond-Adams** [comment]
@hamishwillee Done, though I'd argue that TPO is more significant than either learnjavascript.online or edabit.com
The Odin Project Overview

**Comment by hamishwillee** [comment]
@Raymond-Adams  Regarding Odin project - perhaps it is arguable. I will ask how the broader review team feels about this link and post back here in a day or two if there is broad support. 

But for now I will merge this. Thank you.

**Review by hamishwillee — APPROVED** [review]

**Comment by hamishwillee** [comment]
@Raymond-Adams I got only one response from the team, but they thought that Odinproject looked good. I think so too. So if you want to PR the fix back in, that would be welcome. Sorry to be a pain.

**Pull request merged**
