### PR TITLE
Fix: escape raw characters in HTML

### PR DESCRIPTION
**Pull request by bershanskiy**
Escape raw characters in HTML.

These were found by [`html-validate`](https://www.npmjs.com/package/html-validate) rule `no-raw-characters`.

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
Are there any real problems that any of these are creating?

The fact that html-validate reports errors for them doesn’t seem like a real problem.

The raw content files aren’t intended to be run as-is through something like html-validate or any other HTML linter or validator.

And it shouldn’t be assumed that those characters are a problem for the publishing pipeline, or that they make in through the publishing pipeline as-is.

The output published through Yari doesn’t actually have the raw characters, as far as I can see; in the published output, they get replaced with the character references.

If you check the published output with https://validator.w3.org/nu/?doc=https://developer.mozilla.org/en-US/docs/web/api/baseaudiocontext/state or whatever, no errors about those characters are reported.

So it’s not clear what problem is actually being solved by replacing them in the sources.

**Comment by bershanskiy** [comment]
> Are there any real problems that any of these are creating?

Not, as far as I'm aware. I created this PR for consistency, as a follow-up to #451.

> So it’s not clear what problem is actually being solved by replacing them in the sources.

Escaping characters is the most trivial way to find stray `>` chars in commits. E.g., #907.

Alternatively, we can create a more nuanced approach to special characters:
 - Allow special characters within contexts we expect them to see
   For example, `<`, `>`, `&` (and may be other) characters appear within `<pre>` and `<code>` as operators, `&` is common in `<p>` and `<h[123]>` as "and", any `<kbd>` can contain any character as a button label.
 - Flag these characters as potentially problematic in contexts we would not expect them (all other contexts).
   For example, a stray `>` within `<p>` is likely an error.

This way, we could use the actual characters within `<pre>`, which would simplify JS linting down the line. I like the second option, since it creates the least amount of technical debt in the long term.

**Comment by chrisdavidmills** [comment]
I'd agree that it would be nice to have a way to flag unescaped characters in places where they are a problem. Perhaps this should be part of the fixable flaws @peterbe is masterminding?

But I'd rather not start escaping these inside code examples, where it isn't a problem, as this might set a precedent that this is necessary, and thereby add cognitive load to those writing code examples. That said, I'm going to close this.

**Comment by sideshowbarker** [comment]
> Alternatively, we can create a more nuanced approach to special characters:
> 
> * Allow special characters within contexts we expect them to see
>   For example, `<`, `>`, `&` (and may be other) characters appear within `<pre>` and `<code>` as operators, `&` is common in `<p>` and `<h[123]>` as "and", any `<kbd>` can contain any character as a button label.

Incidentally, note that the HTML spec no longer says having a raw `&` in content is a conformance error. If it’s “unambiguously” not the start of character reference, then it’s fine. And that covers the vast majority of instances in body text, which are in the pattern *foo & bar*, where there’s a space after the `&`. (The place where it can get “ambiguous” is when there’s some character other than a whitespace character right after the `&`).

> * Flag these characters as potentially problematic in contexts we would not expect them (all other contexts).
>   For example, a stray `>` within `<p>` is likely an error.
> 
> This way, we could use the actual characters within `<pre>`, which would simplify JS linting down the line. I like the second option, since it creates the least amount of technical debt in the long term.

Agreed yes that sounds like the right way to deal with them.

**Comment by peterbe** [comment]
I agree with @chrisdavidmills Let's not worry too much about this. 
Thankfully, all `<pre>` tags are processed and serialized correctly. 

For example, on https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Adding_bouncing_balls_features 
the line:
```
if (!(this === balls[j]) && balls[j].exists) {
```
becomes...
```html
...
<span class="token operator">&amp;&amp;</span>
...
```
which is the correct final form the HTML should have. I.e. escaped. So that's nice to know. 

But I don't think you need to escape any HTML inside `<pre>` tags other than `<` and `>` for any other practical reasons. But escaping `"` (for example) would make me sleep better at night if the content was dynamic user-content that would be published. But I sleep well knowing Yari uses `cheerio` and PrismJS correctly to produce a rock-solid final HTML output.

It's my firm position that we mustn't over-worry about the correctness of the *raw* HTML because A) it matter significantl;y less than the final HTML, and B) if we do worry about the input, I'd rather use that energy towards something Markdown'ish.

**Pull request closed without merging**
