### PR TITLE
Moves the closing filter tag to include the feMerge

### PR DESCRIPTION
**Pull request by RCopeland**
regarding: https://github.com/mdn/sprints/issues/3827

### CODE REVIEW

**Comment by peterbe** [comment]
@RCopeland I believe you started this PR before the migration (Dec 14). Is this change still valid?

**Comment by avivmu** [comment]
@chrisdavidmills let's close this as it's not relevant anmore

**Comment by Ryuno-Ki** [comment]
Interesting. It's touching SVG (I'm member of the team there), but I cannot close this PR :o

**Comment by Ryuno-Ki** [comment]
Found it m(

**Pull request closed without merging**
