### PR TITLE
update: Korean Current maintainers info

### PR DESCRIPTION
**Pull request by hochan222**
### Description

update: Korean Discussions and Current maintainers info. 

cc. @mdn/yari-content-ko

### Motivation

Team members and channel changes 

### Additional details

- https://github.com/mdn/translated-content/pull/21666

### CODE REVIEW

**Review by hamishwillee — APPROVED** [review]
So it looks like from https://github.com/mdn/translated-content/pull/21666 that [jho2301](https://github.com/jho2301) is no longer an active maintainer? 

We probably need a better process for picking a reviewer for these - I'm not part of the translation team so it is hard for me to know whether these updates are correct or not.

**Comment by hochan222** [comment]
@hamishwillee I was in a hurry without checking, so I created a PR first. If I had first confirmed that he had left the team and then given a PR, the issue you are worried about would not have arisen.

You can check current locale team members on the page below, but it cannot be said that it is always valid. (Only the mdn  team has the authority to update the translation team's personnel. (or, each to our own.))

- https://github.com/orgs/mdn/teams/yari-content-ko

@mdn/mdn-community-engagement **How about setting the reviewer to `@mdn/mdn-community-engagement` for the current page?** And.. can you exclude [jho2301](https://github.com/jho2301) from the team? He is no longer an active member.

**Comment by hamishwillee** [comment]
Thanks @hochan222 - I don't have the GitHub rights to make those changes, but I have asked for advice.

**Comment by hamishwillee** [comment]
This has been passed to the community manager. I'm hands-off :-)

**Pull request merged**
