### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by OnkarRuikar**
The corrected variable names exist in these files only so no harm would be done.

### CODE REVIEW

**Comment by estelle** [comment]
I personally prefer the original, as it informs the reader that "elemnt" is the Element object, but a variable (or const) defined by the script. Adding @chrisdavidmills so he can decide ;)

**Comment by bsmth** [comment]
Another option is to use something like "item" instead of "element", what do you reckon? 🤔

**Comment by OnkarRuikar** [comment]
> I personally prefer the original, as it informs the reader that "elemnt" is the Element object, but a variable (or const) defined by the script. 

There is no inbuilt `element` object available in JS. So what is wrong with `element`?

**Comment by estelle** [comment]
> > I personally prefer the original, as it informs the reader that "elemnt" is the Element object, but a variable (or const) defined by the script.
> 
> There is no inbuilt `element` object available in JS. So what is wrong with `element`?

People may not know there is no built-in Element object or they may think you can put "body", "section" or another element name there. to make sure people who are learning aren't confused, you'll note we generally write variable names like `myElement` or `elmnt` instead of `element`

**Comment by OnkarRuikar** [comment]
> you'll note we generally write variable names like myElement or elmnt instead of element

No issues with `myElement` but abbreviations (`elmnt`) are against our [variable names writing guidelines](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript#variable_names
). More descriptive function declaration in this case could've been:
```diff
-- function dragElement(element) {
++ function makeDraggable(element) {
```

> People may not know there is no built-in Element object or they may think you can put "body", "section" or another element name there.

But using `body` or `section` as variable names is perfectly fine as they are not in the global scope. The following is valid:
```js
const body = document.body;
const section = document.createElement("section");
```
 Are you trying to say that, inorder to avoid confusion, we should avoid using HTML tag names as variable names?

**Comment by Josh-Cena** [comment]
What about `el` or `elem`? These are common abbreviations and aren't likely to be treated as typos. The point of that style guide is to avoid abbreviations where full names can work and the abbreviation is uncommon, but here full name is obviously non-ideal, and we are also generally against `myElement`.

**Comment by OnkarRuikar** [comment]
> but here full name is obviously non-ideal,

Why `element` is not ideal?\
We should call it `anchor` cos in the example the function is updating anchors and it is not being reused for anything else.

> What about `el` or `elem`? These are common abbreviations and aren't likely to be treated as typos.

Ideally, we should follow https://google.github.io/styleguide/jsguide.html#naming-rules-common-to-all-identifiers

**Comment by Josh-Cena** [comment]
> Why `element` is not ideal?

Because the general consensus here seems to be that this name looks too "special".

**Comment by OnkarRuikar** [comment]
> > Why `element` is not ideal?
> 
> Because the general consensus here seems to be that this name looks too "special".

We need to stand up to the superstition. Otherwise, make it official in the writing guidelines by banning `element` as a variable name.

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
I think this discussion is veering too close to yak-shaving territory, and we shouldn't spend too much more time on it. 

I agree with @OnkarRuikar that "elmnt" sounds like a typo; we should've chosen something a bit more elegant to begin with. But I also agree that `element` sounds a bit too generic, and like it could be a reserved word. It is kind of an unspoken best practice in tech writing that you don't use such words in demos, you also wouldn't call things "property", or "attribute", or "variable", or "method". I also think we should document that somewhere in the guidelines.

For now, I think "element" should be changed to "elem" or "dragElement" (make it a bit more semantic?)

The rest of it is fine.

**Comment by OnkarRuikar** [comment]
>  It is kind of an unspoken best practice in tech writing that you don't use such words in demos, you also wouldn't call things "property", or "attribute", or "variable", or "method".

Thanks for the info.

The yak got shaved too much here so I've [changed it to `elem`](https://github.com/mdn/content/pull/34528/commits/33378d7dcebab2df27787195076ec13356657035):

**Review by chrisdavidmills — APPROVED** [review]
Perfect, thanks @OnkarRuikar! This one looks good to me now.

**Pull request merged**
