### PR TITLE
Put browser-compat info in front-runner for api/[opq]*

### PR DESCRIPTION
**Pull request by teoli2003**
> What was wrong/why is this fix needed? (quick summary only)

We want to have browser-compat in front-runner: this allows us to write {{Compat}} without parameter, and in the future, {{Spec}} (and likely more).

This PR covers api/[opq]* for the case without problem: 1 macro Compat in the page and its parameter matching the slug. Other cases (no Compat macros on a page, multiple Compat macros, macro not matching the slug, will be done at a later stage).

> MDN URL of the main page changed

406 files in api/* 

> Issue number (if there is an associated issue)

openwebdocs/project#36

> Anything else that could help us review it

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
👍

**Comment by Elchi3** [comment]
Looks good to me but a merge conflict needs resolving.

**Comment by teoli2003** [comment]
The conflict was the removal of PaymentAddress.regionCode by foolip in #5434. I merged the head and I think this was an error.

**Comment by Elchi3** [comment]
There is a new conflict now and it looks like it is due to a bad merge? This PR is huge now.

**Comment by teoli2003** [comment]
Yes, I think I mixed something. I wonder if I should not just rebase to head: the extra file will be gone and I'll merge the CSP header that have been changed overnight. This should keep this PR readable.

What do you think, @elchi3 ?

**Comment by Elchi3** [comment]
Yeah, either you resolve it here or you start with a fresh PR based on the latest head. I don't mind, whatever seems most effective for you. :)

**Comment by teoli2003** [comment]
I'm closing this one in profit of #5536.

**Pull request closed without merging**
