### PR TITLE
Fix issue 15872: remove live sample inclusions in CSS

### PR DESCRIPTION
**Pull request by wbamberg**
Part of https://github.com/mdn/content/issues/15872 : this removes the transclusion parameter from all `EmbedLiveSample` calls in the CSS docs.

### CODE REVIEW

**Comment by OnkarRuikar** [comment]
In stacking_context_example_1/index.md
overflow

Can we increase the height of `div4` to `80px`. Like `div1` and `div3` have `80px`.

**Comment by OnkarRuikar** [comment]
Just a question. You have used different flavors of height arguments in the macros:
```
{{ EmbedLiveSample('Setting horizontal box orientation', '', 100) }}
{{ EmbedLiveSample('Example', '', '300px') }}
{{ EmbedLiveSample('Setting font ligatures and contextual forms', '', '700') }}
```
They all work, but what is the preferred way to provide height?

As per https://developer.mozilla.org/en-US/docs/MDN/Structures/Live_samples#live_sample_macros
> **height**
The height of the [<iframe>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) to create, specified in `px`. This is optional; a reasonable default height will be used if you omit this. Note that if you want to use a specific height, you must also specify the width parameter. If you use only one of them, the default frame size is used.

Shouldn't we be providing widths here? Is the width requirement for mobile screens? In which case `width` is must?

**Comment by wbamberg** [comment]
> Just a question. You have used different flavors of height arguments in the macros:
> 
> ```
> {{ EmbedLiveSample('Setting horizontal box orientation', '', 100) }}
> {{ EmbedLiveSample('Example', '', '300px') }}
> {{ EmbedLiveSample('Setting font ligatures and contextual forms', '', '700') }}
> ```
> 
> They all work, but what is the preferred way to provide height?

I don't know. Usually I prefer to omit "px" but not sure it matters.

> 
> As per https://developer.mozilla.org/en-US/docs/MDN/Structures/Live_samples#live_sample_macros
> 
> > **height**
> > The height of the [<iframe>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) to create, specified in `px`. This is optional; a reasonable default height will be used if you omit this. Note that if you want to use a specific height, you must also specify the width parameter. If you use only one of them, the default frame size is used.
> 
> Shouldn't we be providing widths here? Is the width requirement for mobile screens? In which case `width` is must? If this doesn't work like this anymore then should we update the Live_samples document?

`width` used to have an effect in the old platform but AFAIK it is ignored in Yari.

**Comment by wbamberg** [comment]
According to https://github.com/mdn/yari/issues/5016#issuecomment-1113567313 it looks like we ought to omit "px", although I think it works either way.

**Review by teoli2003 — APPROVED** [review]
So, these things were transclusions of themselves (I don't want to see yari's code to handle this parameter)

**Comment by OnkarRuikar** [comment]
> According to [mdn/yari#5016 (comment)](https://github.com/mdn/yari/issues/5016#issuecomment-1113567313) it looks like we ought to omit "px", although I think it works either way.

Good find! Looks like we need to update the doc https://developer.mozilla.org/en-US/docs/MDN/Structures/Live_samples#live_sample_macros to remove `px`. It'll prevent future commits form using `px'.

**Comment by teoli2003** [comment]
> Good find! Looks like we need to update the doc https://developer.mozilla.org/en-US/docs/MDN/Structures/Live_samples#live_sample_macros to remove `px`. It'll prevent future commits form using `px'.

Yes, please.

**Pull request merged**
