### PR TITLE
(HTML) Add `-webkit` prefixed props to `<meter>` page

### PR DESCRIPTION
**Pull request by Jemeni11**
### Description
I added the following links to the bottom of the HTMLElement meter page:

- {{cssxref("::-webkit-meter-bar")}}
- {{cssxref("::-webkit-meter-inner-element") }}
- {{cssxref("::-webkit-meter-even-less-good-value")}}
- {{cssxref("::-webkit-meter-optimum-value")}}
- {{cssxref("::-webkit-meter-suboptimum-value")}}

### Motivation
The HTMLElement progress page has links for its CSS-related pseudo-elements, but the meter page lacks them. Therefore, I added these links for better completeness and user navigation.

### CODE REVIEW

**Comment by bsmth** [comment]
Thanks @Jemeni11 - I'll let Estelle weigh in on this one, but I don't think this will be accepted as vendor-prefixed / non-standard props usually don't belong in these sections. Just noting that this page exists, also which might be an alternative to mention: https://developer.mozilla.org/en-US/docs/Web/CSS/WebKit_Extensions

**Comment by Jemeni11** [comment]
> Thanks @Jemeni11 - I'll let Estelle weigh in on this one, but I don't think this will be accepted as vendor-prefixed / non-standard props usually don't belong in these sections. Just noting that this page exists, also which might be an alternative to mention: https://developer.mozilla.org/en-US/docs/Web/CSS/WebKit_Extensions

Thanks for the fast response, @bsmth. I get it. However, doesn't this mean several links under the "See Also" section of the progress HTMLElement page need to be removed?

- [-moz-orient](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-orient)
- [::-moz-progress-bar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-progress-bar)
- [::-webkit-progress-bar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-progress-bar)
- [::-webkit-progress-value](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-progress-value)
- [::-webkit-progress-inner-element](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-progress-inner-element)

None of these are standard yet.

**Comment by bsmth** [comment]
>doesn't this mean several links under the "See Also" section of the progress HTMLElement page need to be removed

Good point, looks like it's up for discussion whether to keep these and accept your PR. I zoned in on the non-standard props as they don't work everywhere and often cause compatibility issues. Links (mostly examples, though) often end up propagating these in the wild. I've been removing a few of these pages recently as vendors are more often working to disable them in favor of standard props (see #29911, #27273, #26726 etc.).

>None of these are standard yet.

They likely won't be, but I guess there's no other way to style progress bars at the moment, so there may be a case for including the `progress` and `meter` vendor-prefixed props, I'm curious what others think.

**Comment by estelle** [comment]
I think a note saying something to the effect of `While `accent-color` has no effect on the `<meter>` element, some browser allow components of the meter to be styled through non-standard pseudo-elements like x, y, and z.` 

On `<progress>` i would add `accent-color` to the see also, or add a note, as done with the above, but with different content as accent color is supported .

**Comment by bsmth** [comment]
Thanks, Estelle.

> I think a note saying something to the effect of `While `accent-color`has no effect on the`` element, some browser allow components of the meter to be styled through non-standard pseudo-elements like x, y, and z.`
> 
> On `<progress>` i would add `accent-color` to the see also, or add a note, as done with the above, but with different content as accent color is supported .

@Jemeni11 - does this make sense? Would you like to make these changes?

**Comment by Jemeni11** [comment]
Thanks for the quick replies @estelle @bsmth and I'm sorry for my late reply.

> @Jemeni11 - does this make sense? Would you like to make these changes?

Thank you! I'd love to make these changes. 
Is something like this okay? 
```markdown
## See also
- {{HTMLElement("progress")}}

While pseudo-elements like `meter-bar` do not affect the element, some browsers allow the 
meter element to be styled through non-standard pseudo-elements like:

- {{cssxref("::-webkit-meter-bar")}}
- {{cssxref("::-webkit-meter-inner-element") }}
- {{cssxref("::-webkit-meter-even-less-good-value")}}
- {{cssxref("::-webkit-meter-optimum-value")}}
- {{cssxref("::-webkit-meter-suboptimum-value")}}
```
I wasn't sure if I should've listed all the pseudo-elements in the paragraph.

**Comment by estelle** [comment]
> I wasn't sure if I should've listed all the pseudo-elements in the paragraph.

There are MDN guidelines on how to format content within the see also section. See https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#see_also_section

```
## See also

- {{HTMLElement("progress")}}
- {{cssxref("accent-color")}} CSS property
- {{cssxref("::-webkit-meter-bar")}}, {{cssxref("::-webkit-meter-inner-element") }}, {{cssxref("::-webkit-meter-even-less-good-value")}}, {{cssxref("::-webkit-meter-optimum-value")}}, {{cssxref("::-webkit-meter-suboptimum-value")}}: stylable non-standard pseudo-elements
```

**Comment by Jemeni11** [comment]
Thanks for the guidelines @estelle they were really helpful!

**Review by bsmth — APPROVED** [review]
Thanks a lot, leaving my +1, I'll let Estelle have a look in case there's other feedback. Thank you :)

**Comment by Jemeni11** [comment]
> Thanks a lot, leaving my +1, I'll let Estelle have a look in case there's other feedback. Thank you :)

You're welcome! Thanks too (•◡•)

**Review by estelle — APPROVED** [review]
Thank you. Also, congratulations on your first merged MDN content PR. 
Welcome to the team!

**Pull request merged**
