### PR TITLE
Add nolint to syntax blocks

### PR DESCRIPTION
**Pull request by Josh-Cena**
### Description

Caught by my script.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by fisker** [comment]
Out of curiosity, why don't we use `<!-- prettier-ignore -->` instead?

**Comment by Josh-Cena** [comment]
@fisker There's a weak preference in MDN to not use magic comments at all. Plus this will silence both Prettier and ESLint.

**Comment by teoli2003** [comment]
Also, if one day we switch away from Prettier, we don't need to update our Markdown: less coupling.

**Comment by fisker** [comment]
Make sense, good to know.

**Pull request merged**
