### PR TITLE
Slight "clean-up" of crossorigin attribute page

### PR DESCRIPTION
**Pull request by cw118**
#### Summary/Motivation
- Uses HTML tags instead of markdown for text formatting inside HTML tables where applicable (avoids seeing literal text such as `**user credentials**` on the page)
- Other typography modifications (e.g. using code formatting instead of quotes for attribute names, etc.)
- Slight rewording(s)

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by teoli2003** [comment]
I think we should get rid of this HTML table and use Markdown to denote a `<dl>` `<dt>` list. The documentation about how to do this is [here](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#definition_lists).

@cw118, do you want to update your PR to do this?

**Comment by cw118** [comment]
Sounds good, I'll make the changes in a bit :)

And just to clarify, would you prefer it to be formatted as a Markdown table or a definition list?

**Comment by teoli2003** [comment]
We would prefer as a definition list. We try to get rid of tables (Markdown or HTML) as much as possible.

**Comment by cw118** [comment]
I wasn't sure what to do with the [second table](https://github.com/mdn/content/pull/14492/files#diff-e0c1b986282a6756d61543cbb79394156584b17852715954b3bbad8f4c67080eR35-R60) since it doesn't really have term-definition pairs. I left that one as is for now, but do let me know if I should replace it with a definition list as well :)

**Comment by wbamberg** [comment]
> I think we should get rid of this HTML table and use Markdown to denote a `<dl>` `<dt>` list. The documentation about how to do this is [here](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#definition_lists).
> 
> @cw118, do you want to update your PR to do this?

Ha, that's exactly what I came here to say! :)

**Review by sideshowbarker — DISMISSED** [review]

**Comment by cw118** [comment]
@teoli2003 would it be possible to take a look at this? I (hopefully) resolved a merge conflict, and there is a HTML table that I left as is for now because I wasn't sure how to change it :)

**Review by estelle — APPROVED** [review]

**Pull request merged**
