### PR TITLE
Add support for message fragmentation to handle large messages

### LINKED ISSUE #34151: Native messaging example with python 3.12.4 does not work
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging

### What specific section or headline is this issue about?

python3

### What information was incorrect, unhelpful, or incomplete?

the "ping" is correctly received by the python script but the response "pong" is not received by the add-on

the error is that the response exceeds the size limit 

### What did you expect to see?

pong

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by Ashish-CodeJourney**
### Description

Implemented message fragmentation to support the transmission of large messages by splitting them into smaller chunks. This enhancement ensures compatibility with systems that have strict size limits on individual messages, improving the overall reliability of the messaging system.

### Motivation

The primary motivation behind these changes is to address the limitation where messages exceeding a predefined size limit could not be transmitted due to size restrictions on the receiving end. By introducing message fragmentation, we enable the successful transmission of all messages, regardless of their size, thereby enhancing the robustness and flexibility of our messaging system.

### Additional details

This implementation is based on the understanding that many applications and services impose strict size constraints on incoming messages. By allowing messages to be split into smaller chunks and then reassembled on the receiving end, we ensure broader compatibility and improved performance in scenarios involving large data transfers.

### Related issues and pull requests

#34151

### CODE REVIEW

**Comment by Ashish-CodeJourney** [comment]
it looks like @jpmedley is not active from a long time
@Josh-Cena can you please look into this PR and my other PRs where he is assigned as a reviewer ?

**Comment by Josh-Cena** [comment]
This is very related to https://github.com/mdn/content/pull/29104 where @rebloor seems to hit a similar error as https://github.com/mdn/content/issues/34151. I'm going to add them as a reviewer.

**Comment by Ashish-CodeJourney** [comment]
> This is very related to #29104 where @rebloor seems to hit a similar error as #34151. I'm going to add them as a reviewer.

Thanks

**Comment by Ashish-CodeJourney** [comment]
@rebloor does this sounds fine ?

**Comment by rebloor** [comment]
@Ashish-CodeJourney added @dotproto to review the code. Otherwise, I'll need to spin up some code and test.

**Comment by Ashish-CodeJourney** [comment]
> @Ashish-CodeJourney added @dotproto to review the code. Otherwise, I'll need to spin up some code and test.

Okay, let's wait for his review

**Comment by Ashish-CodeJourney** [comment]
> > @Ashish-CodeJourney added @dotproto to review the code. Otherwise, I'll need to spin up some code and test.
> 
> Okay, let's wait for his review

@

> > @Ashish-CodeJourney added @dotproto to review the code. Otherwise, I'll need to spin up some code and test.
> 
> Okay, let's wait for his review

@rebloor  @dotproto any updates ?

**Comment by dotproto** [comment]
I'm trying to clear out my PR backlog today. I just gave this PR a read through and my current thinking is that if we do add chunking to the examples, we should probably do so to both the Python 3 and Node.js code at roughly the same time. I'm tentatively thinking about merging this and another similar PR for Node into a temp branch, cleaning up the text a little, and then landing that temp branch in main.

**Comment by Ashish-CodeJourney** [comment]
> I'm trying to clear out my PR backlog today. I just gave this PR a read through and my current thinking is that if we do add chunking to the examples, we should probably do so to both the Python 3 and Node.js code at roughly the same time. I'm tentatively thinking about merging this and another similar PR for Node into a temp branch, cleaning up the text a little, and then landing that temp branch in main.

Makes sense. 
let me know if you need me to update anything in this

**Comment by Ashish-CodeJourney** [comment]
> > I'm trying to clear out my PR backlog today. I just gave this PR a read through and my current thinking is that if we do add chunking to the examples, we should probably do so to both the Python 3 and Node.js code at roughly the same time. I'm tentatively thinking about merging this and another similar PR for Node into a temp branch, cleaning up the text a little, and then landing that temp branch in main.
> 
> Makes sense. let me know if you need me to update anything in this

@dotproto any updates ?

**Comment by Ashish-CodeJourney** [comment]
> > I'm trying to clear out my PR backlog today. I just gave this PR a read through and my current thinking is that if we do add chunking to the examples, we should probably do so to both the Python 3 and Node.js code at roughly the same time. I'm tentatively thinking about merging this and another similar PR for Node into a temp branch, cleaning up the text a little, and then landing that temp branch in main.
> 
> Makes sense. let me know if you need me to update anything in this

@rebloor @dotproto @Josh-Cena it's open since 4 - 5 months
any updates ? as no one is reviewing

**Pull request closed without merging**
