### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Freelancershipon**
Startup resource added

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

> What was wrong/why is this fix needed? (quick summary only)

> Anything else that could help us review it

### CODE REVIEW

**Comment by teoli2003** [comment]
Why should we add this? It looks like spam to me.

I'll rather delete the whole paragraph.

**Comment by Freelancershipon** [comment]
No,Don't delete

**Comment by Freelancershipon** [comment]
I have added startup resource

**Comment by Freelancershipon** [comment]
> Why should we add this? It looks like spam to me.
> 
> I'll rather delete the whole paragraph.

No,It's a authentic source both are startup

**Comment by teoli2003** [comment]
Why these two and not the 2000 other ones?

**Comment by teoli2003** [comment]
I'm closing this as we have decided to remove this section altogether.

**Comment by sideshowbarker** [comment]
> Why should we add this? It looks like spam to me.
> 
> I'll rather delete the whole paragraph.

Big +1. And I think it’s not just the one paragraph that needs to be deleted at this point — but instead the entire section that paragraph is in; so I opened #7916 to do that deletion.

**Pull request closed without merging**
