### PR TITLE
Improve example in StyleSheetList

### PR DESCRIPTION
**Pull request by digi-booster**
#### Summary

same as #9413 
#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by AnilSeervi** [comment]
> 
> #### Summary
> 
> same as #9413

If the PR is still open and unreviewed, instead of Opening a new PR, you can submit the changes in a single PR by commiting the changes to the same branch.

**Comment by digi-booster** [comment]
> > #### Summary
> > same as #9413
> 
> If the PR is still open and unreviewed, instead of Opening a new PR, you can submit the changes in a single PR by commiting the changes to the same branch.

Those are both on different pages but the example used on both pages is the same.

**Comment by digi-booster** [comment]
> > #### Summary
> > same as #9413
> 
> If the PR is still open and unreviewed, instead of Opening a new PR, you can submit the changes in a single PR by commiting the changes to the same branch.

Okay, if the problem is related to the same topic, I will definitely do that next time.

**Comment by digi-booster** [comment]
> > > #### Summary
> > > same as #9413
> > 
> > 
> > If the PR is still open and unreviewed, instead of Opening a new PR, you can submit the changes in a single PR by commiting the changes to the same branch.
> 
> Okay, if the pr is related to the same topic, I will definitely do that next time.

I tried to do it, but doing it right now is a bit confusing for me.

**Comment by AnilSeervi** [comment]
- Switch to the branch that is submitted as PR
- Navigate to the file you need to change
- Edit the file and commit the changes
- The commit will appear on the PR you submitted.

**Comment by digi-booster** [comment]
> * Switch to the branch that is submitted as PR
> * Navigate to the file you need to change
> * Edit the file and commit the changes
> * The commit will appear on the PR you submitted.

Thanks, @AnilSeervi 🚀

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
