### PR TITLE
Don't mutate reduce accumulator

### PR DESCRIPTION
**Pull request by jonahallibone**
Return a new array in doubling example instead of mutating the `previousValue`

### Description

Changed the doubling example to not modify the `previousValue` argument. If this change makes the example too confusing (need to understand spread operator, logic seems slightly more complex) I understand. If this is an acceptable change, I can modify the PR to fix this elsewhere

### Motivation
This is more inline with how many popular linters will make users change their code, and is more "functional" in nature

### CODE REVIEW

**Comment by Josh-Cena** [comment]
> This is more in line with how many popular linters will make users change their code

I don't think any linter will catch that.

> is more "functional" in nature

I agree with that in principle but it indeed makes the code a bit more... advanced. I think I'll take it since it's why people use `reduce` anyway. Do you want to update it for the other places where we mutate the accumulator?

**Comment by jonahallibone** [comment]
@Josh-Cena yea sure! I'll try and update the PR later today

**Comment by jonahallibone** [comment]
@Josh-Cena Pretty sure I got all the spots. Let me know if there's anything else I can do!

**Review by Josh-Cena — APPROVED** [review]
LGTM. Thank you! Congratulations on your first contribution here—welcome aboard!

**Pull request merged**
