### PR TITLE
Update broken links

### PR DESCRIPTION
**Pull request by OnkarRuikar**

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by OnkarRuikar** [comment]
There were a lot of broken dom-examples links.
Can we add a default message to PR's content section, while creating a new PR  on mdn/dom-examples repo?
We need to convey that they need to update the new URL and code in mdn/content repo as well.

**Comment by teoli2003** [comment]
I'm cc/ing @schalkneethling and @Rumyra to make them aware. They are reorganizing the repos.

**Comment by schalkneethling** [comment]
Thanks so much @OnkarRuikar and @teoli2003 🎉

**Pull request merged**
