### PR TITLE
Do not use JSON.stringify in console.log

### PR DESCRIPTION
**Pull request by JasonLamv-t**
### Description

Such as the title.

### Motivation

The original code does not print the commented expected output.

### Additional details

Nope yet.

### Related issues and pull requests

None.

### CODE REVIEW

**Comment by Josh-Cena** [comment]
In what way does it not print the expected output? All consoles support outputting arrays.

**Comment by JasonLamv-t** [comment]
> In what way does it not print the expected output? All consoles support outputting arrays.

Oops, my fault, I may mess something up wrong so I got `myFish after: 'clown', 'mandarin', 'surgeon' ` before this PR. But the reason why I tried is that, the previous code in the same block print the array processed with JSON.stringify, but another one log directly, this might cause a litter bit of difference. That is the result I got after running the code now.

```bash
myFish before: ["angel","clown","mandarin","surgeon"]
myFish after: [ 'clown', 'mandarin', 'surgeon' ]
```

If it doesn't matter, you can turn off this pr directly. Thanks for your time.

**Comment by Josh-Cena** [comment]
> I got `myFish after: 'clown', 'mandarin', 'surgeon' ` before this PR.

My guess is that you used `+` or template literals instead of `,`, so the array was turned into a string.

> the previous code in the same block print the array processed with JSON.stringify, but another one log directly, this might cause a litter bit of difference

Thanks for pointing it out! I think both should log the array directly so if you could remove the unnecessary JSON.stringify it would be great.

**Review by Josh-Cena — APPROVED** [review]
Thank you! The output before wasn't JSON anyway, so it's clearly a typo in that case.

**Pull request merged**
