### PR TITLE
rm unuseful "not a programming" framing

### PR DESCRIPTION
**Pull request by tantek**
As much as HTML is code that makes computers do things, it is a [computer] "programming" language. The presence/lack of any particular programming language feature (whether Turing blah blah or control structures etc.) does not disqualify that.

### CODE REVIEW

**Review by aaronpk — APPROVED** [review]

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
100% agreed — but not merging because @chrisdavidmills may feel otherwise and should review

**Comment by Ryuno-Ki** [comment]
FWIW I vote in favour of it.

Since last year, I observed a whole range of new people joining the industry (via CodeNewbie or 100 Days of Code, for example). We shouldn't discourage them by joining the gatekeepers trying to declare, that HTML is not a programming language (same with CSS). I even saw logic gates implemented! (That being said, it might was the case, that HTML / CSS lacked features, but no more today).

**Comment by Ryuno-Ki** [comment]
Related to #1960

**Comment by hamishwillee** [comment]
This is a duplicate of https://github.com/mdn/content/pull/1960 which I merged already. There is no point merging, but will leave open so Chris can see the comments.

**Comment by chrisdavidmills** [comment]
This is a duplicate yes, so it can be closed, but thanks to everyone for their care and attention in handling this point (especially @tantek in this thread). I heartily approve of this change.

**Pull request closed without merging**
