### PR TITLE
IDB: Update dom-examples links

### PR DESCRIPTION
**Pull request by OnkarRuikar**
Updated code as well.

### CODE REVIEW

**Comment by jpmedley** [comment]
@Rumyra I've asked to review this, but I have never written IDB code. Do you have anyone on staff who has?

**Comment by Rumyra** [comment]
Hi @OnkarRuikar - the updated code means the text doesn't make sense anymore. Can you explain the reason for updating the code - thanks!

**Comment by sideshowbarker** [comment]
@OnkarRuikar This is waiting on your response to https://github.com/mdn/content/pull/18463#issuecomment-1191576384

**Comment by OnkarRuikar** [comment]
All, sorry for the late response. Didn't know this was blocking something.
***

> Can you explain the reason for updating the code - thanks!

I've been updating broken links as part of #16668. After fixing the links on these pages I found that the code snippets didn't match with the links. So I updated the code…

But we are not having code snippets from the live sample for all the IDB pages. If we were then https://github.com/mdn/content/pull/17211/files would've updated the code as well. The PR also missed these pages. I didn't know this fact while updating the code.

Now, I've reverted the code snippets. However, we are prettifying all the code on mdn/content, so I've ran prettier on the snippets. Now the PR has reduced to simple URLs update and prettified code.

***
@sideshowbarker fixing broken URLs is almost done so I thought of finishing that simple stuff before handling this more involved task. Do we have time limit to close PRs?

**Comment by sideshowbarker** [comment]
> Do we have time limit to close PRs?

We don’t have any time limit to close PRs. But in general it’s a bad idea to keep PRs open for very long — for one reason, because it risks forgetting about them while having moved on in the meantime to work on other things, and for another reason, because other changes can get made to source in the meantime, and then we end up with merge conflicts blocking the PR from being landed — etc.

**Comment by Rumyra** [comment]
Thanks @OnkarRuikar @sideshowbarker 

The original move of the examples was part of a project to tidy up repos a bit. Updating the code and putting it inline with the examples wasn't a part of it, so I'm going to merge this pr as is, and we can look at code updates separately 👍

**Review by Rumyra — APPROVED** [review]

**Pull request merged**
