### PR TITLE
fix: de-table input=range

### PR DESCRIPTION
**Pull request by nschonni**
Left the `<table class="properties">` since it seems to still be widely used, but replaced the Screenshot/Live samples that didn't seem to be a common pattern

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thanks for the PR, @nschonni !

I'm happy to remove tables where we can but I think this is less clear than the original.

I think that since checkmarks are supported in Chrome and WebKit it would be OK to remove the screenshots and rework the description a bit to be clear that (1) this is just showing examples of the feature (not "mockups") and (2) the feature isn't fully supported yet.

If you don't want to make that change let me know and I will close this PR and take care of it myself :).

**Comment by nschonni** [comment]
Not sure I follow the suggestion. This was more because I found that it seemed like it was using tables for layout, but looking at Yari, I see that form is actually what the 4 parameter version of the Macro produces.

**Comment by wbamberg** [comment]
> Not sure I follow the suggestion. 

The live samples here include screenshots because the feature isn't well supported by browsers, and the text acknowledges this by referring to "mockups". I'm saying that we could stop using the screenshot form of EmbedLiveSample, just making them normal live samples, and explain in the text that these features are not well supported by browsers (so people are not surprised when the live sample doesn't show checks in Firefox).

I don't particularly like showing screenshots in cases like this because they age badly and are browser- and platform-specific - for example the screenshots here don't anyway reflect what's shown in Chrome.

But I think the current page is _OK_, and this PR as it stands makes the page worse, not better, so I don't think we should merge it without some extra rework.

**Comment by estelle** [comment]
I agree with @wbamberg. Would be better to show a live demo rather than screenshots, as is done on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist (wondering if the BCD on that page should be more detailed). 

the form control in the demo should include a name, and associated label (implicit, or include an id and make it explicit). I realize the original didn't have that, but since it it being updated....

**Comment by wbamberg** [comment]
> wondering if the BCD on that page should be more detailed).

Definitely, yes.

**Comment by wbamberg** [comment]
I filed https://github.com/mdn/content/pull/21378 to replace this PR.

**Pull request closed without merging**
