### PR TITLE
Bump technote-space/get-diff-action to v4.0.2, other small changes

### PR DESCRIPTION
**Pull request by bershanskiy**
This PR bumps GitHub Actions dependency `technote-space/get-diff-action` to v4.0.2 or removes it altogether where appropriate.

### `.github/workflows/preview.yml`

Removed dependency altogether. This Action does not use the diff, just the fact that at least one of three specific files changed, so it's possible to use only [built-in scripting tools](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths).

### ` .github/workflows/pr-filecheck.yml`

Replaced deprecated `SUFFIX_FILTER` and `PREFIX_FILTER` with `PATTERNS`. Specified `on.pull_request.paths` and removed extra `if`, which will always resolve to true when reached.

## `.github/workflows/pr-build.yml`

Replaced deprecated `SUFFIX_FILTER` and `PREFIX_FILTER` with `PATTERNS`. Specified `pull_request.branches.paths`.

Related: #124

### CODE REVIEW

**Comment by bershanskiy** [comment]
Please note: if `.github/workflows/pr-build.yml` was split into separate files for each job, `build` could run only on changes to `files/**/*.html`, and `check_redirects` only for `files/**/*_redirects.txt` (and would not require `technote-space/get-diff-action`).

**Comment by bershanskiy** [comment]
Also, `build` and `check_redirects` are "Expected — Waiting for status to be reported" because they are "required" by `master` branch protection, but they did not run since files they run on were not changed. There are two possible solutions:
 - remove these `master` branch protections in settings, or
 - run them for all PRs, even when they are known to do nothing

image

**Comment by peterbe** [comment]
Why did you close this?

**Comment by bershanskiy** [comment]
I decided to break up this PR into multiple smaller ones for easier review. Should you need the working copy, I keep it here: https://github.com/bershanskiy/content/tree/actions

**Pull request closed without merging**
