### PR TITLE
removing out of date mdn search tool page

### LINKED ISSUE #2616: Issue with "Search on MDN"
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Tools/Search

**What information was incorrect, unhelpful, or incomplete?**

Filtering results is not work.

**Specific section or headline?**

https://developer.mozilla.org/en-US/docs/MDN/Tools/Search#filtering_results

**What did you expect to see?**

If do not have this function, please delete the relevant content.

**Did you test this? If so, how?**

Look at this link: https://developer.mozilla.org/en-US/search?q=media+record

I didn't find the filter on this page

### PR DESCRIPTION
**Pull request by chrisdavidmills**
Fixes https://github.com/mdn/content/issues/2616

### CODE REVIEW

**Review by Elchi3 — CHANGES_REQUESTED** [review]
Please also remove it from https://developer.mozilla.org/en-US/docs/MDN/Tools

(and maybe search for "MDN/Tools/Search" in the whole tree to get other links removed)

**Comment by NegiAkash890** [comment]
Hi , as much I can interpret from the above comments and the linked issue , I think that all we need to do here is remove the "Search on MDN" section from the pages . Please correct me if I am wrong and also can I help here ?

**Comment by NegiAkash890** [comment]
Hi , as much as I can interpret from the above comments and the linked issue , I think that all we need to do here is remove the "Search on MDN"  section from the pages and the links of the pages  . Please correct me if I am wrong and also can I help here ?

**Comment by chrisdavidmills** [comment]
> Please also remove it from https://developer.mozilla.org/en-US/docs/MDN/Tools

That list is generated by a macro, so no change needed there.

> (and maybe search for "MDN/Tools/Search" in the whole tree to get other links removed)

I did a full search, and there are no other pages linking to that doc.

**Comment by chrisdavidmills** [comment]
> Hi , as much as I can interpret from the above comments and the linked issue , I think that all we need to do here is remove the "Search on MDN" section from the pages and the links of the pages . Please correct me if I am wrong and also can I help here ?

This is a pull request that I am in the middle of getting reviewed, so no help needed here, thanks. The best way to help is to select new issues from the list at https://github.com/mdn/content/issues/; try filtering by clicking on some of the labels, if you are looking for specific subjects to work on, for example.

**Review by Elchi3 — APPROVED** [review]
Awesome, then I'm happy with this.

**Pull request merged**
