### PR TITLE
Remove 'How to add tags' page

### PR DESCRIPTION
**Pull request by teoli2003**
Now that tags are gone, this page is no more useful.

### CODE REVIEW

**Comment by teoli2003** [comment]
This fixes the last content bit of mdn/mdn#262

**Comment by OnkarRuikar** [comment]
We need to remove links to the page as well:
```
[`tags`]: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Tag

[`Deprecated`](/en-US/docs/MDN/Writing_guidelines/Howto/Tag#technology_status_tags)

See [How to tag pages](/en-US/docs/MDN/Writing_guidelines/Howto/Tag) for information about which tags to apply.

See [How to properly tag pages](/en-US/docs/MDN/Writing_guidelines/Howto/Tag)
```

**Comment by teoli2003** [comment]
Good point, my brain malfunctioned and believed there would be no links to it… This is obviously not the case.

**Comment by OnkarRuikar** [comment]
> and believed there would be no links to it… This is obviously not the case.

The onus shouldn't be put on contributors to remember these auto detectable things. It would be better if the PR check workflow, for every deleted document in the PR, grep(rg) entire content for links(`/en-US/docs/${docPath}`).

**Comment by teoli2003** [comment]
> Or may be the document deletion script, after deletion, warn/log document containing references to the deleted document.

I think that `yarn content move` should fix Markdown links automatically. (I opened a yari issue for this: mdn/yari#8292 – the yari team signaled in it that they are accepting PRs for it)
and `yarn content delete` should list Markdown links to the deleted document so that the editor doesn't forget to edit them. (No yari issue opened for this yet)

Even if it doesn't work for links generated by macros, it will already solve many cases.

**Comment by OnkarRuikar** [comment]
> yarn content delete should list Markdown links to the deleted document so that the editor doesn't forget to edit them. (No yari issue opened for this yet)

- I've opened the issue: https://github.com/mdn/yari/issues/8372

**Review by hamishwillee — APPROVED** [review]

**Comment by hamishwillee** [comment]
The fact is, even if you add a redirect, that does not clean up the content around the page link. The redirect should really only be to fix up external links to the page, for which we have no control. I'm sure we all agree with that, and the need to clean up content when deleting/redirecting.

Sadly, I once proposed that deleting or moving a page should list the linked pages. That got closed by (as I recall) a warning added when you delete or redirect a page that you might need to do cleanup. We could request this in yari again.

Thanks very much for making this fix @teoli2003 !!!

**Comment by hamishwillee** [comment]
PS I think it _might_ be worth having a single page covering page metadata, and sticking as much of our page metadata instructions elsewhere into that.

**Pull request merged**
