### PR TITLE
Use let instead of const for paddleX variable

### PR DESCRIPTION
**Pull request by wasabigeek**
#### Summary

`paddleX` holds the current position of the paddle and needs to be modified, however it is now being assigned to a `const`. This PR changes it to use `let` instead.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
We have been overzealous here. Thank you!

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:

**Comment by wasabigeek** [comment]
No worries @teoli2003! Easy fix.

Tangential question, this tutorial still has inconsistent variable declarations (e.g. `var` is still used in quite a few places). Is that intentional?

**Comment by teoli2003** [comment]
No, we are in the process of cleaning them, and we have not cleaned the `var`-> `let/const` example under games. But we fixed some when we modernized some other parts (like the use of arrow functions).

We hope to finish this part of the modernization very soon.

**Comment by teoli2003** [comment]
(PRs welcome, of course)

**Pull request merged**
