### PR TITLE
removed note

### PR DESCRIPTION
**Pull request by estelle**
removed note that seems a bit promotional. External links in the note are similar to "see also" content.

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by hamishwillee** [comment]
That looks like a form of attribution - which needs to exist if we've copied external content. I'd be looking at finding the licensing of the original and using a more formal attribution text.

**Review by wbamberg — APPROVED** [review]
👍 yes, agreed.

**Comment by hamishwillee** [comment]
@wbamberg I guess I was wrong then in https://github.com/mdn/content/pull/12997#issuecomment-1039685665 :-)

**Comment by wbamberg** [comment]
Oh, sorry Hamish, I guess we crossed over here. But perhaps you are right?

**Comment by hamishwillee** [comment]
Let's see what @estelle thinks.

**Pull request merged**
