### PR TITLE
feat: Add link to web-platform-dx/web-features for Baseline issues

### PR DESCRIPTION
**Pull request by bsmth**
### Description

Direct users to web-platform-dx/web-features for Baseline-related issues (tagged with https://github.com/mdn/content/labels/baseline)

### Motivation

Closing some duplicate / related issues in content repo

### CODE REVIEW

**Review by pepelsbey — APPROVED** [review]
Looks good! Thanks :)

**Review by estelle — APPROVED** [review]
Thanks! 🎉

**Comment by hamishwillee** [comment]
@caugner When you say "implementation on MDN" do you mean yari reporting valid data incorrectly, or something else?

The MDN content team are getting what look like valid issues posted about the data that is displayed that we can't do anything with. It doesn't make sense for me (say) to act as a filter for these issues and then have to repost them on baseline every time.

**Comment by LeoMcA** [comment]
> IIRC when baseline was launched, we intentionally did not link to them to avoid them receiving low quality issue reports that actually refer to the implementation on MDN.

I think this is fine now - Baseline has been around for a little while now, so the immediate influx of low quality issues should be gone. These kinds of "Baseline/BCD discrepancy" issues we've been seeing do relate to upstream issues, so I think there's value directing them up there, even if the solution (for now) is maintaining a manual blocklist within yari.

If upstream is getting overloaded with low quality issues we can of course reconsider.

**Review by LeoMcA — APPROVED** [review]

**Review by Rumyra — APPROVED** [review]

**Pull request merged**
