### PR TITLE
Document Intl.DateTimeFormat first argument locales accepts undefined

### PR DESCRIPTION
**Pull request by royalicing**
### Description

Document that `Intl.DateTimeFormat` first argument `locales` can be passed as `undefined`.

### Motivation

I wanted to format a date with custom `dateStyle` options but use the current user’s locale. You can do this by passing `undefined` to the first argument `locales`. This might be implicitly explained by it being documented as “optional” but I think it can be clearer.

### Additional details

There is a code example further down showing `undefined` being passed. But it is amongst many other code examples, and isn’t explicitly documented against the `locales` argument.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Hi there, sorry for holding this up, I intended to do some edits myself, but I haven't had time.

We use the same format for all Intl constructors' `locales` parameter, so you need to update them all. Do you want to do this or is it okay if I do that in a few days?

**Comment by RoyalIcing** [comment]
> Hi there, sorry for holding this up, I intended to do some edits myself, but I haven't had time.
> 
> We use the same format for all Intl constructors' `locales` parameter, so you need to update them all. Do you want to do this or is it okay if I do that in a few days?

I think this is the list of all those Intl constructors? I can have a go at it.

image

**Comment by RoyalIcing** [comment]
It’s failing on a Markdown linter but not giving any context other than:

~~~
markdownlint-cli2 v0.11.0 (markdownlint v0.32.1)
SyntaxError: Expected double-quoted property name in JSON at position 58
```

**Review by Josh-Cena — APPROVED** [review]
Sorry for the long wait! I made some edits myself to specify another case where the default locale is used, just because based on my experience readers tend to get confused by these logical implications. Thanks for the PR!

**Pull request merged**
