### PR TITLE
Fixes #1910 Switched the flags /gi to /ig

### LINKED ISSUE #1910: Error?
Hi. I have read all about some methods and have come to notice that in the replace method, in the examples part with "global" and "ignore", they use the following syntax:

asd

However, this way the flags are not working for me. Quite the opposite if I change "gi" to "ig".

### PR DESCRIPTION
**Pull request by CreaTorAlexander**
Small fix switched the flags as suggested in #1910

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
@sideshowbarker commented on https://github.com/mdn/content/pull/1930#pullrequestreview-580022079 - would it make sense to close the issue, too?

**Comment by Rumyra** [comment]
I'm happy to approve this - however both `ig` and `gi` are valid and both work - @CreaTorAlexander I'm interested to know the situation that presented this issue to you in the first place - there could be something else being overlooked.

Thanks!

**Comment by Rumyra** [comment]
I think I'm answering at the same time as @sideshowbarker in the issue - I'm also happy to close this off :)

**Comment by CreaTorAlexander** [comment]
@Rumyra there were no activity for eight days and I thought it is a 2 minute task. But I was also a bit sceptical because I frequently see RegExp `/gi`

**Comment by Ryuno-Ki** [comment]
@Rumyra Please check the OP in #1910 - It wasn't opened by Alexander.

**Comment by Rumyra** [comment]
Ah yes I see - sorry @CreaTorAlexander 

I'm going to close this pr to match the closing of the issue 👍

**Pull request closed without merging**
