### PR TITLE
Use diff instead of js to mark a diff block

### PR DESCRIPTION
**Pull request by OnkarRuikar**
Reported in https://github.com/orgs/mdn/discussions/158 (PR12)

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
I think this _actually_ denotes a "change" and using two code blocks makes it lose the point. What about changing the language to `diff` instead?

**Comment by OnkarRuikar** [comment]
> What about changing the language to `diff` instead?

I think this will require a PR in yari to load `diff` along with other languages for the diff highlighting. And this is the only block in mdn/content that has diff. So it won't be worth it. :thinking: 

We can simply mark the block as `text` or `plain` though. @teoli2003 wdyt?

***
@teoli2003 deemed this as a case of "example-bad" vs "example-good".
> This is an alternative to "example-bad" and "example-good", that we use everywhere else.

We are conveying the tampering in code comment. Instead of code comment we can have it outside the block.

**Comment by OnkarRuikar** [comment]
> `diff` is a super small component (605 bytes), so loading it is pretty low-cost.

But 'should we support diff blocks on mdn/content' will require a separate community discussion and some approvals.
I have no idea if this has been discussed in the past.

**Comment by teoli2003** [comment]
Yeah, let's put a diff, instead. You are right @Josh-Cena.

I think we should add glsl and diff to the prism syntaxes (but not webidl).

**Comment by OnkarRuikar** [comment]
I've reverted the changes and marked it as diff.

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by teoli2003** [comment]
Yes, but we have to pay attention to complexity too. If the infrastructure is too complex, it is more likely to be less maintained and less stable. Dev resources are scarce, and we have to be sure to have infrastructure as light as possible (but not lighter).

**Comment by Josh-Cena** [comment]
I think I'll eventually help out on Yari as well, just so I can write my content better 😄 (As soon as I have the time...)

**Pull request merged**
