### PR TITLE
Fix comma splicing

### PR DESCRIPTION
**Pull request by Peter-Schorn**
Fixed comma splice.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
This is a widespread pattern in all HTML categories tables. Let's update it for all, or update it for none.

**Comment by Peter-Schorn** [comment]
> Let's update it for all

How do I that that?

**Comment by Josh-Cena** [comment]
If you are doing it in GitHub UI, you can click <kbd>.</kbd>, which will open up a VS Code instance in your browser. You can then search for `<td>None,`, which will reveal all occurrences that need fixing.

**Comment by Josh-Cena** [comment]
Hi @Peter-Schorn do you plan to fix the other occurrences?

**Comment by Peter-Schorn** [comment]
Sorry for the delay. I believe that I have fixed all occurrences. Please let me know if there is anything I'm missing.

**Review by Josh-Cena — APPROVED** [review]
Great work, thanks! Congratulations on your first contribution here—welcome aboard!

**Pull request merged**
