### PR TITLE
Learn node js a to z

### PR DESCRIPTION
**Pull request by AugustinMauroy**
#### Summary
My change adds content on NodeJS. It is not complete but I count on the help of the MDN community to finish and fix my potential error.

--------------------------------------
#### Motivation
I made this change because it lacks a nodeJS tutorial.

--------------------------------------
#### Supporting details
https://nodejs.org/en/
https://www.npmjs.com

--------------------------------------
#### Related Issues
There is no problem

--------------------------------------
#### Metadata
- [x] Add a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

--------------------------------------
Have a good day everyone.

### CODE REVIEW

**Review by MrBrain295 — COMMENTED** [review]
`var` is being replaced with `let` and `const` but this still uses `var`.

**Review by OnkarRuikar — COMMENTED** [review]
A few nitpicks. 
Refer similar tutorial [page about React](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started) and [its markdown code](https://github.com/mdn/content/edit/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md) to get get the idea about indentations and the layout.

**Comment by AugustinMauroy** [comment]
> A few nitpicks.
> Refer similar tutorial [page about React](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started) and [its markdown code](https://github.com/mdn/content/edit/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md) to get get the idea about indentations and the layout.

I am a start if you have time or know people who can made the correction.

A.M.

**Comment by schalkneethling** [comment]
Hi @AugustinMauroy, thank you so much for your pull request and for suggesting new content for MDN Web Docs. Adding new content to MDN Web Docs needs to go through a process to ensure that, 1) it fits with the goals of MDN Web Docs and 2) that the community and we will be able to maintain the new documentation going forward.

Therefore, we would appreciate it if you could open a discussion on https://github.com/mdn/mdn-community/discussions/categories/content-suggestions detailing your reasoning for adding these docs and how we can ensure it is kept up to date.

From there, we can openly discuss the pros and cons and come to a collective conclusion. Should we decide to add these docs to MDN Web Docs, we will move from a discussion to a concrete, actionable, and agreed-upon issue. The last step is to have a pull request such as this to add said content.”

**Pull request closed without merging**
