### PR TITLE
fix flaws server-side/express_nodejs/mongoose

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by peterbe** [comment]
Making this PR uncovered some bugs in Yari to do with fixing fixable flaws and images. 
I was able to create this PR as a way of testing https://github.com/mdn/yari/pull/2263

**Comment by chrisdavidmills** [comment]
Attaching @hamishwillee just in case he didn't see this (I think the CODEOWNERS should've taken care of it, but...)

**Comment by hamishwillee** [comment]
@peterbe This looks great but _only_ the PNG files are rendering when I build locally. The jpgs are not - though I can see they are present. Am I missing something?

**Comment by peterbe** [comment]
@hamishwillee The bug with serving `.jpg` files is solved in Yari now. So it should work fine. 
r?

**Comment by peterbe** [comment]
@hamishwillee ping. r?

**Comment by hamishwillee** [comment]
Sorry @peterbe, I have been on holiday. Will test Monday.

**Review by hamishwillee — APPROVED** [review]
@peterbe Yes, all works great now thanks.

**Pull request merged**
