### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by nievx**
> What was wrong/why is this fix needed? (quick summary only)

> Issue number (if there is an associated issue)

> Anything else that could help us review it

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks for this PR! It looks like you are personally associated with the link you are adding. Can you let us know why this is a notable website that should get a link on this page?

**Review by sideshowbarker — COMMENTED** [review]
Sorry, no. Nobody has audited the existing list of sites here, and without somebody checking them all one by one, we don’t really know that they’re appropriate sites for MDN to be linking to. And so at this point we also don’t need to be adding anything new to the list that is just going to increase the number that we’d need to go back and check again later.

**Comment by sideshowbarker** [comment]
oops, sorry @wbamberg I hadn’t seen that you’d already commented. Lemme know if you want this re-opened — but personally I would prefer that we just remove that entire list of links at this point. It’s not essential to have it in the article, and without checking each of those sites (and continuing to check them periodically), it seems to me we have no way of knowing whether any of them might be completely inappropriate for MDN to be linking to (e.g., domain had subsequently been bought by some scammer, adult site, gambling, whatever).

**Comment by wbamberg** [comment]
> personally I would prefer that we just remove that entire list of links at this point

Yes, I agree with this. I'm always unhappy with lists of links in our pages.

**Comment by sideshowbarker** [comment]
> Yes, I agree with this. I'm always unhappy with lists of links in our pages.

OK, thanks — opened #7145

**Pull request closed without merging**
