### PR TITLE
add interactive map example from examples repo

### PR DESCRIPTION
**Pull request by hirehamir**
This commit seeks to add https://github.com/mdn/interactive-examples/pull/1855.

> What was wrong/why is this fix needed? (quick summary only)

There's a new interactive example for maps. This pull request seeks to publish it.

> Anything else that could help us review it

This is the pull request from the interactive examples repository: https://github.com/mdn/interactive-examples/pull/1855.

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thanks @hamirmahal ! I think this should have a blank line before the macro call:

```
The **`Map`** object holds key-value pairs and remembers the original insertion
order of the keys. Any value (both objects and
{{glossary("Primitive", "primitive values")}}) may be used as
either a key or a value.

{{EmbedInteractiveExample("pages/js/map.html", "taller")}}
```

...so we get a bit of space before the example:

*******

Screen Shot 2021-06-30 at 7 31 56 PM

**Comment by hamirmahal** [comment]
You're welcome, @wbamberg! I added the blank line.

**Review by hirehamir — COMMENTED** [review]
You're welcome, @wbamberg! I added the blank line.

**Review by wbamberg — APPROVED** [review]
thanks @hamirmahal !

**Comment by hamirmahal** [comment]
You're welcome, @wbamberg! Happy to help.

**Pull request merged**
