### PR TITLE
Correct part of the accesskey attribute doc

### LINKED ISSUE #2565: Issue with "accesskey": (Chrome for Linux keyboard combo incorrect)
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey

#### What information was incorrect, unhelpful, or incomplete?
I think the accesskey table is incorrect. According to https://en.wikipedia.org/wiki/Access_key, Chrome for Linux accesskey combo is `Alt + key`, not `Shift + Alt + key`.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/global_attributes/accesskey`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/accesskey/index.html
* Last commit: https://github.com/mdn/content/commit/74a4a9283e1aa5c7f23e31c142010f7e539f736f
* Document last modified: 2021-02-10T17:57:43.000Z

</details>

### PR DESCRIPTION
**Pull request by NegiAkash890**
This fixes typo in the page . This commit is to address issue fix #2565 .

### CODE REVIEW

**Comment by avivmu** [comment]
You should [link the issue in this PR](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)

**Comment by NegiAkash890** [comment]
> You should [link the issue in this PR](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)

I have done it : ) .

**Comment by avivmu** [comment]
Try adding 

> fix #2565 

to the PR description. 
[This is the relevant part](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword):

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message (please note that the pull request must be on the default branch).

**Comment by NegiAkash890** [comment]
> Try adding
> 
> > fix #2565
> 
> to the PR description.
> [This is the relevant part](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword):
> 
> > You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message (please note that the pull request must be on the default branch).
> 
> Right now it's still not linked:
> image

Thanks ; )

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
