### PR TITLE
Added Microsoft Edge to the list of browsers.

### PR DESCRIPTION
**Pull request by Reezaali**

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
This change doesn’t seem necessary. If we list Edge, why not also Brave, or Opera, or other Blink/Chromium-based browsers?
Maybe we should drop the whole _like Firefox, Microsoft Edge, Safari, or Chrome_ part, and just have _It is recommended that you use a modern browser when working through these tutorials._ — because the point is _modern_ part is the real point.

**Comment by chrisdavidmills** [comment]
@sideshowbarker I told Reeza he could add this to the page. My reasoning is as follows:

1. Edge in particular is a major browser, but it is also going to be available on many people's machines by default. It would not be great for someone to be led to believe that they need to download a different browser to run through our course, whe they've already got Edge available.
2. Microsoft is a major contributor to MDN, the PAB, and the OWD. So it is partly political.
3. I'd prefer to not just say "use a modern browser" without giving examples. Some people might not be sure what the browsers are called, and what they need. Also, it is useful to plant that seed early in someone's learning that there are different browsers, and that they might need to try their code out in different ones.
4. I am happy really for us to list multiple browsers, as long the list doesn't get silly or confusing. If a Brave rep came here and asked to add Brave, I've probably be OK with it. If it did turn into a silly edit war, I'd probably be forced to just get rid of the list and just say "modern browser", but I'd rather not do that (see 3.)

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
@Reezaali mostly looks good. One question — is it a branding requirement to say "Microsoft" before "Edge"? We don't list the company names beore the other browsers, so I'd rather not do that for Edge either.

**Comment by sideshowbarker** [comment]
> @sideshowbarker I told Reeza he could add this to the page. My reasoning is as follows:
> …

Ah OK, yup — that all makes sense

**Comment by Reezaali** [comment]
@chrisdavidmills and @sideshowbarker thank you for the feedback. I've adjusted the text.

**Review by chrisdavidmills — APPROVED** [review]
LGTM, cheers @Reezaali !

**Pull request merged**
