### PR TITLE
fix: remove inline status macros from unmaintainable pages

### PR DESCRIPTION
**Pull request by OnkarRuikar**
The BCD synchronization bot can not update inline status macros on the glossary, guide, and landing pages where the `browser-compat` query is not present. For example, the features `Sec-Purpose` header, `EXT_float_blend`, iframe `loading`, `device-memory`, etc. are not experimental anymore. But these features have been tagged experimental in such pages.

Removing inline status macros from the glossary, guide, and landing pages where the browser compatibility info query is not present.

### CODE REVIEW

**Review by fred-wang — APPROVED** [review]
LGTM for @mdn/content-mathml

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
While it's fine to remove experimental badges, I don't think there's need to remove deprecated/non-standard, since they would never be un-deprecated in the future.

**Comment by Josh-Cena** [comment]
Some of these pages are "landing pages by nature". It wouldn't be too hard for the bot to hardcode their structure (e.g. on the HTTP headers page we can look for `{{HTTPHeader("x")}}` in a DL).

**Comment by OnkarRuikar** [comment]
> I don't think there's need to remove deprecated/non-standard, since they would never be un-deprecated in the future.

I've left deprecated as it is. But the non-standard ones could become standard one day, right?

>  It wouldn't be too hard for the bot to hardcode their existence and/or structure (e.g. on the HTTP headers page we can look for {{HTTPHeader("x")}} in a DL).

Properties can be retrieved from DLs without any issues, but when the page doesn't provide the corresponding BCD location(the `browser-compat` query), it becomes hard to locate the BCD data. The same property could be from CSS, SVG, or HTML. The property could be a normal font property or property used inside `@font-face` at-rule.\
We'll need a volunteer to monitor the page changes and update the landing page snapshots, which is not desirable in the long run. Should we limit the statuses to the reference pages only?

**Comment by Josh-Cena** [comment]
> But the non-standard ones could become standard one day, right?

Possible bug highly unlikely. Most "new" features are standard track and non-standard ones are actually just legacy.

I don't know how the script works currently, but I imagine it can do the following: for each entry in `http.header.X`, search for the corresponding `- {{HTTPHeader("X")}}` substring on the `HTTP/Headers` page, and replace it with `- {{HTTPHeader("X")}} ${expectedMacros.join(" ")}`. Similar for the other landing pages that contain an exhaustive list of a BCD group. Does that make sense?

Alternatively, if it's not possible to index the replacement by BCD keys, because we can't know beforehand what features are present on this page (for example, for CSS module pages), we can index the replacement by macro calls instead: first look for all `- {{cssxref("x")}}` substrings, then lookup `css.whatever.x`, and replace the substring with `- {{cssxref("x")}} ${expectedMacros.join(" ")}`.

**Review by Josh-Cena — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
