### PR TITLE
Reinstate Mozilla/Firefox/Privacy redirects and add more

### PR DESCRIPTION
**Pull request by annevk**
This reverts a tiny part of #4744 and adds more redirects as redirects are per-document.

### CODE REVIEW

**Comment by annevk** [comment]
(I'm not sure what happened above, I requested neither of those things as far as I know.)

**Review by peterbe — APPROVED** [review]

**Comment by peterbe** [comment]
> (I'm not sure what happened above, I requested neither of those things as far as I know.)

I don't know what you're referring to here.

**Comment by annevk** [comment]
This:

> annevk requested a review from mdn/core-yari-content as a code owner 6 minutes ago 
> annevk requested review from chrisdavidmills and removed request for mdn/core-yari-content 6 minutes ago

**Comment by peterbe** [comment]
> This:
> 
> > annevk requested a review from mdn/core-yari-content as a code owner 6 minutes ago
> > annevk requested review from chrisdavidmills and removed request for mdn/core-yari-content 6 minutes ago

Reviewers are automatically picked by the configuration around the CODEOWNERS file. 

Weird that it phrases it as if *you* had done those actions.

**Pull request merged**
