### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by neo-clj**
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by sideshowbarker** [comment]
Lacking any accompanying explanation about what’s wrong with the existing wording, it’s not clear to me at least that this change is a clear improvement.

**Comment by Javad-93** [comment]
"has affect" is not correct; because "affect" is a verb in its simple form. The expression should be replaced by something like "has an effect" or "is effective" or "affects", etc.

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
> "has affect" is not correct; because "affect" is a verb in its simple form. The expression should be replaced by something like "has an effect" or "is effective" or "affects", etc.

ah yeah — Thanks for clarifying

**Comment by sideshowbarker** [comment]
Javad, Thanks much for catching this, and congrats on landing your first docs change here — welcome aboard 🎉

**Comment by Javad-93** [comment]
Thank you very much!

**Pull request merged**
