### PR TITLE
Fetch post api docs

### PR DESCRIPTION
**Pull request by Abhishek01039**

### CODE REVIEW

**Comment by avivmu** [comment]
This PR is wrong. From the [specs](https://fetch.spec.whatwg.org/#concept-request-cache-mode):

> Unless stated otherwise, it is "default".

Which makes sense (the default is `"default"`)

**Comment by Abhishek01039** [comment]
What do you mean by wrong?
should we change the `no-cache` to `default`?

**Comment by avivmu** [comment]
From [the docs](https://developer.cdn.mozilla.net/en-US/docs/Web/API/Fetch_API/Using_Fetch#supplying_request_options):

>   // Default options are marked with *

So the code as it now is okay, since `"default"` is marked with *, and that is indeed the default value for the cache option

**Comment by Abhishek01039** [comment]
Sure Thanks for the information

**Pull request closed without merging**
