### PR TITLE
Updated regexp for Processing a text file line by line Fetch api

### LINKED ISSUE #24749: wrong regexp
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

### What specific section or headline is this issue about?

Processing a text file line by line

### What information was incorrect, unhelpful, or incomplete?

`const re = /\n|\r|\r\n/gm;` would match `\n` or `\r` first before the actual `\r\n` returning unnecessary empty string for each such sequence
updating it to `const re = /\r\n|\n|\r/gm;` solves the issue on windows

### What did you expect to see?

`const re = /\r\n|\n|\r/gm;`

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/fetch_api/using_fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fetch_api/using_fetch/index.md
* Last commit: https://github.com/mdn/content/commit/c88a329069328522a5c20c054f9dbced9967dbd4
* Document last modified: 2023-02-20T08:12:58.000Z

</details>

### PR DESCRIPTION
**Pull request by hound77**
### Description

Updated regexp for Processing a text file line by line

### Motivation
Updated regexp for Processing a text file line by line using fetch api docs

const re = /\n|\r|\r\n/gm; would match \n or \r first before the actual \r\n returning unnecessary empty string for each such sequence
updating it to const re = /\r\n|\n|\r/gm; solves the issue.

### Related issues and pull requests

Fixes #24749

### CODE REVIEW

**Comment by hound77** [comment]
@Elchi3 @teoli2003 please review the pr

**Comment by hound77** [comment]
@Elchi3 can you please review this pr.

**Comment by wbamberg** [comment]
Thanks for your PR, @hound77 !

> @Elchi3 @hamishwillee @Josh-Cena can you please review this pr.

I appreciate that you're keen to get your PR reviewed and merged, but please don't do this. We get a lot of PRs to this repo and look at all of them as soon as we have the time. You don't need to ping reviewers explicitly.

**Comment by hound77** [comment]
> Thanks for your PR, @hound77 !
> 
> > @Elchi3 @hamishwillee @Josh-Cena can you please review this pr.
> 
> I appreciate that you're keen to get your PR reviewed and merged, but please don't do this. We get a lot of PRs to this repo and look at all of them as soon as we have the time. You don't need to ping reviewers explicitly.

I am sorry @wbamberg. I am new to open source so wasn't aware of this. will keep in mind going forward.

**Review by Josh-Cena — APPROVED** [review]
LGTM and I made some more refactors. Thank you and welcome to MDN :)

**Comment by wbamberg** [comment]
> > Thanks for your PR, @hound77 !
> > > @Elchi3 @hamishwillee @Josh-Cena can you please review this pr.
> > 
> > 
> > I appreciate that you're keen to get your PR reviewed and merged, but please don't do this. We get a lot of PRs to this repo and look at all of them as soon as we have the time. You don't need to ping reviewers explicitly.
> 
> I am sorry @wbamberg. I am new to open source so wasn't aware of this. will keep in mind going forward.

No worries @hound77 ! And as Josh says, welcome to MDN.

**Pull request merged**
