### PR TITLE
Remove mentions of Modernizr in feature detection page

### LINKED ISSUE #26852: Get rid of Modernizr in the Feature Detection page
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Feature_detection

### What specific section or headline is this issue about?

Using Modernizr to implement feature detection

### What information was incorrect, unhelpful, or incomplete?

Modernizn's last news on their website was in 2017. Their last release on github was in Feb 2022. It feels to me like the development has slowed down considerably and I'm not sure MDN should continue talking about it on the feature detection article.

### What did you expect to see?

I expect MDN not to mention frameworks or libraries that are bound to become outdated fairly fast in our fast moving world of web development.
The rest of the article is very good. I just think the section about modernizr should be deleted.

### Do you have any supporting links, references, or citations?

- Last news on the website from 2017: https://modernizr.com/news/
- Last release on github from Feb 2022: https://github.com/Modernizr/Modernizr/releases

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by captainbrosset**
### Description

Fixes #26852.
This PR removes the mentions of Modernizr on the feature detection page.

### Motivation

Modernizn's last news on their website was in 2017. Their last release on github was in Feb 2022. It feels to me like the development has slowed down considerably and I'm not sure MDN should continue talking about it on the feature detection article.

I expect MDN not to mention frameworks or libraries that are bound to become outdated fairly fast in our fast moving world of web development.
The rest of the article is very good. I just think the section about modernizr should be deleted.

### Additional details

N/A

### Related issues and pull requests

#26852.

### CODE REVIEW

**Comment by wbamberg** [comment]
There are a few other pages that recommend Modernizr, do you think we should update them too while we are at it?

files/en-us/learn/tools_and_testing/cross_browser_testing/javascript/index.md
files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
files/en-us/web/api/eventtarget/addeventlistener/index.md
files/en-us/web/progressive_web_apps/responsive/mobile_first/index.md
files/en-us/learn/forms/html_forms_in_legacy_browsers/index.md
files/en-us/web/guide/mobile/a_hybrid_approach/index.md

**Comment by bsmth** [comment]
>do you think we should update them too while we are at it?

I reckon that's a good idea. I can pick this up as a follow-up if we don't want to block this PR.

**Comment by Josh-Cena** [comment]
@bsmth, it's better if you could send a PR (could be draft) before merging this so we don't forget. Otherwise we would need to open a new issue to track this, which I'm reluctant to do so.

**Comment by Josh-Cena** [comment]
Since there's #27458, @wbamberg @bsmth can we merge this one now?

**Review by bsmth — APPROVED** [review]
Thanks all, leaving my +1 here with a follow-up for removing other mentions cross-linked.

**Comment by captainbrosset** [comment]
Thanks so much Brian for merging and following up. This PR had fallen to the bottom of my prio list.

**Pull request merged**
