### PR TITLE
Fix issue 28418: Add a page for HTMLSelectElement.value

### LINKED ISSUE #28418: No page for HTMLSelectElement.value
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

### What specific section or headline is this issue about?

_No response_

### What information was incorrect, unhelpful, or incomplete?

While doing the Svelte tutorial (part: [*Select bindings*](https://learn.svelte.dev/tutorial/select-bindings)), I had difficulties to understand that the `value` attribute of `<selected>` always contains the value of the selected `<option>`.

In fact the [MDN article about the `<select>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) doesn't mention `value` as an attribute of `<select>` nor does it describe the above mentioned relation between the values of `<selected>` & its `<options>`.

### What did you expect to see?

I expected to see...
1. something that doesn't only describe that the options have `value` attributes, but the `<selected>` element as well.
2. a description of the relation between the value of `<selected>` & its `<options>`.

### Do you have any supporting links, references, or citations?

What helped me to understand & try out the relation (as mentioned above) was the interactive example of [w3schools Select value Property](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_select_value).

```html
<!DOCTYPE html>
<html>
<body>

<form>
  Select your favorite fruit:
  <select id="mySelect">
    <option value="apple">Apple</option>
    <option value="orange">Orange</option>
    <option value="pineapple">Pineapple</option>
    <option value="banana">Banana</option>
  </select>
</form>

<p>Click the button to change the selected fruit to banana.</p>

<button type="button" onclick="myFunction()">Try it</button>

<script>
function myFunction() {
  let val = document.getElementById("mySelect").value
  alert(val)             // (*)
}
</script>

</body>
</html>
```

I added the (*)-line so that I could see the changing value of `<selected>` in action (depending on the selected option.

### Do you have anything more you want to share?

I'm sure that the relation between `<select>` and its `<options>` is described somewhere (on a lower level(?)) - probably some article that describes general behavior of form elements.
But (especially for a beginner - like me) it would be super helpful to at least have a link to such an article - or better: a description right in the relation right in this article.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/select`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/select/index.md
* Last commit: https://github.com/mdn/content/commit/07f0cf4375aaa02e1071d8bd0e8518db7609b7a9
* Document last modified: 2023-07-17T23:05:13.000Z

</details>

### PR DESCRIPTION
**Pull request by wbamberg**
Fixes https://github.com/mdn/content/issues/28418.

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
Thanks Will, looks good to me and could be merged as is. 

I would have talked about the fact that `value` is settable as well, though. To me the page reads a bit like this property would be read-only which it isn't.

**Comment by wbamberg** [comment]
> Thanks Will, looks good to me and could be merged as is.
> 
> I would have talked about the fact that `value` is settable as well, though. To me the page reads a bit like this property would be read-only which it isn't.

AFAIK we only routinely indicate read-only-ness, not read-write-ness. It feels odd just to say "this can be set" without indicating that the use case for setting it is, and I am not sure what that would be. Do you have any suggestions for this?

**Comment by OnkarRuikar** [comment]
> It feels odd just to say "this can be set" without indicating that the use case for setting it is, and I am not sure what that would be. Do you have any suggestions for this?

The spec does say "Can be set, to change the selection." Use cases could be:
- On edit settings screen you want to prepopulate all the inputs including select boxes.
- In a game you want to randomly select an option from a looong options list, e.g. https://jsfiddle.net/8by7zckj/1

**Review by Elchi3 — APPROVED** [review]
Thanks Will! 👍

**Pull request merged**
