### PR TITLE
Add note about module not yet installed

### PR DESCRIPTION
**Pull request by josephrmartinez**
### Description

Running the program exactly as-is at this point will return the following error: 
Error: Cannot find module 'express-validator'
The tutorial either needs to instruct people to install express-validator or comment out the code for now.

### Motivation

Following the tutorial exactly as written should not result in errors. Another solution would be to not include the express-validator line at this point, but add it at a later time when the tutorial actually requests installing and using the module.
const { body, validationResult } = require("express-validator");

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
If express-validator is not used in this page anyway, we should just remove the import line.

**Comment by hamishwillee** [comment]
Thank you - good catch.

I would like to fix this by not having the line in the first place. That means up in the [controller section](https://pr26843.content.dev.mdn.mozit.cloud/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Home_page#controller) make the following removals, and undo your other bits.

image

The validator installation is properly covered in the forms tutorial, so this should be a good fix.

**Comment by hamishwillee** [comment]
PS Do you mind making the change?

**Comment by josephrmartinez** [comment]
Will do!

**Comment by josephrmartinez** [comment]
Opened new pull request #26859

**Pull request closed without merging**
