### PR TITLE
Move files to /css_background_and_borders

### LINKED ISSUE #8017: Content bug: The CSS_Background_and_Borders directory is misspelled
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Border-image_generator
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Border-radius_generator
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/box-shadow_generator

## Specific page section or heading?

Their URL

## What is the problem?

These pages are in the CSS_Background_and_Borders directory, but it seems a misspell of CSS_Backgrounds_and_Borders.

## What did you expect to see?

They should be in 
/docs/Web/CSS/CSS_Backgrounds_and_Borders/
(which already exists) instead of
/docs/Web/CSS/CSS_Background_and_Borders/

### PR DESCRIPTION
**Pull request by AnilSeervi**
Fixes #8017

### CODE REVIEW

**Comment by AnilSeervi** [comment]
Can anyone assist me with the redirects.
Its way too large to be edited with Github UI.

**Comment by AnilSeervi** [comment]
I've edited the `_redirects.txt` from vscode web.
Pressing `.` period on any repo or file opens vscode right away in the web, cool feature.

**Comment by hamishwillee** [comment]
> Can anyone assist me with the redirects.
> I've edited the _redirects.txt from vscode web.

Yes. Don't do this.

Always use yari for this - it is simply too easy to break otherwise:
- if moving a file: https://github.com/mdn/content#moving-one-or-more-documents
- If you deleted a file or for some other reason need a redirect where you aren't doing the moving: https://github.com/mdn/content#redirecting-a-document

**Comment by AnilSeervi** [comment]
> 
> 
> > Can anyone assist me with the redirects.
> > I've edited the _redirects.txt from vscode web.
> 
> Yes. Don't do this.
> 
> Always use yari for this - it is simply too easy to break otherwise:
> 
>     * if moving a file: https://github.com/mdn/content#moving-one-or-more-documents
> 
>     * If you deleted a file or for some other reason need a redirect where you aren't doing the moving: https://github.com/mdn/content#redirecting-a-document
> 
> 
> I would undo the redirect changes you did and do them again as above. Can't comment on the specific move.

Okay, I'm going to open another PR with changes done following that procedure.

**Pull request closed without merging**
