### PR TITLE
change to the correct uses

### LINKED ISSUE #21515: initial value uses are inverted
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/initial_value

### What specific section or headline is this issue about?

Initial value

### What information was incorrect, unhelpful, or incomplete?

For [inherited properties](https://developer.mozilla.org/en-US/docs/Web/CSS/inheritance#inherited_properties), the initial value is used on all elements, as long as no [specified value](https://developer.mozilla.org/en-US/docs/Web/CSS/specified_value) is supplied.
For [non-inherited properties](https://developer.mozilla.org/en-US/docs/Web/CSS/inheritance#non-inherited_properties), the initial value is used on the root element only, as long as no [specified value](https://developer.mozilla.org/en-US/docs/Web/CSS/specified_value) is supplied.

### What did you expect to see?

For [non-inherited properties](https://developer.mozilla.org/en-US/docs/Web/CSS/inheritance#non-inherited_properties), the initial value is used on all elements, as long as no [specified value](https://developer.mozilla.org/en-US/docs/Web/CSS/specified_value) is supplied.
For [inherited properties](https://developer.mozilla.org/en-US/docs/Web/CSS/inheritance#inherited_properties), the initial value is used on the root element only, as long as no [specified value](https://developer.mozilla.org/en-US/docs/Web/CSS/specified_value) is supplied.

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/CSS22/cascade.html#specified-value

### Do you have anything more you want to share?

this is what the page said in 2015:  [link](https://web.archive.org/web/20150606094330/https://developer.mozilla.org/en-US/docs/Web/CSS/initial_value),  and it's similar to my approach.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/initial_value`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/initial_value
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/initial_value/index.md
* Last commit: https://github.com/mdn/content/commit/b6bb952fed5608a2c6d0e75d4ab56de11aa10548
* Document last modified: 2022-10-05T21:52:05.000Z

</details>

### PR DESCRIPTION
**Pull request by Baby-Dvloper**
### Description

I recently came across this definition that someone recently modified in an erroneous and unnecessary way. The previous description of the uses of the initial value was correct according to the specifications.

### Additional details

[specifications](https://www.w3.org/TR/CSS22/cascade.html#specified-value)

### CODE REVIEW

**Comment by wbamberg** [comment]
Looks like they were swapped in https://github.com/mdn/content/pull/21313.

**Comment by TotopoDEV** [comment]
> Looks like they were swapped in #21313.

**Comment by TotopoDEV** [comment]
I'm new to using github so I apologize if I don't use the platform correctly

**Review by wbamberg — APPROVED** [review]
👍 yes, I think you are right and the previous PR was wrong.

@sideshowbarker , since you reviewed https://github.com/mdn/content/pull/21313, would you mind also taking a look at this one? (no criticism implied, I know how it is!)

**Comment by wbamberg** [comment]
Thank you for the fix, @TotopoDEV !

**Pull request merged**
