### PR TITLE
fix bad pre tags in learn/server-side/express_nodejs

### PR DESCRIPTION
**Pull request by peterbe**
I searched out all the pages that has `<code>` inside `<pre>` tags.

### CODE REVIEW

**Comment by peterbe** [comment]
I also removed the redundant `notranslate` classnames.

**Review by hamishwillee — APPROVED** [review]
Thank you so much - saved me a lot of time. I did this for Django last week and stripping out the spans in pre blocks was a complete pain.

**Comment by nschonni** [comment]
@hamishwillee FYI, I was doing that manually too before, but the `flaws` from the commandline actually does this automatically now too

**Comment by hamishwillee** [comment]
@nschonni Great to know. Does flaws from the web page do the same thing? And ... how do I run flaws from the command line? Is it just something like `yarn flaws`?

**Comment by nschonni** [comment]
I've actually never used the web flaws 😄 
There is the `yarn content flaws <slug>` command, but I've been running this `"flaws": "env-cmd --silent cross-env BUILD_OUT_ROOT=build CONTENT_ROOT=files BUILD_FIX_FLAWS=true node node_modules/@mdn/yari/build/cli.js",` to run as a glob from the top of the repo

**Comment by peterbe** [comment]
Confusingly, there are 3 ways to fix fixable flaws. The web UI, the CLI tool, and whilst running `yarn build`. 
They're all good and do the exact same thing. Personally, I quite like the web UI because it feels nice when the problems suddenly go away.

**Pull request merged**
