### PR TITLE
Change use of "standard scripts" to "classic scripts"

### PR DESCRIPTION
**Pull request by Cecil0o0**
### Description

Change use of "standard scripts" to "classic scripts".

### Motivation

I can't help to thank you all for this greatly project, it's quite greatly helpful for me to rebase my knowledge onto MDN web docs created and maintained by writers. And I hope other readers also benefit from my effort on this project. Now my pr is too small, but I believe I will create a useful and medium pr in the future.

The phrase "standard scripts" rarely used on MDN.

Both article [HTMLScriptElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement) and this one [The Script element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) are using "classic scripts" that also used in this article [v8 JavaScript modules](https://v8.dev/features/modules#module-vs-script).

### CODE REVIEW

**Review by hamishwillee — APPROVED** [review]
@Josh-Cena FWIW approving because classic scripts is used more widely in MDN, and these are the only instances of standard script.

I'd be OK with making things standard scripts everywhere too, but that would be up to you.

**Comment by hamishwillee** [comment]
Thanks @Cecil0o0

**Comment by Josh-Cena** [comment]
I also prefer "classic script". I haven't merged this yet because I have discovered a few other instances in a search, but I'm been insanely busy for the past few days to update those. This is definitely the right step to take so thanks to both of you.

**Comment by hamishwillee** [comment]
Oh, sorry, I searched and didn't find any other instances than in this doc (or I would have prompted those to be fixed too). Post process :-)

**Comment by Josh-Cena** [comment]
Not in this doc, but in other docs. In general I would like to propagate a change to the whole MDN if we accept it. But definitely not  requirement.

**Comment by hamishwillee** [comment]
FYI I grepped "standard script" across MDN using Notepad++ and got only this page as a hit for the search term "standard script".

**Comment by Josh-Cena** [comment]
Here's what I see:

image

**Comment by hamishwillee** [comment]
That will teach me to pluralise my search terms. Thanks.

**Comment by hamishwillee** [comment]
@Cecil0o0 If you're interested in fixing those cases too, I'm happy to accept them ^^^

**Pull request merged**
