### PR TITLE
FF91 - Update docs with Feature-Policy: Gamepad and secure context

### PR DESCRIPTION
**Pull request by hamishwillee**
FF91 starts protecting the gamepad API using `Feature-Policy: gamepad`, and also only allows this to be called in secure contexts. This PR
- Adds secure context header to all Gamepad API docs
- Adds docs for the new permission policy
- Adds info about the new permission policy in the API docs that are directly affected.

More context can be found in #6723

### CODE REVIEW

**Comment by Elchi3** [comment]
> * Adds secure context header to all Gamepad API docs

Is it really needed to warn on all pages? Would it be sufficient enough to have the banner on interface pages and navigator.getGamepads?

**Comment by hamishwillee** [comment]
@Elchi3 Technically it depends on how you come to the information. But I agree that almost always you will first come to the interface page, and then to methods etc. I will assume your comment is "policy" and fix up appropriately. Thanks.

**Comment by Elchi3** [comment]
I'm not sure if this is our policy but I think it should be. See also https://github.com/mdn/content/pull/7070

**Review by Elchi3 — APPROVED** [review]
LGTM, nice! 👍

**Pull request merged**
