### PR TITLE
Fix link to CORS credentials

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
#### Summary

URL Fragment was broken because of using old w3c spec. It was pointing to [user-credentials](https://www.w3.org/TR/2020/SPSD-cors-20200602/#user-credentials), now the closest id is in [infrastructure](https://fetch.spec.whatwg.org/#infrastructure).

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by hamishwillee** [comment]
@teoli2003 Was this a good idea?

My concern is that the spec link (and probably the original on that was broken) is not at all useful for a general reader (i.e. you wouldn't be on MDN if you could parse the spec version).
Further, best to keep spec links to the spec table if possible, where they are somewhat tracked and maintained.

Is the spec link actually needed?

**Comment by teoli2003** [comment]
I didn't revisit the pertinence of a link here.

I agree that we should avoid spec links outside the spec table and would happily review (or make) a PR removing this.

**Comment by hamishwillee** [comment]
@NiedziolkaMichal What you do you think re ^^^^. I'm happy to create a PR removing it if you aren't, but would appreciate your opinion.

**Comment by NiedziolkaMichal** [comment]
@hamishwillee That's a good idea. I have removed link and expanded article in PR #14397.

**Comment by hamishwillee** [comment]
Thanks very much. I see that merged already. Good result.

**Pull request merged**
