### PR TITLE
Remove `Document` `lostpointercapture` event

### PR DESCRIPTION
**Pull request by skyclouds2001**
### Description

BCD data update https://github.com/mdn/browser-compat-data/pull/21630

this will delete `Document` `lostpointercapture` event and use the existed `Element` `lostpointercapture` event

### CODE REVIEW

**Review by bsmth — CHANGES_REQUESTED** [review]
Looks good except that the list item is under `Document`, could you move it down so it has `Element` as a parent? Thanks :)

<details>

<summary> Screenshot</summary>

image


</details>

**Comment by skyclouds2001** [comment]
> Looks good except that the list item is under `Document`, could you move it down so it has `Element` as a parent? Thanks :)
> 
> Screenshot

I found they were already under `Element`, so I just sync the list

**Comment by bsmth** [comment]
> > Looks good except that the list item is under `Document`, could you move it down so it has `Element` as a parent? Thanks :)
> > Screenshot
> 
> I found they were already under `Element`, so I just sync the list

Whoops, this has anyway been removed in https://github.com/mdn/content/pull/31220 - sorry for the additional work

**Review by bsmth — APPROVED** [review]
Thank you! 🎉

**Pull request merged**
