### PR TITLE
Updated versions of NodeJs and NPM

### PR DESCRIPTION
**Pull request by pieroguerrero**
### Description

On the instructions to install NodeJS in Ubuntu, I updated the versions of NodeJS and NPM. I also added a generic URL so readers will download the LTS version always.

- LTS version of NodeJs is 16.17.1
- Latest version of NPM is 8.19.2, It works good acording the testing i performed and the [official documentation](https://www.npmjs.com/package/npm/v/8.19.2): 

Screeshot

- [Official documentation with the generic URL:](https://github.com/nodesource/distributions)
Screeshot

### Motivation

A long time ago I finished The Odin Project road map, so I wanted to have this available with good information for other self-taught people.

### Additional details

I tested the instructions on Ubuntu 20.04.

### CODE REVIEW

**Comment by zloirock** [comment]
After a couple of weeks, NodeJS 18 will be the active LTS. LTS of NodeJS 16 will be stopped early, [2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol/), NodeJS 18 will be maintained until 2025.

**Comment by pieroguerrero** [comment]
> After a couple of weeks, NodeJS 18 will be the active LTS. LTS of NodeJS 16 will be stopped early, [2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol/), NodeJS 18 will be maintained until 2025. Since it was not updated for a long time, I think it makes sense to wait for those couple weeks and bump it to 18.

What you propose is a good option. However, NodeJS versions change really fast, the version 12.x listed in the current article was released on 2020. By updating now the version to 16.X will help several people(beginners that check thi article) to work with the latest tools. 
NodeJs 18.X will be released in about one year, time enough to update the again.

**Comment by Josh-Cena** [comment]
Is it possible to do it in a version-unaware way? For example, can we give a "template" for the download command, and tell readers to find the appropriate version themselves, or is there a URL that always points to the LTS version? Imagine if you are to write this section knowing it's not going to be updated for the next 10 years—how would you frame it so it ages well?

**Comment by pieroguerrero** [comment]
> 

Thank you @Josh-Cena. The same is being done for the Windows and macOS versions, so what you say makes sense and I agree.

I will change this PR right now to reflect that.

**Review by hamishwillee — APPROVED** [review]
Thanks @pieroguerrero 

It is indeed hard to keep up with versions. I've been happy enough to keep to a particular version because it makes things easier when people report issues to know what was last tested and shown good. We'll give this a go though - much appreciated.

Next time this iterates we'll be moving to Ubuntu 22.04 as well.

**Comment by pieroguerrero** [comment]
> Thanks @pieroguerrero
> 
> It is indeed hard to keep up with versions. I've been happy enough to keep to a particular version because it makes things easier when people report issues to know what was last tested and shown good. We'll give this a go though - much appreciated.
> 
> Next time this iterates we'll be moving to Ubuntu 22.04 as well.

Awesome, thank you!

**Pull request merged**
