### PR TITLE
Add page types for the WebAssembly section

### PR DESCRIPTION
**Pull request by teoli2003**
This adds page types for WebAssembly. I tried to stay as close as possible as the Web APIs page types for the JS API. There are also `guide` and  `landing-page`, as well as `webassembly-instruction` for the pages with opcodes.

- `webassembly-function`: a global function, that is a method directly under the `WebAssembly` object that acts as a namespace, like `WebAssembly.instantiate()`.
- `webassembly-constructor`: a constructor, like `WebAssembly.Exception()`.
- `webassembly-interface`: a WebAssembly interface, like `WebAssembly.LinkError`.
- `webassembly-instance-property`: an instance property, like `WebAssembly.Instance.exports`.
- `webassembly-instance-method`: an instance method, like `WebAssembly.Exception.getArg()`.
- `webassembly-static-method`: a static method, like `WebAssembly.Module.exports()`.
- `webassembly-instruction`: an instruction, or a set of instructions, like `Wrap`.

This is a part of openwebdocs/project#91

### CODE REVIEW

**Comment by Elchi3** [comment]
> * `webassembly-function`: a global function, that is a method directly under the `WebAssembly` object that acts as a namespace, like `WebAssembly.instantiate()`.

This seems worth talking about. In the JS docs we have the page-types `javascript-namespace` and the methods are of page-type `javascript-static-method`. In API docs, there is `web-api-interface` and `web-api-static-method`.

So, this would introduce a third way of dealing with namespaces. Ideally, we agree on one way to have page-types for namespaces ...

See also the discussion in BCD https://github.com/mdn/browser-compat-data/issues/20114

**Comment by wbamberg** [comment]
> > * `webassembly-function`: a global function, that is a method directly under the `WebAssembly` object that acts as a namespace, like `WebAssembly.instantiate()`.
> 
> This seems worth talking about. In the JS docs we have the page-types `javascript-namespace` and the methods are of page-type `javascript-static-method`. In API docs, there is `web-api-interface` and `web-api-static-method`.
> 
> So, this would introduce a third way of dealing with namespaces. Ideally, we agree on one way to have page-types for namespaces ...
> 
> See also the discussion in BCD [mdn/browser-compat-data#20114](https://github.com/mdn/browser-compat-data/issues/20114)

Unless I'm misreading this:

> a method directly under the `WebAssembly` object that acts as a namespace

...it doesn't mean `instantiate()` acts as a namespace, it means `WebAssembly` acts as a namespace. The sentence is ambiguous though, it would be clearer just to omit "that acts as a namespace". So `webassembly-function` is more like an analog for `web-api-global-function`.

There is an issue here though I think. If the WebAssembly JS docs were still in JavaScript I would probably have made `WebAssembly` a `javascript-namespace`, like `Intl`. But in this proposal `WebAssembly` is a `landing-page`. I'm not keen on that, because `WebAssembly` is a concrete thing, so should get a referency page type. A landing page isn't a docs page for a thing, it's really a nav item, like a sidebar - that is, it's an abstraction.

But if `WebAssembly` is a `javascript-namespace` then we have JS page types outside /JavaScript. Is that OK? If so, does that also mean that `webassembly-instance-method` should instead be `javascript-instance-method`?

Or, since https://github.com/orgs/mdn/discussions/151 suggests that they are more like Web APIs, would it be better to borrow page types from Web/API instead?

**Comment by Elchi3** [comment]
Thanks Will.

I think I am +1 on treating this like a Web API.

Note that Web APIs have no namespace page type and whether they should is discussed in https://github.com/mdn/browser-compat-data/issues/20114. If we assume Web APIs get no "namespace" page-type, then I think it would be like this:

WebAssembly: `web-api-interface` (could be `web-api-namespace`, see the BCD discussion)
WebAssembly.instantiate(): `web-api-static-method`
WebAssembly.LinkError: `web-api-interface`
WebAssembly.Instance.exports: `web-api-instance-property`
WebAssembly.Exception.getArg(): `web-api-instance-method`
WebAssembly.Module.exports(): `web-api-static-method`

For statics, I guess `_static` should be used in slugs then.

**Comment by Josh-Cena** [comment]
They should definitely be `webassembly-*` and not either `javascript-*` or `web-api-*`. They are implemented by the JavaScript engine, not the browser, so they should not be `web-api-*`, and they are not specced by TC39 either (see the discussion before moving the `WebAssembly` reference from JS docs to Wasm docs)

**Review by caugner — APPROVED** [review]
Naming and (config) changes LGTM, but I defer to those with more context to align on final names. Prefixing these types with `webassembly-` sounds like a good idea to me.

**Review by wbamberg — APPROVED** [review]

**Pull request merged**
