### PR TITLE
Improve scrollHeight live sample

### LINKED ISSUE #19153: Include solution to checking if content is overflown in clientHeight page
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight

### What specific section or headline is this issue about?

Problems and Solutions

### What information was incorrect, unhelpful, or incomplete?

N/A

### What did you expect to see?

A solution to the problem: How to know if an element is overflown vertically/horizontally

### Do you have any supporting links, references, or citations?

* This answer points out one solution:  https://stackoverflow.com/a/9541579/16071410.

* A solution is also highlighted earlier in the page: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight#:~:text=If%20the%20element%27s%20content%20can%20fit%20without%20a%20need%20for%20vertical%20scrollbar%2C%20its%20scrollHeight%20is%20equal%20to%20clientHeight

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/scrollheight`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/scrollheight/index.md
* Last commit: https://github.com/mdn/content/commit/58906e1e44f6b192e6993d30241403b8a149b7f7
* Document last modified: 2022-06-21T23:04:37.000Z

</details>

### PR DESCRIPTION
**Pull request by evelinabe**
### Description

 ✍️ Improving the scrollHeight live sample

### Motivation

❓ Issue #19153 asked for a solution to check if an element is overflowing horizontally. The example had a working demo, but was missing a 'Result' header, so it was added for clarity. I refactored the example to make it easier to read, changed the layout by removing a border, removing white-space around the info-text, changing the border color on the remaining paragraph to a color that follow WCAG 2.1 AA based on a contrast ratio of 4.5:1 and added the standard "Lorem ipsum"

### Additional details

 🔗 #19153 
 🔗 https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight

### Related issues and pull requests

🔨 Fixes #19153

### CODE REVIEW

**Comment by Josh-Cena** [comment]
I don't think this does anything about #19153. How does this demonstrate checking for overflow?

**Comment by evelinabe** [comment]
Oh, ok. When I checked one of the links the accepted answer where a similar example to this one. Reading it again I can agree that it is asking for just the simplest form of checking overflow. 

I was under the impression that the standard is changing, since the most recent documents I have signed I have actually had to stay at the bottom to be able to sign. It has resonated with me in a strange kind of way, since when you're signing a paper document it's done at the bottom, even if you reread some portions of it. Not that it matters, none if it is a proof that the document is actually being read, just that the user can scroll all the way down. 

I can change that behaviour?

**Comment by Josh-Cena** [comment]
Yeah, I would suggest reverting the scrolling behavior to the previous one—that's the one I would personally recommend. And we also just need a simple example (like, 2-line function) for checking overflow.

**Comment by evelinabe** [comment]
> Yeah, I would suggest reverting the scrolling behavior to the previous one—that's the one I would personally recommend. And we also just need a simple example (like, 2-line function) for checking overflow.

Thanks, I have updated the PR.

**Review by Josh-Cena — APPROVED** [review]
I've self-committed a few changes which IMO are necessary to keep the UX consistent as before. This looks like a great improvement overall; thanks!

**Pull request merged**
