### PR TITLE
init documentation for `ContactAddress` members

### PR DESCRIPTION
**Pull request by skyclouds2001**
### Description

since the `ContactAddress` interface is directly defined in Contact Picker API and no longer inherit from the `PaymentAddress` interface (and the `PaymentAddress` interface has been deprecated and removed from standard)

the most part of content of the `ContactAddress` interface simply copied from the `PaymentAddress` interface and make some content update

also add the `ContactAddress` interface to Contact Picker API group data

### Additional details

see https://developer.mozilla.org/en-US/docs/Web/API/ContactAddress
reference https://w3c.github.io/contact-picker/#contact-address

### CODE REVIEW

**Review by wbamberg — CHANGES_REQUESTED** [review]
Thank you @skyclouds2001 , this is pretty great. One comment only.

Where you said "make some content update", what updates were these, apart from changing the interface name?

**Comment by bsmth** [comment]
(removing myself from review as Will has got it covered, TY!)

**Comment by skyclouds2001** [comment]
> Thank you @skyclouds2001 , this is pretty great. One comment only.
> 
> Where you said "make some content update", what updates were these, apart from changing the interface name?

It is long ago, I remember I didn't make big changes, but some small update about style

**Review by wbamberg — APPROVED** [review]
👍 thank you @skyclouds2001 !

**Comment by wbamberg** [comment]
> > Thank you @skyclouds2001 , this is pretty great. One comment only.
> > Where you said "make some content update", what updates were these, apart from changing the interface name?
> 
> It is long ago, I remember I didn't make big content changes, but some small update about style (meybe)

Fair enough. I couldn't see anything else. Thanks for this and sorry to be slow with the reviews.

**Pull request merged**
