### PR TITLE
Add a new interactive example

### PR DESCRIPTION
**Pull request by asifurrahaman754**
### Description

I have added a new example for javascript.builtins.Intl.PluralRules.select()

### CODE REVIEW

**Comment by asifurrahaman754** [comment]
@Elchi3 hey I am new to this contribution, I am actually not sure why the test failed, please review my pr and kindly tell me what things need to change.

**Comment by Elchi3** [comment]
> @Elchi3 hey I am new to this contribution, I am actually not sure why the test failed, please review my pr and kindly tell me what things need to change.

Hey @asifurrahaman754, welcome to mdn/content! I'm not sure why it was failing but it wasn't your fault. I merged the latest main into this branch and it passes fine now.

**Comment by Elchi3** [comment]
@schalkneethling https://github.com/mdn/interactive-examples/pull/2278 was merged but loading the interactive example shows up as a 404 in this content PR. When will it be available?

**Review by wbamberg — APPROVED** [review]
👍 the example seems to be working now. Thank you @asifurrahaman754 !

**Pull request merged**
