### PR TITLE
chore(api): Remove screenshots from EmbedLiveSample calls

### PR DESCRIPTION
**Pull request by bsmth**
### Description

This PR removes screenshots in `EmbedLiveSample` calls. The screenshots are used in examples that have good browser support, so they serve no purpose that I can see.

### Motivation

Removing binaries from the repository. This is also an opportunity to deprecate the parameter for including screenshots in the live samples.

### CODE REVIEW

**Review by wbamberg — APPROVED** [review]
👍 nice, and +1 to deprecating this argument.

**Comment by bsmth** [comment]
Thanks!

**Comment by wbamberg** [comment]
I still see screenshot arguments in the following page:

/content/files/en-us/web/api/canvas_api/tutorial/basic_usage/index.md
/content/files/en-us/web/api/canvas_api/tutorial/drawing_shapes/index.md
/content/files/en-us/web/api/canvas_api/tutorial/using_images/index.md
/content/files/en-us/web/api/canvasrenderingcontext2d/arc/index.md
/content/files/en-us/web/api/canvasrenderingcontext2d/fillstyle/index.md
/content/files/en-us/web/api/canvasrenderingcontext2d/globalalpha/index.md
/content/files/en-us/web/api/canvasrenderingcontext2d/linecap/index.md
/content/files/en-us/web/api/canvasrenderingcontext2d/linejoin/index.md
/content/files/en-us/web/api/canvasrenderingcontext2d/strokestyle/index.md
/content/files/en-us/web/css/_doublecolon_-moz-list-number/index.md
/content/files/en-us/web/svg/element/fecolormatrix/index.md
/content/files/en-us/web/svg/element/fegaussianblur/index.md

...was it intentional to omit them?

**Comment by yin1999** [comment]
Hey @bsmth. I'm not sure whether the image [`files/en-us/web/api/canvas_api/tutorial/transformations/canvas_grid_translate.png`](https://github.com/mdn/content/blob/490d3ce35967838dc09026f94b9e9264353b7125/files/en-us/web/api/canvas_api/tutorial/transformations/canvas_grid_translate.png) and [`files/en-us/web/api/canvas_api/tutorial/transformations/canvas_grid_rotate.png`](https://github.com/mdn/content/blob/490d3ce35967838dc09026f94b9e9264353b7125/files/en-us/web/api/canvas_api/tutorial/transformations/canvas_grid_rotate.png) have been removed by mistake. There are still references to these two images in the document:

https://github.com/mdn/content/blob/3d9e8e50f02c36bf22f54703c6ff3559bf05edec/files/en-us/web/api/canvas_api/tutorial/transformations/index.md?plain=1#L94
https://github.com/mdn/content/blob/3d9e8e50f02c36bf22f54703c6ff3559bf05edec/files/en-us/web/api/canvas_api/tutorial/transformations/index.md?plain=1#L136

**Comment by bsmth** [comment]
Thank you both for flagging these issues.

>...was it intentional to omit them?

No, I wasn't sure if this pass was comprehensive.

>removed by mistake

Yes I was overzealous with the image removals, my mistake! I'm following up on that with a fix now 🙏🏻

**Pull request merged**
