### PR TITLE
feat: Add content for getDisplayMedia() monitorTypeSurfaces option

### PR DESCRIPTION
**Pull request by chrisdavidmills**
Note: Technical review for this PR has been completed, kindly done by @beaufortfrancois, so it is now ready for editorial review. I'm not going to create a new editorial review PR for this one as it is really small; we'll keep it all in this PR.

---

### Description

Chrome 119 adds desktop-only support for the [`getDisplayMedia()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) `monitorTypeSurfaces` option (see https://chromestatus.com/feature/5558622137876480). This PR adds content for it, as well as tweaking a couple of weird examples that were missing options object definitions.

Other useful links:

- See https://screen-sharing-controls.glitch.me/ for a demo.
- See https://developer.chrome.com/docs/web-platform/screen-sharing-controls/#monitorTypeSurfaces for an explanation of its purpose

### Related issues and pull requests

See https://github.com/mdn/browser-compat-data/pull/21518 for the associated BCD.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@beaufortfrancois, can I ask you to have a quick look at this PR from a technical standpoint? It's only tiny. Thanks!

**Comment by beaufortfrancois** [comment]
> @beaufortfrancois, can I ask you to have a quick look at this PR from a technical standpoint? It's only tiny. Thanks!

LGTM! The only thing I'd add is maybe a link to the external demo https://screen-sharing-controls.glitch.me/ so that readers can experiment with different combinaisons.

**Review by Elchi3 — APPROVED** [review]
Thanks and sorry for being slow!

**Comment by chrisdavidmills** [comment]
> Thanks and sorry for being slow!

@Elchi3 no worries, and thanks muchly!

**Pull request merged**
