### PR TITLE
Include Temml as one of the MathML Tools.

### PR DESCRIPTION
**Pull request by ronkok**
### Description

Add _Temml_ as one of the tools available for MathML. Temml is a TeX math-to-MathML conversion library written in JavaScript.

### Motivation

Temml has been written specifically for MathML-Core.

### Additional details

GitHub repository is at: https://github.com/ronkok/Temml
Demonstration page: https://temml.org/
LaTeX support is shown at: https://temml.org/docs/en/supported.html

### CODE REVIEW

**Review by fred-wang — APPROVED** [review]
Thanks!

**Comment by hamishwillee** [comment]
Thanks @ronkok , but I'm actually going to reject this change.

Generally we try to avoid linking external tools and libraries at all on MDN. Too often they end up linking to unmaintained projects after a few years. The exceptions were we do link tend to be "defacto standards", larger projects that have a maintenance history, or "notable" projects that do something truly exceptional.

This project, while worthy does not meet those requirements.

**Comment by ronkok** [comment]
@hamishwillee, those are valid concerns. Let's see how they apply here:

> Too often they end up linking to unmaintained projects.

[Texzilla](https://github.com/fred-wang/TeXZilla) has not been updated for three years. The recent changes from MathML 3.0 toward MathML-Core are therefore not adopted.

> The exceptions were we do link tend to be "defacto standards"

The current version of MathJax, 3.x, [no longer includes MathML as a native output](https://docs.mathjax.org/en/latest/output/mathml.html). Their docs do give instructions on how to access an internal memory structure built in MathML, but that MathML is now used for internal purposes. They no longer expect it to be used to render math directly. That's if you can get an output using their instructions. My own attempts have failed.

MathJax can be said to be a "defacto standard", but it is today a standard for rendering math in HTML., not in MathML.

When Chromium supports MathML for the first time a month from now, we may actually begin to see MathML used in web pages. Creators of web pages deserve a tool that is up to date and built to purpose. That would be Temml. 

Please reconsider your decision.

**Comment by fred-wang** [comment]
I actually agree with @hamishwillee ; in a previous changes we had already removed many of existing tools and was a bit skeptical about approving it...

So my proposal would be to go one step further: Completely remove the "Tools" section from MDN. Note that [SVG](https://developer.mozilla.org/en-US/docs/Web/SVG#tools) or [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) don't have something comparable.  Instead we can just link to whichever page the Math WG thinks is relevant for MathML Core. That can be [Math Tools](https://www.w3.org/wiki/Math_Tools) or something else, but discussions about how to list and organize the tools can be performed in the WG. If people agree with that, I can prepare a PR.

Some more comments inline.

> Texzilla has not been updated for three years. The recent changes from MathML 3.0 toward MathML-Core are therefore not adopted.

I believe this is not true, most of the MathML 3 simplifications were discussed in the Math CG in 2019 and integrated into TeXZilla already. I personally still plan to maintain TeXZilla. There is a little Mozilla story behind it because it is the successor of itex2MML, which was used in original demos of the [Mozilla MathML project](https://web.archive.org/web/20100702194705/http://www-archive.mozilla.org/projects/mathml/index.html). But I'm fine if it is removed from the MDN list together with the other tools...

> MathJax can be said to be a "defacto standard", but it is today a standard for rendering math in HTML., not in MathML.

I don't really know the recent status of the MathJax project and their plan with native MathML. I still had the impression that people continue to use it as a fallback for browsers without MathML support. If you are right that it's no longer relevant for MathML purpose then probably we should remove it too...

> Creators of web pages deserve a tool that is up to date and built to purpose. That would be Temml.

I'm grateful that you and others are writing tools for MathML Core. I haven't tried Temml myself but my expectations is that developers will start to create or update tools to use MathML once it is released in Chrome. Perhaps I'm wrong, but I suspect there won't be one "defacto standard" to select, at least in the short term. I also don't think it's the role of MDN reviewers to judge what's the most relevant tools would be...

**Comment by bsmth** [comment]
Hi all, thanks for chiming in here. Adding to @hamishwillee's point, the criteria for inclusion has says that self-promoting external links will not be added. You can read more in our [policies for what we write](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/What_we_write#topics_that_dont_belong_on_mdn_web_docs) in our writing guidelines.

Thank you.

**Comment by fred-wang** [comment]
I moved the discussion about MathML Core tools in the Math WG: https://lists.w3.org/Archives/Public/www-math/2022Dec/0009.html 

Once we have a link of MathML Core tools, we can probably use it to replace the Tools section.

@bsmth Thanks. Good point too!

**Comment by ronkok** [comment]
All very good points, and I accept them. I'm deleting this branch.

**Pull request closed without merging**
