### PR TITLE
style of the first example inside `offsetContainer`

### PR DESCRIPTION
**Pull request by Konrud**
A style for the first example has been set. Couldn't find the way to use classes so used inline style instead.

### CODE REVIEW

**Comment by jpmedley** [comment]
@chrisdavidmills This got assigned to me somehow. I'm not adept enough with CSS to review this by looking at it.

**Comment by chrisdavidmills** [comment]
@jpmedley no worries; I've given it to Rachel instead.

**Comment by rachelandrew** [comment]
@Konrud can you give me the background for this change? I feel like I'm missing some info to know why it needed changing, it would be helpful if you include that in any PR so that the reviewer can understand what the aim is. Thanks!

**Comment by Konrud** [comment]
Of course, for a long time, it's been broken and looked like that

ScrollHeightBUG

As you can see from the image above it can't be easily understood what's going on in this image.

So I've tried to fix things up a bit, in order, it will be more obvious for others.

So after the changes, it should look like this:

ScrollHeightBUG-FIX

Please let me know if my explanation cleared things up a bit or made them more confusing.

**Review by rachelandrew — APPROVED** [review]
I wonder if this might be better as an image, but this looks like an improvement to what is there. Thanks!

**Pull request merged**
