### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by DoodleDeBug**

### CODE REVIEW

**Comment by hamishwillee** [comment]
This change doesn't make any difference to the rendered content. Why do you think it is needed?

**Comment by DoodleDeBug** [comment]
When you copy and paste the string into your work for the task, you get an error because of the un-escaped apostrophe, also the one a couple lines below is written in the same way, so this change provides consistency.

image

**Review by hamishwillee — APPROVED** [review]

**Comment by hamishwillee** [comment]
@DoodleDeBug Thank you for explaining the reason.

The main reason I hate this is that I as an author should not have to remember to escape an apostrophe in normal text. And this is normal text - it isn't source code that you're supposed to be copy-pasting into your code. For consistency you could remove the one below. 

I'll accept this one an move on, but I do see it as more hassle than the discussion is worth.

**Comment by DoodleDeBug** [comment]
> @DoodleDeBug Thank you for explaining the reason.
> 
> The main reason I hate this is that I as an author should not have to remember to escape an apostrophe in normal text. And this is normal text - it isn't source code that you're supposed to be copy-pasting into your code. For consistency you could remove the one below.
> 
> I'll accept this one an move on, but I do see it as more hassle than the discussion is worth.

Fair enough, I'll remember that for next time if I see anymore like it :+1:

**Pull request merged**
