### PR TITLE
fix: zero-width spaces `\u200B`

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Review by chrisdavidmills — APPROVED** [review]
LGTM

**Comment by peterbe** [comment]
How did they even get in there?!
Also, is there a point in making it a flaw? Or even something that can break/crash. For example, if you have a whitespace or zero-width whitespace in the `slug:` value in the front-matter, it will crash the builder. This is good because your PR should fail and that's more severe than a humble flaw. 

But what other characters should be ban? Ideas on this one @fiji-flo ?

**Comment by nschonni** [comment]
I think for the slug it's an easier answer, as there is a spec for URLs https://stackoverflow.com/a/7109208/455535

I was taking a look at regexing non-printable characters, but I didn't find a good range yet for cleaning up some of the others in the body of the HTML

**Comment by peterbe** [comment]
What @fiji-flo and I did in https://github.com/mdn/yari/pull/2172 was that we started with at least checking for that particular Unicode character. I.e. specifically \u200B. 
If we can't figure out a sensible range that makes this generic, do you think we can get some serious 90+% progress by at least banning the use of specifically \u200B?
I really don't know how these get in and perhaps it'll never ever be a problem again.

**Comment by nschonni** [comment]
Should discussion on the valid slugs be on a Yari issue or Content? Just think this is probably good to document and a convo on a PR probably isn't discoverable 😄

**Comment by peterbe** [comment]
Great point! Let's go to https://github.com/mdn/yari/discussions Would you mind starting one?

**Comment by nschonni** [comment]
Done https://github.com/mdn/yari/discussions/2197

**Pull request merged**
