### PR TITLE
Add missing specifications sections

### PR DESCRIPTION
**Pull request by GaurangTandon**
The live specifications are here: https://w3c.github.io/selection-api/#dom-selection-modify

I am not sure if my change works or not though. I could not find documentation for the `{{Specifications}}` tag. I noticed that other documentation pages (like the one for `Selection.toString()`) uses them and it works fine, so I just copied from there. Please let me know if there's another way to achieve this correctly. Thanks!

### CODE REVIEW

**Comment by GaurangTandon** [comment]
Based on the preview it looks like my approach was correct 😄

**Comment by Josh-Cena** [comment]
I've discovered a lot more specification links that are not displayed on pages. Do you mind if I add them to this PR?

**Comment by GaurangTandon** [comment]
Sure please go ahead 🙂

**Review by Josh-Cena — APPROVED** [review]
Updated. Great catch on this!

**Comment by GaurangTandon** [comment]
No worries, thanks for the huge update!

**Pull request merged**
