### PR TITLE
update Active locales

### PR DESCRIPTION
**Pull request by newcih**
no zh-cn, only taiwan there, they do not respect chinese mainland

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by SphinxKnight** [comment]
@newcih could you please provide more details about the inactivation of a whole locale for this project? This is a substantive change with a lot more of ramifications. Without further motivation and approval from a larger set of members, this PR should be closed.

**Comment by newcih** [comment]
> @newcih could you please provide more details about the inactivation of a whole locale for this project? This is a substantive change with a lot more of ramifications. Without further motivation and approval from a larger set of members, this PR should be closed.

when i join the tg group，the member always chat something with taiwan independence，you know what，every country declares that there is only one China，the member in that group dont respect us，that group is just a taiwan group，not china group。so，please remove zh-CN

**Comment by newcih** [comment]
> @newcih could you please provide more details about the inactivation of a whole locale for this project? This is a substantive change with a lot more of ramifications. Without further motivation and approval from a larger set of members, this PR should be closed.

zh-CN mean china，but that group is just a taiwan chat group

**Comment by newcih** [comment]
> @newcih could you please provide more details about the inactivation of a whole locale for this project? This is a substantive change with a lot more of ramifications. Without further motivation and approval from a larger set of members, this PR should be closed.

by the way，this group had removed me，so i cant show the history of chat for you。i just say，do not split China。

**Comment by SphinxKnight** [comment]
@newcih thanks for the additional information. However this change bears upon the locale itself on MDN and needs a broader consensus (and larger changes) for this active locale to be removed (I can see [distinct activity and contribution under `zh-cn` directory on mdn/translated-content](https://github.com/mdn/translated-content/commits/main/files/zh-cn))

If there are issues about the localized content under the zh-CN locale, they should be reported on https://github.com/mdn/translated-content/. 

Regarding the chat activity you're mentioning, if this from a Mozilla-provided tool/channel, I'd avise to refer to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/about/governance/policies/participation/) as indicated from [the code of conduct](https://github.com/mdn/content/blob/main/CODE_OF_CONDUCT.md) of both mdn/content and mdn/translated-content.

I am closing this issue for now. Should `zh-CN` locale not have any activity for a long time under the mdn/translated-content or should a consensus be reached about this locale, this, of course, would need reevaluation.

**Comment by newcih** [comment]
god damn mdn dont respect anything

**Comment by newcih** [comment]
>

**Pull request closed without merging**
