### PR TITLE
Mark `caption-side` experimental values

### PR DESCRIPTION
**Pull request by ramiy**
### Motivation

Current browser support:

* [Blink](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/css_properties.json5;drc=c704e9e51bc30032bed14d88d009e33459e25884;l=2457)
* [WebKit](https://searchfox.org/wubkat/rev/5dfffd1d9c0cdf683b9302cd72303bf9e6700921/Source/WebCore/rendering/style/RenderStyleConstants.h#755)
* [Gecko](https://searchfox.org/mozilla-central/rev/90dce6b0223b4dc17bb10f1125b44f70951585f9/servo/components/style/values/specified/table.rs#33)

only `top` and `bottom` values are supported.

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
Thanks for the update @ramiy. If these values are not supported anywhere, I don't think we should even list them. Tagging them as experimental will make people think they are supported _somewhere_, and then they will get confused because they are not even listed in the compat table.

Also, looking at the [spec](https://drafts.csswg.org/css-logical/#caption-side), only `inline-start` and `inline-end` are even defined, so the block variants should surely be non-standard, if we did list them?

But I think we should delete them.

**Comment by ramiy** [comment]
@chrisdavidmills the discussion in https://github.com/web-platform-tests/interop/issues/434#issuecomment-1812137234 .

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills the discussion in [web-platform-tests/interop#434 (comment)](https://github.com/web-platform-tests/interop/issues/434#issuecomment-1812137234) .

@ramiy OK. So it sounds like it is saying that the `block-start` and `block-end` values don't actually exist; it is just that `top` and `bottom` are now redefined so they are writing mode aware? I don't think they should be listed. Maybe just write a comment below the values that say there are two values defined in the spec that are not implemented in any browser, and list them. You could also mention the updated behavior of `top` and `bottom` if you so wished?

**Comment by ramiy** [comment]
@chrisdavidmills from the spec:

> The existing top and bottom values are idiosyncratically redefined as assigning to the block-start and block-end sides of the table, respectively.

**Comment by ramiy** [comment]
Also see https://github.com/w3c/csswg-drafts/pull/9620, I asked to update the spec to properly define the `bloc-*` values.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills from the spec:
> 
> > The existing top and bottom values are idiosyncratically redefined as assigning to the block-start and block-end sides of the table, respectively.

@ramiy I saw that line too, but it doesn't say that `block-start` and `block-end` values exist. It says that `top` and `bottom` values are redefined so that they now assign the caption to the `block-start` and `block-end` sides of the table, respectively. So for example, if [`writing-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode) was set to `horizontal-tb`, a `caption-side` value of `top` would make the caption appear at the top, but if `writing-mode` was `vertical-rl`, the caption would appear on the right-hand side. 

At least, that's how I read it.

To be clear, the change you have proposed in the spec makes sense to me — it is consistent with other places in which logical properties or values are available alongside older non-logical equivalents (like the [`margin`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin) longhand properties, for example).

But it doesn't seem to reflect the state of the spec right now.

**Comment by Loirooriol** [comment]
Yes, `caption-side: block-start` and `block-end` are not in the spec, the CSSWG resolved to drop them in https://lists.w3.org/Archives/Public/www-style/2015Sep/0113.html, it happened in https://github.com/w3c/csswg-drafts/commit/9cbe2c162db95983e1b327d8136ef622ea8c5db9

https://github.com/w3c/csswg-drafts/issues/9623 might re-add them, but for now they shouldn't be on MDN.

**Comment by estelle** [comment]
inline-start and inline-end should be included, with the experimental added.
block-start and block-end should be removed altogether.

either way, this PR is better than what is currently there, so let's get this added, preferably with updates.

see https://drafts.csswg.org/css-logical/#caption-side - The inline values are in the logical properties spec.

**Comment by estelle** [comment]
commited https://github.com/mdn/content/pull/33903, to replace this PR

**Pull request closed without merging**
