### PR TITLE
Updating URL

### LINKED ISSUE #10666: Issue with "Push API": invalid url serviceworke.rs
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Push_API

#### What information was incorrect, unhelpful, or incomplete?

Reference is to "Serviceworker cookbook", not sure what it's supposed to link to but was added with https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630

no combination of servicewok.rs appears to resolve in DNS.

#### Specific section or headline?

Examples

#### What did you expect to see?

Correct URL.

#### Did you test this? If so, how?

Magic of leftclicking on link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/push_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Push_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/push_api/index.md
* Last commit: https://github.com/mdn/content/commit/75406fcc62b0baba2fac2cf2e1071b6ede787eef
* Document last modified: 2021-10-18T15:44:34.000Z

</details>

### PR DESCRIPTION
**Pull request by Rumyra**
The Service Worker Cookbook is no longer available online, however the repository contains a lot of good examples, so linking to that instead.

#### Related issues

Fixes https://github.com/mdn/content/issues/10666

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Maintenance is hard.

I hate to be always suggesting more work, but since that repo isn't maintained any more, and hasn't been for years, I'm not sure we should be linking to it as is.

https://github.com/mozilla/serviceworker-cookbook/issues/312 suggests transferring these examples to MDN, and that still seems like a good idea. Maybe worth a project proposal?

**Comment by h1z1** [comment]
Do you know any of the folks in https://github.com/mozilla/serviceworker-cookbook/issues/312 ?

**Comment by Rumyra** [comment]
> I hate to be always suggesting more work, but since that repo isn't maintained any more, and hasn't been for years, I'm not sure we should be linking to it as is.
> 
> [mozilla/serviceworker-cookbook#312](https://github.com/mozilla/serviceworker-cookbook/issues/312) suggests transferring these examples to MDN, and that still seems like a good idea. Maybe worth a project proposal?

I've been considering this as well - I think possibly I remove in the meantime so we at least don't have a broken link. I do think these examples are valuable and also in unmaintained better off within the mdn ecosystem. I'll see if I can find someone to talk to about moving

**Comment by wbamberg** [comment]
The link was fixed by @sherwino in https://github.com/mdn/content/pull/11396 (thanks!). I think we should file an OWD project to adopt the cookbook into MDN and either close this issue or repurpose it for that project.

**Comment by Rumyra** [comment]
Yeh v happy with that @wbamberg - I made a bit more head way in getting in moved yesterday and will follow up next week 👍

**Pull request closed without merging**
