### PR TITLE
correct EmbedLiveSample IDs

### PR DESCRIPTION
**Pull request by peterbe**
This only makes sense in conjunction with https://github.com/mdn/yari/pull/2490
But it's almost harmless to merge without requiring specific timing.

### CODE REVIEW

**Comment by peterbe** [comment]
@escattone Don't merge yet. I'm going to check if there are more. Doing one more complete build.

**Comment by peterbe** [comment]
@rachelandrew The `CODEOWNERS` file automatically pinged you for a review. But this is best for Ryan since he has the context on the relevant code changes in Yari relating to kumascript rendering. Sorry for the noise.

**Comment by peterbe** [comment]
@escattone Please go ahead and review this. Ideally in conjuction with https://github.com/mdn/yari/pull/2490

**Review by escattone — APPROVED** [review]
@peterbe I went down the same path as you, and discovered these exact same pages that needed fixing. This is great! At some point we need to do the same analysis for the translated-content.

**Pull request merged**
