### PR TITLE
added list item for The box model.

### PR DESCRIPTION
**Pull request by singhtaranjeet**
Box model list item was missing from the list, so added it.

> What was wrong/why is this fix needed? (quick summary only)

List item for box model was not there, so i thought it would be nice to add it into the page

> Issue number (if there is an associated issue)

> Anything else that could help us review it

### CODE REVIEW

**Comment by rachelandrew** [comment]
@singhtaranjeet it looks as if you have added a link to the current page, which isn't something we want to do. As you can see in the test output above this flags as a flaw.

**Comment by singhtaranjeet** [comment]
@rachelandrew ok, got it. 
I did it because i found out it as a normal behavior of the MDN web docs which you can see on the other pages of docs as well.

For example this one is also pointing to itself and giving the indication to the user that, they are on this particular page.
[https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Handling_different_text_directions](url)

**Comment by singhtaranjeet** [comment]
to be specific you can visit this link
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Handling_different_text_directions#in_this_module
In here we have a <li> tag containing an <a> anchor tag, in black color for informing the user about the current page.

I expected the same behavior in below mentioned page as well, but it was not there so i ended up adding the link in the page.
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model#in_this_module

**Comment by rachelandrew** [comment]
I don't think those links should be on any pages. There could be a non-linked item indicating the current page, but a link to the same page is potentially confusing as someone might click it only to find themselves at the top of the page they just read.

**Comment by singhtaranjeet** [comment]
yes you are right.
To improve the user experience we should add non-linked items to indicate the user about the page.

**Comment by singhtaranjeet** [comment]
@rachelandrew should i close this pull request, because as per the flaw: **Link points to the page it's already on** ,
it can't proceed further!

**Comment by sideshowbarker** [comment]
@singhtaranjeet yes, it’d be good if you could go ahead and close this

**Pull request closed without merging**
