### PR TITLE
chore: use . instead of bashism for filecheck CWD

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by peterbe** [comment]
@hamishwillee Is there any chance you can test this out on your `yari` repo on Windows?

**Review by peterbe — APPROVED** [review]
I was able to make https://github.com/mdn/content/pull/2182 with these and things like 
`yarn filecheck files/en-us/web/css/element()/example1.png` worked fine.

**Comment by peterbe** [comment]
I'm tempted to merge this and then @hamishwillee doesn't have to test this. If we get it wrong, we can fix it later.

**Comment by nschonni** [comment]
I looks like he tried it here https://github.com/mdn/yari/issues/2582#issuecomment-772847406

**Comment by peterbe** [comment]
Let's do it!

**Comment by hamishwillee** [comment]
Yes. I did. Fantastic thanks. I've been manually adding this change to my package.json for the last few days and it makes things a lot easier.

**Pull request merged**
