### PR TITLE
Iss2113

### PR DESCRIPTION
**Pull request by CreaTorAlexander**
Removed the paragraph as said in issue #2113

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
@CreaTorAlexander thanks for your efforts here to help fix some bugs!

All of these fixes look correct, so I'm going to merge this. In future however, can you do tw things different?

1. Only fix a single problem per PR — don't lump multiple unrelated fixes into the same PR. In this case it is not so bad, as they are all simple fixes, but when the PRs get any more complex, it can make things really confusing and hard to review.
2. Link to the issue you are fixing clearly in the PR description, otherwse it is harder to find what issue you are fixing than it needs to be.

Thanks again!

**Comment by CreaTorAlexander** [comment]
Yes I will try my best. Actually I am not this familiar with using Github.

**Comment by chrisdavidmills** [comment]
Don't worry too much about it — GitHub is always hard when you start with it. But you'll get there.

**Comment by Ryuno-Ki** [comment]
@CreaTorAlexander If you could outline in detail what was confusing to you this might even become an opportunity to improve our Learn area for GitHub.
What do you think, @chrisdavidmills?

(Ideally open a discussion in mdn/yari first, as they aren't activated here. Refer to this comment, so peterbe et al won't get confused.)

**Pull request merged**
