### PR TITLE
Testing pull169

### PR DESCRIPTION
**Pull request by peterbe**
Please ignore. 
I'm just testing some things related to https://github.com/mdn/content/pull/169

### CODE REVIEW

**Comment by peterbe** [comment]
@bershanskiy Check this out. 
I'm still unsure what's going on but I'm triggering a PR here with your changes from https://github.com/mdn/content/pull/169 plus changes that touch the file attachments, the HTML, and the redirects. So, as you can see, all 3 workflows are running. (plus the `preview.yml` which always runs anyway)

So why am I not getting cache hits on the `node_modules` in all of them?
In fact, take a look at:
1. https://github.com/mdn/content/pull/299/checks?check_run_id=1564299085 vs.
2. https://github.com/mdn/content/pull/299/checks?check_run_id=1564299180

They share the exact same `yarn.lock` and the exact same check-out directory (aka. `$GITHUB_WORKSPACE`)

Cache **miss**
Screen Shot 2020-12-16 at 9 38 56 AM

Cache **hit**
Screen Shot 2020-12-16 at 9 39 38 AM

Why is it different??

**Actually**, in preparation for this comment I debugged it a bit more. Turns out, the `hashFiles()` function yields different results even though the value of `$GITHUB_WORKSPACE` and the `path` to `hashFiles()` are identical. 
It's surely not documented that way. I think I'm going to start a discussion about this on their Discourse. 

I guess, if this is the facts, we have a choice: 

1. One `.yml` workflow for **each** separate "problem space" (e.g. `pr-build.yml`, `pr-filecheck.yml`, `pr-redirects.yml`)
2. One **single** `.yml` file that does multiple things. (e.g. `pr.yml`)

Because if it's all in one file, we only need to do the `cache` and `yarn install` once for all the things that needs the `node_modules`. 
Please stop me if this is premature optimization! :)

**Comment by peterbe** [comment]
Actually, I'm quite attracted to this idea. It's actually perfectly sensible and realistic that a PR on `mdn/content` comes in with changes to the `.html`, a file attachment, and an edit to the `_redirects.txt` too. 
So, if you can have just one big workflow called "PR" (or "Pull Request check") that has 4 steps:

1. A prerequisite that does things like `checkout` and `cache` + `yarn install`
2. A "Build" one that *depends* on the prerequisite one
3. A "Filecheck" one that *depends* on the prerequisite one
4. A "Redirects" one that *depends* on the prerequisite one

And if we do this, we could consider going back to the branch protection setting and require that this whole workflow always passed. 
We'd rely less on `on.paths.` and more on `technote-space/get-diff-action` within.
Shall we give that a go?

**Comment by bershanskiy** [comment]
I agree with the arguments above for going back to a single "PR workflow", I'll update #169 accordingly.

Please note, however the following challenges with `technote-space/get-diff-action`:
- it fails for very large diffs, like shown in https://github.com/mdn/content/pull/382. This edge case exceedingly rare, but I'd still like to cover this case. Fortunately, there is a way: set GitHub Action to continue on diff-action step failure and then check result.
- it behaves oddly on force-push sometimes. This might not be a problem because the PR's base branch is the repo's main branch and no one ever force-pushes to that.

**Comment by peterbe** [comment]
I'm redirecting to a fresh new attempt here: https://github.com/mdn/content/pull/589

**Pull request closed without merging**
