### PR TITLE
Fix broken links in the “Working with Mozilla source code” article

### LINKED ISSUE #666: Issue with "Working with Mozilla source code": …
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code

#### What information was incorrect, unhelpful, or incomplete?
https://developer.mozilla.org/en-US/Developer_Guide/Source_Code/Mercurial
link is missing/broken, the url is a 404

#### Specific section or headline?
"Getting the code from the Mercurial repository"

#### What did you expect to see?
a working page, at least https://developer.mozilla.org/en-US/Developer_Guide/Source_Code/Mercurial,
but better https://firefox-source-docs.mozilla.org/contributing/vcs/mercurial.html

#### Did you test this? If so, how?
by going to the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/developer_guide/source_code`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/developer_guide/source_code/index.html
* Report started: 2020-12-27T19:31:27.307Z

</details>

### PR DESCRIPTION
**Pull request by sideshowbarker**
This change fixes all broken links in the “Working with Mozilla source code” article, as well removing some unnecessary title attributes, and zapping a couple of non-breaking spaces.

Fixes https://github.com/mdn/content/issues/666

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
LGTM

**Comment by hamishwillee** [comment]
@chrisdavidmills @sideshowbarker Do we run a link checker, at least for internal links?

**Comment by sideshowbarker** [comment]
> @chrisdavidmills @sideshowbarker Do we run a link checker, at least for internal links?

I don’t know myself. I guess it’d be good if we did.

**Comment by Ryuno-Ki** [comment]
https://www.npmjs.com/package/hyperlink could be worth checking out

**Comment by hamishwillee** [comment]
Yes. There are millions of options https://www.npmjs.com/package/broken-link-checker , https://github.com/linkchecker/linkchecker ,  etc. I think it makes sense to run this at least monthly.

**Comment by hamishwillee** [comment]
@sideshowbarker I had a play and there are 8000+ "potential" issues in this gist: https://gist.github.com/hamishwillee/f455ac42da19cb005482f23a78fe1c12

I say potential because many of the missing targets might be something wrong with my script.

That said, a spot check on the "hash does not exist" and "empty hash" cases were valid, and so are most of these links.

Thoughts?

FYI, this was produced using https://github.com/wjdp/htmltest , but I had to modify all the links to strip off /us-EN/docs/ to get it to work. 


PS I also used the BLC checker (https://matthewsetter.com/writing-tools/npm-broken-link-checker/) but that doesn't give you much hint on anchors - only 404s. Cleaned up output for that here: https://gist.github.com/hamishwillee/4305d00308333e6407929b019f796521

**Comment by sideshowbarker** [comment]
> @sideshowbarker I had a play and there are 8000+ "potential" issues in this gist: https://gist.github.com/hamishwillee/f455ac42da19cb005482f23a78fe1c12
> 
> I say potential because many of the missing targets might be something wrong with my script.

Regardless, I guess that still probably gives us an rough idea of the general scale — thousands of broken links/fragments.

Given that, it seems clear this merits further discussion/investigation. So probably it’s time to open a new issue, and move this discussion there? Since it seems like any new mechanisms that might end up getting add in relation to this would necessarily need to come from the @mdn/core-yari-dev team, maybe this is also more of an issue for mdn/yari than for mdn/content?

**Comment by hamishwillee** [comment]
Thanks @sideshowbarker . I think that link checking is both a content and tooling issue. See https://github.com/mdn/content/issues/753 and https://github.com/mdn/yari/issues/2289

**Pull request merged**
