### PR TITLE
Correct tag omission for <tbody>

### PR DESCRIPTION
**Pull request by giorgitsiklauri**
Clerical error fixed ("Must not be present" should have been "must be present").

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by ericwbailey — DISMISSED** [review]
This is an interesting one. The updated phrasing implies a `tbody` element is needed for a `table` element that contains a `tr` element. Tables, however, do not necessarily need a `tbody` element unless a `thead` or `tfoot` is present.

Can we update this to reflect that?

**Comment by giorgitsiklauri** [comment]
This is, indeed, an interesting one, as I have been researching this for 2 days now, and different standards (HTML 3, 4, 5) define this concept slightly differently. It looks like it is not necessary, but interestingly, any browser would still generate `<tbody>` when rendering HTML table without `<tbody>`. Also, [this](https://stackoverflow.com/questions/3078099/is-it-necessary-to-have-tbody-in-every-table) post has interesting answers, while HTML 4 [defines](https://www.w3.org/TR/html4/struct/tables.html#edef-TBODY) same topic differently, and HTML 5 - even [differently](https://html.spec.whatwg.org/#the-tbody-element).

After all, I would be glad to improve this further, but I thought it's *almost* always required, in a little bit complex scenarios, and as all the browsers render `<tbody>` disregarding of what you code up, I concluded it's necessary.. but I am really confused, especially, when I follow HTML 4 and 5 standards - they differ.

Thanks.

**Comment by teoli2003** [comment]
I think we should have two sentences here: one for the rules about the element (when the element is needed) and one about the opening tag omission (Elements ≠ tags). What about:

_The `<tbody>` element is not a required child element for a parent {{ HTMLElement("table") }} element to graphically render. However, it must be present, if the parent {{ HTMLElement("table") }} element has a {{HTMLElement("thead")}}, a {{HTMLElement("tfoot")}} or another {{HTMLElement("tbody")}} element as a child._

_If the `<tbody>` element starts with a {{HTMLElement("tbody")}}  element, and is not following a non-closed  `<tbody>` element, its opening tag can be omitted._

**Comment by teoli2003** [comment]
Friendly ping. I can create a commit with the suggestion, if you are busy.

**Review by teoli2003 — APPROVED** [review]

**Review by teoli2003 — APPROVED** [review]

**Pull request merged**
