### PR TITLE
chore: update links to webvr examples

### LINKED ISSUE #20734: chore: update webvr links to use main and not master
While we are archiving the `webvr` repository, we switched the default branch to `main.` For consistency, we should update the links in the content to use `main.`

### PR DESCRIPTION
**Pull request by schalkneethling**
Update links to the webvr examples repo and demos.

fix #20734

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
What's the policy for mdn/museum? What is it for and how should we decide when things should go there?

I think it's unfortunate that we still have to have WebVR docs on MDN at all, but it seem like we will have to keep them for a while at least.

(I believe the policy there is to delete docs after a feature is no longer supported by any major browsers for at least 2 years. I don't know how this is affected by support-behind-a-flag, which Firefox has here).

But if we do have to keep the docs, what is the thinking behind museuming the sample code? Are we expected to maintain and update it? If not, it gets weird when the page is updated and the linked code isn't any more. I feel that if we link to sample code as valid context to our pages, with text like:

> Note: You can see this complete code at [raw-webgl-example](https://github.com/mdn/museum/blob/main/webvr/raw-webgl-example/webgl-demo.js).

...then that puts us under an obligation to maintain it properly. If we don't want to maintain this code any more, it would be better to remove the links from MDN. If we do want to maintain the code, we should not be museuming it.

**Comment by schalkneethling** [comment]
> What's the policy for mdn/museum? What is it for and how should we decide when things should go there?

It is mainly something fun to keep some code examples around that have live examples—keeping it around for posterity.

> Note: You can see this complete code at [raw-webgl-example](https://github.com/mdn/museum/blob/main/webvr/raw-webgl-example/webgl-demo.js).
> ...then that puts us under an obligation to maintain it properly. If we don't want to maintain this code any more, it would be better to remove the links from MDN. If we do want to maintain the code, we should not be museuming it.

From what I understood, the API has been deprecated, so there should not be any obligation to maintain the code. Perhaps this is an instance where it is better to delete everything, but that might need a more extensive discussion.

**Comment by wbamberg** [comment]
We talked about this in the editorial meeting today.

The basic principle IMO is: we should not link to example code that we're not going to maintain.

We have a principle that once a feature in unsupported by all major browsers for two years, we can remove docs from MDN. In the case of WebVR it's a little complicated because Firefox still supports it behind a flag, but we think that doesn't count - it's effectively unsupported in Firefox as well as everything else. However [it hasn't been unsupported for 2 years, yet](https://pr20736.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/VRDisplay#browser_compatibility), so it doesn't yet meet the criteria for removal.

It looks like it will be March 2024 before it has been unsupported in all browsers for 2 years.

So in the meantime the WebVR APIs should be documented on MDN as a deprecated feature.

I think there is a difference between "fun-for-posterity" code samples, like the WebGL demo, and code samples that are an integral part of our docs. "fun-for-posterity" code samples are specifically historical and it is fine for the code to be old-fashioned or full of bad practices, and we should not have to maintain them - that's why it's called a museum.

But the WebVR code samples are part of our docs, just like any other live samples that are backing for code samples in the page. And so they ought to be maintained.

For example, look at a page like https://developer.mozilla.org/en-US/docs/Web/API/VRDisplay/cancelAnimationFrame. It contains a code block: https://developer.mozilla.org/en-US/docs/Web/API/VRDisplay/cancelAnimationFrame#examples, that's supposed to illustrate the API. If someone files a bug against that code sample, we're expected to fix it. If we have a project to modernize our code samples, we will update it. If we run ESLint over our code samples and it complains about something in this code block, we will fix it.

But this page also says: "Note: You can see this complete code at [raw-webgl-example](https://github.com/mdn/webvr-tests/blob/master/raw-webgl-example/webgl-demo.js)." So readers can expect to follow that link and see the same code, as part of a complete demo. So if the demo is moved into the museum, then this implies that we *do* have to maintain code in the museum, which seems totally against the point of it being in a museum.

What I think would be OK is just to remove all those notes like "Note: You can see this complete code at [raw-webgl-example](https://github.com/mdn/webvr-tests/blob/master/raw-webgl-example/webgl-demo.js)." We can say: these are deprecated APIs, so we don't maintain full demos for them.

**Comment by schalkneethling** [comment]
Hey everyone,

Thank you so much for all of your valuable input. I guess I see two routes here:

## Keep WebVR

This will mean closing this PR, removing the code from the museum, and unarchiving the webvr-examples repository. We could then add a note to the repo stating that the tech is deprecated and will be removed from MDN Web Docs in March 2024. Until then, we will still need to address any issues brought up regarding the docs and the code.

## Remove mentions of the code

Instead of linking to the code and live demos in the content, we remove any links from the docs(as mentioned by @wbamberg here https://github.com/mdn/content/pull/20736#issuecomment-1251695864), keep the WebVR repo archived, and leave the code in the museum for posterity.

@Rumyra, let me know your thoughts on the above. Thanks!

**Comment by bsmth** [comment]
>I guess I see two routes here:

Thanks all, personally, I would go with suggestion __(2)__ -> remove links to the code.

**Pull request closed without merging**
