### PR TITLE
33238: step is not always 1

### LINKED ISSUE #33238: Default `step` value for `datetime-local` input is incorrect
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/step

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/step#syntax

### What information was incorrect, unhelpful, or incomplete?

The default value for `step` in the table in this section for the `datetime-local` input type is listed as "1 (second)". However, on the page for the `datetime-local` input type, the default value is listed as 60 seconds.

### What did you expect to see?

The default to be listed as "60 (seconds)" as it is for the `time` input type.

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/step`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/step
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/step/index.md
* Last commit: https://github.com/mdn/content/commit/1582d17d5c39869980f3dc4a249a09292976acfe
* Document last modified: 2024-01-27T10:11:15.000Z

</details>

### PR DESCRIPTION
**Pull request by estelle**
fixes #33238

### CODE REVIEW

**Review by dipikabh — CHANGES_REQUESTED** [review]
Thanks for these updates, @estelle. I believe the entry in the "Default values for step" table for "datetime-local" also needs to be updated as pointed in the issue.

**Comment by estelle** [comment]
> Thanks for these updates, @estelle. I believe the entry in the "Default values for step" table for "datetime-local" also needs to be updated as pointed in the issue.

Good call. Oddly, it was correct on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local but not here.

**Review by dipikabh — APPROVED** [review]
Thank you 👍

**Comment by estelle** [comment]
where are you or what's going on that you are reviewing PRs at 2:00am or so Toronto time?

**Pull request merged**
