### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by jaredleishman**
Typo

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
I'm unsure, whether it is one.
„it” sounds like the subject in that sentence to me.

**Comment by jaredleishman** [comment]
I believe the current version is grammatically incorrect.
image

**Review by Ryuno-Ki — APPROVED** [review]
Computer says „yes”

**Comment by Ryuno-Ki** [comment]
I somehow swapped the sides in my mind.
You're right.

Thank you for correcting it (and me).

**Comment by jaredleishman** [comment]
Thanks for the review!

**Pull request merged**
