### PR TITLE
Update: supported themes properties for Firefox 89

### LINKED ISSUE #4390: Content bug: Update supported themes properties for Firefox 89
We list and describe supported theming properties on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme. 

There are a couple of updates we'll need to make as a result of changes incoming from Firefox 89: 

1. `tab_background_separator` will not be supported
2. `toolbar_field_separator` will not be supported
3. `tab_line` will behave differently (it will apply a 3px border to all sides of the tab instead of a thick horizontal line to the top border) 
4. `toolbar_vertical_separator` will no longer show up near the hamburger menu

See this [blog post](https://blog.mozilla.org/addons/2021/04/19/changes-to-themeable-areas-of-firefox-in-version-89/) for examples and more descriptions.

### PR DESCRIPTION
**Pull request by Shinyaigeek**
> What was wrong/why is this fix needed? (quick summary only)

update theme properties supports for Firefox89. https://blog.mozilla.org/addons/2021/04/19/changes-to-themeable-areas-of-firefox-in-version-89/

> MDN URL of main page changed

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme

> Issue number (if there is an associated issue)

Fixes: 4390

> Anything else that could help us review it

### CODE REVIEW

**Review by caitmuenster — CHANGES_REQUESTED** [review]
Thank you so much for the PR, @Shinyaigeek! This is off to a great start! 😍

Just a couple of small changes: 

1. The [local preview](https://pr4648.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#_flaws) indicated a few broken links. Can you update those? (If you haven't yet set up your local environment, you should be able to go to the directory on your computer, check out your working branch, and then `yarn install` and `yarn start`. Once you've run `yarn start`, you should be able to click on the local preview link in this comment and click on the button that says "Show Flaws."

2. `tab_background_separator` and 'toolbar_vertical_separator` are deprecated but haven't been removed yet. Can you update the warning message to  say, "[property] is not supported starting with Firefox 89."

**Comment by caitmuenster** [comment]
Oh, one last note! In your PR, can you change 

`Fix: 4390`

to 

`Fixes: 4390`? That should link this PR to the issue and close the issue automatically once your PR is approved + merged. :)

**Comment by Shinyaigeek** [comment]
@caitmuenster Thank you for reviewing!! 

> The local preview indicated a few broken links. Can you update those? (If you haven't yet set up your local environment, you should be able to go to the directory on your computer, check out your working branch, and then yarn install and yarn start. Once you've run yarn start, you should be able to click on the local preview link in this comment and click on the button that says "Show Flaws."

Oh, sorry, I did not notice "Show Flaws" 🙏  I fixed broken links in fa24dd3 .

> tab_background_separator and 'toolbar_vertical_separator` are deprecated but haven't been removed yet. Can you update the warning message to say, "[property] is not supported starting with Firefox 89."

Thank you for pointing this out!! I updated warning message in 232b8a0

> Oh, one last note! In your PR, can you change
Fix: 4390
to
Fixes: 4390? That should link this PR to the issue and close the issue automatically once your PR is approved + merged. :)

I was misunderstood 🙏  I fixed PR description message `Fix: 4390` to `Fixes: 4390`, thank you!!

**Review by caitmuenster — APPROVED** [review]
Wonderful! Thanks so much for your contribution, @Shinyaigeek! 🏅 I will add your contribution to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition) later today. 

Welcome onboard!

**Pull request merged**
