### PR TITLE
CSS cross-fade examples fully tab-aligned

### PR DESCRIPTION
**Pull request by sidewayss**
This is a follow-up to #29023.  I fully expect this PR to be rejected.  I'm surprised that Prettier didn't reformat it.  I was surprised to see the tabular formatting in CSS on this page.  But it is easier to read, isn't it?

What can I say? After years of programming for accountants and financial analysts I grew accustomed tabular formatting, especially when it comes to numbers.  I don't expect others here to share my enthusiasm, but this page opened the door.  This PR seeks to clarify how wide that door is open.

### CODE REVIEW

**Comment by asdwffgtg** [comment]
Bear_vip_Hax

**Comment by Josh-Cena** [comment]
@sidewayss Prettier doesn't reformat it because it's not valid CSS code (it's missing the braces). I don't have strong opinions about this anyway, but should this be valid, Prettier surely will say otherwise, so I think it's better that we stick to the style we use everywhere else.

**Comment by sidewayss** [comment]
> @sidewayss Prettier doesn't reformat it because it's not valid CSS code (it's missing the braces). I don't have strong opinions about this anyway, but should this be valid, Prettier surely will say otherwise, so I think it's better that we stick to the style we use everywhere else.

Ah, the missing braces.  I was assuming it was the comment in the first line of the triple backquotes that got Prettier to format a section based on a particular language.  Then go ahead and close this and #29023. I can create a PR to remove the tab-aligned formatting instead.

**Comment by sidewayss** [comment]
I have created #29036 to replace this and #29023.

**Comment by Josh-Cena** [comment]
> I was assuming it was the comment in the first line of the triple backquotes that got Prettier to format a section based on a particular language.

That's right, but in order for Prettier to format it as CSS properly, it has to be able to understand the code, which it can't here because the code is invalid.

**Comment by sidewayss** [comment]
> > I was assuming it was the comment in the first line of the triple backquotes that got Prettier to format a section based on a particular language.
>
> That's right, but in order for Prettier to format it as CSS properly, it has to be able to understand the code, which it can't here because the code is invalid.

That's the nature of these CSS sections.  They are all this way because they isolate the property outside of a declared style, so Prettier will never touch them.  I'm surprised there's no way to work around that.

**Comment by hamishwillee** [comment]
> I have created https://github.com/mdn/content/pull/29036 to replace this and https://github.com/mdn/content/pull/29023.

Thanks. If you create a replacement, please close the replaced item so people stop looking at it.

**Pull request closed without merging**
