### PR TITLE
fixing user-valid pseudo

### LINKED ISSUE #4304: Missing doc page for :user-valid pseudo-class
The [release notes for version 88](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/88) indicate that pseudo-classes `:user-valid` and `:user-invalid` are now fully supported, but only the latter is linked to its [description page](https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid).

(I'd guess that a modified clone of [`:user-invalid`](https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid) would suffice as a starting point.)

### LINKED ISSUE #4310: Outdated/missing doc page for :-moz-ui-valid and :-moz-ui-invalid pseudo-classes
In checking background details for issue #4304, I found that the `:-moz-ui-valid` pseudo class is documented but `:moz-ui-invalid` is undocumented.

Should a page be added for `:-moz-ui-invalid`?

Since `:user-valid` is supported as of Firefox v88, should `:-moz-ui-valid` be updated to highlight this?

Also, I assume that references to `:moz-ui-valid` should be to `:-moz-ui-valid`?

### PR DESCRIPTION
**Pull request by rachelandrew**
Redo of a PR that got into a muddle (https://github.com/mdn/content/pull/3707)

1. Moves the non-standard `:-moz-ui-valid` to `:user-valid`
2. Updates that page to be correct as to the spec, adds an example
3. Updates `user-invalid` as it still referred to the moz property it was moved from
4. Adds an example to `user-invalid`

Fixes: #4304 
Fixes: #4310 

@chrisdavidmills here is the redo for user-valid, I think these ones where things get moved are way more likely to get into a muddle so if we can merge it before it happens again would be good :D

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
I've already reviewed this, so all good. Yes, let's get this merged right away!

**Comment by chrisdavidmills** [comment]
@rachelandrew except that I can't because now the redirects are failing again...;-(
I again don't know what the problem is here. Did you use the tool to create the redirect?

**Comment by rachelandrew** [comment]
No, because I can't. We've never managed to get the tool to work on Windows :( if you remember, I spent ages back and forth trying to get it to work.

**Comment by rachelandrew** [comment]
I thought I'd figured it out but everything seems to be failing with an "internal error" now so I'm not sure.

**Comment by chrisdavidmills** [comment]
@rachelandrew sorry, I'd forgotten about all that.

@peterbe more redirect misery. Can you suggest what we can do to move forward here?

**Comment by rachelandrew** [comment]
I have an old Mac Mini, it may be the path of least resistance to set that up purely to run these tools!

**Comment by peterbe** [comment]
Are we sure it ever was a problem with redirects? 
I restart the tests (by clicking the "Re-run jobs") button in the checks there on GitHub Actions. I think there simply was a glitch in GitHub Action the first time that prevented the tests from even starting at all. 

All good now?

**Comment by kurahaupo** [comment]
(following up from #4304 and #4310)

@rachelandrew I note that [the release notes for 88](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/88) say (under "Removals"):

> Default styling for the non-standard `:user-invalid` and `:-moz-ui-valid` has been removed (bug 1693969).

By any chance was `:-moz-ui-invalid` inadvertently replaced by `:user-invalid` there?

**Comment by rachelandrew** [comment]
@peterbe I think there was a problem with redirects which I fixed, but then the build failed after that which made it look like that was still an issue. But now it has conflicts again so I may have to do the whole thing over once again ... cc: @chrisdavidmills

**Comment by peterbe** [comment]
Ugh. Redirects. Hard to get right and still needs a lot of work to become smooth and user-friendly. Sorry about that. 

The reason you're getting a merge conflict on the `_wikihistory.json` file is because the CLI, when it adds to the JSON file, adds it at the end. So it's only a matter of time till a merge conflict can happen. Insane when the file is 160k long!
I think the solution would be to sort all entries in the `_wikihistory.json` so that next time someone uses the CLI (to rename something) when it injects into the `_wikihistory.json` file it adds it alphabetically so conflicts can't happen ever.

**Comment by peterbe** [comment]
But I think if you merge in the latest `main` into your branch and view the conflict in your IDE it should be pretty easy to save it so that you keep both entries. Happy to help on Slack or Zoom if you ping!

**Comment by peterbe** [comment]
@rachelandrew once https://github.com/mdn/yari/pull/3606 lands hopefully these annoying merge conflicts will become impossible.

**Comment by kurahaupo** [comment]
@peterbe I was going to suggest switching the automated tools to use POSIX text file format but I see that your PR would already do that, yay!

**Comment by kurahaupo** [comment]
@rachelandrew I've created a commit on top of your PR to remove the trailing newline; if you merge that into your PR, it should pull cleanly.

Feel free to rebase-squash it; it's not worth crediting me.

https://github.com/kurahaupo/content/tree/redo-user-valid-pr

**Comment by rachelandrew** [comment]
@kurahaupo hmm, that doesn't seem to have helped. I'll make a third attempt to do this PR today!

**Comment by peterbe** [comment]
> @kurahaupo hmm, that doesn't seem to have helped. I'll make a third attempt to do this PR today!

@rachelandrew I'm always happy to rubberduck debug and help on Zoom if you want a hand.

**Comment by kurahaupo** [comment]
The conflict because someone else modified the same file and _also_ reversed the line ending, so they're still opposing.
You can either pop my commit off your PR (`git reset --hard @^` then `git push --force`) or use [my branch](/kurahaupo/content/tree/redo-user-valid-pr) instead.

**Comment by kurahaupo** [comment]
Argh! I originally put this comment on #3707 instead of here.

@rachelandrew
A PR is simply a proposal to merge branch A into branch B, usually where A is a user repo and B is an upstream (likely origin/main on your PC). Rebasing A onto B does not "incorporate all the subsequent commits in B into the PR", since the PR neither knows nor cares where the branch starts or ends.

What rebasing does do is move all the commits in B "before" those in A (and thus those intended by the PR), which is actually what you want to happen, as it provides a clean baseline for the PR so that merging can be done as a fast-forward merge.

I've rebased my branch onto main, and as you can see, it only shows your two commits as being significant.

I suggest that on your PC you go:

git remote add kurahaupo https://github.com/kurahaupo/content
git fetch kurahaupo
git checkout redo-user-valid-pr
git reset --hard kurahaupo/redo-user-valid-pr
git push --force

The final "push" assumes that your fork on github is the default push target for your local repo; otherwise give its remote name on the end of that line.

**Comment by Ryuno-Ki** [comment]
Perhaps it's worth to keep a tutorial at hand about git.
Personally, I enjoy Atlassian's documentation, e.g. https://www.atlassian.com/git/tutorials/merging-vs-rebasing

Hopefully we can resolve this merge conflict here soon.

**Comment by rachelandrew** [comment]
@Ryuno-Ki I've read plenty of git tutorials, and followed various instructions. I've not yet found a satisfactory solution to these issues, that is quicker than just re-doing the PR when these things happen. I'm going to redo the PR once I know Chris is around to merge it quickly.

**Comment by kurahaupo** [comment]
The problem with cancelling and redoing PRs is that this multiplies the time required of other people, for reviewing and approving.

Merging or rebasing the PR branch from the upstream and dealing with any conflicts within your branch is the "normal" way to do a PR. 

Rebasing leaves a cleaner git history, whereas merging is generally simpler.

The ideal is that the head of your PR branch should have the head of main as an ancestor when the PR is actioned. I suggest that you play around with branches in your own PC until you're comfortable with this.

In particular you'll want to get the hang of using `git reset --hard `_`sha`_ to undo commits, merges & rebases. Using `git push --force` on your PC is roughly the equivalent of doing `git reset --hard` on github, and can similarly be used to fix breakages.

**Pull request closed without merging**
