### PR TITLE
Fix value of this at top-level scope

### PR DESCRIPTION
**Pull request by geryogam**

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Nice catch! This (pun intended) is very complicated, so I made some edits myself. Do they look good to you?

**Review by Josh-Cena — COMMENTED** [review]
Nice catch! This (pun intended) is very complicated, so I made some edits myself. Do they look good to you?

**Review by Josh-Cena — APPROVED** [review]
Thank you!

**Comment by geryogam** [comment]
Thanks!

**Pull request merged**
