### PR TITLE
Add _static suffix for static methods and properties

### LINKED ISSUE #104: Support same name for static method and instance method
This has been discussed in https://github.com/mdn/content/discussions/5121 and there's general agreement that something needs to be done, but no concrete proposal on the table. https://github.com/whatwg/fetch/pull/1392 will not be possible to document until this is resolved.

@teoli2003 can you label this `proposed for Q3 2022`?

### PR DESCRIPTION
**Pull request by wbamberg**
Fixes https://github.com/openwebdocs/project/issues/104.

This PR:

- adds a `_static` suffix to the URLs for the 42 pages we have that document static methods and properties in Web/API.
- updates our meta-docs for Web/API method and property pages to ask people to add this suffix for statics

As a side-effect, because it runs the new linter, it enforces a line length of 80 characters for front matter items across MDN. That means it obsoletes https://github.com/mdn/content/pull/26441. I know we are not decided about this, but I believe that if we adjust this limit later (to, say 120 characters) then the linter will fix this up for us. And I don't really want to block this change on that decision.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍 Let's not block this on the line length in Front-matter. It will be easier to fix this later.

**Comment by OnkarRuikar** [comment]
And we missed the opportuinity(https://github.com/mdn/content/pull/26441#issuecomment-1527027604) to test the front-matter validation in daily cron job. :(

> 👍 Let's not block this on the line length in Front-matter. It will be easier to fix this later.

Due to the nature of values there are no line break opportunities in front-matter attributes(except for `title`). So it looks weird.

We have two options:
a) Make line length infinite. All the chomped lines (`>-`) in content ATM will get straighten up.
b) Use inline break style. Following is a valid syntax recongnized by yari as well.
```yml
title: "long long very\
  long title"
slug: "Web/API/long/long/long\
  /very/long/slug
```
For this we'll have to tweak the parser or implement ourselves in fmlinter.

**Comment by teoli2003** [comment]
Let's go back to the root: What problem are we trying to solve in limiting the line length in YAML?

All our YAML entries are determined (that is there is no real editorial decision in adding them): `title` can be long as well as `mdn_url`, but they are kind of "algorithmically" determined. Cutting them into several lines doesn't bring any readability improvement. `title` and `short_title` can be theoretically long, but practically, their length will be limited by how they are displayed on the MDN website.

I don't think any problem is solved by limiting the line length in YAML. (Correct me if I'm wrong!). Also making them infinite (or very long) is not complicated.

Therefore, I think we should not cut long lines in YAML headers (because of how we use them); if there were a `description` field, it would be different.

What do you think @wbamberg, @OnkarRuikar ?

**Comment by OnkarRuikar** [comment]
> I don't think any problem is solved by limiting the line length in YAML. (Correct me if I'm wrong!). Also, making them infinite (or very long) is not complicated.

Agree. I am +1 on making it infinite. Because it will be simple for authors, as following is an unknown construct for most of us:
https://github.com/mdn/content/blob/6cbf2506986184c7d18716da803f06dc743b5101/files/en-us/web/svg/attribute/gradientunits/index.md?plain=1#L5-L9

**Comment by wbamberg** [comment]
Yes, I'm totally happy with this.

**Pull request merged**
