### PR TITLE
Node.js Aliases

### PR DESCRIPTION
**Pull request by JavascriptLearner815**
Checklist — To help your pull request get merged faster, please do the following:

1. - [X] Node.js is also mentioned to be spelled NodeJS as well. npm is also mentioned to be spelled NPM as well.
1. - [X] Fixes nil.
1. - [X] Auto-merge skipped, all successful.
1. - [X] No links, but previously added the "Node Package Manager (npm)" section.

### CODE REVIEW

**Comment by JavascriptLearner815** [comment]
This is a minor edit.

**Comment by chrisdavidmills** [comment]
Thanks for the contribution @JavascriptLearner815 . I just wanted to query this a bit. I always tend to write the former Node.js, and see it everywhere like that on the official site, docs, etc. And I've always seen the latter write npm. In fact, I've heard folks in the know say that it shouldn't be written NPM.

I've done a few searches to see if I can find much evidence of these aliases in use, and can find very little.

So, not to say I don't believe you, but at the same time, where do you see these used? I am just wondering how helpful this change is to readers.

**Comment by JavascriptLearner815** [comment]
> Thanks for the contribution @JavascriptLearner815 . I just wanted to query this a bit. I always tend to write the former Node.js, and see it everywhere like that on the official site, docs, etc. And I've always seen the latter written as npm. In fact, I've heard folks in the know say that it shouldn't be written NPM.
> 
> I've done a few searches to see if I can find much evidence of these aliases in use, and can find very little.
> 
> So, not to say I don't believe you, but at the same time, where do you see these used? I am just wondering how helpful this change is to readers.

Usually in wikis that anyone can contribute to or for some tutorial videos.

"how to create an express server with node JS" instead of "how to created an express server with node.js"

"Node JS Full Course" instead of "Node.js Full Course"

"Introducing ... Yarn & NPM"

**Comment by JavascriptLearner815** [comment]
inactive

**Comment by JavascriptLearner815** [comment]
> inactive

x2

**Comment by chrisdavidmills** [comment]
Right, OK. I don't think we need to include notes on alternative spellings of these (which are arguably wrong), so I'm going to close this.

**Pull request closed without merging**
