### PR TITLE
Use consistent formatting for all macros (3)

### PR DESCRIPTION
**Pull request by Josh-Cena**
### Description

https://github.com/mdn/content/pull/29006
https://github.com/mdn/content/pull/29007

### CODE REVIEW

**Comment by hamishwillee** [comment]
Seems pretty pointless since all the formats work.

**Comment by Josh-Cena** [comment]
@hamishwillee You could have said the same about Markdown formatting: any format would work but uniformity is better because it saves us from pointless diff when different people want it different ways. This would be a one-time effort: once this style is enforced it would be trivial to keep it consistent into the future. This also makes it easier to check for other consistency issues when we can do a text-based comparison instead of adjusting for minor whitespace issues (had we not formatted our markdown we would run into this issue everywhere).

**Comment by hamishwillee** [comment]
@Josh-Cena Honestly? I like the change, but I would have made it collaboratively - raised a discussion to confirm the preferred format (I prefer `{{deprecated_header}}` to `{{Deprecated_Header}}`) and have a plan that actually disallows and raises flaws for formats we won't accept. That's how all that other markdown stuff got agreed.

**Comment by Josh-Cena** [comment]
It was a "majority wins" case for most of the macro casing changes. `{{Deprecated_Header}}` etc. are slightly different because they are automatically added by Onkar's sync with BCD, so I opted to use the same format as his script to not cause more divergence. I can discuss if necessary.

**Comment by hamishwillee** [comment]
> I can discuss if necessary.

I'd prefer it https://github.com/orgs/mdn/discussions/448 .

**Comment by Josh-Cena** [comment]
I really don't want to get these changes blocked, though. I can revert the macro casing changes if needed, but I want to get whitespace, quotes, and line break changes in, so I can be unblocked from further macro sanitation.

**Comment by hamishwillee** [comment]
I'm happy to merge it if you remove the changes.

I'd very much like to merge all of it, since I suspect this is what we'll converge on. But would rather wait until everyone has had their say.

**Review by hamishwillee — APPROVED** [review]
Actually stuff it. The macros are all over the place right now, so this is no worse. Merging, on the understanding that you may well have to revert if we settle on some other naming convention.

**Comment by Josh-Cena** [comment]
Indeed, this simply removes the _inconsistency_, not to say I made any kind of conscious choice that I won't revisit. Definitely open to change it to something else as long as it remains consistent.

**Pull request merged**
