### PR TITLE
updated chromeImg screenshot

### PR DESCRIPTION
**Pull request by Biki-das**
updated chrome time screenshot-
https://github.com/mdn/content/issues/8035

### CODE REVIEW

**Review by ericwbailey — CHANGES_REQUESTED** [review]
I noticed there's weird artifacts on the image. Can you provide a cleaner image?

**Comment by Biki-das** [comment]
Ok, thanks for the feedback

**Review by ericwbailey — APPROVED** [review]
Much better, thank you!

**Comment by Biki-das** [comment]
My pleasure ,thanks for guiding me out

**Comment by Biki-das** [comment]
Hello @ericwbailey , I have encountered a problem of capturing screenshot for the time picker , whenever i initiate to take one , the drop down which helps us to select the desired time disappears,Do you know any Trick to work it around?

**Comment by Biki-das** [comment]
hello @ericwbailey , i have pushed another PR updated the edge screenshot , do check and give me a feedback

**Comment by ericwbailey** [comment]
@Biki-das Could you please link me to the relevant PR?

**Comment by Biki-das** [comment]
> @Biki-das Could you please link me to the relevant PR?

Sure https://github.com/mdn/content/pull/8571

@ericwbailey

**Comment by ericwbailey** [comment]
Thanks, @Biki-das. I see Estelle is tagged for review on that, so I'll let them cover it.

**Comment by Biki-das** [comment]
hello @estelle , as @ericwbailey  toldm that you are in charge of reviewing PR, please review #8571

**Pull request merged**
