### PR TITLE
Update links to canvas-raycaster to point to its new location in dom-examples

### PR DESCRIPTION
**Pull request by dipikabh**
#### Summary

Update links for mdn/canvas-raycaster to mdn/dom-examples/canvas-raycaster 

#### Motivation

Part of repo maintenance exercise

#### Related issues

PR for moving the repo: https://github.com/mdn/dom-examples/pull/111
Issue tracker: https://github.com/mdn/mdn/issues/193

### CODE REVIEW

**Review by wbamberg — APPROVED** [review]
Thanks for this PR, @dipikabh ! It looks like this repo hasn't been moved yet, so do you want to hold off merging until then?

What do you think about deleting this page and either linking directly to GitHub from https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API#guides_and_tutorials or just deleting the demo as well?

The tutorial is really not a useful tutorial and the code is very old.

@Rumyra , @teoli2003 , views?

**Comment by Rumyra** [comment]
Yeh we had a little chat about it and agree - however I really like this little demo, so we decided to create mdn/museum for little demos like this (I think there are more we can remove from MDN moving forward)

**Comment by dipikabh** [comment]
Thanks @wbamberg! Like Ruth mentioned, moving the repo to `mdn/museum` (https://github.com/mdn/museum/pull/1) instead. I'll delete this page when that lands.

**Comment by dipikabh** [comment]
Thanks @wbamberg! Like Ruth mentioned, moving the repo to `mdn/museum` (https://github.com/mdn/museum/pull/1) instead. I'll delete this page when that lands.

**Pull request closed without merging**
