### PR TITLE
updating user-valid and user-invalid

### PR DESCRIPTION
**Pull request by rachelandrew**
Working on #3455 this PR:

1. Moves the non-standard `:-moz-ui-valid` to `:user-valid`
2. Updates that page to be correct as to the spec, adds an example
3. Updates `user-invalid` as it still referred to the moz property it was moved from
4. Adds an example to `user-invalid`

I'm next going to do the BCD and syntax entries for the pseudo, which currently will show as an error.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@rachelandrew you've got a few merge conflicts on this one. Please can you fix them? Then we'll get it merged.

**Comment by rachelandrew** [comment]
@chrisdavidmills I'm afraid I can't see how to do that. If I do git status at the cli I don't see any conflicts and github won't let me use the GUI tool. I guess I'll just do the PR again?

**Comment by rachelandrew** [comment]
I'm looking at this information, but it doesn't help: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills I'm afraid I can't see how to do that. If I do git status at the cli I don't see any conflicts and github won't let me use the GUI tool. I guess I'll just do the PR again?

Yeah, pain as it is, it might be quicker than trying to fix it. I has a good go at it on Wednesday, but ended up pushing my changes to some weird branch somewhere else on your fork ;-\

**Comment by Ryuno-Ki** [comment]
Interesting, as the [comparison](https://github.com/mdn/content/compare/main...rachelandrew:user-valid) doesn't look bad, either.

Normally, I do a rebase with the Git CLI, where those conflicts disappear:

```
git checkout main
git fetch upstream  # That is, the mdn repository
git rebase upstream/main  # Replay changes in mdn repository into mine
git checkout user-valid  # In case of Rachel's PR here
git rebase main
```

Since you only have two commits here, that should work.

**Comment by rachelandrew** [comment]
@Ryuno-Ki unfortunately not, that causes the problem of collecting up every single commit since I made this PR as part of it. I don't know how to avoid that problem other than to re-do the PR, which is what I'll do now.

**Comment by Ryuno-Ki** [comment]
Dang.
Okay, cherry-picking would be another escape-hatch.
If that does not work either, manual redo of copy-pasting :-(

**Comment by Ryuno-Ki** [comment]
@rachelandrew Can we close this PR in favour of the other?

**Comment by kurahaupo** [comment]
Argh! b5f67baec5d6233ccccf8c1fad87c986b397cd7c and 2151cf98b17a40cafa9fc547c0c75215fa9564e3 were both manual changes that touched the same files.

@rachelandrew 
A PR is simply a proposal to merge branch A into branch B, usually where A is a user repo and B is an upstream (likely `origin/main` on your PC). Rebasing A onto B does _not_ "incorporate all the subsequent commits in B into the PR", since the PR neither knows nor cares where the branch starts or ends.

What rebasing _does_ do is move all the commits in B "before" those in A (and thus those intended by the PR), which is actually what you want to happen, as it provides a clean baseline for the PR so that merging can be done as a fast-forward merge.

I've rebased [my branch](/kurahaupo/content/tree/redo-user-valid-pr) onto main, and as you can see, it only shows your two commits as being significant.

I suggest that on your PC you go:
```sh
git remote add kurahaupo https://github.com/kurahaupo/content
git fetch kurahaupo
git checkout redo-user-valid-pr
git reset --hard kurahaupo/redo-user-valid-pr
git push --force
```
The final "push" assumes that your fork is the default push target for your local repo; otherwise give its remote name on the end of that line.

**Pull request closed without merging**
