### PR TITLE
Correction

### PR DESCRIPTION
**Pull request by RAKESH-PATEL57**
Correction in "For - in " loops

### Description

for (const i of arr) {
  console.log(i);    // here it will be console.log(arr[i])  acording to  below Logs 
}
// Logs: 3 5 7       

### Motivation

I just correcting the code so that user don't get confused why this output is shown.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Did you try?

image

**Comment by RAKESH-PATEL57** [comment]
have you seen this 👇👇👇
correction

 if you not merge this one then correct the log . if we console.log the index number then how we will get the value !

**Comment by Josh-Cena** [comment]
image

**Comment by RAKESH-PATEL57** [comment]
now I understood 😁

**Pull request closed without merging**
