### PR TITLE
Remove mentions of historic `Accept-Charset` header

### PR DESCRIPTION
**Pull request by ddbeck**
> What was wrong/why is this fix needed? (quick summary only)

Over in BCD, [we're inclined to drop `Accept-Charset`](https://github.com/mdn/browser-compat-data/pull/9610#issuecomment-811859732). Browsers haven't sent this header for many, many years (IE since 2008, Chrome since 2013). After giving it some thought, I think mentioning in this decade confuses more than informs. Some text I removed makes a pretty good case for me:

> With UTF-8 now being well-supported, being the preferred way of encoding characters, and to guarantee better privacy through less configuration-based entropy, browsers omit the Accept-Charset header: Internet Explorer 8, Safari 5, Opera 11, Firefox 10 and Chrome 27 have abandoned this header.

Nobody ought to send this header, servers ought to ignore it, and it's interesting mostly as a historic artifact. This PR scrubs most mentions of the header (except as one of the [forbidden header names](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name)) and deletes the reference page.

> MDN URL of main page changed

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset

### CODE REVIEW

**Comment by ddbeck** [comment]
@wbamberg Perhaps of interest to you, since you and I chatted about it previously.

**Comment by hamishwillee** [comment]
FWIW If it were me I would keep the `Accept-Charset` page itself and the BCD entry, but replace most of the content with a single note capturing your points above - essentially it should not be used. The rest of the PR is great.

Why? Well, the header is still in live specs, and at some point people will reasonably search for it - resulting in "why haven't you got information on this" questions. I'd rather we had a minimal placeholder that explains that it exists but should not be used and that we have deliberately decided not to include info for it everywhere.

**Comment by ddbeck** [comment]
I'm more set on removing the BCD than I am removing the page. It meets all our criteria for removal and is the last feature between us and a stronger data quality check.

So if we let the page stand, then we'd have to drop the compat section and, with the progress being made on generated spec tables, the specifications would go someday too. It's a _very_ thin page at that point.

**Comment by hamishwillee** [comment]
@ddbeck Perhaps I wasn't clear in https://github.com/mdn/content/pull/4250#issuecomment-822846633 - I am absolutely happy with removing BCD and most of this cleanup. I am also already suggesting a much much thinner version of the doc - so that does not phase me.

Essentially the difference is that in your proposal the header is missing even though it is in the specification - so we look like we're doing a crap job, and there is no way for anyone to know they shouldn't use it. With my proposal people can find the doc which says "don't use this".

Does that make sense?

**Comment by chrisdavidmills** [comment]
I think I agree with Hamish's proposal here. For something that was supported, but not isn't, it is useful to have a page available with a definitive conclusion on it of "this isn't supported, don't use this". Having nothing would lead to uncertainty.

In the past, the main cases in which we've removed pages are cases in which something was documented early, but then was never actually implemented. That's a bit different.

**Comment by ddbeck** [comment]
For some reason, the preview comment doesn't mention the page, but I've reinstated it, revised a little, and dropped most of its content:

https://pr4250.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTTP/Headers/Accept-Charset

**Review by hamishwillee — APPROVED** [review]
@ddbeck Works for me (so approved). How about we add a deprecation warning up the top like this:
```
{{Deprecated_Header}}
<div class="notecard warning">
  <h4>Warning</h4>
  <p>Do not use this header. It has not sent by any major browser for many years and should be ignored by servers.</p>
</div>
```

**Comment by ddbeck** [comment]
@hamishwillee I tried your suggestion, but `{{Deprecated_Header}}` links to the (now non-existent) compat section, which feels pretty broken. (Also, it is so, so wordy.) So I removed it, but I left the warning as suggested.

**Comment by hamishwillee** [comment]
Awesome. Thanks!

**Pull request merged**
