### PR TITLE
Remove examples of font-stretch images with html/css live example

### PR DESCRIPTION
**Pull request by muchafm**
This is a proposition regarding the font-stretch property example, an [issue](https://github.com/mdn/content/issues/19290) has been opened. This proposition is based on what is already done for other css property.

### CODE REVIEW

**Review by teoli2003 — CHANGES_REQUESTED** [review]
What about two drop-down menus, one with the font, the other with the keyword with two divs below, one with the "standard" size, the other with the stretched size? cc/ @estelle 

It would be more dynamic and likely much shorter.

**Comment by wbamberg** [comment]
Thanks you for your PR! I had another request: could we keep examples in the "Examples" section, and follow the standard for formatting them: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples#formatting_live_samples ?

See for example: https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow#examples .

**Comment by hamishwillee** [comment]
This doesn't work as a live example: https://pr20135.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/font-stretch#result

I have been battling this same problem in the Font Loading API docs - you only get system fonts and fonts you load via FontFaceSet and @font-face available in your page. The ones indicated are not available to the live example.
The problem here is that fonts that aren't on the same site need to be served with appropriate headers. Google Fonts would serve them appropriately if I could work out how to define the static URL for the woff files we need.

That's why this is done as an interactive example - the example gets the file locally and the result is then the frame. 

... and yes, it should be a live example in the Examples section if that issue can be resolved.

**Comment by hamishwillee** [comment]
PS Not, the font-stretch is the problematic case for examples - most of the other things that need to be shown can be done using more or less ordinary fonts either already loaded on MDN or readily available from Google Fonts.

**Review by dipikabh — CHANGES_REQUESTED** [review]

**Comment by hamishwillee** [comment]
I think this should be closed, at least for now.

The proposal was to generate the table showing stretch dynamically. A suggestion of one way to do that was to use live examples. But since the live example doesn't work there isn't much point. 

What I would do is start by creating a new version of `{{EmbedGHLiveSample("css-examples/variable-fonts/font-stretch.html", '100%', 950)}}` that generates the table and embedding it.

**Comment by muchafm** [comment]
hi @hamishwillee, I'm going to close the pr and going to follow your suggestion :) thank you for the feedback @teoli2003 @wbamberg @dipikabh

**Pull request closed without merging**
