### PR TITLE
Simplify prefers-color-scheme example

### PR DESCRIPTION
**Pull request by NeatNit**
### Description

The [main example for the `prefers-color-scheme` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#examples) is needlessly confusing. This PR replaces it with a much simpler example, dealing only with color schemes.

### Motivation

The current example involves "day" and "night" classes mixed with the schemes. It makes it difficult for a reader to understand, and the reasoning behind its structure is not explained. It does a bad job of demonstrating the `prefers-color-scheme` media query and the simplest application of it.

The replacement example in this PR is straightforward and (hopefully) easy to understand and adapt to different websites. It uses the media query the way it was intended - to select a color scheme for content - without any extra complications.

### Additional details

~~Important: I tested this only using a fiddle website. I am not able to set up a node.js environment currently, but I did my best and I hope the result renders correctly. Since this is such a small change, I was hoping a maintainer (or automated system?) could just quickly check that it renders correctly, and if not let me know how to correct it. I'm sorry if this is a big no-no, the effort to set up an entire environment just to update/improve one example seems disproportionate.~~

Update: awesome, the GitHub bot generated a preview :)

~~As for the actual content change - I am wondering if I made it over-complicated by adding the text labels with `display: none/initial;`. It creates a nice output in the example, but at the cost of making the CSS significantly longer and more complex, defeating the purpose of this PR to make the example simpler. I did add comments to explain what each section does in order to help readers know which bits are important, but I welcome any feedback.~~

Update: I've removed that bit, I'm now confident it was unnecessary.

### Related issues and pull requests

Issue #22155 was possibly opened as a direct result of the confusing nature of the current example.

### CODE REVIEW

**Comment by NeatNit** [comment]
Is it possible to put the live sample before the HTML and CSS, like so?

> ### Detecting a dark or light theme
> 
> Three elements show the possible color schemes for a website: a light scheme, a dark scheme, and a default scheme (if the browser doesn't support this feature or can't determine a preferred color scheme).
> 
> Below those three example elements is a "result" element showing the actual scheme that your browser selected, using the `prefers-color-scheme` media query.
> 
> **{{EmbedLiveSample("Detecting_a_dark_or_light_theme")}}**
> 
> This example was generated with the following code:
> 
> HTML:
> 
> ```
> ...
> ```
> 
> CSS:
> 
> ```
> ...
> ```

If so, I think it would be a lot easier to read - the description and output are right next to each other, and can fit on the screen together.

**Comment by dipikabh** [comment]
Hello @NeatNit, welcome to the MDN Web Docs project and thank you for your contribution! 🎉 

I'll take a look at your changes and will get back to you shortly.

**Comment by dipikabh** [comment]
Hello @NeatNit, I'm afraid the original example is actually good, in that, it shows two baselines and then shows how each of them would change based on the chosen theme and the styles defined for each theme. Perhaps the styles applied when a color theme is detected can be made a bit more different from the initial styles so that the difference is more pronounced and clarifies the concept a bit more.

Some other improvements that can be done include rewriting the example description to make it clearer and hiding some of the CSS code to reduce the amount of code displayed on the page. But the original example itself looks good.

**Comment by NeatNit** [comment]
> Hello @NeatNit, I'm afraid the original example is actually good, in that, it shows two baselines and then shows how each of them would change based on the chosen theme and the styles defined for each theme. Perhaps the styles applied when a color theme is detected can be made a bit more different from the initial styles so that the difference is more pronounced and clarifies the concept a bit more.

I think we can both agree that "the example is good/bad" is a matter of opinion, but I contest:

1. Why does the only example need to show *two* baselines? What's wrong with just showing one, like in the PR? As far as demonstrating `prefers-color-scheme`, using two baselines offers no benefit at all, as far as I can tell. It's not that it's wrong per se, it just adds complication and cognitive load to the reader who just wants to see how the media query works.
2. Even if for some reason the example should have two baselines, why would they be Day and Night - the exact themes that Light and Dark schemes are associated with? Why not Orange and Pink baselines, for example? Choosing baselines that *might as well themselves* be called Dark and Light, is the worst possible way to demonstrate switching between light and dark themes.
3. The way the current example is set up, you will never see all 3 options at once. The leftmost boxes show the default theme, and *one* of the other pairs will switch to a lighter/darker theme, but the other will stay with the default theme - same as the leftmost pair. In my example, all possible outcomes are shown at the top (statically), and an actual dynamic result is shown below them.

The current example is baffling and impossible to understand without reading the code with full focus and reverse-engineering what the author intended to demonstrate. My example is - I hope - easy to understand by *just looking at the output* (and reading the description wouldn't hurt). Then after understanding the output, the reader would think "oh, I get it, now let's see how it's set up in the code", and start reading the code already knowing what it does.

**Comment by dipikabh** [comment]
Hi @NeatNit, thanks for sharing your viewpoint. I agree with the part that the words 'day' and 'night' can be changed to reduce confusion. The two baselines help to compare two different situations. Like I mentioned, we could update the styling of the light and dark themes to better highlight what developers can do when a user-selected color theme is detected, make them more different from the initial states.

> The way the current example is set up, you will never see all 3 options at once. The leftmost boxes show the default theme, and one of the other pairs will switch to a lighter/darker theme, but the other will stay with the default theme - same as the leftmost pair. 

This what I meant by "rewriting the example description to make it clearer". The write up before the code snippets should explain a) what the example is trying to demo and b) what readers can expect to see in the result – that it will not all happen at the same time but what will happen when a particular theme is chosen.

As per our CSS property template, we do follow the order of showing HTML code, CSS code, and then the Result. I feel a few minor updates to the code ('day', 'night', and styling for the two themes) and improving the example write up is what we should target here.

**Comment by NeatNit** [comment]
@dipikabh if I make a new PR modifying the current example the way you suggest, will it have a better chance of being accepted?

And would it be appropriate to replace "day" and "night" with different colors that aren't associated with brightness - such as red and blue?

**Comment by dipikabh** [comment]
Hello @NeatNit, yes, that would be great! Thank you for asking.

> And would it be appropriate to replace "day" and "night" with different colors that aren't associated with brightness - such as red and blue?

Or how about not using colors at all? How about theme1 and theme2 or some other generic word? Also, how about:
- making the styling of the final themes starkly different from the initial?
- saying in the example description that each row represents the style corresponding to the theme detected? (maybe add a black row in between?)

Ideally the example should have a description in the beginning to say what we're trying to demo. And after the Result, a para should explain the rendition of the html and css codes. (For reference: [Formatting live samples](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples#formatting_live_samples))

**Comment by NeatNit** [comment]
Alright, I'll do that soon! (tomorrow probably)

> Or how about not using colors at all? How about theme1 and theme2 or some other generic word?

Sure, but I'm not a designer and I really don't have any idea of what the themes should be and how they will be different from each other. It essentially requires making 3 variants of each theme - neutral, dark, and light. And I still don't see the benefit of demonstrating two themes - can you explain?

Although I've just had a thought - we could have one theme that's dark by default but changes when a light color scheme is preferred, and a second theme that's bright by default but changes to dark. This would only require two variants of each theme, and is also very close to how this feature is used in practice on live websites.

Does that sound good to you? And as I said, I'm not a designer so I'm not sure what the two themes could be, so I'm open to input. Although I could search around for some openly licensed color themes and use those. I don't want to make some ugly [programmer theme](https://en.wikipedia.org/wiki/Programmer_art?wprov=sfla1)!

> * saying in the example description that each row represents the style corresponding to the theme detected? (maybe add a black row in between?)
> 
> Ideally the example should have a description in the beginning to say what we're trying to demo. And after the Result, a para should explain the rendition of the html and css codes. (For reference: [Formatting live samples](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples#formatting_live_samples))

I will definitely make sure that the example and text are as clear as I can make them, documenting is the entire point after all!

Thanks for the link, I couldn't find this article at the time of making this PR. (On second look now, it seems I didn't look hard enough, but I swear that I *did* look 😅)

**Comment by dipikabh** [comment]
> And would it be appropriate to replace "day" and "night" with different colors that aren't associated with brightness - such as red and blue?

All I meant is the usage of the words 'red' and 'blue', that we perhaps use a non-color word. Nothing wrong with 'red' and 'blue'. Just hope the words don't add to the confusion.

> And I still don't see the benefit of demonstrating two themes - can you explain?

Because there are two options, `light` and `dark`, so we show we can style them

> I'm not a designer so I'm not sure what the two themes could be, so I'm open to input. 

On second thoughts, I still feel the existing example is good. If you just change 'day' and 'night', add some description, hide the formatting css code (to reduce the length of the code snippet), it should be sufficient to improve the clarity.

**Pull request closed without merging**
