### PR TITLE
fix image solving #17150

### LINKED ISSUE #17150: JS and CSS response Is reversed in Vary's image
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#vary

### What information was incorrect, unhelpful, or incomplete?

These Images has CSS and JS responses as example.
But, I think that JS and CSS response Is reversed.

image

image

https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#vary

### What did you expect to see?

- `https://example.com/script.js`: `function main(){ ... `
- `https://example.com/style.css`: `body { ...`

image

### Do you have any supporting links, references, or citations?

This changes has been introduced in https://github.com/mdn/content/pull/16009

### Do you have anything more you want to share?

cc @Jxck

### PR DESCRIPTION
**Pull request by Jxck**
#### Summary

fix: #17150

invert URL in table cell `script.js` <-> `style.css`

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by teoli2003** [comment]
Thanks @Jxck 

This looks good, but can you run
`yarn filecheck "files/en-us/web/http/caching/keyed-with-url-and-language.png" --save-compression`
(and its equivalent for the other image)

That way the tests will pass and we can merge this.

**Review by teoli2003 — CHANGES_REQUESTED** [review]
Need images to be compressed

**Comment by Jxck** [comment]
@teoli2003 done

**Review by teoli2003 — APPROVED** [review]
👍  Thank you!

**Pull request merged**
