### PR TITLE
Add more resources to helpful tools

### PR DESCRIPTION
**Pull request by mehulmpt**
Added codedamn as a free helpful tool for running JavaScript/Node programs within the browser.

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
In general these days we try to avoid having lists of third-party tools in MDN articles. So I think rather than adding further tools to this list, we might want to consider either eliminating it altogether, or reducing it.

@wbamberg What do you think?

**Comment by wbamberg** [comment]
> In general these days we try to avoid having lists of third-party tools in MDN articles. So I think rather than adding further tools to this list, we might want to consider either eliminating it altogether, or reducing it.
> 
> @wbamberg What do you think?

I think there are some useful sites listed there, although it could definitely be pruned.

I don't think we should add the site added by this PR. We don't have specific guidelines for when it's OK to add external links, but as a rule I think we need to have confidence that the site will still be around and properly maintained for years, which generally means a substantial track record.

**Comment by Muradalsaaideh** [comment]
> Added codedamn as a free helpful tool for running JavaScript/Node programs within the browser.

b4ecc619e16a998ef0239f686410254743014205

**Comment by Muradalsaaideh** [comment]
> Added codedamn as a free helpful tool for running JavaScript/Node programs within the browser.

b4ecc619e16a998ef0239f686410254743014205

**Comment by mehulmpt** [comment]
> but as a rule I think we need to have confidence that the site will still be around and properly maintained for years, which generally means a substantial track record.

@wbamberg @sideshowbarker codedamn has been around for more than 6 years now as a YouTube channel (https://youtube.com/codedamn), more than 1 year now as an officially registered company. We raised our pre-seed round last year (https://www.crunchbase.com/organization/codedamn) to build an interactive learn to code platform online and is used by 100K+ developers at the moment. 

Obviously, as code maintainers, it is your job to take action, but I wouldn't hesitate to say that we intend to be around for years, if not decades to come. All the best.

**Pull request closed without merging**
