### PR TITLE
Remove seoSummary, part 2

### PR DESCRIPTION
**Pull request by wbamberg**
This is the second of two PRs, after https://github.com/mdn/content/pull/8114, to remove all `seoSummary` classes from the Web/API docs, in cases where `seoSummary` just marks up the first (non-macro) paragraph in the page. In cases like this, `seoSummary` has no effect, and can therefore be safely removed.

This is part of https://github.com/mdn/content/issues/8110.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
I did three passes:
- A visual check of the preview output of each page.
- A check of the code of the multiline summary paragraphs.
- A check of the code of the summary paragraphs on one single line.

**Comment by teoli2003** [comment]
Great!

**Comment by wbamberg** [comment]
Thank you for these tedious reviews @teoli2003 !

**Comment by hamishwillee** [comment]
I think the ability to cope with tedium may be one of the core requirements for a tech writer :-0.

**Pull request merged**
