### PR TITLE
Add spec URLs for all remaining subtrees

### PR DESCRIPTION
**Pull request by sideshowbarker**
Part of https://github.com/mdn/content/issues/13126

### CODE REVIEW

**Comment by wbamberg** [comment]
I would like us to think more about whether we should use the `spec-urls` front matter key for unstructured guide pages. 

My conception of these front matter keys is that they are for reference pages that must follow a particular structure, which flows from the fact that they document a thing that has a number of attributes. So say, a CSS property always has BCD and a spec reference and a set of examples, and then front matter is a concise way to list references to some of those things.

But a page like https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts is a guide page: it has no structure and no mandatory elements. Which elements it contains is just a matter for the author to choose. So deciding to include a spec table seems like an ad hoc choice by the author, and it feels like a better fit would be an ad hoc mechanism for including it. This might be `{{Specifications("https://my/spec.url")}}`, or we might just say that spec tables (in the form that `{{Specifications}}` renders them) are not for guide pages at all, and spec URLs can just be referenced in prose: "Secure contexts are described in the https://my/spec.url specification" or something.

Maybe this just seems too theoretical a concern. A couple of ways it gets more concrete are:

* because guide pages have no structure, an author might want to include multiple tables in different places in the doc. `spec-urls` can't handle this. So we would anyway need provision for real ad hoc spec tables, so (unless we effectively ban spec tables in guide pages) we would anyway need to support `{{Specifications("https://my/spec.url")}}`.

* in some future it would be really nice to have a description of reference page structure that describes the elements a page must/may contain, and the order in which they come. If we did that we could get rid of `{{Specifications}}` and `{{Compat}}` entirely (at the moment their only purpose is to tell Yari where to put the thing). But this will never work for guide pages. So we will never be able to remove `{{Specifications}}` for guide pages.

So given that, if we want guide pages to contain spec tables:
1. we will always need to support `{{Specifications("https://my/spec.url")}}`
2. we will never be able to remove the argument-less `{{Specifications}}` macro for any guide pages

....it seems like we might as well have all guide pages use the `{{Specifications("https://my/spec.url")}}` form.

I know this probably feels like a very theoretical thing and I'm sorry to be bringing stop energy to this work :(. I'm just keen to ensure that it fits in with the overall direction we want to take.

**Comment by sideshowbarker** [comment]
> ....it seems like we might as well have all guide pages use the `{{Specifications("https://my/spec.url")}}` form.

OK, I’ve now switched all the non-reference docs changed in this PR branch to call the `Specifications` macro with a URL (rather than using the `spec-urls` frontmatter key).

**Comment by queengooborg** [comment]
Is this still blocked?  I assume this is ready for review?

**Comment by sideshowbarker** [comment]
> Is this still blocked? I assume this is ready for review?

This had an _add-`Reference`-tag_ change similar to some of the related PRs, but I’ve now removed that and rebased this and I have no further changes —

**Review by queengooborg — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
