### PR TITLE
Updated alt attributes of some images in forms guide

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

There are some missing or empty alt attributes to images in forms guide in learn section. So I have updated those with some good small descriptions explaining about images.
#### Motivation

Alt attributes of an image is very helpful for people who use assistive technologies like screen readers. It helps them to know and get the idea about the content of image. Also for any reasons if image doesn't load, alt attributes helpful get idea about image. Alt attribute is necessary for a website with good accessibility

#### Supporting details

List of missing alt attributes: https://docs.google.com/spreadsheets/d/1cDHee6mwDMlY6zANEmg8MjR8tL-wrCS86uawpWZ4XbA/edit?usp=sharing

#### Related issues

This pull request related to issue https://github.com/mdn/content/issues/19334
and add some fixes to it.

#### Metadata

- [x] Updates alt attributes of some images in forms guide.
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by isatveersingh** [comment]
Actually I did this pull request previously, but I messed up some things in my account, so I had to delete the forked repository. Now I am doing this PR again.

**Review by estelle — COMMENTED** [review]
Thank you! Sorry you had to PR twice. I know all too well how sometimes starting over is faster than fixing a borked pull request.

I have a few suggested edits. 

Screen readers say "image" before reading alt attributes, so the user knows it's an image. Sometimes it does make sense to say it's a screenshot or a photo but only when the type of image is important to the context. Otherwise, it's best to not include image.

**Comment by isatveersingh** [comment]
@estelle Thankyou for your suggestions

**Review by estelle — APPROVED** [review]
Awesome. Thanks!

**Pull request merged**
