### PR TITLE
Document bluetooth write value functions

### PR DESCRIPTION
**Pull request by cdgarren**
> What was wrong/why is this fix needed? (quick summary only)

The BluetoothGattRemoteCharacteristic page was missing the non-deprecated methods for writing values.

> Issue number (if there is an associated issue)

 #3426

> Anything else that could help us review it

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Chris, thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

**Comment by sideshowbarker** [comment]
To support this and get the Specifications section populated, we also need to add `mdn_url` and `spec_url` values to:

* https://github.com/mdn/browser-compat-data/blob/main/api/BluetoothRemoteGATTCharacteristic.json#L1135
* https://github.com/mdn/browser-compat-data/blob/main/api/BluetoothRemoteGATTCharacteristic.json#L1182

If you’d be interested in creating a PR for that too, that’d be great — otherwise, I can.

**Comment by cdgarren** [comment]
> 
> 
> To support this and get the Specifications section populated, we also need to add `mdn_url` and `spec_url` values to:
> 
>     * https://github.com/mdn/browser-compat-data/blob/main/api/BluetoothRemoteGATTCharacteristic.json#L1135
> 
>     * https://github.com/mdn/browser-compat-data/blob/main/api/BluetoothRemoteGATTCharacteristic.json#L1182
> 
> 
> If you’d be interested in creating a PR for that too, that’d be great — otherwise, I can.

@sideshowbarker I will work on a PR.

**Comment by sideshowbarker** [comment]
> @sideshowbarker I will work on a PR.

Super — once you have it ready, I’ll be happy to review it

**Comment by cdgarren** [comment]
> 
> 
> > @sideshowbarker I will work on a PR.
> 
> Super — once you have it ready, I’ll be happy to review it

Here you go: https://github.com/mdn/browser-compat-data/pull/11315

**Pull request merged**
