### PR TITLE
Clarify the type of chunk parameter in ReadableStreamDefaultController

### PR DESCRIPTION
**Pull request by Mubelotix**
Source: The spec https://streams.spec.whatwg.org/#model

### Description

Clarify the type of chunk parameter in ReadableStreamDefaultController

### Motivation

I had no idea what object I was supposed to pass

### CODE REVIEW

**Comment by Mubelotix** [comment]
What's going on here? Why isn't anyone reviewing this?

**Comment by wbamberg** [comment]
> What's going on here? Why isn't anyone reviewing this?

Sorry, we have a lot to do here and it takes a while to get to reviews sometimes. I will take a look tomorrow.

**Review by wbamberg — COMMENTED** [review]
Thanks for your PR, @Mubelotix , but I don't think this is the right thing to do. "chunk" is a really fundamental concept in the Streams API, and it's assumed that people reading the reference docs for the various parts of it have that background knowledge.

Put another way: there are lots and lots of references to "chunk" throughout the Streams API reference documentation, and I don't think it makes sense to define it inline every time it is used.

We do define "chunk" in the introductory guide material for the API (https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Concepts).

We could look at making the linkage to that more obvious? Options might include:

1. add a link to https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Concepts from https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultController/enqueue#see_also
2. add a link to https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Concepts from the sidebar for this page? I filed https://github.com/mdn/yari/issues/6229 for this a long time ago but Mozilla haven't prioritised it.
3. link directly from "chunk" here to https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Concepts ? It's a bit odd because we can't link directly to a definition of "chunk" in that page, just because of how that page is structured.
4. we could additionally restructure https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Concepts so it provides a linkable definition of "chunk", and that might be the best option, but it's quite a bit more work.

**Comment by Josh-Cena** [comment]
@Mubelotix Are you going to apply one of the suggestions above?

**Pull request closed without merging**
