### PR TITLE
Update TypeScript popularity information in Svelte Section

### PR DESCRIPTION
**Pull request by U-C-S**
What's Updated: The popularity information of TypeScript according to latest reports and statistics, since some of the links are now dead

Content URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_TypeScript#why_typescript

### CODE REVIEW

**Comment by wbamberg** [comment]
I appreciate this PR to update the paragraph, but really feel that content like this is guaranteed to go out of date very quickly. Could we just remove the first two paragraphs and start this section with "TypeScript's main advantages are:" ? @chrisdavidmills ?

**Comment by chrisdavidmills** [comment]
@wbamberg yes, I'd agree with this.

@U-C-S can you update, according to Will's suggestion? Thanks!

**Comment by U-C-S** [comment]
Done.... Check and Squash

**Review by chrisdavidmills — APPROVED** [review]
Perfect, thanks a lot @U-C-S !

Merging...

**Comment by U-C-S** [comment]
Thanks... Glad contributing something here.

 I'll try make more useful contributions here in future....

**Comment by chrisdavidmills** [comment]
> Thanks... Glad contributing something here.

We really appreciate your contribution.
 
> I'll try make more useful contributions here in future....

Anything you have time to do would be amazing. Let me know if you want any advice on other tasks you could take on.

**Comment by U-C-S** [comment]
> Anything you have time to do would be amazing. Let me know if you want any advice on other tasks you could take on.

Yeh, I would like too.... I have a lots of free time from next week

**Comment by chrisdavidmills** [comment]
> > Anything you have time to do would be amazing. Let me know if you want any advice on other tasks you could take on.
> 
> Yeh, I would like too.... I have a lots of free time from next week

Great! A good place to start is https://developer.mozilla.org/en-US/docs/MDN/Contribute#primary_contribution_types. Have a look at the guides to contributing and see what you'd like to do. Fixing some of our issues would be the highest priority thing right now, as our backlog has gotten quite big. You could start by just gong to https://github.com/mdn/content/issues and choosing some bugs to work on.

**Pull request merged**
