### PR TITLE
Run 'yarn tool fix-redirects en-us'

### PR DESCRIPTION
**Pull request by Elchi3**
For https://github.com/mdn/yari/pull/2982

### CODE REVIEW

**Comment by fiji-flo** [comment]
@Elchi3 I'm still fixing issues with validation. The redirects to other locales are actually working and should stay in there.

**Comment by Elchi3** [comment]
Awesome, thanks @fiji-flo 🎉 
(meant to open this as a draft, sorry!)

**Comment by Elchi3** [comment]
I assume this PR should then only fix the first two English SVG-related redirects. Let me know if that would be helpful. (Otherwise, we can just close this PR.)

**Comment by fiji-flo** [comment]
the current state of https://github.com/mdn/yari/pull/2982 should help with that.

`yarn tool fix-redirects en-us` just removes the 4 _en-US_ redirects.

**Comment by Elchi3** [comment]
Brilliant, thanks so much! 🚀 

I reverted and ran `yarn tool fix-redirects en-us` here.

**Comment by Elchi3** [comment]
Closing in favor of https://github.com/mdn/content/pull/2617

**Pull request closed without merging**
