### PR TITLE
Provide some additional guidance on gradients

### PR DESCRIPTION
**Pull request by SimpleProgrammingAU**
I recently came into an issue where I was trying to place a plain black bar using a sized gradient within the background of an element. However, because I wasn't setting the `background-repeat` property, it would just make the entire background black. Although the answer is obvious in hindsight, I think this bit of added guidance (perhaps with some slight tweaking to wording) would prevent quite a few head scratches.

Sentence inserted within the changed paragraph:

> Additionally, if you do not specify the `background-repeat` property, the `gradient` will repeat across the element by default.

Checklist — To help your pull request get merged faster, please do the following:

1. - [x] Provide a summary of your changes — say what problem you are fixing, what files are changed, and what you've done. This doesn't need to be hugely detailed, as we can see exact changes in the "Files changed" tab.
1. - [x] Provide a link to the issue(s) you are fixing, if appropriate, in the form "Fixes _url-of-issue_". GitHub will render this in the form "Fixes #1234", with the issue number linked to the issue. Doing this allows us to figure out what issues you are fixing, as well as helping to automate things (for example the issue will be closed once the PR that fixed it has been merged).
1. - [x] Review the results of the automated checking we run on every PR and fix any problems reported (see the list of checks near the bottom of the PR page). If you need help, please ask in a comment!
1. - [x] Link to any other resources that you think might be useful in reviewing your PR.

### CODE REVIEW

**Review by rachelandrew — COMMENTED** [review]
I'm not convinced this is the right page to document this. 

This page is about `background-size`. The reason the gradient repeats is that the initial value of `background-repeat` is `repeat`. I think such a note would be better placed in a guide or in the CSS Learn material on the subject in order to keep the property page focused.

**Comment by SimpleProgrammingAU** [comment]
The reason I suggest this change is based on my experience troubleshooting the issue I had. While looking for answers, I came across the `background-size` page. Because there was a section on `gradient`s, I thought this was going to be what I needed to know. In contrast, there is no such information provided on the `background-repeat` page. So the `background-repeat` property became a blind spot in my code that would have been easily sorted with the appropriate prompt.

I sought opinions from many other devs on how to fix my issue and got wildly varying responses. This suggests that I am not the only dev out there who might need this prompt.

If a sentence to that effect is considered inappropriate for the page, perhaps it would be valuable to include an `interactive example` in the **Working with gradients** section to exemplify the issue along with other relevant examples. Either way, I think there is a real benefit in including a reminder that the `background-repeat` property needs to be set for some circumstances.

**Comment by rachelandrew** [comment]
I understand why you are suggesting the change, however if we detail every interaction with other properties on each property page, they will become unfocussed. That is why we have the guides and other additional material. Though this page doesn't seem to link to them which it should do.

The paragraph you updated needs looking at anyway as it has some very old info in there.

I would suggest that instead of adding this, I add a Note, which links to the existing material on gradients and backgrounds, and make sure those pages include the information.

**Comment by sideshowbarker** [comment]
Closing this per https://github.com/mdn/content/pull/3164#issuecomment-799987040

**Pull request closed without merging**
