### PR TITLE
Update spec URL for CSSOM.

### PR DESCRIPTION
**Pull request by jpmedley**
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by teoli2003** [comment]
- We don't link to TR since 2012-2013 (Spec people say that TR stands for Trash)
- SpecData.json is no more used on mdn/content, only on mdn/translated-content.
- The draft link is not broken, it is a know bug on the csswg website (and annoying one)

**Comment by jpmedley** [comment]
Where are the spec URLs loaded from then?

**Comment by teoli2003** [comment]
mdn/browser-compat-data

**Comment by jpmedley** [comment]
>We don't link to TR since 2012-2013

I started contributing in 2014 or 2015. That I can remember,  no one that I can remember has ever enforced this on anything I've contributed. this would also have kept services workers from being documented for several years after they were available in all major browsers.

**Comment by teoli2003** [comment]
I don't understand how linking to the editor's draft version of a spec rather than the published TR version relates to the moment we can document a feature.

**Comment by jpmedley** [comment]
We're on two different pages. I was under the impression that the W3C draft did not actually exist. The link didn't go there, and I couldn't find it. So I submitted the TR link instead. The link seems to work now.

(Also, haven't worked on BCD much lately and forgot you were reading spec urls from there. Sorry about that.)

**Comment by teoli2003** [comment]
No worry! I thought there was some misunderstanding.

**Pull request closed without merging**
