### PR TITLE
Add Proxy link to See also subsction

### PR DESCRIPTION
**Pull request by hinell**

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks for your PR. But I'm not sure that these are particularly relevant links to add to these pages. Was there a reason you felt they were needed here?

**Comment by sideshowbarker** [comment]
@wbamberg I guess this PR is waiting on action from you? That is, deciding whether to merge it, or close it unmerged.

**Comment by wbamberg** [comment]
I was waiting for a response from the author about the reasoning for adding this link. But in the absence of that I will close this PR.

**Comment by hinell** [comment]
@wbamberg Sorry for a belated answer. This simply links related functionality. The same thin can be achieved by various methods.

**Comment by hinell** [comment]
@wbamberg you want to reopen this?

**Comment by wbamberg** [comment]
Thanks for getting back, @hinell ! It's still not obvious to me *why* `Proxy` is so closely related to `Object.defineProperty()` that it should get a link in "See also". That's what I was getting at in my comment.

**Comment by hinell** [comment]
@wbamberg Well you have to read about proxies here [Proxy]. By using [Proxy] you can manipulate the same properties on an original object via a proxy ones. You just create and use a separate object with its own descriptor similar to one used by `Object.defineProperty()` or `Object.defineProperties()`. That's why they are related.

The [Reflect] is related too btw. They are all related to object's fields properties.

[Proxy]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy
[Reflect]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect

**Pull request closed without merging**
