### PR TITLE
Restore description of headers modification restrictions

### PR DESCRIPTION
**Pull request by Josh-Cena**
This was deleted in https://github.com/mdn/content/pull/34278, but we still have references referring to it, in particular the immutable guard. I've restored the section from the old "fetch concepts" page. Maybe developers won't care as much as what's presented here but it doesn't hurt to be fully technically precise.

### CODE REVIEW

**Comment by wbamberg** [comment]
I'm -1 on this change. I removed the stuff about guard because it seemed to me an internal spec implementation thing, not a thing that's accessible to web developers. You can't ask a headers object what its guard is, for example.

Also I think https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Headers#headers_guards is a highly confusing way of explaining something that's pretty simple, and that's largely because it inserts this guard abstraction (e.g. `request-no-cors`):

- if a request is no-cors, you can only set/delete/append simple headers
- for all other requests, you can set/delete/append all headers except forbidden ones
- for responses created using ``error()` or `redirect()`, you can't set/delete/append any headers
- for all other responses, you can set/delete/append all headers except forbidden ones

I think this is a lot simpler and covers the things people need to know.

**Comment by Josh-Cena** [comment]
OK, I like your suggestion better. I just didn't want to spend time thinking about the way to re-frame it. Yours seems more reasonable.

**Comment by wbamberg** [comment]
I suppose the references to guard (and the now-deleted glossary page) are in https://developer.mozilla.org/en-US/docs/Web/API/Headers and https://developer.mozilla.org/en-US/docs/Web/API/Headers/delete and it's definitely worth cleaning that up. Apart from the broken links, the `delete()` page doesn't document exceptions properly, and doesn't capture the no-cors case, and we don't have corresponding bits in the `set()` or `append()` pages.

**Comment by Josh-Cena** [comment]
`no-cors` is not much different from setting other forbidden request headers: they only fail silently. Only immutable headers will fail to be modified.

**Review by wbamberg — APPROVED** [review]
This looks great, thank you. Approving, but it would be better still to move everything in the preamble, except the first para "The Headers interface of the [Fetch API](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Fetch_API)...", under the new "Description" heading, like:

> The Headers interface of the [Fetch API](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Fetch_API) allows you to perform various actions on [HTTP request and response headers](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTTP/Headers). These actions include retrieving, setting, adding to, and removing headers from the list of the request's headers.
>
> ## Description
>
> A Headers object has an associated header list, which is initially empty and consists of zero or more name and value pairs. You can add to this using methods like [append()](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Headers/append) (see [Examples](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Headers#examples).) In all methods of this interface, header names are matched by case-insensitive byte sequence.
>
> For security reasons, some headers can only be controlled by the user agent. These headers include the [forbidden header names](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Glossary/Forbidden_header_name) and [forbidden response header names](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Glossary/Forbidden_response_header_name).
>
> You can retrieve a Headers object via the [Request.headers](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Request/headers) and [Response.headers](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Response/headers) properties, and create a new Headers object using the [Headers()](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Headers/Headers) constructor.
>
> An object implementing Headers can directly be used in a [for...of](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Statements/for...of) structure, instead of [entries()](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Headers/entries): for (const p of myHeaders) is equivalent to for (const p of myHeaders.entries()).
>
> Note: you can find out more about the available headers by reading our [HTTP headers](https://pr35165.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTTP/Headers) reference.
>
> ### Modification restrictions
> ...

**Pull request merged**
