### PR TITLE
Remove ::-webkit-outer-spin-button

### PR DESCRIPTION
**Pull request by teoli2003**
Gone from every browser for more than a decade.

### CODE REVIEW

**Comment by dipikabh** [comment]
@teoli2003, these changes look good. We can also remove the link from the [See also](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-inner-spin-button#see_also) in `::-webkit-inner-spin-button`.

From a quick search on the net, it seems that `::-webkit-outer-spin-button` is mentioned/used in various examples. If someone comes to MDN looking for it, they will likely be redirected to the `::-webkit-inner-spin-button` page. However, this redirection might happen without any additional context or background information about `::-webkit-outer-spin-button` and its current status or usage.

It could be beneficial to maintain a log on MDN of features that were once introduced/supported but are no longer in use. This log could also include information about any replacements for these features or links to bugs for more information. AFAIK, we do make note of feature name changes on MDN, providing information about their previous names.

For future reference, I'm leaving the link to this bug here that removed `::-webkit-outer-spin-button`: https://bugs.webkit.org/show_bug.cgi?id=61845

On second thoughts, I wonder if it makes sense to not delete the `::-webkit-outer-spin-button` page. Instead of the usual compatibility table in the "Browser compatibility" section, we could just mention that it's been removed and add a link to the WebKit bug. What do you think?

**Comment by teoli2003** [comment]
It is mdn/content policy not to keep pages for features removed from the web for more than 2 years.

Also, this feature was only supported in Chrome for 6 months in 2010/2011 and Safari for 1 year…

Keeping it leads to several problems:
- maintaining it is not free.
- we don't have BCD info anymore 2 years after the last removal
- coherence: should we document all these features? Over the decades, dozens of similar features came and went in the different browsers. That's a lot of work.

This is an obscure feature to style a UI element going in the way that has moved since. The only examples on the web explain how to _hide_ the widget (W3Schools + 1 gist). It was only helpful until the widget's position in the UI changed a few months later, back in 2011.

It was designed to solve a problem that doesn't exist anymore.

(I've removed the extra link)

**Comment by dipikabh** [comment]
That's a helpful explanation. And a good reminder of MDN policies about maintaining/removing content. Thanks, @teoli2003.

**Review by dipikabh — APPROVED** [review]
Thank you! 👍

**Pull request merged**
