### PR TITLE
Remove extra else if

### PR DESCRIPTION
**Pull request by YangFong**
### Description

Remove the extra else from the example.

### Motivation

The `else` here is meaningless.

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
I find if-else chains more readable. They also take fewer lines than multiple ifs. If you want, you can remove the last `else if`, but in general I'm not in favor of these stylistic changes.

**Comment by YangFong** [comment]
The number of lines of code is not indicative of readability, it's just written in standard format, and if the curly braces are omitted, the number of lines of code is the same.

```js
const sortFn = (a, b) => {
  if (a[a.length - 1] < b[b.length - 1]) return -1;
  else if (a[a.length - 1] > b[b.length - 1]) return 1;
  else if (a[a.length - 1] === b[b.length - 1]) return 0;
}
```

```js
const sortFn = (a, b) => {
  if (a[a.length - 1] < b[b.length - 1]) return -1;
  if (a[a.length - 1] > b[b.length - 1]) return 1;
  if (a[a.length - 1] === b[b.length - 1]) return 0;
}
```

I want to keep all the conditional statements so that I know exactly what will trigger them. It's not appropriate to write this way:

```js
const sortFn = (a, b) => {
  if (a[a.length - 1] < b[b.length - 1]) {
    return -1;  
  } else if (a[a.length - 1] > b[b.length - 1]) {
    return 1;
  }
  return 0;
}
```

**Comment by Josh-Cena** [comment]
> ```js
> const sortFn = (a, b) => {
>   if (a[a.length - 1] < b[b.length - 1]) {
>     return -1;  
>   } else if (a[a.length - 1] > b[b.length - 1]) {
>     return 1;
>   }
>   return 0;
> }
> ```

In fact, that's the only correct way to write it. Both of your suggestions above would trigger linter warnings that not all code paths return a value. However, putting the last `return` in an `else` block also triggers the `no-else-return` rule (mostly to avoid putting unreachable code after the `else` block). In most of the codebases I've seen, the code you are proposing here is the most idiomatic.

**Comment by YangFong** [comment]
This I admit, it doesn't qualify in TypeScript:

```ts
// Error
const sortFn = (a: string, b: string): number => {
    if (a[a.length - 1] < b[b.length - 1]) return -1;
    if (a[a.length - 1] > b[b.length - 1]) return 1;
    if (a[a.length - 1] === b[b.length - 1]) return 0;
};
```

I think I can accept the change:

```js
const sortFn = (a, b) => {
  if (a[a.length - 1] < b[b.length - 1]) {
    return -1; // Negative number => a < b, a comes before b
  }
  if (a[a.length - 1] > b[b.length - 1]) {
    return 1; // Positive number => a > b, a comes after b
  }
  return 0; // Zero => a = b, a and b keep their original order
}

**Comment by Josh-Cena** [comment]
I still don't like the multiple `if`s. `else if` is not only one line shorter, it also conveys the idea that the different conditions are disjoint.

**Review by Josh-Cena — APPROVED** [review]
Thank you!

**Pull request merged**
