### PR TITLE
Add 0n,-0n to the JS “sameness” comparison table

### PR DESCRIPTION
**Pull request by arturcarvalho**
Add comparison between `0n` and `-0n` to the comparisons table based on issue https://github.com/mdn/content/issues/1309

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Artur, very nice refinement — thanks much, and congrats on landing your first docs change here. Welcome aboard 🎉

**Comment by arturcarvalho** [comment]
> 
> 
> Artur, very nice refinement — thanks much, and congrats on landing your first docs change here. Welcome aboard 🎉

Thank you very much @sideshowbarker. It's still a bit hard to believe that I was able to make a change to THE reference :sweat_smile:

**Comment by chrisdavidmills** [comment]
> Thank you very much @sideshowbarker. It's still a bit hard to believe that I was able to make a change to THE reference 😅

I love this ;-)

But yeah, anyone who has the enthusiasm is welcome to help make MDN better.

**Comment by arturcarvalho** [comment]
> I love this ;-)
> 
> But yeah, anyone who has the enthusiasm is welcome to help make MDN better.

Thanks for the kind reply @chrisdavidmills.

Maybe you find this interesting: 3 weeks ago I started writing a [post](https://www.coderanx.com/javascript/falsy-values-in-javascript) that I thought it would take 5 minutes and because I couldn't understand why there were [8 falsy values](https://github.com/mdn/content/issues/1309) I'm  now reading the spec and IEEE stuff to understand what is the reasoning to have different results when dividing `number` and `BigInt` by `0`.

It's like I opened a can of worms and then thought, these are quite tasty, let me eat some more =)

**Comment by chrisdavidmills** [comment]
> > I love this ;-)
> > But yeah, anyone who has the enthusiasm is welcome to help make MDN better.
> 
> Thanks for the kind reply @chrisdavidmills.
> 
> Maybe you find this interesting: 3 weeks ago I started writing a [post](https://www.coderanx.com/javascript/falsy-values-in-javascript) that I thought it would take 5 minutes and because I couldn't understand why there were [8 falsy values](https://github.com/mdn/content/issues/1309) I'm now reading the spec and IEEE stuff to understand what is the reasoning to have different results when dividing `number` and `BigInt` by `0`.
> 
> It's like I opened a can of worms and then thought, these are quite tasty, let me eat some more =)

Ha, nice!

And I love the LotR Mnemonic ;-)

**Pull request merged**
