### PR TITLE
Updated the description of Invalid_State_Err

### LINKED ISSUE #2589: Issue with "WebSocket.send()": Exceptions thrown listed is incorrect
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/send

#### What information was incorrect, unhelpful, or incomplete?
In the Exceptions Thrown section, it says the `INVALID_STATE_ERR` exception is thrown when `send` is called while the connection is not `OPEN`. That is incorrect, as an exception is only called in the `CONNECTING` state; if `CLOSING` or `CLOSED`, send just discards the data. Refer to RFC: https://html.spec.whatwg.org/multipage/web-sockets.html#dom-websocket-send
Or run the following snippet in a browser console: 
```
var ws = new WebSocket("wss://invalid-ws-url.com");
setTimeout(() => ws.send("Hello"), 5000);
```

#### Specific section or headline?
Exceptions thrown->INVALID_STATE_ERR

#### What did you expect to see?
Should say it only throws in the state is `CONNECTING`. Should probably mention in the description of the method that it doesn't do anything if the connection is already closed, and the onus is on the user to check the `readyState` before calling `send`.

#### Did you test this? If so, how?
Ran a snippet in the browser console:
```
var ws = new WebSocket("wss://invalid-ws-url.com");
setTimeout(() => ws.send("Hello"), 5000);
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/websocket/send`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/send
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/websocket/send/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

### PR DESCRIPTION
**Pull request by CreaTorAlexander**
Fixes #2589 

Updated with informations from here.
https://html.spec.whatwg.org/multipage/web-sockets.html#dom-websocket-send

### CODE REVIEW

**Review by wbamberg — CHANGES_REQUESTED** [review]
The bug report also says:

>  Should probably mention in the description of the method that it doesn't do anything if the connection is already closed, and the onus is on the user to check the readyState before calling send.

I'm not sure checking `readyState` is a good idea, because presumably there's always the possibility that the connection started closing after you checked but before you sent. So you have to handle that case anyway (if you care). But it might be worth adding an extra paragraph after the introductory paragraph, something like:

> The browser will throw an exception if you call `send()` when the connection is in the `CONNECTING` state. If you call `send()` when the connection is in the `CLOSING` or `CLOSED` states, the browser will silently discard the data.

**Comment by CreaTorAlexander** [comment]
I will take a look at the extra paragraph later on. Thanks for your review.

**Comment by wbamberg** [comment]
@CreaTorAlexander , are you still intending to finish this PR, and can I help with anything here?

**Comment by CreaTorAlexander** [comment]
@wbamberg acutally I have forgott about this issue. I will take a look at it in the next days. Thank you for the reminder.

**Comment by sideshowbarker** [comment]
@CreaTorAlexander, are still going to be able to make time to work further on this PR?

**Comment by sideshowbarker** [comment]
Closing for lack of response.

**Pull request closed without merging**
