### PR TITLE
Remove documentation for <content> element

### PR DESCRIPTION
**Pull request by queengooborg**
This PR removes the documentation for the `<content>` HTML element.  Correlates with https://github.com/mdn/browser-compat-data/pull/19147.

### CODE REVIEW

**Comment by teoli2003** [comment]
We should redirect the old pages to https://developer.mozilla.org/en-US/docs/Web/Web_Components

People looking for these pages (or following a link) are likely dealing with Web Components, and the most up-to-date info about it should be there.

(In general, we shouldn't delete a page without adding a redirect–unless it is a clear error)

**Comment by teoli2003** [comment]
It has been replaced by `<slot>`.

**Comment by Elchi3** [comment]
Ah okay, yes, in that case we should put redirects to https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement

**Comment by wbamberg** [comment]
Is it also worth adding a note there like:

> This is the replacement for the deprcated `<content>` element.

...so people expecting to be at `<content>` and landing there have some context?

**Comment by teoli2003** [comment]
> Is it also worth adding a note there like:
> 
> > This is the replacement for the deprcated `<content>` element.
> 
> ...so people expecting to be at `<content>` and landing there have some context?

I'm not sure we should do this: this is noise added to `<slot>`. `<content>` is almost unknown. It was a test a long time ago.  We are unsure if there are links to that page and if anybody will visit it and go through the redirect. It really is a redirect just-in-case.

So I'm not sure we should complicate the page for everybody to lower the surprise of somebody following a linkto a feature outdated for a decade.

Yes, there will be a surprise for somebody trying to visit these pages, but I think that's fine for outdated features long removed from the Web.

**Comment by wbamberg** [comment]
@queengooborg , do you want to take care of this: https://github.com/mdn/content/pull/25352#issuecomment-1477995434 ?

**Comment by queengooborg** [comment]
I'm trying to, but running `yarn content add-redirect /en-US/docs/Web/API/HTMLContentElement /en-US/docs/Web/API/HTMLSlotElement` (and a few variants) is reporting `Invalid URL`.

**Comment by teoli2003** [comment]
Just spent a lot of time trying to fix the redirects manually. I'll go back to this next week. There is clearly a bug.

**Review by teoli2003 — APPROVED** [review]
👍

**Pull request merged**
