### PR TITLE
Update WAI-ARIA link from 1.1 to 1.2

### PR DESCRIPTION
**Pull request by erastus-murungi**
### Description

Just a tiny change that updates the WAI-ARIA recommendation link to the latest one. From 1.1 to 1.2

### Motivation

Providing readers with an easier way to get to the latest version of the W3C (WAI-ARIA) recommendation.

### CODE REVIEW

**Comment by scottaohara** [comment]
why not link to https://www.w3.org/TR/wai-aria/ instead - which will always link to the latest W3C rec.  That way it doens't need to be updated again when ARIA 1.3, 1.4, 1.x drops?

**Review by scottaohara — CHANGES_REQUESTED** [review]
see above comment

**Comment by erastus-murungi** [comment]
Thanks for the quick review. You're right it does make sense to have link language agnostic. I have made the requested change.

**Review by scottaohara — APPROVED** [review]

**Review by estelle — APPROVED** [review]
Thank you. Also, congratulations on your first merged MDN content PR. Welcome to he team!

**Pull request merged**
