### PR TITLE
Propose alternative examples for OOP

### PR DESCRIPTION
**Pull request by tshemsedinov**
#### Summary
Abstractions such as `Person`, `Animal`, `Foo`, `Bar`, `Cat`, and `Professor` don't give a proper understanding of OOP, they are widespread in books and guides for beginners, but can be never found in a real programs. Such abstraction are neither DTOs nor domain model classes, they are just tutorial examples. I propose to take programming and mathematical abstractions like `Adder`, `Point`, `List`, `Lock`, `Connection`, `Session`, `Pool` which can be very simple and expressive enough to show all OOP features. At the same time those abstractions are good enough to be moved with minimal corrections to the real production code. Here are examples from my university course and I believe, it works.

#### Metadata
- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by hamishwillee** [comment]
Firstly, thanks @tshemsedinov for posting this PR. I can see you've put some thought and effort into it.

As a non-OOP or JavaScript expert I do not like this change. I don't find `Adder`, `Point`, `List`, `Lock`, `Connection`, `Session`, `Pool` at all familiar terms. In an example designed to take beginners through core concepts they are a distraction rather than a help for the core concepts. I'm sure that they might be helpful for computer scientists, but not for the far broader audience that  MDN addresses.

That is not to say that the examples used could not be better, but there are good reasons why most of these kinds of tutorials use simple models to demonstrate the concepts. We're probably lucky that this one didn't use the traditional car/manufacturer model :-).

Not my call though. Let's see what others think.

**Comment by tshemsedinov** [comment]
@hamishwillee You are right, those examples are from university CS course (`Adder`, `Point`, `List`, `Lock`, `Connection`, `Session`, `Pool`) for teaching professionals (`Software engineering` specialty). MDN addresses wider audience, even non-technical and we should use common-knowledge. That's why I use just math examples: `Point`, `Rectangle`, `Triangle`, `Polygon`. Also I removed examples like `Person`, `Professor`, `Student`, `Animal` from this article because this classes representing not real-world objects `Person`, but its informational aspect, so it would be better name for this class `InformationAboutPerson`. I do not like that `Animal` have method `slip` or `eat` printing something to console and `Professor` have methods like `introduceSelf` or `grade` printing something to console because such behavior should not be implemented in informational classes. It is so imaginary... It would be good co combine data and behavior in class `ComboBox` or `Socket`, methods and event are natural for such classes and they may do something useful. But we can't use such abstractions, because they are difficult for beginners. Maybe `Adder` will be easier, just a container for number to have a value inside and `add` method. We need something except math abstractions. Maybe we can express OOP using `Array`, `Map`, `Set` classes as a polyfills for built-in classes so it is known for everybody. And that will be something existing in production programming. What do you think, I'll prepare examples quickly.

**Comment by hamishwillee** [comment]
@tshemsedinov Thanks for the clarification. Looking at the actual Math example you have done, rather than the ones mentioned in the description this is not intimidating. This kind of example has a long and illustrious history in OOP education - I think the first course I did used the example of shape, square and rectangle. `Adder` is a little odd in this context.

Honestly, I don't see this this change as "wrong", but I do see it as _unnecessary_. I don't find the fact that Person etc are not "real world" objects in any way a barrier to understanding the concepts.

But I'm going to leave it to @wbamberg to review since he's currently working his way through updating many of the JavaScript documents.

**Comment by bsmth** [comment]
Hi @tshemsedinov thanks a lot for your additions. I'm going to close this one for now as it looks inactive and there are quite a lot of conflicts between your branch and `main`. If you think this is wrong, please feel free to comment or reopen with new changes.

Thanks a lot :)

**Pull request closed without merging**
