### PR TITLE
remove re-declaration of myNum and myString

### PR DESCRIPTION
**Pull request by DoodleDeBug**
re-declaration of variables aka "let" causes an error

### CODE REVIEW

**Comment by hamishwillee** [comment]
@DoodleDeBug I read this example as replacing the code from the previous example, which would work (you have obviously just appended the code). This is different than the case you posted in https://github.com/mdn/content/pull/1466, where you might reasonable append all 3 lines.

So I disagree with this change. However if you think on re-reading that this is ambigous you might make the following change instead ... 

image

**Comment by DoodleDeBug** [comment]
@hamishwillee I think as a beginner it's not that obvious how to clear/replace the previous code and it isn't mentioned in the chapter about dev tools either. So maybe that is something to be added to the dev tools page? Unfortunately, as a beginner myself, the only way I know to clear the console (and get rid of stored variables) is by refreshing the page! I think replacing "Try this" with "Replace the previous code with this" is fine as long as it's made obvious somewhere else (preferably the dev tools console page) how to do this. So this page: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools

**Comment by hamishwillee** [comment]
Ah, I was ensvisaging using a loaded HTML file, but you're right, many will just post into the javascript console.

So suggest the solution is to rename the second mystring and typof

**Comment by DoodleDeBug** [comment]
> Ah, I was ensvisaging using a loaded HTML file, but you're right, many will just post into the javascript console.
> 
> So suggest the solution is to rename the second mystring and typof

Ok, sounds good...I will make them myNum2 and myString2. Also, did you mean myNum or typeof?? I will assume you meant myNum!

**Comment by hamishwillee** [comment]
Yes, I mean myString2 and myNum2. Sorry for being unclear!

**Pull request closed without merging**
