### PR TITLE
Phrasing content and flow content categories

### PR DESCRIPTION
**Pull request by madmurphy**
Added short clarifications to the phrasing content and flow content paragraphs

### CODE REVIEW

**Review by chrisdavidmills — COMMENTED** [review]
Thanks for updating this @madmurphy . I looked at this page and then fell down a rabbit hole and started to make a bunch more imrovements, as I felt that what was there could be so much better! So I hope you don't mind , but I've added a bunch more changes here, as well as copy editing your work. What do you think?

**Comment by madmurphy** [comment]
Looks great to me. I wanted to have an explicit sentence that stated that phrasing content can be used everywhere flow content is expected, as it happens in the following example, where two `Text` nodes and a phrasing element (`<strong>`) are nested directly inside the `<body>` element:

``` html
<body>
	To be, or not to be, <strong>that</strong> is the question
</body>
```

Although a bit unusual, the example above is perfectly valid. It wouldn't be so unusual though if a web developer wondered for instance whether it would be valid to nest a link element (`<a>`) directly inside a (`<nav>`) element without intermediate paragraphs (`<p>`). If they read the documentation, they would discover that the `<nav>` element expects flow content, while a `<p>` element instead expects phrasing content. At this point they might think that using an intermediate `<p>` element would be a better choice, but this would not be the case, since phrasing content is also flow content.

Clarifying this was the purpose of my intervention.

--madmurphy

**Comment by chrisdavidmills** [comment]
> Looks great to me. I wanted to have an explicit sentence that stated that phrasing content can be used everywhere flow content is expected, as it happens in the following example, where two `Text` nodes and a phrasing element (`<strong>`) are nested directly inside the `<body>` element:
> 
> ```
> <body>
> 	To be, or not to be, <strong>that</strong> is the question
> </body>
> ```
> 
> Although a bit unusual, the example above is perfectly valid. It wouldn't be so unusual though if a web developer wondered for instance whether it would be valid to nest a link element (`<a>`) directly inside a (`<nav>`) element without intermediate paragraphs (`<p>`). If they read the documentation, they would discover that the `<nav>` element expects flow content, while a `<p>` element instead expects phrasing content. At this point they might think that using an intermediate `<p>` element would be a better choice, but this would not be the case, since phrasing content is also flow content.
> 
> Clarifying this was the purpose of my intervention.
> 
> --madmurphy

This does make sense to me, but then I thought a bit more about this — surely _all_ of the categories that are subsets of flow content could be used everywhere that flow content is allowed, or expected? In which case I should update all of those places where I've put "x is a subset of flow content" to include "...and can be used everywhere flow content is expected"?

What do you think about this?

**Comment by madmurphy** [comment]
I think the confusion can arise only with phrasing content, since this is the only subgroup of flow content _required_ in some contexts – like for example inside a paragraph (`<p>`). The other subgroups of flow content are never _required_ as far as I know. There are no parent elements that for example expects only interactive content, embedded content, heading content or sectioning content (but I can always be wrong).

However, since MDN is a general guide, I think that adding “and can be used everywhere flow content is expected” for each subgroup as you have suggested is the right solution.

**Comment by chrisdavidmills** [comment]
Yup, just because it is not required, doesn't mean that people won't just do it anyway ;-) I suspect that this is our safest bet. I'll add those now, and get it merged. Thanks @madmurphy !

**Review by chrisdavidmills — APPROVED** [review]

**Pull request merged**
