### PR TITLE
fix: Typos in SVG and related

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]

**Comment by chrisdavidmills** [comment]
Hrm, I can't merge this one for some reason.

**Comment by nschonni** [comment]
@chrisdavidmills gave it a rebase to see if that helps

**Review by chrisdavidmills — APPROVED** [review]

**Comment by chrisdavidmills** [comment]
I used my admin privs to do it, although I'm not normally comfortable with doing that.

**Comment by nschonni** [comment]
Oh, maybe related to the CODEOWNERS?

**Pull request merged**
