### PR TITLE
Revert "Add underscores around slug of Object/proto"

### PR DESCRIPTION
**Pull request by caugner**
Reverts mdn/content#22828, as the change unfortunately breaks our build (**edit**: not only) in @queengooborg's `yari:esm` branch, which will be merged into `yari:main` next week.

### CODE REVIEW

**Comment by queengooborg** [comment]
Note that the PR also breaks the current main branch, not just the ESM branch!

**Review by Josh-Cena — APPROVED** [review]
I'm approving for now, but my understanding is correct that it hasn't broken anyone, right? In the future, when I'm trying to move the page again, do I need to wait for the upstream issue to be fixed, because at that time it's going to cause actual production pipeline breakage?

**Comment by Josh-Cena** [comment]
> Note that the PR also breaks the current main branch, not just the ESM updates!

Ah okay, thanks for the info! Let me know if I can be of any help.

**Comment by caugner** [comment]
> I'm approving for now, but my understanding is correct that it hasn't broken anyone, right?

In fact, it would have broken our prod build: https://github.com/mdn/yari/actions/runs/3660523191/jobs/6187762832#step:14:1389

**Pull request merged**
