### PR TITLE
Remove moz api

### LINKED ISSUE #21878: Remove mentions of moz APIs from drag&drop documentation
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Multiple_items

### What specific section or headline is this issue about?

_No response_

### What information was incorrect, unhelpful, or incomplete?

At some point all the moz APIs like `mozSetDatAt` were merely Firefox only, but at this point they have been completely removed. (Or rather they are inaccessible to web content)

This also affects https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types.

### What did you expect to see?

It might be best to just remove that page completely.

### Do you have any supporting links, references, or citations?

https://bugzilla.mozilla.org/show_bug.cgi?id=1666287

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by qibing147147**
### Related issues and pull requests
Fixes https://github.com/mdn/content/issues/21878

### CODE REVIEW

**Review by sideshowbarker — CHANGES_REQUESTED** [review]
This is really nice work but I think what https://github.com/mdn/content/issues/21878 is requesting is not just the removal of `files/en-us/web/api/datatransfer/mozsetdataat`, but also the removal of all the following:
```
files/en-us/web/api/datatransfer/mozcleardataat/
files/en-us/web/api/datatransfer/mozcursor/
files/en-us/web/api/datatransfer/mozgetdataat/
files/en-us/web/api/datatransfer/mozitemcount/
files/en-us/web/api/datatransfer/mozsourcenode/
files/en-us/web/api/datatransfer/moztypesat/
files/en-us/web/api/datatransfer/mozusercancelled/
```
@evilpie, can you confirm?

**Comment by qibing147147** [comment]
> This is really nice work but I think what #21878 is requesting is not just the removal of `files/en-us/web/api/datatransfer/mozsetdataat`, but also the removal of all the following:
> 
> ```
> files/en-us/web/api/datatransfer/mozcleardataat/
> files/en-us/web/api/datatransfer/mozcursor/
> files/en-us/web/api/datatransfer/mozgetdataat/
> files/en-us/web/api/datatransfer/mozitemcount/
> files/en-us/web/api/datatransfer/mozsourcenode/
> files/en-us/web/api/datatransfer/moztypesat/
> files/en-us/web/api/datatransfer/mozusercancelled/
> ```
> 
> @evilpie, can you confirm?

These apis may be used in old Firefox,so i just remove quote in main docs,but retain the api entry

**Comment by evilpie** [comment]
I think we could remove the API docs for mozItemCount, mozClearDataAt, mozGetDataAt and mozSetDataAt, because those are definitely unusable now. mozCursor, mozUserCacelled and mozSourceNode stil seem to exist.

**Comment by qibing147147** [comment]
> I think we could remove the API docs for mozItemCount, mozClearDataAt, mozGetDataAt and mozSetDataAt, because those are definitely unusable now. mozCursor, mozUserCacelled and mozSourceNode stil seem to exist.

Remove mozItemCount, mozClearDataAt, mozGetDataAt and mozSetDataAt completely? ut if someone still wants to use these apis on the old browser,they may not be able to see these apis

**Comment by sideshowbarker** [comment]
@qibing147147 

> Remove mozItemCount, mozClearDataAt, mozGetDataAt and mozSetDataAt completely? ut if someone still wants to use these apis on the old browser,they may not be able to see these apis

But the current patch in this PR is already completely removing the entire `mozSetDatAt` article, right?

How are the cases of `mozItemCount`, `mozClearDataAt`, and `mozGetDataAt` different than the case of `mozSetDatAt`?

**Comment by qibing147147** [comment]
> @qibing147147
> 
> > Remove mozItemCount, mozClearDataAt, mozGetDataAt and mozSetDataAt completely? ut if someone still wants to use these apis on the old browser,they may not be able to see these apis
> 
> But the current patch in this PR is already completely removing the entire `mozSetDataAt` article, right?
> 
> How are the cases of `mozItemCount`, `mozClearDataAt`, and `mozGetDataAt` different than the case of `mozSetDataAt`?



> @qibing147147
> 
> > Remove mozItemCount, mozClearDataAt, mozGetDataAt and mozSetDataAt completely? ut if someone still wants to use these apis on the old browser,they may not be able to see these apis
> 
> But the current patch in this PR is already completely removing the entire `mozSetDataAt` article, right?
> 
> How are the cases of `mozItemCount`, `mozClearDataAt`, and `mozGetDataAt` different than the case of `mozSetDataAt`?

Sorry,I remove the `mozSetDataAt` article by mistake,I will revert the `mozSetDataAt` article. At the same time, I will remove quotes of `mozItemCount`, `mozClearDataAt`, `mozGetDataAt` and `mozSetDataAt` in main docs,but retain the entrance of these apis.Is that OK, you think?

**Comment by sideshowbarker** [comment]
> Is that OK, you think?

I think @evilpie should be the one to decide what’s OK here — since he’s the one who raised the issue this PR is intended to resolve. But at https://github.com/mdn/content/pull/22092#issuecomment-1305357940, he already said:

> I think we could remove the API docs for mozItemCount, mozClearDataAt, mozGetDataAt and mozSetDataAt, because those are definitely unusable now.

…so I imagine we can assume he’s not OK with not removing them.

This PR overall is otherwise great, and I’d be happy to merge it as-is. But merging it as-is wouldn’t resolve https://github.com/mdn/content/issues/21878 — so if we do merge it as-is, then pretty much the next thing I’d do is to then open a follow-up PR myself that removes the `mozItemCount`, `mozClearDataAt`, `mozGetDataAt` and `mozSetDataAt` docs.

**Comment by qibing147147** [comment]
> > Is that OK, you think?
> 
> I think @evilpie should be the one to decide what’s OK here — since he’s the one who raised the issue this PR is intended to resolve. But at [#22092 (comment)](https://github.com/mdn/content/pull/22092#issuecomment-1305357940), he already said:
> 
> > I think we could remove the API docs for mozItemCount, mozClearDataAt, mozGetDataAt and mozSetDataAt, because those are definitely unusable now.
> 
> …so I imagine we can assume he’s not OK with not removing them.
> 
> This PR overall is otherwise great, and I’d be happy to merge it as-is. But merging it as-is wouldn’t resolve #21878 — so if we do merge it as-is, then pretty much the next thing I’d do is to then open a follow-up PR myself that removes the `mozItemCount`, `mozClearDataAt`, `mozGetDataAt` and `mozSetDataAt` docs.

It's OK. I will remove quotes and entrance of these apis.

I'd like to ask u a question.

Why is the Markdownlint executed incorrectly?

image

**Comment by qibing147147** [comment]
> > I'd like to ask u a question.
> > Why is the Markdownlint executed incorrectly?
> 
> I don’t know. We’ve been having a variety of `git`-related failures with the Markdown linter running under our GitHub Actions CI. I think it has something to do with the specific GH action that does the checkout only doing a shallow clone rather than fully cloning the repo. But I’m not sure. Regardless, the error message shown in [#22092 (comment)](https://github.com/mdn/content/pull/22092#issuecomment-1308416230) doesn’t indicate any specific problem with the changes in this PR but is instead some unrelated failure in our tooling — and so, we could merge this PR in spite of that.



> > I'd like to ask u a question.
> > Why is the Markdownlint executed incorrectly?
> 
> I don’t know. We’ve been having a variety of `git`-related failures with the Markdown linter running under our GitHub Actions CI. I think it has something to do with the specific GH action that does the checkout only doing a shallow clone rather than fully cloning the repo. But I’m not sure. Regardless, the error message shown in [#22092 (comment)](https://github.com/mdn/content/pull/22092#issuecomment-1308416230) doesn’t indicate any specific problem with the changes in this PR but is instead some unrelated failure in our tooling — and so, we could merge this PR in spite of that.

OK.Thanks for ur reply

**Comment by qibing147147** [comment]
> > I'd like to ask u a question.
> > Why is the Markdownlint executed incorrectly?
> 
> I don’t know. We’ve been having a variety of `git`-related failures with the Markdown linter running under our GitHub Actions CI. I think it has something to do with the specific GH action that does the checkout only doing a shallow clone rather than fully cloning the repo. But I’m not sure. Regardless, the error message shown in [#22092 (comment)](https://github.com/mdn/content/pull/22092#issuecomment-1308416230) doesn’t indicate any specific problem with the changes in this PR but is instead some unrelated failure in our tooling — and so, we could merge this PR in spite of that.

I have remove moz apis completely,would you mind heping me review again?

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
@qibing147147, thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

**Pull request merged**
