### PR TITLE
Auto-label new issues based on MDN URLs in description

### PR DESCRIPTION
**Pull request by sideshowbarker**
This change causes appropriate labels to be automatically added (using a GitHub Action) to new issues based on matches for particular MDN URL pathnames/slugs found anywhere in the issue descriptions.

<s>Although this initial PR only includes matching for MDN URL pathnames/slugs, the underlying GitHub Action being added here allows us to match on any arbitrary issue-description substrings we want. So we may later find some auto-labeling uses for it other than just matching on MDN URLs.</s>

### CODE REVIEW

**Comment by schalkneethling** [comment]
@sideshowbarker Thanks so much for this pull request. I read the description of how this works over on the action’s repo and noticed this line: "Should the regular expression not match, the label will be removed."

Could this cause issues with our current auto labeling? @Rumyra thoughts?

**Comment by Rumyra** [comment]
> Could this cause issues with our current auto labeling? @Rumyra thoughts?

Yes what @sideshowbarker said :) The only auto labelling at the moment is `needs-triage` and `idle` which I don't see this affecting. And if one of the labels in this action are _not_ added because there's no MDN url, that could be used as a good indication the issue should be elsewhere anyway, so may be helpful.

**Comment by nschonni** [comment]
May be worth using the versioned templates https://github.com/github/issue-labeler#example-using-versioned-issue-templates

**Comment by schalkneethling** [comment]
> May be worth using the versioned templates https://github.com/github/issue-labeler#example-using-versioned-issue-templates

@sideshowbarker Thoughts? Do you want to look into this first or are we good to merge?

**Review by schalkneethling — APPROVED** [review]

**Pull request merged**
