### PR TITLE
updating section article, including adding info about headings

### LINKED ISSUE #2240: Need example of when a <section> might NOT have a heading
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
I think it would be useful to clarify what is meant by:

<blockquote>Typically, but not always, sections have a heading.</blockquote>

Specifically, I would like for the article to clarify when a section might *not* have a heading.

(I'm wondering about this myself.)

A [usage note](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section#Usage_notes) specifies:

<blockquote>Each <code>&lt;section&gt;</code> should be identified, typically by including a heading (<code>&lt;h1&gt;</code>-<code>&lt;h6&gt;</code> element) as a child of the &lt;section&gt; element.</blockquote>

HTML Living Standard specifies:

<blockquote>A section, in this context, is a thematic grouping of content, typically with a heading.</blockquote>

The section examples at the [<code>section</code> MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) and https://html.spec.whatwg.org/multipage/sections.html#the-section-element all use <code>&lt;h1&gt;</code>-<code>&lt;h6&gt;</code> elements.

### PR DESCRIPTION
**Pull request by chrisdavidmills**
Fixes #2240 

@jonkri, what do you think?

### CODE REVIEW

**Comment by jonkri** [comment]
@chrisdavidmills:

Thanks for this! :slightly_smiling_face: Very interesting!

The way I have generally worked with sections like these (the ones in the heading exceptions examples) has been to add a heading anyway, and then perhaps hide it visually using CSS. In other words, I've been in the habit of kind of "forcing" a document outline whenever I have thought that a section has been a good way to group content together. So in the button bar, for instance, I would something like `<h1 style="display: none;">Controls</h1>` inside the section element.

I'm wondring what benefit these sections without headings give us. Less `div` elements in the code would be one, I guess. Are there accessibility or SEO benefits as well? Would it be possible to say something about where we would generally draw the line between `div` and `section` elements without headings?

Thanks!

**Comment by Ryuno-Ki** [comment]
> I would something like `<h1 style="display: none;">Controls</h1>` inside the section element.

This will also hide it for screenreaders. https://webaim.org/techniques/css/invisiblecontent/ has recommendations how to style them instead. (I haven't checked, whether mdn-minimalist already provides such an utility class).

**Comment by chrisdavidmills** [comment]
Thanks for the comments @jonkri and @Ryuno-Ki . I've added a little bit more to cover hidden headings, as I do think it is worth talking about.

I don't think it is worth talking about `<div>` versus `<section>` without headings...?

**Comment by chrisdavidmills** [comment]
> "outine" should be "outline" here.

fixed, thanks!

**Comment by rachelandrew** [comment]
@chrisdavidmills there is a good overview of when to use article or section here https://www.smashingmagazine.com/2020/01/html5-article-section/ might be worth adding as a "See also"?

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills there is a good overview of when to use article or section here https://www.smashingmagazine.com/2020/01/html5-article-section/ might be worth adding as a "See also"?

Agreed, and added!

**Review by rachelandrew — APPROVED** [review]

**Pull request merged**
