### PR TITLE
Changed the URLs to the Trusted Types repository.

### PR DESCRIPTION
**Pull request by koto**
### Description

Changed the repository URL for Trusted Types spec/polyfill.

### Motivation

The repository was renamed.

### CODE REVIEW

**Comment by bsmth** [comment]
Thank you! It looks like this is also referenced in [`files/jsondata/SpecData.json`](https://github.com/mdn/content/blob/main/files/jsondata/SpecData.json) would you like to update it there, also?

**Comment by koto** [comment]
Good point! Done, thanks!

**Comment by bsmth** [comment]
Thanks @koto. There's some occurrences elsewhere I found when grepping the source, [I've listed them above](https://github.com/mdn/content/pull/22661#issuecomment-1333836405). Do you want to change them or should I do that on your branch?

**Comment by koto** [comment]
Done :)

**Review by bsmth — APPROVED** [review]
LGTM, would be nice to have another +1 to double-check

**Review by Elchi3 — APPROVED** [review]
LGTM

browser-specs is usually our authority for spec urls and they made the change as well :) https://github.com/w3c/browser-specs/pull/729

**Comment by koto** [comment]
Thanks!

**Pull request merged**
