### PR TITLE
flattening document

### PR DESCRIPTION
**Pull request by mattiapontonio**

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
I think what you are doing here is good, but:

"How to use URLs" should also be uplifted to an H2

And "Examples of absolute URLs"/"Examples of relative URLs" should be H3s

**Comment by mattiapontonio** [comment]
@chrisdavidmills actually Yes.
Can You please suggest and i commit?

**Review by chrisdavidmills — APPROVED** [review]
I've fixed them. Ready to merge now.

**Comment by mattiapontonio** [comment]
@chrisdavidmills thanks. I've got the mechanism of requesting change so next time i Will try to commit after the comment.

**Pull request merged**
