### PR TITLE
Daily markdownlint

### PR DESCRIPTION
**Pull request by OnkarRuikar**

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]

**Comment by OnkarRuikar** [comment]
Was trying to figure out the macro issue:
> Unexpected input
[ [ | ] [ ]? ]#? [ auto | default | none | context-menu | help | pointer | progress | wait | cell | crosshair | text | vertical-text | alias | copy | move | no-drop | not-allowed | grab | grabbing | e-resize | n-resize | ne-resize | nw-resize | s-resize | se-resize | sw-resize | w-resize | ew-resize | ns-resize | nesw-resize | nwse-resize | col-resize | row-resize | all-scroll | zoom-in | zoom-out ]

The macro renders as it is `{{csssyntax}}` on main site.

But looks like it's an ongoing issue since mid Jun.

**Comment by teoli2003** [comment]
Can you file an issue?

**Comment by OnkarRuikar** [comment]
> Can you file an issue?

I think this is related to https://github.com/mdn/yari/issues/6779 .

**Comment by teoli2003** [comment]
Oh yes, thank you. We are waiting for the new version of CSS Tree to be used by MDN (Friendly ping, @schalkneethling ).

**Pull request merged**
