### PR TITLE
Update index.md

### LINKED ISSUE #27127: The "start" parameter of Array.prototype.copyWithin() is not optional
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/copyWithin

### What specific section or headline is this issue about?

TypedArray.prototype.copyWithin()

### What information was incorrect, unhelpful, or incomplete?

https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/typedarray/copywithin/index.md

https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.copywithin

### What did you expect to see?

The "start" parameter of `TypedArray.prototype.copyWithin()`  is required.

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/typedarray/copywithin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/copyWithin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/typedarray/copywithin/index.md
* Last commit: https://github.com/mdn/content/commit/194d3e00cb93a6e5ea44812548f4131cb17f0381
* Document last modified: 2023-02-21T00:33:25.000Z

</details>

### PR DESCRIPTION
**Pull request by postmeback**
Added the text given in the issue

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Sorry that issue was framed in a weird way (I believe the OP got confused), but the issue is about _removing_ optionality from Array#copyWithin, not to do anything with TypedArray.

**Comment by postmeback** [comment]
Hi @Josh-Cena , can you please simplify the requirement / bug and (maybe) provide suggestion to this PR.

TIA

**Review by estelle — APPROVED** [review]
Thanks! 🎉

**Comment by Josh-Cena** [comment]
Sorry I didn't request changes, but this is not supposed to be merged😅

**Pull request merged**
