### PR TITLE
Express: mongoose connection update

### PR DESCRIPTION
**Pull request by hamishwillee**
This updates the mongodb connection as per my testing today.

Note that the main change is the connection screen, but also the default URL is simpler, and reflects cluster not database name.

This testing initiated by PR here: #22763

### CODE REVIEW

**Comment by hamishwillee** [comment]
@caugner Something odd going on here. I'm getting errors for `filecheck` fails in CI, but I got no errors in local linter when doing the commit. 


If I run the commands suggested by CI locally, 

```
       2 of 2 errors can be fixed:
       
       yarn filecheck 'files/en-us/learn/server-side/express_nodejs/mongoose/mongodb_atlas_-_chooseaconnectionmethod.jpg' --save-compression
       yarn filecheck 'files/en-us/learn/server-side/express_nodejs/mongoose/mongodb_atlas_-_connectforshortsrv.jpg' --save-compression
```

... Then I get told nothing to fix (this is on Windows)

```
D:\github\mozilla\content>yarn filecheck 'files/en-us/learn/server-side/express_nodejs/mongoose/mongodb_atlas_-_chooseaconnectionmethod.jpg' --save-compression
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files yari-filecheck --cwd=. 'files/en-us/learn/server-side/express_nodejs/mongoose/mongodb_atlas_-_chooseaconnectionmethod.jpg' --save-compression
progress [========================================] 100% | ETA: 0s | 0/0
Done in 1.05s.

D:\github\mozilla\content>yarn filecheck 'files/en-us/learn/server-side/express_nodejs/mongoose/mongodb_atlas_-_connectforshortsrv.jpg' --save-compression

yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files yari-filecheck --cwd=. 'files/en-us/learn/server-side/express_nodejs/mongoose/mongodb_atlas_-_connectforshortsrv.jpg' --save-compression
progress [========================================] 100% | ETA: 0s | 0/0
Done in 1.03s.

D:\github\mozilla\content>git status
On branch mongodb_pt2
nothing to commit, working tree clean
```

**Comment by bsmth** [comment]
Hi @hamishwillee, I ran the `yarn filecheck` commands on macOS and checked them in: https://github.com/mdn/content/pull/22914/commits/6069864a1c436026424a13ff96dd523297ce01e7

Claas should have a look here as a follow-up, the tooling is likely not portable for the file paths cross-OS.

**Review by bsmth — APPROVED** [review]
Thanks @hamishwillee 👍🏻

**Comment by blobtub** [comment]
Following on from @hamishwillee's comment on a related PR #22763, I tested the simpler connection URL from the tutorial app and this created a database "test" on the cluster (rather than using the "local_library" database indicated by the tutorial instructions).  
Do we want to change the instructions in the tutorial to use this (presumably, default) test database, or prompt the user to amend the connection URL so it uses the local_library database?

**Comment by hamishwillee** [comment]
@blobtub Good catch - thank you very much. I have fixed in https://github.com/mdn/content/pull/22996 to add the db back to the string, and also fix a couple of other minor inconsistencies.

**Comment by hamishwillee** [comment]
Thanks for review and fixes @bsmth

**Pull request merged**
