### PR TITLE
typo: notes

### PR DESCRIPTION
**Pull request by estelle**

### CODE REVIEW

**Comment by Josh-Cena** [comment]
Ooops, I've just sent https://github.com/mdn/content/pull/35344, with a corresponding Markdown lint rule ^^ Should we merge yours, and then rebase mine, and you can review that too?

**Comment by estelle** [comment]
> Ooops, I've just sent #35344, with a corresponding Markdown lint rule ^^ Should we merge yours, and then rebase mine, and you can review that too?

Beat you to it! 

We can just close this one and merge #35344, but the X and Y are in #34931, which is a larger PR, though that might be the only edtis on those two pages.

**Comment by Josh-Cena** [comment]
It would be better to just merge #35344, then, so #34931 doesn't touch files it doesn't otherwise need to touch.

**Comment by estelle** [comment]
Closing as this will be resolved by https://github.com/mdn/content/pull/35344,

**Pull request closed without merging**
