### PR TITLE
Run Prettier over guide pages

### PR DESCRIPTION
**Pull request by Josh-Cena**
Also refactored content where necessary to avoid weird code.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by Josh-Cena** [comment]
My first merged pull request? Yay!

**Comment by hamishwillee** [comment]
Yes, I pinged @schalkneethling on this for another one. Something wrong with the automation.

**Comment by bsmth** [comment]
I think this runs once per contributor from the date it's been enabled in the repo

**Pull request merged**
