### PR TITLE
Replace JPG with PNG screenshot

### LINKED ISSUE #24854: Incorrect image format used to demonstrate pixel quality
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

### What specific section or headline is this issue about?

Correcting resolution in a <canvas>

### What information was incorrect, unhelpful, or incomplete?

The example with writing "I love MDN" on a green box is blurry.

### What did you expect to see?

A high-quality image. You can't display a quality simple two-color image using jpeg lossy compression! This should be png format instead.

### Do you have any supporting links, references, or citations?

Adobe and many others says about using png

**They’re often the default format for screenshot images since they can provide a highly accurate representation of your desktop and don’t compress pixels together. A huge color palette and lossless compression ensure they retain plenty of detail — making them a popular choice for illustrations and charts.**

### Do you have anything more you want to share?

Here is an example zoomed in Photoshop. You can see the typical jpeg "fuzz" around the letters and the general noise in the image. The image on the right, if png, would be razor sharp! Or at least with png at most would be some anti-aliasing edges. Be sure to view this full-size, not the size in the box shown here (click on it with a big terminal window)

Given it's a graphic, and I'm new to MDN, I don't feel comfortable providing an alternate png file.

mdn
full-size

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/devicepixelratio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/devicepixelratio/index.md
* Last commit: https://github.com/mdn/content/commit/bb8221e061bba27dbdbe5a3698b6c69febf0bc70
* Document last modified: 2023-02-19T07:19:47.000Z

</details>

### PR DESCRIPTION
**Pull request by Josh-Cena**
### Description

Fix https://github.com/mdn/content/issues/24854

### CODE REVIEW

**Comment by ferdnyc** [comment]
@Josh-Cena 

Thanks for doing this! Two thoughts:

1. This seems a golden opportunity to rename the file from the nonsensical `devicepixelration_diff` to what I assume it was always supposed to be, `devicepixelratio_diff`. (Modulo the different extension.)

2. The new image is **significantly** larger than the old one (`1592px` wide, compared to `1120px` for the JPG). I'm slightly concerned that may lead to it being _downscaled_ when displayed on many devices/browsers. Which could also affect the quality of the demonstration.
 
    (Then again, the old file was probably downscaled on non-HiDPI screens already. I don't think the MSDN site CSS permits the content DIV to grow that wide, in desktop browsers. And my phone, for example, has a 1080px-wide screen, so it displays the JPG at ~900px wide already. Maybe it's a moot point.)

**Comment by Josh-Cena** [comment]
So... I don't need to do anything about the size? I could either scale the image myself or I could re-take a screenshot with a demo that appears _smaller_ on my screen, but neither sounds ideal to me.

**Comment by ferdnyc** [comment]
@Josh-Cena 

IMHO it's fine as-is, though technically my opinion carries less weight than yours seeing as you're a project member and I'm just some random guy. :grin:

**Comment by Josh-Cena** [comment]
> technically my opinion carries less weight than yours

Not at all! I'm not a maintainer of the WebAPI docs, neither am I very well-versed with screen resolutions, image formats, etc., so I'm definitely open to your feedback.

**Review by wbamberg — APPROVED** [review]
👍 thank you @Josh-Cena and @ferdnyc !

**Pull request merged**
