### PR TITLE
add initial rfc to repo

### PR DESCRIPTION
**Pull request by chrisdavidmills**
As part of the MDN opportunity assessment process, we are intending to create RFCs to explain a suggested larger stream of work that we want to work on. This is the first of those RFCs.

---

Checklist — To help your pull request get merged faster, please do following:

1. - [ ] Provide a summary of your changes — say what problem you are fixing, what files are changed, what you've done. This doesn't need to be hugely detailed, as we can see exact changes in the "Files changed" tab.
1. - [ ] Provide a link to the issue(s) you are fixing, if appropriate, in the form "Fixes _url-of-issue_". GitHub will render this in the form "Fixes #1234", with the issue number linked to the issue. Doing this allows us to figure out what issues you are fixing, as well as helping to automate things (for example the issue will be closed once the PR that fixed it has been merged).
1. - [ ] Review the results of the automated checking we run on every PR and fix any problems reported (see the list of checks near the bottom of the PR page). If you need help, please ask in a comment!
1. - [ ] Link to any other resources that you think might be useful in reviewing your PR.

### CODE REVIEW

**Comment by peterbe** [comment]
> I'd like a comment from @mdn/core-yari-dev about whether they are OK with me storing these things here. I'll also invite some other folks to have a look at te PR content itself.

👍 

However, I think you should extend the `markdown-lint.yml` file so it also checks this directory. E.g.:
```diff
on:
  pull_request:
    branches:
      - main
    paths:
      - '*.md'
+     - 'rfcs/**/*.md'
      - .github/workflows/markdown-lint.yml


jobs:
```

**Comment by escattone** [comment]
> I'd like a comment from @mdn/core-yari-dev about whether they are OK with me storing these things here. I'll also invite some other folks to have a look at te PR content itself.

👍 From me as well.

**Comment by nschonni** [comment]
> However, I think you should extend the `markdown-lint.yml` file so it also checks this directory. E.g.:

I'd probably suggest replacing the current glob with `- '**/*.md'`

**Comment by peterbe** [comment]
> > However, I think you should extend the `markdown-lint.yml` file so it also checks this directory. E.g.:
> 
> 
> 
> I'd probably suggest replacing the current glob with `- '**/*.md'`

Let's not do that. I don't know if we're ready to use that CLI to lint all the content index.md files when we move to Markdown later this or next month.

**Comment by chrisdavidmills** [comment]
Thanks for the comments folks. I've added the RFCs to the markdown linting as suggested by @peterbe , and also upddated the table markdown syntax, as it is horrible to read, and I suspect will be horrible to get to pass the markdown linting ;-)

**Review by schalkneethling — APPROVED** [review]
I love this, thanks @chrisdavidmills - As a side note, I would love to be involved here as much as possible.

**Comment by chrisdavidmills** [comment]
> I love this, thanks @chrisdavidmills - As a side note, I would love to be involved here as much as possible.

Yay, cheers @schalkneethling ! By "be involved", you mean you'd like to review/provide feedback on the RFCs that come in? We'd love to have your feedback.

**Comment by schalkneethling** [comment]
> > I love this, thanks @chrisdavidmills - As a side note, I would love to be involved here as much as possible.
> 
> Yay, cheers @schalkneethling ! By "be involved", you mean you'd like to review/provide feedback on the RFCs that come in? We'd love to have your feedback.

That as well as the work on writing content regarding a11y and ARIA

**Comment by chrisdavidmills** [comment]
> > > I love this, thanks @chrisdavidmills - As a side note, I would love to be involved here as much as possible.
> > 
> > 
> > Yay, cheers @schalkneethling ! By "be involved", you mean you'd like to review/provide feedback on the RFCs that come in? We'd love to have your feedback.
> 
> That as well as the work on writing content regarding a11y and ARIA

Wonderful, absolutely

**Comment by dontcallmedom** [comment]
coming a bit after the battle, but there is a W3C Community Group very actively working on infrastructure to test and keep track of which roles are implemented how in what browser/AT: https://www.w3.org/community/aria-at/

See also https://github.com/w3c/aria-at - I think it would be great to engage with the CG to see how the two efforts can benefit from one another.

**Pull request merged**
