### PR TITLE
Rewrite/reduce Event reference

### LINKED ISSUE #1662: https://developer.mozilla.org/en-US/docs/Web/Events/checking  404
https://developer.mozilla.org/en-US/docs/Web/Events/checking
This page 404

### PR DESCRIPTION
**Pull request by hamishwillee**
This doc had numerous broken links, use of a bad macro, and relatively old content (mostly because it predated putting event reference under the associated object).

Given that events are documented under the associated object it does not make sense to duplicate that - or to maintain such duplication. What this does is document and link to the main objects (in the section that documents the events). It does provide some links to the subsections of some of the docs to give a flavour of some of the kinds of events.

This does not attempt to be exhaustive, but it has the main documented objects and should be easy to maintain going forward.
This should be much easier to maintain. 

@chrisdavidmills I am happy enough with this, but one other option is to put this as a sub-section of the Event reference doc itself: https://developer.mozilla.org/en-US/docs/Web/API/Event

Fixes #1662.

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
This is looking much better, thanks so much Hamish. This page has needed a facelift for so long!

There are a few bits that I'd like to see updated here:

1. I'd like some kind of explanation up the top that all the event object classes that represent events are based on the Event class.
2. Next, I'd like to see a table, I think, rather than the description list you've got here. As it currently stands, it is possibly a bit confusing as to what the things in the description list are. Instead I'd probably like to see a three-column table - first column "Object" (e.g. Document), second column "Associated event object(s)" (e.g. Event, MouseEvent, sometimes there are more than one), third column "Common events and event types" (list a few of the most common events, and/or links to the event type lists that you've current got here). If this makes things too complex for a single table, we could always have a few tables under different headings in this page, e.g. "Common DOM Events", "Database events", "Media events", "Form Events"...
3. I know we can always iterate on this, but I'm getting the feeling you are missing a fair few, like service worker-related events, web speech api events, etc. I'm not sure if you intended this to be exhaustive or somply list the most common stuff. It is already a whole tonne better than it was.
4. I'd like to see the events listed in alphabetical order. Seems a bit random at the moment.
5. I've delete "Depending on the browser/environment there may also be events for popups, tab changes, batteries, calls, sensors, smartcards, SMS messages, and many others.", as it isn't really very helpful. Maybe say something like "This page lists the most common events you'll come across on the web. If you are searching for an event that isn't listed here, try searching for its name, topic area, or associated specification on the rest of MDN."

**Comment by hamishwillee** [comment]
Hi @chrisdavidmills 

FWIW to do this "right" you would tag each of the events in the metadata and dynamically generate the list. Doing it manually is always going to and be unreliable.

You're still thinking of this as a "detailed events reference", while I have been thinking of this as an index into the objects that contain the documentation. So it is this way "by design". I preferred it because now I'm not sure what should/should not be documented here - everything? nothing? 

Anyway, I've gone part way to what you asked for so we can evaluate. 
- First column is now ALL the event firing classes I could find by searching for the heading structure. Not alphabetic yet since you might want to eliminate some.
- Second one is the events themselves - which I don't find useful. 
- Third is links to sub headings in the object event docs where they exist or XXX placheholder for those that don't. 

image

To iterate this we need to think about what should be in that last column. I just don't know what is important vs what is not important. Is it that you want a reference, or is my idea of an object index reasonable.

If you say you really want a reference then that's at least a week of work + RSI. I think I'd want to add metadata to the individual events and script this.

**Comment by chrisdavidmills** [comment]
I think we agree with each other here. I believe this is worth spending some time on, as looking at the GA figure for this page, it is pretty high traffic (43K monthly views, even in its current crappy state).

But it is hard to decide what is best to do on it. I wasn't really thinking of an exhaustive events reference, more a reference for the most common event types that people will want to find 80% fo the time?

Perhaps you could create something that largely looks likw what we want, but keep it manual for now, and then slightly later on we can ask the engineers for help with creating an automated system that grabs all the event pages and does the same thing, but properly. I know you could do it properly right now, with a KumaScript macro, but we are getting rid of KS in the near future, so I'd rather you not waste your time on that.

Looking at the table we now have, I'd say this is worse than what you originally had, but it was a useful exercise to consider this form. My updated thoughts after seeing this version:

1. The giant table is a bit of a mess. We definitely need multiple tables, split up by some kind of categorization system, like "Common DOM events", "Database", "Audio/Video", etc.
2. I agree that listing the event objects is pointless. You've got the relevant event object listed on every event page anyway, so people can find them there.
3. People will probably start their search by functon (e.g. "I want to know about animation events") than object even is fired on ("I want to know about events fired on Window or Document"). So how about we start with Event type, in which we make up something to describe the event, then a longer description, and then finally links to the places where those events are documented.

so the table could end up looking something more like this in each case:

| Event type      | Description | Documentation
| ----------- | ----------- | -----------
| Animation      | Events related to the [Web Animation API](), used to respond to changes in animation status (e.g. when an animation starts or ends)       | [Animation events fired on Document](), [Animation events fired on Window]()

**Comment by hamishwillee** [comment]
@chrisdavidmills I think we are aligned too. The missing bit of info for me being that this page is used a lot, even if not useful. 

Not sure how this would look dynamically. I can tell you that a flat list of all the events in the [docs looks like this](https://gist.github.com/hamishwillee/d140a84e104c30b7d2214c5f5b087abf) - generated by parsing all docs with filename _event and parsing out the title. It would be easy to add that at the end as a linkable version if you thought it useful?

In the mean time, your proposal sounds excellent. I will see what I can do .

**Comment by chrisdavidmills** [comment]
Yay, I like where this is going! Filling in all the details for all the events looks like it will be painful, but we could perhaps share the work and get a few bits done each day, until the list is worked through.

**Comment by hamishwillee** [comment]
@chrisdavidmills FYI worked on this a bit today too. The main "event index" (ie bit we already discussed) getting there. The grouping left that I **might** still include in this are:connection, focus, gamepad, history, manifest, messaging, print, promise rejection, WebVR, composition

Upshot, hopefully when I work Friday we can consider looking at publishing.

In addition, I auto-created this index at the end. This is any event that has its own event doc and is named according to site conventions. I'd love to add a comment next to each but since this is dynamically generated that would require we had sensible markup of seo summary (that not used for events :-( )

image

**Comment by hamishwillee** [comment]
@chrisdavidmills This is now ready for you to review. I suggest perhaps you look at it rendered.

There is a miscellaneous row where I wasn't sure whether it was worth creating individual rows. Can you check that and let me know if perhaps some belong in other obvious places?

I also had to create and events section to link to in SVGGraphical ...

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
This is looking really good mate. I reckon it could be improved as we go along, but as it stands it is a useful organization of events, and a vast improvement on what we had before. I'm very happy with the structure as it stands.

Couple of grammar nits/typos in the front matter:

* "functions used to get additional" > "functions to provide additional"?
* "Events > Interfaces based on Event" > "Event > Interfaces based on Event."

It looks a bit weird how the center column of the table has all its content aligned towards the top of the cells, whereas in the other two columns the content is vertically centered. This is because the content is contained in paragraphs in the center column, but not in the others. Paragraphs everywhere would be good, to make it consistent.

Media — I reckon you should list some more obvious Media APIs; the ones that immediately sprint to mind are:

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Video_and_audio_APIs#the_htmlmediaelement_api
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API
And WebRTC of course, but you've given that a separate table row, which I think is OK.

Other bits:

* "selection etc." > "selection, etc."
* "hardware agnostic" > "hardware-agnostic"
* "Network Infomrmation API" > "Network Information API)"
* Punctuation needs fixing on "SpeechSynthesisUtterance, ."
* "Events related to the Web Workers API, Broadcast Channel API and Channel Messaging API." > needs oxford comma
* There is no mention of any service worker-related events, and I'm sure there's loads in there. I wonder if we never got around to updating those pages to collect the events together?

Thoughts on miscellaneous events:

* You could group together AbortSignal and XMLHttpRequest into a single group along the lines of "Asynchronous data fetching".
* EventSource is to do with Server-sent events, so you could maybe made a row for that? It's quite an important thing that people will want to know about.
* The others could be lumped into some kind of "HTML element content display management" category? They all relate to the toggling, opening, or closing of some kind of spangly display element, or changing the textual content. I'd get rid of Element/details, as that's exactly the same event as covered at HTMLDetailsElement. We should probably delete that part of the `<details>` element page, as I don't think any other HTML element page has that section.

The event listing is useful, but it'd probably looks better as a description list rather than paragraphs and separate unordered lists, e.g. turn 

```
<p>AbortSignal</p>
<ul>
  <li><a href="/en-US/docs/Web/API/AbortSignal/abort_event">abort event</a></li>
</ul>
```

into 

```
<dl>
  <dt>AbortSignal</dt>
  <dd>
    <ul>
      <li><a href="/en-US/docs/Web/API/AbortSignal/abort_event">abort event</a></li>
    </ul>
  </dd>
...
```

Also, link all the interface names to their reference pages. Also, code terms should all be in `<code>`

Sorry for the long comment that results in a lot more work for you. Don't hate me too much ;-)

**Comment by hamishwillee** [comment]
> It looks a bit weird how the center column of the table has all its content aligned towards the top of the cells, whereas in the other two columns the content is vertically centered. This is because the content is contained in paragraphs in the center column, but not in the others. Paragraphs everywhere would be good, to make it consistent.

So this is actually the layout of a standard table - it's just that we rarely have multiple columns where the center one is fattest. I agree and have fixed it with an inline `<style>` block.

**Comment by hamishwillee** [comment]
@chrisdavidmills Thanks for all the advice. I "think" I have integrated all of it, though there are a few "requests for clarification" above https://github.com/mdn/content/pull/2094#issuecomment-783877820

Getting there!

**Comment by chrisdavidmills** [comment]
> Already did that. What am I missing? I have added Web Audio API to the center column BUT that does not have an events section, which is why it doesn't link properly.

Ah yes, sorry, missed that!

> Service worker events covered as part of workers section. Did you miss this, or am I missing something?

Ah yes, I did miss that! I did wonder whether the middle column could do with a link to the https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API page? 

I think it is OK if these links don't link directly to an events section. Those are usually on interface landing pages, not overall API landing pages.

**Review by chrisdavidmills — APPROVED** [review]
OK, this is looking really good, nice work @hamishwillee . I think I'm going to merge this now, as the only remaining comment in my previous comment box is really minor and I'm not all that fussed about it.

Another small thing that might be nice if you get the time is to update the contribution docs to mention this page and tell people that are writing any events documentation to add them here.

**Comment by hamishwillee** [comment]
Thanks @chrisdavidmills

Good suggestions. Done in https://github.com/mdn/content/pull/2633

**Pull request merged**
