### PR TITLE
Enhance object() special behavior

### PR DESCRIPTION
**Pull request by Ahmed-Hakeem**

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
Hi, this section is broken into two scenarios:

1. When `Object()` itself is called or constructed
2. When `Object()` is constructed with `new.target !== Object`

These two cases are logically disjoint and complementary, while after the revision they no longer are.

**Comment by Ahmed-Hakeem** [comment]
Maybe I didn't get it ..... but at the end of the day constructing object() with  new.target!= Object is a construct or call to Object() and run the same logic .... I beg to differ ...I can't see any separation between 2 cases ...and the specs just specify the Object() implementation steps as: when the newTarget is not undefined and not the Object itself then it will create an empty object with the new.target.prototype as undefined 
...other than that it will do the behavior we mentioned just before this hint

**Comment by Ahmed-Hakeem** [comment]
We can even make this case as number 1 thing in the steps we mentioned before this step

**Comment by Josh-Cena** [comment]
There are three cases:

1. `Object()` is called
2. `Object()` is constructed, `new.target === Object`
3. `Object()` is constructed, `new.target !== Object`

Cases 1 and 2 both perform type coercion. Only case 3 always creates a new empty object. After your change, it sounds like case 1 also creates an empty object, which is not the case (it creates an empty object when passed `null` or `undefined`, but that's just part of how type coercion works)

**Comment by Josh-Cena** [comment]
I think the misunderstanding is here:

"`new.target === undefined`" is exactly equivalent to "`Object()` is called". There isn't a case where you can "construct `Object()` while setting `new.target` to a non-constructor; not even with `Reflect.construct()`.

**Comment by Ahmed-Hakeem** [comment]
> There are three cases:
> 
> 1. `Object()` is called
> 2. `Object()` is constructed, `new.target === Object`
> 3. `Object()` is constructed, `new.target !== Object`
> 
> Cases 1 and 2 both perform type coercion. Only case 3 always creates a new empty object. After your change, it sounds like case 1 also creates an empty object, which is not the case (it creates an empty object when passed `null` or `undefined`, but that's just part of how type coercion works)

I can't think of a case that Object() can be constructed and at the same time with new.target equals undefined .... but according to specs this can happen so they put a condition like (new.target !== Object && new.target == undefined ) .... so that's why I added it here to match the specs

**Comment by Josh-Cena** [comment]
The way to detect whether a function is called or constructed is to check `new.target === undefined`. This is mentioned in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target

**Comment by Ahmed-Hakeem** [comment]
> I think the misunderstanding is here:
> 
> "`new.target === undefined`" is exactly equivalent to "`Object()` is called". There isn't a case where you can "construct `Object()` while setting `new.target` to a non-constructor; not even with `Reflect.construct()`.

Yeah me neither can't get anything do this

So either this condition in the specs is redundant 
Or our knowledge of the language didn't catch this part 

But as you can see they are putting the condition that it's not undefined beside not equal Object
image

**Comment by Josh-Cena** [comment]
The spec can't say "when `Object` is calle". The way to know whether an object is called is to test `new.target === undefined`z

**Comment by Ahmed-Hakeem** [comment]
> The spec can't say "when `Object` is called"—that's not a well-defined term. The way to know whether an object is called is to test `new.target === undefined`.

You mean they meant by "not undefined" that it is not constructed .... yeah, maybe this is the most reasonable thing we can end with ... if this is the case appreciate if we can clarify this to readers .... I know that you mentioned 'constructed' but I think it's a good idea to add more clarification to this case ..... also aside from this mentioning 'empty object' is adding value to the reader.

**Comment by Josh-Cena** [comment]
`new.target === undefined` is a more indirect way of saying something is called instead of constructed. The only reason the spec uses the former is to be well-defined and rigorous, but it's an irrelevant technical detail to readers.

**Comment by Ahmed-Hakeem** [comment]
Got it.... how about this: 'when Object() is constructed (new.target == undefined).....'

**Comment by Josh-Cena** [comment]
Ideally yes, but I don't think this is worth an individual PR. You are explaining a more obvious concept with a less obvious one.

**Comment by Ahmed-Hakeem** [comment]
> Ideally yes, but I don't think this is worth an individual PR. You are explaining a more obvious concept with a less obvious one.

Yeah, let's leave it ....I'm not even 100% sure about this rule .... still scratching my head to find anything do this case = I mean construct Object with newTarget as undefined ... but your saying regarding their meaning makes sense to me.

Thanks, dude for your discussion :) ...appreciate it!

**Comment by Ahmed-Hakeem** [comment]
"it checks whether NewTarget is undefined, which indicates a [[Call]] invocation."

from the specs : ) 

now confirmed ..... feel free to add this one in one of your PRs or even reopen this one:

> Got it.... how about this: 'when Object() is constructed (new.target == undefined) but.....'

**Pull request closed without merging**
