### PR TITLE
Redirect Document DnD events to HTMLElement

### PR DESCRIPTION
**Pull request by Elchi3**
@foolip said in https://github.com/mdn/browser-compat-data/pull/16556#pullrequestreview-1027520573:

> Rather than add new entries, I think the drag* and drop events on `Document` should be moved to `HTMLElement`, since the target of these events are elements with the `draggable` attribute. In my testing it seems like it has to be HTML elements, not arbitrary elements.

@queengooborg opened a content PR for `GlobalEventHandler` redirects: https://github.com/mdn/content/pull/18286 but no redirects from `Document` to `HTMLElement` happened.

Meanwhile the BCD already removed the compat data for `Document` DnD events: https://github.com/mdn/browser-compat-data/pull/16556. That's why these pages are now displayed without compat tables and spec sections.

So, this PR removes and redirects `Document` DnD events to `HTMLELement`.

I hope this makes sense in light of the event pages reorg.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
This makes sense to me.

**Review by teoli2003 — CHANGES_REQUESTED** [review]
There are extra `/`s in the redirect file. This is because slugs don't start with `/` and `yarn content delete --redirect` don't prevent adding an extra `/`.

**Comment by Josh-Cena** [comment]
I can never remember which commands expect full URLs and which expect page slugs. Yari ought to make some effort to normalize this.

**Comment by Elchi3** [comment]
> I can never remember which commands expect full URLs and which expect page slugs. Yari ought to make some effort to validate and/or normalize this.

Exactly this!! Plus `yarn content validate-redirects` is not enough, apparently CI does `yarn content validate-redirects --strict`, so I wonder why `--strict` isn't the default.

**Review by teoli2003 — APPROVED** [review]

**Pull request merged**
