### PR TITLE
Add underscores around slug of Object/proto

### PR DESCRIPTION
**Pull request by Josh-Cena**
### Description

This makes the slug less ambiguous about what it's referring to. Also makes it more consistent with `__defineGetter__` and friends.

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
Thanks! 👍 

Needs a BCD update: https://github.com/mdn/browser-compat-data/blob/main/javascript/builtins/Object.json#L1426

**Comment by caugner** [comment]
@Josh-Cena Unfortunately this change had an unexpected side-effect on yari, breaking its [ESM build](https://github.com/mdn/yari/actions/runs/3660226383/jobs/6187120275#step:7:102) (even though the error message is cryptic).

Would it be okay for you to revert this change while we work on a fix in yari? 🙏

**Comment by caugner** [comment]
@queengooborg and I looked into it and didn't find an easy fix, because the build fails with a random-ish error message before anything happens. I have seldomly seen something like this.

**Comment by Josh-Cena** [comment]
It looks like `__proto__` injection—does Yari use a plain object to store key-value pairs of slug segments to document trees? It could cause the `__proto__` key to become enumerable.

**Comment by Josh-Cena** [comment]
@caugner Let me know if help is needed; I can checkout that branch and see for myself. It does look cryptic to me from the outside.

**Comment by queengooborg** [comment]
Thanks @Josh-Cena -- we created a channel in the OWD Slack and invited you!

**Pull request merged**
