### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by fn-ix**
Line 355, should be _successor_ instead of _ancestor_; `<html>` is already the highest-level “ancestor”, so any elements with `position: absolute` will either be positioned relative to it or to any positioned _descendant/successor_ elements.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
I think here "its" is referring to the element you are positioning, not `html`.

So it wants to say: the element can be positioned relative to its closest positioned ancestor, as we say in https://developer.mozilla.org/en-US/docs/Web/CSS/position#absolute.

"its" is ambiguous here though, and we should fix that. Perhaps we could take/adapt the text from https://developer.mozilla.org/en-US/docs/Web/CSS/position#absolute ?

**Comment by fn-ix** [comment]
Sounds good to me.

> From there, you can fix it to a position relative to the edges of its closest positioned ancestor (which becomes `<html>` if no other ancestors are positioned).

Maybe the part in the parenthesis is excessive/inelegant?

**Comment by wbamberg** [comment]
> Sounds good to me.
> 
> > From there, you can fix it to a position relative to the edges of its closest positioned ancestor (which becomes `<html>` if no other ancestors are positioned).
> 
> Maybe the part in the parenthesis is excessive/inelegant?

I think this is perfect.

**Review by wbamberg — APPROVED** [review]
Thank you for the fix, @fn-ix , and welcome to the MDN contributor community!

**Pull request merged**
