### PR TITLE
Iss2147

### PR DESCRIPTION
**Pull request by CreaTorAlexander**

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
We've definitely fixed some of this stuff already, in the other PR I reviewed. Can you review the stuff that is handled elsewhere, and provide a description of what is left in the PR decription, along with what issue it fixes?

**Comment by CreaTorAlexander** [comment]
I think #2147 is left https://github.com/mdn/content/pull/2149/commits/5bc1887c6e17ee560fd145036e3f617923df8e8b
The two other commits were already merged. But I don't understand I did seperate branches so why are these commits also included in this PR?

**Comment by Ryuno-Ki** [comment]
Could it be that you branched off from a previous PR you created?
Then, the history would contain that commit.

Instead, checkout the main branch and then create a new branch to separate the commits from each other.

**Comment by CreaTorAlexander** [comment]
Yes, my bad I didn't switched back to the main and created it out of the before created branch. Thanks for the advice.

**Comment by Ryuno-Ki** [comment]
Knowledge++ :)
Is there some place we should improve our documentation to make it easier for new contributors?

**Comment by CreaTorAlexander** [comment]
Definetly learning GitHub by doing :)
Hmm, one thing I am not sure about is, I update files with adding one word or removing one word. Should I do for all of them a seperate branch with a seperate commit or can I summarize them together?

**Comment by Ryuno-Ki** [comment]
Hm, the only thing I could imagine is https://github.com/mdn/content/pull/2151#discussion_r571696903 - perhaps in conjunction with a reference to the ticket ID.

That being said, we have some PRs, that do bulk changes.
So if your edits have some common thread, you could follow along this pathway.

**Pull request closed without merging**
