### PR TITLE
Remove multiple new lines

### PR DESCRIPTION
**Pull request by bershanskiy**
Allow no more than one empty line to make content look neater. This PR does not have any real content changes -- just removal of empty lines.

I realize that this PR might be too large to review, and I can break it up into smaller pieces, if needed.

### CODE REVIEW

**Comment by bershanskiy** [comment]
Apparently this PR is too big for `get-diff-action`...

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
> Apparently this PR is too big for `get-diff-action`...

Yeah, to merge, it’s gonna need an admin override regardless

**Review by chrisdavidmills — APPROVED** [review]
Thanks for the cleanup @bershanskiy .

**Comment by chrisdavidmills** [comment]
@bershanskiy I'll merge it once you've cleaned up the merge conflicts.

**Review by chrisdavidmills — APPROVED** [review]

**Comment by bershanskiy** [comment]
@chrisdavidmills Done!

**Comment by chrisdavidmills** [comment]
@bershanskiy perfect, thanks.

**Pull request merged**
