### PR TITLE
fix: Closed and re-opened em and strong tags

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Review by chrisdavidmills — APPROVED** [review]
Some nice fixes here; thanks @nschonni !

**Comment by chrisdavidmills** [comment]
Ooop, merge conflicts.

**Comment by nschonni** [comment]
@chrisdavidmills gave it a rebase

**Comment by chrisdavidmills** [comment]
Perfect, thanks @nschonni !

**Pull request merged**
