### PR TITLE
Added additional information in the section about combining pseudo el…

### PR DESCRIPTION
**Pull request by KeshavSaraf**
…ements and pseudo classes

The already provided description on the website gives details about cascading pseudo element with pseudo class. However, no information about cascading pseudo class with pseudo element has been provided. I have added just that piece of information.

### CODE REVIEW

**Review by chrisdavidmills — COMMENTED** [review]
Hi @KeshavSaraf, and thank you for your interest in contributing to MDN.

So, I think your intention is good here, but I do have some concerns about the content you are suggesting to add:

1. The example is different to the one above it with no warning or lead up, which I think could be confusing/off-putting to the reader.
2. The suggested note is discussing quite an advanced concept which, while I think it potentially has value, I am concerned that it may be a bit advanced to a beginner audience (which is who the `/Learn` articles are aimed at). Do they really need this information?
3. On reading the part about the limited support for the `::first-line:hover` version, I tried it, and saw that it didn't seem to work in Firefox Nightly, Chrome Canary, or Safari release. Where does it actually work?

Based on these concerns, I wonder whether it'd be better to just not include this note. Or maybe just swap it out for a more general note that talks about the order of the pseudos mattering, saying that generally you should put the class first and the element second, as the other way round tends to not work?

What do you think?

**Comment by KeshavSaraf** [comment]
I see your concerns. The following is my attempt to address those:
My main aim is that readers should be aware that those two are two different selectors and might be a probable cause of styles not applying as the user wants due to incorrect styles. Also, `::first-line:hover` is in itself an example of combining pseudo-classes with pseudo-elements, thereby helping the reader to see another example of how a combination of pseudo-class and a pseudo-element can be interpreted.

**Addressing the 3 main issues**
1. Definitely, giving an example improves clarity. However, as pointed out by you in point no. 3, `::first-line:hover` is actually an unimplemented specification. Currently, I don't know of any browser that supports it. However, it is a valid [CSS specification](https://www.w3.org/TR/selectors-4/#pseudo-element-states). Providing an example in the interactive editor is not possible at the moment (due to the lack of its implementation). However, there are other ways to achieve the behavior, so, if you wish, I can add an example whose behavior matches with that of `::first-line:hover`. However, in my opinion, providing an example that hasn't been implemented yet would be more confusing to the readers, especially beginners and may also mislead them into believing that such specifications have been implemented.

2. I do believe that `::first-line:hover` can be included as all the knowledge required to interpret that has been provided by the docs just prior to the note. So, this should be still pretty basic to the readers. Also, if this still seems like an advanced topic, I will attach a line at the end, saying that if the reader doesn't understand `::first-line:hover`, they needn't worry about it much and that further knowledge will help them to understand what the note says.  And as they progress, they will get a way around to achieve this behavior if they ever require it.

In addition, the note is required, especially for completeness. Anyone who tries to experiment/play with CSS, would most probably, in my opinion try attaching a pseudo-class after a pseudo-element and then try to figure why that isn't working. The reader might falsely conclude that the specification doesn't provide a way to select a state of a pseudo-element. Or he/she might resort to searching the web which might redirect them to the official W3C website, which is in fact much more complex. This might make the reader "waste" their time in experimenting with a futile and advanced topic rather than "investing" it in more productive learning actions.

3. As mentioned above, Currently, I don't know of any browser that supports this.

**Conclusion**
To conclude, I still believe the note should be added, not for the sake of increasing reader's knowledge but rather to clarify some doubts that might pop-up in the reader's mind. Also, there are other advantages of this note, it gives the reader another example of interpreting a selector combining pseudo-classes and pseudo-elements.  

Please share your views.

**Comment by chrisdavidmills** [comment]
@KeshavSaraf after this discussion, I still feel like the current note confuses more than it helps. It is helpful to inform the beginner audience that the order of the pseudos matters, and having them in different orders creates different selectors, some of which may not word or make sense. I also think it would be useful to tell them that generally you should put the class first and the element second, as the other way round tends to not work, although in some cases it may do in the future.

At this point you could perhaps say that `::first-line:hover` is a good example — it is currently unsupported but is technically valid CSS. `:hover::first-line` on the other hand is supported. Then you could tell them to go try it in the above live code example.

But I think it needs this kind of build-up, and we need to be very explicit that it is currently unsupported. I also don't think it is helpful to tell them to try it in the CSS validator to see that it is valid CSS — this will make the beginner audience go "hrm, well what use is that then, if I can't actually use it anywhere?".

**Comment by KeshavSaraf** [comment]
I am going to close this pull request. Thank you for taking out time to review this.

**Pull request closed without merging**
