### PR TITLE
[Markdown] [Glossary] Convert Glossary to markdown - DO NOT SQUASH MERGE

### PR DESCRIPTION
**Pull request by wbamberg**
Previously filed as https://github.com/mdn/content/pull/9384 which rotted.

The preparation PR for this: https://github.com/mdn/content/pull/9361.

The conversion report:

```
# Report from 10/6/2021, 11:14:50 AM
## All unhandled elements
- sub (8)
- section#Quick_links (1)
## Details per Document
### [/en-US/docs/Glossary/Bézier_curve](https://developer.mozilla.org/en-US/docs/Glossary/Bézier_curve)
### Missing conversion rules
- sub (13:173)
- sub (13:188)
- sub (13:203)
- sub (13:222)
- sub (15:64)
- sub (15:81)
- sub (15:114)
- sub (15:131)
### [/en-US/docs/Glossary](https://developer.mozilla.org/en-US/docs/Glossary)
### Missing conversion rules
- section#Quick_links (28:1)
```

(unconverted elements were discussed in https://github.com/mdn/content/pull/9361).

### CODE REVIEW

**Comment by wbamberg** [comment]
To coordinate reviews I've created https://docs.google.com/spreadsheets/d/1wefKa0rTmHLZAg0GVZ69aNQL_h5eatUYBX0DmeE9MqE/edit?usp=sharing

As before, the purpose of this is just to ensure different people review different pages.

**Comment by hamishwillee** [comment]
@wbamberg I looked at a huge number of these (marked up some in the tracking, but looked at many more). There are a couple of minor things but overall IMO this is good to go.

**Comment by wbamberg** [comment]
> @wbamberg I looked at a huge number of these (marked up some in the tracking, but looked at many more). There are a couple of minor things but overall IMO this is good to go.

Thanks so much for looking Hamish! I pushed fixes for the issues you found.

**Review by hamishwillee — APPROVED** [review]
Good to go

**Pull request merged**
