### PR TITLE
Add links to some `core-js` polyfills

### PR DESCRIPTION
**Pull request by zloirock**

### CODE REVIEW

**Comment by zloirock** [comment]
@Elchi3 I didn't see this thread, but I saw some related. I agree that MDN should not contain polyfills directly.

I already had problems because of incorrect / incomplete MDN polyfills some times, for example, https://github.com/zloirock/core-js/issues/588. In addition, I see some links to incorrect / incomplete polyfills on MDN pages. To fix it at least somehow, I made this PR.

`core-js` is the most popular polyfill of JS standard library and used on most websites ([even a naive detection shows ~59%](https://gist.github.com/zloirock/7331cec2a1ba74feae09e64584ec5d0e)) and contains proper polyfills.

I didn't remove polyfills code from MDN, I'm not sure that it's in the scope of this PR.

**Review by sideshowbarker — APPROVED** [review]

**Comment by Rumyra** [comment]
I agree with @sideshowbarker - I think these resources add value. If no one disagrees I will go ahead and merge this 👍

**Review by Elchi3 — APPROVED** [review]
Yes, I hope to continue the conversation on Polyfills but please merge this, @Rumyra 👍

**Comment by sideshowbarker** [comment]
Denis, thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

**Pull request merged**
