### PR TITLE
fix: trusted type api bogus example

### LINKED ISSUE #35241: Trusted Types example is bogus
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

```
const escapeHTMLPolicy = trustedTypes.createPolicy("myEscapePolicy", {
  createHTML: (string) => string.replace(/>/g, "<"),
});
```

Replacing `>` with `<` isn't helping and I guess is not what was intended.

### What did you expect to see?

Should replace the characters `<"'&` with `&lt;`, `&quot;`, `&apos;`, `&amp;` or so.

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/trusted_types_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/trusted_types_api/index.md
* Last commit: https://github.com/mdn/content/commit/736da094f1fe86aefb458e5505ad216789b0ba12
* Document last modified: 2024-05-13T06:03:17.000Z

</details>

### PR DESCRIPTION
**Pull request by gagan-bhullar-tech**
### Description

PR fixes #35241

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thanks for your PR! But this doesn't seem to be the fix suggested by @zcorpan in the [issue report](https://github.com/mdn/content/issues/35241):

> Should replace the characters <"'& with `&lt;`, `&quot;`, `&apos;`, `&amp;` or so.

**Comment by wbamberg** [comment]
Thank you!

I just saw that the following pages contain the same bogus example:
https://developer.mozilla.org/en-US/docs/Web/API/TrustedTypePolicyFactory
https://developer.mozilla.org/en-US/docs/Web/API/TrustedTypePolicyFactory/createPolicy
https://developer.mozilla.org/en-US/docs/Web/API/TrustedTypePolicy
https://developer.mozilla.org/en-US/docs/Web/API/TrustedTypePolicy/name
https://developer.mozilla.org/en-US/docs/Web/API/TrustedHTML/toJSON
https://developer.mozilla.org/en-US/docs/Web/API/TrustedHTML/toString

Note also that https://developer.mozilla.org/en-US/docs/Web/API/TrustedHTML only escapes `<`, which is also what the web.dev article does: https://web.dev/articles/trusted-types#trusted-type-policy. Would it be better just to do that in MDN's examples?

**Comment by Josh-Cena** [comment]
I think what exactly to replace depends on the context, and replacing angle brackets alone can close out most if not all injection vectors. For example you would want to escape quotes if the content is an attribute, but no need to do so if it's inserted as text content; sometimes it may even be helpful to _not_ escape ampersands to avoid certain footguns. Nevertheless it wouldn't hurt to give a complete example, at least once, and elsewhere we should at least not be bogus.

**Comment by gagan-bhullar-tech** [comment]
@wbamberg and @Josh-Cena updated PR. Please review.

**Review by wbamberg — APPROVED** [review]
👍 thank you @gagan-bhullar-tech !

**Pull request merged**
