### PR TITLE
Fix issue 13506: adjust example iframe height

### LINKED ISSUE #13506: Bug: Output examples obscured by small scrolling region
On the `<time>` and `<cite>` pages the output examples cannot be read without scrolling. In both cases the iframe height is set at 60px. 

I did not check every HTML page but looked around enough to note that it seems to be an isolated issue. Several I looked at had no iframe height (`<em>`, `<mark>`, `<s>`, `<span>`) and others had larger fixed height (`<strong>` is set at 80px and was visible without scrolling).

## Where did you spot the bug?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite

### Device
- Desktop

### Browser
- Chrome: (v99.0.4844.51)
- Firefox: (v97.0.1)

### Operating system
- Mac OS: (10.15.7)

## Screenshots
Example showing the result text for the HTML example is cut off and cannot be read

### PR DESCRIPTION
**Pull request by wbamberg**
Fixes https://github.com/mdn/content/issues/13506.

Adjusts the iframe height for some live samples. Also fixed a heading to use sentence case.

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by caugner** [comment]
@wbamberg I quickly checked the preview URLs above and I seem to still see the problem on the cite article (but not on the time article):

Screenshot_20220305-085845~2

**Comment by caugner** [comment]
@schalkneethling I really think we have a spacing issue here. Maybe spacing from `<p>` and iframe add up?

**Comment by schalkneethling** [comment]
> @schalkneethling I really think we have a spacing issue here. Maybe spacing from `<p>` and iframe add up?

That might very well be. The larger problem here is that we do not have control over what is inside these frames so, it is kinda the author’s responsibility to ensure they size of the iframe appropriately. I guess something that we changed as part of the redesign had an impact on these and that is why some of them needs a little bump.

Once we get underway on the project to make these be part of the content and not GitHub pages inside an `iframe` things will be much easier to maintain for both sides I believe.

Thank you for looking into this @caugner, much appreciated.

**Comment by caugner** [comment]
Do we already track this project [to make the examples part of the content] somewhere?

As an intermediate solution, we could have a ResizeObserver that sets the outer height of example iframes to their inner height. But I'm just thinking out loud here, enjoy your weekend, @schalkneethling!

**Comment by wbamberg** [comment]
> @wbamberg I quickly checked the preview URLs above and I seem to still see the problem on the cite article (but not on the time article):

Yes, this problem happens with the redesign but not the old design. When I run `yarn start` from MDN content I'm getting the old design, in which it looks OK. The new design seems to get extra padding, which makes the example overflow.

Old design:

Screen Shot 2022-03-05 at 9 25 00 AM

New design:

Screen Shot 2022-03-05 at 9 26 34 AM

But, many of these scrollbar issues were present before the redesign. I think they might be a regression caused by https://github.com/mdn/yari/issues/3260.

**Pull request merged**
