### PR TITLE
Revert newly added {{SeeCompatTable}} macros, part 1

### PR DESCRIPTION
**Pull request by OnkarRuikar**
Addresses https://github.com/mdn/content/pull/19911#pullrequestreview-1084154438

> We are gradually trying to remove the `{{SeeCompatTable}}` macros. 
> We have been removing this macro for some time now. Please change this throughout.

This reverts `{{SeeCompatTable}}` macros that were added in PR series https://github.com/mdn/content/pull/19185.

***
cc/ @jpmedley, @teoli2003

### CODE REVIEW

**Comment by teoli2003** [comment]
We are not removing `SeeCompatMacro` for the moment.

**Comment by hamishwillee** [comment]
Not without a replacement :-)

**Comment by OnkarRuikar** [comment]
> Not without a replacement :-)

It's basically the experimental header https://github.com/mdn/yari/blob/main/kumascript/macros/SeeCompatTable.ejs#L17

Do we want to rename it to `{{Experimental_Header}}` to avoid confusions?

**Comment by teoli2003** [comment]
Yes, of course, not without a replacement. (Long term, we want to get rid of the macros creating the banners and have synchronization with bcd happening automatically) [Sorry, I didn't give the whole explanation here]

We are much more used to its name (`SeeCompatTable`) than learning another one. It would add to the confusion.

(Thanks Onkar for your help, and sorry for the mess.)

**Comment by OnkarRuikar** [comment]
> (Thanks Onkar for your help, and sorry for the mess.)

No worries. I am excited to automatically run the script on every new `mdn/brower-compat-data` release.
I know these are hard to review PRs. Thanks for reviewing these!

Excluding the [part 40](https://github.com/mdn/content/pull/19958), there are only 60 files left in WebAPIs.

**Pull request closed without merging**
