### PR TITLE
chore(contrib): fix markdown guide wording

### PR DESCRIPTION
**Pull request by bsmth**
This is a follow-up after some rewording in #22299

### CODE REVIEW

**Comment by Josh-Cena** [comment]
@bsmth I have a proposal. On MDN, we see two styles of prose wrapping:

```md
Break by sentences.
Break by sentences.
```

```md
Break by paragraphs. Break by paragraphs.
```

Both sides have good reasons and I don't plan to convince anyone to switch their style. (I'm die-hard for the second one.) However, I suggest that, if we are editing a file that already uses one style (i.e. it doesn't line break in the middle of a sentence), further edits should respect the existing wrapping style. This way, we get better diff views and we can easily see where text is inserted/deleted in the middle of a sentence/paragraph.

Could that also go into the Markdown guide?

**Comment by Josh-Cena** [comment]
So my suggestion is two parts. First (and the important one, really) is that this PR is a bit hard to review because of the format changes 😉 Second is about adding this to the style guide. I don't know how strongly people feel about their prose wrapping style, but I think a good baseline is "don't unnecessarily add or remove line breaks". This helps with a clean diff and blame history. "Unnecessary" here is up for discretion: I personally change wrapping if:

- The previous paragraph is wrapped in the middle of a sentence, which isn't something anyone does nowadays.
- I'm rewriting the entire paragraph such that no sentence is the same as before.
- The paragraph has grown/shrunk so much that the previous wrapping is irrelevant.

Mostly, anything that you think may help the reviewers have a good time...

**Comment by wbamberg** [comment]
> Thanks for chiming in.
> 
> > Could that also go into the Markdown guide?
> 
> I think we can add it in this PR, indeed. It feels like a "should" case instead of a hard rule (preferable but not required), what do you think?

I agree with the idea but don't think this should be in the MD guide. This page is supposed to be just about markup features. But I'm not sure where it should go.

**Comment by bsmth** [comment]
We have a [make progress not noise](https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests#make_progress_not_noise) section in the PR submission guidelines which might be appropriate.

**Comment by OnkarRuikar** [comment]
It would be great if we mention that we use [markdownlint](https://github.com/DavidAnson/markdownlint) tool to find and fix issues in markdown text. And [the configuration](https://github.com/mdn/content/blob/main/.markdownlint-cli2.jsonc) that is being used. So new contributors will be more aware.

We’ll mention Prettier when the setup/changes are complete.

**Comment by wbamberg** [comment]
> It would be great if we mention that we use [markdownlint](https://github.com/DavidAnson/markdownlint) tool to find and fix issues in markdown text. And [the configuration](https://github.com/mdn/content/blob/main/.markdownlint-cli2.jsonc) that is being used. So new contributors will be more aware.
> 
> We’ll mention Prettier when the setup/changes are complete.

+1 Again, I'm not sure where.

**Review by wbamberg — APPROVED** [review]
👍 thank you @bsmth , this looks good to me!

**Pull request merged**
