### PR TITLE
Replace usage of alert() in mouseEvent

### PR DESCRIPTION
**Pull request by AnilSeervi**
Fixes portion of #7566

### CODE REVIEW

**Comment by teoli2003** [comment]
Are you sure the demo is working? I can't get `canceled` to be displayed in the output field.

**Comment by AnilSeervi** [comment]
> Are you sure the demo is working? I can't get `canceled` to be displayed in the output field.

May I know how `canceled` triggered in the previous example.

**Comment by teoli2003** [comment]
I don't know how the original example was working and I think that focusing on the cancelation doesn't bring much.

How about doing this:
```
<p><label><input type="checkbox" id="checkbox"> Checked</label></p>
<p><button id="button">Click me to send a MouseEvent to the checkbox</button></p>
```
and
```
function simulateClick() {
  //Get the element to click on
  let cb = document.getElementById("checkbox"); 
  
  //Create a synthetic click MouseEvent
  let evt = new MouseEvent("click", {
    bubbles: true,
    cancelable: true,
    view: window
  });

  // Send the event to the checkbox element
  cb.dispatchEvent(evt);
 
}

document.getElementById("button").addEventListener('click', simulateClick);
```

I think it demonstrate the feature better, and do not make use of `alert()`.

**Comment by AnilSeervi** [comment]
Yes, this looks okay.
Will Change to just dispatching the event.

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
