### PR TITLE
fix: Flaws in en-us/learn/accessibility/

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@peterbe this is an interesting failure, it looks like it pulled down a JPG, but decided on the check that it should be a PNG.
Probably something to spin out to a separate issue, but should it be fixing the extension if it downloads it and finds it's incorrect? Or is the test possibly bad?

**Review by chrisdavidmills — APPROVED** [review]
LGTM, but waiting on a merge for further discussion about the failing test.

**Comment by peterbe** [comment]
> @peterbe this is an interesting failure, it looks like it pulled down a JPG, but decided on the check that it should be a PNG.
> Probably something to spin out to a separate issue, but should it be fixing the extension if it downloads it and finds it's incorrect? Or is the test possibly bad?
> 
> ```
>  $ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) /home/runner/work/content/content/files/en-us/learn/accessibility/accessibility_troubleshooting/assessment-site-finished.png /home/runner/work/content/content/files/en-us/learn/accessibility/css_and_javascript/focus-highlight-chrome.png /home/runner/work/content/content/files/en-us/learn/accessibility/css_and_javascript/focus-highlight-firefox.png /home/runner/work/content/content/files/en-us/learn/accessibility/css_and_javascript/tabbed-info-box.png /home/runner/work/content/content/files/en-us/learn/accessibility/html/button-focused-unfocused.png /home/runner/work/content/content/files/en-us/learn/accessibility/html/title-attribute.png /home/runner/work/content/content/files/en-us/learn/accessibility/html/voiceover-formcontrols.png /home/runner/work/content/content/files/en-us/learn/accessibility/html/voiceover-good-form-label.png /home/runner/work/content/content/files/en-us/learn/accessibility/multimedia/closed-captions.png /home/runner/work/content/content/files/en-us/learn/accessibility/multimedia/native-controls-chrome.png /home/runner/work/content/content/files/en-us/learn/accessibility/multimedia/native-controls-firefox.png /home/runner/work/content/content/files/en-us/learn/accessibility/multimedia/subtitles_german.jpg /home/runner/work/content/content/files/en-us/learn/accessibility/multimedia/video-player-with-captions.png /home/runner/work/content/content/files/en-us/learn/accessibility/wai-aria_basics/landmarks-list.png
> Error: /home/runner/work/content/content/files/en-us/learn/accessibility/multimedia/subtitles_german.jpg is type 'image/png' but named extension is '.jpg'
> ```

Which page had a `.jpg` that then became `.png`?

**Comment by nschonni** [comment]
From https://github.com/mdn/content/blob/1c69e43eb32230b50bd2ac7d246a383ae926f0fd/files/en-us/learn/accessibility/multimedia/index.html#L277
Interstly, if you look at https://media.prod.mdn.mozit.cloud/attachments/2016/12/03/14442/da114167d08d97a954387f15bfffdf49/Subtitles_German.jpg "View Image Info" it also recognizes it as a PNG

But the downloader pulled it down and kept the "JPG" extension because that's what it declared

**Comment by peterbe** [comment]
If it actually is a PNG, it should become `Subtitles_German.png`. But does it use the right compression plugin is the question.

**Comment by nschonni** [comment]
I just manually renamed the extension and `src` to PNG and the build is happy again.
I'll leave it to you to decide if there should be an issue to fix the download handling to sniff the type or just leave it to be caught in the filecheck like today

**Comment by peterbe** [comment]
Oh I see. It does *not* become `subtitles_german.png` unless you manually fixed it. Yeah, it's because the file it writes is based on the URL, not based on the image. 
I don't think it's worth writing a bunch of new code for it.

**Comment by nschonni** [comment]
OK, I think this is OK to land then

**Pull request merged**
