### PR TITLE
Daily markdownlint

### PR DESCRIPTION
**Pull request by OnkarRuikar**

### CODE REVIEW

**Comment by OnkarRuikar** [comment]
@teoli2003 and @nschonni The PR check workflows didn't run for #20350 (first time contribution), so no linting happened and the lint error got through. How can we address this use case?

**Comment by nschonni** [comment]
Hard to tell what happened, but since the preview didn't happen I'm guessing the repo limits CI for first time contributors, so the task didn't run. Nothing that can be done for that if reviewers don't click to run the CI. https://github.com/mdn/content/pull/16036 is still pending to just automated the cleanup when those happen

**Review by Josh-Cena — APPROVED** [review]

**Comment by teoli2003** [comment]
Another thing we discussed is to make some tests (not Markdownlint) mandatory to merge a PR. This should have the consequence of preventing merging PRs without running the tests.

**Comment by Josh-Cena** [comment]
TBH I never found the restriction useful on any repo that's not using self-hosted runners.

**Pull request merged**
