### PR TITLE
fix: "forward" instead of "forth"

### PR DESCRIPTION
**Pull request by Cecil0o0**
### Description

noun "forth" lay emphasis on coming out from inside of entity, seems like "nothing" changed to "something". such as "She brought forth a new idea."

another usage is "The soldiers marched forth.", "forth" following with "marched" could be more common-to-see

noun "forward" may just means opposite of `back`, for example, assume move back means B to A, then move forward means A to B.

### Motivation

meeting noun "forth" makes me feel a bit strange for first eye on it. I think it could be more friendly for readers if use a more simple and appropriate noun~ How about it?

btw a joke, I had thought it's an ordinary number until I search that.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
["Back and forth"](https://dictionary.cambridge.org/us/dictionary/english/back-and-forth) is a common phrase while I've never heard anyone say "back and forward".

**Comment by Cecil0o0** [comment]
Hi friend @Josh-Cena, thanks for comment. As you say, I made a mistake . 

I’m trying to dive deep into web technologies, my plan is trying my best to walk through the content on mdn. Although this is a quite large job, but I decided to take effort for that, because it make sense for me!

During that, I read line by line and take effort to translate English content into Chinese for myself only for now.

Sorry if you feel bothered.

But I hope a chance to communicate with you, how to choose between these two phrases "backward and forward" and "back and forth"?

**Comment by Josh-Cena** [comment]
"Backward and forward" is quite long and I've also rarely (though perhaps not never) heard anyone use it. Again "back and forth" is probably the standard terminology for describing the motion here.

By the way, there are Chinese translations for most docs and you can contribute to https://github.com/mdn/translated-content if you find anything outdated or wrong.

**Comment by Cecil0o0** [comment]
@Josh-Cena I got helpful information from you which is enough for me, thanks a lot!

**Comment by hamishwillee** [comment]
FYI only @Josh-Cena as a native speaker you are right that "forth" is more natural. Not worth changing, but if I was to update this I'd have removed everything after the comma as redundant.

**Comment by Cecil0o0** [comment]
Hi @hamishwillee, Thanks for leaving a comment here!

**Comment by Cecil0o0** [comment]
Hi @hamishwillee, may I communicate with you about your comment?

I think this phrase "everything after the comma" represents this sentence "moving back and forth between the two topics", if I was right. I may have a bit different sense for that, HTML and CSS are two closely related topics of web technology, It could be a difficult go-through for people like me to read, study and understand these two in a not enough range of time, and during the range of time I actually do "moving back and forth", so I think it could be a **progressive** sentence to describe more detailed rather than "redundant"~

**Comment by hamishwillee** [comment]
@Cecil0o0 Let me put it to you this way - if that sentence wasn't there, what would you do differently? The answer is nothing - the only way to learn them at the same time is to go back and forth between the topics. Hence they information is pointless.
But that's just my take - not worth the time to discuss or change.

**Pull request closed without merging**
