### PR TITLE
FF129 Relnote: Navigator.vibrate() removed

### PR DESCRIPTION
**Pull request by hamishwillee**
FF129 stops exposing [`Navigator.vibrate()`]() because it has been broken for about 4 years, but the presence of the API is still used to feature detect for vibration - https://bugzilla.mozilla.org/show_bug.cgi?id=1653318. This is the release note.

Related docs work can be tracked in #34703

### CODE REVIEW

**Comment by hamishwillee** [comment]
@pepelsbey Any chance you could review your release PRs on a weekly basis? Would really help me clear my queue, and reduce pressure on the end of the release cycle if this could be done more regularly.

**Review by bsmth — APPROVED** [review]
I'm +1 on this, thank you!

**Review by pepelsbey — COMMENTED** [review]
I’d suggest moving this to the “Removals” section to separate it from added features. Also, the “has not worked some years” wording makes Firefox look too sloppy. Maybe we can be a bit more formal here.

**Comment by hamishwillee** [comment]
> I’d suggest moving this to the “Removals” section to separate it from added features. Also, the “has not worked some years” wording makes Firefox look too sloppy. Maybe we can be a bit more formal here.

Thanks @pepelsbey - removals is obviously the right place. I have stripped out the reasons why this was removed as they don't really matter.

**Pull request merged**
