### PR TITLE
Block level links

### LINKED ISSUE #23841: The image element is considered an inline element
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks

### What specific section or headline is this issue about?

Block level links

### What information was incorrect, unhelpful, or incomplete?

The Block level links section of the creating hyperlinks article describes images as block level elements. But images are considered inline elements.

### What did you expect to see?

I expected to see images described as inline elements.

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/creating_hyperlinks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/creating_hyperlinks/index.md
* Last commit: https://github.com/mdn/content/commit/d05f7e910c03168355f5ac96ee3724edd76573f4
* Document last modified: 2022-12-19T18:38:16.000Z

</details>

### PR DESCRIPTION
**Pull request by Adi-ty**
### Description
This PR fixes the issue #23841 

### Related issues and pull requests
Fixes #23841

### CODE REVIEW

**Comment by estelle** [comment]
I commented in the issue. I think the tutorial needs a little help, not the example ;)

I wrote:

> I think the tutorial has issues here. Images are indeed inline elements, so using an image as the example when the header reads "block level links" will confuse a lot of people.
>
> The example should likely be making the h1 company name a link to the home page, and then separate out that images can also be encased in a <a>, and show that as a separate example.

**Comment by Adi-ty** [comment]
Can you be more elaborate on how should I change the example should I change the example for the image to h1?

**Comment by estelle** [comment]
> Can you be more elaborate on how should I change the example should I change the example for the image to h1?

Breaking the section into two examples. One with an H1 showing the point of the heading of the section, and then another section about images in links, elaborating on the content of the kind of mislabeled section.

**Comment by Adi-ty** [comment]
> > Can you be more elaborate on how should I change the example should I change the example for the image to h1?
> 
> Breaking the section into two examples. One with an H1 showing the point of the heading of the section, and then another section about images in links, elaborating on the content of the kind of mislabeled section.

It will also require changing the content above the example accordingly?

**Comment by estelle** [comment]
> It will also require changing the content above the example accordingly?

yes

**Comment by Adi-ty** [comment]
@estelle do you mind telling what should the example say and how exactly this should be split up into two examples ?

**Comment by wbamberg** [comment]
Closing in favour of https://github.com/mdn/content/pull/24725. Sorry @Adi-ty , and we appreciate your work here, but it seems like this PR was not progressing. Please feel free to choose another issue to work on.

**Pull request closed without merging**
