### PR TITLE
Update constructable stylesheet examples

### PR DESCRIPTION
**Pull request by ebidel**
### Description

Constructible stylesheets are now mutable arrays.
The spec was updated in https://www.w3.org/TR/cssom-1/#extensions-to-the-document-or-shadow-root-interface.

### Motivation

Keep examples up to date and inline with spec changes.

### Additional details

Chrome 99 made the update some time ago: 
https://chromestatus.com/feature/5638996492288000
https://www.w3.org/TR/cssom-1/#extensions-to-the-document-or-shadow-root-interface
https://bugs.chromium.org/p/chromium/issues/detail?id=1236777

### CODE REVIEW

**Comment by wbamberg** [comment]
Thank you for this PR, @ebidel ! It looks fine but I had a couple of questions.

- Do you happen to know if Firefox supports this as well? I saw from https://chromestatus.com/feature/5638996492288000 that they are supportive of it but couldn't find a bug. Maybe @hamishwillee knows?
- I also guess from https://chromestatus.com/feature/5638996492288000 that Safari is not going to be shipping this?

If not all browsers implement this then I think we'll need a subfeature in the BCD for this feature describing which browsers support it, and also probably some words in the page explaining the issue, so the BCD subfeature is comprehensible to people. Does that make sense?

Something along the lines of:

> In earlier versions of the specification, `adoptedStyleSheets` was not mutable, so to add a stylesheet a developer would have to create a new array and assign it to the property:
>
> ```js
> shadow.adoptedStyleSheets = [...document.adoptedStyleSheets, extraSheet];
> ```

...and then we could call the BCD subfeature something like "adoptedStyleSheets is mutable".

Does that make sense?

Also though, I filed a PR to add a bit on constructable stylesheets to our "Using custom elements guide": https://github.com/mdn/content/pull/29484, and had some questions.

In this PR I said that using constructable stylesheets is more efficient than using `<style>` elements attached to the shadow DOM tree, which came from my reading of https://web.dev/constructable-stylesheets/ and https://github.com/WICG/construct-stylesheets/blob/gh-pages/explainer.md. But I'm not sure what guidance we should give to developers about when/whether to use one or ther other, or exactly what the tradeoffs are. If you had anything to add there I'd appreciate it. Thank you!

**Comment by ebidel** [comment]
I tested this bit of code in latest Safari (16.6) and FF (118) and it's working:
```
const sheet = new CSSStyleSheet();
sheet.replaceSync('body { color: red; }');
document.adoptedStyleSheets.push(sheet);
```

Not sure when the updates were made in each engine, but I'm not sure we need to keep the legacy behavior around. Looks like any modern browser supporting C Stylesheets supports the new behavior.

I think the guidance you have in that guide is good. The main reason to use CS over `<style>` is that it gives you a mechanism to easily share a large stylesheet across multiple shadow roots. For example, in the case of a web component, you could attach the entirety of bootstrap to a component's shadow root, get all the benefits of scoped css, and have that stylesheet reused across all instances of the component as well as any other components that adopt the CS. The browser will parse that stylesheet once. It's memory efficient. Also has interesting cases being a regular stylesheet object. If you have a handle to the sheet, calling `bootstrapSheet.disabled = true` would turn off the bootstrap styles for all components that use that boostrap stylesheet. Pretty cool and can't do that with a declared `<style>`.

`<style>` is great if you want to be declarative, have few styles, and dont have a use case to share those style rules across different components.

**Comment by hamishwillee** [comment]
> but I'm not sure we need to keep the legacy behavior around. Looks like any modern browser supporting C Stylesheets supports the new behavior.

We do, by policy for at least 2 years. @wbamberg suggestion above seems very sensible.

Added in 101 https://bugzilla.mozilla.org/show_bug.cgi?id=1766227

**Comment by ebidel** [comment]
@wbamberg mind taking over this PR and fostering it through with your suggested changes? n

**Comment by wbamberg** [comment]
> @wbamberg mind taking over this PR and fostering it through with your suggested changes? n

Sure thing. Let's just merge this one and do the rest in a follow-up.

**Review by wbamberg — APPROVED** [review]
👍 thank you @ebidel !

**Pull request merged**
