### PR TITLE
Ff128 Blob.bytes() supported

### PR DESCRIPTION
**Pull request by hamishwillee**
FF128 supports `Blob.bytes()` in https://bugzilla.mozilla.org/show_bug.cgi?id=1896475. This adds docs for it and a release note. 

Related docs work can be tracked in #33991

### CODE REVIEW

**Comment by bsmth** [comment]
BTW, Yari complains about `{{domxref("Uint8Array")}}` "(consider changing which macro you use)".

**Review by bsmth — APPROVED** [review]
Changes look good to me! Thanks, Hamish

**Comment by hamishwillee** [comment]
Thanks very much for the review @bsmth - I fixed up the typed array instances to jsxref (good catch) - link previously worked and I didn't look carefully at the errors :-0

**Comment by bsmth** [comment]
Thanks, Hamish!

**Pull request merged**
