### PR TITLE
PWA: refactor async function and remove eventlistener

### PR DESCRIPTION
**Pull request by stevenharderjr**
### Description
Refactored to allow removal of the event listener on the in-app install button.

### Motivation
Just seemed like a loose end.

### Additional details
N/A

### Related issues and pull requests

None that I'm aware of.

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
If we already hid the button, why do we need to do anything about the click handler? Is there any user experience difference here?

Also you need to update the code below too.

**Comment by stevenharderjr** [comment]
> If we already hid the button, why do we need to do anything about the click handler? Is there any user experience difference here?

UX difference? Of course not. It's just best practice to remove unused event listeners.

**Comment by wbamberg** [comment]
It's not an unused event listener though. The `beforeinstallprompt` event is fired again if you click the in-app install button then dismiss the resulting prompt dialog (which makes sense, because the user might change their mind about installing).

With the code in this PR, in that situation, the in-app install button will appear but not do anything.

**Comment by pepelsbey** [comment]
Given @wbamberg’s comment, I’m inclined to close the PR. Although removing event listeners is a good pattern in general, it might cause problems in this specific case. But thank you for caring about the code quality! And let us know if we’re missing something here.

**Comment by stevenharderjr** [comment]
I agree. Thank you.

**Pull request closed without merging**
