### PR TITLE
New Glossary Page Fixes #2682

### LINKED ISSUE #2682: Sorry, the page /en-US/docs/Glossary/device_pixels could not be found.
Hey,

I was reading about [CSS pixel](https://developer.mozilla.org/en-US/docs/Glossary/CSS_pixel) and one of the hyperlinks didn't work. The one is named in the title: https://developer.mozilla.org/en-US/docs/Glossary/device_pixels

You guys are doing amazing work!

Wishing best,
Rando

### PR DESCRIPTION
**Pull request by CreaTorAlexander**
My First Site, Added Glossary Site and fixed the link to device_pixel instead of device_pixels, Fixes #2682

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
This is a really good effort for your first new page, well done @CreaTorAlexander  !

There's a couple of small technical issues to highlight, which are really quick to fix:

1. First of all, in the page's front matter, you should update the `title` and `slug` to `Device pixel` and `Glossary/Device_pixel` respectively. On MDN, we always use "sentence case" for titles and slugs, i.e. first letter capitalized, everything else lower case. The only exception to this is when the title or slug contains a proper name or acronym, such as "Chris" or "CSS"
2. In the CSS pixel article, you changed the glossary link reference to the Device pixels article to {{Glossary("device pixel")}}. This makes the link work, but it is also grammatically incorrect, i.e. the link text should be "device pixels". You can fix this by adding a second parameter to the macro call with the preferred link text if it is different to the page title, i.e. the fix here would be {{Glossary("Device pixel","device pixels")}}

I'd also like to request some changes to the content itself:

1. I think you should include a link to the https://hacks.mozilla.org/2013/09/css-length-explained/ article in the device pixel article as well as the CSS pixel article.
2. I'd like you add a bit more content to the article to describe how a device pixel differs from a CSS pixel, but in the other direction to how it is explained on the CSS pixels article ;-) I think it is useful in both places.
3. I'd delete "(picture element)" — I'm not sure what relevant this has.

After you've made those changes, I'll give the finished content a quick copy edit before merging it, but the language is not too bad at all, so I don't anticipate it being a lot of changes.

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills Thanks for the feedback. I will update it later on :+1:

**Comment by CreaTorAlexander** [comment]
One question in the file structure *device_pixel* in lowercase is correct right?
Because the other files are all *lowercase*
For example digital_certificate, distributed_denial_of_service css_preprocessor and so on

**Comment by CreaTorAlexander** [comment]
I have updated it. For the CSS pixel content I used the definitions from the other glossar site. 
I have also linked the glossar site. Here I wasn't sure should I link every occurence or is linking one time fine?

**Comment by chrisdavidmills** [comment]
Apologies @CreaTorAlexander , I didn't see your edits until now! I've checked it over, and made some small copy edits. We can merge this now. 

Congratulations on your first new page being merged.

**Review by chrisdavidmills — APPROVED** [review]

**Pull request merged**
