### PR TITLE
Update a broken link

### PR DESCRIPTION
**Pull request by OnkarRuikar**

### CODE REVIEW

**Comment by teoli2003** [comment]
I would rather delete this page. What do you think @estelle?

**Comment by OnkarRuikar** [comment]
Should we remove suggestions of defunct google groups from mdn/content?
Most of them are full of spam messages now. And some haven't received any message in years.
***
Most of the products must have switch to GitHub/forums by now. So is mailing list mechanism still alive? Should we remove defunct mailing list suggestions from mdn/content?

**Comment by teoli2003** [comment]
Yes, we should remove them. (Though, please double-check if the thing is active, but most of the time, it won't)

**Review by estelle — APPROVED** [review]
thank you

**Pull request merged**
