### PR TITLE
Fix attribute in Autonomous custom elements example

### LINKED ISSUE #11568: Issue with "Using custom elements": minor error in code snippet
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

#### What information was incorrect, unhelpful, or incomplete?

img.src = this.hasAttribute('src') ? this.getAttribute('src') : 'img/default.png';

should be:

img.src = this.hasAttribute('img') ? this.getAttribute('img') : 'img/default.png';

#### Specific section or headline?

Autonomous custom elements

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/web_components/using_custom_elements/index.md
* Last commit: https://github.com/mdn/content/commit/e9e3d9c0ab23538f3bc6deea1f6bc20013a1e2eb
* Document last modified: 2021-12-23T19:24:11.000Z

</details>

### PR DESCRIPTION
**Pull request by pavanbellamkonda**
Fixes https://github.com/mdn/content/issues/11568

#### Summary
Changed attribute key from `src` to `img` as it is not matching with the example provided below
 ```
<popup-info img="img/alt.png" data-text="Your card validation code (CVC)
  is an extra security feature — it is the last 3 or 4 numbers on the
  back of your card."></popup-info>
```

#### Motivation

This PR helps reduce confusion because of the bug.
#### Supporting details

Changed 
```
img.src = this.hasAttribute('src') ? this.getAttribute('src') : 'img/default.png';
```
to
```
img.src = this.hasAttribute('img') ? this.getAttribute('img') : 'img/default.png';
```
as the html example uses `img` attribute below
```
<popup-info img="img/alt.png" data-text="Your card validation code (CVC)
  is an extra security feature — it is the last 3 or 4 numbers on the
  back of your card."></popup-info>
```
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
This change isn’t correct. The element being created by the example code is an `img` element for the `img/default.png` element, not a `popup-info` element with an `img` attribute for an `img/alt.png` image.

**Comment by pavanbellamkonda** [comment]
@sideshowbarker  The url for for image is passed thru the `img` attribute in `popup-info` element, and while accessing it (thru `this.hasAttribute` and `this.getAttribute` taking value from `popup-info`) , instead of using the same `img` attribute, `src` attribute is being used.

**Comment by pavanbellamkonda** [comment]
The source code in the live demo has the same code I suggested as well.

image
```
let imgUrl;
if(this.hasAttribute('img')) {
  imgUrl = this.getAttribute('img');
} else {
  imgUrl = 'img/default.png';
}

const img = document.createElement('img');
img.src = imgUrl;
icon.appendChild(img);
```

**Comment by sideshowbarker** [comment]
> @sideshowbarker The url for for image is passed thru the `img` attribute in `popup-info` element, and while accessing it (thru `this.hasAttribute` and `this.getAttribute` taking value from `popup-info`) , instead of using the same `img` attribute, `src` attribute is being used.

You’re right — sorry I missed that

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Pavan, thanks much for catching this and fixing it, and congrats on landing your first docs change here — welcome aboard 🎉

**Pull request merged**
