### PR TITLE
Replace unmaintained webauthn.org with alternatives

### PR DESCRIPTION
**Pull request by collinanderson**
#### Summary

Replace unmaintained webauthn.org with alternatives

#### Motivation

webauthn.org has been unmaintained for over 2 years.

#### Supporting details

https://github.com/webauthn-open-source/fido2-server-demo/issues/28

https://github.com/webauthn-open-source/fido2-lib/commit/9a9311ae9fb01dab4ca6026a8725c3a6a3e19350#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [✅] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by wbamberg** [comment]
Thank you for this! It certainly looks like we should remove this. @dontcallmedom , do you think the suggested replacement demo links are good? 

From a page structure point of view it would be nice to have these links under their own H2 "Demos" or something, rather than just hidden under the code sample.

**Comment by JamesCullum** [comment]
Thanks for the change - all looks good!
If you want to create a separate section for those, feel free to add it 👍

**Comment by dontcallmedom** [comment]
LGTM @wbamberg

**Review by wbamberg — APPROVED** [review]
👍 thanks @collinanderson and Dominique!

**Pull request merged**
