### PR TITLE
remove zero width spaces from folder names

### PR DESCRIPTION
**Pull request by peterbe**
Seems to be a junk file anyway.

### CODE REVIEW

**Comment by peterbe** [comment]
Perhaps this context helps: https://github.com/mdn/yari/pull/2172#issuecomment-747071073

**Comment by nschonni** [comment]
@peterbe figured out how to rename the file instead of deleting in https://github.com/mdn/content/pull/329

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Not merging this because it seems it’s superseded by #329, right?

**Comment by nschonni** [comment]
Funnily enough, after fixing this file, I think this is probably the better approach, except with redirect like #942

**Pull request closed without merging**
