### PR TITLE
Remove <shadow> and HTMLShadowElement

### PR DESCRIPTION
**Pull request by Elchi3**
Followup to https://github.com/mdn/browser-compat-data/pull/19293

### CODE REVIEW

**Review by estelle — APPROVED** [review]
TIL! i didn't even know there had ever been a shadow element.

**Comment by Graywolf9** [comment]
Hi! I just have the small doubt about if there is no needed a redirect

This is what @teoli2003 said in this PR https://github.com/mdn/content/pull/25352#issuecomment-1471361195

```
In general, we shouldn't delete a page without adding a redirect–unless it is a clear error
```

**Comment by Elchi3** [comment]
Where to redirect to?

**Comment by Graywolf9** [comment]
It was just a doubt to know how the process works, but I think it could be to:
- `<slot>`
- WebComponents
- Shadow DOM

**Pull request merged**
