### PR TITLE
Drop mention of frameborder from “other embedding technologies” doc

### PR DESCRIPTION
**Pull request by sideshowbarker**
Fixes https://github.com/mdn/content/issues/6411

### CODE REVIEW

**Comment by Elchi3** [comment]
Thanks! I wonder if the page should talk about the border, though. I suspect the border is unwanted in most cases and there should be a note or a pointer how to get rid of it?

**Review by rachelandrew — APPROVED** [review]

**Comment by rachelandrew** [comment]
> Thanks! I wonder if the page should talk about the border, though. I suspect the border is unwanted in most cases and there should be a note or a pointer how to get rid of it?

I would have thought at this point most people would just use CSS without thinking about it? Not sure it needs a special mention.

**Comment by Elchi3** [comment]
I guess I'm assuming beginners whenever we touch learning area content. Was CSS introduced in a learning module before this one? Just a thought, though. Feel free to merge without my nit :)

**Comment by rachelandrew** [comment]
The complete basics stuff (which comes earlier if you were following this in sequence) covers CSS, but I don't think we do much in the way of CSS within the HTML part, so it might be a bit odd to start going into it for one thing.

**Comment by sideshowbarker** [comment]
Yeah, since the text says:

> This example includes the basic essentials needed to use an `<iframe>`

…then I guess that among the essential things developers should be familiar with is the fact that unless they use CSS `border: none`, browsers will display the `iframe` with a border (which they probably don’t want).

So I just now pushed an update which shows that and documents it.

**Comment by sideshowbarker** [comment]
> The complete basics stuff (which comes earlier if you were following this in sequence) covers CSS, but I don't think we do much in the way of CSS within the HTML part, so it might be a bit odd to start going into it for one thing.

Yeah I’m fine with it either way — the commit I just added doesn’t explicitly mention CSS but instead just hyperlinks `border: none` to https://developer.mozilla.org/en-US/docs/Web/CSS/border. So maybe kind of avoids the need to go into the details any further.

**Review by Elchi3 — APPROVED** [review]
Very nice, thank you! 👍

**Pull request merged**
