### PR TITLE
Django - fix up model diagram to match code

### LINKED ISSUE #4495: UML for Django Models tutorial is out of date
URL:
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Models

Issue:
The UML at the top is not the same as the model.
The BookInstance model has a field for "imprint", for example.

### PR DESCRIPTION
**Pull request by hamishwillee**
Fixes #4495

Adds borrower and imprint to the bookinstance in UML. Note that this replaces the PNG image as an SVG to ease future editing (i.e. via inkscape)

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
LGTM; let's merge this.

**Comment by chrisdavidmills** [comment]
Ah. It wants you to run --save-compression on the SVG.

**Comment by hamishwillee** [comment]
@chrisdavidmills Isn't that a bug? How can you compress a vector diagram?

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills Isn't that a bug? How can you compress a vector diagram?

LOL, that's a good point! Can you file an issue on Yari?

**Comment by peterbe** [comment]
This topic first came up in https://github.com/mdn/yari/issues/1678
In the case of a little `.svg` file, it might feel academic and arbitrary. But the topic is interesting. It could be a binary Photoshop source/project file. So it might be smart to upload the original/source files somewhere so if the article author's laptop is run over by a bus.

**Comment by peterbe** [comment]
> @chrisdavidmills Isn't that a bug? How can you compress a vector diagram?

A vector diagram is an XML file. There are whitespace and quotations inside that can be optimized. 
So to make this PR pass you'll have to run the compress command that the error hints about.

**Comment by Ryuno-Ki** [comment]
Plus, tools like Photoshop tend to add `id` attributes for layers that are not used for anything within the SVG.
Those tools might not catch these instances.

**Comment by hamishwillee** [comment]
Yes exactly - as per https://github.com/mdn/yari/issues/1678 the problem I am trying to solve in this case is managing source files to ease editing. I did it in this case because I could no longer modify the png manually - so created in lucidchart, and was planning to do future edits in inkscape. 

On Friday I will test if this is still editable after minification. If so that will fix this case. IMO this is still worth discussing/resolving though.

**Comment by peterbe** [comment]
> Yes exactly - as per [mdn/yari#1678](https://github.com/mdn/yari/issues/1678) the problem I am trying to solve in this case is managing source files to ease editing. I did it in this case because I could no longer modify the png manually - so created in lucidchart, and was planning to do future edits in inkscape.

I think it's a worthwhile discussion to have. 
I know nothing about Lucidchart or Inkscape but I've seen it many times where an employee built some graph, exported a PNG (or something), puts that into project. Then time passes and that exported graph is now out of date but that employee has left the project. 
So I'm interested in solutions to that problem. A solution that is sustainable but can never bloat the git repo with files that aren't relevant for building the site. 
Nothing urgent, but ideas welcome.

**Comment by Ryuno-Ki** [comment]
Perhaps worth to pick this situation up in https://github.com/mdn/yari/discussions/3652, too?

**Comment by hamishwillee** [comment]
@chrisdavidmills I have compressed the svg image and merged. 
FYI The flaw checker was showing an error because learn docs all have a list of modules in the set at the end. I have fixed this up by making the current page link into bold. This is better anyway since it provides the context of the current page in the list of modules.

**Comment by hamishwillee** [comment]
@peterbe Will continue the discussion https://github.com/mdn/content/pull/4505#issuecomment-828683352 elsewhere. But in summary, I fully agree w.r.t. image compression being important - these things can quickly get out of hand.

**Pull request merged**
