### PR TITLE
remove the redundant title

### PR DESCRIPTION
**Pull request by yin1999**
#### Summary

This is a part of example, so remove the `## Nesting counters`.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by yin1999** [comment]
Seems the `Basic example: reversed counter` example is broken, I'm not sure about that @teoli2003

**Comment by teoli2003** [comment]
Looks good to me, am I missing something?

Capture d’écran 2022-06-09 à 14 21 40

**Comment by teoli2003** [comment]
Maybe you are using Chrome:
Capture d’écran 2022-06-09 à 14 22 57

**Comment by yin1999** [comment]
> Maybe you are using Chrome: Capture d’écran 2022-06-09 à 14 22 57

Oh, yes. I'm using Chrome. Thanks

**Pull request merged**
