### PR TITLE
fix: Learn/Performance/perceived_performance slug

### PR DESCRIPTION
**Pull request by nschonni**
Was lowercase causing flaws to change a bunch of files

### CODE REVIEW

**Comment by nschonni** [comment]
@peterbe ran into a crash here because the end file is the same as the source
```
$ yarn content move Learn/Performance/perceived_performance Learn/Performance/Perceived_performance
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/tool/cli.js move Learn/Performance/perceived_performance Learn/Performance/Perceived_performance
Will move 1 documents from Learn/Performance/perceived_performance to Learn/Performance/Perceived_performance for en-US
Learn/Performance/perceived_performance → Learn/Performance/Perceived_performance
√ Proceed? ... yes
Error running git mv,files\en-us\learn\performance\perceived_performance,files\en-us\learn\performance\perceived_performance
<Buffer 66 61 74 61 6c 3a 20 63 61 6e 20 6e 6f 74 20 6d 6f 76 65 20 64 69 72 65 63 74 6f 72 79 20 69 6e 74 6f 20 69 74 73 65 6c 66 2c 20 73 
6f 75 72 63 65 3d ... 139 more bytes>

error: Cannot read property 'toString' of undefined

error Command failed with exit code 1.
```
Not sure if it's worth spinning up a Yari issue

**Review by chrisdavidmills — COMMENTED** [review]
These changes look OK, but I'm wondering if I shouldn't merge it yet in light of the crash?

**Comment by nschonni** [comment]
I don't think it needs to block on the failure, but I'll just outline the steps in case you decide there is a follow up tool issue:
1. Ran move
1. Tool crashed
   - File updated with slug change
   - wikihistory had deleted entry and added new one at bottom of file
   - No change to redirects, but makes sense since a casing change shouldn't need a redirect
1. Manual fixed the wikihistory and committed

**Comment by peterbe** [comment]
I'll take a look.

**Comment by peterbe** [comment]
Yeah, let's not merge this yet. I have a fix in Yari coming. Watch this space @nschonni !

**Comment by nschonni** [comment]
OK, but do you think the Yari fix will change what the actual changed files are?

**Comment by peterbe** [comment]
> OK, but do you think the Yari fix will change what the actual changed files are?

Not entirely sure. What might be missing is a redirect entry. But it's actually somewhat related to the other bugs you encountered. Of which I'm working on with @fiji-flo in Slack.

**Comment by peterbe** [comment]
For the record, I have a draft of some fixes here: https://github.com/mdn/yari/pull/2656

**Comment by nschonni** [comment]
Yeah, I wouldn't think it "should" get a redirect since the URLs on MDN aren't currently case sensitive.
EX: 
- https://developer.mozilla.org/en-us/docs/web/api/xrrigidtransform/matriX
- https://developer.mozilla.org/en-us/docs/web/api/xrrigidtransform/matrix

They may have been in the past though under the MediaWiki setup looking at this question https://webmasters.stackexchange.com/questions/90339/why-are-urls-case-sensitive

**Comment by peterbe** [comment]
Right. Confirmed. The redirect isn't worth keeping if all it does is changing case. 
Go ahead with this PR.

**Comment by nschonni** [comment]
@chrisdavidmills  ping

**Review by chrisdavidmills — APPROVED** [review]

**Pull request merged**
