### PR TITLE
Delete deprecated macros page

### LINKED ISSUE #22124: Deprecated macros page may be removed
Since https://github.com/mdn/content/pull/22104, the deprecated macros page has no content. It might be a good idea to remove this entirely.

### PR DESCRIPTION
**Pull request by dawei-wang**
Fixes mdn/content#22124

### CODE REVIEW

**Review by Elchi3 — CHANGES_REQUESTED** [review]
Thanks for your PR!

In order to delete pages, you need to use the CLI command. See https://github.com/mdn/content/blob/main/CONTRIBUTING.md#deleting-a-document

Also, https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Macros still links to this page. Please remove the last sentence on that page.

**Comment by dawei-wang** [comment]
@Elchi3 I followed the steps in the CONTRIBUTING guide to use the CLI command to delete files but it doesn't seem to perform any of the other actions e.g. updating the _wikihistory file-it only deletes the file I specified. Any idea how to fix this issue. Thanks.

**Comment by Elchi3** [comment]
Does it say anything?
Did you re-add the file and then delete it with the command?

**Comment by dawei-wang** [comment]
My terminal says the following after typing in yarn content delete "MDN/Writing_guidelines/Page_structures/Macros/Deprecated_macros":

`warning ..\..\package.json: No license field
$ env-cmd --silent cross-env CONTENT_ROOT=files yari-tool delete mdn/Writing_guidelines/Page_structures/Macros/Deprecated_macros
Will remove 1 documents:
mdn/Writing_guidelines/Page_structures/Macros/Deprecated_macros
Deleting without a redirect. Consider using the --redirect option with a related page instead.
? Proceed? Yes
Moved 1 documents.
Done in 20.32s.

git add .

git commit -m "Delete Deprecated macros pages"
→ No staged files found.
[delete-deprecated-macros-page-1 48f916f755] Delete Deprecated macros pages
 1 file changed, 12 deletions(-)
 delete mode 100644 files/en-us/mdn/writing_guidelines/page_structures/macros/deprecated_macros/index.md`
I was expecting the _wikihistory file to be staged at least.

**Comment by dawei-wang** [comment]
I added the file back in by pulling from upstream first

**Comment by Elchi3** [comment]
Thanks for double checking and sorry for the confusion. I guess this is alright then. I don't see the file mentioned in the redirects file nor in wikihistory, so probably it was never in there.

**Review by Elchi3 — APPROVED** [review]

**Comment by dawei-wang** [comment]
No problem

**Pull request merged**
