### PR TITLE
Make clear: typed arrays can only be copy-constructed from same type

### LINKED ISSUE #7592: Issue with "BigInt64Array() constructor": `new BigInt64Array( new Int32Array(1) )` is not allowed
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array/BigInt64Array

Note: this issue applies to the constructors for all TypedArrays.  I picked this page because the problem is a little easier to describe for `BigInt64`s.

#### What information was incorrect, unhelpful, or incomplete?

All TypedArray constructors claim they can be constructed from "an object of any of the typed array types (such as `Int32Array`)".  If I'm reading the spec correctly, this is the behaviour it expects.  In practice, `BigInt64` and `BigUint64` typed arrays are not compatible with other types (see below for examples).

#### Specific section or headline?

Syntax > Parameters > typedArray > "an object of any of the typed array types (such as `Int32Array`)"

Alternatively, the page is missing a section discussing the deviation between the spec and observed behaviour.

#### What did you expect to see?

The *Syntax > Parameters > typedArray* section of all TypedArray constructors should indicate that `Big*` parameters are not accepted for non-`Big*` constructors, and vice versa.

and/or

A new section should be added discussing this issue.

#### Did you test this? If so, how?

Testing in the Firefox console shows this is always incompatible:

    >> new Int32Array( new BigInt64Array(0) )
    Uncaught TypeError: BigInt64Array elements are incompatible with Int32Array

    >> new Int32Array( new BigInt64Array(1) )
    Uncaught TypeError: BigInt64Array elements are incompatible with Int32Array

    >> new BigInt64Array( new Int32Array(0) )
    Uncaught TypeError: Int32Array elements are incompatible with BigInt64Array

    >> new BigInt64Array( new Int32Array(1) )
    Uncaught TypeError: Int32Array elements are incompatible with BigInt64Array

Testing in node shows that only non-empty TypedArrays cause errors:

    $ node
    Welcome to Node.js v12.21.0.
    Type ".help" for more information.
    > new Int32Array( new BigInt64Array(0) )
    Int32Array(0) []
    > new Int32Array( new BigInt64Array(1) )
    Uncaught TypeError: Cannot convert a BigInt value to a number
        at new Int32Array (<anonymous>)
    > new BigInt64Array( new Int32Array(0) )
    BigInt64Array(0) []
    > new BigInt64Array( new Int32Array(1) )
    Uncaught TypeError: Cannot convert 0 to a BigInt
        at new BigInt64Array (<anonymous>)
    > 

(Chromium's console output is similar to node)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/bigint64array/bigint64array`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array/BigInt64Array
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/bigint64array/bigint64array/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

### PR DESCRIPTION
**Pull request by sideshowbarker**
Fixes https://github.com/mdn/content/issues/7592

### CODE REVIEW

**Comment by bakkot** [comment]
Ah, sorry, I should have been clearer: you can construct any Big- array from any other Big- array, and any non-Big- array from any other non-Big- array; they don't need to be _exactly_ the same type. It's just mixing Big- with non-Big- which fails. So `new Int16Array(new Int32Array(1))` works, as does `new BigInt64Array(new BigUint64Array(1))`.

**Comment by sideshowbarker** [comment]
> Ah, sorry, I should have been clearer: you can construct any Big- array from any other Big- array, and any non-Big- array from any other non-Big- array; they don't need to be _exactly_ the same type. It's just mixing Big- with non-Big- which fails. So `new Int16Array(new Int32Array(1))` works, as does `new BigInt64Array(new BigUint64Array(1))`.

oops, yeah — I see you were actually pretty clear about; I just didn’t read carefully enough. Will fix is and push an update to the branch.

**Comment by bakkot** [comment]
> I see you were actually pretty clear about

(I wasn't originally, I re-read the comment and realized it was misleading and edited it, and you probably read my original misleading version.)

**Comment by Elchi3** [comment]
> Will fix is and push an update to the branch.

ping @sideshowbarker

**Comment by sideshowbarker** [comment]
Sorry for having neglected this one for so long. I’ll make time this weekend to try to wrap it up.

**Comment by Elchi3** [comment]
@sideshowbarker ping :) Or do you want someone else to take over?

**Comment by himanshugarg** [comment]
Sorry @sideshowbarker for stealing this one from you. Hope you weren't on it already.

**Comment by sideshowbarker** [comment]
> Sorry @sideshowbarker for stealing this one from you.

Not at all. Thanks extremely much for picking it up — I really appreciate it, and very glad it’s finally resolved.

**Pull request closed without merging**
