### PR TITLE
content-visibility auto (#23555 fixes)

### PR DESCRIPTION
**Pull request by dipikabh**
### Description

This is a copy of Dave's pull request https://github.com/mdn/content/pull/23555. Adding my changes on top to incorporate the review comment fixes while Dave is away.

### Motivation

This content update is related to Firefox release work. [BCD](https://github.com/mdn/browser-compat-data/pull/18627) and [release notes](https://github.com/mdn/content/pull/23556) for this property are already updated and merged. Opening this PR to ensure that content also reflects the latest updates to the CSS property.

Copying @estelle who reviewed the original pull request.

### CODE REVIEW

**Comment by dipikabh** [comment]
Hi @estelle, since Dave is away and this is a release-related content update that needs to be merged, I am taking up fixing your review comments on https://github.com/mdn/content/pull/23555. I have fixed all but two (Dave can probably address those up when he's back). Hoping we can land this quickly. Thanks!

**Comment by dipikabh** [comment]
@Rumyra, @bsmth - would appreciate one of you taking a look to get this merged. Thanks!

**Comment by bsmth** [comment]
Taking a look now 👀

**Review by bsmth — APPROVED** [review]
Nice, thank you 🙌🏻

**Pull request merged**
