### PR TITLE
Move Accessibility section above Examples for CSS pages

### PR DESCRIPTION
**Pull request by mcaskill**
### Description

Moves Accessibility section above Examples for CSS Function, Property, and Selector pages. Does not change the content of the section.

### Motivation

Bring pages in line with template change from mdn/content#34984, as agreed in [github.com/orgs/mdn/discussions/430](https://github.com/orgs/mdn/discussions/430#discussioncomment-6633135)

### Additional details

Full discussion thread: [github.com/orgs/mdn/discussions/430](https://github.com/orgs/mdn/discussions/430)

Many pages already had their Accessibility section above Examples or other sections above it.

The following pages and areas have been ignored since they do not follow the CSS page templates:

* [CSS Layout cookbook](https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook)
* [CSS flag `!important`](./files/en-us/web/css/important/index.md)
* [CSS media feature `forced-colors`](./files/en-us/web/css/@media/forced-colors/index.md)

### Related issues and pull requests

* Follow-up to: mdn/content#34984
* Similar changes to HTML: mdn/content#34007

### CODE REVIEW

**Comment by estelle** [comment]
Thank you for suggesting this contribution. 

I did a search of live pages, and HTML element pages use the heading "Accessibility" while CSS pages and HTML attributes use the heading "Accessibility concerns". So we should not be dropping the "concerns" on these CSS pages.

**Comment by estelle** [comment]
> Thank you for suggesting this contribution.
> 
> I did a search of live pages, and HTML element pages use the heading "Accessibility" while CSS pages and HTML attributes use the heading "Accessibility concerns". So we should not be dropping the "concerns" on these CSS pages.

I'll ping @dipikabh, just in case I am wrong.

**Comment by mcaskill** [comment]
@estelle Hello, thank you for reviewing this pull request. The section title change is in accordance with the decisions taken in the aforementioned discussion and related pull requests.

If what was decided has changed, I can revert the renaming of section titles and contribute a new pull request for HTML pages.

**Comment by dipikabh** [comment]
> I'll ping @dipikabh, just in case I am wrong.

Hi @estelle, we are indeed moving ahead with changing "Accessibility concerns" to "Accessibility" across HTML and CSS pages, as mentioned in these comments ([this](https://github.com/orgs/mdn/discussions/430#discussioncomment-6562096) and [this](https://github.com/orgs/mdn/discussions/430#discussioncomment-6562208)) of the discussion. The idea is to expand the scope of the section to include guidelines (like best practices or tips) that are not necessarily "concerns".

**Review by estelle — APPROVED** [review]
Thank you. 
Also, congratulations on your first merged MDN content PR. 
Welcome to the team!

**Pull request merged**
