### PR TITLE
Correct heading description in Array.p.slice() doc

### PR DESCRIPTION
**Pull request by sideshowbarker**
This is a follow-up fix to https://github.com/mdn/content/pull/1351

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thank you @sideshowbarker !

Do you know if we need to keep the heading ID in sync with the title? Back in the Wiki days the ID got generated (and I guess in a Markdown future the same will happen) so I guess it doesn't matter if they diverge in this interim period. And it seems inevitable that they will diverge anyway if keeping them in sync is a manual process. Still, it bothers me to see them diverge.

@chrisdavidmills , any views here?

**Comment by chrisdavidmills** [comment]
@wbamberg I'm not convinced that having the headings in the source is really useful at all, for exactly the reasons you state.

However, none of this is currently decided, so just for now I think we should keep the IDs in sync with the headings.

**Comment by sideshowbarker** [comment]
> Do you know if we need to keep the heading ID in sync with the title?

I am pretty sure we don’t need to. @peterbe can confirm — but since Yari generates the heading IDs and overwrites whatever explicit ID value a heading might have, then as far as I can see, that means it doesn’t matter whether we keep the heading IDs in sync or not.

> And it seems inevitable that they will diverge anyway if keeping them in sync is a manual process.

Right — to, trying to maintain the heading IDs manually in the source and keep them in sync seems kind of futile and not worth requiring authors to worry about.

> Still, it bothers me to see them diverge.

I agree it’s bothersome. The solution I’d propose is that we adopt a policy that when we edit or review patches/PRs that include heading changes, we remove the IDs as part of the PR. That eliminates the problem of trying to keep them in sync. (And to be clear, if we remove a heading ID, Yari will still automatically generate an ID for that heading in the published/rendered article.)

**Comment by sideshowbarker** [comment]
> so just for now I think we should keep the IDs in sync with the headings

OK, I made it so in 211ec7a.

(And posted my previous comment before I’d seen @chrisdavidmills’s comment — so, to be clear, I’m happy to go along with whatever the guidance is; and at this point, the guidance is that we keep them in sync, so I’m fine with that.)

**Review by wbamberg — APPROVED** [review]
Thanks for tolerating my pedantry @sideshowbarker !

**Comment by peterbe** [comment]
If you type in: `<h3>Some &amp _special_ stuff</h3>` in the raw HTML, it renders out as:
```html
<h3 id="some__special__stuff">
  <a href="#some__special__stuff" title="Permalink to Some &amp; _special_ stuff">
    Some &amp; _special_ stuff</a></h3>
```

But if you opt to manually type in an `id`, like: `<h3 id="basketball">Some &amp _special_ stuff</h3>` the set ID is respected and you end up with:
```html
<h3 id="basketball">
  <a href="#basketball" title="Permalink to Some &amp; _special_ stuff">
    Some &amp; _special_ stuff</a></h3>
```

That's all fine. However, it starts to matter if you depend on this ID. E.g.

```html
<h3>Peter Bengtson</h3>
{{LiveSample('peter_bengtson')}}
```
That'll work. But then you realize your typo and change it to:
```diff
-<h3>Peter Bengtson</h3>
+<h3>Peter Bengtsson</h3>
{{LiveSample('peter_bengtson')}}
```
Now, you managed to break the `LiveSample` macro in a subtle way. 

I'd need to think it over a bit, but in general I think it's a mistake to have any IDs hardcoded. It's a waste of your precious time and computers can do it for you. But it's a powerful tool when you want to depend on it for something or perhaps don't want the translated content's URLs to break. E.g. https://developer.mozilla.org/ja/docs/Web/HTML/Element/video#see_also wouldn't work if the translated HTML the Japenese deal with was: `<h2>See also</h2>`. So in that sense, it's good that raw HTML source sets a title. 

But that'll be a future challenge when we go to Markdown. And what's so bad about a URL like https://developer.mozilla.org/ja/docs/Web/HTML/Element/video#%E9%96%A2%E9%80%A3%E6%83%85%E5%A0%B1

**Comment by wbamberg** [comment]
Oh so it appears as if heading IDs *are not* regenerated from the heading text?

>  I think it's a mistake to have any IDs hardcoded

I agree. In a Markdown future, I think heading IDs should always be generated from the heading text and the ID should not appear in the source at all. A big part of moving to Markdown anyway is to stop people from having to care about things like this.

> And what's so bad about a URL like https://developer.mozilla.org/ja/docs/Web/HTML/Element/video#%E9%96%A2%E9%80%A3%E6%83%85%E5%A0%B1

Right, I agree. I think translators will anyway want to localize URLs when it's appropriate (i.e. when the URL contains natural language-y things like https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics), so there's no general expectation that just switching the locale part of the URL will work anyway. I remember discussing this with @SphinxKnight back in the day.

The only place I know this breaks stuff is live samples, that rely on the macro argument matching the ID, and we often saw bugs like this, where people translated the page, including the headings, then the IDs changed accordingly and the macro stopped being able to find the example. And our response was generally "update the macro argument". Pretty grim.

As you say we have to resolve this in Markdown-land. For that I think we can simplify the specification for live samples so they are not dependent on IDs.

**Comment by peterbe** [comment]
For the record, I think live samples can be saved in a better way. Instead of using an ID that's expected to be a `<div id="THIS">` you just create a sub-folder, in the current folder, called `THIS` and in it you create files like `THIS/sample.css` and `THIS/sample.js` or something. Sounds familiar? :)

**Pull request merged**
