### PR TITLE
New "revert-layer" keyword page

### PR DESCRIPTION
**Pull request by dipikabh**
#### Summary

A new global keyword was introduced in FF97, the `revert-layer` keyword.
This keyword was added to the existing list of other global keywords:`initial`, `inherit`, `unset`, and `revert`.

This PR adds the documentation for the `revert-layer` keyword.

#### Supporting details

https://bugzilla.mozilla.org/show_bug.cgi?id=1699220
https://drafts.csswg.org/css-cascade-5/#revert-layer

#### Related issues

Content issue tracking this work: https://github.com/mdn/content/issues/13373
PR for updating "Specifications" and "Browser compatibility" sections: https://github.com/mdn/browser-compat-data/pull/15524

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

### CODE REVIEW

**Comment by Rumyra** [comment]
I need a bit more time on this to go over the examples - I'll do that first thing tomorrow 👍

**Comment by dipikabh** [comment]
Thanks @Rumyra for your valuable feedback! I replaced the `<div>` example to the `<li>` example like you suggested.

To show multiple scenarios, I added two lists in the example. That has made the page long. I hope it has not made the writeup more confusing. Let me know what you think. 

I'd also appreciate of you could give the entire page a readthrough again because I tweaked phrases here and there for better clarity.

**Review by Rumyra — APPROVED** [review]
This is so so good!! I'm pressing the big green button

**Comment by dipikabh** [comment]
> This is so so good!! I'm pressing the big green button

Yay!

@Rumyra, thanks for all your guidance before and during the writing of this page!

**Pull request merged**
