### PR TITLE
docs(relnotes): Remove 'Adapting XUL Applications for Firefox 1.5' guide with redirect

### LINKED ISSUE #32558: Remove "See also Adapting XUL Applications for Firefox 1.5." and related page
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/1.5

### What specific section or headline is this issue about?

XUL changes

### What information was incorrect, unhelpful, or incomplete?

The page https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/1.5/Adapting_XUL_Applications_for_Firefox_1.5 can be deleted

### What did you expect to see?

Fewer dead links

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/firefox/releases/1.5`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/1.5
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/1.5/index.md
* Last commit: https://github.com/mdn/content/commit/c75b7911b520a770c081003cf0e3baaf7034adaf
* Document last modified: 2023-10-13T13:06:04.000Z

</details>

### PR DESCRIPTION
**Pull request by bsmth**
### Description

Fixes #32558

### Additional details

Removed using:

```bash
 yarn content delete "Mozilla/Firefox/Releases/1.5/Adapting_XUL_Applications_for_Firefox_1.5" --redirect "Mozilla/Firefox/Releases/1.5"
```

### CODE REVIEW

**Review by dipikabh — CHANGES_REQUESTED** [review]
Changes look good, @bsmth.

I guess the change to remove the "See also..." sentence in [XUL and Extension Developers](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/1.5#xul_and_extension_developers) can also be included in this PR?

**Comment by bsmth** [comment]
Thanks @dipikabh - I've removed in most recent commit, I wasn't sure if we want to leave it red like the other links. This doesn't look so nice in the current state:

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/1.5#xul_and_extension_developers

Maybe the links should be removed/converted to regular text as they're not going to be fixed any time soon.

**Review by dipikabh — APPROVED** [review]
Thanks! I agree, we should just remove all the broken links on this page. Probably also not worth the effort to look for Firefox source docs to link to (I looked for `XPCNativeWrapper` on MDN and outside of release docs, there is only 1 reference, on the page [Share objects with page scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts)). 

Approving this one, so you have the option to remove the broken links here or in a new PR if you want to dig further.

**Review by hamishwillee — APPROVED** [review]
Looks good to me too.

**Comment by bsmth** [comment]
Thanks, both! I will merge this shortly

> not worth the effort to look for Firefox source docs to link to

This is a good follow-up PR I think, I would check if there is existing new URLs for each broken link on this page, update it if so, and convert to regular text if not.

**Pull request merged**
